/* Akademik Takvim — mevcut veri/yükleme/jest akışı korunur */
(function(){if(!document.querySelector('link[data-akademik-takvim-modern]')){const l=document.createElement('link');l.rel='stylesheet';l.href='css/akademik-takvim-modern.css?v=1';l.dataset.akademikTakvimModern='1';document.head.appendChild(l)}})();
let _akademikTakvimVeri=null;
const AKADEMIK_TAKVIM_ONBELLEK_ANAHTARI='akademikTakvimOnbellek';
function _akademikTakvimOnbellekOku(){try{const h=localStorage.getItem(AKADEMIK_TAKVIM_ONBELLEK_ANAHTARI);return h?JSON.parse(h):null}catch(e){return null}}
function _akademikTakvimOnbellegeYaz(storagePath,dataUri){try{localStorage.setItem(AKADEMIK_TAKVIM_ONBELLEK_ANAHTARI,JSON.stringify({storagePath,dataUri}))}catch(e){}}
function _akademikTakvimGorseliOnbellekleAl(veri){if(!veri||!veri.gorselUrl||!veri.storagePath)return;fetch(veri.gorselUrl).then(r=>r.blob()).then(blob=>new Promise((resolve,reject)=>{const o=new FileReader();o.onloadend=()=>resolve(o.result);o.onerror=reject;o.readAsDataURL(blob)})).then(dataUri=>_akademikTakvimOnbellegeYaz(veri.storagePath,dataUri)).catch(()=>{})}
function akademikTakvimBaglantisiKur(){AkademikTakvimService.dinle(v=>{_akademikTakvimVeri=v;if(document.getElementById('akademikTakvimOverlay'))_akademikTakvimIcerigiCiz()})}
function akademikTakvimAc(){const eski=document.getElementById('akademikTakvimOverlay');if(eski)eski.remove();const ov=document.createElement('div');ov.id='akademikTakvimOverlay';ov.style.cssText='position:fixed;inset:0;z-index:9400;display:flex;flex-direction:column;';document.body.appendChild(ov);document.body.classList.add('modal-open');if(typeof _pullToRefreshAyarla==='function')_pullToRefreshAyarla(false);const adminMi=typeof AKTIF_KULLANICI!=='undefined'&&AKTIF_KULLANICI&&AKTIF_KULLANICI.admin===true;ov.innerHTML=`<div class="at-topbar"><button class="at-back" onclick="akademikTakvimKapat()" aria-label="Geri">‹</button><div class="at-title"><b>Akademik Takvim</b><small>Okul çalışma takvimi</small></div><div>${adminMi?`<input type="file" id="akademikTakvimDosyaInput" accept="image/*" style="display:none" onchange="akademikTakvimDosyaSecildi(this.files[0])"><button class="at-upload" onclick="document.getElementById('akademikTakvimDosyaInput').click()">🖼️ ${_akademikTakvimVeri?'Değiştir':'Yükle'}</button>`:''}</div></div><div id="akademikTakvimIcerik"></div><div class="at-help">↔ İki parmakla yakınlaştırın · Çift dokunuşla hızlı yakınlaştır</div>`;_akademikTakvimIcerigiCiz()}
function akademikTakvimKapat(){const ov=document.getElementById('akademikTakvimOverlay');if(ov)ov.remove();document.body.classList.remove('modal-open');if(typeof _pullToRefreshAyarla==='function')_pullToRefreshAyarla(true)}
function _akademikTakvimIcerigiCiz(){const el=document.getElementById('akademikTakvimIcerik');if(!el)return;if(!_akademikTakvimVeri||!_akademikTakvimVeri.gorselUrl){el.innerHTML='<div class="at-empty"><b>Akademik takvim yüklenmemiş</b>Yönetici bir takvim görseli yüklediğinde burada tam ekran görüntülenecek.</div>';return}const onbellek=_akademikTakvimOnbellekOku();const kaynak=onbellek&&onbellek.storagePath===_akademikTakvimVeri.storagePath?onbellek.dataUri:_akademikTakvimVeri.gorselUrl;if(kaynak===_akademikTakvimVeri.gorselUrl)_akademikTakvimGorseliOnbellekleAl(_akademikTakvimVeri);el.innerHTML=`<img id="akademikTakvimGorsel" src="${kaynak}" alt="Akademik Takvim">`;_akademikTakvimJestBagla()}
function _akademikTakvimJestBagla(){const govde=document.getElementById('akademikTakvimIcerik'),img=document.getElementById('akademikTakvimGorsel');if(!govde||!img)return;let zoom=1,panX=0,panY=0,baslangicMesafe=0,baslangicZoom=1,surukleniyor=false,surukleBasX=0,surukleBasY=0,panBasX=0,panBasY=0,sonTapZamani=0,dokunmaBirDegdi=false,dokunmaBasX=0,dokunmaBasY=0,coklu=false;const uygula=()=>img.style.transform=`translate(${panX}px, ${panY}px) scale(${zoom})`;const mesafe=(t1,t2)=>Math.hypot(t1.clientX-t2.clientX,t1.clientY-t2.clientY);govde.addEventListener('touchstart',e=>{if(e.touches.length===2){coklu=true;baslangicMesafe=mesafe(e.touches[0],e.touches[1]);baslangicZoom=zoom;surukleniyor=false}else if(e.touches.length===1){coklu=false;dokunmaBirDegdi=true;dokunmaBasX=e.touches[0].clientX;dokunmaBasY=e.touches[0].clientY;if(zoom>1.02){surukleniyor=true;surukleBasX=e.touches[0].clientX;surukleBasY=e.touches[0].clientY;panBasX=panX;panBasY=panY}}},{passive:true});govde.addEventListener('touchmove',e=>{if(e.touches.length===2){zoom=Math.min(6,Math.max(1,baslangicZoom*(mesafe(e.touches[0],e.touches[1])/baslangicMesafe)));uygula()}else if(e.touches.length===1){if(Math.abs(e.touches[0].clientX-dokunmaBasX)>10||Math.abs(e.touches[0].clientY-dokunmaBasY)>10)dokunmaBirDegdi=false;if(surukleniyor){panX=panBasX+(e.touches[0].clientX-surukleBasX);panY=panBasY+(e.touches[0].clientY-surukleBasY);uygula()}}},{passive:true});govde.addEventListener('touchend',e=>{surukleniyor=false;if(e.touches.length>0)return;if(dokunmaBirDegdi&&!coklu){const simdi=Date.now();if(simdi-sonTapZamani<300){zoom=zoom>1.02?1:2.2;panX=0;panY=0;uygula();sonTapZamani=0}else sonTapZamani=simdi}coklu=false})}
async function akademikTakvimDosyaSecildi(dosya){if(!dosya)return;const el=document.getElementById('akademikTakvimIcerik'),oncekiVeri=_akademikTakvimVeri;if(el)el.innerHTML='<div class="at-progress">Yükleniyor… <span id="akademikTakvimYuzde">%0</span></div>';try{const yeniVeri=await AkademikTakvimService.gorselYukle(dosya,yuzde=>{const y=document.getElementById('akademikTakvimYuzde');if(y)y.textContent=`%${yuzde}`},oncekiVeri);_akademikTakvimVeri=yeniVeri;_akademikTakvimIcerigiCiz();toast('Akademik takvim güncellendi.')}catch(e){if(e.message&&e.message.startsWith('depolama-siniri:'))toast(e.message.slice('depolama-siniri:'.length));else if(e.message!=='yetkisiz')toast('Yükleme hatası: '+e.message);_akademikTakvimIcerigiCiz()}}
(function haritaKutuphaneleriniYukle(){if(document.querySelector('script[data-map-libs]'))return;const s=document.createElement('script');s.src='js/map-libs.js';s.async=false;s.dataset.mapLibs='1';document.head.appendChild(s)})();
(function pdfExportKutuphaneleriniYukle(){if(document.querySelector('script[data-pdf-export-libs]'))return;const s=document.createElement('script');s.src='js/pdf-export-libs.js';s.async=false;s.dataset.pdfExportLibs='1';document.head.appendChild(s)})();
(function dokumanPdfAraclariniYukle(){if(document.querySelector('script[data-dokuman-pdf-tools]'))return;const s=document.createElement('script');s.src='js/dokuman-pdf-tools.js';s.async=false;s.dataset.dokumanPdfTools='1';document.head.appendChild(s)})();
(function nativeRaporOnizlemeyiYukle(){if(document.querySelector('script[data-native-report-preview]'))return;const s=document.createElement('script');s.src='js/native-report-preview.js';s.async=false;s.dataset.nativeReportPreview='1';document.head.appendChild(s)})();
