/* Koruk Asistan — AppLoader v40
   Tek başlangıç sahibi: Firebase + auth + lazy modüller. Tema sahibi: ShellUI.
   Tek görünürlük sahibi: PermissionService.
   Tek davranışsal düzen sahibi: AppConfig (oy_navDuzeni/uygulama).
   Modül lifecycle: aktif sayfa değişirken eski UI abonelikleri merkezi olarak kapatılır.
 */
(function(){
'use strict';
if(window.AppLoader)return;
const loaded=new Set(),loading=new Map(),registry=new Map();
let startupDone=false,initialRequested=false,accountPreparedForUid='',sessionBootstrapUid='',sessionBootstrapPromise=null;
const MODULE_GLOBALS=Object.freeze({dashboard:'DashboardModule',people:'PeopleModule',academic:'AcademicModule',management:'ManagementModule',communication:'CommunicationModule',transport:'TransportModule',documents:'DocumentsModule',tools:'ToolsModule',settings:'SettingsModule'});
const normalize=src=>String(src||'').split('?')[0].replace(/^\.\//,'');
const alreadyInDom=src=>{const n=normalize(src);return [...document.querySelectorAll('script[src]')].some(s=>normalize(s.getAttribute('src'))===n)};
function loadScript(src){const key=normalize(src);if(loaded.has(key)||alreadyInDom(src)){loaded.add(key);return Promise.resolve(key)}if(loading.has(key))return loading.get(key);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=false;s.dataset.korukLazy=key;s.onload=()=>{loaded.add(key);loading.delete(key);resolve(key)};s.onerror=()=>{loading.delete(key);reject(new Error('module-load:'+key))};document.head.appendChild(s)});loading.set(key,p);return p}
async function loadMany(files){for(const f of files||[])await loadScript(f)}
function define(name,files){registry.set(name,[...(files||[])])}
const FIREBASE_STORAGE_SDK='https://www.gstatic.com/firebasejs/10.12.2/firebase-storage-compat.js';
const isLoaded=name=>(registry.get(name)||[]).every(x=>loaded.has(normalize(x))||alreadyInDom(x));
const list=()=>[...registry.entries()].map(([name,files])=>({name,files:[...files],loaded:isLoaded(name)}));
define('dashboard',['js/modules/school-live-status.js','js/modules/dashboard.js']);
define('people',['js/modules/people.js','js/modules/people-import.js','js/modules/people-classic-ui.js','js/modules/classes-mobile-parity.js']);
define('academic',[FIREBASE_STORAGE_SDK,'js/modules/report-engine.js','js/modules/academic.js']);
define('management',['js/modules/report-engine.js','js/modules/management.js']);
define('communication',[FIREBASE_STORAGE_SDK,'js/modules/communication.js','js/modules/assistant.js']);
define('transport',['js/modules/report-engine.js','js/modules/transport.js','js/modules/transport-service-parity.js']);
define('documents',[FIREBASE_STORAGE_SDK,'js/modules/report-engine.js','js/modules/documents.js']);
define('tools',['js/modules/tools.js','js/modules/teacher-list.js','js/modules/map-ui.js','js/modules/rubric-settings.js','js/modules/rubric-tools.js']);
define('settings',['js/modules/settings.js']);

const MODULE_DEFAULTS=[{key:'dashboard',label:'Ana Sayfa',icon:'🏠',visible:true,order:10},{key:'people',label:'Öğretmen / Öğrenci',icon:'👥',visible:true,order:20},{key:'academic',label:'Akademik',icon:'📚',visible:true,order:30},{key:'management',label:'Yönetim',icon:'🗂️',visible:true,order:40},{key:'communication',label:'İletişim',icon:'💬',visible:true,order:50},{key:'transport',label:'Taşıma',icon:'🚌',visible:true,order:60},{key:'documents',label:'Doküman / Rapor',icon:'📄',visible:true,order:70},{key:'tools',label:'Araçlar',icon:'🧰',visible:true,order:80},{key:'settings',label:'Ayarlar',icon:'⚙️',visible:true,order:90}];
const DASHBOARD_DEFAULTS=[{key:'welcome',label:'Karşılama',visible:true,order:10},{key:'stats',label:'Okul Özeti',visible:true,order:20},{key:'upcoming',label:'Yaklaşanlar',visible:true,order:30},{key:'announcements',label:'Duyurular',visible:true,order:40},{key:'duty',label:'Bugünün Nöbeti',visible:true,order:50}];
function mergeRows(defaults,rows){const by=new Map((rows||[]).map(x=>[x.key,x]));return defaults.map(d=>({...d,...(by.get(d.key)||{}),key:d.key})).sort((a,b)=>Number(a.order||0)-Number(b.order||0))}
function rawConfig(){return AppStore?.data?.('appConfig')?.find?.(x=>x.id==='uygulama')||{}}
function appConfig(){const r=rawConfig();return{defaultModule:r.defaultModule||'dashboard',modules:mergeRows(MODULE_DEFAULTS,r.modules),dashboardCards:mergeRows(DASHBOARD_DEFAULTS,r.dashboardCards)}}
function moduleMeta(key){return appConfig().modules.find(x=>x.key===key)||MODULE_DEFAULTS.find(x=>x.key===key)||{key,label:key,icon:'',visible:true,order:999}}
const dashboardCards=()=>appConfig().dashboardCards;
function applyNavigation(){const nav=document.querySelector('.ka-app-nav');if(!nav)return;appConfig().modules.forEach(m=>{const b=nav.querySelector(`[data-ka-module="${m.key}"]`);if(!b)return;b.dataset.configVisible=m.visible===false?'false':'true';b.textContent=`${m.icon?m.icon+' ':''}${m.label||m.key}`;nav.appendChild(b)});PermissionService?.apply?.(nav);nav.querySelectorAll('[data-ka-module]').forEach(b=>{if(moduleMeta(b.dataset.kaModule).visible===false)b.hidden=true});const title=document.getElementById('v2ModuleTitle'),route=AppStore?.get?.('ui.route');if(title&&route)title.textContent=moduleMeta(route).label||route}
async function saveConfig(patch){const u=window.AKTIF_KULLANICI||AppStore?.get?.('session.user');if(!u?.admin)throw new Error('yetkisiz');const current=appConfig(),next={...current,...patch,id:'uygulama',guncellenmeTarihi:new Date().toISOString()};if(patch.modules)next.modules=mergeRows(MODULE_DEFAULTS,patch.modules);if(patch.dashboardCards)next.dashboardCards=mergeRows(DASHBOARD_DEFAULTS,patch.dashboardCards);await DeviceData.set('appConfig',COL.navDuzeni,'uygulama',next,{merge:false});applyNavigation();window.dispatchEvent(new CustomEvent('koruk:app-config-changed',{detail:next}));return next}
const resetConfig=()=>saveConfig({defaultModule:'dashboard',modules:MODULE_DEFAULTS,dashboardCards:DASHBOARD_DEFAULTS});
const CLASSIC_MENU_GROUPS=[
 {key:'people',label:'Öğretmen & Öğrenciler',icon:'👥',tone:'green',route:'people',items:[['Öğretmenler','👩‍🏫','people','teachers'],['Öğrenciler','🎓','people','students'],['Sınıflar','🏫','people','classes'],['Öğrenci Yoklama','☑️','tools','student-attendance'],['Öğrenci Listesi Oluşturucu','📋','tools','student-list'],['Ödev Takip Çizelgesi','✅','tools','homework'],['Not Çizelgesi','📊','tools','grades']]},
 {key:'exams',label:'Sınavlar ve Not İşlemleri',icon:'📝',tone:'violet',route:'academic',items:[['Yazılı Sınavlar','☑️','academic','written'],['Deneme Sınavları','🧪','academic','trial'],['Deneme Sonuçları','🏅','academic','results'],['Test Sonuçları','📋','academic','results'],['Ders Et. Kat. Puan Dağıtımı','📊','tools','rubric'],['Proje Değerlendirme Ölçeği','📏','tools','project']]},
 {key:'communication',label:'İletişim & Haberler',icon:'💬',tone:'red',route:'communication',items:[['Mesajlaşma','💬','communication','messages'],['Haberler','📰','communication','news'],['Duyurular','📣','communication','announcements'],['Anketler','📋','communication','polls']]},
 {key:'programs',label:'Programlar',icon:'📅',tone:'green',route:'academic',items:[['Ders Programı','📅','academic','schedule'],['Nöbet Programı','🛡️','management','duty'],['Yıllık Plan','📋','academic','plans']]},
 {key:'calendar',label:'Takvim & Notlar',icon:'📆',tone:'cyan',route:'communication',items:[['Takvim','📆','communication','calendar'],['Notlar','📒','communication','notes']]},
 {key:'transport',label:'Taşıma',icon:'🚌',tone:'violet',route:'transport',items:[['Taşıma İşlemleri','🚌','transport','services'],['Harita','🗺️','tools','map']],subLabel:'Yerleşim Araçları',subItems:[['Servis Oturma','💺','transport','busSeats'],['Sınıf Oturma','🏫','transport','classSeats']]},
 {key:'documents',label:'Döküman & Evraklar',icon:'📁',tone:'amber',route:'documents',items:[['Dökümanlar','📁','documents'],['Evrak Takibi','📄','documents','evrak'],['Mevzuat','📖','documents','mevzuat'],['Aylık İşler','🕘','management','tasks'],['Akademik Takvim','📅','academic','calendar'],['Kontrol Listeleri','📋','tools','checklists']],subLabel:'Raporlar',subItems:[['Maarif Model','🏅','tools','form-maarif'],['Belirli Gün ve Haftalar','📅','tools','form-belirli'],['ŞÖK','🛡️','tools','form-sok'],['Zümre','👥','tools','form-zumre'],['Sosyal Kulüpler','♡','tools','form-kulup'],['Rehberlik','🧭','tools','form-rehberlik'],['Yıllık Planlar & BEP Planları','📋','tools','form-bep'],['Diğer Evraklar','📁','tools','form-diger']]},
 {key:'management',label:'Personel İşleri',icon:'🧑‍💼',tone:'orange',route:'management',items:[['Personeller','🧑‍💼','management','staff'],['Maaş Değişikliği','💵','payroll'],['Tebliğ-Tebellüğ İmza Sirküsü','🔔','documents','teblig'],['Puantaj & İmza Sirküsü','🕘','management','puantaj'],['Dilekçe & İzinler','📄','management','dilekce'],['Devamsızlık Çizelgesi','📅','tools','attendance']],subLabel:'Diploma İşlemleri',subItems:[['Diploma Kayıt Talep Dilekçesi','📄','management','diploma-request'],['Diploma Okul Dilekçesi','📄','management','diploma-response']]},
 {key:'settings',label:'Ayarlar',icon:'⚙️',tone:'slate',route:'settings',items:[['Ayarlar','⚙️','settings'],['Okul Bilgileri','🏢','settings','school'],['Veriler','🗄️','settings','data'],['Kullanıcı İşlemleri','🛡️','settings','users'],['Kullanıcı İstatistikleri','📋','settings','statistics']]}
];
function applyClassicMenuGroups(){const target=window.ShellUI?.MENU_GROUPS;if(!Array.isArray(target))return false;target.splice(0,target.length,...CLASSIC_MENU_GROUPS.map(g=>({...g,items:(g.items||[]).map(x=>[...x]),subItems:(g.subItems||[]).map(x=>[...x])})));return true}
window.AppConfig={MODULE_DEFAULTS,DASHBOARD_DEFAULTS,CLASSIC_MENU_GROUPS,get:appConfig,module:moduleMeta,dashboardCards,applyNavigation,applyClassicMenuGroups,save:saveConfig,reset:resetConfig};
applyClassicMenuGroups();
function registerClassicPageRoutes(){
  if(typeof window.ShellUI?.registerPageRoute!=='function')return false;
  const diplomaRoute=type=>async({root})=>{window.ManagementModule?.unmount?.();if(!window.ReportEngine?.printReport)await loadScript('js/modules/report-engine.js');if(!window.PersonnelDocuments?.open)await loadScript('js/modules/personnel-documents.js');if(!window.PersonnelDocuments?.open)throw new Error('personnel-documents-load');return window.PersonnelDocuments.open(type,root)};
  window.ShellUI.registerPageRoute('diploma-request',diplomaRoute('request'));
  window.ShellUI.registerPageRoute('diploma-response',diplomaRoute('response'));
  return true;
}
registerClassicPageRoutes();

const PERMISSION_RANK={hidden:0,preview:1,read:2,edit:3};
const PERMISSION_CATALOG=[];
const BASE_PERMISSION_CATALOG=[['module.dashboard','Ana Sayfa','page'],['module.people','Kadrolar','page'],['module.academic','Akademik','page'],['module.management','Yönetim','page'],['module.communication','İletişim','page'],['module.transport','Taşıma','page'],['module.documents','Dokümanlar','page'],['module.tools','Araçlar','page'],['module.settings','Ayarlar','page'],['people.teachers','Öğretmenler','section'],['people.classes','Sınıflar','section'],['people.students','Öğrenciler','section'],['people.students.edit','Öğrenci düzenleme','action'],['people.attendance.edit','Yoklama düzenleme','action'],['academic.exams','Sınavlar','section'],['academic.exams.edit','Sınav düzenleme','action'],['academic.plans','Yıllık planlar','section'],['academic.schedule','Ders Programı','section'],['academic.schedule.edit','Ders Programı düzenleme','action'],['management.duty','Nöbet','section'],['management.duty.edit','Nöbet düzenleme','action'],['management.personnel','Personel','section'],['communication.messages','Mesajlaşma','section'],['communication.messages.send','Mesaj gönderme','action'],['communication.announcements','Duyurular','section'],['communication.polls','Anketler','section'],['communication.polls.edit','Anket yönetimi','action'],['communication.news','Haberler','section'],['communication.news.edit','Haber yönetimi','action'],['communication.calendar','Takvim','section'],['communication.calendar.edit','Takvim düzenleme','action'],['communication.notes','Notlar','section'],['communication.notes.edit','Not düzenleme','action'],['transport.services','Servisler','section'],['transport.services.edit','Servis düzenleme','action'],['transport.seating','Oturma planı','section'],['transport.seating.edit','Oturma planı düzenleme','action'],['transport.classSeating','Sınıf oturma planı','section'],['transport.classSeating.edit','Sınıf oturma planı düzenleme','action'],['transport.report.inspection','Denetim Formu','action'],['transport.report.monthly','Aylık Takip','action'],['documents.view','Doküman görüntüleme','section'],['documents.edit','Doküman düzenleme','action'],['documents.tracking','Evrak Takibi','section'],['documents.tracking.edit','Evrak Takibi düzenleme','action'],['tools.checklists','Kontrol Listeleri','section'],['tools.map','Harita','section'],['tools.schedules','Çizelgeler','section'],['tools.attendance','Devamsızlık','section'],['tools.gradebook','Ödev / Not','section'],['settings.school','Okul Bilgileri','section'],['settings.school.edit','Okul bilgilerini düzenleme','action'],['settings.roles','Rol Yönetimi','section'],['settings.roles.edit','Rol düzenleme','action'],['settings.users','Kullanıcı Yönetimi','section'],['settings.app','Uygulama Düzeni','section'],['settings.app.edit','Uygulama düzenini değiştirme','action']];
BASE_PERMISSION_CATALOG.forEach(([key,label,type])=>PERMISSION_CATALOG.push({key,label,type}));
const LEGACY_PERMISSION_ALIASES={'module.dashboard':['dashboard'],'module.people':['ogretmenler','siniflar','ogrenciler','yoklama'],'people.teachers':['ogretmenler'],'people.classes':['siniflar'],'people.students':['ogrenciler'],'people.students.edit':['ogrenciler','siniflar'],'people.attendance.edit':['yoklama'],'module.academic':['sinavIslemleri','yillikPlan','dersProgrami','dersSaatleri','akademikTakvim','denemeSonuclari','testSonuclari'],'academic.exams':['sinavIslemleri'],'academic.exams.edit':['sinavIslemleri'],'academic.plans':['yillikPlan'],'academic.schedule':['dersProgrami'],'academic.schedule.edit':['dersProgrami'],'module.management':['nobet','personel','periyodikIsler','ogretmenIzinleri'],'management.duty':['nobet'],'management.duty.edit':['nobet'],'management.personnel':['personel'],'module.communication':['mesajlasma','duyurular','anketler','haberler','takvim','notlar'],'communication.messages':['mesajlasma'],'communication.messages.send':['mesajlasma'],'communication.announcements':['duyurular'],'communication.polls':['anketler'],'communication.polls.edit':['anketler'],'communication.news':['haberler'],'communication.news.edit':['haberler'],'communication.calendar':['takvim'],'communication.calendar.edit':['takvim'],'communication.notes':['notlar'],'communication.notes.edit':['notlar'],'module.transport':['tasima'],'transport.services':['tasima'],'transport.services.edit':['tasima'],'transport.seating':['tasima'],'transport.seating.edit':['tasima'],'transport.classSeating':['tasima'],'transport.classSeating.edit':['siniflar','tasima'],'transport.report.inspection':['tasima'],'transport.report.monthly':['tasima'],'module.documents':['dokumanlar','evrak'],'documents.view':['dokumanlar'],'documents.edit':['dokumanlar'],'documents.tracking':['evrak'],'documents.tracking.edit':['evrak'],'module.tools':['kontrolListeleri','harita','cizelgeler','devamsizlik','odevTakip','notCizelgesi'],'tools.checklists':['kontrolListeleri'],'tools.map':['harita'],'tools.schedules':['cizelgeler'],'tools.attendance':['devamsizlik'],'tools.gradebook':['odevTakip','notCizelgesi'],'module.settings':['sistemAyarlari','kullaniciYonetimi','okulBilgileri'],'settings.school':['okulBilgileri'],'settings.school.edit':['okulBilgileri'],'settings.roles':['kullaniciYonetimi'],'settings.roles.edit':['kullaniciYonetimi'],'settings.users':['kullaniciYonetimi'],'settings.app':['sistemAyarlari'],'settings.app.edit':['sistemAyarlari']};
function permissionNormalize(value){if(value===true)return'edit';if(value===false)return'hidden';const v=String(value??'').trim().toLocaleLowerCase('tr').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');if(['gizle','hidden','none','yok'].includes(v))return'hidden';if(['onizle','onizleme','preview'].includes(v))return'preview';if(['goruntule','oku','read','readonly','salt-okunur','saltonur'].includes(v))return'read';if(['duzenle','edit','tam','full','yonet'].includes(v))return'edit';return null}
function permissionValue(obj,key){if(!obj||typeof obj!=='object')return undefined;if(Object.prototype.hasOwnProperty.call(obj,key))return obj[key];return String(key||'').split('.').reduce((node,part)=>node&&typeof node==='object'?node[part]:undefined,obj)}
function permissionKeys(key){const p=String(key||'').split('.').filter(Boolean),out=[];for(let i=p.length;i>0;i--)out.push(p.slice(0,i).join('.'));return out}
function permissionSourceLevel(source,key){for(const k of permissionKeys(key)){const n=permissionNormalize(permissionValue(source,k));if(n)return n}return null}
function legacySourceLevel(source,key){let best=null;for(const alias of LEGACY_PERMISSION_ALIASES[key]||[]){const n=permissionNormalize(permissionValue(source,alias));if(n&&(!best||PERMISSION_RANK[n]>PERMISSION_RANK[best]))best=n}return best}
function permissionSession(){return{user:window.AKTIF_KULLANICI||AppStore?.get?.('session.user')||null,role:window.AKTIF_ROL||AppStore?.get?.('session.role')||null}}
function rawPermissionLevel(key){const{user,role}=permissionSession();if(user?.admin===true)return'edit';return permissionSourceLevel(user?.yetkiler,key)||legacySourceLevel(user?.yetkiler,key)||permissionSourceLevel(role?.yetkiler,key)||legacySourceLevel(role?.yetkiler,key)||null}
function moduleNameForKey(key){const first=String(key||'').split('.')[0];return registry.has(first)?first:null}
function moduleLevel(name){const direct=rawPermissionLevel('module.'+name),{role}=permissionSession();if(direct)return direct;return role?.yetkiler&&Object.keys(role.yetkiler).length?'hidden':'edit'}
function permissionLevel(key,{fallback='edit'}={}){if(String(key).startsWith('module.'))return moduleLevel(String(key).slice(7));let level=rawPermissionLevel(key)||permissionNormalize(fallback)||'edit';const module=moduleNameForKey(key);if(module){const ceiling=moduleLevel(module);if(PERMISSION_RANK[level]>PERMISSION_RANK[ceiling])level=ceiling}return level}
const permissionCan=(key,min='read')=>PERMISSION_RANK[permissionLevel(key)]>=PERMISSION_RANK[permissionNormalize(min)||'read'];
function permissionRequire(key,min='edit'){if(!permissionCan(key,min)){const e=new Error('yetkisiz:'+key);e.code='permission-denied';throw e}return true}
function permissionApply(root=document){root.querySelectorAll?.('[data-ka-module]').forEach(el=>{const level=moduleLevel(el.dataset.kaModule);el.dataset.permissionLevel=level;el.hidden=level==='hidden'||moduleMeta(el.dataset.kaModule).visible===false});root.querySelectorAll?.('[data-ka-permission]').forEach(el=>{const min=permissionNormalize(el.dataset.kaMinLevel)||'preview',level=permissionLevel(el.dataset.kaPermission);el.dataset.permissionLevel=level;el.hidden=PERMISSION_RANK[level]<PERMISSION_RANK[min]});root.querySelectorAll?.('[data-ka-write],[data-ka-requires-edit]').forEach(el=>{const key=el.dataset.kaPermission||el.dataset.kaWrite||el.dataset.kaRequiresEdit||'module.'+(AppStore?.get?.('ui.route')||'');if('disabled'in el)el.disabled=!permissionCan(key,'edit')})}
function permissionApplyModule(name){const root=document.getElementById('v2ModuleRoot');if(!root)return moduleLevel(name);const level=moduleLevel(name);root.dataset.permissionMode=level;document.getElementById('kaPermissionPreviewNotice')?.remove();if(level==='preview'){const n=document.createElement('div');n.id='kaPermissionPreviewNotice';n.className='ka-card';n.innerHTML='<div class="ka-card__body"><strong>Önizleme modu</strong><div class="ka-muted">Bu sayfayı görebilirsiniz ancak değişiklik yapamazsınız.</div></div>';root.prepend(n)}permissionApply(root);return level}
function permissionRefresh(){applyNavigation();permissionApply(document);const r=AppStore?.get?.('ui.route');if(r)requestAnimationFrame(()=>permissionApplyModule(r));return true}
window.PermissionService={LEVELS:Object.freeze({...PERMISSION_RANK}),catalog:PERMISSION_CATALOG,aliases:Object.freeze({...LEGACY_PERMISSION_ALIASES}),normalize:permissionNormalize,level:permissionLevel,moduleLevel,can:permissionCan,canEdit:k=>permissionCan(k,'edit'),isPreview:k=>permissionLevel(k)==='preview',require:permissionRequire,apply:permissionApply,applyModule:permissionApplyModule,refresh:permissionRefresh};
window.gorebilir=window.gorebilir||((key)=>PermissionService.can(key,'read'));window.duzenleyebilir=window.duzenleyebilir||((key)=>PermissionService.can(key,'edit'));window.kullaniciYonetimiYetkisiVar=window.kullaniciYonetimiYetkisiVar||(()=>permissionSession().user?.admin===true||PermissionService.can('settings.users','edit'));
async function load(name){if(!registry.has(name))throw new Error('module-not-defined:'+name);if(moduleMeta(name).visible===false||moduleLevel(name)==='hidden'){const e=new Error('module-forbidden:'+name);e.code='permission-hidden';throw e}await loadMany(registry.get(name));if(name==='academic'||name==='communication'||name==='documents')window.firebaseStorageHazirla?.();window.dispatchEvent(new CustomEvent('koruk:module-ready',{detail:{name,permissionLevel:moduleLevel(name)}}));requestAnimationFrame(()=>permissionApplyModule(name));return name}
function applyTheme(theme,opts={}){return window.ShellUI?.applyTheme?.(theme,opts)??theme}
function toggleTheme(){return window.ShellUI?.toggleTheme?.()}
function startPlatform(){if(startupDone)return true;startupDone=true;if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}),{once:true});try{if(typeof firebaseyiBaslat!=='function'||!firebaseyiBaslat())return false;authDinleyiciKur?.();return true}catch(e){console.error('[AppLoader]',e);return false}}
async function prepareAccountLocalData(user){if(!user?.uid||accountPreparedForUid===user.uid||!SyncEngine||!COL)return;accountPreparedForUid=user.uid;const types=[];if(COL.depolamaAyarlari){SyncEngine.register('depolamaAyarlari',COL.depolamaAyarlari);types.push('depolamaAyarlari')}if(COL.navDuzeni){SyncEngine.register('appConfig',COL.navDuzeni);types.push('appConfig')}if(types.length){await SyncEngine.localHydrate(types);applyNavigation();SyncEngine.schedule(80)}}
async function ensureInitialModule(){if(initialRequested)return;initialRequested=true;const cfg=appConfig();let name=cfg.defaultModule||'dashboard';if(moduleMeta(name).visible===false||moduleLevel(name)==='hidden')name=cfg.modules.find(m=>m.visible!==false&&moduleLevel(m.key)!=='hidden')?.key||'dashboard';setActiveModule(name);document.getElementById('v2ModuleTitle').textContent=moduleMeta(name).label||name;await load(name).catch(e=>console.warn('[InitialModule]',e?.message||e))}
function syncLegacySession(){let user=null,role=null;try{if(typeof AKTIF_KULLANICI!=='undefined')user=AKTIF_KULLANICI}catch(_){}try{if(typeof AKTIF_ROL!=='undefined')role=AKTIF_ROL}catch(_){}if(!user?.uid)return false;window.AKTIF_KULLANICI=user;window.AKTIF_ROL=role||null;AppStore?.set?.('session.user',user);AppStore?.set?.('session.role',role||null);if(sessionBootstrapUid===user.uid&&sessionBootstrapPromise){permissionRefresh();return true}sessionBootstrapUid=user.uid;sessionBootstrapPromise=Promise.all([Promise.resolve(AppBootstrap?.start?.()),prepareAccountLocalData(user)]).then(()=>{permissionRefresh();return ensureInitialModule()}).catch(e=>{console.warn('[Local bootstrap]',e?.message||e);sessionBootstrapPromise=null;return false});return true}
function syncAuthVisibility(){const login=document.getElementById('girisEkrani'),pending=document.getElementById('onayBekleniyorEkrani'),app=document.getElementById('app');if(!login||!pending||!app)return;syncLegacySession();const p=pending.classList.contains('active'),a=app.classList.contains('ready')||app.classList.contains('show');login.hidden=p||a;pending.hidden=!p;app.hidden=!a;pending.classList.toggle('ka-hidden',!p)}
function moduleApi(name){return window[MODULE_GLOBALS[name]]||null}
function unmountModule(name){if(!name)return false;const api=moduleApi(name);try{api?.unmount?.();return !!api?.unmount}catch(e){console.warn('[AppLoader] module-unmount:',name,e);return false}}
function suspendActiveModule(){return unmountModule(AppStore?.get?.('ui.route'))}
function setActiveModule(name){const previous=AppStore?.get?.('ui.route');if(previous&&previous!==name)unmountModule(previous);document.querySelectorAll('[data-ka-module]').forEach(btn=>{const active=btn.dataset.kaModule===name;btn.classList.toggle('active',active);active?btn.setAttribute('aria-current','page'):btn.removeAttribute('aria-current')});AppStore?.set?.('ui.route',name)}
function bindShell(){startPlatform();applyNavigation();document.querySelectorAll('[data-ka-module]').forEach(btn=>btn.addEventListener('click',async()=>{const name=btn.dataset.kaModule;if(moduleMeta(name).visible===false||moduleLevel(name)==='hidden')return;setActiveModule(name);document.getElementById('v2ModuleTitle').textContent=moduleMeta(name).label||name;await load(name)}));document.addEventListener('click',e=>{const el=e.target.closest?.('[data-ka-write],[data-ka-requires-edit]');if(!el)return;const key=el.dataset.kaPermission||el.dataset.kaWrite||el.dataset.kaRequiresEdit||'module.'+(AppStore?.get?.('ui.route')||'');if(!PermissionService.can(key,'edit')){e.preventDefault();e.stopImmediatePropagation()}},true);syncAuthVisibility();permissionApply(document);['girisEkrani','onayBekleniyorEkrani','app'].forEach(id=>{const el=document.getElementById(id);if(el)new MutationObserver(syncAuthVisibility).observe(el,{attributes:true,attributeFilter:['class']})});window.addEventListener('koruk:app-ready',()=>{document.getElementById('v2SyncStatus').textContent='Cihaz verisi hazır';permissionRefresh();ensureInitialModule()});window.addEventListener('koruk:sync-state',e=>{document.getElementById('v2SyncStatus').textContent=(e.detail?.pending||0)+' bekleyen işlem'});window.addEventListener('koruk:app-config-changed',applyNavigation);AppStore?.subscribe?.('data.appConfig',()=>requestAnimationFrame(applyNavigation))}
window.AppLoader={define,load,loadMany,loadScript,isLoaded,list,bindShell,syncAuthVisibility,syncLegacySession,setActiveModule,startPlatform,applyTheme,toggleTheme,prepareAccountLocalData,unmountModule,suspendActiveModule,moduleApi};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindShell,{once:true});else bindShell();
})();