/* Koruk Asistan — Arama Modern v1
 * Mevcut global dizileri kullanır; yeni Firestore sorgusu veya veri modeli oluşturmaz.
 * Arama sekmesi kapalıyken snapshot kaynaklı globalAramaYap çağrılarını DOM işine dönüştürmez.
 */
(function(){
'use strict';
if(window.__KORUK_ARAMA_MODERN_V1__)return;window.__KORUK_ARAMA_MODERN_V1__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').trim();
function gv(n){try{return eval(`typeof ${n}!=='undefined'?${n}:null`)}catch(_){return null}}
function arr(n){const v=gv(n);return Array.isArray(v)?v:[]}
let kat='hepsi',filtersOpen=false,servisSet=new Set(),sinifSet=new Set(),kulupSet=new Set();
function active(){return $('#tab-arama')?.classList.contains('active')}
function initials(a,b){return `${String(a||'').trim()[0]||''}${String(b||'').trim()[0]||''}`.toLocaleUpperCase('tr')||'?'}
function teacherName(o){return `${o?.ad||''} ${o?.soyad||''}`.trim()||'Öğretmen'}
function personName(o){return `${o?.ad||''} ${o?.soyad||''}`.trim()||o?.adSoyad||'Personel'}
function className(id,fallback=''){return arr('siniflar').find(x=>x.id===id)?.ad||fallback||'—'}
function serviceName(id,fallback=''){const x=arr('servisler').find(s=>s.id===id);return x?.servisAdi||x?.guzergah||fallback||'—'}
function svgSearch(){return '<svg class="ka-search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>'}
function shell(){const root=$('#tab-arama');if(!root)return null;if(root.dataset.kaModern==='1')return root;root.dataset.kaModern='1';root.classList.add('ka-search-page');root.innerHTML=`<div class="ka-head"><div><h1>Arama</h1><p>Okuldaki kişi, öğrenci, servis ve kayıtları tek noktadan bulun.</p></div></div><section class="ka-search-shell"><div class="ka-searchbox">${svgSearch()}<input id="globalAramaInput" type="search" autocomplete="off" inputmode="search" placeholder="İsim, sınıf, telefon, servis, evrak…"><button type="button" class="ka-clear" aria-label="Aramayı temizle">×</button></div><div class="ka-cats" id="aramaKategoriButonlar"></div><div class="ka-filter-bar"><button type="button" class="ka-filter-toggle">Filtreler <span class="ka-filter-count" style="display:none">0</span></button><button type="button" class="ka-reset">Filtreleri sıfırla</button></div><div class="ka-filters"><div class="ka-filter-group"><span class="ka-filter-label">Cinsiyet</span><select id="aramaCinsiyetFiltre"><option value="">Tümü</option><option value="kiz">Kız</option><option value="erkek">Erkek</option></select></div><div class="ka-filter-group"><span class="ka-filter-label">Sınıf</span><div class="ka-filter-chips" id="aramaSinifSecenekleri"></div></div><div class="ka-filter-group"><span class="ka-filter-label">Servis</span><div class="ka-filter-chips" id="aramaServisSecenekleri"></div></div><div class="ka-filter-group"><span class="ka-filter-label">Sosyal Kulüp</span><div class="ka-filter-chips" id="aramaKulupSecenekleri"></div></div></div></section><div class="ka-summary" id="kaSearchSummary"></div><div class="ka-result-info"><b id="kaResultTitle">Kayıtlar</b><span id="kaResultMeta"></span></div><div id="globalAramaSonuclar"></div>`;
const inp=$('#globalAramaInput',root);inp.addEventListener('input',()=>globalAramaYap());$('.ka-clear',root).onclick=()=>globalAramaTemizle();$('.ka-filter-toggle',root).onclick=()=>{filtersOpen=!filtersOpen;$('.ka-filters',root).classList.toggle('open',filtersOpen)};$('.ka-reset',root).onclick=()=>gelismisFiltreSifirla();$('#aramaCinsiyetFiltre',root).onchange=()=>globalAramaYap();renderCats();aramaGelismisFiltreDoldur();return root}
const CATS=[['hepsi','Tümü'],['ogrenci','Öğrenci'],['ogretmen','Öğretmen'],['personel','Personel'],['servis','Servis'],['evrak','Evrak'],['not','Not']];
function renderCats(){const el=$('#aramaKategoriButonlar');if(!el)return;el.innerHTML=CATS.map(([id,label])=>`<button type="button" class="ka-cat ${kat===id?'aktif':''}" data-kat="${id}">${esc(label)}</button>`).join('');$$('.ka-cat',el).forEach(b=>b.onclick=()=>{kat=b.dataset.kat;renderCats();globalAramaYap()})}
function updateFilterCount(){const n=servisSet.size+sinifSet.size+kulupSet.size+($('#aramaCinsiyetFiltre')?.value?1:0),el=$('.ka-filter-count');if(el){el.textContent=n;el.style.display=n?'inline-block':'none'}}
window.aramaKatSec=function(btn){kat=btn?.dataset?.kat||'hepsi';renderCats();globalAramaYap()};
window.globalAramaTemizle=function(){const i=$('#globalAramaInput');if(i)i.value='';globalAramaYap();i?.focus()};
window.gelismisFiltreSifirla=function(){servisSet.clear();sinifSet.clear();kulupSet.clear();const c=$('#aramaCinsiyetFiltre');if(c)c.value='';aramaGelismisFiltreDoldur();globalAramaYap()};
window.aramaFiltreTikla=function(set,id,el){if(set.has(id))set.delete(id);else set.add(id);el?.classList.toggle('secili',set.has(id));updateFilterCount();globalAramaYap()};
window.aramaGelismisFiltreDoldur=function(){const se=$('#aramaServisSecenekleri'),si=$('#aramaSinifSecenekleri'),ku=$('#aramaKulupSecenekleri');if(se){se.innerHTML=arr('servisler').map(s=>`<button type="button" class="arama-filtre-chip ${servisSet.has(s.id)?'secili':''}" data-id="${esc(s.id)}">🚌 ${esc(s.servisAdi||s.guzergah||'Servis')}</button>`).join('');$$('button',se).forEach(b=>b.onclick=()=>aramaFiltreTikla(servisSet,b.dataset.id,b))}if(si){si.innerHTML=arr('siniflar').slice().sort((a,b)=>String(a.ad||'').localeCompare(String(b.ad||''),'tr')).map(s=>`<button type="button" class="arama-filtre-chip ${sinifSet.has(s.id)?'secili':''}" data-id="${esc(s.id)}">${esc(s.ad||'Sınıf')}</button>`).join('');$$('button',si).forEach(b=>b.onclick=()=>aramaFiltreTikla(sinifSet,b.dataset.id,b))}if(ku){const list=gv('cizelgeVerileri')?.sosyalKulupler||[];ku.innerHTML=list.map(k=>`<button type="button" class="arama-filtre-chip ${kulupSet.has(k.id)?'secili':''}" data-id="${esc(k.id)}">🎗️ ${esc(k.ad||'Kulüp')}</button>`).join('');$$('button',ku).forEach(b=>b.onclick=()=>aramaFiltreTikla(kulupSet,b.dataset.id,b))}updateFilterCount()};
function match(q,vals){return !q||norm(vals.filter(Boolean).join(' ')).includes(q)}
function students(q){const c=$('#aramaCinsiyetFiltre')?.value||'';return arr('veliler').filter(v=>{if(servisSet.size&&!servisSet.has(v.servisId))return false;if(sinifSet.size&&!sinifSet.has(v.sinifId))return false;if(kulupSet.size&&!kulupSet.has(v.kulupId))return false;const g=norm(v.cinsiyet);if(c==='kiz'&&!['k','kiz','kadin'].includes(g))return false;if(c==='erkek'&&!['e','erkek'].includes(g))return false;return match(q,[v.ogrenciAdi,v.veliAdi,v.telefon,v.telefon1,v.telefon2,v.eposta,className(v.sinifId),serviceName(v.servisId,v.servisAdi),v.kulupAdi])})}
function teachers(q){return arr('ogretmenler').filter(o=>match(q,[o.ad,o.soyad,o.brans,o.unvan,o.telefon,o.eposta]))}
function staff(q){return arr('personelListesi').filter(o=>match(q,[o.ad,o.soyad,o.adSoyad,o.gorev,o.unvan,o.telefon]))}
function buses(q){return arr('servisler').filter(s=>match(q,[s.servisAdi,s.guzergah,s.soforAdi,s.soforTelefon,s.plaka]))}
function docs(q){return arr('evrakTakibi').filter(e=>match(q,[e.baslik,e.konu,e.aciklama,e.tur,e.durum,e.sayi]))}
function notes(q){return arr('notlar').filter(n=>match(q,[n.baslik,n.icerik,n.not]))}
function avatarTeacher(o){const url=String(o?.profilFotoUrl||'');return url&&/^https?:\/\//i.test(url)?`<span class="ka-avatar"><img src="${esc(url)}" alt=""></span>`:`<span class="ka-avatar">${esc(initials(o.ad,o.soyad))}</span>`}
function row(main,sub,action,avatar,side=''){return `<button type="button" class="ka-row" data-action="${esc(action)}">${avatar}<span class="ka-row-main"><b>${esc(main)}</b><small>${esc(sub)}</small></span><span class="ka-row-side">${side?`<span class="ka-badge">${esc(side)}</span>`:''}<span class="ka-arrow">›</span></span></button>`}
function group(title,emoji,list,render,max){if(!list.length)return'';const shown=list.slice(0,max);return `<section class="ka-group"><div class="ka-group-head"><div class="ka-group-title"><span class="ka-group-icon">${emoji}</span>${esc(title)}</div><span class="ka-count">${list.length} sonuç</span></div>${shown.map(render).join('')}${list.length>shown.length?`<div class="ka-more">+${list.length-shown.length} kayıt daha · Aramayı daraltabilirsiniz</div>`:''}</section>`}
function bindRows(){$$('.ka-row[data-action]').forEach(b=>b.onclick=()=>{const [type,id]=String(b.dataset.action||'').split(':');try{if(type==='ogrenci')ogrenciDetayModalAc(id);else if(type==='ogretmen')ogretmenDetayAc(id);else if(type==='personel')personelDetayAc(id);else if(type==='servis')sekmeAc('tasima');else if(type==='evrak'){sekmeAc('evrak');}else if(type==='not')sekmeAc('notlar')}catch(_){}})}
function summaries(st,te,pe,bu){const s=$('#kaSearchSummary');if(!s)return;s.innerHTML=[['Öğrenci',st.length],['Öğretmen',te.length],['Personel',pe.length],['Servis',bu.length]].map(x=>`<div class="ka-summary-card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
window.globalAramaYap=function(){if(!active())return;const root=shell();if(!root)return;aramaGelismisFiltreDoldur();const q=norm($('#globalAramaInput')?.value||''),st=students(q),te=teachers(q),pe=staff(q),bu=buses(q),ev=docs(q),no=notes(q);summaries(st,te,pe,bu);let html='',total=0;const max=q?50:8;if(kat==='hepsi'||kat==='ogrenci'){total+=st.length;html+=group('Öğrenciler','🎓',st,v=>row(v.ogrenciAdi||'Öğrenci',`${className(v.sinifId)} · ${v.veliAdi||'Veli bilgisi yok'}`,`ogrenci:${v.id}`,`<span class="ka-avatar">${esc(String(v.ogrenciAdi||'?')[0].toLocaleUpperCase('tr'))}</span>`,serviceName(v.servisId,v.servisAdi)!=='—'?serviceName(v.servisId,v.servisAdi):''),max)}if(kat==='hepsi'||kat==='ogretmen'){total+=te.length;html+=group('Öğretmenler','👩‍🏫',te,o=>row(teacherName(o),[o.brans,o.unvan].filter(Boolean).join(' · ')||'Öğretmen',`ogretmen:${o.id}`,avatarTeacher(o)),max)}if(kat==='hepsi'||kat==='personel'){total+=pe.length;html+=group('Personel','🧑‍💼',pe,p=>row(personName(p),p.gorev||p.unvan||'Personel',`personel:${p.id}`,`<span class="ka-avatar">${esc(initials(p.ad,p.soyad))}</span>`),max)}if(kat==='hepsi'||kat==='servis'){total+=bu.length;html+=group('Servisler','🚌',bu,s=>row(s.servisAdi||s.guzergah||'Servis',[s.plaka,s.soforAdi,s.guzergah].filter(Boolean).join(' · '),`servis:${s.id}`,`<span class="ka-avatar">🚌</span>`),max)}if(kat==='hepsi'||kat==='evrak'){total+=ev.length;html+=group('Evraklar','📄',ev,e=>row(e.baslik||e.konu||'Evrak',[e.tur,e.durum,e.tarih].filter(Boolean).join(' · '),`evrak:${e.id}`,`<span class="ka-avatar">📄</span>`,e.durum||''),max)}if(kat==='hepsi'||kat==='not'){total+=no.length;html+=group('Notlar','🗒️',no,n=>row(n.baslik||n.not||n.icerik||'Not',n.tarih||n.olusturmaTarihi||'Kişisel not',`not:${n.id}`,`<span class="ka-avatar">🗒️</span>`),max)}const title=$('#kaResultTitle'),meta=$('#kaResultMeta');if(title)title.textContent=q?`“${$('#globalAramaInput').value.trim()}” sonuçları`:'Tüm kayıtlar';if(meta)meta.textContent=`${total} eşleşme`;const out=$('#globalAramaSonuclar');if(out)out.innerHTML=html||'<div class="ka-empty"><div class="ka-empty-icon">🔎</div><b>Sonuç bulunamadı</b><span>Arama ifadesini veya filtreleri değiştirin.</span></div>';bindRows()};
function boot(){shell();if(active())globalAramaYap()}
const oldSekme=window.sekmeAc;if(typeof oldSekme==='function'&&!window.__KA_SEKME_WRAP__){window.__KA_SEKME_WRAP__=true;window.sekmeAc=function(tab){const r=oldSekme.apply(this,arguments);if(tab==='arama')requestAnimationFrame(()=>{shell();globalAramaYap();$('#globalAramaInput')?.focus()});return r}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
