/* Koruk Asistan — mobil ana sayfa duyuru bileşeni
 * Firestore beklemez: merkezi runtime/cache verisini okur, event-driven güncellenir.
 * Aynı DOM için tek sahip; aktif duyuru yoksa eski kartı kaldırır.
 */
(function(){
'use strict';
if(!matchMedia('(max-width:1023px)').matches||window.__KH_DUYURU_COMPONENT__)return;window.__KH_DUYURU_COMPONENT__=true;
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function list(){const r=window.KorukRuntimeState?.get('duyurular');if(Array.isArray(r)&&r.length)return r;const c=window.KorukDashboardCache?.duyurular;return Array.isArray(c)?c:[]}
function aktifDuyuru(){return list().filter(d=>d&&!d.arsivlendi&&d.aktif!==false&&!d.pasif).sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||'')))[0]||null}
function tarihMetni(v){if(!v)return'';try{if(typeof isoYereleCevir==='function'){const x=isoYereleCevir(v);return[x.tarih,x.saat].filter(Boolean).join(' · ')}return new Date(v).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}catch(_){return''}}
function okudumMu(d){try{return typeof DuyurularService!=='undefined'&&DuyurularService.benOkudumMu(d)}catch(_){return false}}
function adminMi(){try{return !!window.AKTIF_KULLANICI?.admin}catch(_){return false}}
function detayAc(id){try{if(typeof duyuruDetayAc==='function')return duyuruDetayAc(id)}catch(_){}try{if(typeof sekmeAc==='function')sekmeAc('duyurular')}catch(_){}}
function html(d){const ok=okudumMu(d),okuyan=Object.keys(d.okuyanlar||{}).length,icerik=String(d.icerik||d.aciklama||'').trim(),kisa=icerik.length>180?icerik.slice(0,180).trim()+'…':icerik;return `<article class="kh-announcement ${ok?'is-read':'is-unread'}" data-duyuru-id="${esc(d.id)}"><div class="kh-announcement-accent"></div><div class="kh-announcement-head"><div class="kh-announcement-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m3 11 18-5v12L3 14v-3Z"/><path d="M11.6 16.5 13 21H7l-1.2-6"/></svg></div><div class="kh-announcement-title-wrap"><div class="kh-announcement-kicker">DUYURU</div><h3>${esc(d.baslik||d.ad||'Duyuru')}</h3><div class="kh-announcement-meta">${esc(d.olusturanAdi||'Yönetim')}${d.tarih?' · '+esc(tarihMetni(d.tarih)):''}</div></div><span class="kh-announcement-status ${ok?'read':'new'}">${ok?'✓ OKUNDU':'YENİ'}</span></div>${kisa?`<button type="button" class="kh-announcement-body" data-action="detail">${esc(kisa)}</button>`:''}<div class="kh-announcement-footer"><label class="kh-read-check ${ok?'checked':''}"><input type="checkbox" data-action="read" ${ok?'checked disabled':''} style="position:absolute!important;opacity:0!important;pointer-events:none!important;width:1px!important;height:1px!important"><span class="kh-read-box">✓</span><span>${ok?'Okundu olarak işaretlendi':'Okudum'}</span></label>${adminMi()?`<button type="button" class="kh-read-count" data-action="readers"><span>👁</span><b>${okuyan}</b> kişi okudu <span class="arrow">›</span></button>`:''}</div></article>`}
let lastSig='';
function genericIn(dyn){return Array.from(dyn.children).find(el=>!el.classList.contains('kh-announcement')&&(el.textContent||'').toLocaleUpperCase('tr').includes('DUYURU'))||null}
function sync(){const dyn=$('#tab-panel.kh-home .kh-dynamic');if(!dyn)return false;const d=aktifDuyuru(),kart=$('.kh-announcement',dyn),generic=genericIn(dyn);if(!d){kart?.remove();if(generic)generic.remove();lastSig='';return true}const sig=`${d.id}|${Object.keys(d.okuyanlar||{}).length}|${okudumMu(d)?1:0}|${d.baslik||''}|${d.icerik||''}|${d.arsivlendi?1:0}|${d.aktif===false?0:1}`;if(kart&&lastSig===sig){if(generic)generic.remove();return true}const box=document.createElement('div');box.innerHTML=html(d);const yeni=box.firstElementChild;if(kart)kart.replaceWith(yeni);else if(generic)generic.replaceWith(yeni);else dyn.prepend(yeni);if(generic&&generic.isConnected&&generic!==yeni)generic.remove();lastSig=sig;const read=$('[data-action="read"]',yeni);if(read&&!read.disabled)read.onchange=async e=>{if(!e.target.checked)return;e.target.disabled=true;try{await DuyurularService.okunduIsaretle(d.id);lastSig='';window.KorukRuntimeState?.signal?.('duyuru-read');schedule()}catch(err){e.target.checked=false;e.target.disabled=false;try{toast('Okundu bilgisi kaydedilemedi: '+err.message)}catch(_){}}};$('[data-action="detail"]',yeni)?.addEventListener('click',()=>detayAc(d.id));$('[data-action="readers"]',yeni)?.addEventListener('click',()=>detayAc(d.id));return true}
let queued=false;function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;sync()})}
let tries=0;function boot(){if(sync())return;if(++tries<100)setTimeout(boot,50)}
window.addEventListener('koruk:data-updated',schedule);window.addEventListener('koruk:dashboard-render',schedule);window.addEventListener('focus',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();