/* Koruk Asistan — Temiz Mobil Ana Sayfa
 * Tek renderer / tek DOM sahibi. Eski dashboard renderini mobilde calistirmaz.
 * Mevcut veri dizilerini ve servis fonksiyonlarini sadece OKUR.
 * Alt navigasyona dokunmaz.
 */
(function(){
'use strict';
if(window.__KORUK_HOME_OWNER__) return;
if(!window.matchMedia('(max-width:1023px)').matches) return;
window.__KORUK_HOME_OWNER__=true;

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function gv(name){try{return eval(`typeof ${name}!=='undefined'?${name}:null`)}catch(_){return null}}
function arr(name){const v=gv(name);return Array.isArray(v)?v:[]}
function norm(v){return String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').trim()}
function iso(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayName(d=new Date()){return ['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'][d.getDay()]}
function parseDate(v){if(!v)return null;try{const d=v?.toDate?v.toDate():new Date(String(v).length===10?String(v)+'T00:00:00':v);return isNaN(d)?null:d}catch(_){return null}}
function fmtDate(v,opt={day:'numeric',month:'long'}){const d=parseDate(v);return d?new Intl.DateTimeFormat('tr-TR',opt).format(d):''}
function daysUntil(v){const d=parseDate(v);if(!d)return null;d.setHours(0,0,0,0);const t=new Date();t.setHours(0,0,0,0);return Math.round((d-t)/86400000)}
function relativeDay(n){if(n===null)return'';if(n===0)return'Bugün';if(n===1)return'Yarın';if(n<0)return`${Math.abs(n)} gün geçti`;return`${n} gün`}
function openTab(name){try{if(typeof sekmeAc==='function')return sekmeAc(name)}catch(_){}document.querySelector(`[data-tab="${name}"]`)?.click()}
function user(){return gv('AKTIF_KULLANICI')||window.AKTIF_KULLANICI||null}
function teacher(){try{if(typeof bagliOgretmenimGetir==='function'){const t=bagliOgretmenimGetir();if(t)return t}}catch(_){}const u=user();return u?.bagliOgretmenId?arr('ogretmenler').find(x=>x.id===u.bagliOgretmenId)||null:null}
function isAdmin(){return !!user()?.admin}
function displayName(){const t=teacher();if(t){const n=`${t.ad||''} ${t.soyad||''}`.trim();if(n)return n}const u=user()||{};return String(u.adSoyad||u.ad_soyad||u.ad||u.isim||u.displayName||u.kullaniciAdi||'').trim()||'Kullanıcı'}
function greeting(){const h=new Date().getHours();return h<6?'İyi geceler':h<11?'Günaydın':h<18?'Tünaydın':h<22?'İyi akşamlar':'İyi geceler'}
function teacherName(id){const t=arr('ogretmenler').find(x=>x.id===id);return t?`${t.ad||''} ${t.soyad||''}`.trim():'—'}
function classNameFrom(x){return x?.sinif||x?.sinifAdi||arr('siniflar').find(s=>s.id===x?.sinifId)?.ad||'—'}
function lessonNameFrom(x){return x?.ders||x?.dersAdi||arr('dersListesi').find(d=>d.id===x?.dersId)?.ad||'—'}
function lessonTime(no){try{if(typeof dersSaatiBilgisi==='function')return dersSaatiBilgisi(Number(no))}catch(_){}return null}
function lessonStatus(){try{if(typeof suankiDersDurumu==='function')return suankiDersDurumu()||{durum:'yok'}}catch(_){}return {durum:'yok'}}
function gender(v){const n=norm(v);if(/^(k|kadin|bayan|female|kiz)$/.test(n)||n.includes('kadin')||n.includes('kiz'))return'k';if(/^(e|erkek|bay|male)$/.test(n)||n.includes('erkek'))return'e';return''}
function genderOf(x){return gender(x?.cinsiyet??x?.cinsiyeti??x?.cins??x?.gender??'')}

const PATHS={
 users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
 student:'<path d="m3 10 9-5 9 5-9 5-9-5Z"/><path d="M7 12v5c3 2 7 2 10 0v-5"/>',
 school:'<path d="M3 21h18M5 21V7l7-4 7 4v14M9 10h2M13 10h2M9 14h2M13 14h2"/>',
 bus:'<path d="M6 17h12M6 17v2M18 17v2M5 17a2 2 0 0 1-2-2V7c0-3 2-4 9-4s9 1 9 4v8a2 2 0 0 1-2 2"/><path d="M3 10h18M7 14h.01M17 14h.01"/>',
 shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/>',
 book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5v13Z"/><path d="M8 7h8M8 11h6"/>',
 exam:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',
 note:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/>',
 task:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1 2-2V5a2 2 0 0 1 2-2h11"/>',
 news:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V5H6.5A2.5 2.5 0 0 0 4 7.5v12Z"/><path d="M8 9h8M8 13h6"/>',
 globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/>',
 file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/>',
 bolt:'<path d="m13 2-9 12h8l-1 8 9-12h-8l1-8Z"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
 cloud:'<path d="M17.5 19H9a7 7 0 1 1 6.7-9h1.8a4.5 4.5 0 0 1 0 9Z"/>',
 megaphone:'<path d="m3 11 18-5v12L3 14v-3Z"/><path d="M11.6 16.5 13 21H7l-1.2-6"/>',
 chart:'<path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-7"/>',
 message:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>',
 search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${PATHS[name]||PATHS.note}</svg>`}
const IG='<svg viewBox="0 0 24 24" aria-hidden="true"><defs><linearGradient id="khig" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="#feda75"/><stop offset=".35" stop-color="#fa7e1e"/><stop offset=".6" stop-color="#d62976"/><stop offset=".82" stop-color="#962fbf"/><stop offset="1" stop-color="#4f5bd5"/></linearGradient></defs><rect x="2" y="2" width="20" height="20" rx="6" fill="url(#khig)"/><rect x="6.3" y="6.3" width="11.4" height="11.4" rx="3.5" fill="none" stroke="#fff" stroke-width="1.7"/><circle cx="12" cy="12" r="3.1" fill="none" stroke="#fff" stroke-width="1.7"/><circle cx="17.2" cy="6.8" r="1.1" fill="#fff"/></svg>';
const XICON='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>';
function section(title,icoName,more){const s=document.createElement('section');s.className='kh-section';const h=document.createElement('div');h.className='kh-section-head';h.innerHTML=`<div class="kh-section-title">${icon(icoName)}<span>${esc(title)}</span></div>${more?`<button type="button" class="kh-more">${esc(more.label||'Tümü')} ›</button>`:''}`;if(more)$('.kh-more',h).onclick=more.action;s.append(h);return s}
function card(html=''){const c=document.createElement('div');c.className='kh-card';c.innerHTML=html;return c}
function chip(text,cls=''){return `<span class="kh-chip ${cls}">${esc(text)}</span>`}

function weather(){const v=gv('sonHavaVerisi');if(!v)return null;let text='Hava Durumu',emoji='🌤️';try{if(typeof havaKoduOku==='function'){const x=havaKoduOku(v.kod);if(x){text=x.t||x.aciklama||text;emoji=x.e||x.emoji||emoji}}}catch(_){}let loc='';try{loc=localStorage.getItem('oyHavaKonum')||''}catch(_){}return {temp:Math.round(Number(v.sicaklik)||0),text,emoji,loc}}
function bellView(){const d=new Date();if(d.getDay()===0||d.getDay()===6)return {big:'Hafta sonu',sub:'Bugün ders bulunmuyor'};const s=lessonStatus();if(s.durum==='ders')return {big:`${s.saat}. Ders`,sub:`Bitmesine ${timeFromMinutes(s.kalanDk||0)}`};if(s.durum==='ogle')return {big:'Öğle Arası',sub:s.kalanDk!=null?`${timeFromMinutes(s.kalanDk)} sonra ders`:'Dinlenme zamanı'};if(s.durum==='teneffus')return {big:'Teneffüs',sub:s.saat?`${s.saat}. Ders · ${timeFromMinutes(s.kalanDk||0)} sonra`:'Sonraki ders bekleniyor'};if(s.durum==='baslamadi')return {big:'Dersler başlamadı',sub:s.saat?`${s.saat}. Ders · ${timeFromMinutes(s.kalanDk||0)} sonra`:'Program bekleniyor'};if(s.durum==='bitti')return {big:'Dersler tamamlandı',sub:'Bugünkü ders programı sona erdi'};return {big:'Zil sayacı',sub:'Ders saatleri yükleniyor'}}
function timeFromMinutes(min){const sec=Math.max(0,Math.round(Number(min||0)*60));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function hero(){const h=document.createElement('header');h.className='kh-hero';const w=weather(),b=bellView();h.innerHTML=`<div class="kh-brand">KORUK ASİSTAN</div><div class="kh-greeting">${esc(greeting())}, ${esc(displayName())} 👋</div><div class="kh-date">${esc(new Intl.DateTimeFormat('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()))}</div><div class="kh-live-stack"><button type="button" class="kh-live-card" id="khWeather" style="text-align:left;width:100%"><div class="kh-live-icon">${w?`<span style="font-size:26px">${w.emoji}</span>`:icon('cloud')}</div><div class="kh-live-main">${w?`<b>${w.temp}°C</b><small>${esc(w.text)}${w.loc?' · '+esc(w.loc):''}</small>`:'<b>Hava durumu</b><small>Veri yükleniyor</small>'}</div></button><button type="button" class="kh-live-card" id="khBell" style="text-align:left;width:100%"><div class="kh-live-icon">${icon('bell')}</div><div class="kh-live-main"><b>${esc(b.big)}</b><small>${esc(b.sub)}</small></div></button></div>`;$('#khWeather',h).onclick=()=>{try{if(typeof havaDurumuDetayAc==='function')havaDurumuDetayAc()}catch(_){}};$('#khBell',h).onclick=()=>{try{if(typeof zilTiklandi==='function')zilTiklandi()}catch(_){}};return h}

function dynamicItems(){const out=[];const today=iso();const denemes=arr('denemeSinavlari');const activeExam=denemes.find(x=>String(x.tarih||x.sinavTarihi||'')===today&&norm(x.durum||'').indexOf('tamam')<0)||gv('aktifDenemeSinavi');if(activeExam)out.push({type:'deneme',icon:'exam',title:activeExam.ad||activeExam.baslik||'Deneme sınavı',sub:activeExam.saat?`Saat ${activeExam.saat}`:'Bugün',side:'CANLI',tab:'denemeSinavlari'});const announcements=arr('duyurular').filter(x=>x.aktif!==false&&!x.pasif);if(announcements.length){const x=announcements[0];out.push({type:'duyuru',icon:'megaphone',title:x.baslik||x.ad||'Duyuru',sub:x.icerik||x.aciklama||'',side:'DUYURU',tab:'duyurular'})}const polls=[...arr('anketler'),...arr('anketListesi')].filter(x=>x.aktif!==false&&!x.kapali);if(polls.length){const x=polls[0];out.push({type:'anket',icon:'chart',title:x.baslik||x.soru||'Aktif anket',sub:x.aciklama||'',side:'ANKET',tab:'anket'})}return out.slice(0,3)}
function dynamicSection(){const data=dynamicItems();if(!data.length)return null;const wrap=document.createElement('div');wrap.className='kh-dynamic';wrap.innerHTML=data.map((x,i)=>`<button type="button" class="kh-dyn-item" data-i="${i}" style="width:100%;text-align:left;color:var(--kh-text)"><span class="kh-dyn-icon">${icon(x.icon)}</span><span class="kh-row-main"><b>${esc(x.title)}</b><small>${esc(x.sub)}</small></span>${chip(x.side,x.type==='deneme'?'red':'')}</button>`).join('');$$('[data-i]',wrap).forEach(b=>b.onclick=()=>openTab(data[Number(b.dataset.i)].tab));return wrap}
function newsSection(){const news=arr('haberler').filter(x=>x&&x.aktif!==false);if(!news.length)return null;const wrap=document.createElement('div');wrap.className='kh-news';const items=news.slice(0,10);const text=items.map((x,i)=>`<button type="button" class="kh-news-item" data-n="${i}">${esc(x.baslik||x.ad||'Haber')}</button><span class="kh-news-dot">•</span>`).join('');wrap.style.setProperty('--kh-ticker-time',`${Math.max(22,items.length*8)}s`);wrap.innerHTML=`<button type="button" class="kh-news-label" aria-label="Haberler">${icon('news')} HABERLER</button><div class="kh-news-viewport"><div class="kh-news-track">${text}${text}</div></div>`;$('.kh-news-label',wrap).onclick=()=>openTab('haberler');$$('.kh-news-item',wrap).forEach(b=>b.onclick=()=>{const x=items[Number(b.dataset.n)];const url=x?.url||x?.link;if(url){try{window.open(url,'_blank','noopener')}catch(_){location.href=url}}else openTab('haberler')});return wrap}

function statsData(){
  const staff=arr('ogretmenler').filter(Boolean);
  const classes=arr('siniflar'),pupils=arr('veliler'),services=arr('servisler');
  const k=staff.filter(x=>genderOf(x)==='k').length,e=staff.filter(x=>genderOf(x)==='e').length;
  const cls=id=>classes.find(s=>s.id===id);
  const level=s=>Number(s?.seviye||String(s?.ad||'').match(/\d+/)?.[0]||0);
  let pri={t:0,k:0,e:0},mid={t:0,k:0,e:0};
  const classGenderTotal=classes.reduce((n,s)=>n+Number(s.kizSayisi||0)+Number(s.erkekSayisi||0),0);
  if(classGenderTotal>0){classes.forEach(s=>{const g=level(s)>0&&level(s)<=4?pri:mid;const kk=Number(s.kizSayisi||0),ee=Number(s.erkekSayisi||0),tt=Number(s.ogrenciSayisi||kk+ee||0);g.t+=tt;g.k+=kk;g.e+=ee})}
  else if(pupils.length){pupils.forEach(p=>{const lv=level(cls(p.sinifId))||Number(String(p.sinif||p.sinifAdi||'').match(/\d+/)?.[0]||0);const g=lv>0&&lv<=4?pri:mid;g.t++;const c=genderOf(p);if(c==='k')g.k++;if(c==='e')g.e++})}
  else{classes.forEach(s=>{const g=level(s)>0&&level(s)<=4?pri:mid;g.t+=Number(s.ogrenciSayisi||0)})}
  let activeServices=services.filter(x=>!['pasif','iptal','silindi'].includes(norm(x.durum||'aktif'))).length;
  if(!activeServices){const ids=new Set(pupils.map(x=>x.servisId||x.servisAdi).filter(Boolean));activeServices=ids.size}
  return {ogretmen:staff.length,k,e,ogr:pri.t+mid.t,pri,mid,sinif:classes.length,servis:activeServices}
}
function statsSection(){
  const d=statsData(),s=section('Okul Özeti','school'),wrap=document.createElement('div');wrap.className='kh-stats';
  const teacherDetail=`<div class="kh-teacher-genders"><span class="kh-gender-badge female">♀ <b>${d.k}</b><small>Kadın</small></span><span class="kh-gender-badge male">♂ <b>${d.e}</b><small>Erkek</small></span></div>`;
  const studentDetail=`<div class="kh-student-split"><div><span>İLKOKUL</span><b>${d.pri.t}</b><small><i class="kh-sex female">♀</i>${d.pri.k} <i class="kh-sex male">♂</i>${d.pri.e}</small></div><i class="kh-student-divider"></i><div><span>ORTAOKUL</span><b>${d.mid.t}</b><small><i class="kh-sex female">♀</i>${d.mid.k} <i class="kh-sex male">♂</i>${d.mid.e}</small></div></div>`;
  const items=[['users','Öğretmen',d.ogretmen,teacherDetail,'ogretmenler'],['student','Öğrenci',d.ogr,studentDetail,'siniflar'],['school','Sınıf',d.sinif,'<span class="kh-summary-note">Aktif sınıf / şube</span>','siniflar'],['bus','Servis',d.servis,'<span class="kh-summary-note">Aktif servis</span>','tasima']];
  wrap.innerHTML=items.map(([ic,l,n,det,tab])=>`<button class="kh-stat kh-stat-${ic}" type="button" data-tab="${tab}"><div class="kh-stat-icon">${icon(ic)}</div><div class="kh-stat-label">${l}</div><div class="kh-stat-number">${n}</div><div class="kh-stat-detail">${det}</div></button>`).join('');
  $$('[data-tab]',wrap).forEach(b=>b.onclick=()=>openTab(b.dataset.tab));s.append(wrap);return s
}

function socialLinks(){const o=gv('okulBilgileriAyari')||gv('okulBilgileri')||{};let links=[];try{if(typeof sosyalLinklerVeriyeCevir==='function')links=sosyalLinklerVeriyeCevir(o)||[]}catch(_){}if(!links.length&&Array.isArray(o.sosyalLinkler))links=o.sosyalLinkler;if(!links.length){if(o.instagram)links.push({etiket:'Instagram',ikon:'instagram',url:o.instagram});if(o.x)links.push({etiket:'X',ikon:'x',url:o.x});[o.web,o.webSitesi,o.ilkokulWeb,o.ortaokulWeb].filter(Boolean).forEach((u,i)=>links.push({etiket:i?'Okul Sitesi 2':'Okul Sitesi',ikon:'web',url:u}))}return links.filter(x=>x?.url&&!/facebook|youtube/i.test(`${x.ikon||''} ${x.etiket||''}`)).slice(0,4)}
function socialSection(){const links=socialLinks();if(!links.length)return null;const s=section('Sosyal Medya ve Okul Siteleri','globe');const wrap=document.createElement('div');wrap.className='kh-social';wrap.innerHTML=links.map(l=>{const k=norm(`${l.ikon||''} ${l.etiket||''}`);const brand=k.includes('instagram')?IG:(k==='x'||k.includes('twitter'))?XICON:icon('globe');return `<a href="${esc(l.url)}" target="_blank" rel="noopener"><span class="kh-social-icon">${brand}</span><span>${esc(l.etiket||'Okul Sitesi')}</span></a>`}).join('');s.append(wrap);return s}
function dutyPlace(x){const p=arr('nobetYerleri').find(y=>y.id===x?.yerId);return x?.yer||x?.yerAdi||p?.ad||''}
function isDutyChief(x){return norm(dutyPlace(x)).includes('nobetci amir')||norm(x?.gorev||'').includes('nobetci amir')}
function todayDuties(){const t=iso();return arr('nobetAtamalari').filter(x=>x.tarih===t&&!isDutyChief(x))}
function dutiesTodaySection(){const data=todayDuties();const s=section("Bugünün Nöbetçileri",'shield',{label:'Tümü',action:()=>openTab('nobet')});const c=card(data.length?data.map(x=>`<div class="kh-row"><div class="kh-row-main"><b>${esc(x.ogretmenAdi||teacherName(x.ogretmenId))}</b><small>${esc(dutyPlace(x)||'Nöbet')}</small></div>${chip('Bugün')}</div>`).join(''):'<div class="kh-empty">Bugün nöbetçi öğretmen kaydı bulunmuyor.</div>');s.append(c);return s}
function leaveTodaySection(){const t=iso();const data=arr('ogretmenIzinleri').filter(x=>(!x.baslangic||x.baslangic<=t)&&(!x.bitis||x.bitis>=t));if(!data.length)return null;const s=section('Bugün İzinli Öğretmenler','calendar');const c=card(data.map(x=>`<div class="kh-row"><div class="kh-row-main"><b>${esc(x.ogretmenAdi||teacherName(x.ogretmenId))}</b><small>${esc(x.tur||x.aciklama||'İzinli')}</small></div>${chip('İzinli','amber')}</div>`).join(''));s.append(c);return s}
function tasksSection(){const raw=[...arr('gorevler'),...arr('hatirlaticilar')].filter(x=>{const st=norm(x.durum||'');return !x.tamamlandi&&!['tamamlandi','arsivlendi','kapali'].includes(st)&&(x.tarih||x.sonTarih)}).sort((a,b)=>String(a.tarih||a.sonTarih).localeCompare(String(b.tarih||b.sonTarih)));if(!raw.length)return null;const data=raw.slice(0,6);const s=section('Yaklaşan Etkinlik / Görevler','task',{label:'Tümü',action:()=>openTab('takvim')});const c=card(data.map(x=>{const d=daysUntil(x.tarih||x.sonTarih);return `<div class="kh-row"><div class="kh-row-main"><b>${esc(x.baslik||x.ad||x.aciklama||'Görev')}</b><small>${esc(fmtDate(x.tarih||x.sonTarih))}</small></div><div class="kh-side">${esc(relativeDay(d))}</div></div>`}).join(''));c.onclick=()=>openTab('takvim');s.append(c);return s}
function currentPeriod(){const st=lessonStatus();if(st.durum==='ders')return {period:Number(st.saat),mode:'now',left:st.kalanDk};if(st.durum==='teneffus'||st.durum==='baslamadi')return {period:Number(st.saat),mode:'next',left:st.kalanDk};return {period:null,mode:st.durum}}
function currentLessonsSection(){const info=currentPeriod(),gun=dayName();let title='Şu Anki Dersler';if(info.mode==='next'&&info.period)title=`Sonraki Dersler · ${info.period}. Ders`;const s=section(title,'book',{label:'Tümü',action:()=>openTab('dersProgrami')});const c=card();if(new Date().getDay()===0||new Date().getDay()===6)c.innerHTML='<div class="kh-empty">Bugün ders programı bulunmuyor.</div>';else if(info.mode==='bitti')c.innerHTML='<div class="kh-empty">Bugünkü dersler tamamlandı.</div>';else if(info.period){const rows=arr('dersProgrami').filter(x=>norm(x.gun)===norm(gun)&&Number(x.saat)===info.period).sort((a,b)=>classNameFrom(a).localeCompare(classNameFrom(b),'tr'));c.innerHTML=`<div class="kh-lessons-head"><span>SINIF</span><span>DERS</span><span style="text-align:right">ÖĞRETMEN</span></div>${rows.length?rows.map((x,i)=>`<button type="button" class="kh-lesson" data-i="${i}"><span class="class">${esc(classNameFrom(x))}</span><span>${esc(lessonNameFrom(x))}</span><span class="teacher">${esc(x.ogretmenAdi||teacherName(x.ogretmenId))}</span></button>`).join(''):'<div class="kh-empty">Bu ders saati için program kaydı bulunmuyor.</div>'}`;$$('.kh-lesson',c).forEach(b=>b.onclick=()=>openTab('dersProgrami'))}else c.innerHTML='<div class="kh-empty">Ders saatleri yükleniyor.</div>';s.append(c);return s}
function weekDates(){const d=new Date(),diff=(d.getDay()+6)%7,mon=new Date(d);mon.setDate(d.getDate()-diff);return Array.from({length:5},(_,i)=>{const x=new Date(mon);x.setDate(mon.getDate()+i);return x})}
function weekDutySection(){const dates=weekDates(),all=arr('nobetAtamalari');const s=section('Haftanın Nöbet Programı','calendar',{label:'Tümü',action:()=>openTab('nobet')});const c=card();c.innerHTML=dates.map(d=>{const key=iso(d),rows=all.filter(x=>x.tarih===key&&!isDutyChief(x));return `<div class="kh-weekday ${key===iso()?'today':''}"><div class="kh-weekday-head"><span>${dayName(d).toLocaleUpperCase('tr')}</span>${key===iso()?chip('BUGÜN'):''}</div>${rows.length?rows.map(x=>`<div class="kh-mini"><span>${esc(x.ogretmenAdi||teacherName(x.ogretmenId))}</span><span>${esc(dutyPlace(x)||'—')}</span></div>`).join(''):'<div class="kh-mini"><span style="color:var(--kh-muted)">Nöbet kaydı yok</span><span></span></div>'}</div>`}).join('');c.onclick=()=>openTab('nobet');s.append(c);return s}
function upcomingExams(mine=false){const tid=teacher()?.id;return arr('sinavlar').filter(x=>{const d=daysUntil(x.tarih||x.sinavTarihi);if(d===null||d<0)return false;if(!mine)return true;if(!tid)return false;return x.ogretmenId===tid||x.sorumluOgretmenId===tid||x.ekleyenOgretmenId===tid}).sort((a,b)=>String(a.tarih||a.sinavTarihi).localeCompare(String(b.tarih||b.sinavTarihi))||String(a.saat||'').localeCompare(String(b.saat||'')))}
function examsSection(mine=false){const data=upcomingExams(mine).slice(0,8);if(!data.length)return null;const s=section(mine?'Sınavlarım':'Yaklaşan Yazılı Sınavlar','exam',{label:'Tümü',action:()=>openTab('yaziliSinavlar')});const c=card();let last='',html='';data.forEach(x=>{const date=x.tarih||x.sinavTarihi;if(date!==last){last=date;html+=`<div class="kh-exam-date">${esc(fmtDate(date,{day:'2-digit',month:'short',weekday:'long'}).toLocaleUpperCase('tr'))}</div>`}html+=`<div class="kh-row"><div class="kh-row-main"><b>${esc(classNameFrom(x))} · ${esc(lessonNameFrom(x))}</b><small>${esc(x.ad||x.sinavAdi||x.tur||'Yazılı sınav')}${x.saat?' · '+esc(x.saat):''}</small></div><div class="kh-side">${esc(relativeDay(daysUntil(date)))}</div></div>`});c.innerHTML=html;c.onclick=()=>openTab('yaziliSinavlar');s.append(c);return s}
function personalLessons(date=new Date()){const t=teacher();if(!t)return[];const gun=dayName(date);return arr('dersProgrami').filter(x=>x.ogretmenId===t.id&&norm(x.gun)===norm(gun)).sort((a,b)=>Number(a.saat)-Number(b.saat))}
function personalScheduleSection(){const t=teacher();if(!t)return null;const rows=personalLessons(),st=lessonStatus();const s=section('Ders Programım','book',{label:'Haftalık',action:()=>openTab('dersNobetProgramim')});const c=card();c.innerHTML=rows.length?rows.map(x=>{const tm=lessonTime(x.saat),now=st.durum==='ders'&&Number(st.saat)===Number(x.saat);return `<div class="kh-personal-row ${now?'now':''}"><div class="kh-personal-period">${esc(x.saat)}. DERS</div><div><b>${esc(classNameFrom(x))} · ${esc(lessonNameFrom(x))}</b><small>${tm?`${esc(tm.baslangic)} – ${esc(tm.bitis)}`:''}</small></div>${now?chip('ŞİMDİ'):''}</div>`}).join(''):'<div class="kh-empty">Bugün dersiniz bulunmuyor.</div>';c.onclick=()=>openTab('dersNobetProgramim');s.append(c);return s}
function myNotes(){const u=user()||{},t=teacher(),uid=u.uid||u.id;return arr('notlar').filter(x=>{if(!x.sahipUid&&!x.kullaniciUid&&!x.ogretmenId)return isAdmin();return x.sahipUid===uid||x.kullaniciUid===uid||(t&&x.ogretmenId===t.id)}).sort((a,b)=>String(b.tarih||b.olusturmaTarihi||'').localeCompare(String(a.tarih||a.olusturmaTarihi||''))).slice(0,4)}
function notesSection(){const data=myNotes();const s=section('Notlarım','note',{label:'Tümü',action:()=>openTab('notlar')});const c=card(data.length?data.map(x=>`<div class="kh-row"><div class="kh-row-main"><b>${esc(x.baslik||x.icerik||x.not||'Not')}</b><small>${esc(fmtDate(x.tarih||x.olusturmaTarihi))}</small></div><span></span></div>`).join(''):'<div class="kh-empty">Henüz kişisel notunuz yok.</div>');c.onclick=()=>openTab('notlar');s.append(c);return s}
function planForLesson(lesson){const level=Number(String(classNameFrom(lesson)).match(/\d+/)?.[0]||0),name=norm(lessonNameFrom(lesson));return arr('yillikPlanTanimlari').find(p=>Number(p.seviye)===level&&norm(p.dersAdi)===name)||null}
function currentPlanWeek(plan){if(!plan)return null;let idx=0;try{if(typeof _yplBugunHaftaIndex==='function')idx=_yplBugunHaftaIndex(plan)}catch(_){}return {idx,row:(plan.satirlar||[])[idx]||null}}
function outcomesFor(lesson){const plan=planForLesson(lesson),week=currentPlanWeek(plan);if(!plan||!week?.row)return {plan,items:[],idx:week?.idx||0};const skip=new Set(['ay','hafta','saat']);const items=[];Object.entries(week.row).forEach(([k,v])=>{if(!v||skip.has(k)||k.startsWith('_'))return;const text=Array.isArray(v)?v.join(' · '):String(v);if(text.trim())items.push(text.trim())});return {plan,items:items.slice(0,3),all:items,idx:week.idx}}
function openPlan(lesson){const p=planForLesson(lesson);try{if(p&&typeof yillikPlanHaftaAc==='function')return yillikPlanHaftaAc(p.id)}catch(_){}openTab('yillikPlan')}
function teacherFocusSection(){const t=teacher();if(!t)return null;const st=lessonStatus(),today=personalLessons();let lesson=null,mode='',left=null;if(st.durum==='ders'){lesson=today.find(x=>Number(x.saat)===Number(st.saat));if(lesson)mode='now'}if(!lesson){const cur=Number(st.saat||0);lesson=today.find(x=>Number(x.saat)>=cur&&!(st.durum==='ders'&&Number(x.saat)===cur));if(lesson){mode='next';const tm=lessonTime(lesson.saat);if(tm){const d=new Date(),now=d.getHours()*60+d.getMinutes()+d.getSeconds()/60;left=Math.max(0,(Number(tm.baslangic.split(':')[0])*60+Number(tm.baslangic.split(':')[1]))-now)}}}if(!lesson)return null;const out=outcomesFor(lesson);const s=section(mode==='now'?'Şu Anki Dersim':'Sonraki Dersim','book');const c=card();c.innerHTML=`<div class="kh-focus"><div class="kh-focus-top"><span class="kh-focus-label">${mode==='now'?'● CANLI':left!=null?`${Math.ceil(left)} dk sonra`:'HAZIRLIK'}</span>${chip(`${lesson.saat}. Ders`)}</div><h3>${esc(classNameFrom(lesson))} · ${esc(lessonNameFrom(lesson))}</h3><div class="meta">${(()=>{const tm=lessonTime(lesson.saat);return tm?`${esc(tm.baslangic)} – ${esc(tm.bitis)}`:''})()}</div><div class="kh-outcomes"><div class="kh-outcomes-title">BU HAFTANIN ÖĞRENME ÇIKTILARI / KAZANIMLARI</div>${out.items.length?`<ul>${out.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${out.all.length>3?`<div class="kh-side" style="margin-top:7px;text-align:left">+${out.all.length-3} kazanım daha</div>`:''}`:'<div class="kh-empty" style="padding:8px 0;text-align:left">Bu ders için güncel hafta kazanımı bulunamadı.</div>'}</div></div><button type="button" class="kh-plan-button">Yıllık Planı Aç ›</button>`;$('.kh-plan-button',c).onclick=()=>openPlan(lesson);s.append(c);return s}
function todayLessonsTeacher(){const rows=personalLessons();if(!rows.length)return null;const st=lessonStatus();const s=section('Bugünkü Derslerim','book',{label:'Haftalık',action:()=>openTab('dersNobetProgramim')});const c=card(rows.map((x,i)=>{const now=st.durum==='ders'&&Number(st.saat)===Number(x.saat),out=outcomesFor(x);return `<button type="button" class="kh-row" data-i="${i}" style="width:100%;text-align:left;border-left:0;border-right:0;border-top:0;background:${now?'var(--kh-brand-soft)':'transparent'};color:var(--kh-text)"><div class="kh-row-main"><b>${esc(x.saat)}. Ders · ${esc(classNameFrom(x))} · ${esc(lessonNameFrom(x))}</b><small>${out.items[0]?`📌 ${esc(out.items[0])}`:'Yıllık planı aç'}</small></div>${now?chip('ŞİMDİ'):chip('Planı')}</button>`}).join(''));$$('[data-i]',c).forEach(b=>b.onclick=()=>openPlan(rows[Number(b.dataset.i)]));s.append(c);return s}
function myDutySection(){const t=teacher();if(!t)return null;const duty=todayDuties().find(x=>x.ogretmenId===t.id);if(!duty)return null;const key=`kh-duty-done:${t.id}:${iso()}`;let done=false;try{done=localStorage.getItem(key)==='1'}catch(_){}const s=section('Bugünkü Nöbetim','shield');const c=card(`<div class="kh-row"><div class="kh-row-main"><b>${esc(dutyPlace(duty)||'Nöbet')}</b><small>Bugünkü nöbet göreviniz</small></div>${chip('BUGÜN')}</div><label class="kh-duty-check"><input id="khDutyCheck" type="checkbox" ${done?'checked':''}> <span>Nöbet defterini doldurdum</span></label>`);$('#khDutyCheck',c).onchange=e=>{try{localStorage.setItem(key,e.target.checked?'1':'0')}catch(_){}};s.append(c);return s}
function quickSection(){const s=section('Hızlı İşlemler','bolt');const w=document.createElement('div');w.className='kh-quick';const acts=[['exam','Sınav Ekle',()=>{openTab('yaziliSinavlar');setTimeout(()=>{try{if(typeof yaziliSinavModalAc==='function')yaziliSinavModalAc()}catch(_){}},100)}],['note','Not Ekle',()=>{openTab('notlar');setTimeout(()=>{try{if(typeof notlarModalAc==='function')notlarModalAc()}catch(_){}},100)}],['message','Mesaj Gönder',()=>openTab('mesajlasma')],['megaphone','Duyurular',()=>openTab('duyurular')]];w.innerHTML=acts.map((a,i)=>`<button type="button" data-i="${i}">${icon(a[0])}${esc(a[1])}</button>`).join('');$$('[data-i]',w).forEach(b=>b.onclick=acts[Number(b.dataset.i)][2]);s.append(w);return s}
function teacherDocsSection(){const t=teacher();if(!t)return null;const data=arr('evrakTakibi').filter(x=>{const ids=[x.ogretmenId,x.hedefOgretmenId,x.atananOgretmenId,x.sorumluId].filter(Boolean);return ids.includes(t.id)&&!['arsivlendi'].includes(norm(x.durum||''))}).sort((a,b)=>String(a.sonTarih||a.tarih||'9999').localeCompare(String(b.sonTarih||b.tarih||'9999'))).slice(0,6);if(!data.length)return null;const s=section('Teslim Edilecek Evraklar','file',{label:'Tümü',action:()=>openTab('evrak')});const c=card(data.map(x=>{const due=x.sonTarih||x.tarih,d=daysUntil(due),delivered=/teslim edildi|tamamlandi/.test(norm(x.durum||'')),late=!delivered&&d!==null&&d<0;return `<div class="kh-row"><div class="kh-row-main"><b>${esc(x.baslik||x.konu||x.aciklama||'Evrak')}</b><small>${due?'Son tarih: '+esc(fmtDate(due)):''}</small></div>${delivered?chip('Teslim Edildi','green'):late?chip('Gecikti','red'):chip(d===0?'Bugün':d===1?'Yarın':d!=null?`${d} gün`:'Bekliyor','amber')}</div>`}).join(''));c.onclick=()=>openTab('evrak');s.append(c);return s}
function agendaItemsFor(date){const key=iso(date),out=[];personalLessons(date).forEach(x=>{const tm=lessonTime(x.saat);out.push({time:tm?.baslangic||'',icon:'book',text:`${classNameFrom(x)} · ${lessonNameFrom(x)}`,tab:'dersNobetProgramim'})});upcomingExams(true).filter(x=>(x.tarih||x.sinavTarihi)===key).forEach(x=>out.push({time:x.saat||'',icon:'exam',text:`${classNameFrom(x)} ${lessonNameFrom(x)} yazılısı`,tab:'yaziliSinavlar'}));[...arr('gorevler'),...arr('hatirlaticilar')].filter(x=>(x.tarih||x.sonTarih)===key).forEach(x=>out.push({time:x.saat||'',icon:'task',text:x.baslik||x.ad||x.aciklama||'Görev',tab:'takvim'}));return out.sort((a,b)=>String(a.time).localeCompare(String(b.time)))}
function calendarSection(){const base=new Date(),diff=(base.getDay()+6)%7,mon=new Date(base);mon.setDate(base.getDate()-diff);const dates=Array.from({length:7},(_,i)=>{const d=new Date(mon);d.setDate(mon.getDate()+i);return d});const s=section('Takvim','calendar',{label:new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(base),action:()=>openTab('takvim')});const c=card();let selected=dates.findIndex(d=>iso(d)===iso());if(selected<0)selected=0;function draw(){const d=dates[selected],agenda=agendaItemsFor(d);c.innerHTML=`<div class="kh-calendar">${dates.map((x,i)=>`<button type="button" class="kh-day ${i===selected?'today':''} ${agendaItemsFor(x).length?'has':''}" data-day="${i}">${['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][i]}<b>${x.getDate()}</b></button>`).join('')}</div><div class="kh-agenda-title">${esc(fmtDate(d,{day:'numeric',month:'long',weekday:'long'}).toLocaleUpperCase('tr'))}</div>${agenda.length?agenda.map(x=>`<div class="kh-row" data-tab="${x.tab}"><div class="kh-row-main"><b>${esc(x.text)}</b><small>${x.time?esc(x.time):'Tüm gün'}</small></div><span style="color:var(--kh-brand);width:20px">${icon(x.icon)}</span></div>`).join(''):'<div class="kh-empty">Bu gün için kayıt bulunmuyor.</div>'}`;$$('[data-day]',c).forEach(b=>b.onclick=()=>{selected=Number(b.dataset.day);draw()});$$('.kh-row[data-tab]',c).forEach(r=>r.onclick=()=>openTab(r.dataset.tab))}draw();s.append(c);return s}
function adminSections(shell){[dynamicSection(),newsSection(),statsSection(),socialSection(),dutiesTodaySection(),leaveTodaySection(),tasksSection(),currentLessonsSection(),weekDutySection(),examsSection(false),personalScheduleSection(),notesSection()].filter(Boolean).forEach(x=>shell.append(x))}
function teacherSections(shell){[teacherFocusSection(),dynamicSection(),newsSection(),todayLessonsTeacher(),myDutySection(),quickSection(),examsSection(true),teacherDocsSection(),notesSection(),calendarSection(),socialSection()].filter(Boolean).forEach(x=>shell.append(x))}
function render(){const p=$('#tab-panel');if(!p||!user())return false;p.classList.remove('dash-modern','db6','kc-home');p.classList.add('kh-home');const shell=document.createElement('main');shell.className='kh-shell';shell.append(hero());if(isAdmin())adminSections(shell);else teacherSections(shell);const top=document.createElement('button');top.type='button';top.className='kh-backtop';top.setAttribute('aria-label','Yukarı dön');top.textContent='↑';top.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});p.replaceChildren(shell,top);lastSignature=dataSignature();liveTick();return true}
function sigOne(name,fields=['id','tarih','durum']){return arr(name).map(x=>fields.map(f=>{const v=x?.[f];return v?.seconds||v||''}).join(':')).join('|')}
function dataSignature(){const u=user(),t=teacher();return [u?.id||u?.uid||'',u?.admin?'A':'U',t?.id||'',sigOne('ogretmenler',['id','ad','soyad','cinsiyet','cinsiyeti','gender']),sigOne('siniflar',['id','ad','ogrenciSayisi','kizSayisi','erkekSayisi']),sigOne('veliler',['id','sinifId','cinsiyet','servisId','servisAdi']),sigOne('servisler',['id','durum','guzergah','servisAdi']),sigOne('dersProgrami',['id','gun','saat','ogretmenId','sinif','ders']),sigOne('nobetAtamalari',['id','tarih','ogretmenId','yerId']),sigOne('sinavlar',['id','tarih','sinavTarihi','ogretmenId']),sigOne('haberler',['id','baslik','aktif']),sigOne('duyurular',['id','baslik','aktif']),sigOne('gorevler',['id','tarih','durum']),sigOne('hatirlaticilar',['id','tarih','durum']),sigOne('ogretmenIzinleri',['id','baslangic','bitis','ogretmenId']),sigOne('notlar',['id','tarih','ogretmenId']),sigOne('yillikPlanTanimlari',['id','egitimOgretimYili'])].join('~')}
let lastSignature='';
function refreshIfChanged(){if(!user())return;const p=$('#tab-panel');const s=dataSignature();if(s!==lastSignature||!$('.kh-shell',p))render()}
function liveTick(){const b=$('#khBell');if(b){const v=bellView();const m=$('.kh-live-main',b);if(m)m.innerHTML=`<b>${esc(v.big)}</b><small>${esc(v.sub)}</small>`}const w=$('#khWeather'),wd=weather();if(w&&wd){const ic=$('.kh-live-icon',w),m=$('.kh-live-main',w);if(ic)ic.innerHTML=`<span style="font-size:26px">${wd.emoji}</span>`;if(m)m.innerHTML=`<b>${wd.temp}°C</b><small>${esc(wd.text)}${wd.loc?' · '+esc(wd.loc):''}</small>`}const top=$('.kh-backtop');if(top)top.style.display=window.scrollY>520?'block':'none'}
function claimDashboardRenderer(){if(window.__KH_RENDER_CLAIMED__)return true;if(typeof window.renderDashboard!=='function')return false;const desktopRender=window.renderDashboard;window.renderDashboard=function(){if(window.matchMedia('(max-width:1023px)').matches)return render();return desktopRender.apply(this,arguments)};window.__KH_RENDER_CLAIMED__=true;return true}
let claimTry=0;const claimTimer=setInterval(()=>{if(claimDashboardRenderer()||++claimTry>120)clearInterval(claimTimer)},100);
setInterval(refreshIfChanged,1800);setInterval(liveTick,1000);window.addEventListener('scroll',liveTick,{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden){setTimeout(refreshIfChanged,50);setTimeout(liveTick,100)}});[0,100,300,700,1400,2600].forEach(ms=>setTimeout(refreshIfChanged,ms));window.KorukHome={render,refresh:refreshIfChanged};
})();