/* Koruk Asistan — Uygulama içi belge görüntüleyici v3 */
(function(){
'use strict';
const DESTEK=new Set(['pdf','doc','docx','xls','xlsx','csv','txt','png','jpg','jpeg','webp','gif','bmp','svg','ppt','pptx','rtf','odt','ods']);
const DOCX='https://cdn.jsdelivr.net/npm/docx-preview@0.3.6/dist/docx-preview.min.js';
const JSZIP='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';
let A=null,pdf=null,wb=null,wordZoom=1;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function ext(s){try{const n=decodeURIComponent(String(s||'').split('?')[0].split('#')[0].split('/').pop()||'');const i=n.lastIndexOf('.');return i<0?'':n.slice(i+1).toLowerCase();}catch(_){return '';}}
function googleDocsMu(u){return /^https:\/\/(docs|drive)\.google\.com\//i.test(String(u||''));}
function style(){if(document.getElementById('dv3css'))return;const s=document.createElement('style');s.id='dv3css';s.textContent=`.dv3{position:fixed;inset:0;z-index:1000000;background:#30363d;color:#fff;display:flex;flex-direction:column;font-family:Inter,Arial,sans-serif}.dv3h{min-height:58px;padding:max(8px,env(safe-area-inset-top)) 10px 8px;display:flex;align-items:center;gap:7px;background:#101419}.dv3title{flex:1;min-width:0}.dv3title b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#fff!important;text-shadow:0 1px 1px #0008}.dv3title small{color:#d7dee7!important}.dv3btn{border:1px solid #46505b;background:#252c34;color:#fff;border-radius:9px;padding:9px 11px;font-weight:650}.dv3btn.primary{background:#087c7c}.dv3body{flex:1;min-height:0;overflow:auto;-webkit-overflow-scrolling:touch}.dv3status{min-height:100%;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:12px;text-align:center;padding:24px}.dv3pdf{display:flex;flex-direction:column;align-items:center;gap:14px;padding:14px}.dv3pdf canvas{background:#fff;box-shadow:0 3px 15px #0008;max-width:100%;height:auto}.dv3wordtools{position:sticky;top:0;z-index:8;display:flex;align-items:center;justify-content:center;gap:6px;padding:7px;background:#20262d;border-bottom:1px solid #46505b}.dv3wordtools button{min-width:40px}.dv3body.dv3wordbody{background:#cfd3d7}.dv3wordviewport{padding:10px;overflow:visible;width:100%;min-width:0;box-sizing:border-box}.dv3wordscene{position:relative;margin:0 auto}.dv3wordstage{position:absolute;left:0;top:0;transform-origin:top left;display:block}.dv3word .docx-wrapper{padding:18px!important;background:#cfd3d7!important;align-items:flex-start!important;justify-content:flex-start!important;min-width:max-content!important}.dv3word section.docx{margin:0 0 18px 0!important;box-shadow:0 2px 12px #0005!important;background:#fff!important}.dv3excel{background:#fff;color:#111;min-height:100%}.dv3tabs{position:sticky;top:0;z-index:3;display:flex;overflow-x:auto;gap:4px;padding:7px;background:#20262d}.dv3tabs button{white-space:nowrap;padding:7px 10px}.dv3sheet{overflow:auto}.dv3sheet table{border-collapse:collapse}.dv3sheet td,.dv3sheet th{border:1px solid #d5d8dc;padding:4px 6px;white-space:nowrap}.dv3text{margin:12px;padding:16px;background:#fff;color:#111;white-space:pre-wrap}.dv3img{min-height:100%;display:flex;align-items:center;justify-content:center;padding:12px}.dv3img img{max-width:100%;max-height:100%}.dv3info{padding:10px 12px;background:#26313a;color:#e6edf3}.dv3frame{width:100%;height:100%;border:0;background:#fff}@media(max-width:640px){.dv3hide{display:none}.dv3btn{padding:8px}.dv3wordviewport{padding:4px}.dv3word .docx-wrapper{padding:10px!important}.dv3word section.docx{margin-bottom:12px!important}}`;document.head.appendChild(s);}
function openShell(url,name,e){close();style();document.body.dataset.dv3Overflow=document.body.style.overflow||'';document.body.style.overflow='hidden';const d=document.createElement('div');d.className='dv3';d.id='dv3';d.innerHTML=`<div class="dv3h"><button class="dv3btn" id="dv3x">✕</button><div class="dv3title"><b>${esc(name)}</b><small>${esc((e||'belge').toUpperCase())}</small></div><button class="dv3btn primary" id="dv3down">⬇ <span class="dv3hide">İndir</span></button></div><div class="dv3body" id="dv3body"></div>`;document.body.appendChild(d);A={url,name,e,body:d.querySelector('#dv3body')};d.querySelector('#dv3x').onclick=close;d.querySelector('#dv3down').onclick=download;}
function close(){document.getElementById('dv3')?.remove();if(A?.blobUrl)URL.revokeObjectURL(A.blobUrl);A=null;pdf=null;wb=null;if(document.body.dataset.dv3Overflow!==undefined){document.body.style.overflow=document.body.dataset.dv3Overflow;delete document.body.dataset.dv3Overflow;}}
function status(t){if(A)A.body.innerHTML=`<div class="dv3status"><div style="font-size:30px">⏳</div><div>${esc(t)}</div></div>`;}
function fail(t,d){if(A)A.body.innerHTML=`<div class="dv3status"><div style="font-size:38px">⚠️</div><b>${esc(t)}</b>${d?`<small>${esc(d)}</small>`:''}<button class="dv3btn primary" onclick="document.getElementById('dv3down').click()">⬇ İndir</button></div>`;}
async function getBuf(){const r=await fetch(A.url,{cache:'no-store'});if(!r.ok)throw new Error('Dosya alınamadı ('+r.status+')');return r.arrayBuffer();}
async function download(){try{const r=await fetch(A.url,{cache:'no-store'}),b=await r.blob();if(typeof uygulamaDosyaKaydet==='function'){const fr=new FileReader();const x=await new Promise((ok,no)=>{fr.onloadend=()=>ok(String(fr.result).split(',')[1]);fr.onerror=no;fr.readAsDataURL(b)});await uygulamaDosyaKaydet(x,A.name,b.type||'application/octet-stream',false);}else{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=A.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}}catch(e){typeof toast==='function'&&toast('İndirme hatası: '+e.message);}}
function load(src,test){if(test())return Promise.resolve();return new Promise((ok,no)=>{const old=[...document.scripts].find(x=>x.src===src);if(old){old.addEventListener('load',ok,{once:true});old.addEventListener('error',no,{once:true});return;}const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s);});}
async function docxReady(){await load(JSZIP,()=>typeof JSZip!=='undefined');await load(DOCX,()=>typeof docx!=='undefined'&&typeof docx.renderAsync==='function');}
function wordOlcekUygula(){if(!A)return;const st=A.body.querySelector('#dv3wordStage'),scene=A.body.querySelector('#dv3wordScene'),wrap=A.body.querySelector('#dv3wordViewport');if(!st||!scene||!wrap)return;const dogalW=Math.max(1,Number(st.dataset.naturalWidth)||st.scrollWidth||1),dogalH=Math.max(1,Number(st.dataset.naturalHeight)||st.scrollHeight||1);st.style.transform=`scale(${wordZoom})`;scene.style.width=Math.ceil(dogalW*wordZoom)+'px';scene.style.height=Math.ceil(dogalH*wordZoom)+'px';wrap.style.width='100%';wrap.style.height='auto';const l=A.body.querySelector('#dv3wordZoomLabel');if(l)l.textContent=Math.round(wordZoom*100)+'%';}
function wordZoomUygula(z){wordZoom=Math.max(0.35,Math.min(3,z));wordOlcekUygula();}
function wordSigdir(){if(!A)return;const st=A.body.querySelector('#dv3wordStage'),wrapper=A.body.querySelector('#dv3word .docx-wrapper'),sayfa=A.body.querySelector('#dv3word section.docx');if(!st||!wrapper||!sayfa)return;st.style.transform='none';const sayfalar=[...A.body.querySelectorAll('#dv3word section.docx')];const maxSayfaW=Math.max(...sayfalar.map(x=>x.offsetWidth||x.getBoundingClientRect().width||1),sayfa.offsetWidth||1);const ws=getComputedStyle(wrapper),padX=(parseFloat(ws.paddingLeft)||0)+(parseFloat(ws.paddingRight)||0);const dogalW=Math.ceil(maxSayfaW+padX);const dogalH=Math.ceil(wrapper.scrollHeight||st.scrollHeight||sayfa.scrollHeight||1);st.dataset.naturalWidth=String(dogalW);st.dataset.naturalHeight=String(dogalH);const uygunW=Math.max(240,A.body.clientWidth-20);wordZoom=Math.max(0.35,Math.min(1,uygunW/dogalW));wordOlcekUygula();A.body.scrollTo({left:0,top:0,behavior:'auto'});}
async function renderDocx(buf){status('Word belgesi hazırlanıyor…');try{await docxReady();wordZoom=1;A.body.classList.add('dv3wordbody');A.body.innerHTML='<div class="dv3wordtools"><button class="dv3btn" id="dv3wordMinus">−</button><button class="dv3btn" id="dv3wordFit">Sığdır</button><span id="dv3wordZoomLabel" style="min-width:48px;text-align:center;font-weight:700">100%</span><button class="dv3btn" id="dv3wordPlus">+</button></div><div class="dv3wordviewport" id="dv3wordViewport"><div class="dv3wordscene" id="dv3wordScene"><div class="dv3wordstage" id="dv3wordStage"><div class="dv3word" id="dv3word"></div></div></div></div>';await docx.renderAsync(buf,A.body.querySelector('#dv3word'),null,{inWrapper:true,breakPages:true,ignoreWidth:false,ignoreHeight:false,ignoreFonts:false,renderHeaders:true,renderFooters:true,renderFootnotes:true,ignoreLastRenderedPageBreak:false,useBase64URL:true});A.body.querySelector('#dv3wordMinus').onclick=()=>wordZoomUygula(wordZoom-0.15);A.body.querySelector('#dv3wordPlus').onclick=()=>wordZoomUygula(wordZoom+0.15);A.body.querySelector('#dv3wordFit').onclick=wordSigdir;requestAnimationFrame(()=>requestAnimationFrame(wordSigdir));}catch(e){fail('Word belgesi görüntülenemedi.',e.message);}}
function zipMi(buf){const u=new Uint8Array(buf,0,Math.min(4,buf.byteLength));return u.length>=4&&u[0]===0x50&&u[1]===0x4b&&(u[2]===0x03||u[2]===0x05||u[2]===0x07);}
async function docAc(){status('Word dosya türü doğrulanıyor…');try{const buf=await getBuf();if(zipMi(buf))return renderDocx(buf);A.body.innerHTML='<div class="dv3info">Bu dosya gerçek eski Word 97-2003 (.doc) biçiminde. Firebase bağlantıları Microsoft/Google sunucularına her zaman açılamadığı için dış görüntüleyici yerine cihazdaki Office/Word uygulaması önerilir.</div><div class="dv3status"><div style="font-size:44px">📄</div><b>Eski Word (.doc)</b><div>Dosya indirilmeden web tarayıcısında birebir işlenemiyor.</div><button class="dv3btn" id="dv3sys">Word / Office ile Aç</button><button class="dv3btn primary" id="dv3save">Cihaza Kaydet</button></div>';A.body.querySelector('#dv3sys').onclick=()=>window.open(A.url,'_system');A.body.querySelector('#dv3save').onclick=download;}catch(e){fail('Word dosyası okunamadı.',e.message);}}
async function pdfAc(){if(typeof pdfjsLib==='undefined')return fail('PDF.js bulunamadı.');status('PDF hazırlanıyor…');try{pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';pdf=await pdfjsLib.getDocument({url:A.url,cMapUrl:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/cmaps/',cMapPacked:true,standardFontDataUrl:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/standard_fonts/',useSystemFonts:true,disableFontFace:false}).promise;A.body.innerHTML='<div class="dv3pdf" id="dv3pdf"></div>';const area=A.body.firstChild,dpr=Math.min(devicePixelRatio||1,2.25);for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),base=p.getViewport({scale:1}),cw=Math.min(Math.max(280,A.body.clientWidth-28),base.width*1.35),sc=cw/base.width,v=p.getViewport({scale:sc*dpr}),c=document.createElement('canvas');c.width=Math.round(v.width);c.height=Math.round(v.height);c.style.width=Math.round(base.width*sc)+'px';c.style.height=Math.round(base.height*sc)+'px';area.appendChild(c);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;}}catch(e){fail('PDF görüntülenemedi.',e.message);}}
function excelShell(names,fn){A.body.innerHTML='<div class="dv3excel"><div class="dv3tabs" id="dv3tabs"></div><div class="dv3sheet" id="dv3sheet"></div></div>';const t=A.body.querySelector('#dv3tabs');names.forEach((n,i)=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>fn(i);t.appendChild(b)});if(names.length)fn(0);}
async function xlsxAc(buf){status('Excel hazırlanıyor…');try{buf=buf||await getBuf();if(typeof ExcelJS!=='undefined'){wb=new ExcelJS.Workbook();await wb.xlsx.load(buf);excelShell(wb.worksheets.map(x=>x.name),i=>{const ws=wb.worksheets[i],out=A.body.querySelector('#dv3sheet');let h='<table>';ws.eachRow({includeEmpty:true},r=>{h+='<tr>';for(let c=1;c<=ws.columnCount;c++){const x=r.getCell(c),v=x.value&&typeof x.value==='object'?(x.value.text??x.value.result??''):x.value;h+='<td>'+esc(v??'')+'</td>'}h+='</tr>'});out.innerHTML=h+'</table>';});return;}if(typeof XLSX==='undefined')throw new Error('Excel bileşeni bulunamadı');const x=XLSX.read(buf,{type:'array',cellDates:true});excelShell(x.SheetNames,i=>A.body.querySelector('#dv3sheet').innerHTML=XLSX.utils.sheet_to_html(x.Sheets[x.SheetNames[i]]));}catch(e){fail('Excel dosyası görüntülenemedi.',e.message);}}
async function xlsAc(){status('Excel dosya türü doğrulanıyor…');try{const buf=await getBuf();if(zipMi(buf))return xlsxAc(buf);if(typeof XLSX==='undefined')throw new Error('SheetJS bulunamadı');const x=XLSX.read(buf,{type:'array',cellDates:true,cellStyles:true});excelShell(x.SheetNames,i=>A.body.querySelector('#dv3sheet').innerHTML=XLSX.utils.sheet_to_html(x.Sheets[x.SheetNames[i]]));}catch(e){fail('Eski Excel (.xls) görüntülenemedi.',e.message);}}
async function textAc(csv){status('Dosya okunuyor…');try{const r=await fetch(A.url,{cache:'no-store'}),txt=await r.text();if(csv&&typeof XLSX!=='undefined'){const x=XLSX.read(txt,{type:'string'});excelShell(x.SheetNames,i=>A.body.querySelector('#dv3sheet').innerHTML=XLSX.utils.sheet_to_html(x.Sheets[x.SheetNames[i]]));}else A.body.innerHTML='<pre class="dv3text">'+esc(txt)+'</pre>';}catch(e){fail('Dosya okunamadı.',e.message);}}
function imgAc(){A.body.innerHTML='<div class="dv3img"><img src="'+esc(A.url)+'" alt="'+esc(A.name)+'"></div>';}
function onlineAc(){A.body.innerHTML='<div class="dv3info">Bu belge türünün tarayıcıda güvenilir yerel görüntüleyicisi yok. Otomatik indirme yapılmadı.</div><div class="dv3status"><div style="font-size:44px">📎</div><button class="dv3btn" id="dv3sys">Sistemle Aç</button><button class="dv3btn primary" id="dv3save">İndir</button></div>';A.body.querySelector('#dv3sys').onclick=()=>window.open(A.url,'_system');A.body.querySelector('#dv3save').onclick=download;}
async function ac(url,name){if(!url)return;name=name||decodeURIComponent(String(url).split('?')[0].split('/').pop()||'Belge');if(googleDocsMu(url)){openShell(url,name,'google');A.body.innerHTML='<iframe class="dv3frame" src="'+esc(url)+'"></iframe>';return;}const e=ext(name)||ext(url);openShell(url,name,e);if(e==='pdf')return pdfAc();if(e==='docx')return renderDocx(await getBuf());if(e==='doc')return docAc();if(e==='xlsx')return xlsxAc();if(e==='xls')return xlsAc();if(e==='csv')return textAc(true);if(e==='txt')return textAc(false);if(['png','jpg','jpeg','webp','gif','bmp','svg'].includes(e))return imgAc();return onlineAc();}
window.DokumanOkuyucu={destekliMi:s=>googleDocsMu(s)||DESTEK.has(ext(s)),googleDocsMu,ac,kapat:close};
})();
