/* Koruk Asistan — Kullanıcı İstatistikleri modern mobil render */
(function(){
'use strict';
if(window.__KORUK_IST_MODERN__)return;window.__KORUK_IST_MODERN__=true;
const mobil=()=>window.matchMedia('(max-width:1023px)').matches;
let filtre='tumu',arama='',cache=[];
function esc(s){return typeof escapeHtml==='function'?escapeHtml(s||''):String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtSure(s){return typeof _istSureFormat==='function'?_istSureFormat(s):`${Math.round((s||0)/60)} dk`}
function fmtTarih(t){return typeof _istTarihFormat==='function'?_istTarihFormat(t):'—'}
function topPage(v){return typeof _istEnCokZiyaretEdilen==='function'?_istEnCokZiyaretEdilen(v):'—'}
function mb(b){return typeof _istMbFormat==='function'?_istMbFormat(Math.max(0,b||0)):`${((Math.max(0,b||0))/(1024*1024)).toFixed(1))} MB`}
function panel(){const g=document.getElementById('istatistikTabloGovde');return g&&g.closest('.tab-panel')}
function storageTotal(k){const d=k.depolamaKullanimi||{};return ['mesaj','duyuru','dokuman','takvim'].reduce((t,x)=>t+Math.max(0,d[x]||0),0)}
function storageRows(k){const d=k.depolamaKullanimi||{},items=[['Mesaj','mesaj'],['Duyuru','duyuru'],['Doküman','dokuman'],['Takvim','takvim']],max=Math.max(1,...items.map(x=>Math.max(0,d[x[1]]||0)));return items.map(([ad,key])=>{const val=Math.max(0,d[key]||0),pct=Math.min(100,Math.round(val/max*100));return `<div class="ist-storage-row"><span>${ad}</span><div class="ist-bar"><i style="width:${pct}%"></i></div><b>${mb(val)}</b></div>`}).join('')}
function filtered(){let a=cache.filter(k=>(k.ad||'').toLocaleLowerCase('tr').includes(arama.toLocaleLowerCase('tr')));if(filtre==='aktif')a.sort((x,y)=>(y.girisSayisi||0)-(x.girisSayisi||0));else if(filtre==='son')a.sort((x,y)=>{const tx=x.sonGiris?.toMillis?x.sonGiris.toMillis():new Date(x.sonGiris||0).getTime(),ty=y.sonGiris?.toMillis?y.sonGiris.toMillis():new Date(y.sonGiris||0).getTime();return ty-tx});else if(filtre==='depolama')a.sort((x,y)=>storageTotal(y)-storageTotal(x));return a}
function drawList(muaf){const el=document.getElementById('istModernList');if(!el)return;const a=filtered();if(!a.length){el.innerHTML='<div class="ist-empty">Filtreye uygun kullanıcı bulunamadı.</div>';return}el.innerHTML=a.map((k,i)=>`<article class="ist-user-card"><div class="ist-user-head"><div><b>${esc(k.ad||'Bilinmiyor')}</b><small>Son giriş: ${esc(fmtTarih(k.sonGiris))}</small></div><span class="ist-rank">#${i+1}</span></div><div class="ist-metrics"><div class="ist-metric"><b>${k.girisSayisi||0}</b><span>Giriş</span></div><div class="ist-metric"><b>${esc(fmtSure(k.toplamSureSaniye||0))}</b><span>Kullanım</span></div><div class="ist-metric"><b>${k.dosyaYuklemeSayisi||0}</b><span>Dosya</span></div><div class="ist-metric"><b>${k.notEklemeSayisi||0}</b><span>Not</span></div></div><div class="ist-page-line">En çok kullanılan: <strong>${esc(topPage(k.sayfaZiyaretleri))}</strong></div><details class="ist-storage"><summary><span>Depolama kullanımı</span><span>${esc(mb(storageTotal(k)))} ▾</span></summary><div class="ist-storage-body">${storageRows(k)}<label class="ist-exempt"><span>Depolama sınırından muaf</span><input type="checkbox" ${muaf[k.uid]?'checked':''} onchange="istKullaniciMuafDegistir('${k.uid}',this)"></label></div></details></article>`).join('')}
function summary(){const s=document.getElementById('istModernSummary');if(!s)return;const toplamGiris=cache.reduce((t,k)=>t+(k.girisSayisi||0),0),toplamSure=cache.reduce((t,k)=>t+(k.toplamSureSaniye||0),0),toplamDosya=cache.reduce((t,k)=>t+(k.dosyaYuklemeSayisi||0),0);s.innerHTML=`<div><b>${cache.length}</b><span>Kullanıcı</span></div><div><b>${toplamGiris}</b><span>Toplam giriş</span></div><div><b>${esc(fmtSure(toplamSure))}</b><span>Kullanım</span></div><div><b>${toplamDosya}</b><span>Dosya</span></div>`}
async function renderModern(){if(typeof kullaniciYonetimiYetkisiVar==='function'&&!kullaniciYonetimiYetkisiVar()){toast('Bu sayfayı görüntüleme yetkiniz yok.');return}const p=panel();if(!p||typeof IstatistikService==='undefined')return; p.classList.add('ist-modern-page');p.innerHTML=`<div class="page-header"><div><div class="page-title">Kullanıcı İstatistikleri</div><div class="page-sub">Uygulama kullanım ve depolama özeti</div></div></div><div class="ist-shell"><section class="ist-hero"><span class="ist-kicker">KORUK ASİSTAN</span><h1>Kullanıcı İstatistikleri</h1><p>Gerçek kullanım sayaçları ve kullanıcı bazlı depolama durumu.</p><div id="istModernSummary" class="ist-summary"></div></section><div class="ist-tools"><label class="ist-search"><span>⌕</span><input id="istModernSearch" placeholder="Kullanıcı ara" autocomplete="off"></label><button class="ist-refresh" onclick="renderIstatistikler()">↻ Yenile</button></div><div class="ist-filters"><button class="ist-filter active" data-ist-filter="tumu">Tümü</button><button class="ist-filter" data-ist-filter="aktif">En Aktif</button><button class="ist-filter" data-ist-filter="son">Son Giriş</button><button class="ist-filter" data-ist-filter="depolama">Depolama</button></div><div id="istModernList" class="ist-user-list"><div class="ist-empty">Yükleniyor…</div></div><section class="ist-admin"><b>Depolama Yönetimi</b><p>Gerçek dosyaları tarayarak kullanıcı depolama sayaçlarını yeniden hesaplar. Yalnız admin kullanabilir.</p><button onclick="istDepolamaYenidenHesaplaTikla()">🧮 Depolamayı Yeniden Hesapla</button></section></div>`;try{cache=await IstatistikService.tumIstatistikleriGetir();cache.sort((a,b)=>(b.girisSayisi||0)-(a.girisSayisi||0));let muaf={};try{const snap=await db.collection(COL.kullanicilar).get();snap.docs.forEach(d=>muaf[d.id]=!!d.data().depolamaMuaf)}catch(e){console.warn('[İstatistik] muafiyet okunamadı',e)}window.__IST_MUAF_MAP=muaf;summary();drawList(muaf);const q=document.getElementById('istModernSearch');q?.addEventListener('input',()=>{arama=q.value||'';drawList(muaf)});p.querySelectorAll('[data-ist-filter]').forEach(b=>b.addEventListener('click',()=>{filtre=b.dataset.istFilter;p.querySelectorAll('[data-ist-filter]').forEach(x=>x.classList.toggle('active',x===b));drawList(muaf)}))}catch(e){console.error('[İstatistik modern]',e);document.getElementById('istModernList').innerHTML=`<div class="ist-empty">İstatistikler yüklenemedi: ${esc(e.message||'')}</div>`}}
function install(){if(typeof window.renderIstatistikler!=='function'||typeof IstatistikService==='undefined')return false;const old=window.renderIstatistikler;if(old.__modern)return true;function wrapped(){return mobil()?renderModern():old.apply(this,arguments)}wrapped.__modern=true;window.renderIstatistikler=wrapped;return true}
let n=0;const t=setInterval(()=>{if(install()||++n>150)clearInterval(t)},100);document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));
})();
