/* Koruk Asistan — Mesajlaşma Modern v6
   Sade konuşma listesi + WhatsApp benzeri mobil sohbet ekranı. */
(function(){
'use strict';
if(window.__KM_MESSAGING_MODERN_V6__) return;
window.__KM_MESSAGING_MODERN_V6__=true;

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function svgChat(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/><path d="M8 9h8M8 13h5"/></svg>';}
function anaKapsayici(list){return list.closest('[id^="tab-"]')||list.closest('.tab-content')||list.closest('.tab-panel')||list.parentElement;}
function konusmaIdKarttan(k){const m=(k.getAttribute('onclick')||'').match(/mesajKonusmaAc\(['\"]([^'\"]+)/);return m?m[1]:null;}
function eskiBasligiGizle(root){$$('.page-header',root).forEach(h=>{const t=(h.textContent||'').toLocaleLowerCase('tr');if(t.includes('mesaj'))h.classList.add('km-legacy-head');});$$('p',root).forEach(p=>{if((p.textContent||'').trim().toLocaleLowerCase('tr')==='okul içi mesajlaşma'){const c=p.closest('.card,.page-header')||p.parentElement;if(c&&c!==root)c.classList.add('km-legacy-head');}});}
function eskiYeniMesaj(root){return $$('button',root).find(b=>{const t=(b.textContent||'').toLocaleLowerCase('tr');return t.includes('yeni mesaj')||t.includes('mesaj yaz');});}
function tekillestir(list){let data=[];try{data=Array.isArray(konusmalar)?konusmalar:[];}catch(_){return;}const ben=(()=>{try{return AKTIF_KULLANICI?.uid||'';}catch(_){return'';}})();const byId=new Map(data.map(k=>[k.id,k])),seen=new Set();$$('.konusma-karti',list).forEach(card=>{const k=byId.get(konusmaIdKarttan(card));if(!k||k.grupMu){card.style.display='flex';return;}const diger=(k.katilimciUidler||[]).filter(x=>x!==ben).sort().join('|'),key='p:'+diger;if(diger&&seen.has(key))card.style.display='none';else{if(diger)seen.add(key);card.style.display='flex';}});}
function baslikSayisiniGuncelle(root,list){tekillestir(list);const n=$$('.konusma-karti',list).filter(x=>x.style.display!=='none').length;const el=$('.km-msg-count',root);if(el)el.textContent=n?`${n} sohbet`:'Henüz sohbet yok';}

let sohbetAcikti=false;
function sohbetDurumu(){
  const ov=$('#detayOverlay');if(!ov)return;let aktif=false;try{aktif=!!_aktifKonusmaId;}catch(_){aktif=false;}
  const overlayAcik=ov.classList.contains('active'),acik=aktif&&overlayAcik;
  if(sohbetAcikti&&!overlayAcik&&aktif&&typeof _mesajPaneliTemizle==='function'){
    try{_mesajPaneliTemizle();}catch(_){}
    aktif=false;
  }
  sohbetAcikti=acik;
  ov.classList.toggle('km-chat-mode',acik);
  document.documentElement.classList.toggle('km-chat-open',acik);
  if(acik){sohbetBasliginiDuzenle();setTimeout(mesajSatirlariniHazirla,20);setTimeout(sonaKaydir,40);}
}
function sohbetBasliginiDuzenle(){const ov=$('#detayOverlay');if(!ov?.classList.contains('km-chat-mode'))return;const palette=$('#detayMesajArkaplanBtn',ov);if(palette)palette.style.display='none';const close=$('.detay-head-actions button[onclick*="detayPanelKapat"]',ov);if(close){close.classList.add('km-chat-back');close.setAttribute('aria-label','Geri');close.setAttribute('title','Geri');}}
function sonaKaydir(){const b=$('#detayBody');if(b)b.scrollTop=b.scrollHeight;}
function mesajSatirlariniHazirla(){const kutu=$('#mesajAkisKutusu');if(!kutu)return;let data=[];try{data=Array.isArray(mesajlar)?[...mesajlar].sort((a,b)=>(a.tarih||'').localeCompare(b.tarih||'')):[];}catch(_){data=[];}const satirlar=Array.from(kutu.children).filter(el=>!el.classList.contains('mesaj-tarih-ayirici')&&el.querySelector('.mesaj-balon-govde,.mesaj-dosya-karti,img'));satirlar.forEach((el,i)=>{const m=data[i];if(!m)return;el.classList.add('km-msg-row');el.dataset.messageId=m.id||'';el.querySelectorAll('.btn-mesaj-sil').forEach(b=>b.style.display='none');});}
function uzunBasSilKur(){if(window.__KM_LONG_PRESS_BOUND_V6__)return;window.__KM_LONG_PRESS_BOUND_V6__=true;let timer=null,startX=0,startY=0,target=null;const temizle=()=>{if(timer)clearTimeout(timer);timer=null;target=null;};document.addEventListener('pointerdown',e=>{const row=e.target.closest('#detayOverlay.km-chat-mode .km-msg-row');if(!row||e.target.closest('button,a,input'))return;target=row;startX=e.clientX;startY=e.clientY;timer=setTimeout(()=>{const id=target?.dataset.messageId;if(!id)return;try{navigator.vibrate?.(35);}catch(_){}target.classList.add('km-msg-selected');setTimeout(()=>target?.classList.remove('km-msg-selected'),400);if(typeof mesajTekSil==='function')mesajTekSil(id);temizle();},650);},true);document.addEventListener('pointermove',e=>{if(target&&(Math.abs(e.clientX-startX)>10||Math.abs(e.clientY-startY)>10))temizle();},true);document.addEventListener('pointerup',temizle,true);document.addEventListener('pointercancel',temizle,true);}
function servisKorumasiniKur(){if(window.__KM_SERVICE_GUARD_V6__||typeof MesajlasmaService==='undefined')return;window.__KM_SERVICE_GUARD_V6__=true;const uidCache=new Map(),uidBekleyen=new Map(),orjUid=MesajlasmaService._ogretmenUidBul.bind(MesajlasmaService);MesajlasmaService._ogretmenUidBul=function(id){if(uidCache.has(id))return Promise.resolve(uidCache.get(id));if(uidBekleyen.has(id))return uidBekleyen.get(id);const p=orjUid(id).then(uid=>{uidCache.set(id,uid||null);uidBekleyen.delete(id);return uid;}).catch(e=>{uidBekleyen.delete(id);throw e;});uidBekleyen.set(id,p);return p;};const orjBaslat=MesajlasmaService.konusmaBaslatOgretmenIle.bind(MesajlasmaService),bekleyen=new Map();MesajlasmaService.konusmaBaslatOgretmenIle=function(id,ad,mevcut,foto){if(bekleyen.has(id))return bekleyen.get(id);const p=orjBaslat(id,ad,mevcut,foto).finally(()=>bekleyen.delete(id));bekleyen.set(id,p);return p;};}
function yeniKonusmaArayuzunuKur(){if(window.__KM_NEW_CHAT_OVERRIDE_V6__||typeof window.yeniKonusmaModalAc!=='function'||typeof window.modalAc!=='function')return;window.__KM_NEW_CHAT_OVERRIDE_V6__=true;window.yeniKonusmaModalAc=function(){const bagli=typeof bagliOgretmenimGetir==='function'?bagliOgretmenimGetir():null;const secenekler=(typeof ogretmenler!=='undefined'?ogretmenler:[]).filter(o=>!bagli||o.id!==bagli.id).sort((a,b)=>(a.ad+' '+a.soyad).localeCompare(b.ad+' '+b.soyad,'tr'));const body='<div class="km-new-chat"><span class="km-new-chat-icon">'+svgChat()+'</span><div><b>Yeni sohbet</b><small>Mesaj göndereceğiniz öğretmeni seçin.</small></div></div><div class="form-group km-person-select"><label>Kişi</label><select id="f_mesajKisi"><option value="">Öğretmen seçiniz…</option>'+secenekler.map(o=>'<option value="'+esc(o.id)+'" data-ad="'+esc(o.ad+' '+o.soyad)+'" data-foto="'+esc(o.profilFotoUrl||'')+'">'+esc(o.ad+' '+o.soyad)+'</option>').join('')+'</select></div><button type="button" class="km-group-link" onclick="modalKapat();grupOlusturModalAc();">👥 Grup sohbeti oluştur</button>';modalAc('Yeni Mesaj',body,async()=>{const sel=$('#f_mesajKisi');if(!sel||!sel.value){try{toast('Bir kişi seçin.');}catch(_){}return;}const op=sel.selectedOptions[0],id=sel.value,ad=op.dataset.ad,foto=op.dataset.foto;try{modalKapat();}catch(_){}try{const konusmaId=await MesajlasmaService.konusmaBaslatOgretmenIle(id,ad,typeof konusmalar!=='undefined'?konusmalar:[],foto);for(let i=0;i<15;i++){if(Array.isArray(konusmalar)&&konusmalar.some(k=>k.id===konusmaId)){mesajKonusmaAc(konusmaId);return;}await new Promise(r=>setTimeout(r,80));}try{toast('Sohbet oluşturuldu.');}catch(_){}}catch(err){const m=err?.message||'';try{if(m==='hesap-yok')toast('Bu öğretmenin uygulamaya bağlı hesabı yok.');else if(m==='kendine-mesaj')toast('Kendinize mesaj gönderemezsiniz.');else if(m!=='yetkisiz')toast('Hata: '+m);}catch(_){}}},null);$('#modalOverlay')?.classList.add('km-message-modal');};}
function heroKur(root,list){$$('.km-msg-tools,.km-msg-filters,.km-msg-search,.km-msg-stats',root).forEach(x=>x.remove());let hero=$('.km-msg-hero',root);if(!hero){hero=document.createElement('section');hero.className='km-msg-hero';list.parentNode.insertBefore(hero,list);}hero.innerHTML='<div class="km-msg-title"><span class="km-msg-title-ico">'+svgChat()+'</span><div><h2>Mesajlar</h2><p>Okul içi güvenli iletişim</p></div></div><button type="button" class="km-msg-new" aria-label="Yeni mesaj">＋<span>Yeni Mesaj</span></button>';$('.km-msg-new',hero).onclick=()=>{if(typeof yeniKonusmaModalAc==='function')yeniKonusmaModalAc();};let meta=$('.km-msg-list-head',root);if(!meta){meta=document.createElement('div');meta.className='km-msg-list-head';list.parentNode.insertBefore(meta,list);}meta.innerHTML='<b>Sohbetler</b><span class="km-msg-count">Henüz sohbet yok</span>';const eski=eskiYeniMesaj(root);if(eski&&!eski.classList.contains('km-msg-new'))eski.style.display='none';}
function kur(){const list=$('#mesajKonusmaListesi');if(!list)return false;const root=anaKapsayici(list);if(!root)return false;root.classList.add('km-messaging');eskiBasligiGizle(root);servisKorumasiniKur();yeniKonusmaArayuzunuKur();uzunBasSilKur();heroKur(root,list);baslikSayisiniGuncelle(root,list);if(!list.dataset.kmObserve){list.dataset.kmObserve='1';new MutationObserver(()=>requestAnimationFrame(()=>baslikSayisiniGuncelle(root,list))).observe(list,{childList:true});}sohbetDurumu();return true;}
const ov=$('#detayOverlay');if(ov)new MutationObserver(()=>sohbetDurumu()).observe(ov,{attributes:true,attributeFilter:['class']});
const body=$('#detayBody');if(body)new MutationObserver(()=>requestAnimationFrame(()=>{mesajSatirlariniHazirla();sonaKaydir();})).observe(body,{childList:true,subtree:true});
let tries=0,t=setInterval(()=>{if(kur()||++tries>60)clearInterval(t);},120);
document.addEventListener('click',e=>{if(e.target.closest('.konusma-karti,[onclick*="detayPanelKapat"]'))setTimeout(sohbetDurumu,20);},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',kur,{once:true});else kur();
})();