/* Koruk Asistan — Öğrenciler Modern v1
 * Mevcut veliler[], siniflar[] ve ogrenciDetayModalAc() akışını kullanır.
 * Firestore/veri modeli değiştirilmez.
 */
(function(){
'use strict';
if(window.__KH_STUDENTS_MODERN_V1__)return;window.__KH_STUDENTS_MODERN_V1__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').trim();
function arr(n){try{return Array.isArray(eval(n))?eval(n):[]}catch(_){return[]}}
function className(id){return arr('siniflar').find(x=>x.id===id)?.ad||'Sınıfsız'}
let classFilter='';
function active(){return $('#tab-ogrenciler')?.classList.contains('active')}
function phone(v){return v.telefon1||v.telefon||v.telefon2||v.telefon3||''}
function ensure(){const root=$('#tab-ogrenciler');if(!root)return null;if(root.dataset.khStudents==='1')return root;root.dataset.khStudents='1';root.classList.add('kh-students-page');root.innerHTML=`<div class="kh-stu-head"><div><h1>Öğrenciler</h1><p>Öğrenci, sınıf ve veli bilgilerine hızlı erişim.</p></div><button type="button" class="kh-stu-add" aria-label="Yeni öğrenci">＋</button></div><div class="kh-stu-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="ogrenciArama" type="search" autocomplete="off" placeholder="Ad, soyad, öğrenci no veya sınıf ara"><button class="clear" type="button" aria-label="Temizle">×</button></div><div class="kh-stu-stats" id="khStuStats"></div><div class="kh-stu-filters" id="khStuFilters"></div><div class="kh-stu-list-head"><b id="khStuTitle">Öğrenciler</b><span id="ogrencilerOzet"></span></div><div id="ogrencilerListe" class="kh-stu-list"></div>`;
$('#ogrenciArama',root).addEventListener('input',render);$('.clear',root).onclick=()=>{$('#ogrenciArama',root).value='';render()};$('.kh-stu-add',root).onclick=()=>{if(typeof ogrenciVeliModalAc==='function')ogrenciVeliModalAc();else if(typeof ogrenciModalAc==='function')ogrenciModalAc();};return root}
function stats(all){const total=all.length,kiz=all.filter(v=>norm(v.cinsiyet)==='kiz').length,erkek=all.filter(v=>norm(v.cinsiyet)==='erkek').length,sinifSayisi=new Set(all.map(v=>v.sinifId).filter(Boolean)).size;const el=$('#khStuStats');if(el)el.innerHTML=`<div class="kh-stu-stat"><small>Toplam</small><b>${total}</b></div><div class="kh-stu-stat"><small>Erkek</small><b>${erkek}</b></div><div class="kh-stu-stat"><small>Kız</small><b>${kiz}</b></div><div class="kh-stu-stat"><small>Sınıf</small><b>${sinifSayisi}</b></div>`}
function filters(){const el=$('#khStuFilters');if(!el)return;const classes=arr('siniflar').slice().sort((a,b)=>String(a.ad||'').localeCompare(String(b.ad||''),'tr'));el.innerHTML=`<button class="kh-stu-chip ${!classFilter?'active':''}" data-id="">Tümü</button>`+classes.map(s=>`<button class="kh-stu-chip ${classFilter===s.id?'active':''}" data-id="${esc(s.id)}">${esc(s.ad||'Sınıf')}</button>`).join('');$$('.kh-stu-chip',el).forEach(b=>b.onclick=()=>{classFilter=b.dataset.id||'';filters();render()})}
function call(t,e){e.stopPropagation();if(t)location.href='tel:'+String(t).replace(/\s+/g,'')}
function message(t,e){e.stopPropagation();if(!t)return;const p=String(t).replace(/\D/g,'');const n=p.startsWith('0')?'90'+p.slice(1):p;window.open('https://wa.me/'+n,'_blank')}
function row(v){const tel=phone(v),name=v.ogrenciAdi||'Öğrenci',cls=className(v.sinifId),no=v.ogrenciNo?` · No: ${v.ogrenciNo}`:'',veli=v.veliAdi?` · ${v.veliAdi}`:'';return `<div class="kh-stu-row" data-id="${esc(v.id)}"><div class="kh-stu-avatar">${esc(String(name).trim().charAt(0).toLocaleUpperCase('tr')||'?')}</div><div class="kh-stu-main"><span class="kh-stu-name">${esc(name)}</span><span class="kh-stu-meta">${esc(cls+no+veli)}</span></div><div class="kh-stu-actions">${tel?`<button class="kh-stu-action call" data-call="${esc(tel)}" aria-label="Ara">☎</button><button class="kh-stu-action msg" data-msg="${esc(tel)}" aria-label="Mesaj">✉</button>`:''}</div><span class="kh-stu-arrow">›</span></div>`}
function render(){if(!active())return;ensure();const all=arr('veliler');stats(all);filters();const q=norm($('#ogrenciArama')?.value||'');let list=all.filter(v=>{if(classFilter&&v.sinifId!==classFilter)return false;if(!q)return true;const hay=[v.ogrenciAdi,v.ogrenciNo,v.veliAdi,v.telefon,v.telefon1,v.telefon2,v.telefon3,v.eposta,className(v.sinifId),v.servisAdi,v.kulupAdi].map(norm).join(' ');return hay.includes(q)}).sort((a,b)=>String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr'));const out=$('#ogrencilerListe'),oz=$('#ogrencilerOzet');if(oz)oz.textContent=`${list.length} öğrenci`;if(!out)return;out.innerHTML=list.length?list.map(row).join(''):'<div class="kh-stu-empty"><b>Kayıt bulunamadı</b><div>Arama ifadesini veya sınıf filtresini değiştirin.</div></div>';$$('.kh-stu-row',out).forEach(r=>r.onclick=()=>{if(typeof ogrenciDetayModalAc==='function')ogrenciDetayModalAc(r.dataset.id)});$$('[data-call]',out).forEach(b=>b.onclick=e=>call(b.dataset.call,e));$$('[data-msg]',out).forEach(b=>b.onclick=e=>message(b.dataset.msg,e))}
const old=window.renderOgrenciler;window.renderOgrenciler=function(){if(!active()){if(typeof old==='function')return old.apply(this,arguments);return}return render()};
const oldSekme=window.sekmeAc;if(typeof oldSekme==='function'&&!window.__KH_STU_TAB_WRAP__){window.__KH_STU_TAB_WRAP__=true;window.sekmeAc=function(tab){const r=oldSekme.apply(this,arguments);if(tab==='ogrenciler')setTimeout(()=>{ensure();render()},0);return r}}
function boot(){ensure();if(active())render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
