/* Koruk Asistan — Öğrenciler Modern v2
 * Mevcut veliler[], siniflar[], denemeSinavListesi[] ve testSinavListesi[] verilerini kullanır.
 * Firestore/veri modeli değiştirilmez.
 */
(function(){
'use strict';
if(window.__KH_STUDENTS_MODERN_V2__)return;window.__KH_STUDENTS_MODERN_V2__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').trim();
function arr(n){try{const v=eval(n);return Array.isArray(v)?v:[]}catch(_){return[]}}
function className(id){return arr('siniflar').find(x=>x.id===id)?.ad||'Sınıfsız'}
function active(){return $('#tab-ogrenciler')?.classList.contains('active')}
function phone(v){return v.telefon1||v.telefon||v.telefon2||v.telefon3||''}
function examList(name){return arr(name)}
let classFilter='';
function ensure(){const root=$('#tab-ogrenciler');if(!root)return null;if(root.dataset.khStudents==='2')return root;root.dataset.khStudents='2';root.classList.add('kh-students-page');root.innerHTML=`<div class="kh-stu-head"><div><h1>Öğrenciler</h1><p>Öğrenci, sınıf, veli ve sınav bilgilerine hızlı erişim.</p></div><button type="button" class="kh-stu-add" aria-label="Yeni öğrenci">＋</button></div><div class="kh-stu-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="ogrenciArama" type="search" autocomplete="off" placeholder="Ad, soyad, öğrenci no veya sınıf ara"><button class="clear" type="button" aria-label="Temizle">×</button></div><div class="kh-stu-stats" id="khStuStats"></div><div class="kh-stu-filters" id="khStuFilters"></div><div class="kh-stu-list-head"><b>Öğrenciler</b><span id="ogrencilerOzet"></span></div><div id="ogrencilerListe" class="kh-stu-list"></div>`;$('#ogrenciArama',root).addEventListener('input',render);$('.clear',root).onclick=()=>{$('#ogrenciArama',root).value='';render()};$('.kh-stu-add',root).onclick=()=>{if(typeof ogrenciVeliModalAc==='function')ogrenciVeliModalAc();else if(typeof ogrenciModalAc==='function')ogrenciModalAc()};return root}
function stats(all){const total=all.length,kiz=all.filter(v=>norm(v.cinsiyet)==='kiz').length,erkek=all.filter(v=>norm(v.cinsiyet)==='erkek').length,sinifSayisi=new Set(all.map(v=>v.sinifId).filter(Boolean)).size;const el=$('#khStuStats');if(el)el.innerHTML=`<div class="kh-stu-stat"><small>Toplam</small><b>${total}</b></div><div class="kh-stu-stat"><small>Erkek</small><b>${erkek}</b></div><div class="kh-stu-stat"><small>Kız</small><b>${kiz}</b></div><div class="kh-stu-stat"><small>Sınıf</small><b>${sinifSayisi}</b></div>`}
function filters(){const el=$('#khStuFilters');if(!el)return;const classes=arr('siniflar').slice().sort((a,b)=>String(a.ad||'').localeCompare(String(b.ad||''),'tr'));el.innerHTML=`<button class="kh-stu-chip ${!classFilter?'active':''}" data-id="">Tümü</button>`+classes.map(s=>`<button class="kh-stu-chip ${classFilter===s.id?'active':''}" data-id="${esc(s.id)}">${esc(s.ad||'Sınıf')}</button>`).join('');$$('.kh-stu-chip',el).forEach(b=>b.onclick=()=>{classFilter=b.dataset.id||'';filters();render()})}
function call(t,e){e?.stopPropagation();if(t)location.href='tel:'+String(t).replace(/\s+/g,'')}
function message(t,e){e?.stopPropagation();if(!t)return;const p=String(t).replace(/\D/g,'');const n=p.startsWith('0')?'90'+p.slice(1):p;window.open('https://wa.me/'+n,'_blank')}
function row(v){const tel=phone(v),name=v.ogrenciAdi||'Öğrenci',cls=className(v.sinifId),no=v.ogrenciNo?` · No: ${v.ogrenciNo}`:'',veli=v.veliAdi?` · ${v.veliAdi}`:'';return `<div class="kh-stu-row" data-id="${esc(v.id)}"><div class="kh-stu-avatar">${esc(String(name).trim().charAt(0).toLocaleUpperCase('tr')||'?')}</div><div class="kh-stu-main"><span class="kh-stu-name">${esc(name)}</span><span class="kh-stu-meta">${esc(cls+no+veli)}</span></div><div class="kh-stu-actions">${tel?`<button class="kh-stu-action call" data-call="${esc(tel)}" aria-label="Ara">☎</button><button class="kh-stu-action msg" data-msg="${esc(tel)}" aria-label="Mesaj">✉</button>`:''}</div><span class="kh-stu-arrow">›</span></div>`}
function render(){if(!active())return;ensure();const all=arr('veliler');stats(all);filters();const q=norm($('#ogrenciArama')?.value||'');const list=all.filter(v=>{if(classFilter&&v.sinifId!==classFilter)return false;if(!q)return true;return [v.ogrenciAdi,v.ogrenciNo,v.veliAdi,v.telefon,v.telefon1,v.telefon2,v.telefon3,v.eposta,className(v.sinifId),v.servisAdi,v.kulupAdi].map(norm).join(' ').includes(q)}).sort((a,b)=>String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr'));const out=$('#ogrencilerListe'),oz=$('#ogrencilerOzet');if(oz)oz.textContent=`${list.length} öğrenci`;if(!out)return;out.innerHTML=list.length?list.map(row).join(''):'<div class="kh-stu-empty"><b>Kayıt bulunamadı</b><div>Arama ifadesini veya sınıf filtresini değiştirin.</div></div>';$$('.kh-stu-row',out).forEach(r=>r.onclick=()=>studentDetail(r.dataset.id));$$('[data-call]',out).forEach(b=>b.onclick=e=>call(b.dataset.call,e));$$('[data-msg]',out).forEach(b=>b.onclick=e=>message(b.dataset.msg,e))}
function examMatches(studentId){const collect=(list,type)=>list.map(s=>{const sonuc=(s.sonuclar||[]).find(o=>o.ogrenciId===studentId);return sonuc?{type,sinav:s,sonuc}:null}).filter(Boolean);return collect(examList('denemeSinavListesi'),'Deneme').concat(collect(examList('testSinavListesi'),'Test')).sort((a,b)=>String(b.sinav.tarih||'').localeCompare(String(a.sinav.tarih||'')))}
function examCard(x){const ders=Object.entries(x.sonuc.dersSonuclari||{}).slice(0,3).map(([ad,d])=>`${ad}: ${Number(d.net||0).toFixed(2)} net`).join(' · ');return `<button class="kh-stu-exam" data-exam-open="1"><span class="kh-stu-exam-type ${x.type==='Deneme'?'deneme':'test'}">${x.type}</span><span class="kh-stu-exam-main"><b>${esc(x.sinav.ad||x.type)}</b><small>${esc(x.sinav.tarih||'Tarih yok')}${ders?' · '+esc(ders):''}</small></span><strong>${Number(x.sonuc.toplamNet||0).toFixed(2)}<small> net</small></strong></button>`}
function infoRow(label,value){return value?`<div class="kh-stu-info-row"><span>${esc(label)}</span><b>${esc(value)}</b></div>`:''}
function closeDetail(){const ov=$('#khStuDetail');if(ov)ov.remove();document.body.classList.remove('kh-stu-detail-open')}
function studentDetail(id){const v=arr('veliler').find(x=>x.id===id);if(!v)return;closeDetail();const tel=phone(v),exams=examMatches(id),latest=exams.slice(0,4),denemeCount=exams.filter(x=>x.type==='Deneme').length,testCount=exams.filter(x=>x.type==='Test').length,lastNet=exams.length?Number(exams[0].sonuc.toplamNet||0).toFixed(2):'—';const ov=document.createElement('div');ov.id='khStuDetail';ov.className='kh-stu-detail';ov.innerHTML=`<div class="kh-stu-detail-top"><button class="kh-stu-back" aria-label="Geri">‹</button><b>Öğrenci Detayı</b><span></span></div><div class="kh-stu-detail-body"><section class="kh-stu-profile"><div class="kh-stu-profile-avatar">${esc(String(v.ogrenciAdi||'?').trim().charAt(0).toLocaleUpperCase('tr'))}</div><div><h2>${esc(v.ogrenciAdi||'Öğrenci')}</h2><p>${esc(className(v.sinifId))}${v.ogrenciNo?' · No: '+esc(v.ogrenciNo):''}</p></div></section><div class="kh-stu-quick">${tel?`<button data-detail-call="${esc(tel)}"><span>☎</span>Ara</button><button data-detail-msg="${esc(tel)}"><span>✉</span>Mesaj</button>`:''}<button data-detail-results="1"><span>▥</span>Sınavlar</button></div><section class="kh-stu-info">${infoRow('Veli',v.veliAdi)}${infoRow('Veli Telefon',tel)}${infoRow('Cinsiyet',v.cinsiyet)}${infoRow('Servis',v.servisAdi)}${infoRow('Sosyal Kulüp',v.kulupAdi)}${infoRow('E-posta',v.eposta)}${infoRow('Adres',v.adres)}</section><section class="kh-stu-exam-summary"><div><small>Deneme</small><b>${denemeCount}</b></div><div><small>Test</small><b>${testCount}</b></div><div><small>Son Net</small><b>${lastNet}</b></div></section><section class="kh-stu-results"><div class="kh-stu-section-head"><div><b>Deneme & Test Sonuçları</b><small>En güncel kayıtlar</small></div>${exams.length?'<button data-detail-results="1">Tümünü Gör</button>':''}</div>${latest.length?latest.map(examCard).join(''):'<div class="kh-stu-no-result">Bu öğrenci için henüz deneme veya test sonucu yok.</div>'}</section></div>`;document.body.appendChild(ov);document.body.classList.add('kh-stu-detail-open');$('.kh-stu-back',ov).onclick=closeDetail;$$('[data-detail-call]',ov).forEach(b=>b.onclick=e=>call(b.dataset.detailCall,e));$$('[data-detail-msg]',ov).forEach(b=>b.onclick=e=>message(b.dataset.detailMsg,e));$$('[data-detail-results],[data-exam-open]',ov).forEach(b=>b.onclick=()=>{closeDetail();if(typeof ogrenciSinavSonuclariGoster==='function')ogrenciSinavSonuclariGoster(id)})}
window.khOgrenciDetayAc=studentDetail;
const old=window.renderOgrenciler;window.renderOgrenciler=function(){if(!active()){if(typeof old==='function')return old.apply(this,arguments);return}return render()};
const oldSekme=window.sekmeAc;if(typeof oldSekme==='function'&&!window.__KH_STU_TAB_WRAP_V2__){window.__KH_STU_TAB_WRAP_V2__=true;window.sekmeAc=function(tab){const r=oldSekme.apply(this,arguments);if(tab==='ogrenciler')setTimeout(()=>{ensure();render()},0);return r}}
function boot(){ensure();if(active())render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();