/* Koruk Asistan — Öğretmenler / Personel Merkezi
   Mevcut ogretmenler, dersProgrami, nobetAtamalari ve cizelgeVerileri kullanılır. */
(function(){'use strict';
let filtre='';
const esc=s=>typeof escapeHtml==='function'?escapeHtml(s||''):String(s||'').replace(/[&<>"']/g,'');
function veri(){return typeof ogretmenler!=='undefined'&&Array.isArray(ogretmenler)?ogretmenler:[]}
function dersler(id){return typeof dersProgrami!=='undefined'?dersProgrami.filter(d=>d.ogretmenId===id):[]}
function bugunDers(id){const gun=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'][new Date().getDay()];return dersler(id).filter(d=>d.gun===gun).sort((a,b)=>(+a.saat||0)-(+b.saat||0))}
function nobet(o){if(typeof nobetAtamalari==='undefined')return null;const ad=(o.ad+' '+o.soyad).toLocaleLowerCase('tr');return nobetAtamalari.find(n=>n.ogretmenId===o.id||String(n.ogretmenAdSoyad||'').toLocaleLowerCase('tr').includes(ad))||null}
function kulup(id){try{return (cizelgeVerileri.sosyalKulupler||[]).find(k=>Array.isArray(k.ogretmenIdler)&&k.ogretmenIdler.includes(id))||null}catch(e){return null}}
function rehber(o){try{const ad=(o.ad+' '+o.soyad).toLocaleLowerCase('tr');return (cizelgeVerileri.rehberlik||[]).find(r=>r.ogretmenId===o.id||String(r.danisman||'').toLocaleLowerCase('tr').includes(ad))||null}catch(e){return null}}
function izinli(id){try{return typeof ogretmenIzinRozeti==='function'&&!!ogretmenIzinRozeti(id)}catch(e){return false}}
function avatar(o){const src=o.fotograf||o.foto||o.photoURL||o.profilFoto||'';if(src)return `<img class="ogm-avatar" src="${esc(src)}" alt="">`;const h=((o.ad||'?')[0]+(o.soyad||'')[0]).toLocaleUpperCase('tr');return `<div class="ogm-avatar-fallback">${esc(h)}</div>`}
function kart(o){const bd=bugunDers(o.id),nb=nobet(o),kl=kulup(o.id),rh=rehber(o),hafta=dersler(o.id).length;const ilk=bd[0];return `<article class="ogm-card" data-ogretmen-id="${esc(o.id)}"><div class="ogm-card-top">${avatar(o)}<div class="ogm-name"><b>${esc((o.ad+' '+o.soyad).trim())}</b><span>${esc(o.brans||o.unvan||'Öğretmen')}</span></div><button class="ogm-more" onclick="ogretmenDetayAc('${esc(o.id)}')" aria-label="Detay">›</button></div><div class="ogm-tags">${izinli(o.id)?'<span class="ogm-tag red">İzinli</span>':''}${bd.length?`<span class="ogm-tag">Bugün ${bd.length} ders</span>`:'<span class="ogm-tag">Bugün dersi yok</span>'}${nb?'<span class="ogm-tag warn">Nöbet kaydı</span>':''}</div><div class="ogm-info">${ilk?`<div class="ogm-info-row"><span>📚</span><span>Sıradaki: ${esc(ilk.sinif||'—')} · ${esc(ilk.ders||'—')} · ${esc(ilk.saat||'—')}. ders</span></div>`:`<div class="ogm-info-row"><span>📚</span><span>Haftalık ${hafta} ders saati</span></div>`}${rh?`<div class="ogm-info-row"><span>🏫</span><span>Sınıf danışmanlığı: ${esc(rh.ad||'—')}</span></div>`:''}${kl?`<div class="ogm-info-row"><span>👥</span><span>Kulüp: ${esc(kl.ad||'—')}</span></div>`:''}${o.telefon?`<div class="ogm-info-row"><span>☎</span><span>${esc(o.telefon)}</span></div>`:''}</div><div class="ogm-actions"><button class="ogm-action primary" onclick="ogretmenDetayAc('${esc(o.id)}')">Profili Gör</button><button class="ogm-action" onclick="ogretmenModalAc('${esc(o.id)}')">Düzenle</button></div></article>`}
function render(){const tab=document.getElementById('tab-ogretmenler');if(!tab)return;tab.classList.add('ogm-modern');const q=(document.getElementById('ogmAra')?.value||'').toLocaleLowerCase('tr');let list=veri().filter(o=>{const s=(o.ad+' '+o.soyad+' '+(o.brans||'')+' '+(o.unvan||'')).toLocaleLowerCase('tr');return(!q||s.includes(q))&&(!filtre||String(o.brans||'')===filtre)}).sort((a,b)=>(a.ad||'').localeCompare(b.ad||'','tr'));const brans=[...new Set(veri().map(o=>o.brans).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'));const nobetSay=veri().filter(o=>!!nobet(o)).length;tab.innerHTML=`<div class="ogm-shell"><div class="ogm-head"><div class="ogm-title"><small>Koruk Asistan · Personel</small><h2>Öğretmenler</h2><p>Personel bilgileri, program ve sorumluluklar tek ekranda.</p></div><button class="ogm-add" onclick="ogretmenModalAc()">+ Öğretmen</button></div><div class="ogm-stats"><div class="ogm-stat"><b>${veri().length}</b><span>Öğretmen</span></div><div class="ogm-stat"><b>${brans.length}</b><span>Branş</span></div><div class="ogm-stat"><b>${nobetSay}</b><span>Nöbet Kaydı</span></div></div><div class="ogm-tools"><label class="ogm-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input id="ogmAra" value="${esc(document.getElementById('ogmAra')?.value||'')}" placeholder="Öğretmen veya branş ara…" oninput="window.OgretmenlerModern.render()"></label><select class="ogm-filter" onchange="window.OgretmenlerModern.filtrele(this.value)"><option value="">Tüm branşlar</option>${brans.map(b=>`<option ${filtre===b?'selected':''}>${esc(b)}</option>`).join('')}</select></div><div class="ogm-grid">${list.length?list.map(kart).join(''):'<div class="ogm-empty">Arama ölçütlerine uygun öğretmen bulunamadı.</div>'}</div></div>`}
function kur(){const btn=document.querySelector('[data-tab="ogretmenler"]');if(btn&&!btn.dataset.ogm){btn.dataset.ogm='1';btn.addEventListener('click',()=>setTimeout(render,80))}const tab=document.getElementById('tab-ogretmenler');if(tab&&tab.classList.contains('active'))render()}
window.OgretmenlerModern={render,filtrele:v=>{filtre=v;render()},kur};
document.addEventListener('DOMContentLoaded',kur);setTimeout(kur,1200);
})();