/* Koruk Asistan — Takvim modern mobil görünüm. Veri modeli ve servisler korunur. */
(function(){
'use strict';
if(window.__KORUK_TAKVIM_MODERN__) return; window.__KORUK_TAKVIM_MODERN__=true;
const mobil=()=>window.matchMedia('(max-width:1023px)').matches;
let seciliGun='';
function esc(v){return typeof escapeHtml==='function'?escapeHtml(v||''):String(v||'')}
function bugun(){return typeof _isoToday==='function'?_isoToday():(new Date()).toISOString().slice(0,10)}
function trGun(iso){try{return new Date(iso+'T00:00:00').toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'})}catch(_){return iso}}
function listeler(){return {e:typeof hatirlaticilar!=='undefined'?hatirlaticilar:[],g:typeof gorevler!=='undefined'?gorevler:[],p:typeof periyodikIsler!=='undefined'?periyodikIsler:[]}}
function ozetGuncelle(){const {e,g,p}=listeler(),b=bugun();const eBug=e.filter(x=>typeof etkinlikBuGundeAktifMi==='function'&&etkinlikBuGundeAktifMi(x,b)&&!x.tamamlandi).length;const gBug=g.filter(x=>x.sonTarih===b&&!(typeof gorevTamamlandiMi==='function'&&gorevTamamlandiMi(x))).length;const gecik=g.filter(x=>x.sonTarih&&x.sonTarih<b&&!(typeof gorevTamamlandiMi==='function'&&gorevTamamlandiMi(x))).length+p.filter(x=>!x.tamamlandi&&x.bitis&&x.bitis<b).length;const a=document.getElementById('tkOzetEtkinlik'),c=document.getElementById('tkOzetGorev'),d=document.getElementById('tkOzetGeciken');if(a)a.textContent=eBug;if(c)c.textContent=gBug;if(d)d.textContent=gecik}
function seciliIsaretle(){document.querySelectorAll('#tab-takvim .takvim-hucre').forEach(h=>{const o=h.getAttribute('onclick')||'';h.classList.toggle('tk-secili',!!seciliGun&&o.includes("'"+seciliGun+"'"))})}
function sahipEtiketi(uid){if(!uid||typeof kullaniciYonetimiYetkisiVar!=='function'||!kullaniciYonetimiYetkisiVar()||typeof _sahipAdiGetir!=='function')return '';const ad=_sahipAdiGetir(uid);return ad&&ad!=='Ben'?` · ${esc(ad)}`:''}
function gunPanelRender(){const panel=document.getElementById('takvimSeciliGunPanel');if(!panel)return;const iso=seciliGun||bugun();seciliGun=iso;const {e,g,p}=listeler();const etkin=e.filter(x=>typeof etkinlikBuGundeAktifMi==='function'&&etkinlikBuGundeAktifMi(x,iso));const gorev=g.filter(x=>x.sonTarih===iso);const per=p.filter(x=>!x.tamamlandi&&(x.baslangic===iso||x.bitis===iso));let html='';etkin.forEach(x=>{html+=`<div class="tk-day-item event"><span class="tk-day-icon">⏰</span><div class="tk-day-main"><b>${esc(x.baslik)}</b><small>${x.saat?esc(x.saat)+' · ':''}${esc(x.oncelik||'Orta')}${x.tekrar&&x.tekrar.tip?' · Tekrarlı':''}${sahipEtiketi(x.sahipUid)}</small></div><button class="tk-day-edit" onclick="takvimEtkinlikDuzenle('${x.id}')">Düzenle</button></div>`});gorev.forEach(x=>{const tamam=typeof gorevTamamlandiMi==='function'&&gorevTamamlandiMi(x);html+=`<div class="tk-day-item task"><span class="tk-day-icon">${tamam?'✓':'☑'}</span><div class="tk-day-main"><b>${esc(x.baslik)}</b><small>${tamam?'Tamamlandı':'Görev'} · ${esc(x.oncelik||'Orta')}${sahipEtiketi(x.sahipUid)}</small></div><button class="tk-day-edit" onclick="takvimGorevDuzenle('${x.id}')">Düzenle</button></div>`});per.forEach(x=>{const t=x.bitis===iso?'Bitiş':'Başlangıç';html+=`<div class="tk-day-item periodic"><span class="tk-day-icon">↻</span><div class="tk-day-main"><b>${esc(x.isAdi||'Periyodik iş')}</b><small>${t}${x.bitis?' · '+esc(x.bitis):''}</small></div><span></span></div>`});if(!html)html='<div class="tk-empty">Bu gün için kayıt yok. Aşağıdaki butonlarla hızlıca ekleyebilirsiniz.</div>';panel.innerHTML=`<div class="tk-day-head"><div><h3>${trGun(iso)}</h3><small>${etkin.length} etkinlik · ${gorev.length} görev · ${per.length} periyodik</small></div><div class="tk-day-actions"><button class="event" onclick="takvimEtkinlikEkle('${iso}')">+ Etkinlik</button><button onclick="takvimGorevEkle('${iso}')">+ Görev</button></div></div><div class="tk-day-body">${html}</div>`;seciliIsaretle()}
function kabukKur(){if(!mobil())return false;const p=document.getElementById('tab-takvim');if(!p)return false;if(p.classList.contains('tk-modern'))return true;p.classList.add('tk-modern');p.innerHTML=`<div class="page-header"><div><div class="page-title">TAKVİM</div></div></div><div class="tk-shell"><section class="tk-hero"><span class="tk-kicker">KORUK ASİSTAN</span><h1>Takvim</h1><p>Etkinlikleri, görevleri ve yaklaşan işleri tek ekranda yönetin.</p><div class="tk-summary"><div><b id="tkOzetEtkinlik">0</b><span>Bugünkü etkinlik</span></div><div><b id="tkOzetGorev">0</b><span>Bugünkü görev</span></div><div><b id="tkOzetGeciken">0</b><span>Geciken iş</span></div></div></section><section class="tk-calendar-card"><div class="tk-nav"><button onclick="takvimAyDegistir(-1)" aria-label="Önceki ay">‹</button><div class="tk-month"><b id="takvimAyBasligi"></b><small>Bir güne dokunarak ayrıntıları görün</small></div><button onclick="takvimAyDegistir(1)" aria-label="Sonraki ay">›</button></div><div class="tk-tools"><button onclick="takvimBugunGit();takvimModernGunSec('${bugun()}')">Bugün</button><button class="primary" onclick="takvimEtkinlikEkle(seciliGun||'${bugun()}')">+ Yeni Etkinlik</button></div><div class="takvim-grid" id="takvimGrid"></div></section><section class="tk-day-card" id="takvimSeciliGunPanel"></section><section class="tk-agenda-card"><div class="tk-agenda-head"><div><h3>Yaklaşan 30 Gün</h3><small>Etkinlik, görev ve periyodik işler</small></div></div><div id="takvimAjanda"></div></section></div>`;seciliGun=bugun();return true}
window.takvimModernGunSec=function(iso){seciliGun=iso;gunPanelRender()};
function sar(){if(!mobil()||typeof window.takvimGridRender!=='function'||typeof window.takvimAjandaRender!=='function')return false;if(window.__TK_SARILDI__)return true;window.__TK_SARILDI__=true;const grid=window.takvimGridRender,aj=window.takvimAjandaRender,ay=window.takvimAyDegistir,bg=window.takvimBugunGit,veri=window.takvimVeriGuncelle;window.takvimGridRender=function(){const r=grid.apply(this,arguments);setTimeout(()=>{seciliIsaretle();ozetGuncelle()},0);return r};window.takvimAjandaRender=function(){const r=aj.apply(this,arguments);setTimeout(ozetGuncelle,0);return r};window.takvimAyDegistir=function(d){const r=ay.apply(this,arguments);setTimeout(()=>{seciliIsaretle();ozetGuncelle()},0);return r};window.takvimBugunGit=function(){const r=bg.apply(this,arguments);seciliGun=bugun();setTimeout(gunPanelRender,0);return r};if(typeof veri==='function')window.takvimVeriGuncelle=function(){const r=veri.apply(this,arguments);setTimeout(()=>{ozetGuncelle();gunPanelRender()},0);return r};window.takvimGunTikla=function(iso){window.takvimModernGunSec(iso)};return true}
function baslat(){if(!mobil())return;if(!kabukKur())return;let n=0;const t=setInterval(()=>{if(sar()||++n>100){clearInterval(t);try{takvimGridRender();takvimAjandaRender()}catch(_){}ozetGuncelle();gunPanelRender()}},50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',baslat);else setTimeout(baslat,0);
window.addEventListener('koruk:data-updated',()=>setTimeout(()=>{ozetGuncelle();gunPanelRender()},0));
})();
