/* Koruk Asistan — klasik header davranışı. Router/tema sahibi ShellUI olarak kalır. */
(function(global){
'use strict';
if(global.KaHeaderUI)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const user=()=>global.AppStore?.get?.('session.user')||global.AKTIF_KULLANICI||{};
let popup=null,observer=null,menuCustomizerRequested=false;
const icon={profile:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 21a8 8 0 0 1 16 0" fill="none" stroke="currentColor" stroke-width="2"/></svg>',settings:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 12h2m12 0h2M12 4v2m0 12v2M6.3 6.3l1.4 1.4m8.6 8.6 1.4 1.4m0-11.4-1.4 1.4m-8.6 8.6-1.4 1.4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>',moon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z" fill="none" stroke="currentColor" stroke-width="2"/></svg>',logout:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 17l5-5-5-5M15 12H3M14 3h6a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'};
function close(){popup?.remove();popup=null;document.removeEventListener('pointerdown',outside,true)}
function outside(e){if(!popup)return;if(popup.contains(e.target)||e.target.closest('[data-ka-header-profile],[data-ka-header-notification]'))return;close()}
function pop(anchor,width=390){close();const r=anchor.getBoundingClientRect();popup=document.createElement('div');popup.className='ka-card ka-classic-header-popover';popup.setAttribute('role','dialog');popup.style.cssText=`position:fixed;z-index:1110;top:${Math.max(r.bottom+8,76)}px;right:${Math.max(10,innerWidth-r.right)}px;width:min(${width}px,calc(100vw - 20px));max-height:calc(100dvh - ${Math.max(r.bottom+22,92)}px);overflow:auto;background:var(--ka-card-raised-bg);border:1px solid var(--ka-border);border-radius:24px;box-shadow:var(--ka-shadow-modal);padding:0`;document.body.appendChild(popup);setTimeout(()=>document.addEventListener('pointerdown',outside,true),0);return popup}
function linkedTeacher(){const u=user(),id=u.bagliOgretmenId||u.ogretmenId;return id?arr('ogretmenler').find(x=>x.id===id)||null:null}
function profileInfo(){const u=user(),t=linkedTeacher(),name=t?[t.ad,t.soyad].filter(Boolean).join(' '):(u.adSoyad||[u.ad,u.soyad].filter(Boolean).join(' ')||u.displayName||u.kullaniciAdi||'Kullanıcı'),photo=t?.profilFotoUrl||t?.fotoUrl||u.profilFotoUrl||u.fotoUrl||'',username=u.kullaniciAdi?`@${u.kullaniciAdi}`:(u.email||''),role=u.admin?'Yönetici':(t?.brans||u.unvan||u.rolAdi||u.rol||'Kullanıcı');return{u,t,name,photo,username,role}}
function openProfile(anchor){const {name,photo,username,role}=profileInfo(),dark=document.documentElement.getAttribute('data-theme')==='dark',p=pop(anchor,360);p.innerHTML=`<div style="padding:22px 20px 15px"><div style="display:flex;gap:13px;align-items:center"><span class="ka-avatar" style="width:54px;height:54px;flex:0 0 54px;border:1px solid var(--ka-border)">${photo?`<img src="${esc(photo)}" alt="${esc(name)}">`:icon.profile}</span><div style="min-width:0"><strong style="display:block;font-size:17px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(name)}</strong><small class="ka-muted" style="display:block;margin-top:2px">${esc(username)}</small><span class="ka-badge ka-badge--success" style="margin-top:6px">${esc(role)}</span></div></div><div style="height:1px;background:var(--ka-border);margin:16px 0 10px"></div><div class="ka-stack" style="gap:2px"><button class="ka-btn ka-btn--ghost" data-hu-profile style="justify-content:flex-start;min-height:50px">${icon.profile}<span>Profilim</span></button><button class="ka-btn ka-btn--ghost" data-hu-settings style="justify-content:flex-start;min-height:50px">${icon.settings}<span>Ayarlar</span></button><button class="ka-btn ka-btn--ghost" data-hu-theme style="justify-content:flex-start;min-height:50px">${icon.moon}<span>${dark?'Açık Temaya Geç':'Koyu Temaya Geç'}</span></button><div style="height:1px;background:var(--ka-border);margin:5px 0"></div><button class="ka-btn ka-btn--ghost" data-hu-logout style="justify-content:flex-start;min-height:50px;color:var(--ka-danger)">${icon.logout}<span>Çıkış Yap</span></button></div></div>`;
 p.querySelector('[data-hu-profile]')?.addEventListener('click',()=>{close();global.ShellUI?.renderProfile?.()});
 p.querySelector('[data-hu-settings]')?.addEventListener('click',()=>{close();global.ShellUI?.routeModule?.('settings',{bottom:'menu'})});
 p.querySelector('[data-hu-theme]')?.addEventListener('click',async()=>{await global.ShellUI?.toggleTheme?.();openProfile(anchor)});
 p.querySelector('[data-hu-logout]')?.addEventListener('click',()=>{if(confirm('Hesabınızdan çıkış yapmak istediğinize emin misiniz?'))global.cikisYap?.()});
}
function dateOf(x){const v=x?.tarih||x?.sonTarih||x?.baslangicTarihi||x?.olusturmaTarihi||x?.guncellenmeTarihi;if(!v)return null;try{const d=v?.toDate?v.toDate():new Date(String(v).length===10?`${v}T00:00:00`:v);return isNaN(d)?null:d}catch(_){return null}}
function rows(){const now=new Date(),limit=new Date(now.getTime()+45*86400000),out=[],me=user().uid||'';for(const x of arr('hatirlaticilar')){if(x?.tamamlandi===true)continue;const d=dateOf(x);if(!d||d<now||d>limit)continue;out.push({type:'Etkinlik',icon:'⏰',title:x.baslik||x.ad||x.konu||x.aciklama||'Yaklaşan etkinlik',date:d,time:x.saat||'',page:'calendar',count:1})}if(me)for(const k of arr('konusmalar')){const n=Number(k?.okunmayanlar?.[me]||0);if(n<1)continue;const other=Object.entries(k.katilimciAdlari||{}).filter(([id])=>id!==me).map(([,ad])=>ad).filter(Boolean).join(', ');out.push({type:'Mesaj',icon:'💬',title:k.grupMu?(k.grupAdi||'Grup mesajı'):(other||'Yeni mesaj'),date:dateOf(k.sonMesaj||k)||now,page:'messages',count:n})}if(me)for(const d of arr('duyurular')){if(d?.arsivlendi===true||d?.aktif===false||d?.okuyanlar?.[me])continue;out.push({type:'Duyuru',icon:'📣',title:d.baslik||'Yeni duyuru',date:dateOf(d)||now,page:'announcements',count:1})}return out.sort((a,b)=>b.date-a.date).slice(0,20)}
function fmt(d,time=''){const ds=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);return `${ds}${time?` · ${time}`:''}`}
function syncBell(){const bell=$('[data-ka-header-notification]'),badge=$('[data-ka-notification-count]'),list=rows(),count=list.reduce((n,r)=>n+Math.max(1,Number(r.count)||1),0);if(bell){bell.hidden=false;bell.style.position='relative';bell.style.border='1px solid var(--ka-header-border)';bell.style.borderRadius='14px';bell.style.width='44px';bell.style.height='44px';bell.style.background='var(--ka-card-bg)'}if(badge){badge.textContent=String(Math.min(count,99));badge.hidden=count<1;badge.style.cssText='position:absolute;right:-3px;top:-5px;min-width:19px;height:19px;padding:0 5px;border-radius:999px;display:grid;place-items:center;background:#d9a514;color:#fff;font-size:10px;font-weight:900;border:2px solid var(--ka-header-bg)'}return list}
function openNotifications(anchor){const list=syncBell(),p=pop(anchor,410);p.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;padding:15px 17px;border-bottom:1px solid var(--ka-border)"><strong style="font-size:17px">Bildirimler</strong><button class="ka-link-button" data-hu-all type="button">Tümünü Gör</button></div><div>${list.length?list.map((r,i)=>`<button type="button" data-hu-notice="${i}" style="appearance:none;width:100%;border:0;border-bottom:1px solid var(--ka-border);background:transparent;color:var(--ka-text);padding:13px 16px;display:grid;grid-template-columns:36px minmax(0,1fr) 8px;gap:10px;align-items:center;text-align:left"><span style="font-size:22px">${r.icon}</span><span><strong style="display:block;font-size:14px">${esc(r.title)}</strong><small class="ka-muted" style="display:block;margin-top:4px">${esc(fmt(r.date,r.time))}</small></span><i style="width:7px;height:7px;border-radius:50%;background:#d9a514"></i></button>`).join(''):'<div class="ka-empty" style="margin:14px">Yeni bildirim bulunmuyor.</div>'}</div>`;
 p.querySelector('[data-hu-all]')?.addEventListener('click',()=>{close();global.ShellUI?.routeModule?.('communication',{bottom:'menu',page:'calendar',title:'Takvim'})});
 $$('[data-hu-notice]',p).forEach(b=>b.addEventListener('click',()=>{const r=list[Number(b.dataset.huNotice)];if(!r)return;close();global.ShellUI?.routeModule?.('communication',{bottom:'menu',page:r.page,title:r.type==='Mesaj'?'Mesajlaşma':r.type==='Duyuru'?'Duyurular':'Takvim'})}));
}
function capture(e){const profile=e.target.closest?.('[data-ka-header-profile]');if(profile){e.preventDefault();e.stopImmediatePropagation();openProfile(profile);return}const bell=e.target.closest?.('[data-ka-header-notification]');if(bell){e.preventDefault();e.stopImmediatePropagation();openNotifications(bell);return}}
function lazyMenuCustomizer(e){if(global.MenuCustomizer||menuCustomizerRequested||!e.target.closest?.('[data-ka-shell-action="menu"]'))return;menuCustomizerRequested=true;setTimeout(()=>{const p=global.AppLoader?.loadScript?.('js/core/menu-customizer.js');if(!p){menuCustomizerRequested=false;return}Promise.resolve(p).then(()=>{global.MenuCustomizer?.bind?.();global.MenuCustomizer?.apply?.();global.ShellUI?.renderMenuGrid?.()}).catch(err=>{menuCustomizerRequested=false;console.warn('[MenuCustomizer lazy]',err?.message||err)})},0)}
function init(){document.addEventListener('click',capture,true);document.addEventListener('click',lazyMenuCustomizer);syncBell();const header=$('.ka-app-header');if(header){observer=new MutationObserver(()=>queueMicrotask(syncBell));observer.observe(header,{subtree:true,attributes:true,attributeFilter:['hidden','style']})}for(const type of ['hatirlaticilar','konusmalar','duyurular'])global.AppStore?.subscribe?.('data.'+type,()=>requestAnimationFrame(syncBell));global.AppStore?.subscribe?.('session.user',()=>requestAnimationFrame(syncBell));}
global.KaHeaderUI={init,openProfile,openNotifications,syncBell,close};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
