/* Koruk Asistan — ortak rapor çıktı / paylaşım katmanı
 * Web + Android WebView + iOS Web/PWA için platform bağımsız API.
 * Özel raporların içeriğine müdahale etmez; çağıran katman seçer.
 */
(function(w){
'use strict';
if(w.KAReportOutput)return;
const enc=new TextEncoder();
function escXml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function bytes(s){return enc.encode(s)}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}
function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function concat(parts){let n=0;parts.forEach(p=>n+=p.length);const o=new Uint8Array(n);let i=0;parts.forEach(p=>{o.set(p,i);i+=p.length});return o}
function crc32(data){let c=0xffffffff;for(let i=0;i<data.length;i++){c^=data[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function zipStore(files){const local=[],central=[];let offset=0;files.forEach(f=>{const name=bytes(f.name),data=typeof f.data==='string'?bytes(f.data):f.data,crc=crc32(data);const h=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name]);local.push(h,data);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=h.length+data.length});const cd=concat(central);return new Blob([concat(local),cd,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(offset),u16(0)],{type:'application/zip'})}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);return true}
function rowsFromTable(table){return [...table.rows].map(r=>[...r.cells].map(c=>String(c.innerText??c.textContent??'').trim()))}
function firstTable(root){return root?.querySelector?.('table')||null}
function xlsx(rows,title){const now=new Date().toISOString();const sheetRows=rows.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>{const ref=String.fromCharCode(65+(ci%26))+((ri+1));return `<c r="${ref}" t="inlineStr"><is><t>${escXml(v)}</t></is></c>`}).join('')}</row>`).join('');const files=[
{name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'},
{name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},
{name:'xl/workbook.xml',data:`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${escXml(title||'Rapor')}" sheetId="1" r:id="rId1"/></sheets></workbook>`},
{name:'xl/_rels/workbook.xml.rels',data:'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'},
{name:'xl/worksheets/sheet1.xml',data:`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheetRows}</sheetData></worksheet>`}
];return zipStore(files)}
function docx(rows,title){const p=(s)=>`<w:p><w:r><w:t xml:space="preserve">${escXml(s)}</w:t></w:r></w:p>`;const table='<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single"/><w:left w:val="single"/><w:bottom w:val="single"/><w:right w:val="single"/><w:insideH w:val="single"/><w:insideV w:val="single"/></w:tblBorders></w:tblPr>'+rows.map(r=>'<w:tr>'+r.map(v=>`<w:tc><w:p><w:r><w:t>${escXml(v)}</w:t></w:r></w:p></w:tc>`).join('')+'</w:tr>').join('')+'</w:tbl>';const documentXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${p(title||'Rapor')}${table}<w:sectPr/></w:body></w:document>`;return zipStore([
{name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'},
{name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'},
{name:'word/document.xml',data:documentXml}
])}
function htmlBlob(html){return new Blob([`<!doctype html><html><head><meta charset="utf-8"></head><body>${html}</body></html>`],{type:'text/html;charset=utf-8'})}
async function png(root,title){if(!root)throw new Error('Rapor içeriği bulunamadı.');const clone=root.cloneNode(true);clone.style.cssText='position:absolute;left:-100000px;top:0;background:#fff;color:#111;padding:24px;width:'+Math.max(800,root.scrollWidth||800)+'px;';document.body.appendChild(clone);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${clone.scrollWidth||800}" height="${clone.scrollHeight||600}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">${clone.outerHTML}</div></foreignObject></svg>`;const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);try{const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});const c=document.createElement('canvas');c.width=clone.scrollWidth||800;c.height=clone.scrollHeight||600;c.getContext('2d').drawImage(img,0,0);return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('PNG oluşturulamadı.')),'image/png'))}finally{URL.revokeObjectURL(url);clone.remove()}}
function pdf(root){if(!root)throw new Error('Rapor içeriği bulunamadı.');const w2=window.open('','_blank');if(!w2)throw new Error('Yazdırma penceresi açılamadı.');w2.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Rapor</title><style>@page{margin:12mm}body{font-family:Arial,sans-serif}table{border-collapse:collapse;width:100%}th,td{border:1px solid #888;padding:5px}</style></head><body>'+root.innerHTML+'</body></html>');w2.document.close();w2.focus();setTimeout(()=>{w2.print();},250);return true}
async function exportReport({root,title='rapor',format='pdf'}){format=String(format).toLowerCase();const safe=normFile(title||'rapor').replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'')||'rapor';const table=firstTable(root),rows=table?rowsFromTable(table):[];if(format==='xlsx'||format==='excel'){return download(xlsx(rows,title),safe+'.xlsx')}if(format==='docx'||format==='word'){return download(docx(rows,title),safe+'.docx')}if(format==='png'){return download(await png(root,title),safe+'.png')}if(format==='pdf'){return pdf(root)}if(format==='html'){return download(htmlBlob(root?.innerHTML||''),safe+'.html')}throw new Error('Desteklenmeyen çıktı biçimi: '+format)}
function normFile(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c')}
async function share(blob,name,title){if(!navigator.share)return false;const file=new File([blob],name,{type:blob.type||'application/octet-stream'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:title||name,files:[file]});return true}return false}
w.KAReportOutput=Object.freeze({export:exportReport,download,share,xlsx,docx,png,pdf});
})(window);