/* Koruk Asistan — V2 Shell UI
 * Eski Koruk Asistan UX hiyerarşisi yeni local-first mimaride yeniden üretilir.
 * Eski JS/CSS dosyalarına çalışma zamanı bağımlılığı yoktur.
 */
(function(global){
'use strict';
if(global.ShellUI)return;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const user=()=>global.AppStore?.get?.('session.user')||global.AKTIF_KULLANICI||{};
const SVG={
 home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11 12 3l9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>',
 profile:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 21a8 8 0 0 1 16 0" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>',
 search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="2"/><path d="m20 20-4-4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 note:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h14v18H5z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M8 8h8M8 12h8M8 16h5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 back:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
 chevron:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
 settings:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-width="2"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.04.04-2.86 2.86-.04-.04A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 1.55V21h-4v-.05A1.7 1.7 0 0 0 9 19.4a1.7 1.7 0 0 0-1.88.34l-.04.04-2.86-2.86.04-.04A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.55-1H3v-4h.05A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.34-1.88l-.04-.04 2.86-2.86.04.04A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.55V3h4v.05A1.7 1.7 0 0 0 15 4.6a1.7 1.7 0 0 0 1.88-.34l.04-.04 2.86 2.86-.04.04A1.7 1.7 0 0 0 19.4 9a1.7 1.7 0 0 0 1.55 1H21v4h-.05A1.7 1.7 0 0 0 19.4 15Z" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>',
 moon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z" fill="none" stroke="currentColor" stroke-width="2"/></svg>',
 sun:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 logout:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 17l5-5-5-5M15 12H3M14 3h6a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'
};
const MENU_GROUPS=[
 {key:'people',label:'Öğretmen & Öğrenciler',icon:'👥',tone:'green',route:'people',items:[['Öğretmenler','👩‍🏫','people'],['Öğrenciler','🎓','people'],['Sınıflar','🏫','people'],['Öğrenci Yoklama','☑️','people'],['Öğrenci Listesi Oluşturucu','📋','tools'],['Ödev Takip Çizelgesi','✅','tools'],['Not Çizelgesi','📊','tools']]},
 {key:'exams',label:'Sınavlar ve Not İşlemleri',icon:'📝',tone:'violet',route:'academic',items:[['Yazılı Sınavlar','☑️','academic'],['Deneme Sınavları','🧪','academic'],['Deneme Sonuçları','🏅','academic'],['Test Sonuçları','📋','academic'],['Ders Et. Kat. Puan Dağıtımı','📊','tools'],['Proje Değerlendirme Ölçeği','📏','tools']]},
 {key:'programs',label:'Programlar',icon:'📅',tone:'green',route:'academic',items:[['Ders Programı','📅','academic'],['Nöbet Programı','🛡️','management'],['Yıllık Plan','📚','academic']]},
 {key:'communication',label:'İletişim & Haberler',icon:'💬',tone:'red',route:'communication',items:[['Mesajlaşma','💬','communication'],['Haberler','📰','communication'],['Duyurular','📣','communication'],['Anketler','📋','communication']]},
 {key:'calendar',label:'Takvim & Notlar',icon:'📆',tone:'cyan',route:'communication',items:[['Takvim','📆','communication'],['Notlar','📒','communication']]},
 {key:'transport',label:'Taşıma',icon:'🚌',tone:'violet',route:'transport',items:[['Taşıma İşlemleri','🚌','transport'],['Harita','🗺️','tools']]},
 {key:'documents',label:'Doküman & Evraklar',icon:'📁',tone:'amber',route:'documents',items:[['Dokümanlar','📁','documents'],['Mevzuat','📖','documents'],['Akademik Takvim','📅','documents'],['Kontrol Listeleri','📋','tools'],['Evrak Takibi','📄','documents'],['Aylık İşler','🕘','management']],subLabel:'Raporlar',subItems:[['Maarif Model','🏅','documents'],['Belirli Gün ve Haftalar','📅','documents'],['ŞÖK','🛡️','documents'],['Rehberlik','🧭','documents'],['Yıllık Planlar & BEP Planları','📋','documents'],['Zümre','👥','documents'],['Sosyal Kulüpler','♡','documents']]},
 {key:'management',label:'İdari İşler',icon:'🗂️',tone:'orange',route:'management',items:[['Personeller','👥','management'],['Maaş Değişikliği','💵','payroll'],['Tebliğ-Tebellüğ İmza Sirküsü','🔔','documents'],['Puantaj & İmza Sirküsü','🕘','management'],['Dilekçe & İzinler','📄','management'],['Devamsızlık Çizelgesi','📅','tools'],['Evrak Takibi','📄','documents']]},
 {key:'settings',label:'Ayarlar',icon:'⚙️',tone:'slate',route:'settings',items:[['Ayarlar','⚙️','settings'],['Okul Bilgileri','🏢','settings'],['Veriler','🗄️','settings'],['Kullanıcı İşlemleri','🛡️','settings'],['Kullanıcı İstatistikleri','📋','settings']]}
];
const DASHBOARD_ROUTES={announcements:'communication',polls:'communication',news:'communication',stats:'people',duty:'management',absences:'management',upcoming:'communication',lessons:'academic','week-duty':'management',exams:'academic',schedule:'academic',notes:'communication',calendar:'communication'};
let activeAction='home',menuGroup=null,visibilityObserver=null,headerPopover=null;
function setTitle(v){const el=$('#v2ModuleTitle');if(el)el.textContent=v||''}
function setBottomActive(action){activeAction=action;$$('[data-ka-shell-action]').forEach(b=>{const on=b.dataset.kaShellAction===action;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')})}
function moduleAllowed(name){const meta=global.AppConfig?.module?.(name);return meta?.visible!==false&&global.PermissionService?.moduleLevel?.(name)!=='hidden'}
function closeMenu(){const layer=$('#kaMenuLayer');if(layer){layer.classList.remove('open');layer.hidden=true;layer.innerHTML=''}menuGroup=null;document.body.classList.remove('ka-layer-open')}
function closeHeaderPopover(){headerPopover?.remove();headerPopover=null;document.removeEventListener('pointerdown',outsideHeaderPopover,true)}
function outsideHeaderPopover(e){if(!headerPopover)return;if(headerPopover.contains(e.target)||e.target.closest('[data-ka-header-profile],[data-ka-header-notification],[data-ka-theme-toggle]'))return;closeHeaderPopover()}
function popoverBase(anchor,width=330){closeHeaderPopover();const r=anchor.getBoundingClientRect(),el=document.createElement('div');el.className='ka-card';el.setAttribute('role','dialog');el.style.cssText=`position:fixed;z-index:1100;top:${Math.max(r.bottom+8,70)}px;right:${Math.max(10,innerWidth-r.right)}px;width:min(${width}px,calc(100vw - 20px));max-height:calc(100dvh - ${Math.max(r.bottom+22,86)}px);overflow:auto;background:var(--ka-card-raised-bg);border:1px solid var(--ka-border);border-radius:18px;box-shadow:var(--ka-shadow-modal);padding:12px;`;document.body.appendChild(el);headerPopover=el;setTimeout(()=>document.addEventListener('pointerdown',outsideHeaderPopover,true),0);return el}
async function routeModule(name,{bottom='menu'}={}){
  closeHeaderPopover();closeMenu();
  /* Özel rotalar — ayrı eager-loaded modüller */
  if(name==='payroll'){
    if(global.PayrollChangeModule?.open){
      setBottomActive(bottom);setTitle('Maaş Değişikliği Bildirim Formu');
      global.PayrollChangeModule.open();
    }else{
      await routeModule('management',{bottom});
    }
    return true;
  }
  const meta=global.AppConfig?.module?.(name)||{label:name};
  if(meta.visible===false||global.PermissionService?.moduleLevel?.(name)==='hidden')return false;
  setBottomActive(bottom);global.AppLoader?.setActiveModule?.(name);
  setTitle(meta.label||name);await global.AppLoader?.load?.(name);return true
}
function visibleItems(g){return(g.items||[]).filter(x=>moduleAllowed(x[2])).concat((g.subItems||[]).filter(x=>moduleAllowed(x[2])))}
function visibleGroups(){return MENU_GROUPS.filter(g=>moduleAllowed(g.route)&&visibleItems(g).length)}
function menuCount(g){return visibleItems(g).length}
function renderMenuGrid(){const layer=$('#kaMenuLayer');if(!layer)return;menuGroup=null;const cards=visibleGroups();layer.innerHTML=`<div class="ka-menu-page"><header class="ka-menu-head"><h2>Menü</h2><button type="button" class="ka-icon-button" data-ka-menu-close aria-label="Menüyü kapat">${SVG.close}</button></header><div class="ka-menu-grid">${cards.map(g=>`<button type="button" class="ka-menu-card ka-menu-card--${g.tone}" data-ka-menu-group="${g.key}"><span class="ka-menu-card__icon">${g.icon}</span><strong>${esc(g.label)}</strong><span class="ka-badge">${menuCount(g)}</span></button>`).join('')}</div></div>`;layer.querySelector('[data-ka-menu-close]')?.addEventListener('click',closeMenu);$$('[data-ka-menu-group]',layer).forEach(b=>b.addEventListener('click',()=>renderMenuList(b.dataset.kaMenuGroup)))}
function listRow(item){return`<button type="button" class="ka-btn ka-btn--secondary" data-ka-menu-route="${item[2]}"><span class="ka-avatar">${item[1]}</span><strong class="ka-grow">${esc(item[0])}</strong><span>${SVG.chevron}</span></button>`}
function renderMenuList(key){const layer=$('#kaMenuLayer'),g=MENU_GROUPS.find(x=>x.key===key);if(!layer||!g)return;menuGroup=key;const main=(g.items||[]).filter(x=>moduleAllowed(x[2])),sub=(g.subItems||[]).filter(x=>moduleAllowed(x[2]));layer.innerHTML=`<div class="ka-menu-page"><header class="ka-menu-head"><button type="button" class="ka-icon-button" data-ka-menu-back aria-label="Menüye dön">${SVG.back}</button><h2 class="ka-grow">${esc(g.label)}</h2></header><div class="ka-stack ka-page">${main.map(listRow).join('')}${sub.length?`<h3>${esc(g.subLabel||'Diğer')}</h3>${sub.map(listRow).join('')}`:''}</div></div>`;layer.querySelector('[data-ka-menu-back]')?.addEventListener('click',renderMenuGrid);$$('[data-ka-menu-route]',layer).forEach(b=>b.addEventListener('click',()=>routeModule(b.dataset.kaMenuRoute,{bottom:'menu'})))}
function openMenu(){closeHeaderPopover();const layer=$('#kaMenuLayer');if(!layer)return;renderMenuGrid();layer.hidden=false;requestAnimationFrame(()=>layer.classList.add('open'));document.body.classList.add('ka-layer-open');setBottomActive('menu')}
function syncVisibilityClasses(){for(const id of ['girisEkrani','onayBekleniyorEkrani','app']){const el=document.getElementById(id);if(el)el.classList.toggle('ka-hidden',el.hidden)}}
function observeVisibility(){if(visibilityObserver)return;syncVisibilityClasses();visibilityObserver=new MutationObserver(syncVisibilityClasses);for(const id of ['girisEkrani','onayBekleniyorEkrani','app']){const el=document.getElementById(id);if(el)visibilityObserver.observe(el,{attributes:true,attributeFilter:['hidden']})}}
function normalizeDashboardLayout(){return !!$('.ka-home[data-dashboard-role]')}
function profileName(u){return u.adSoyad||[u.ad,u.soyad].filter(Boolean).join(' ')||u.displayName||u.kullaniciAdi||'Kullanıcı'}
function profileRole(u){return u.unvan||u.rolAdi||u.rol||u.brans||'Koruk Asistan Kullanıcısı'}
function linkedTeacher(){const id=user().bagliOgretmenId;return id?arr('ogretmenler').find(x=>x.id===id)||null:null}
function profileInfo(){const u=user(),t=linkedTeacher(),name=t?[t.ad,t.soyad].filter(Boolean).join(' '):profileName(u),role=t?.brans||profileRole(u),photo=t?.profilFotoUrl||t?.fotoUrl||u.profilFotoUrl||u.fotoUrl||'',username=u.kullaniciAdi?`@${u.kullaniciAdi}`:(u.email||'');return{u,t,name,role,photo,username}}
function renderProfile(){closeHeaderPopover();closeMenu();setBottomActive('profile');setTitle('Profilim');const {u,t,name,role,photo}=profileInfo(),root=$('#v2ModuleRoot');if(!root)return;const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toLocaleUpperCase('tr');root.innerHTML=`<section class="ka-profile-page"><div class="ka-profile-hero"><div class="ka-profile-avatar">${photo?`<img src="${esc(photo)}" alt="${esc(name)}">`:esc(initials||'K')}</div><div class="ka-profile-copy"><h2>${esc(name)}</h2><p>${esc(role)}</p>${t?.telefon||u.telefon?`<small>☎ ${esc(t?.telefon||u.telefon)}</small>`:''}${t?.email||u.email?`<small>✉ ${esc(t?.email||u.email)}</small>`:''}</div></div><div class="ka-profile-section"><h3>Çizelgelerim</h3><div class="ka-profile-grid"><button type="button" data-profile-route="academic">📅<span>Ders Programım</span></button><button type="button" data-profile-route="management">🛡️<span>Nöbetlerim</span></button><button type="button" data-profile-route="academic">📏<span>Sınavlarım</span></button><button type="button" data-profile-route="documents">📄<span>Diğer Görevlerim</span></button></div></div><button type="button" class="ka-logout-button" data-profile-logout>↪ Oturumu Kapat</button></section>`;$$('[data-profile-route]',root).forEach(b=>b.addEventListener('click',()=>routeModule(b.dataset.profileRoute,{bottom:'profile'})));root.querySelector('[data-profile-logout]')?.addEventListener('click',()=>{if(confirm('Hesabınızdan çıkış yapmak istediğinize emin misiniz?'))global.cikisYap?.()})}
function currentTheme(){return document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light'}
function syncThemeButton(){const dark=currentTheme()==='dark',btn=$('[data-ka-theme-toggle]');if(btn){btn.classList.remove('ka-hidden');btn.innerHTML=dark?SVG.sun:SVG.moon;btn.setAttribute('aria-label',dark?'Açık temaya geç':'Koyu temaya geç');btn.title=dark?'Açık temaya geç':'Koyu temaya geç'}global.AppStore?.set?.('ui.theme',dark?'dark':'light');const meta=$('meta[data-ka-theme-color]');if(meta)meta.content=dark?'#0d1118':'#17684f'}
async function applyTheme(theme,{persist=true}={}){const next=theme==='dark'?'dark':'light';if(next==='dark')document.documentElement.setAttribute('data-theme','dark');else document.documentElement.removeAttribute('data-theme');syncThemeButton();if(persist){const uid=user().uid;if(uid&&global.KorukLocalFirst?.meta)await global.KorukLocalFirst.meta(uid,'theme',next).catch(()=>{})}window.dispatchEvent(new CustomEvent('koruk:theme-changed',{detail:{theme:next}}));return next}
function toggleTheme(){return applyTheme(currentTheme()==='dark'?'light':'dark')}
async function hydrateTheme(){const uid=user().uid;if(!uid){syncThemeButton();return}let saved=null;try{saved=await global.KorukLocalFirst?.meta?.(uid,'theme')}catch(_){}await applyTheme(saved==='dark'?'dark':'light',{persist:false})}
function openProfilePopover(){const anchor=$('[data-ka-header-profile]');if(!anchor)return;const {name,username,photo}=profileInfo(),p=popoverBase(anchor,360),dark=currentTheme()==='dark';p.innerHTML=`<div style="padding:10px 10px 12px;border-bottom:1px solid var(--ka-border);display:flex;gap:11px;align-items:center"><span class="ka-avatar" style="width:46px;height:46px;flex-basis:46px">${photo?`<img src="${esc(photo)}" alt="">`:SVG.profile}</span><div style="min-width:0"><strong style="display:block;font-size:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(name)}</strong><small class="ka-muted">${esc(username)}</small></div></div><div class="ka-stack" style="gap:4px;padding-top:8px"><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start" data-hp-profile>${SVG.profile}<span>Profilim</span></button><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start" data-hp-settings>${SVG.settings}<span>Ayarlar</span></button><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start" data-hp-theme>${dark?SVG.sun:SVG.moon}<span>${dark?'Açık Temaya Geç':'Koyu Temaya Geç'}</span></button><div style="height:1px;background:var(--ka-border);margin:4px 0"></div><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start;color:var(--ka-danger)" data-hp-logout>${SVG.logout}<span>Çıkış Yap</span></button></div>`;p.querySelector('[data-hp-profile]')?.addEventListener('click',renderProfile);p.querySelector('[data-hp-settings]')?.addEventListener('click',()=>routeModule('settings',{bottom:'menu'}));p.querySelector('[data-hp-theme]')?.addEventListener('click',async()=>{await toggleTheme();openProfilePopover()});p.querySelector('[data-hp-logout]')?.addEventListener('click',()=>{if(confirm('Hesabınızdan çıkış yapmak istediğinize emin misiniz?'))global.cikisYap?.()})}
function dateOf(x){const v=x?.tarih||x?.sonTarih||x?.baslangicTarihi||x?.olusturmaTarihi;if(!v)return null;try{const d=v?.toDate?v.toDate():new Date(String(v).length===10?`${v}T00:00:00`:v);return isNaN(d)?null:d}catch(_){return null}}
function notificationRows(){const now=new Date(),limit=new Date(now.getTime()+45*86400000),seen=new Set(),rows=[];for(const [type,source] of [['Görev',arr('gorevler')],['Hatırlatıcı',arr('hatirlaticilar')]])for(const x of source){const d=dateOf(x);if(!d||d<new Date(now.getTime()-7*86400000)||d>limit)continue;const title=x.baslik||x.ad||x.konu||x.aciklama||type,key=`${type}:${x.id||title}:${d.toISOString()}`;if(seen.has(key))continue;seen.add(key);rows.push({type,title,date:d,time:x.saat||'',id:x.id})}return rows.sort((a,b)=>a.date-b.date).slice(0,12)}
function formatNoticeDate(d,time=''){const ds=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);return `${ds}${time?` · ${time}`:''}`}
function updateNotificationBadge(){const rows=notificationRows(),count=rows.filter(x=>x.date>=new Date()).length,b=$('[data-ka-notification-count]');if(!b)return;b.textContent=String(Math.min(count,99));b.hidden=count<1}
function openNotifications(){const anchor=$('[data-ka-header-notification]');if(!anchor)return;const p=popoverBase(anchor,400),rows=notificationRows();p.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding:6px 6px 10px;border-bottom:1px solid var(--ka-border)"><strong style="font-size:17px">Bildirimler</strong><span class="ka-badge">${rows.length}</span></div><div style="display:flex;flex-direction:column">${rows.length?rows.map(r=>`<button type="button" class="ka-btn ka-btn--ghost" data-notice-row style="min-height:70px;border-radius:0;justify-content:flex-start;text-align:left;border-bottom:1px solid var(--ka-border);padding:10px 8px"><span style="font-size:21px">⏰</span><span style="min-width:0"><strong style="display:block;white-space:normal">${esc(r.title)}</strong><small class="ka-muted">${esc(formatNoticeDate(r.date,r.time))}</small></span></button>`).join(''):'<div class="ka-empty" style="margin-top:10px">Yaklaşan bildirim bulunmuyor.</div>'}</div>`;$$('[data-notice-row]',p).forEach(b=>b.addEventListener('click',()=>routeModule('communication',{bottom:'menu'})))}
function norm(v){return String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function searchRows(q){const n=norm(q),rows=[];for(const x of arr('ogretmenler')){const title=x.adSoyad||[x.ad,x.soyad].filter(Boolean).join(' ')||'Öğretmen';if(!n||norm(`${title} ${x.brans||''} ${x.telefon||''}`).includes(n))rows.push({type:'Öğretmen',icon:'👩‍🏫',title,meta:x.brans||x.unvan||''})}for(const x of arr('veliler')){const title=x.ogrenciAdi||x.adSoyad||x.ad||'Öğrenci';if(!n||norm(`${title} ${x.veliAdi||''} ${x.telefon||''} ${x.sinif||x.sinifAdi||''}`).includes(n))rows.push({type:'Öğrenci',icon:'🎓',title,meta:[x.sinifAdi||x.sinif,x.veliAdi].filter(Boolean).join(' · ')})}for(const x of arr('servisler')){const title=x.servisAdi||x.guzergah||x.plaka||'Servis';if(!n||norm(`${title} ${x.plaka||''} ${x.soforAdi||''}`).includes(n))rows.push({type:'Servis',icon:'🚌',title,meta:[x.plaka,x.soforAdi].filter(Boolean).join(' · ')})}for(const x of arr('evrakTakibi')){const title=x.evrakAdi||x.baslik||x.konu||'Evrak';if(!n||norm(`${title} ${x.durum||''}`).includes(n))rows.push({type:'Evrak',icon:'📄',title,meta:x.durum||''})}return rows.slice(0,80)}
function renderSearchResults(root,q){const out=root.querySelector('[data-shell-search-results]'),rows=searchRows(q);if(!out)return;out.innerHTML=rows.length?rows.map(r=>`<article class="ka-search-result"><span>${r.icon}</span><div><strong>${esc(r.title)}</strong><small>${esc([r.type,r.meta].filter(Boolean).join(' · '))}</small></div></article>`).join(''):'<div class="ka-empty">Eşleşen kayıt bulunamadı.</div>'}
function renderSearch(){closeHeaderPopover();closeMenu();setBottomActive('search');setTitle('Arama');const root=$('#v2ModuleRoot');if(!root)return;root.innerHTML=`<section class="ka-search-page"><div class="ka-search-box">${SVG.search}<input type="search" data-shell-search-input placeholder="İsim, sınıf, telefon, servis, evrak…" autocomplete="off"></div><div class="ka-search-chips"><span>Öğrenci</span><span>Öğretmen</span><span>Servis</span><span>Evrak</span></div><div data-shell-search-results></div></section>`;const input=root.querySelector('[data-shell-search-input]');input?.addEventListener('input',()=>renderSearchResults(root,input.value));renderSearchResults(root,'');setTimeout(()=>input?.focus(),40)}
function closeQuickNote(){document.getElementById('kaQuickNoteModal')?.remove()}
function openQuickNote(){closeHeaderPopover();closeMenu();setBottomActive('note');closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Hızlı Not</h3><p class="ka-muted">Aklınızdakini hemen kaydedin</p></div><button type="button" class="ka-icon-button" data-note-close aria-label="Kapat">${SVG.close}</button></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Notunuz</span><textarea data-note-text rows="7" placeholder="Notunuzu yazın..."></textarea></label><div class="ka-note-colors"><button type="button" data-note-color="yesil" class="active">●</button><button type="button" data-note-color="mavi">●</button><button type="button" data-note-color="mor">●</button><button type="button" data-note-color="turuncu">●</button></div></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);let color='yesil';$$('[data-note-color]',ov).forEach(b=>b.addEventListener('click',()=>{$$('[data-note-color]',ov).forEach(x=>x.classList.remove('active'));b.classList.add('active');color=b.dataset.noteColor}));const close=()=>{closeQuickNote();setBottomActive(global.AppStore?.get?.('ui.route')==='dashboard'?'home':'menu')};ov.querySelector('[data-note-close]')?.addEventListener('click',close);ov.querySelector('[data-note-cancel]')?.addEventListener('click',close);ov.querySelector('[data-note-save]')?.addEventListener('click',async()=>{const text=ov.querySelector('[data-note-text]')?.value.trim();if(!text)return;const u=user();try{await global.DeviceData?.add?.('notlar',global.COL?.notlar,{baslik:'Hızlı Not',icerik:text,not:text,renk:color,sahipUid:u.uid||'',tarih:new Date().toISOString(),olusturmaTarihi:new Date().toISOString()});close();global.toast?.('Not kaydedildi.')}catch(e){console.error('[QuickNote]',e);global.toast?.('Not kaydedilemedi.')}});setTimeout(()=>ov.querySelector('[data-note-text]')?.focus(),30)}
function home(){closeHeaderPopover();closeMenu();setBottomActive('home');return routeModule('dashboard',{bottom:'home'})}
function bindHeader(){document.querySelector('[data-ka-home-trigger]')?.addEventListener('click',home);document.querySelector('[data-ka-header-profile]')?.addEventListener('click',openProfilePopover);document.querySelector('[data-ka-header-notification]')?.addEventListener('click',openNotifications);document.querySelector('[data-ka-theme-toggle]')?.addEventListener('click',toggleTheme)}
function bindBottom(){$$('[data-ka-shell-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.kaShellAction;if(a==='home')home();else if(a==='profile')renderProfile();else if(a==='menu')openMenu();else if(a==='search')renderSearch();else if(a==='note')openQuickNote()}))}
function bindDashboardCards(){document.addEventListener('click',e=>{if(e.target.closest('button,a,input,select,textarea,label'))return;const hero=e.target.closest('.ka-home-hero');if(hero){routeModule('academic',{bottom:'menu'});return}const card=e.target.closest('[data-home-section]');if(!card)return;const target=DASHBOARD_ROUTES[card.dataset.homeSection];if(target)routeModule(target,{bottom:'menu'});})}
function hydrateHeader(){const {name,photo}=profileInfo(),profile=$('[data-ka-header-profile]');if(profile){const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toLocaleUpperCase('tr');profile.innerHTML=photo?`<img src="${esc(photo)}" alt="${esc(name)}">`:esc(initials||'K');profile.setAttribute('aria-label',`${name} hesabı`)}updateNotificationBadge();syncThemeButton()}
function init(){observeVisibility();bindHeader();bindBottom();bindDashboardCards();hydrateHeader();hydrateTheme();window.addEventListener('koruk:app-ready',()=>{syncVisibilityClasses();hydrateHeader();hydrateTheme()});window.addEventListener('koruk:app-config-changed',()=>{if(!$('#kaMenuLayer')?.hidden){menuGroup?renderMenuList(menuGroup):renderMenuGrid()}});global.AppStore?.subscribe?.('session.user',()=>{syncVisibilityClasses();hydrateHeader();hydrateTheme()});for(const type of ['gorevler','hatirlaticilar','ogretmenler'])global.AppStore?.subscribe?.('data.'+type,hydrateHeader)}
global.ShellUI={init,home,openMenu,closeMenu,routeModule,renderProfile,renderSearch,openQuickNote,openProfilePopover,openNotifications,toggleTheme,applyTheme,renderMenuGrid,renderMenuList,normalizeDashboardLayout,syncVisibilityClasses,MENU_GROUPS,DASHBOARD_ROUTES};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);