/* Koruk Asistan — V2 Shell UI
 * Eski uygulamanın kullanıcı deneyimi yeni mimari üzerinde yeniden üretilir.
 * Veri erişimi yalnız AppStore / DeviceData üzerinden yapılır.
 */
(function(global){
'use strict';
if(global.ShellUI)return;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const user=()=>global.AppStore?.get?.('session.user')||global.AKTIF_KULLANICI||{};
const SVG={
 home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11 12 3l9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>',
 profile:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 21a8 8 0 0 1 16 0" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>',
 search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="2"/><path d="m20 20-4-4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 note:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h14v18H5z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M8 8h8M8 12h8M8 16h5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'
};
const MENU=[
 {key:'people',label:'Öğretmen & Öğrenciler',icon:'👥',tone:'green'},
 {key:'academic',label:'Akademik İşlemler',icon:'📚',tone:'violet'},
 {key:'management',label:'Yönetim İşlemleri',icon:'🗂️',tone:'orange'},
 {key:'communication',label:'İletişim',icon:'💬',tone:'cyan'},
 {key:'transport',label:'Taşımalı Eğitim',icon:'🚌',tone:'amber'},
 {key:'documents',label:'Doküman & Rapor',icon:'📄',tone:'red'},
 {key:'tools',label:'Araçlar',icon:'🧰',tone:'purple'},
 {key:'settings',label:'Sistem & Ayarlar',icon:'⚙️',tone:'slate'}
];
let activeAction='home';
function setTitle(v){const el=$('#v2ModuleTitle');if(el)el.textContent=v||''}
function setBottomActive(action){activeAction=action;$$('[data-ka-shell-action]').forEach(b=>{const on=b.dataset.kaShellAction===action;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')})}
function closeMenu(){const layer=$('#kaMenuLayer');if(layer){layer.classList.remove('open');layer.hidden=true}document.body.classList.remove('ka-layer-open')}
async function routeModule(name,{bottom='menu'}={}){closeMenu();const meta=global.AppConfig?.module?.(name)||{label:name};if(meta.visible===false||global.PermissionService?.moduleLevel?.(name)==='hidden')return false;setBottomActive(bottom);global.AppLoader?.setActiveModule?.(name);setTitle(meta.label||name);await global.AppLoader?.load?.(name);return true}
function renderMenu(){const layer=$('#kaMenuLayer');if(!layer)return;const cards=MENU.filter(m=>{const meta=global.AppConfig?.module?.(m.key);return meta?.visible!==false&&global.PermissionService?.moduleLevel?.(m.key)!=='hidden'});layer.innerHTML=`<div class="ka-menu-page"><header class="ka-menu-head"><h2>Menü</h2><button type="button" class="ka-icon-button" data-ka-menu-close aria-label="Menüyü kapat">${SVG.close}</button></header><div class="ka-menu-grid">${cards.map(m=>`<button type="button" class="ka-menu-card ka-menu-card--${m.tone}" data-ka-menu-module="${m.key}"><span class="ka-menu-card__icon">${m.icon}</span><strong>${esc(m.label)}</strong></button>`).join('')}</div></div>`;layer.querySelector('[data-ka-menu-close]')?.addEventListener('click',closeMenu);$$('[data-ka-menu-module]',layer).forEach(b=>b.addEventListener('click',()=>routeModule(b.dataset.kaMenuModule,{bottom:'menu'})))}
function openMenu(){const layer=$('#kaMenuLayer');if(!layer)return;renderMenu();layer.hidden=false;requestAnimationFrame(()=>layer.classList.add('open'));document.body.classList.add('ka-layer-open');setBottomActive('menu')}
function profileName(u){return u.adSoyad||[u.ad,u.soyad].filter(Boolean).join(' ')||u.displayName||u.kullaniciAdi||'Kullanıcı'}
function profileRole(u){return u.unvan||u.rolAdi||u.rol||u.brans||'Koruk Asistan Kullanıcısı'}
function renderProfile(){closeMenu();setBottomActive('profile');setTitle('Profilim');const u=user(),root=$('#v2ModuleRoot');if(!root)return;const name=profileName(u),initials=name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toLocaleUpperCase('tr');root.innerHTML=`<section class="ka-profile-page"><div class="ka-profile-hero"><div class="ka-profile-avatar">${u.fotoUrl?`<img src="${esc(u.fotoUrl)}" alt="${esc(name)}">`:esc(initials||'K')}</div><div class="ka-profile-copy"><h2>${esc(name)}</h2><p>${esc(profileRole(u))}</p>${u.email?`<small>${esc(u.email)}</small>`:''}</div></div><div class="ka-profile-section"><h3>Hesabım</h3><div class="ka-profile-grid"><button type="button" data-profile-route="academic">📅<span>Ders Programım</span></button><button type="button" data-profile-route="management">🛡️<span>Nöbetlerim</span></button><button type="button" data-profile-route="communication">🔔<span>Bildirimler</span></button><button type="button" data-profile-route="settings">⚙️<span>Ayarlar</span></button></div></div><button type="button" class="ka-logout-button" data-profile-logout>↪ Çıkış Yap</button></section>`;$$('[data-profile-route]',root).forEach(b=>b.addEventListener('click',()=>routeModule(b.dataset.profileRoute,{bottom:'profile'})));root.querySelector('[data-profile-logout]')?.addEventListener('click',()=>global.cikisYap?.())}
function norm(v){return String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function searchRows(q){const n=norm(q);const rows=[];for(const x of arr('ogretmenler')){const title=x.adSoyad||[x.ad,x.soyad].filter(Boolean).join(' ')||'Öğretmen';if(!n||norm(`${title} ${x.brans||''} ${x.telefon||''}`).includes(n))rows.push({type:'Öğretmen',icon:'👩‍🏫',title,meta:x.brans||x.unvan||''})}for(const x of arr('veliler')){const title=x.ogrenciAdi||x.adSoyad||x.ad||'Öğrenci';if(!n||norm(`${title} ${x.veliAdi||''} ${x.telefon||''} ${x.sinif||x.sinifAdi||''}`).includes(n))rows.push({type:'Öğrenci',icon:'🎓',title,meta:[x.sinifAdi||x.sinif,x.veliAdi].filter(Boolean).join(' · ')})}for(const x of arr('servisler')){const title=x.servisAdi||x.guzergah||x.plaka||'Servis';if(!n||norm(`${title} ${x.plaka||''} ${x.soforAdi||''}`).includes(n))rows.push({type:'Servis',icon:'🚌',title,meta:[x.plaka,x.soforAdi].filter(Boolean).join(' · ')})}for(const x of arr('evrakTakibi')){const title=x.evrakAdi||x.baslik||x.konu||'Evrak';if(!n||norm(`${title} ${x.durum||''}`).includes(n))rows.push({type:'Evrak',icon:'📄',title,meta:x.durum||''})}return rows.slice(0,80)}
function renderSearchResults(root,q){const out=root.querySelector('[data-shell-search-results]'),rows=searchRows(q);if(!out)return;out.innerHTML=rows.length?rows.map(r=>`<article class="ka-search-result"><span>${r.icon}</span><div><strong>${esc(r.title)}</strong><small>${esc([r.type,r.meta].filter(Boolean).join(' · '))}</small></div></article>`).join(''):'<div class="ka-empty">Eşleşen kayıt bulunamadı.</div>'}
function renderSearch(){closeMenu();setBottomActive('search');setTitle('Arama');const root=$('#v2ModuleRoot');if(!root)return;root.innerHTML=`<section class="ka-search-page"><div class="ka-search-box">${SVG.search}<input type="search" data-shell-search-input placeholder="İsim, sınıf, telefon, servis, evrak…" autocomplete="off"></div><div class="ka-search-chips"><span>Öğrenci</span><span>Öğretmen</span><span>Servis</span><span>Evrak</span></div><div data-shell-search-results></div></section>`;const input=root.querySelector('[data-shell-search-input]');input?.addEventListener('input',()=>renderSearchResults(root,input.value));renderSearchResults(root,'');setTimeout(()=>input?.focus(),40)}
function closeQuickNote(){document.getElementById('kaQuickNoteModal')?.remove()}
function openQuickNote(){closeMenu();setBottomActive('note');closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Hızlı Not</h3><p class="ka-muted">Aklınızdakini hemen kaydedin</p></div><button type="button" class="ka-icon-button" data-note-close aria-label="Kapat">${SVG.close}</button></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Notunuz</span><textarea data-note-text rows="7" placeholder="Notunuzu yazın..."></textarea></label><div class="ka-note-colors"><button type="button" data-note-color="yesil" class="active">●</button><button type="button" data-note-color="mavi">●</button><button type="button" data-note-color="mor">●</button><button type="button" data-note-color="turuncu">●</button></div></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);let color='yesil';$$('[data-note-color]',ov).forEach(b=>b.addEventListener('click',()=>{$$('[data-note-color]',ov).forEach(x=>x.classList.remove('active'));b.classList.add('active');color=b.dataset.noteColor}));const close=()=>{closeQuickNote();setBottomActive(global.AppStore?.get?.('ui.route')==='dashboard'?'home':'menu')};ov.querySelector('[data-note-close]')?.addEventListener('click',close);ov.querySelector('[data-note-cancel]')?.addEventListener('click',close);ov.querySelector('[data-note-save]')?.addEventListener('click',async()=>{const text=ov.querySelector('[data-note-text]')?.value.trim();if(!text)return;const u=user();try{await global.DeviceData?.add?.('notlar',global.COL?.notlar,{baslik:'Hızlı Not',icerik:text,not:text,renk:color,sahipUid:u.uid||'',tarih:new Date().toISOString(),olusturmaTarihi:new Date().toISOString()});close();global.toast?.('Not kaydedildi.')}catch(e){console.error('[QuickNote]',e);global.toast?.('Not kaydedilemedi.')}});setTimeout(()=>ov.querySelector('[data-note-text]')?.focus(),30)}
function home(){closeMenu();setBottomActive('home');return routeModule('dashboard',{bottom:'home'})}
function bindHeader(){document.querySelector('[data-ka-home-trigger]')?.addEventListener('click',home);document.querySelector('[data-ka-header-profile]')?.addEventListener('click',renderProfile)}
function bindBottom(){$$('[data-ka-shell-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.kaShellAction;if(a==='home')home();else if(a==='profile')renderProfile();else if(a==='menu')openMenu();else if(a==='search')renderSearch();else if(a==='note')openQuickNote()}))}
function hydrateHeader(){const u=user(),profile=$('[data-ka-header-profile]');if(profile){const n=profileName(u),initials=n.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toLocaleUpperCase('tr');profile.textContent=initials||'K';profile.setAttribute('aria-label',`${n} profili`)}}
function init(){bindHeader();bindBottom();hydrateHeader();window.addEventListener('koruk:app-ready',hydrateHeader);window.addEventListener('koruk:app-config-changed',()=>{if(!$('#kaMenuLayer')?.hidden)renderMenu()});global.AppStore?.subscribe?.('session.user',hydrateHeader)}
global.ShellUI={init,home,openMenu,closeMenu,routeModule,renderProfile,renderSearch,openQuickNote};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
