/* Koruk Asistan — V2 Shell UI
 * Eski Koruk Asistan UX hiyerarşisi yeni local-first mimaride yeniden üretilir.
 * Eski JS/CSS dosyalarına çalışma zamanı bağımlılığı yoktur.
 */
(function(global){
'use strict';
if(global.ShellUI)return;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const user=()=>global.AppStore?.get?.('session.user')||global.AKTIF_KULLANICI||{};
const SVG={
 home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11 12 3l9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>',
 profile:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M4 21a8 8 0 0 1 16 0" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>',
 search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="2"/><path d="m20 20-4-4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 note:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h14v18H5z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M8 8h8M8 12h8M8 16h5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 back:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
 chevron:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
 settings:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-width="2"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.04.04-2.86 2.86-.04-.04A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 1.55V21h-4v-.05A1.7 1.7 0 0 0 9 19.4a1.7 1.7 0 0 0-1.88.34l-.04.04-2.86-2.86.04-.04A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.55-1H3v-4h.05A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.34-1.88l-.04-.04 2.86-2.86.04.04A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.55V3h4v.05A1.7 1.7 0 0 0 15 4.6a1.7 1.7 0 0 0 1.88-.34l.04-.04 2.86 2.86-.04.04A1.7 1.7 0 0 0 19.4 9a1.7 1.7 0 0 0 1.55 1H21v4h-.05A1.7 1.7 0 0 0 19.4 15Z" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>',
 moon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z" fill="none" stroke="currentColor" stroke-width="2"/></svg>',
 sun:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',
 logout:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 17l5-5-5-5M15 12H3M14 3h6a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'
};
const MENU_GROUPS=[
 {key:'people',label:'Öğretmen & Öğrenciler',icon:'👥',tone:'green',route:'people',items:[['Öğretmenler','👩‍🏫','people','teachers'],['Öğrenciler','🎓','people','students'],['Sınıflar','🏫','people','classes'],['Öğrenci Yoklama','☑️','tools','student-attendance'],['Öğrenci Listesi Oluşturucu','📋','tools','student-list'],['Ödev Takip Çizelgesi','✅','tools','homework'],['Not Çizelgesi','📊','tools','grades']]},
 {key:'exams',label:'Sınavlar ve Not İşlemleri',icon:'📝',tone:'violet',route:'academic',items:[['Yazılı Sınavlar','☑️','academic','written'],['Deneme Sınavları','🧪','academic','trial'],['Deneme Sonuçları','🏅','academic','results'],['Test Sonuçları','📋','academic','results'],['Ders Et. Kat. Puan Dağıtımı','📊','tools','rubric'],['Proje Değerlendirme Ölçeği','📏','tools','project']]},
 {key:'programs',label:'Programlar',icon:'📅',tone:'green',route:'academic',items:[['Ders Programı','📅','academic','schedule'],['Nöbet Programı','🛡️','management','duty'],['Yıllık Plan','📚','academic','plans']]},
 {key:'communication',label:'İletişim & Haberler',icon:'💬',tone:'red',route:'communication',items:[['Mesajlaşma','💬','communication','messages'],['Haberler','📰','communication','news'],['Duyurular','📣','communication','announcements'],['Anketler','📋','communication','polls']]},
 {key:'calendar',label:'Takvim & Notlar',icon:'📆',tone:'cyan',route:'communication',items:[['Takvim','📆','communication','calendar'],['Notlar','📒','communication','notes']]},
 {key:'transport',label:'Taşıma',icon:'🚌',tone:'violet',route:'transport',items:[['Servisler','🚌','transport','services'],['Servis Oturma','💺','transport','busSeats'],['Sınıf Oturma','🏫','transport','classSeats'],['Harita','🗺️','tools','map']]},
 {key:'documents',label:'Doküman & Evraklar',icon:'📁',tone:'amber',route:'documents',items:[['Dokümanlar','📁','documents'],['Mevzuat','📖','documents','mevzuat'],['Akademik Takvim','📅','academic','calendar'],['Kontrol Listeleri','📋','tools','checklists'],['Evrak Takibi','📄','documents','evrak'],['Aylık İşler','🕘','management','tasks']],subLabel:'Raporlar',subItems:[['Maarif Model','🏅','tools','form-maarif'],['Belirli Gün ve Haftalar','📅','tools','form-belirli'],['ŞÖK','🛡️','tools','form-sok'],['Rehberlik','🧭','tools','form-rehberlik'],['Yıllık Planlar & BEP Planları','📋','tools','form-bep'],['Zümre','👥','tools','form-zumre'],['Sosyal Kulüpler','♡','tools','form-kulup']]},
 {key:'management',label:'İdari İşler',icon:'🗂️',tone:'orange',route:'management',items:[['Personeller','👥','management','staff'],['Maaş Değişikliği','💵','payroll'],['Tebliğ-Tebellüğ İmza Sirküsü','🔔','documents','teblig'],['Puantaj & İmza Sirküsü','🕘','management','puantaj'],['Dilekçe & İzinler','📄','management','dilekce'],['Devamsızlık Çizelgesi','📅','tools','attendance'],['Evrak Takibi','📄','documents','evrak']]},
 {key:'settings',label:'Ayarlar',icon:'⚙️',tone:'slate',route:'settings',items:[['Ayarlar','⚙️','settings'],['Okul Bilgileri','🏢','settings','school'],['Veriler','🗄️','settings','data'],['Kullanıcı İşlemleri','🛡️','settings','users'],['Kullanıcı İstatistikleri','📋','settings','statistics']]}
];
const FORM_PAGES=Object.freeze({'form-maarif':'Maarif Model Raporları','form-belirli':'Belirli Günler ve Haftalar','form-sok':'ŞÖK','form-rehberlik':'Rehberlik','form-bep':'BEP Planları','form-zumre':'Zümre','form-kulup':'Sosyal Kulüpler'});
const CUSTOM_PAGE_ROUTES=new Map();
const DASHBOARD_ROUTES={announcements:{module:'communication',page:'announcements',title:'Duyurular'},polls:{module:'communication',page:'polls',title:'Anketler'},news:{module:'communication',page:'news',title:'Haberler'},duty:{module:'management',page:'duty',title:'Nöbet Programı'},'today-duty':{module:'management',page:'duty',title:'Nöbet Programı'},absences:{module:'management',page:'leaves',title:'İzinler'},upcoming:{module:'communication',page:'calendar',title:'Takvim'},lessons:{module:'academic',page:'schedule',title:'Ders Programı'},'week-duty':{module:'management',page:'duty',title:'Nöbet Programı'},exams:{module:'academic',page:'written',title:'Yazılı Sınavlar'},schedule:{module:'academic',page:'schedule',title:'Ders Programı'},notes:{module:'communication',page:'notes',title:'Notlar'},calendar:{module:'communication',page:'calendar',title:'Takvim'}};
let activeAction='home',menuGroup=null,visibilityObserver=null,layerObserver=null,headerPopover=null,themeTouched=false;
function registerPageRoute(page,handler){page=String(page||'').trim();if(!page||typeof handler!=='function')return()=>{};CUSTOM_PAGE_ROUTES.set(page,handler);return()=>{if(CUSTOM_PAGE_ROUTES.get(page)===handler)CUSTOM_PAGE_ROUTES.delete(page)}}
function installBuiltInPageRoutes(){if(global.__shellBuiltInPageRoutes)return;global.__shellBuiltInPageRoutes=true;registerPageRoute('data',async()=>{global.SettingsModule?.unmount?.();if(!global.KaDataPage?.open)throw new Error('KaDataPage hazır değil.');return global.KaDataPage.open()})}
function setTitle(v){const el=$('#v2ModuleTitle');if(el)el.textContent=v||''}
function setBottomActive(action){activeAction=action;$$('[data-ka-shell-action]').forEach(b=>{const on=b.dataset.kaShellAction===action;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')})}
function moduleAllowed(name){const meta=global.AppConfig?.module?.(name);return meta?.visible!==false&&global.PermissionService?.moduleLevel?.(name)!=='hidden'}
function syncLayerLock(){const menuOpen=!!$('#kaMenuLayer')?.classList.contains('open'),modalOpen=!!document.querySelector('.ka-modal-backdrop');document.body.classList.toggle('ka-layer-open',menuOpen||modalOpen)}
function observeLayerLock(){if(layerObserver)return;layerObserver=new MutationObserver(syncLayerLock);layerObserver.observe(document.body,{childList:true,subtree:true});syncLayerLock()}
function closeMenu(){const layer=$('#kaMenuLayer');if(layer){layer.classList.remove('open');layer.hidden=true;layer.innerHTML=''}menuGroup=null;syncLayerLock()}
function closeHeaderPopover(){headerPopover?.remove();headerPopover=null;document.removeEventListener('pointerdown',outsideHeaderPopover,true)}
function outsideHeaderPopover(e){if(!headerPopover)return;if(headerPopover.contains(e.target)||e.target.closest('[data-ka-header-profile],[data-ka-header-notification],[data-ka-theme-toggle]'))return;closeHeaderPopover()}
function popoverBase(anchor,width=330){closeHeaderPopover();const r=anchor.getBoundingClientRect(),el=document.createElement('div');el.className='ka-card';el.setAttribute('role','dialog');el.style.cssText=`position:fixed;z-index:1100;top:${Math.max(r.bottom+8,70)}px;right:${Math.max(10,innerWidth-r.right)}px;width:min(${width}px,calc(100vw - 20px));max-height:calc(100dvh - ${Math.max(r.bottom+22,86)}px);overflow:auto;background:var(--ka-card-raised-bg);border:1px solid var(--ka-border);border-radius:18px;box-shadow:var(--ka-shadow-modal);padding:12px;`;document.body.appendChild(el);headerPopover=el;setTimeout(()=>document.addEventListener('pointerdown',outsideHeaderPopover,true),0);return el}
function cleanupFormPage(){global.__kaFormPageObserver?.disconnect?.();global.__kaFormPageObserver=null}
function hideModuleChrome(root,name){
  const shell=root?.querySelector?.(`[data-${name}-module]`);if(!shell)return;
  const head=shell.querySelector(':scope > .ka-row');if(head)head.hidden=true;
  const searchSelectors={academic:'[data-academic-search-wrap]',management:'[data-management-search-wrap]',communication:'#communicationSearch',transport:'#transportSearch',documents:'#documentsSearch',tools:'#toolsSearch',settings:'#settingsSearch'};
  const target=searchSelectors[name]?shell.querySelector(searchSelectors[name]):null;
  const searchWrap=target?.matches?.('.ka-field')?target:target?.closest?.('.ka-field');if(searchWrap)searchWrap.hidden=true;
  const tabs=shell.querySelector(':scope > .ka-tabs');if(tabs)tabs.hidden=true;
}
function applyFormPage(root,page,title){const wanted=FORM_PAGES[page];if(!wanted)return false;const ok=global.ToolsModule?.openPage?.('forms',title);if(ok===false)return false;hideModuleChrome(root,'tools');const applyFilter=()=>{const content=root.querySelector('#toolsContent');content?.querySelectorAll(':scope > section').forEach(section=>{const h=section.querySelector('h3');section.hidden=!h||!String(h.textContent||'').trim().startsWith(wanted)})};cleanupFormPage();requestAnimationFrame(()=>{applyFilter();const content=root.querySelector('#toolsContent');if(content){global.__kaFormPageObserver=new MutationObserver(applyFilter);global.__kaFormPageObserver.observe(content,{childList:true})}});if(title)setTitle(title);return true}
function applySubpage(name,page,title){
  const root=$('#v2ModuleRoot');if(!root||!page)return false;
  const studentPages={'student-attendance':'attendance','student-list':'student-list',homework:'homework',grades:'grades'};
  if(name==='tools'&&page==='student-attendance'){
    global.ToolsModule?.unmount?.();
    Promise.resolve(global.StudentPages?.open?.('attendance',title)).catch(e=>{console.error('[Shell/student-attendance]',e);global.toast?.('Öğrenci yoklama açılamadı.');});
    if(title)setTitle(title);return true;
  }
  if(name==='tools'&&page==='student-list'){
    Promise.resolve(global.OgretmenListeUI?.open?.()).then(()=>requestAnimationFrame(()=>{const shell=root.querySelector('[data-tools-module]');if(shell){const head=shell.querySelector(':scope > .ka-row'),tabs=shell.querySelector('.ka-tabs');if(head)head.hidden=true;if(tabs)tabs.hidden=true}})).catch(e=>{console.error('[Shell/student-list]',e);global.toast?.('Öğrenci listesi oluşturucu açılamadı.');});
    if(title)setTitle(title);return true;
  }
  if(name==='tools'&&(page==='homework'||page==='grades')){
    global.ToolsModule?.unmount?.();
    Promise.resolve(global.OdevNotUI?.open?.(studentPages[page])).catch(e=>{console.error('[Shell/gradebook]',e);global.toast?.('Çizelge açılamadı.');});
    if(title)setTitle(title);return true;
  }
  if(name==='tools'&&FORM_PAGES[page])return applyFormPage(root,page,title);
  if(name==='documents'&&page==='evrak'&&global.EvrakTakipPage?.open){
    global.DocumentsModule?.unmount?.();
    Promise.resolve(global.EvrakTakipPage.open(root)).catch(e=>{console.error('[Shell/evrak]',e);global.toast?.('Evrak Takibi açılamadı.');});
    if(title)setTitle(title);return true;
  }
  if(name==='documents'&&page==='mevzuat'){
    global.DocumentsModule?.unmount?.();
    Promise.resolve((async()=>{
      if(!global.LegislationEngine)await global.AppLoader?.loadScript?.('js/modules/legislation.js');
      if(!global.LegislationModule?.mount)await global.AppLoader?.loadScript?.('js/modules/legislation-ui.js');
      if(!global.LegislationModule?.mount)throw new Error('Mevzuat modülü yüklenemedi.');
      return global.LegislationModule.mount(root);
    })()).catch(e=>{console.error('[Shell/mevzuat]',e);global.toast?.('Mevzuat açılamadı.');});
    if(title)setTitle(title);return true;
  }
  if(name==='documents'&&page==='teblig'&&global.DocumentsModule?.openTeblig){
    global.DocumentsModule.openTeblig();
    requestAnimationFrame(()=>{const shell=root.querySelector('[data-documents-module]');if(shell){const head=shell.querySelector(':scope > .ka-row'),search=shell.querySelector('#documentsSearch')?.closest('.ka-field'),formButton=shell.querySelector('[data-document-form="teblig"]')?.closest('.ka-row');if(head)head.hidden=true;if(search)search.hidden=true;if(formButton)formButton.hidden=true}});
    if(title)setTitle(title);return true;
  }
  if(name==='academic'&&['schedule','written','trial','results','plans','calendar'].includes(page)){
    const ok=global.AcademicModule?.openPage?.(page,title);hideModuleChrome(root,'academic');
    if(ok===false)global.toast?.('Akademik sayfa açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='management'&&['staff','tasks','leaves','duty','puantaj','dilekce'].includes(page)){
    const ok=global.ManagementModule?.openPage?.(page,title);hideModuleChrome(root,'management');
    if(ok===false)global.toast?.('Yönetim sayfası açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='communication'&&['announcements','messages','polls','news','notes','calendar'].includes(page)){
    const ok=global.CommunicationModule?.openPage?.(page,title);hideModuleChrome(root,'communication');
    if(ok===false)global.toast?.('İletişim sayfası açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='transport'&&['services','busSeats','classSeats'].includes(page)){
    const ok=global.TransportModule?.openPage?.(page,title);hideModuleChrome(root,'transport');
    if(ok===false)global.toast?.('Taşıma sayfası açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='settings'&&['school','users','statistics','account','sync','roles','app','reminders','storage'].includes(page)){
    const ok=global.SettingsModule?.openPage?.(page,title);hideModuleChrome(root,'settings');
    if(ok===false)global.toast?.('Ayarlar sayfası açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='people'&&['teachers','classes','students'].includes(page)){
    const ok=global.PeopleModule?.openPage?.(page,title);
    if(ok===false)global.toast?.('Kişiler sayfası açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='tools'&&['checklists','map','attendance'].includes(page)){
    const ok=global.ToolsModule?.openPage?.(page,title);hideModuleChrome(root,'tools');
    if(ok===false)global.toast?.('Araç sayfası açılamadı.');
    if(title)setTitle(title);return true;
  }
  if(name==='tools'&&['rubric','project'].includes(page)){
    Promise.resolve(global.RubricToolsModule?.openPage?.(page)).catch(e=>{console.error('[Shell/rubric]',e);global.toast?.('Değerlendirme aracı açılamadı.');});
    if(title)setTitle(title);return true;
  }
  if(name==='academic'){
    const h=root.querySelector('[data-academic-module] > .ka-row h2');if(h&&title)h.textContent=title;
  }
  if(name==='communication'){
    const h=root.querySelector('[data-communication-module] > .ka-row h2');if(h&&title)h.textContent=title;
  }
  if(name==='management'){
    const h=root.querySelector('[data-management-module] > .ka-row h2');if(h&&title)h.textContent=title;
  }
  if(['academic','communication','management','transport','documents','tools','settings'].includes(name))hideModuleChrome(root,name);
  if(title)setTitle(title);
  return false;
}
async function routeModule(name,{bottom='menu',page='',title=''}={}){
  const requestedGradePage=name==='tools'&&(page==='homework'||page==='grades')?page:'';
  if(global.OdevNotUI?.page&&global.OdevNotUI.page!==requestedGradePage&&global.OdevNotUI.close?.()===false)return false;
  if(!(name==='tools'&&page==='student-list'))global.OgretmenListeUI?.close?.();
  if(!(name==='tools'&&page==='student-attendance'))global.StudentPages?.close?.();
  closeHeaderPopover();closeMenu();
  if(!(name==='tools'&&FORM_PAGES[page]))cleanupFormPage();
  if(name==='payroll'){
    try{
      if(!global.ReportEngine?.printReport)await global.AppLoader?.loadScript?.('js/modules/report-engine.js');
      if(!global.PayrollChangeModule?.open)await global.AppLoader?.loadScript?.('js/modules/payroll-change.js');
      if(!global.PayrollChangeModule?.open)throw new Error('Maaş değişikliği modülü yüklenemedi.');
      setBottomActive(bottom);setTitle('Maaş Değişikliği Bildirim Formu');
      global.PayrollChangeModule.open();
    }catch(e){
      console.error('[Shell/payroll]',e);global.toast?.('Maaş değişikliği formu açılamadı.');
      await routeModule('management',{bottom});
    }
    return true;
  }
  const meta=global.AppConfig?.module?.(name)||{label:name};
  if(meta.visible===false||global.PermissionService?.moduleLevel?.(name)==='hidden')return false;
  const custom=page&&CUSTOM_PAGE_ROUTES.get(page);
  if(custom){
    setBottomActive(bottom);global.AppLoader?.setActiveModule?.(name);setTitle(title||meta.label||name);
    try{return (await custom({name,bottom,page,title,root:$('#v2ModuleRoot')}))!==false}catch(e){console.error('[Shell/custom-page]',page,e);global.toast?.('Sayfa açılamadı.');return false}
  }
  setBottomActive(bottom);global.AppLoader?.setActiveModule?.(name);
  setTitle(title||meta.label||name);await global.AppLoader?.load?.(name);
  if(page)requestAnimationFrame(()=>applySubpage(name,page,title));
  return true
}
function visibleItems(g){return(g.items||[]).filter(x=>moduleAllowed(x[2])).concat((g.subItems||[]).filter(x=>moduleAllowed(x[2])))}
function visibleGroups(){return MENU_GROUPS.filter(g=>moduleAllowed(g.route)&&visibleItems(g).length)}
function menuCount(g){return visibleItems(g).length}
function renderMenuGrid(){const layer=$('#kaMenuLayer');if(!layer)return;menuGroup=null;const cards=visibleGroups();layer.innerHTML=`<div class="ka-menu-page"><header class="ka-menu-head"><h2>Menü</h2><button type="button" class="ka-icon-button" data-ka-menu-close aria-label="Menüyü kapat">${SVG.close}</button></header><div class="ka-menu-grid">${cards.map(g=>`<button type="button" class="ka-menu-card ka-menu-card--${g.tone}" data-ka-menu-group="${g.key}"><span class="ka-menu-card__icon">${g.icon}</span><strong>${esc(g.label)}</strong><span class="ka-badge">${menuCount(g)}</span></button>`).join('')}</div></div>`;layer.querySelector('[data-ka-menu-close]')?.addEventListener('click',closeMenu);$$('[data-ka-menu-group]',layer).forEach(b=>b.addEventListener('click',()=>renderMenuList(b.dataset.kaMenuGroup)))}
function listRow(item){return`<button type="button" class="ka-btn ka-btn--secondary" data-ka-shell-route="${item[2]}" data-ka-menu-page="${esc(item[3]||'')}" data-ka-menu-title="${esc(item[0]||'')}"><span class="ka-avatar">${item[1]}</span><strong class="ka-grow">${esc(item[0])}</strong><span>${SVG.chevron}</span></button>`}
function renderMenuList(key){const layer=$('#kaMenuLayer'),g=MENU_GROUPS.find(x=>x.key===key);if(!layer||!g)return;menuGroup=key;const main=(g.items||[]).filter(x=>moduleAllowed(x[2])),sub=(g.subItems||[]).filter(x=>moduleAllowed(x[2]));layer.innerHTML=`<div class="ka-menu-page"><header class="ka-menu-head"><button type="button" class="ka-icon-button" data-ka-menu-back aria-label="Menüye dön">${SVG.back}</button><h2 class="ka-grow">${esc(g.label)}</h2></header><div class="ka-stack ka-page">${main.map(listRow).join('')}${sub.length?`<h3>${esc(g.subLabel||'Diğer')}</h3>${sub.map(listRow).join('')}`:''}</div></div>`;layer.querySelector('[data-ka-menu-back]')?.addEventListener('click',renderMenuGrid);$$('[data-ka-shell-route]',layer).forEach(b=>b.addEventListener('click',()=>routeModule(b.dataset.kaShellRoute,{bottom:'menu',page:b.dataset.kaMenuPage||'',title:b.dataset.kaMenuTitle||''})))}
function openMenu(){closeHeaderPopover();const layer=$('#kaMenuLayer');if(!layer)return;renderMenuGrid();layer.hidden=false;requestAnimationFrame(()=>{layer.classList.add('open');syncLayerLock()});setBottomActive('menu')}
function syncVisibilityClasses(){for(const id of ['girisEkrani','onayBekleniyorEkrani','app']){const el=document.getElementById(id);if(el)el.classList.toggle('ka-hidden',el.hidden)}}
function observeVisibility(){if(visibilityObserver)return;syncVisibilityClasses();visibilityObserver=new MutationObserver(syncVisibilityClasses);for(const id of ['girisEkrani','onayBekleniyorEkrani','app']){const el=document.getElementById(id);if(el)visibilityObserver.observe(el,{attributes:true,attributeFilter:['hidden']})}}
function normalizeDashboardLayout(){return !!$('.ka-home[data-dashboard-role]')}
function profileName(u){return u.adSoyad||[u.ad,u.soyad].filter(Boolean).join(' ')||u.displayName||u.kullaniciAdi||'Kullanıcı'}
function profileRole(u){return u.unvan||u.rolAdi||u.rol||u.brans||'Koruk Asistan Kullanıcısı'}
function linkedTeacher(){const u=user(),id=u.bagliOgretmenId||u.ogretmenId;return id?arr('ogretmenler').find(x=>x.id===id)||null:null}
function profileInfo(){const u=user(),t=linkedTeacher(),name=t?[t.ad,t.soyad].filter(Boolean).join(' '):profileName(u),role=t?.brans||profileRole(u),photo=t?.profilFotoUrl||t?.fotoUrl||u.profilFotoUrl||u.fotoUrl||'',username=u.kullaniciAdi?`@${u.kullaniciAdi}`:(u.email||'');return{u,t,name,role,photo,username}}
function renderProfile(){closeHeaderPopover();closeMenu();setBottomActive('profile');setTitle('Profilim');const {u,t,name,role,photo}=profileInfo(),root=$('#v2ModuleRoot');if(!root)return;const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toLocaleUpperCase('tr');root.innerHTML=`<section class="ka-profile-page"><div class="ka-profile-hero"><div class="ka-profile-avatar">${photo?`<img src="${esc(photo)}" alt="${esc(name)}">`:esc(initials||'K')}</div><div class="ka-profile-copy"><h2>${esc(name)}</h2><p>${esc(role)}</p>${t?.telefon||u.telefon?`<small>☎ ${esc(t?.telefon||u.telefon)}</small>`:''}${t?.email||u.email?`<small>✉ ${esc(t?.email||u.email)}</small>`:''}</div></div><div class="ka-profile-section"><h3>Çizelgelerim</h3><div class="ka-profile-grid"><button type="button" data-profile-route="academic">📅<span>Ders Programım</span></button><button type="button" data-profile-route="management">🛡️<span>Nöbetlerim</span></button><button type="button" data-profile-route="academic">📏<span>Sınavlarım</span></button><button type="button" data-profile-route="documents">📄<span>Diğer Görevlerim</span></button></div></div><button type="button" class="ka-logout-button" data-profile-logout>↪ Oturumu Kapat</button></section>`;$$('[data-profile-route]',root).forEach(b=>b.addEventListener('click',()=>routeModule(b.dataset.profileRoute,{bottom:'profile'})));root.querySelector('[data-profile-logout]')?.addEventListener('click',()=>{if(confirm('Hesabınızdan çıkış yapmak istediğinize emin misiniz?'))global.cikisYap?.()})}
function currentTheme(){return document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light'}
function syncThemeButton(){const dark=currentTheme()==='dark',btn=$('[data-ka-theme-toggle]');if(btn){btn.classList.remove('ka-hidden');btn.innerHTML=dark?SVG.sun:SVG.moon;btn.setAttribute('aria-label',dark?'Açık temaya geç':'Koyu temaya geç');btn.title=dark?'Açık temaya geç':'Koyu temaya geç'}global.AppStore?.set?.('ui.theme',dark?'dark':'light');const meta=$('meta[data-ka-theme-color]');if(meta)meta.content=dark?'#0d1713':'#17684f'}
async function applyTheme(theme,{persist=true}={}){const next=theme==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',next);document.documentElement.style.colorScheme=next;try{localStorage.setItem('ka-theme',next)}catch(_){}syncThemeButton();if(persist){const uid=user().uid;if(uid&&global.KorukLocalFirst?.meta)await global.KorukLocalFirst.meta(uid,'theme',next).catch(()=>{})}window.dispatchEvent(new CustomEvent('koruk:theme-changed',{detail:{theme:next}}));return next}
function toggleTheme(){themeTouched=true;return applyTheme(currentTheme()==='dark'?'light':'dark')}
async function hydrateTheme(){if(themeTouched){syncThemeButton();return currentTheme()}const uid=user().uid;let saved=global.AppStore?.get?.('ui.theme')||null;if(uid){try{saved=(await global.KorukLocalFirst?.meta?.(uid,'theme'))||saved}catch(_){}}if(saved!=='dark'&&saved!=='light'){try{saved=localStorage.getItem('ka-theme')||saved}catch(_){}}if(saved!=='dark'&&saved!=='light')saved=currentTheme();await applyTheme(saved,{persist:false});return saved}
function takeThemeOwnership(){if(!global.AppLoader)return;global.AppLoader.applyTheme=applyTheme;global.AppLoader.toggleTheme=toggleTheme}
function bindThemeCapture(){document.addEventListener('click',e=>{const themeBtn=e.target.closest?.('[data-ka-theme-toggle]');if(!themeBtn)return;e.preventDefault();e.stopPropagation();toggleTheme()},true)}
function openProfilePopover(){const anchor=$('[data-ka-header-profile]');if(!anchor)return;const {name,username,photo}=profileInfo(),p=popoverBase(anchor,360),dark=currentTheme()==='dark';p.classList.add('ka-profile-popover-legacy');p.innerHTML=`<div style="padding:10px 10px 12px;border-bottom:1px solid var(--ka-border);display:flex;gap:11px;align-items:center"><span class="ka-avatar" style="width:46px;height:46px;flex-basis:46px">${photo?`<img src="${esc(photo)}" alt="">`:SVG.profile}</span><div style="min-width:0"><strong style="display:block;font-size:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(name)}</strong><small class="ka-muted">${esc(username)}</small></div></div><div class="ka-stack" style="gap:4px;padding-top:8px"><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start" data-hp-profile>${SVG.profile}<span>Profilim</span></button><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start" data-hp-settings>${SVG.settings}<span>Ayarlar</span></button><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start" data-hp-theme>${dark?SVG.sun:SVG.moon}<span>${dark?'Açık Temaya Geç':'Koyu Temaya Geç'}</span></button><div style="height:1px;background:var(--ka-border);margin:4px 0"></div><button class="ka-btn ka-btn--ghost" style="justify-content:flex-start;color:var(--ka-danger)" data-hp-logout>${SVG.logout}<span>Çıkış Yap</span></button></div>`;p.querySelector('[data-hp-profile]')?.addEventListener('click',renderProfile);p.querySelector('[data-hp-settings]')?.addEventListener('click',()=>routeModule('settings',{bottom:'menu'}));p.querySelector('[data-hp-theme]')?.addEventListener('click',async()=>{await toggleTheme();openProfilePopover()});p.querySelector('[data-hp-logout]')?.addEventListener('click',()=>{if(confirm('Hesabınızdan çıkış yapmak istediğinize emin misiniz?'))global.cikisYap?.()})}
function dateOf(x){const v=x?.tarih||x?.sonTarih||x?.baslangicTarihi||x?.olusturmaTarihi||x?.guncellenmeTarihi;if(!v)return null;try{const d=v?.toDate?v.toDate():new Date(String(v).length===10?`${v}T00:00:00`:v);return isNaN(d)?null:d}catch(_){return null}}
function notificationRows(){const now=new Date(),limit=new Date(now.getTime()+45*86400000),rows=[],me=user().uid||'';for(const x of arr('hatirlaticilar')){if(x?.tamamlandi===true)continue;const d=dateOf(x);if(!d||d<now||d>limit)continue;rows.push({type:'Etkinlik',icon:'⏰',title:x.baslik||x.ad||x.konu||x.aciklama||'Yaklaşan etkinlik',date:d,time:x.saat||'',id:x.id,page:'calendar',count:1})}if(me)for(const k of arr('konusmalar')){const unread=Number(k?.okunmayanlar?.[me]||0);if(unread<1)continue;const diger=Object.entries(k.katilimciAdlari||{}).filter(([id])=>id!==me).map(([,ad])=>ad).filter(Boolean).join(', '),title=k.grupMu?(k.grupAdi||'Grup mesajı'):(diger||'Yeni mesaj'),d=dateOf(k.sonMesaj||k)||now;rows.push({type:'Mesaj',icon:'💬',title,date:d,time:'',id:k.id,page:'messages',count:unread,meta:`${unread} okunmamış mesaj`})}if(me)for(const d of arr('duyurular')){if(d?.arsivlendi===true||d?.aktif===false||d?.okuyanlar?.[me])continue;const dt=dateOf(d)||now;rows.push({type:'Duyuru',icon:'📣',title:d.baslik||'Yeni duyuru',date:dt,time:'',id:d.id,page:'announcements',count:1,meta:'Okunmamış duyuru'})}return rows.sort((a,b)=>{const ap=a.type==='Mesaj'?0:a.type==='Duyuru'?1:2,bp=b.type==='Mesaj'?0:b.type==='Duyuru'?1:2;return ap-bp||(a.type==='Etkinlik'?a.date-b.date:b.date-a.date)}).slice(0,20)}
function formatNoticeDate(d,time=''){const ds=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);return `${ds}${time?` · ${time}`:''}`}
function updateNotificationBadge(){const rows=notificationRows(),count=rows.reduce((n,r)=>n+Math.max(1,Number(r.count)||1),0),bell=$('[data-ka-header-notification]'),b=$('[data-ka-notification-count]');if(b){b.textContent=String(Math.min(count,99));b.hidden=count<1}if(bell)bell.hidden=count<1}
function openNotifications(){const anchor=$('[data-ka-header-notification]');if(!anchor||anchor.hidden)return;const p=popoverBase(anchor,400),rows=notificationRows(),count=rows.reduce((n,r)=>n+Math.max(1,Number(r.count)||1),0);p.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding:6px 6px 10px;border-bottom:1px solid var(--ka-border)"><strong style="font-size:17px">Bildirimler</strong><span class="ka-badge">${count}</span></div><div style="display:flex;flex-direction:column">${rows.length?rows.map((r,i)=>`<button type="button" class="ka-btn ka-btn--ghost" data-notice-index="${i}" style="min-height:70px;border-radius:0;justify-content:flex-start;text-align:left;border-bottom:1px solid var(--ka-border);padding:10px 8px"><span style="font-size:21px">${r.icon}</span><span style="min-width:0"><strong style="display:block;white-space:normal">${esc(r.title)}</strong><small class="ka-muted">${esc(r.meta||`${r.type} · ${formatNoticeDate(r.date,r.time)}`)}</small></span></button>`).join(''):'<div class="ka-empty" style="margin-top:10px">Yeni bildirim bulunmuyor.</div>'}</div>`;$$('[data-notice-index]',p).forEach(b=>b.addEventListener('click',()=>{const r=rows[Number(b.dataset.noticeIndex)];if(r)routeModule('communication',{bottom:'menu',page:r.page,title:r.type==='Mesaj'?'Mesajlaşma':r.type==='Duyuru'?'Duyurular':'Takvim'})}))}
function norm(v){return String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function searchRows(q){const n=norm(q),rows=[];for(const x of arr('ogretmenler')){const title=x.adSoyad||[x.ad,x.soyad].filter(Boolean).join(' ')||'Öğretmen';if(!n||norm(`${title} ${x.brans||''} ${x.telefon||''}`).includes(n))rows.push({type:'Öğretmen',icon:'👩‍🏫',title,meta:x.brans||x.unvan||''})}for(const x of arr('veliler')){const title=x.ogrenciAdi||x.adSoyad||x.ad||'Öğrenci';if(!n||norm(`${title} ${x.veliAdi||''} ${x.telefon||''} ${x.sinif||x.sinifAdi||''}`).includes(n))rows.push({type:'Öğrenci',icon:'🎓',title,meta:[x.sinifAdi||x.sinif,x.veliAdi].filter(Boolean).join(' · ')})}for(const x of arr('servisler')){const title=x.servisAdi||x.guzergah||x.plaka||'Servis';if(!n||norm(`${title} ${x.plaka||''} ${x.soforAdi||''}`).includes(n))rows.push({type:'Servis',icon:'🚌',title,meta:[x.plaka,x.soforAdi].filter(Boolean).join(' · ')})}for(const x of arr('evrakTakibi')){const title=x.evrakAdi||x.baslik||x.konu||'Evrak';if(!n||norm(`${title} ${x.durum||''}`).includes(n))rows.push({type:'Evrak',icon:'📄',title,meta:x.durum||''})}return rows.slice(0,80)}
function renderSearchResults(root,q){const out=root.querySelector('[data-shell-search-results]'),rows=searchRows(q);if(!out)return;out.innerHTML=rows.length?rows.map(r=>`<article class="ka-search-result"><span>${r.icon}</span><div><strong>${esc(r.title)}</strong><small>${esc([r.type,r.meta].filter(Boolean).join(' · '))}</small></div></article>`).join(''):'<div class="ka-empty">Eşleşen kayıt bulunamadı.</div>'}
function renderSearch(){closeHeaderPopover();closeMenu();setBottomActive('search');setTitle('Arama');const root=$('#v2ModuleRoot');if(!root)return;root.innerHTML=`<section class="ka-search-page"><div class="ka-search-box">${SVG.search}<input type="search" data-shell-search-input placeholder="İsim, sınıf, telefon, servis, evrak…" autocomplete="off"></div><div class="ka-search-chips"><span>Öğrenci</span><span>Öğretmen</span><span>Servis</span><span>Evrak</span></div><div data-shell-search-results></div></section>`;const input=root.querySelector('[data-shell-search-input]');input?.addEventListener('input',()=>renderSearchResults(root,input.value));renderSearchResults(root,'');setTimeout(()=>input?.focus(),40)}
function closeQuickNote(){document.getElementById('kaQuickNoteModal')?.remove();syncLayerLock()}
function quickNoteCloseAndRestore(){closeQuickNote();setBottomActive(global.AppStore?.get?.('ui.route')==='dashboard'?'home':'menu')}
function openTextQuickNote(){closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Metin Notu</h3><p class="ka-muted">Hızlıca metin notu oluşturun</p></div><button type="button" class="ka-icon-button" data-note-close aria-label="Kapat">${SVG.close}</button></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Başlık</span><input data-note-title placeholder="Not başlığı..."></label><label class="ka-field"><span class="ka-field__label">Notunuz</span><textarea data-note-text rows="8" placeholder="Notunuzu yazın..."></textarea></label></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);const close=quickNoteCloseAndRestore;ov.querySelector('[data-note-close]')?.addEventListener('click',close);ov.querySelector('[data-note-cancel]')?.addEventListener('click',close);ov.querySelector('[data-note-save]')?.addEventListener('click',async()=>{const baslik=ov.querySelector('[data-note-title]')?.value.trim()||'Hızlı Not',icerik=ov.querySelector('[data-note-text]')?.value.trim();if(!icerik)return;try{await global.NotlarService?.notKaydet?.(null,{baslik,icerik,tip:'metin',renk:'sari',tarih:new Date().toISOString().slice(0,10),etiketler:[]});close();global.toast?.('Not kaydedildi.')}catch(e){console.error('[QuickNote/text]',e);global.toast?.('Not kaydedilemedi.')}});setTimeout(()=>ov.querySelector('[data-note-title]')?.focus(),30)}
function openChecklistQuickNote(){closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Yapılacaklar</h3><p class="ka-muted">Kontrol edilebilir görev listesi</p></div><button type="button" class="ka-icon-button" data-note-close aria-label="Kapat">${SVG.close}</button></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Başlık</span><input data-note-title placeholder="Yapılacaklar başlığı..."></label><div class="ka-stack" data-check-list></div><button type="button" class="ka-btn ka-btn--secondary ka-btn--sm" data-check-add>+ Görev ekle</button></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);const list=ov.querySelector('[data-check-list]'),add=()=>{const row=document.createElement('div');row.className='ka-row';row.innerHTML='<input type="checkbox" disabled><input class="ka-grow" data-check-text placeholder="Görev yazın..."><button type="button" class="ka-icon-button" data-check-remove>×</button>';list.appendChild(row);row.querySelector('[data-check-remove]').onclick=()=>row.remove();row.querySelector('[data-check-text]').focus()};ov.querySelector('[data-check-add]').onclick=add;add();const close=quickNoteCloseAndRestore;ov.querySelector('[data-note-close]')?.addEventListener('click',close);ov.querySelector('[data-note-cancel]')?.addEventListener('click',close);ov.querySelector('[data-note-save]')?.addEventListener('click',async()=>{const baslik=ov.querySelector('[data-note-title]')?.value.trim()||'Yapılacaklar',maddeler=[...ov.querySelectorAll('[data-check-text]')].map(x=>x.value.trim()).filter(Boolean).map(metin=>({metin,tamamlandi:false}));if(!maddeler.length)return;try{await global.NotlarService?.notKaydet?.(null,{baslik,icerik:'',maddeler,tip:'todo',renk:'sari',tarih:new Date().toISOString().slice(0,10),etiketler:[]});close();global.toast?.('Yapılacaklar kaydedildi.')}catch(e){console.error('[QuickNote/checklist]',e);global.toast?.('Liste kaydedilemedi.')}})}
function quickNoteCommonFields(title=''){return `<label class="ka-field"><span class="ka-field__label">Başlık</span><input data-note-title value="${esc(title)}" placeholder="Not başlığı..."></label><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Tarih</span><input type="date" data-note-date value="${new Date().toISOString().slice(0,10)}"></label><label class="ka-field"><span class="ka-field__label">Etiketler</span><input data-note-tags placeholder="önemli, toplantı"></label></div>`}
function quickNotePayload(ov,tip,extra={}){return{baslik:ov.querySelector('[data-note-title]')?.value.trim()||({cizim:'Çizim',goruntu:'Görsel Not',tablo:'Tablo Notu'}[tip]||'Hızlı Not'),tip,renk:'sari',tarih:ov.querySelector('[data-note-date]')?.value||new Date().toISOString().slice(0,10),etiketler:String(ov.querySelector('[data-note-tags]')?.value||'').split(',').map(x=>x.trim()).filter(Boolean),...extra}}
function openDrawingQuickNote(){closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Çizim</h3><p class="ka-muted">El yazısı, eskiz ve serbest çizim</p></div><button type="button" class="ka-icon-button" data-note-close>${SVG.close}</button></div><div class="ka-modal__body ka-stack">${quickNoteCommonFields()}<div class="ka-row ka-wrap"><label class="ka-field ka-grow"><span class="ka-field__label">Renk</span><input type="color" data-draw-color value="#1A2A2A"></label><label class="ka-field"><span class="ka-field__label">Kalınlık</span><input type="range" data-draw-size min="1" max="18" value="4"></label><button type="button" class="ka-btn ka-btn--secondary ka-btn--sm" data-draw-clear>Temizle</button></div><canvas data-draw-canvas width="900" height="560" style="width:100%;height:min(48dvh,420px);background:#fff;border:1px solid var(--ka-border);border-radius:14px;touch-action:none"></canvas></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);const canvas=ov.querySelector('[data-draw-canvas]'),ctx=canvas.getContext('2d');ctx.lineCap='round';ctx.lineJoin='round';let drawing=false,last=null;const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.addEventListener('pointerdown',e=>{drawing=true;last=point(e);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.strokeStyle=ov.querySelector('[data-draw-color]').value;ctx.lineWidth=Number(ov.querySelector('[data-draw-size]').value)||4;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>drawing=false));ov.querySelector('[data-draw-clear]').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);const close=quickNoteCloseAndRestore;ov.querySelector('[data-note-close]').onclick=close;ov.querySelector('[data-note-cancel]').onclick=close;ov.querySelector('[data-note-save]').onclick=async()=>{try{await global.NotlarService?.notKaydet?.(null,quickNotePayload(ov,'cizim',{cizimData:canvas.toDataURL('image/png')}));close();global.toast?.('Çizim kaydedildi.')}catch(e){console.error('[QuickNote/drawing]',e);global.toast?.('Çizim kaydedilemedi.')}}}
function openImageQuickNote(){closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Görsel Not</h3><p class="ka-muted">Fotoğraf veya görsel not</p></div><button type="button" class="ka-icon-button" data-note-close>${SVG.close}</button></div><div class="ka-modal__body ka-stack">${quickNoteCommonFields()}<label class="ka-field"><span class="ka-field__label">Görsel</span><input type="file" accept="image/*" data-image-input></label><div data-image-preview class="ka-empty">Görsel seçilmedi.</div></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);let data='';const input=ov.querySelector('[data-image-input]'),preview=ov.querySelector('[data-image-preview]');input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{data=String(r.result||'');preview.className='';preview.innerHTML=`<img src="${data}" alt="Görsel önizleme" style="max-width:100%;max-height:45dvh;border-radius:14px;object-fit:contain">`};r.readAsDataURL(f)};const close=quickNoteCloseAndRestore;ov.querySelector('[data-note-close]').onclick=close;ov.querySelector('[data-note-cancel]').onclick=close;ov.querySelector('[data-note-save]').onclick=async()=>{if(!data)return global.toast?.('Önce bir görsel seçin.');try{await global.NotlarService?.notKaydet?.(null,quickNotePayload(ov,'goruntu',{goruntu:data}));close();global.toast?.('Görsel not kaydedildi.')}catch(e){console.error('[QuickNote/image]',e);global.toast?.('Görsel not kaydedilemedi.')}}}
function tableQuickHtml(rows,cols,values=[]){let h='<table class="ka-table"><tbody>';for(let r=0;r<rows;r++){h+='<tr>';for(let c=0;c<cols;c++){const v=values?.[r]?.[c]||'';h+=`<${r===0?'th':'td'}><input data-table-cell data-r="${r}" data-c="${c}" value="${esc(v)}" placeholder="${r===0?'Başlık '+(c+1):'...'}"></${r===0?'th':'td'}>`}h+='</tr>'}return h+'</tbody></table>'}
function openTableQuickNote(){closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note"><div class="ka-modal__header"><div><h3>Tablo Notu</h3><p class="ka-muted">Satır ve sütunlarla düzenli kayıt</p></div><button type="button" class="ka-icon-button" data-note-close>${SVG.close}</button></div><div class="ka-modal__body ka-stack">${quickNoteCommonFields()}<div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Satır</span><input type="number" min="1" max="20" value="3" data-table-rows></label><label class="ka-field"><span class="ka-field__label">Sütun</span><input type="number" min="1" max="10" value="3" data-table-cols></label></div><div style="overflow:auto" data-table-wrap>${tableQuickHtml(3,3)}</div></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-note-cancel>İptal</button><button type="button" class="ka-btn" data-note-save>Kaydet</button></div></section>`;document.body.appendChild(ov);const rebuild=()=>{const vals=[];ov.querySelectorAll('[data-table-cell]').forEach(x=>{const r=Number(x.dataset.r),c=Number(x.dataset.c);(vals[r]??=[])[c]=x.value});const rows=Math.max(1,Math.min(20,Number(ov.querySelector('[data-table-rows]').value)||3)),cols=Math.max(1,Math.min(10,Number(ov.querySelector('[data-table-cols]').value)||3));ov.querySelector('[data-table-wrap]').innerHTML=tableQuickHtml(rows,cols,vals)};ov.querySelector('[data-table-rows]').onchange=rebuild;ov.querySelector('[data-table-cols]').onchange=rebuild;const close=quickNoteCloseAndRestore;ov.querySelector('[data-note-close]').onclick=close;ov.querySelector('[data-note-cancel]').onclick=close;ov.querySelector('[data-note-save]').onclick=async()=>{const rows=Number(ov.querySelector('[data-table-rows]').value)||3,cols=Number(ov.querySelector('[data-table-cols]').value)||3,tabloVeri=[];ov.querySelectorAll('[data-table-cell]').forEach(x=>{const r=Number(x.dataset.r),c=Number(x.dataset.c);(tabloVeri[r]??=[])[c]=x.value.trim()});try{await global.NotlarService?.notKaydet?.(null,quickNotePayload(ov,'tablo',{tabloVeri,tabloSatir:rows,tabloSutun:cols}));close();global.toast?.('Tablo notu kaydedildi.')}catch(e){console.error('[QuickNote/table]',e);global.toast?.('Tablo notu kaydedilemedi.')}}}
function openQuickNote(){closeHeaderPopover();closeMenu();setBottomActive('note');closeQuickNote();const ov=document.createElement('div');ov.id='kaQuickNoteModal';ov.className='ka-modal-backdrop ka-sheet-backdrop';ov.innerHTML=`<section class="ka-modal ka-quick-note ka-quick-note-launcher"><div class="ka-modal__header"><div><h3>Hızlı Not</h3><p class="ka-muted">Ne eklemek istiyorsunuz?</p></div><button type="button" class="ka-icon-button" data-note-close aria-label="Kapat">${SVG.close}</button></div><div class="ka-modal__body"><div class="ka-quick-note-grid"><button type="button" data-quick-kind="text"><span>📝</span><strong>Metin Notu</strong><small>Başlık ve metin</small></button><button type="button" data-quick-kind="check"><span>☑️</span><strong>Yapılacaklar</strong><small>Kontrol edilebilir görev listesi</small></button><button type="button" data-quick-kind="draw"><span>✏️</span><strong>Çizim</strong><small>El yazısı ve serbest çizim</small></button><button type="button" data-quick-kind="image"><span>🖼️</span><strong>Görsel Not</strong><small>Fotoğraf ve açıklama</small></button><button type="button" data-quick-kind="table"><span>▦</span><strong>Tablo Notu</strong><small>Satır ve sütunlarla kayıt</small></button></div><button type="button" class="ka-quick-note-all" data-quick-kind="all"><span>📚</span><div><strong>Notlarımı Görüntüle</strong><small>Tüm notlarınıza ulaşın</small></div><b>›</b></button></div></section>`;document.body.appendChild(ov);ov.querySelector('[data-note-close]')?.addEventListener('click',quickNoteCloseAndRestore);ov.querySelector('[data-quick-kind="text"]')?.addEventListener('click',openTextQuickNote);ov.querySelector('[data-quick-kind="check"]')?.addEventListener('click',openChecklistQuickNote);ov.querySelector('[data-quick-kind="draw"]')?.addEventListener('click',openDrawingQuickNote);ov.querySelector('[data-quick-kind="image"]')?.addEventListener('click',openImageQuickNote);ov.querySelector('[data-quick-kind="table"]')?.addEventListener('click',openTableQuickNote);ov.querySelector('[data-quick-kind="all"]')?.addEventListener('click',()=>{quickNoteCloseAndRestore();routeModule('communication',{bottom:'menu',page:'notes',title:'Notlarım'})})}
function closeTopModal(){const modal=$$('.ka-modal-backdrop').filter(x=>x.isConnected&&!x.hidden).at(-1);if(!modal)return false;if(modal.id==='kaQuickNoteModal'){quickNoteCloseAndRestore();return true}const close=modal.querySelector('[data-close],[data-service-close],[data-dilekce-modal-kapat],[data-teacher-modal-close],[data-people-modal-close],[data-note-close],[data-note-cancel]');if(close)close.click();else modal.remove();syncLayerLock();return true}
function peopleDetailBack(){const root=$('#v2ModuleRoot');if(!root||global.AppStore?.get?.('ui.route')!=='people')return false;const back=root.querySelector('[data-results-back],[data-student-back],[data-class-back],[data-teacher-close]');if(!back)return false;back.click();return true}
function handleBack(){try{if(headerPopover){closeHeaderPopover();return'handled'}if(closeTopModal())return'handled';const layer=$('#kaMenuLayer');if(layer&&!layer.hidden){if(menuGroup)renderMenuGrid();else{closeMenu();setBottomActive(global.AppStore?.get?.('ui.route')==='dashboard'?'home':'menu')}return'handled'}if(peopleDetailBack())return'handled';const route=global.AppStore?.get?.('ui.route');if(route&&route!=='dashboard'){home();return'handled'}if(activeAction!=='home'){home();return'handled'}}catch(e){console.warn('[Shell/back]',e)}return'exit'}
function home(){closeHeaderPopover();closeMenu();setBottomActive('home');return routeModule('dashboard',{bottom:'home'})}
function bindHeader(){document.addEventListener('click',e=>{const homeBtn=e.target.closest('[data-ka-home-trigger]');if(homeBtn){home();return}const profileBtn=e.target.closest('[data-ka-header-profile]');if(profileBtn){e.preventDefault();openProfilePopover();return}const noticeBtn=e.target.closest('[data-ka-header-notification]');if(noticeBtn&&!noticeBtn.hidden){e.preventDefault();openNotifications()}})}
function bindBottom(){$$('[data-ka-shell-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.kaShellAction;if(a==='home')home();else if(a==='profile')renderProfile();else if(a==='menu')openMenu();else if(a==='search')renderSearch();else if(a==='note')openQuickNote()}))}
function bindDashboardCards(){document.addEventListener('click',e=>{if(e.target.closest('button,a,input,select,textarea,label,[data-dash-route],[data-dash-lesson-plan],[data-dash-reminder-index],[data-dash-external],[data-dash-quick-note]'))return;const card=e.target.closest('[data-home-section]');if(!card)return;const target=DASHBOARD_ROUTES[card.dataset.homeSection];if(target)routeModule(target.module,{bottom:'menu',page:target.page||'',title:target.title||''});})}
function hydrateHeader(){const {name,photo}=profileInfo(),profile=$('[data-ka-header-profile]');if(profile){const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toLocaleUpperCase('tr');profile.innerHTML=photo?`<img src="${esc(photo)}" alt="${esc(name)}">`:esc(initials||'K');profile.setAttribute('aria-label',`${name} hesabı`)}updateNotificationBadge();syncThemeButton()}
function init(){installBuiltInPageRoutes();observeVisibility();observeLayerLock();takeThemeOwnership();bindThemeCapture();bindHeader();bindBottom();bindDashboardCards();global.geriTusuIsle=handleBack;hydrateHeader();hydrateTheme();window.addEventListener('koruk:app-ready',()=>{takeThemeOwnership();syncVisibilityClasses();hydrateHeader();hydrateTheme()});window.addEventListener('koruk:app-config-changed',()=>{if(!$('#kaMenuLayer')?.hidden){menuGroup?renderMenuList(menuGroup):renderMenuGrid()}});global.AppStore?.subscribe?.('session.user',()=>{syncVisibilityClasses();hydrateHeader();hydrateTheme()});for(const type of ['hatirlaticilar','konusmalar','duyurular','ogretmenler'])global.AppStore?.subscribe?.('data.'+type,hydrateHeader)}
global.ShellUI={init,home,openMenu,closeMenu,routeModule,registerPageRoute,renderProfile,renderSearch,openQuickNote,openProfilePopover,openNotifications,toggleTheme,applyTheme,renderMenuGrid,renderMenuList,normalizeDashboardLayout,syncVisibilityClasses,handleBack,MENU_GROUPS,DASHBOARD_ROUTES};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);