from pathlib import Path
import re

ROOT = Path('.')
mgmt_path = ROOT / 'js/modules/management.js'
css_path = ROOT / 'css/design-system.css'
sw_path = ROOT / 'service-worker.js'
test_path = ROOT / 'tests/classic-duty-v2-smoke.test.js'

mgmt = mgmt_path.read_text(encoding='utf-8')
css = css_path.read_text(encoding='utf-8')
sw = sw_path.read_text(encoding='utf-8')
test = test_path.read_text(encoding='utf-8')

def replace_func(src, name, next_name, replacement):
    start_token = f'function {name}('
    end_token = f'\nfunction {next_name}('
    start = src.find(start_token)
    if start < 0:
        raise SystemExit(f'function not found: {name}')
    end = src.find(end_token, start)
    if end < 0:
        raise SystemExit(f'next function not found after {name}: {next_name}')
    return src[:start] + replacement.rstrip() + src[end:]

shell = r'''function shell(){return`<section class="ka-stack" data-management-module><div class="ka-row ka-row--between ka-management-intro" data-management-heading><div><h2>Yönetim</h2><p class="ka-muted">Personel, görev, izin ve nöbet bilgileri cihaz verisinden açılır.</p></div><span id="managementCount" class="ka-badge"></span></div><label class="ka-field ka-management-search" data-management-search-wrap><span class="ka-field__label">Ara</span><input id="managementSearch" type="search" placeholder="Personel, görev veya tarih ara…"></label><div id="managementContent" class="ka-stack"></div></section>`}'''
mgmt = replace_func(mgmt, 'shell', 'staff', shell)

# Remove the old mobile-only day-card renderer. The canonical duty view is now the table on every viewport.
start = mgmt.find('function dutyMobile(')
end = mgmt.find('\nfunction dutyGrid(', start)
if start < 0 or end < 0:
    raise SystemExit('dutyMobile block not found')
mgmt = mgmt[:start] + mgmt[end+1:]

new_grid = r'''function dutyGrid(){const places=NobetService.yerSirali(arr('nobetYerleri')),assign=arr('nobetAtamalari'),chiefs=arr('nobetciAmirleri'),holidays=arr('resmiTatiller'),days=new Date(dutyYear,dutyMonth+1,0).getDate(),rows=[],q=norm(query||''),placeCount=Math.max(1,places.length);for(let d=1;d<=days;d++){const iso=NobetService.tarihISO(dutyYear,dutyMonth,d),dt=new Date(dutyYear,dutyMonth,d),weekend=[0,6].includes(dt.getDay()),holiday=holidays.find(t=>t.tarih===iso),chief=chiefs.find(x=>x.tarih===iso),dayName=dt.toLocaleDateString('tr-TR',{weekday:'short'}).replace('.','').toLocaleUpperCase('tr'),dateLabel=dt.toLocaleDateString('tr-TR',{day:'2-digit',month:'short'}).replace('.',''),dayAssignments=assign.filter(x=>x.tarih===iso),searchText=[iso,dateLabel,dayName,holiday?.aciklama,chief?.ad,...places.map(p=>p.ad),...dayAssignments.map(a=>a.ogretmenAdSoyad)].filter(Boolean).join(' ');if(q&&!norm(searchText).includes(q))continue;if(weekend){rows.push(`<tr class="ka-duty-grid__weekend"><th scope="row"><b>${esc(dateLabel)}</b></th><td class="ka-duty-grid__day">${esc(dayName)}</td><td class="ka-duty-grid__state" colspan="${placeCount}">Hafta sonu</td><td class="ka-duty-grid__empty">—</td></tr>`);continue}if(holiday){rows.push(`<tr class="ka-duty-grid__holiday"><th scope="row"><b>${esc(dateLabel)}</b></th><td class="ka-duty-grid__day">${esc(dayName)}</td><td class="ka-duty-grid__state" colspan="${placeCount}">🎉 ${esc(holiday.aciklama||'Resmi Tatil')}</td><td class="ka-duty-grid__empty">—</td></tr>`);continue}const cells=places.length?places.map(p=>{const a=dayAssignments.find(x=>x.yerId===p.id);return`<td><button type="button" class="ka-duty-cell ${a?'filled':'empty'}" data-duty-cell="${iso}" data-duty-place="${esc(p.id)}" ${canEditDuty()?'':'disabled'}>${a?`<strong>${esc(a.ogretmenAdSoyad||'')}</strong>`:'<span>＋</span>'}</button></td>`}).join(''):'<td class="ka-duty-grid__empty">Nöbet yeri eklenmedi</td>';rows.push(`<tr><th scope="row"><b>${esc(dateLabel)}</b></th><td class="ka-duty-grid__day">${esc(dayName)}</td>${cells}<td><button type="button" class="ka-duty-cell ${chief?'filled':'empty'}" data-duty-chief="${iso}" ${canEditDuty()?'':'disabled'}>${chief?`<strong>${esc(chief.ad||'')}</strong>`:'<span>＋</span>'}</button></td></tr>`)}const placeHeaders=places.length?places.map(p=>`<th>${esc(String(p.ad||'Nöbet Yeri').toLocaleUpperCase('tr'))}</th>`).join(''):'<th>NÖBET ALANI</th>';return`<div class="ka-table-wrap ka-duty-grid-wrap" tabindex="0" aria-label="Aylık nöbet çizelgesi, yatay kaydırılabilir"><table class="ka-duty-grid"><thead><tr><th>Tarih</th><th>Gün</th>${placeHeaders}<th>Nöbetçi Amir</th></tr></thead><tbody>${rows.join('')||`<tr><td colspan="${placeCount+3}"><div class="ka-empty">Aramanızla eşleşen nöbet kaydı bulunamadı.</div></td></tr>`}</tbody></table></div>`}'''
mgmt = replace_func(mgmt, 'dutyGrid', 'duty', new_grid)

new_duty = r'''function duty(){const count=arr('nobetAtamalari').length,monthTitle=new Date(dutyYear,dutyMonth,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'}),edit=canEditDuty(),actions=`${edit?`<button class="ka-duty-action-card" type="button" data-duty-places><span class="ka-duty-action-icon">📍</span><span class="ka-duty-action-copy"><strong>Nöbet Yerleri</strong><small>Bahçe, bina ve alanlar</small></span><span class="ka-duty-action-chevron">›</span></button><button class="ka-duty-action-card" type="button" data-duty-excel><span class="ka-duty-action-icon">📥</span><span class="ka-duty-action-copy"><strong>Excel’den İçe Aktar</strong><small>Dosyadan toplu içe aktar</small></span><span class="ka-duty-action-chevron">›</span></button>`:''}<button class="ka-duty-action-card" type="button" data-duty-report><span class="ka-duty-action-icon">🖨️</span><span class="ka-duty-action-copy"><strong>Nöbet Listesi</strong><small>Çizelgeyi görüntüle ve yazdır</small></span><span class="ka-duty-action-chevron">›</span></button>${edit?`<button class="ka-duty-action-card" type="button" data-duty-auto><span class="ka-duty-action-icon">🔄</span><span class="ka-duty-action-copy"><strong>Otomatik Nöbet Dağıtımı</strong><small>Aylık dağıtımı oluştur</small></span><span class="ka-duty-action-chevron">›</span></button>`:''}`;return{count,html:`<section class="ka-stack ka-duty-page"><div class="ka-duty-action-grid">${actions}</div><div class="ka-duty-summary-grid"><article class="ka-card ka-duty-summary-card"><div class="ka-card__header"><div class="ka-duty-card-title"><span>👥</span><div><small>BUGÜN</small><h3>Bugünün Nöbetçileri</h3></div></div></div><div class="ka-card__body">${todayDutyHtml()}</div></article><article class="ka-card ka-duty-summary-card"><div class="ka-card__header ka-row ka-row--between"><div class="ka-duty-card-title"><span>📅</span><div><small>TAKVİM</small><h3>Resmi Tatiller</h3></div></div>${edit?'<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-duty-holiday-add>+ Tatil Ekle</button>':''}</div><div class="ka-card__body ka-duty-holidays">${holidaysHtml()}</div></article></div><button class="ka-duty-report-card" type="button" data-duty-report><span class="ka-duty-report-icon">📄</span><span class="ka-duty-report-copy"><strong>Öğretmen Nöbet Çizelgesi</strong><small>${esc(monthTitle)} çizelgesini görüntüleyin veya yazdırın.</small></span><span class="ka-duty-report-open">🖨 Önizle</span></button><article class="ka-card ka-duty-surface"><div class="ka-card__body"><div class="ka-duty-month"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-duty-month="-1">‹ Önceki Ay</button><h3>📅 ${esc(monthTitle)}</h3><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-duty-month="1">Sonraki Ay ›</button></div>${dutyGrid()}</div></article></section>`}}'''
mgmt = replace_func(mgmt, 'duty', 'modal', new_duty)

new_report = r'''function dutyReportModal(){const selected=`${dutyYear}-${String(dutyMonth+1).padStart(2,'0')}`,ov=modal('Nöbet Raporu',`<label class="ka-field"><span class="ka-field__label">Ay</span><input type="month" data-month value="${selected}"></label><label class="ka-field"><span class="ka-field__label">Sayfa yönü</span><select data-orientation><option value="dikey">Dikey A4</option><option value="yatay">Yatay A4</option></select></label>`,'Önizle');ov.querySelector('[data-save]').onclick=async()=>{await createDutyReport(ov.querySelector('[data-month]').value,ov.querySelector('[data-orientation]').value);ov.remove()}}
async function createDutyReport(month,yon){if(!globalThis.ReportEngine)await AppLoader.loadScript('js/modules/report-engine.js');const [ys,ms]=String(month).split('-'),y=Number(ys),m=Number(ms)-1;if(!y||m<0)return;const yerler=NobetService.yerSirali(arr('nobetYerleri')),atamalar=arr('nobetAtamalari'),amirler=arr('nobetciAmirleri'),tatiller=arr('resmiTatiller'),okulRows=arr('okulBilgileri'),okul=okulRows.find(x=>x.id==='ayarlar')||okulRows[0]||{},okulAdi=okul.okulAdi||okul.ad||'KORUK İLK - ORTAOKULU',gunSayisi=new Date(y,m+1,0).getDate(),rows=[];for(let g=1;g<=gunSayisi;g++){const dt=new Date(y,m,g),gun=dt.getDay();if(gun===0||gun===6)continue;const iso=NobetService.tarihISO(y,m,g),tatil=tatiller.find(t=>t.tarih===iso);if(tatil){rows.push(`<tr class="ka-duty-report-holiday"><td>${esc(date(iso))}</td><td colspan="${yerler.length+1}"><strong>${esc(tatil.aciklama||tatil.ad||tatil.adi||'RESMİ TATİL')}</strong></td></tr>`);continue}const cells=yerler.map(yer=>`<td>${esc(atamalar.find(x=>x.tarih===iso&&x.yerId===yer.id)?.ogretmenAdSoyad||'')}</td>`).join(''),amir=amirler.find(a=>a.tarih===iso);rows.push(`<tr><td>${esc(date(iso))}</td>${cells}<td>${esc(amir?.ad||'')}</td></tr>`)}const headers=yerler.map(x=>`<th>${esc(String(x.ad||'Nöbet Yeri').toLocaleUpperCase('tr'))}</th>`).join(''),ayBasligi=new Date(y,m,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'}).toLocaleUpperCase('tr'),body=`<section class="ka-duty-report"><div class="ka-duty-report-title"><h1>${esc(String(okulAdi).toLocaleUpperCase('tr'))}</h1><p>${esc(ayBasligi)} ÖĞRETMEN NÖBET ÇİZELGESİ</p></div><table class="ka-duty-report-table"><thead><tr><th>Tarih</th>${headers}<th>Nöbetçi Amir</th></tr></thead><tbody>${rows.join('')}</tbody></table><section class="ka-duty-report-tasks"><h2>NÖBETÇİ ÖĞRETMENİN GÖREVLERİ</h2><ol>${DUTY_TASKS.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section></section>`;return ReportEngine.printReport('Öğretmen Nöbet Çizelgesi',body,{fileName:`Nobet_Cizelgesi_${ys}_${ms}`,yon:yon==='yatay'?'yatay':'dikey',okulAdi,logoGoster:true,tarihGoster:true,baslikGoster:true,compact:true,fontSize:8,kenarBosluk:8})}'''
mgmt = replace_func(mgmt, 'dutyReportModal', 'bindDuty', new_report)

mgmt = mgmt.replace("document.querySelector('[data-duty-report]')?.addEventListener('click',dutyReportModal);", "document.querySelectorAll('[data-duty-report]').forEach(b=>b.addEventListener('click',dutyReportModal));")
old_render = "function render(){if(!mounted)return;const searchWrap=document.querySelector('[data-management-search-wrap]');if(searchWrap)searchWrap.hidden=['duty','puantaj','dilekce'].includes(active);"
new_render = "function render(){if(!mounted)return;const module=document.querySelector('[data-management-module]');module?.classList.toggle('is-duty-page',active==='duty');const searchWrap=document.querySelector('[data-management-search-wrap]');if(searchWrap)searchWrap.hidden=['puantaj','dilekce'].includes(active);"
if old_render not in mgmt:
    raise SystemExit('render visibility marker not found')
mgmt = mgmt.replace(old_render, new_render, 1)

# Retire the old mobile duty card CSS hooks that forced the table off on phones.
css = css.replace('.ka-schedule-mobile,.ka-duty-mobile{display:none}', '.ka-schedule-mobile{display:none}')
css = css.replace('.ka-schedule-wrap,.ka-duty-grid-wrap{display:none}', '.ka-schedule-wrap{display:none}')
css = css.replace('.ka-schedule-mobile,.ka-duty-mobile{display:block}', '.ka-schedule-mobile{display:block}')
css = re.sub(r'^\s*\.ka-duty-mobile[^\n]*\n', '', css, flags=re.M)

marker = '/* ===== NÖBET PROGRAMI CANONICAL REDESIGN ===== */'
if marker in css:
    raise SystemExit('duty redesign CSS already exists')
css += r'''

/* ===== NÖBET PROGRAMI CANONICAL REDESIGN ===== */
[data-management-module].is-duty-page{gap:14px;max-width:1180px;margin:0 auto}
.is-duty-page>.ka-management-intro{position:relative;overflow:hidden;align-items:center;min-height:146px;padding:22px 24px;border:1px solid var(--ka-hero-border);border-radius:26px;background:linear-gradient(135deg,color-mix(in srgb,var(--ka-primary) 92%,#0b533e),color-mix(in srgb,var(--ka-primary-hover) 88%,#073d2f));box-shadow:var(--ka-hero-shadow);color:#fff}
.is-duty-page>.ka-management-intro:after{content:"";position:absolute;right:-45px;bottom:-86px;width:270px;height:190px;border:34px solid color-mix(in srgb,#fff 7%,transparent);border-radius:50%}
.is-duty-page>.ka-management-intro>*,.is-duty-page>.ka-management-intro h2,.is-duty-page>.ka-management-intro p{position:relative;z-index:1;color:#fff}.is-duty-page>.ka-management-intro h2{font-size:30px}.is-duty-page>.ka-management-intro p{max-width:620px;margin-top:7px;color:color-mix(in srgb,#fff 76%,transparent);font-size:13px}.is-duty-page>.ka-management-intro #managementCount{min-width:74px;min-height:64px;display:grid;place-items:center;padding:8px 13px;border:1px solid color-mix(in srgb,#fff 22%,transparent);background:color-mix(in srgb,#071812 22%,transparent);color:#9df1cf;font-size:13px;text-align:center}
.is-duty-page>.ka-management-search{margin:0}.is-duty-page>.ka-management-search .ka-field__label{display:none}.is-duty-page>.ka-management-search input{min-height:54px;border-radius:17px;padding-left:16px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm)}
.ka-duty-page{width:100%;max-width:1180px;margin:0 auto;gap:14px}.ka-duty-action-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ka-duty-action-card{appearance:none;min-width:0;min-height:88px;display:grid;grid-template-columns:42px minmax(0,1fr) 20px;gap:10px;align-items:center;padding:13px;border:1px solid color-mix(in srgb,var(--ka-primary) 34%,var(--ka-border));border-radius:19px;background:linear-gradient(145deg,color-mix(in srgb,var(--ka-primary) 13%,var(--ka-card-bg)),var(--ka-card-bg));color:var(--ka-text);text-align:left;box-shadow:var(--ka-shadow-sm);cursor:pointer}.ka-duty-action-card:active{transform:scale(.99)}.ka-duty-action-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:var(--ka-primary-soft);font-size:20px}.ka-duty-action-copy{min-width:0}.ka-duty-action-copy strong,.ka-duty-action-copy small{display:block}.ka-duty-action-copy strong{font-size:13px;line-height:1.25}.ka-duty-action-copy small{margin-top:3px;color:var(--ka-text-muted);font-size:9px;line-height:1.35}.ka-duty-action-chevron{color:var(--ka-primary);font-size:23px;font-weight:800}
.ka-duty-summary-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ka-duty-summary-card{overflow:hidden}.ka-duty-card-title{display:flex;align-items:center;gap:9px}.ka-duty-card-title>span{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;background:var(--ka-primary-soft);font-size:17px}.ka-duty-card-title small{display:block;color:var(--ka-primary);font-size:8px;font-weight:950;letter-spacing:.09em}.ka-duty-card-title h3{margin-top:2px;font-size:15px}.ka-duty-today-row{display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--ka-border)}.ka-duty-today-row:last-child{border-bottom:0}.ka-duty-today-row strong,.ka-duty-today-row span{display:block}.ka-duty-today-row strong{color:var(--ka-text-muted);font-size:8px;text-transform:uppercase;letter-spacing:.04em}.ka-duty-today-row span{margin-top:2px;color:var(--ka-primary);font-size:12px;font-weight:900}.ka-duty-holidays{max-height:245px;overflow:auto}.ka-duty-holiday{display:flex;align-items:center;gap:9px;padding:8px 0;border-bottom:1px solid var(--ka-border)}.ka-duty-holiday:last-child{border-bottom:0}
.ka-duty-report-card{appearance:none;width:100%;display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:12px;align-items:center;padding:12px 14px;border:1px solid var(--ka-border);border-radius:18px;background:var(--ka-card-bg);color:var(--ka-text);box-shadow:var(--ka-shadow-sm);text-align:left;cursor:pointer}.ka-duty-report-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:15px;background:var(--ka-primary-soft);font-size:22px}.ka-duty-report-copy{min-width:0}.ka-duty-report-copy strong,.ka-duty-report-copy small{display:block}.ka-duty-report-copy strong{font-size:14px}.ka-duty-report-copy small{margin-top:3px;color:var(--ka-text-muted);font-size:10px}.ka-duty-report-open{min-height:38px;display:inline-flex;align-items:center;padding:0 12px;border:1px solid color-mix(in srgb,var(--ka-primary) 45%,var(--ka-border));border-radius:12px;color:var(--ka-primary);font-size:10px;font-weight:850}
.ka-duty-surface{overflow:hidden}.ka-duty-surface>.ka-card__body{padding:13px}.ka-duty-month{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:9px;margin-bottom:10px}.ka-duty-month h3{text-align:center;text-transform:capitalize;font-size:16px}.ka-duty-grid-wrap{display:block!important;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch;border:1px solid var(--ka-border);border-radius:15px;background:var(--ka-card-bg);scrollbar-width:thin}.ka-duty-grid{width:100%;min-width:760px;border-collapse:separate;border-spacing:0;font-size:10px}.ka-duty-grid th,.ka-duty-grid td{height:44px;padding:0;border-right:1px solid var(--ka-border);border-bottom:1px solid var(--ka-border);background:var(--ka-card-bg);vertical-align:middle}.ka-duty-grid tr>*:last-child{border-right:0}.ka-duty-grid tbody tr:last-child>*{border-bottom:0}.ka-duty-grid thead th{position:sticky;top:0;z-index:5;height:42px;padding:7px 9px;background:linear-gradient(180deg,#1d7b5c,#17684f);color:#fff;font-size:9px;font-weight:900;text-align:center;white-space:nowrap}.ka-duty-grid thead th:first-child{left:0;z-index:8}.ka-duty-grid tbody th{position:sticky;left:0;z-index:3;min-width:88px;padding:0 9px;background:var(--ka-card-bg);color:var(--ka-text);text-align:left;font-size:11px;white-space:nowrap}.ka-duty-grid__day{min-width:58px;text-align:center;color:var(--ka-text-muted);font-size:9px;font-weight:800}.ka-duty-grid td{min-width:145px}.ka-duty-grid td:last-child{min-width:130px}.ka-duty-cell{appearance:none;width:100%;height:43px;border:0;background:transparent;color:var(--ka-text);padding:6px 8px;text-align:center;font:inherit;cursor:pointer}.ka-duty-cell:disabled{opacity:1;cursor:default}.ka-duty-cell strong{font-size:10px;font-weight:850;white-space:normal}.ka-duty-cell span{color:var(--ka-primary);font-size:17px}.ka-duty-cell.filled{background:color-mix(in srgb,var(--ka-primary) 8%,var(--ka-card-bg));color:var(--ka-primary)}.ka-duty-grid__state{color:var(--ka-warning);background:color-mix(in srgb,var(--ka-warning) 8%,var(--ka-card-bg))!important;text-align:center;font-weight:850}.ka-duty-grid__holiday .ka-duty-grid__state{color:var(--ka-primary);background:var(--ka-primary-soft)!important}.ka-duty-grid__empty{text-align:center;color:var(--ka-text-muted)}
[data-theme="dark"] .ka-duty-grid thead th{background:linear-gradient(180deg,#165741,#103e30)}[data-theme="dark"] .ka-duty-action-card{background:linear-gradient(145deg,color-mix(in srgb,var(--ka-primary) 9%,var(--ka-card-bg)),var(--ka-card-bg))}
@media(max-width:760px){.is-duty-page>.ka-management-intro{min-height:132px;padding:18px;border-radius:22px}.is-duty-page>.ka-management-intro h2{font-size:25px}.is-duty-page>.ka-management-intro p{font-size:11px}.ka-duty-action-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ka-duty-action-card{min-height:80px;padding:11px;grid-template-columns:37px minmax(0,1fr) 17px}.ka-duty-action-icon{width:37px;height:37px;border-radius:11px;font-size:18px}.ka-duty-summary-grid{grid-template-columns:1fr}.ka-duty-report-card{grid-template-columns:42px minmax(0,1fr) auto;padding:10px}.ka-duty-report-icon{width:42px;height:42px}.ka-duty-report-open{padding-inline:9px}.ka-duty-surface>.ka-card__body{padding:9px}.ka-duty-month{grid-template-columns:1fr auto 1fr;gap:5px}.ka-duty-month h3{font-size:12px}.ka-duty-month .ka-btn{min-width:0;padding-inline:7px;font-size:8.5px}.ka-duty-grid{min-width:720px}}
@media(max-width:390px){.ka-duty-action-copy small{display:none}.ka-duty-action-card{min-height:68px}.ka-duty-report-open{font-size:0}.ka-duty-report-open:after{content:"🖨";font-size:17px}}

/* Duty report uses the same ReportEngine shell but preserves the uploaded roster anatomy. */
.ka-report .ka-duty-report{color:#111}.ka-report .ka-duty-report-title{text-align:center;margin:3px 0 7px}.ka-report .ka-duty-report-title h1{margin:0!important;color:#111!important;font-size:12pt!important;font-weight:800!important;line-height:1.15!important}.ka-report .ka-duty-report-title p{margin:4px 0 0!important;color:#111!important;font-size:9pt!important;line-height:1.15!important}.ka-report .ka-duty-report-table{table-layout:fixed}.ka-report .ka-duty-report-table th{padding:3px 4px!important;background:#17684f!important;border-color:#397461!important;color:#fff!important;font-size:7.4pt!important;line-height:1.1!important}.ka-report .ka-duty-report-table td{height:17px!important;padding:2.2px 4px!important;border-color:#d5ded9!important;background:#fff!important;color:#17221e!important;font-size:7.2pt!important;line-height:1.12!important}.ka-report .ka-duty-report-table tbody tr:nth-child(even) td{background:#f7faf8!important}.ka-report .ka-duty-report-table th:first-child,.ka-report .ka-duty-report-table td:first-child{width:16%;white-space:nowrap}.ka-report .ka-duty-report-holiday td{font-weight:800!important;text-align:center!important;background:#f1f6f3!important}.ka-report .ka-duty-report-tasks{margin-top:7px;color:#111}.ka-report .ka-duty-report-tasks h2{margin:0 0 4px!important;color:#111!important;font-size:10.5pt!important;line-height:1.15!important}.ka-report .ka-duty-report-tasks ol{margin:0!important;padding-left:18px!important}.ka-report .ka-duty-report-tasks li{margin:0 0 2px!important;padding-left:2px!important;color:#111!important;font-size:7.2pt!important;line-height:1.22!important}
'''

if "const CACHE_ADI='oy-cache-v817';" not in sw:
    raise SystemExit('expected service worker cache v817 not found')
sw = sw.replace("const CACHE_ADI='oy-cache-v817';", "const CACHE_ADI='oy-cache-v818';", 1)

old_test = "for(const marker of ['dutyMobile','ka-duty-mobile','ka-duty-mobile-chip','ka-duty-mobile-chief','ka-duty-mobile-notice']) assert(src.includes(marker),`Mobil Nöbet görünüm sözleşmesi eksik: ${marker}`);\nassert(src.includes('${dutyMobile()}${dutyGrid()}'),'Mobil ve masaüstü Nöbet Programı aynı canonical render akışından üretilmeli.');"
new_test = "assert(!src.includes('function dutyMobile('),'Mobil gün-kartı rendererı emekliye ayrılmalı.');\nassert(!src.includes('${dutyMobile()}${dutyGrid()}'),'Nöbet Programı mobilde ayrı gün kartı rendererı kullanmamalı.');\nassert(src.includes('${dutyGrid()}'),'Aylık Nöbet Programı tüm ekranlarda canonical tablo rendererı üzerinden üretilmeli.');\nfor(const marker of ['ka-duty-action-grid','ka-duty-report-card','ka-duty-grid__day','tabindex=\\\"0\\\"','Gün']) assert(src.includes(marker),`Yeni Nöbet tablo/tasarım sözleşmesi eksik: ${marker}`);\nassert(src.includes('ka-duty-report-title')&&src.includes('ka-duty-report-table')&&src.includes('ka-duty-report-tasks'),'Yüklenen örneğe karşılık gelen nöbet rapor anatomisi korunmalı.');\nassert(src.includes('compact:true')&&src.includes('fontSize:8')&&src.includes('kenarBosluk:8'),'Nöbet raporu tek sayfalık kompakt A4 ayarlarını kullanmalı.');"
if old_test not in test:
    raise SystemExit('classic duty test marker not found')
test = test.replace(old_test, new_test, 1)

mgmt_path.write_text(mgmt, encoding='utf-8')
css_path.write_text(css, encoding='utf-8')
sw_path.write_text(sw, encoding='utf-8')
test_path.write_text(test, encoding='utf-8')

print('Duty program redesign patch applied.')
