from pathlib import Path

css_path=Path('css/design-system.css')
css=css_path.read_text(encoding='utf-8')
marker='/* Servis Oturma — alternatif tasarım v5 */'
if marker not in css:
    css += r'''

/* Servis Oturma — alternatif tasarım v5 */
.ka-bus-editor-backdrop{padding:clamp(8px,2vw,18px)!important;align-items:center!important;background:color-mix(in srgb,var(--ka-overlay) 88%,#04110c 12%)!important;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}
.ka-bus-editor-modal.ka-bus-classic-modal{width:min(100%,720px)!important;max-width:720px!important;height:min(96dvh,980px)!important;max-height:96dvh!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;border:1px solid color-mix(in srgb,var(--ka-primary) 26%,var(--ka-border))!important;border-radius:28px!important;background:linear-gradient(180deg,color-mix(in srgb,var(--ka-card-bg) 96%,var(--ka-primary) 4%),var(--ka-card-bg))!important;box-shadow:0 28px 80px rgba(0,0,0,.38)!important}
.ka-bus-classic-header{flex:0 0 auto!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:16px 18px!important;background:linear-gradient(135deg,color-mix(in srgb,var(--ka-primary) 88%,#006747 12%),color-mix(in srgb,var(--ka-primary) 72%,#0f9f74 28%))!important;border-bottom:0!important;color:#fff!important}.ka-bus-classic-header h2{font-size:clamp(18px,4vw,25px)!important;line-height:1.12!important;color:#fff!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.ka-bus-classic-header .ka-icon-button{flex:0 0 44px!important;background:rgba(255,255,255,.12)!important;color:#fff!important;border:1px solid rgba(255,255,255,.12)!important}
.ka-bus-classic-content{flex:1 1 auto!important;min-height:0!important;overflow-y:auto!important;overscroll-behavior:contain!important;padding:14px!important;padding-bottom:18px!important;gap:12px!important;background:radial-gradient(circle at 100% 0,color-mix(in srgb,var(--ka-primary) 9%,transparent),transparent 32%),var(--ka-card-bg)!important}
.ka-bus-classic-hero{padding:12px!important;border-radius:18px!important;border:1px solid color-mix(in srgb,var(--ka-primary) 18%,var(--ka-border))!important;background:linear-gradient(145deg,color-mix(in srgb,var(--ka-primary-soft) 68%,var(--ka-card-bg)),var(--ka-card-bg))!important;box-shadow:none!important}.ka-bus-classic-hero h3{font-size:16px!important;margin-bottom:9px!important;display:flex!important;align-items:center!important;gap:8px!important}.ka-bus-classic-stats{display:grid!important;grid-template-columns:1.25fr 1.25fr .8fr .75fr!important;gap:0!important;border-top:1px solid color-mix(in srgb,var(--ka-border) 78%,transparent)!important;border-bottom:1px solid color-mix(in srgb,var(--ka-border) 78%,transparent)!important}.ka-bus-classic-stats>div{min-width:0!important;padding:9px 9px 8px!important;border-right:1px solid color-mix(in srgb,var(--ka-border) 76%,transparent)!important}.ka-bus-classic-stats>div:last-child{border-right:0!important}.ka-bus-classic-stats small{display:block!important;font-size:9px!important;letter-spacing:.06em!important;color:var(--ka-text-muted)!important}.ka-bus-classic-stats strong{display:block!important;margin-top:3px!important;font-size:12px!important;line-height:1.25!important;white-space:normal!important;overflow-wrap:anywhere!important;color:var(--ka-text)!important}.ka-bus-classic-hero p{margin-top:9px!important;font-size:11px!important;line-height:1.35!important;color:var(--ka-text-muted)!important}
.ka-bus-template-section{display:grid!important;gap:7px!important;margin:0!important;padding:0!important}.ka-bus-template-section>.ka-muted{font-size:11px!important;font-weight:800!important;text-transform:uppercase!important;letter-spacing:.06em!important}.ka-bus-template-grid{display:flex!important;grid-template-columns:none!important;gap:7px!important;overflow-x:auto!important;padding:1px 1px 5px!important;scrollbar-width:none!important;scroll-snap-type:x proximity!important}.ka-bus-template-grid::-webkit-scrollbar{display:none!important}.ka-bus-template-card{flex:0 0 138px!important;min-height:58px!important;display:grid!important;grid-template-columns:28px 1fr!important;grid-template-rows:auto auto!important;align-items:center!important;column-gap:7px!important;row-gap:0!important;padding:8px 9px!important;border-radius:14px!important;border:1px solid var(--ka-border)!important;background:var(--ka-muted-bg)!important;color:var(--ka-text)!important;text-align:left!important;scroll-snap-align:start!important;box-shadow:none!important}.ka-bus-template-card>span{grid-row:1/3!important;font-size:22px!important}.ka-bus-template-card strong{font-size:11px!important;line-height:1.12!important;color:inherit!important}.ka-bus-template-card small{font-size:8.5px!important;line-height:1.15!important;color:var(--ka-text-muted)!important}.ka-bus-template-card.is-active{background:linear-gradient(135deg,#18b86a,#0e9f5b)!important;border-color:#27d47f!important;color:#fff!important;box-shadow:0 7px 18px rgba(17,170,99,.22)!important}.ka-bus-template-card.is-active small{color:rgba(255,255,255,.84)!important}
.ka-bus-edit-row{display:flex!important;margin:0!important}.ka-bus-edit-row .ka-btn{width:100%!important;min-height:42px!important;border-radius:13px!important;background:color-mix(in srgb,var(--ka-primary-soft) 70%,var(--ka-card-bg))!important;border-color:color-mix(in srgb,var(--ka-primary) 46%,var(--ka-border))!important;color:var(--ka-primary)!important}.ka-bus-edit-hint{margin:0!important;padding:9px 11px!important;border-radius:12px!important;background:color-mix(in srgb,var(--ka-info) 10%,var(--ka-card-bg))!important;border:1px solid color-mix(in srgb,var(--ka-info) 24%,var(--ka-border))!important;font-size:10px!important;color:var(--ka-text-muted)!important}
.ka-bus-tool-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:7px!important;margin:0!important}.ka-bus-tool-grid .ka-btn{width:100%!important;min-width:0!important;min-height:44px!important;padding:5px 6px!important;border-radius:13px!important;font-size:10.5px!important;line-height:1.1!important;white-space:normal!important;text-align:center!important}.ka-bus-tool-grid [data-bus-row-add]{background:linear-gradient(135deg,#13ad63,#0c9252)!important;border-color:#1cc976!important;color:#fff!important}.ka-bus-tool-grid [data-bus-row-remove]{background:var(--ka-button-secondary-bg)!important;color:var(--ka-button-secondary-text)!important;border-color:var(--ka-button-secondary-border)!important}.ka-bus-tool-grid [data-bus-report]{background:linear-gradient(135deg,#327fd9,#1d65bc)!important;border-color:#418fe8!important;color:#fff!important}.ka-bus-tool-grid [data-bus-clear-all]{background:linear-gradient(135deg,#e64b4b,#c93636)!important;border-color:#ee6565!important;color:#fff!important}
.ka-bus-classic-stage{display:flex!important;justify-content:center!important;align-items:flex-start!important;padding:12px 7px 15px!important;border-radius:22px!important;border:1px solid color-mix(in srgb,var(--ka-border) 82%,transparent)!important;background:linear-gradient(180deg,color-mix(in srgb,var(--ka-muted-bg) 74%,#dbe4e0 26%),color-mix(in srgb,var(--ka-card-bg) 90%,var(--ka-primary-soft) 10%))!important;overflow:visible!important}.ka-bus-classic-shell{width:min(100%,420px)!important;max-width:420px!important;min-height:560px!important;margin:0 auto!important;padding:10px 10px 14px!important;border:3px solid color-mix(in srgb,#647580 76%,var(--ka-border))!important;border-radius:38px 38px 26px 26px!important;background:linear-gradient(180deg,#31434a,#25353b 62%,#2d3f45)!important;box-shadow:0 14px 28px rgba(10,30,24,.24),inset 0 0 0 1px rgba(255,255,255,.06)!important;color:#fff!important}.ka-bus-classic-lights{display:grid!important;grid-template-columns:26px 1fr 26px!important;align-items:center!important;gap:8px!important;margin:1px 7px 8px!important}.ka-bus-classic-lights>span{font-size:16px!important;filter:saturate(1.12)!important}.ka-bus-classic-lights>i{height:17px!important;border-radius:7px!important;background:linear-gradient(180deg,#2677c7,#1b5c9f)!important;border:1px solid rgba(255,255,255,.22)!important;box-shadow:inset 0 1px 4px rgba(255,255,255,.18)!important}.ka-bus-classic-plate{width:max-content!important;max-width:80%!important;margin:0 auto 12px!important;padding:5px 15px!important;border-radius:10px!important;border:2px solid #8a99a3!important;background:#182329!important;color:#fff!important;font-size:13px!important;font-weight:900!important;letter-spacing:.13em!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.ka-bus-classic-front-row{display:grid!important;grid-template-columns:minmax(0,1.22fr) minmax(0,.92fr)!important;gap:12px!important;align-items:start!important;margin-bottom:12px!important}.ka-bus-classic-driver{min-height:94px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:3px!important;padding:8px!important;border-radius:18px!important;border:1px solid rgba(213,173,79,.48)!important;background:linear-gradient(145deg,#33301f,#23251b)!important;color:#ffd572!important;box-shadow:none!important}.ka-bus-classic-driver span{font-size:28px!important;line-height:1!important}.ka-bus-classic-driver strong{width:100%!important;max-width:100%!important;white-space:normal!important;overflow:visible!important;text-overflow:clip!important;overflow-wrap:anywhere!important;text-align:center!important;font-size:12px!important;line-height:1.1!important;color:#f5d180!important}.ka-bus-classic-front-seats{display:flex!important;justify-content:flex-end!important;gap:8px!important;min-width:0!important}
.ka-bus-classic-body{display:grid!important;gap:9px!important}.ka-bus-classic-row{display:grid!important;grid-template-columns:minmax(0,1fr) 38px minmax(0,1fr)!important;gap:4px!important;align-items:center!important}.ka-bus-classic-side{display:flex!important;gap:7px!important;min-width:0!important}.ka-bus-classic-side.is-left{justify-content:flex-end!important}.ka-bus-classic-side.is-right{justify-content:flex-start!important}.ka-bus-classic-aisle{min-width:38px!important;display:flex!important;align-items:center!important;justify-content:center!important;align-self:stretch!important;border-inline:1px dashed rgba(255,255,255,.13)!important;color:#c6d0d4!important}.ka-bus-classic-door{display:flex!important;flex-direction:column!important;align-items:center!important;gap:2px!important;font-size:13px!important}.ka-bus-classic-door b{font-size:8px!important;font-weight:700!important;letter-spacing:.1em!important;writing-mode:vertical-rl!important}.ka-bus-classic-rear{display:flex!important;justify-content:center!important;gap:7px!important;margin-top:12px!important;padding-top:12px!important;border-top:1px dashed rgba(255,255,255,.22)!important}
.ka-bus-classic-shell .ka-bus-seat{position:relative!important;width:64px!important;max-width:64px!important;height:76px!important;min-height:76px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important;padding:6px 4px!important;border-radius:15px!important;border:2px solid #586575!important;background:linear-gradient(180deg,#465263,#394453)!important;color:#e9eef2!important;box-shadow:inset 0 -5px 0 rgba(0,0,0,.08),0 4px 8px rgba(0,0,0,.18)!important;overflow:hidden!important}.ka-bus-classic-shell .ka-bus-seat::after{content:'';position:absolute!important;inset:4px!important;border-radius:11px!important;border:1px solid rgba(255,255,255,.06)!important;pointer-events:none!important}.ka-bus-classic-shell .ka-bus-seat.is-filled{background:linear-gradient(180deg,#28d879,#0daf5b)!important;border-color:#19c96b!important;color:#fff!important;box-shadow:inset 0 -6px 0 rgba(0,102,52,.18),0 4px 9px rgba(0,155,80,.25)!important}.ka-bus-classic-shell .ka-bus-seat.is-reserved{background:linear-gradient(180deg,#3e94f0,#236ecb)!important;border-color:#4da1ff!important;color:#fff!important}.ka-bus-classic-shell .ka-bus-seat.is-locked{background:linear-gradient(180deg,#ffbd3f,#ef9715)!important;border-color:#ffc657!important;color:#2b210d!important}.ka-bus-classic-shell .ka-bus-seat__avatar{position:relative!important;z-index:1!important;width:24px!important;height:24px!important;display:grid!important;place-items:center!important;flex:0 0 24px!important;margin:0!important;border-radius:50%!important;background:rgba(9,66,48,.72)!important;color:#fff!important;font-size:9px!important;font-weight:900!important}.ka-bus-classic-shell .ka-bus-seat__number{position:absolute!important;top:4px!important;left:6px!important;z-index:2!important;font-size:8px!important;font-weight:900!important;opacity:.72!important}.ka-bus-classic-shell .ka-bus-seat__name{position:relative!important;z-index:1!important;display:-webkit-box!important;width:100%!important;max-height:31px!important;overflow:hidden!important;-webkit-box-orient:vertical!important;-webkit-line-clamp:3!important;white-space:normal!important;overflow-wrap:anywhere!important;text-overflow:clip!important;text-align:center!important;font-size:8.6px!important;line-height:1.04!important;font-weight:850!important;color:inherit!important}.ka-bus-classic-rear .ka-bus-seat{width:62px!important;max-width:62px!important}.ka-bus-classic-shell .ka-bus-seat:active{transform:scale(.97)!important}
.ka-bus-classic-legend{display:flex!important;justify-content:center!important;flex-wrap:wrap!important;gap:8px 14px!important;margin:0!important;padding:9px 11px!important;border-radius:14px!important;border:1px solid var(--ka-border)!important;background:var(--ka-muted-bg)!important}.ka-bus-classic-legend span{display:flex!important;align-items:center!important;gap:5px!important;font-size:10px!important;color:var(--ka-text-muted)!important}.ka-bus-classic-legend i{width:13px!important;height:13px!important;border-radius:4px!important}.ka-bus-classic-legend .is-filled{background:#18c96a!important}.ka-bus-classic-legend .is-empty{background:#465263!important}.ka-bus-classic-legend .is-reserved{background:#2f7fe0!important}.ka-bus-classic-legend .is-locked{background:#f2a21d!important}
.ka-bus-classic-footer{flex:0 0 auto!important;display:grid!important;grid-template-columns:minmax(0,.8fr) minmax(0,1.3fr)!important;gap:9px!important;padding:11px 14px max(11px,var(--ka-safe-bottom))!important;border-top:1px solid var(--ka-border)!important;background:color-mix(in srgb,var(--ka-card-bg) 95%,transparent)!important;backdrop-filter:blur(14px)!important;-webkit-backdrop-filter:blur(14px)!important}.ka-bus-classic-footer .ka-btn{width:100%!important;min-height:48px!important;border-radius:14px!important}.ka-bus-classic-footer [data-bus-save]{background:linear-gradient(135deg,#16b966,#0e9855)!important;border-color:#22cb75!important;color:#fff!important;box-shadow:0 8px 20px rgba(14,152,85,.22)!important}.ka-bus-classic-stage+.ka-bus-row-actions,.ka-bus-classic-legend+.ka-bus-classic-actions{display:none!important}
.ka-bus-seat-picker{z-index:1000050!important;align-items:flex-end!important;padding:0!important;background:rgba(3,14,10,.72)!important;backdrop-filter:blur(8px)!important;-webkit-backdrop-filter:blur(8px)!important}.ka-bus-seat-picker__modal{width:100%!important;max-width:560px!important;max-height:88dvh!important;margin:0 auto!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;border-radius:24px 24px 0 0!important;border:1px solid color-mix(in srgb,var(--ka-primary) 26%,var(--ka-border))!important;background:var(--ka-card-bg)!important;box-shadow:0 -18px 50px rgba(0,0,0,.36)!important}.ka-bus-seat-picker__modal .ka-modal__header{padding:14px 15px!important;border-bottom:1px solid var(--ka-border)!important;background:linear-gradient(135deg,color-mix(in srgb,var(--ka-primary-soft) 78%,var(--ka-card-bg)),var(--ka-card-bg))!important}.ka-bus-seat-picker__modal .ka-modal__header h3{font-size:18px!important}.ka-bus-seat-picker__modal .ka-modal__body{overflow-y:auto!important;padding:13px!important;gap:10px!important}.ka-bus-seat-picker__modal input[type=search]{min-height:46px!important;border-radius:14px!important;background:var(--ka-muted-bg)!important}.ka-bus-student-list{display:grid!important;gap:7px!important}.ka-bus-student-option{width:100%!important;display:flex!important;align-items:center!important;gap:10px!important;padding:9px 10px!important;border:1px solid var(--ka-border)!important;border-radius:14px!important;background:var(--ka-card-bg)!important;color:var(--ka-text)!important;text-align:left!important}.ka-bus-student-option:hover,.ka-bus-student-option:focus-visible{border-color:color-mix(in srgb,var(--ka-primary) 52%,var(--ka-border))!important;background:color-mix(in srgb,var(--ka-primary-soft) 54%,var(--ka-card-bg))!important}.ka-bus-student-option__avatar{width:38px!important;height:38px!important;flex:0 0 38px!important;display:grid!important;place-items:center!important;border-radius:50%!important;background:linear-gradient(135deg,#20c878,#0e9f5b)!important;color:#fff!important;font-weight:900!important}.ka-bus-student-option strong{display:block!important;font-size:13px!important;line-height:1.2!important}.ka-bus-student-option small{display:block!important;margin-top:2px!important;font-size:10px!important;color:var(--ka-text-muted)!important}.ka-bus-seat-picker-actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;padding:10px 13px max(10px,var(--ka-safe-bottom))!important;border-top:1px solid var(--ka-border)!important;background:var(--ka-card-bg)!important}.ka-bus-seat-picker-actions .ka-btn{width:100%!important;min-height:42px!important;font-size:11px!important;border-radius:12px!important}
[data-theme="dark"] .ka-bus-classic-stage{background:linear-gradient(180deg,#0e1c18,#0a1512)!important;border-color:#284239!important}[data-theme="dark"] .ka-bus-classic-shell{background:linear-gradient(180deg,#24343b,#1b292f 62%,#223238)!important;border-color:#50636c!important}[data-theme="dark"] .ka-bus-template-card{background:#111d18!important;border-color:#294239!important}[data-theme="dark"] .ka-bus-classic-hero{background:linear-gradient(145deg,#132a21,#101b17)!important}
@media(max-width:560px){.ka-bus-editor-backdrop{padding:0!important;align-items:stretch!important}.ka-bus-editor-modal.ka-bus-classic-modal{width:100%!important;max-width:none!important;height:100dvh!important;max-height:100dvh!important;border-radius:0!important;border-inline:0!important}.ka-bus-classic-header{padding:14px 15px!important}.ka-bus-classic-content{padding:11px!important}.ka-bus-classic-hero{padding:10px!important}.ka-bus-classic-stats>div{padding:7px 5px!important}.ka-bus-classic-stats small{font-size:7.5px!important}.ka-bus-classic-stats strong{font-size:10px!important}.ka-bus-tool-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.ka-bus-tool-grid .ka-btn{min-height:42px!important;font-size:10.5px!important}.ka-bus-classic-stage{padding:9px 4px 12px!important;border-radius:18px!important}.ka-bus-classic-shell{width:min(100%,390px)!important;padding:9px 7px 13px!important;border-radius:34px 34px 24px 24px!important}.ka-bus-classic-row{grid-template-columns:minmax(0,1fr) 34px minmax(0,1fr)!important}.ka-bus-classic-aisle{min-width:34px!important}.ka-bus-classic-shell .ka-bus-seat{width:58px!important;max-width:58px!important;height:72px!important;min-height:72px!important}.ka-bus-classic-rear .ka-bus-seat{width:55px!important;max-width:55px!important}.ka-bus-classic-shell .ka-bus-seat__name{font-size:7.8px!important}.ka-bus-classic-front-row{gap:8px!important}.ka-bus-classic-driver{min-height:90px!important}.ka-bus-classic-footer{padding-inline:10px!important}.ka-bus-seat-picker__modal{max-width:none!important}}
@media(min-width:561px){.ka-bus-seat-picker{align-items:center!important;padding:18px!important}.ka-bus-seat-picker__modal{border-radius:24px!important;max-height:min(80dvh,760px)!important}}
'''
css_path.write_text(css,encoding='utf-8')

index_path=Path('index.html')
index=index_path.read_text(encoding='utf-8')
if 'css/design-system.css?v=892' not in index:
    raise SystemExit('index CSS version token moved')
index=index.replace('css/design-system.css?v=892','css/design-system.css?v=893',1)
index_path.write_text(index,encoding='utf-8')

sw_path=Path('service-worker.js')
sw=sw_path.read_text(encoding='utf-8')
for old,new in [("const CACHE_ADI='oy-cache-v892';","const CACHE_ADI='oy-cache-v893';"),("'./css/design-system.css?v=892'","'./css/design-system.css?v=893'")]:
    if old not in sw:
        raise SystemExit(f'service worker token moved: {old}')
    sw=sw.replace(old,new,1)
sw_path.write_text(sw,encoding='utf-8')

for path in Path('tests').glob('transport-*.test.js'):
    txt=path.read_text(encoding='utf-8')
    txt=txt.replace('css/design-system.css?v=892','css/design-system.css?v=893')
    txt=txt.replace("CACHE_ADI='oy-cache-v892'","CACHE_ADI='oy-cache-v893'")
    txt=txt.replace("'./css/design-system.css?v=892'","'./css/design-system.css?v=893'")
    path.write_text(txt,encoding='utf-8')

new_test=Path('tests/transport-seating-alt-design.test.js')
new_test.write_text(r'''const fs=require('fs');
const assert=require('assert');
const css=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
for(const token of ['Servis Oturma — alternatif tasarım v5','.ka-bus-editor-modal.ka-bus-classic-modal','.ka-bus-template-grid{display:flex!important','.ka-bus-tool-grid{display:grid!important','.ka-bus-classic-shell .ka-bus-seat.is-filled','.ka-bus-seat-picker__modal','.ka-bus-student-option','[data-theme="dark"] .ka-bus-classic-stage'])assert(css.includes(token),`Alternatif servis oturma tasarım sözleşmesi eksik: ${token}`);
assert(index.includes('css/design-system.css?v=893'),'Index yeni servis oturma tasarımını yüklemeli.');
assert(sw.includes("CACHE_ADI='oy-cache-v893'")&&sw.includes("'./css/design-system.css?v=893'"),'Service Worker yeni tasarım CSS paketini önbelleğe almalı.');
console.log('Servis oturma alternatif tasarım testi başarılı.');
''',encoding='utf-8')
print('alternative bus seating design applied')
