from pathlib import Path


def replace_once(path, old, new):
    p=Path(path)
    s=p.read_text(encoding='utf-8')
    if old not in s:
        raise SystemExit(f'Pattern not found in {path}: {old[:120]}')
    p.write_text(s.replace(old,new,1),encoding='utf-8')

page=Path('js/modules/meeting-schedule.js')
s=page.read_text(encoding='utf-8')

s=s.replace("let root=null,mounted=false,unsubs=[],editingId='',draft=blankDraft();","let root=null,mounted=false,unsubs=[],editingId='',draft=blankDraft(),formMessage='';",1)

old="</label>${edit?`<div class=\"ka-meeting-form-actions\">"
new="</label>${formMessage?`<div class=\"ka-card\" data-meeting-form-message role=\"alert\"><div class=\"ka-card__body\"><strong>⚠️ ${esc(formMessage)}</strong></div></div>`:''}${edit?`<div class=\"ka-meeting-form-actions\">"
if old not in s: raise SystemExit('form message anchor not found')
s=s.replace(old,new,1)
s=s.replace("${editingId?'Vazgeç / Yeni Satır':'+ Yeni Satır'}","${editingId?'Vazgeç / Yeni Satır':'+ Satırı Ekle'}",1)

s=s.replace("function pruneClasses(){const eligible=new Set(eligibleClasses().map(s=>s.id));draft.sinifIdler=draft.sinifIdler.filter(id=>eligible.has(id))}","function clearFormMessage(){formMessage='';root?.querySelector('[data-meeting-form-message]')?.remove()}\nfunction pruneClasses(){const eligible=new Set(eligibleClasses().map(s=>s.id));draft.sinifIdler=draft.sinifIdler.filter(id=>eligible.has(id))}",1)

s=s.replace("function setKademe(k){if(!['ilkokul','ortaokul'].includes(k)||k===draft.kademe)return;draft.kademe=k;draft.zumreSeviyeleri=[];draft.bransId='';draft.bransAdi='';draft.tumSiniflar=false;draft.sinifIdler=[];render()}","function setKademe(k){if(!['ilkokul','ortaokul'].includes(k)||k===draft.kademe)return;clearFormMessage();draft.kademe=k;draft.zumreSeviyeleri=[];draft.bransId='';draft.bransAdi='';draft.tumSiniflar=false;draft.sinifIdler=[];render()}",1)
s=s.replace("function setType(t){if(!['sok','zumre','diger'].includes(t)||t===draft.tur)return;draft.tur=t;if(t!=='zumre'){draft.zumreSeviyeleri=[];draft.bransId='';draft.bransAdi=''}draft.tumSiniflar=false;draft.sinifIdler=[];render()}","function setType(t){if(!['sok','zumre','diger'].includes(t)||t===draft.tur)return;clearFormMessage();draft.tur=t;if(t!=='zumre'){draft.zumreSeviyeleri=[];draft.bransId='';draft.bransAdi=''}draft.tumSiniflar=false;draft.sinifIdler=[];render()}",1)
s=s.replace("function toggleLevel(n){n=Number(n);const s=new Set(draft.zumreSeviyeleri);s.has(n)?s.delete(n):s.add(n);draft.zumreSeviyeleri=[...s].sort((a,b)=>a-b);draft.tumSiniflar=false;pruneClasses();render()}","function toggleLevel(n){clearFormMessage();n=Number(n);const s=new Set(draft.zumreSeviyeleri);s.has(n)?s.delete(n):s.add(n);draft.zumreSeviyeleri=[...s].sort((a,b)=>a-b);draft.tumSiniflar=false;pruneClasses();render()}",1)
s=s.replace("function toggleClass(id){draft.tumSiniflar=false;const s=new Set(draft.sinifIdler);s.has(id)?s.delete(id):s.add(id);draft.sinifIdler=[...s];render()}","function toggleClass(id){clearFormMessage();draft.tumSiniflar=false;const s=new Set(draft.sinifIdler);s.has(id)?s.delete(id):s.add(id);draft.sinifIdler=[...s];render()}",1)

old_save="async function save(){const err=validate();if(err)return global.toast?.(err);const eligible=new Map(eligibleClasses().map(s=>[s.id,s])),br=branches().find(x=>x.id===draft.bransId),old=editingId?records().find(x=>x.id===editingId):null,u=user(),payload={...normalizeDraft(draft),bransAdi:draft.tur==='zumre'&&draft.kademe==='ortaokul'?String(br?.ad||draft.bransAdi||''):'',sinifAdlari:draft.tumSiniflar?[]:draft.sinifIdler.map(id=>className(eligible.get(id))).filter(Boolean),konu:draft.konu.trim(),olusturanUid:old?.olusturanUid||u.uid||'',olusturanAdi:old?.olusturanAdi||currentName(),olusturmaTarihi:old?.olusturmaTarihi||new Date().toISOString(),guncellenmeTarihi:new Date().toISOString()};try{await Service.kaydet(editingId||null,payload);const keep=draft.kademe;editingId='';draft=blankDraft(keep);global.toast?.('Toplantı çizelgesine kaydedildi.');render()}catch(e){global.toast?.(e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Toplantı kaydedilemedi: '+(e?.message||e))}}"
new_save="async function save({keepReady=false}={}){const err=validate();if(err){formMessage=err;render();global.toast?.(err);return false}formMessage='';const eligible=new Map(eligibleClasses().map(s=>[s.id,s])),br=branches().find(x=>x.id===draft.bransId),old=editingId?records().find(x=>x.id===editingId):null,u=user(),payload={...normalizeDraft(draft),bransAdi:draft.tur==='zumre'&&draft.kademe==='ortaokul'?String(br?.ad||draft.bransAdi||''):'',sinifAdlari:draft.tumSiniflar?[]:draft.sinifIdler.map(id=>className(eligible.get(id))).filter(Boolean),konu:draft.konu.trim(),olusturanUid:old?.olusturanUid||u.uid||'',olusturanAdi:old?.olusturanAdi||currentName(),olusturmaTarihi:old?.olusturmaTarihi||new Date().toISOString(),guncellenmeTarihi:new Date().toISOString()};try{await Service.kaydet(editingId||null,payload);const keep=draft.kademe;editingId='';draft=blankDraft(keep);global.toast?.(keepReady?'Satır eklendi. Yeni toplantıyı girebilirsiniz.':'Toplantı çizelgesine kaydedildi.');render();return true}catch(e){const msg=e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Toplantı kaydedilemedi: '+(e?.message||e);formMessage=msg;render();global.toast?.(msg);return false}}"
if old_save not in s: raise SystemExit('save anchor not found')
s=s.replace(old_save,new_save,1)

old_bind="function bind(){if(!root)return;root.querySelectorAll('[data-meeting-kademe]').forEach(b=>b.onclick=()=>setKademe(b.dataset.meetingKademe));root.querySelectorAll('[data-meeting-type]').forEach(b=>b.onclick=()=>setType(b.dataset.meetingType));root.querySelectorAll('[data-meeting-level]').forEach(b=>b.onclick=()=>toggleLevel(b.dataset.meetingLevel));root.querySelector('[data-meeting-branch]')?.addEventListener('change',e=>{draft.bransId=e.target.value;draft.bransAdi=branches().find(x=>x.id===draft.bransId)?.ad||''});root.querySelector('[data-meeting-all-classes]')?.addEventListener('click',()=>{draft.tumSiniflar=!draft.tumSiniflar;if(draft.tumSiniflar)draft.sinifIdler=[];render()});root.querySelectorAll('[data-meeting-class]').forEach(b=>b.onclick=()=>toggleClass(b.dataset.meetingClass));root.querySelector('[data-meeting-date]')?.addEventListener('change',e=>{draft.tarih=e.target.value});root.querySelector('[data-meeting-time]')?.addEventListener('change',e=>{draft.saat=e.target.value});root.querySelector('[data-meeting-topic]')?.addEventListener('input',e=>{draft.konu=e.target.value});root.querySelector('[data-meeting-new]')?.addEventListener('click',()=>{const keep=draft.kademe;editingId='';draft=blankDraft(keep);render()});root.querySelector('[data-meeting-save]')?.addEventListener('click',save);root.querySelectorAll('[data-meeting-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.meetingEdit));root.querySelectorAll('[data-meeting-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.meetingDelete));root.querySelector('[data-meeting-report]')?.addEventListener('click',printReport);global.PermissionService?.apply?.(root)}"
new_bind="function handleClick(e){const el=e.target?.closest?.('button');if(!el||!root?.contains(el))return;if(el.hasAttribute('data-meeting-kademe'))return setKademe(el.dataset.meetingKademe);if(el.hasAttribute('data-meeting-type'))return setType(el.dataset.meetingType);if(el.hasAttribute('data-meeting-level'))return toggleLevel(el.dataset.meetingLevel);if(el.hasAttribute('data-meeting-all-classes')){clearFormMessage();draft.tumSiniflar=!draft.tumSiniflar;if(draft.tumSiniflar)draft.sinifIdler=[];render();return}if(el.hasAttribute('data-meeting-class'))return toggleClass(el.dataset.meetingClass);if(el.hasAttribute('data-meeting-new')){if(editingId){const keep=draft.kademe;editingId='';draft=blankDraft(keep);clearFormMessage();render();return}void save({keepReady:true});return}if(el.hasAttribute('data-meeting-save')){void save();return}if(el.hasAttribute('data-meeting-edit'))return edit(el.dataset.meetingEdit);if(el.hasAttribute('data-meeting-delete')){void remove(el.dataset.meetingDelete);return}if(el.hasAttribute('data-meeting-report'))void printReport()}\nfunction handleChange(e){const el=e.target;if(!el||!root?.contains(el))return;if(el.matches?.('[data-meeting-branch]')){clearFormMessage();draft.bransId=el.value;draft.bransAdi=branches().find(x=>x.id===draft.bransId)?.ad||'';return}if(el.matches?.('[data-meeting-date]')){clearFormMessage();draft.tarih=el.value;return}if(el.matches?.('[data-meeting-time]')){clearFormMessage();draft.saat=el.value}}\nfunction handleInput(e){const el=e.target;if(el?.matches?.('[data-meeting-topic]')){clearFormMessage();draft.konu=el.value}}\nfunction bind(){if(!root)return;root.onclick=handleClick;root.onchange=handleChange;root.oninput=handleInput;global.PermissionService?.apply?.(root)}"
if old_bind not in s: raise SystemExit('bind anchor not found')
s=s.replace(old_bind,new_bind,1)

s=s.replace("async function open(target=document.getElementById('v2ModuleRoot')){if(!target)return false;unmount();root=target;mounted=true;draft=blankDraft();editingId='';subscribe();await prepareLocal();render();return true}","async function open(target=document.getElementById('v2ModuleRoot')){if(!target)return false;unmount();root=target;mounted=true;draft=blankDraft();editingId='';formMessage='';subscribe();await prepareLocal();render();return true}",1)
s=s.replace("function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];root=null;editingId=''}","function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];if(root){root.onclick=null;root.onchange=null;root.oninput=null}root=null;editingId='';formMessage=''}",1)

page.write_text(s,encoding='utf-8')

# Strengthen regression contract for the exact Android/WebView issue.
test=Path('tests/meeting-schedule-v1-smoke.test.js')
t=test.read_text(encoding='utf-8')
t=t.replace("assert(sw.includes(\"const CACHE_ADI='oy-cache-v851';\"),'Toplantı sayfası cache sürümünü yükseltmeli.');","assert(page.includes(\"root.onclick=handleClick\")&&page.includes(\"root.onchange=handleChange\")&&page.includes(\"root.oninput=handleInput\"),'Toplantı formu yeniden çizimlere dayanıklı delegated event kullanmalı.');\nassert(page.includes(\"data-meeting-form-message\")&&page.includes(\"formMessage=err;render()\"),'Doğrulama hatası form içinde görünür olmalı.');\nassert(page.includes(\"'+ Satırı Ekle'\")&&page.includes(\"save({keepReady:true})\"),'Yeni Satır gerçek kayıt ekleme davranışına bağlı olmalı.');\nassert(!page.includes(\"root.querySelector('[data-meeting-new]')?.addEventListener('click',()=>{const keep=draft.kademe;editingId='';draft=blankDraft(keep);render()})\"),'Yeni Satır yalnız form sıfırlamamalı.');\nassert(sw.includes(\"const CACHE_ADI='oy-cache-v852';\"),'Toplantı eylem düzeltmesi cache sürümünü yükseltmeli.');",1)
test.write_text(t,encoding='utf-8')

sw=Path('service-worker.js')
w=sw.read_text(encoding='utf-8')
if "const CACHE_ADI='oy-cache-v851';" not in w: raise SystemExit('cache v851 not found')
sw.write_text(w.replace("const CACHE_ADI='oy-cache-v851';","const CACHE_ADI='oy-cache-v852';",1),encoding='utf-8')
