/* Koruk Asistan — sade Service Worker
   Görev: uygulama kabuğunu önbelleğe almak, uygulama kodunu ve kabuğunu ağdan güncel tutmak ve Firebase Messaging bildirimlerini taşımak.
   Önemli: Sürümlü JS/CSS istekleri query-string'e göre ayrı cache anahtarı kullanır. */
const CACHE_ADI='oy-cache-v1262';
let messaging=null;
try{
  importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');
  importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js');
  firebase.initializeApp({apiKey:"AIzaSyCxLlLCA0Deu7dcQch5e1c4R5ur5FSkc",authDomain:"okul-6e302.firebaseapp.com",projectId:"okul-6e302",storageBucket:"okul-6e302.firebasestorage.app",messagingSenderId:"738103486583",appId:"1:738103486583:web:da91129b1a08f2463efe72"});
  messaging=firebase.messaging();
}catch(e){console.warn('[SW] Firebase Messaging başlatılamadı:',e);}
const FIREBASE_SDK=['https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js','https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore-compat.js','https://www.gstatic.com/firebasejs/10.12.2/firebase-auth-compat.js','https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js','https://www.gstatic.com/firebasejs/10.12.2/firebase-storage-compat.js'];
const ONBELLEGE_ALINACAKLAR=['./','./index.html','./manifest.json','./css/design-system.css?v=1101','./css/design-system.css','./css/dashboard-announcement-media.css?v=923','./js/app-loader.js?v=1051','./js/modules/report-engine.js?v=3','./js/modules/reports.js?v=11','./js/firebase-init.js','./js/core/core.js?v=1038','./js/core/core.js','./js/core/login-security.js?v=885','./js/core/login-security.js','./js/core/read-optimized-sync.js?v=2','./js/core/platform/widget-adapter.js','./js/core/shell-ui.js?v=1068','./js/core/shell-ui.js','./js/modules/school-live-status.js?v=1066','./js/modules/dashboard.js?v=1095','./js/modules/dashboard.js','./js/modules/people.js','./js/modules/people-import.js','./js/modules/people-classic-ui.js','./js/modules/classes-mobile-parity.js','./js/modules/academic.js?v=892','./js/modules/management.js?v=893','./js/modules/committees.js?v=2','./js/modules/communication.js?v=839','./js/modules/transport.js?v=948','./js/modules/food-menu.js?v=1037','./js/modules/documents.js','./js/modules/tools.js','./js/modules/settings.js?v=880','./js/modules/meeting-schedule.js','./js/modules/assistant.js','./js/modules/rubric-settings.js?v=1064','./js/modules/rubric-settings.js','./js/modules/rubric-tools.js','./js/modules/rubric-tools-engine.js','./js/auth.js','./js/app-loader.js?v=1047','./js/app-loader.js','./assets/icon-192.png','./assets/icon-512.png','./assets/icon-180.png'];
const ONBELLEGE_TEKIL=ONBELLEGE_ALINACAKLAR.filter((url,index,list)=>{const path=String(url).split('?')[0];const same=list.filter(item=>String(item).split('?')[0]===path);const preferred=same.find(item=>String(item).includes('?'))||same[0];return url===preferred&&list.findIndex(item=>item===url)===index;});
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_ADI).then(cache=>Promise.all([Promise.allSettled(ONBELLEGE_TEKIL.map(url=>cache.add(url).catch(err=>console.warn('[SW] Önbelleklenemedi:',url,err)))),Promise.allSettled(FIREBASE_SDK.map(async url=>{try{const response=await fetch(url,{mode:'no-cors',cache:'no-store'});await cache.put(url,response)}catch(err){console.warn('[SW] Firebase SDK önbelleklenemedi:',url,err)}}))]));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys(),old=names.filter(n=>n!==CACHE_ADI&&/^oy-cache-v\d+$/.test(n));await Promise.all(old.map(n=>caches.delete(n)));await self.clients.claim()})())});
function firebaseSdkIstegiMi(req){try{const u=new URL(req.url);return u.origin==='https://www.gstatic.com'&&u.pathname.startsWith('/firebasejs/10.12.2/')&&/-compat\.js$/.test(u.pathname)}catch(_){return false}}
async function firebaseSdkCacheFirst(event){const cached=await caches.match(event.request,{ignoreSearch:false});if(cached)return cached;try{const response=await fetch(event.request);if(response){const copy=response.clone();event.waitUntil(caches.open(CACHE_ADI).then(cache=>cache.put(event.request,copy)).catch(()=>{}));}return response}catch(_){return new Response('',{status:503,headers:{'Content-Type':'application/javascript; charset=utf-8'}})}}
function apiIstegiMi(url){return url.includes('firestore.googleapis.com')||url.includes('identitytoolkit.googleapis.com')||url.includes('securetoken.googleapis.com')||url.includes('firebaseinstallations.googleapis.com')||url.includes('fcmregistrations.googleapis.com');}
function kodKaynakMi(req){try{const u=new URL(req.url);return req.destination==='script'||req.destination==='style'||/\\.(?:js|css)$/.test(u.pathname)}catch(_){return false}}
async function kodCacheFirst(event){const req=event.request,cached=await caches.match(req,{ignoreSearch:false});const yenile=fetch(event.request,{cache:'no-store'}).then(response=>{if(response&&response.ok){const copy=response.clone();return caches.open(CACHE_ADI).then(cache=>cache.put(req,copy).catch(()=>{})).then(()=>response)}return response}).catch(()=>cached||new Response('',{status:503}));if(cached){event.waitUntil(yenile);return cached;}return yenile}
async function navigasyonCacheFirst(event){const req=event.request,cached=await caches.match(req,{ignoreSearch:false});try{const response=await fetch(req);if(response&&response.ok){const copy=response.clone();event.waitUntil(caches.open(CACHE_ADI).then(cache=>cache.put(req,copy)).catch(()=>{}));}return response}catch(_){return cached||new Response('',{status:503})}}
self.addEventListener('fetch',event=>{const req=event.request,url=req.url;if(req.method!=='GET')return;if(firebaseSdkIstegiMi(req)){event.respondWith(firebaseSdkCacheFirst(event));return}if(apiIstegiMi(url))return;if(kodKaynakMi(req)){event.respondWith(kodCacheFirst(event));return}if(req.mode==='navigate'){event.respondWith(navigasyonCacheFirst(event));return}event.respondWith((async()=>{const cached=await caches.match(req,{ignoreSearch:false});try{const response=await fetch(req);if(response&&response.ok){const copy=response.clone();event.waitUntil(caches.open(CACHE_ADI).then(cache=>cache.put(req,copy)).catch(()=>{}));}return response}catch(_){return cached||new Response('',{status:503})}})())});
if(typeof firebase!=='undefined'&&firebase.messaging){self.addEventListener('push',event=>{try{event.waitUntil((async()=>{const data=event.data?.json?.()||{};const n=data.notification||data.data||{};await self.registration.showNotification(n.title||'Koruk Asistan',{body:n.body||'Yeni bildirim',icon:'./assets/icon-192.png',badge:'./assets/icon-192.png',data:n.data||{}})})())}catch(e){console.warn('[SW] push:',e)}})}
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{const c=list.find(x=>x.url&&x.url.includes(location.origin));return c?c.focus():clients.openWindow('./')}))});
