const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('js/modules/settings.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const firebase=fs.readFileSync('js/firebase-init.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(src);
assert(src.includes("['admin-info','İdari Bilgiler ve Şifreler'"),'İdari bilgiler native Settings menüsünde değil.');
assert(src.includes("active==='admin-info'?adminInfoPage()"),'İdari bilgiler native render akışına bağlı değil.');
assert(src.includes("active==='holiday'?holidayPage()"),'Tatil Modu native Settings sayfası değil.');
assert(src.includes('data-admin-subscription-add')&&src.includes('data-admin-note-add'),'Esnek abonelik/not ekleme eksik.');
assert(src.includes("['Ortak','İlkokul','Ortaokul','Diğer']"),'İlkokul/Ortaokul resmî bilgi ayrımı eksik.');
assert(!src.includes('<details class="ka-admin-section'),'Akordiyon tekrar eklenmiş.');
assert(css.includes('Native Settings: İdari Bilgiler ve Şifreler'),'İdari ekran stilleri design-system.css içinde değil.');
assert(!firebase.includes('settings-admin-extension.js'),'firebase-init extension loader içermemeli.');
assert(!sw.includes('settings-admin-extension.js'),'Service worker extension cache içermemeli.');
assert(!fs.existsSync('js/core/settings-admin-extension.js'),'Extension dosyası tamamen silinmeli.');
console.log('Native Settings idari bilgiler + tatil entegrasyonu başarılı.');
