const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('js/modules/settings.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const firebase=fs.readFileSync('js/firebase-init.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(src);
assert(!src.includes("['admin-info','İdari Bilgiler ve Şifreler'"),'İdari bilgiler ayrı Settings menüsü olarak geri dönmemeli.');
assert(src.includes("if(tab==='admin-info')return false")&&!src.includes("active==='admin-info'?"),'Eski admin-info route tamamen emekli edilmeli.');
assert(src.includes("adminPanel=adminInfoAllowed()?adminInfoPanel():''")&&src.includes('data-admin-info-panel'),'İdari bilgiler Okul Bilgileri sayfasının yetkili bölümünde olmalı.');
assert(src.includes('id="schoolAddress"')&&src.includes("adres:String(kaynak.adres||kaynak.okulAdresi||'').trim()"),'Okul adresi merkezi Okul Bilgileri modeline yazılmalı.');
assert(src.includes("['social','Sosyal Medya','Sosyal medya ve web adresleri']")&&src.includes("active==='social'?socialSettings()")&&src.includes('sosyalKaydet(sosyalLinkler)'),'Sosyal medya ayrı Settings sayfasına taşınmalı.');
const schoolBlock=src.slice(src.indexOf('function school(){'),src.indexOf('function bindSchool(out)'));
assert(!schoolBlock.includes('settingsSocialList')&&!schoolBlock.includes('data-social-add'),'Okul Bilgileri temel formunda sosyal medya editörü kalmamalı.');
assert(src.includes('data-admin-subscription-add')&&src.includes('data-admin-note-add'),'Esnek abonelik/not ekleme korunmalı.');
assert(src.includes('IdariBilgilerRepository')&&src.includes('IdariBilgilerService'),'İdari bilgiler Repository/Service katmanında kalmalı.');
assert(src.includes("device().set('idariBilgiler'"),'İdari bilgiler DeviceData üzerinden yazılmalı.');
assert(src.includes("SyncEngine.register(t,c)")&&src.includes("idariBilgiler:COL.idariBilgiler"),'İdari bilgiler SyncEngine kaydı korunmalı.');
assert(!src.includes('db.collection'),'SettingsModule doğrudan Firestore kullanmamalı.');
assert(src.includes("['Ortak','İlkokul','Ortaokul','Diğer']"),'İlkokul/Ortaokul resmî bilgi ayrımı korunmalı.');
assert(!src.includes('<details class="ka-admin-section'),'İdari bilgiler akordiyona dönmemeli.');
assert(css.includes('Native Settings: İdari Bilgiler ve Şifreler'),'İdari ekran stilleri merkezi design-system.css içinde kalmalı.');
assert(!firebase.includes('settings-admin-extension.js'),'firebase-init extension loader içermemeli.');
assert(!sw.includes('settings-admin-extension.js'),'Service worker extension cache içermemeli.');
assert(!fs.existsSync('js/core/settings-admin-extension.js'),'Extension dosyası geri gelmemeli.');
console.log('Okul Bilgileri + idari bilgiler + sosyal medya Settings sahipliği başarılı.');
