const fs=require('fs');
const assert=require('assert');
const communication=fs.readFileSync('js/modules/communication.js','utf8');
const documents=fs.readFileSync('js/modules/documents.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
new Function(communication);
new Function(documents);
const announcementBlock=communication.slice(communication.indexOf('function announcements(){'),communication.indexOf('\nfunction conversationTitle(k)',communication.indexOf('function announcements(){')));
for(const token of ['ka-announcement-list','ka-announcement-card','ka-announcement-status','ka-announcement-gallery','ka-announcement-details','ka-announcement-card__actions','data-announcement-read','data-announcement-edit','data-announcement-delete'])assert(announcementBlock.includes(token),`Duyurular yeni görünüm/işlem sözleşmesi eksik: ${token}`);
assert(!announcementBlock.includes('style='),'Duyuru kartları inline style üretmemeli.');
const actionBlock=communication.slice(communication.indexOf('function communicationActionBar(){'),communication.indexOf('\nfunction openAnnouncementModal',communication.indexOf('function communicationActionBar(){')));
for(const token of ['ka-announcement-toolbar','ka-announcement-segmented','data-announcement-filter="active"','data-announcement-filter="archive"','data-announcement-new'])assert(actionBlock.includes(token),`Duyuru toolbar sözleşmesi eksik: ${token}`);
const modalBlock=communication.slice(communication.indexOf('function openAnnouncementModal(item={}){'),communication.indexOf('\nfunction openPollModal(){',communication.indexOf('function openAnnouncementModal(item={}){')));
for(const token of ['ka-announcement-modal','ka-announcement-upload','name="resimler"','multiple','name="arsivlendi"','name="keepImage"','DuyurularService?.resimYukle','DuyurularService?.duyuruKaydet'])assert(modalBlock.includes(token),`Duyuru modal sözleşmesi eksik: ${token}`);
assert(!modalBlock.includes('style='),'Duyuru modalı inline style üretmemeli.');
for(const token of ['.ka-announcement-card{','.ka-announcement-toolbar{','.ka-announcement-modal{','[data-theme="dark"]'])assert(css.includes(token),`Merkezi design-system duyuru stili eksik: ${token}`);
const docShell=documents.slice(documents.indexOf('function shell(){'),documents.indexOf('\nfunction renderToolbar()',documents.indexOf('function shell(){')));
assert(!docShell.includes('data-document-form="teblig"'),'Dokümanlar ana sayfasında Tebliğ-Tebellüğ hızlı butonu kalmamalı.');
assert(documents.includes('data-teblig-field="tarihIso"'),'Tebliğ-Tebellüğ canonical form motoru menü rotası için korunmalı.');
assert(!communication.includes('.collection('),'Communication doğrudan Firestore kullanmamalı.');
console.log('Duyurular canonical redesign + Dokümanlar Tebliğ hızlı giriş kaldırma sözleşmesi başarılı.');
