from pathlib import Path
p=Path('js/dokuman-okuyucu.js'); s=p.read_text(encoding='utf-8')
def rep(a,b,label):
    global s
    c=s.count(a)
    if c!=1: raise SystemExit(f'{label}: expected 1 match, got {c}')
    s=s.replace(a,b,1)
rep("let A=null,pdf=null,wb=null,wordZoom=1,pdfZoom=1;","let A=null,pdf=null,wb=null,wordZoom=1,pdfZoom=1,excelZoom=1;",'excel zoom state')
rep(".dv3excel{background:#fff;color:#111;min-height:100%}.dv3tabs{position:sticky;top:0;z-index:3;display:flex;overflow-x:auto;gap:4px;padding:7px;background:#20262d}.dv3tabs button{white-space:nowrap;padding:7px 10px}.dv3sheet{overflow:auto}.dv3sheet table{border-collapse:collapse}.dv3sheet td,.dv3sheet th{border:1px solid #d5d8dc;padding:4px 6px;white-space:nowrap}",".dv3body.dv3excelbody{overflow:hidden;display:flex;flex-direction:column;min-width:0;background:#eef1f4}.dv3excel{display:flex;flex:1 1 auto;min-height:0;flex-direction:column;background:#fff;color:#111}.dv3tabs{flex:0 0 auto;display:flex;overflow-x:auto;gap:4px;padding:7px;background:#20262d;border-bottom:1px solid #46505b}.dv3tabs button{white-space:nowrap;padding:7px 10px}.dv3exceltools{flex:0 0 auto;display:flex;align-items:center;justify-content:center;gap:6px;padding:7px;background:#29313a;border-bottom:1px solid #46505b}.dv3sheetviewport{flex:1 1 auto;min-height:0;overflow:auto;max-width:100%;padding:10px;box-sizing:border-box;overscroll-behavior:contain;touch-action:pan-x pan-y;background:#eef1f4}.dv3sheetscene{position:relative;margin:0}.dv3sheetstage{position:absolute;left:0;top:0;transform-origin:top left;display:block}.dv3sheet{display:inline-block;background:#fff;box-shadow:0 3px 14px #0003}.dv3sheet table{border-collapse:collapse}.dv3sheet td,.dv3sheet th{border:1px solid #d5d8dc;padding:4px 6px;white-space:nowrap}",'excel css')
old="function excelShell(names,fn){A.body.innerHTML='<div class=\"dv3excel\"><div class=\"dv3tabs\" id=\"dv3tabs\"></div><div class=\"dv3sheet\" id=\"dv3sheet\"></div></div>';const t=A.body.querySelector('#dv3tabs');names.forEach((n,i)=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>fn(i);t.appendChild(b)});if(names.length)fn(0);}"
new="function excelOlcekUygula(){if(!A)return;const st=A.body.querySelector('#dv3sheetStage'),scene=A.body.querySelector('#dv3sheetScene'),sheet=A.body.querySelector('#dv3sheet');if(!st||!scene||!sheet)return;const w=Math.max(1,Number(st.dataset.naturalWidth)||sheet.scrollWidth||sheet.offsetWidth||1),h=Math.max(1,Number(st.dataset.naturalHeight)||sheet.scrollHeight||sheet.offsetHeight||1);st.style.transform=`scale(${excelZoom})`;scene.style.width=Math.ceil(w*excelZoom)+'px';scene.style.height=Math.ceil(h*excelZoom)+'px';const l=A.body.querySelector('#dv3excelZoomLabel');if(l)l.textContent=Math.round(excelZoom*100)+'%';}\nfunction excelOlcuYenile(){if(!A)return;const st=A.body.querySelector('#dv3sheetStage'),sheet=A.body.querySelector('#dv3sheet');if(!st||!sheet)return;st.style.transform='none';st.dataset.naturalWidth=String(Math.ceil(Math.max(1,sheet.scrollWidth||sheet.offsetWidth||1)));st.dataset.naturalHeight=String(Math.ceil(Math.max(1,sheet.scrollHeight||sheet.offsetHeight||1)));excelOlcekUygula();}\nfunction excelZoomUygula(z){excelZoom=Math.max(0.2,Math.min(3,z));excelOlcekUygula();}\nfunction excelSigdir(){if(!A)return;const wrap=A.body.querySelector('#dv3sheetViewport'),st=A.body.querySelector('#dv3sheetStage'),sheet=A.body.querySelector('#dv3sheet');if(!wrap||!st||!sheet)return;st.style.transform='none';const w=Math.max(1,sheet.scrollWidth||sheet.offsetWidth||1),h=Math.max(1,sheet.scrollHeight||sheet.offsetHeight||1);st.dataset.naturalWidth=String(Math.ceil(w));st.dataset.naturalHeight=String(Math.ceil(h));const uygun=Math.max(1,wrap.clientWidth-20);excelZoom=Math.max(0.15,Math.min(1,uygun/w));excelOlcekUygula();wrap.scrollTo({left:0,top:0,behavior:'auto'});}\nfunction excelShell(names,fn){excelZoom=1;A.body.classList.add('dv3excelbody');A.body.innerHTML='<div class=\"dv3excel\"><div class=\"dv3tabs\" id=\"dv3tabs\"></div><div class=\"dv3exceltools\"><button class=\"dv3btn\" id=\"dv3excelMinus\">−</button><button class=\"dv3btn\" id=\"dv3excelFit\">Sığdır</button><span id=\"dv3excelZoomLabel\" style=\"min-width:48px;text-align:center;font-weight:700;color:#fff\">100%</span><button class=\"dv3btn\" id=\"dv3excelPlus\">+</button></div><div class=\"dv3sheetviewport\" id=\"dv3sheetViewport\"><div class=\"dv3sheetscene\" id=\"dv3sheetScene\"><div class=\"dv3sheetstage\" id=\"dv3sheetStage\"><div class=\"dv3sheet\" id=\"dv3sheet\"></div></div></div></div></div>';const t=A.body.querySelector('#dv3tabs');const ac=i=>{fn(i);requestAnimationFrame(()=>requestAnimationFrame(excelSigdir));};names.forEach((n,i)=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>ac(i);t.appendChild(b)});A.body.querySelector('#dv3excelMinus').onclick=()=>excelZoomUygula(excelZoom-0.15);A.body.querySelector('#dv3excelPlus').onclick=()=>excelZoomUygula(excelZoom+0.15);A.body.querySelector('#dv3excelFit').onclick=excelSigdir;if(names.length)ac(0);}"
rep(old,new,'excel shell')
p.write_text(s,encoding='utf-8')

t=Path('tests/document-viewer-smoke.test.js'); ts=t.read_text(encoding='utf-8'); marker="console.log('Belge görüntüleyici smoke testleri başarılı.');"; extra="""
assert(src.includes('excelZoomUygula'), 'Excel görüntüleyicide yakınlaştırma/uzaklaştırma bulunmalı.');
assert(src.includes('excelSigdir'), 'Excel görüntüleyicide Sığdır bulunmalı.');
assert(src.includes('id=\"dv3excelZoomLabel\"'), 'Excel zoom yüzdesi gösterilmeli.');
assert(src.includes('.dv3sheetviewport{flex:1 1 auto;min-height:0;overflow:auto'), 'Excel kaydırma yalnız tablo viewportunda olmalı.');
assert(src.includes('st.style.transform=`scale(${excelZoom})`'), 'Excel zoom yalnız çalışma sayfasına uygulanmalı.');
assert(src.includes('const uygun=Math.max(1,wrap.clientWidth-20)'), 'Excel Sığdır gerçek viewport genişliğini kullanmalı.');
"""
if extra.strip() not in ts: ts=ts.replace(marker,extra+'\n'+marker)
t.write_text(ts,encoding='utf-8')

sw=Path('service-worker.js'); x=sw.read_text(encoding='utf-8')
if "const CACHE_ADI = 'oy-cache-v434';" in x:
    x=x.replace("const CACHE_ADI = 'oy-cache-v434';","const CACHE_ADI = 'oy-cache-v435';",1)
elif "const CACHE_ADI = 'oy-cache-v435';" not in x:
    raise SystemExit('service worker cache version unexpected')
sw.write_text(x,encoding='utf-8')
