const fs=require('fs');
const assert=require('assert');
const seating=fs.readFileSync('js/modules/class-seating.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const transport=fs.readFileSync('js/modules/transport.js','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(seating);
assert(seating.includes("const used=assigned(),current=seat.dataset.studentId||'',all=students()"),'Öğrenci seçici tüm sınıf listesini açmalı.');
assert(seating.includes("placed?'Başka sırada':'Yerleşmedi'")&&seating.includes("is-assigned':'is-unassigned'"),'Yerleşen ve yerleşmeyen öğrenciler seçicide ayrı durumla gösterilmeli.');
assert(seating.includes('const other=seatForStudent(student.id,seat)')&&seating.includes('if(other)clearSeat(other,{refresh:false})'),'Başka sıradaki öğrenci yeni sıraya taşınırken eski yeri boşaltılmalı.');
assert(seating.includes("seat.addEventListener('keydown'")&&seating.includes('if(seat)chooseStudent(seat)'),'Sıra isim alanı dokunma ve klavye ile öğrenci seçiciyi açmalı.');
assert(seating.includes("clone.style.backgroundImage='none'")&&seating.includes("clone.classList.add('ka-class-seating-print-canvas')"),'PDF klonu kareli arka planı taşımamalı.');
assert(seating.includes("baslikGoster:false")&&seating.includes('kenarBosluk:3')&&seating.includes('scale=Math.min(1,printable.w*pxPerMm/p.w,stageH*pxPerMm/p.h)*.985'),'PDF şablonu A4 kullanılabilir alana ölçeklenmeli.');
for(const marker of ['.ka-class-seating-page','.ka-class-seating-workspace','.ka-class-seating-roster','.ka-class-seating-student.is-assigned','.ka-class-seating-student.is-unassigned','[data-theme="dark"] .ka-class-seating-page','.ka-class-seating-print-canvas'])assert(design.includes(marker),`Merkezi sınıf oturma tasarım stili eksik: ${marker}`);
assert(transport.includes("class-seating.js?v=883"),'Sınıf oturma motoru yeni sürümle yüklenmeli.');
assert(loader.includes("js/modules/transport.js?v=883"),'Transport modülü cache-bust ile yüklenmeli.');
assert(sw.includes("CACHE_ADI='oy-cache-v883'")&&sw.includes("class-seating.js?v=883")&&sw.includes("transport.js?v=883"),'Service Worker yeni sınıf oturma paketini precache etmeli.');
assert(!/\bdb\s*\.\s*collection\s*\(/.test(seating)&&!seating.includes('firebase.firestore('),'Sınıf oturma UI doğrudan Firestore kullanmamalı.');
console.log('Sınıf oturma planı yeniden tasarım ve A4 çıktı testleri başarılı.');
