const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('js/modules/management.js','utf8');

assert(src.includes('DeviceData/IndexedDB -> AppStore'),'Management local-first veri akışı korunmalı.');
assert(!src.includes('db.collection('),'Management doğrudan Firestore kullanmamalı.');
for(const api of ['yeriEkle','yeriGuncelle','yeriSil','tatilEkle','atamaKaydet','amirKaydet','exceliUygula','otomatikDagitimUygula','defterDolduToggle']) assert(src.includes(api),`Nöbet V2 servis API eksik: ${api}`);
for(const text of ['Nöbet Programı','Nöbet Yerleri','Excel’den İçe Aktar','Nöbet Listesi','Otomatik Nöbet Dağıtımı','Bugünün Nöbetçileri','Resmi Tatiller','+ Tatil Ekle','‹ Önceki Ay','Sonraki Ay ›','Nöbetçi Amir','Öğretmen Nöbet Çizelgesi','Çizelgeyi görüntüle ve yazdır']) assert(src.includes(text),`Canonical Nöbet ekranı öğesi eksik: ${text}`);
for(const hook of ['data-duty-cell','data-duty-chief','data-duty-book','data-duty-holiday-add','data-duty-auto','data-duty-month','data-duty-places','data-duty-excel','data-duty-place-new','data-duty-place-edit','data-duty-place-delete']) assert(src.includes(hook),`Nöbet etkileşim sözleşmesi eksik: ${hook}`);
assert(src.includes('class="ka-duty-grid"'),'Aylık nöbet çizelgesi tablo anatomisi korunmalı.');
assert(!src.includes('function dutyMobile('),'Mobil gün-kartı rendererı emekliye ayrılmalı.');
assert(!src.includes('${dutyMobile()}${dutyGrid()}'),'Nöbet Programı mobilde ayrı gün kartı rendererı kullanmamalı.');
assert(src.includes('${dutyGrid()}'),'Aylık Nöbet Programı tüm ekranlarda canonical tablo rendererı üzerinden üretilmeli.');
for(const marker of ['ka-duty-action-grid','ka-duty-report-card','ka-duty-grid__day','tabindex=\"0\"','Gün']) assert(src.includes(marker),`Yeni Nöbet tablo/tasarım sözleşmesi eksik: ${marker}`);
assert(src.includes('ka-duty-report-banner')&&src.includes('ka-duty-report-table')&&src.includes('ka-duty-report-weekend')&&src.includes('ka-duty-report-holiday')&&src.includes('ka-duty-report-phones')&&src.includes('ka-duty-report-tasks')&&src.includes('ka-duty-report-footer')&&src.includes('ka-duty-report-signature'),'Tam sayfa nöbet raporu anatomisi korunmalı.');
assert(src.includes('compact:true')&&src.includes('fontSize:7')&&src.includes('kenarBosluk:5'),'Nöbet raporu tüm ayı tek A4 sayfaya sığdıran ayarları kullanmalı.');
assert(!src.includes('MutationObserver'),'Nöbet mobil görünümü sonradan DOM yamasıyla üretilmemeli.');
assert(src.includes("device().set('nobetRotasyon',COL.nobetRotasyon"),'Rotasyon kaydı DeviceData üzerinden kalmalı.');
assert(src.includes("PermissionService?.can?.('management.duty.edit','edit')"),'Nöbet yazma işlemleri merkezi management.duty.edit yetkisine bağlı kalmalı.');
assert(src.includes('DutyBookService.toggle(atama,deger)'),'Management nöbet defteri ortak çekirdek servisine delege edilmeli.');
console.log('Classic Duty V2 görünüm + local-first + yönetim araçları sözleşmesi başarılı.');