const fs=require('fs');
const assert=require('assert');
const v4=fs.readFileSync('js/dashboard-mobile-v4.js','utf8');
const polish=fs.readFileSync('js/dashboard-mobile-v4-polish.js','utf8');
const hotfix=fs.readFileSync('js/dashboard-mobile-v4-hotfix.js','utf8');
const stateV3=fs.readFileSync('js/dashboard-mobile-state-v3.js','utf8');
const counts=fs.readFileSync('js/dashboard-card-count-fix.js','utf8');
const role=fs.readFileSync('js/role-ui-hardening.js','utf8');
const cleanup=fs.readFileSync('js/dashboard-today-cleanup.js','utf8');
const docsRepo=fs.readFileSync('js/core/repositories/dokumanlar.repository.js','utf8');
const loader=fs.readFileSync('js/ui-stability-fixes.js','utf8');
const webInit=fs.readFileSync('js/dashboard-v2-init.js','utf8');
const webSidebar=fs.readFileSync('js/web-sidebar-v2.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');

assert(v4.includes('Mobil Rol Bazlı Ana Sayfa v6'),'Rol bazlı mobil dashboard v6 bulunmalı');
assert(v4.includes("root.classList.remove('db4','db5')")&&v4.includes("root.classList.add('db6')"),'Eski mobil dashboard sınıfları v6 ile değiştirilmelidir');
assert(v4.includes('db6-weather')&&v4.includes('heroHavaSatir'),'Hava durumu v6 içinde korunmalı');
assert(v4.includes('db6-clock')&&v4.includes('zilWidget'),'Zil sayacı v6 içinde korunmalı');
assert(v4.includes('adminSections')&&v4.includes('teacherSections'),'Rol bazlı ana sayfa akışları bulunmalı');
assert(v4.includes('Haftanın Nöbet Programı')&&v4.includes('Yaklaşan Yazılı Sınavlar'),'Admin operasyon kartları bulunmalı');
assert(v4.includes('Bugünkü Derslerim')&&v4.includes('yillikPlanHaftaAc'),'Öğretmen ders-yıllık plan bağlantısı bulunmalı');
assert(v4.includes('Nöbet defterini doldurdum'),'Öğretmen nöbet defteri kontrolü bulunmalı');
assert(v4.includes('Hızlı İşlemler')&&v4.includes('Takvim'),'Öğretmen hızlı işlemler ve takvim alanı bulunmalı');
assert(v4.includes('grid-template-columns:repeat(4,1fr)'),'Hızlı işlemler mobilde dört eşit karta sahip olmalı');
assert(v4.includes('@media(prefers-reduced-motion:reduce)'),'Hareket azaltma tercihi desteklenmeli');

assert(polish.includes('dashboardV41Duzenle')&&polish.includes('INFO_CARDS'));
assert(hotfix.includes("PREF_COL='oy_kullaniciTercihleri'"));
assert(hotfix.includes("DEFAULT_INFO=['personel','ogrenci','sinif','servis','hatirlatici','not']"));
assert(stateV3.includes('dashboardMobilBilgiKartlariV3')&&stateV3.includes('dashboardMobilHizliIslemlerV3'),'Mobil v3 kalıcı tercih alanları bulunmalı');
assert(counts.includes("g('COL')?.servisler||'oy_servisler'"));
assert(counts.includes('onSnapshot'));
assert(counts.includes("gorebilir');return typeof f==='function'?!!f('tasima')"),'Servis kartı Taşıma yetkisini kullanmalı');
assert(counts.includes('dbx-female')&&counts.includes('dbx-male'));
assert(counts.includes('#heroSosyalMedya>*>span:last-child'),'Sosyal bağlantı etiket kontrastı sabitlenmeli');
assert(role.includes("ADMIN_ONLY_SETTINGS=['Optik Puan Referans Ayarları','Hatırlatma Sistemi','Depolama Sınırları']"));
assert(role.includes("READONLY_SETTINGS=['Ders Saatleri','Ders Listesi','Branş Listesi']"));
assert(role.includes('Teslim Etmem Gerekenler')&&role.includes('hatirlatmalariTopla'));
assert(role.includes("QUICK_PREF='dashboardHizliIslemler'")&&role.includes('Hızlı İşlemleri Düzenle'));
assert(!role.includes('setInterval('),'Rol UI global interval kullanmamalı');
assert(!role.includes('new MutationObserver'),'Rol UI global DOM observer kullanmamalı');
assert(!hotfix.includes('setInterval('),'Dashboard tercih katmanı polling yapmamalı');
assert(counts.includes("gridObserver.observe(grid,{childList:true})"),'Sayaç observer yalnız bilgi kartı gridine sınırlandırılmalı');
assert(!counts.includes('observe(document.documentElement'),'Sayaç tüm DOM’u izlememeli');
assert(cleanup.includes('Bugünkü Nöbet')&&cleanup.includes('btn.remove()'),'Bugünkü Nöbet kartı Bugün alanından kaldırılmalı');
assert(cleanup.includes("grid.style.gridTemplateColumns='repeat(2,minmax(0,1fr))'"),'Bugün alanı kalan iki kart için düzenlenmeli');
assert(docsRepo.includes("where('gorunurluk','==','herkes')"),'Normal kullanıcı herkese açık dökümanları sorgulamalı');
assert(docsRepo.includes('auth.currentUser')&&docsRepo.includes('auth.onAuthStateChanged'),'Döküman dinleyicisi profil/auth yükleme yarışına dayanıklı olmalı');
assert(!docsRepo.includes('if(!ben || ben.admin === true)'),'Profil hazır değilken kullanıcı admin varsayılmamalı');
assert(loader.includes("matchMedia('(max-width: 1023px)')"),'Mobil dashboard yükleyicisi ekran genişliğiyle sınırlandırılmalı');
assert(loader.indexOf("if(mobilDashboard)")<loader.indexOf("dashboard-mobile-v4.js"),'Mobil dashboard yalnız mobil koşulunda yüklenmeli');
assert(loader.includes('dashboard-mobile-state-v3.js'),'Mobil v3 durum yöneticisi yüklenmeli');
assert(webInit.includes("matchMedia('(min-width: 1024px)')")||/function\s+isWeb\s*\(\)\s*\{\s*return\s+window\.innerWidth\s*>=\s*1024/.test(webInit),'Web dashboard yalnız masaüstünde çalışmalı');
assert(webSidebar.includes('_navDuzeniTumGruplarGetir'),'Web sidebar alt navigasyonun aynı veri modelini kullanmalı');
assert(loader.includes('role-ui-hardening.js'));
assert(sw.includes("'./js/role-ui-hardening.js'"));
assert(sw.includes('oy-cache-v449'));
console.log('dashboard-mobile-v4-smoke: OK');
