const fs=require('fs');
const assert=require('assert');
const v4=fs.readFileSync('js/dashboard-mobile-v4.js','utf8');
const polish=fs.readFileSync('js/dashboard-mobile-v4-polish.js','utf8');
const hotfix=fs.readFileSync('js/dashboard-mobile-v4-hotfix.js','utf8');
const counts=fs.readFileSync('js/dashboard-card-count-fix.js','utf8');
const role=fs.readFileSync('js/role-ui-hardening.js','utf8');
const cleanup=fs.readFileSync('js/dashboard-today-cleanup.js','utf8');
const docsRepo=fs.readFileSync('js/core/repositories/dokumanlar.repository.js','utf8');
const loader=fs.readFileSync('js/ui-stability-fixes.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
assert(v4.includes("p.classList.remove('dmv2','dmv3')"));assert(v4.includes("p.classList.add('db4')"));assert(v4.includes('db4-weather')&&v4.includes('heroHavaSatir'));assert(v4.includes('db4-bell')&&v4.includes('zilWidget'));assert(polish.includes('dashboardV41Duzenle')&&polish.includes('INFO_CARDS'));
assert(hotfix.includes("PREF_COL='oy_kullaniciTercihleri'"));assert(hotfix.includes("DEFAULT_INFO=['personel','ogrenci','sinif','servis','hatirlatici','not']"));
assert(counts.includes("g('COL')?.servisler||'oy_servisler'"));assert(counts.includes('onSnapshot'));assert(counts.includes("gorebilir');return typeof f==='function'?!!f('tasima')"),'Servis kartı Taşıma yetkisini kullanmalı');assert(counts.includes('dbx-female')&&counts.includes('dbx-male'));assert(counts.includes('#heroSosyalMedya>*>span:last-child'),'Sosyal bağlantı etiket kontrastı sabitlenmeli');
assert(role.includes("ADMIN_ONLY_SETTINGS=['Optik Puan Referans Ayarları','Hatırlatma Sistemi','Depolama Sınırları']"));assert(role.includes("READONLY_SETTINGS=['Ders Saatleri','Ders Listesi','Branş Listesi']"));assert(role.includes('Teslim Etmem Gerekenler')&&role.includes('hatirlatmalariTopla'));assert(role.includes("QUICK_PREF='dashboardHizliIslemler'")&&role.includes('Hızlı İşlemleri Düzenle'));assert(role.includes('normalizeQuick')&&role.includes('out.length<4'),'Hızlı işlemler dört karta tamamlanmalı');
assert(!role.includes('setInterval('),'Rol UI global interval kullanmamalı');assert(!role.includes('new MutationObserver'),'Rol UI global DOM observer kullanmamalı');assert(!hotfix.includes('setInterval('),'Dashboard tercih katmanı polling yapmamalı');assert(counts.includes("gridObserver.observe(grid,{childList:true})"),'Sayaç observer yalnız bilgi kartı gridine sınırlandırılmalı');assert(!counts.includes('observe(document.documentElement'),'Sayaç tüm DOM’u izlememeli');
assert(cleanup.includes('Bugünkü Nöbet')&&cleanup.includes('btn.remove()'),'Bugünkü Nöbet kartı Bugün alanından kaldırılmalı');
assert(cleanup.includes("grid.style.gridTemplateColumns='repeat(2,minmax(0,1fr))'"),'Bugün alanı kalan iki kart için düzenlenmeli');
assert(docsRepo.includes("where('gorunurluk','==','herkes')"),'Normal kullanıcı herkese açık dökümanları sorgulamalı');
assert(docsRepo.includes('auth.currentUser')&&docsRepo.includes('auth.onAuthStateChanged'),'Döküman dinleyicisi profil/auth yükleme yarışına dayanıklı olmalı');
assert(!docsRepo.includes('if(!ben || ben.admin === true)'),'Profil hazır değilken kullanıcı admin varsayılmamalı');
assert(loader.includes('role-ui-hardening.js'));assert(loader.includes('dashboard-today-cleanup.js'));assert(sw.includes("'./js/role-ui-hardening.js'"));assert(sw.includes("'./js/dashboard-today-cleanup.js'"));assert(sw.includes('oy-cache-v446'));assert(v4.includes('@media(prefers-reduced-motion:reduce)'));
console.log('dashboard-mobile-v4-smoke: OK');
