const fs=require('fs');
const assert=require('assert');
const {cacheVersion,assetVersion}=require('./helpers/version-contract');
const dashboard=fs.readFileSync('js/modules/dashboard.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(dashboard);
assert(dashboard.includes("ov.className='ka-modal-backdrop'")&&dashboard.includes("ov.classList.add('ka-reminder-backdrop')")&&dashboard.includes('ka-reminder-modal'),'Öğretmen açılış hatırlatması merkezi modal yüzeyinde özel reminder tasarımı kullanmalı.');
for(const marker of ['ka-reminder-head','ka-reminder-summary','ka-reminder-list','ka-reminder-item','ka-reminder-footer','reminderSummary(items)','REMINDER_KIND_META']) assert(dashboard.includes(marker),`Hatırlatma yeni görünüm sözleşmesi eksik: ${marker}`);
assert(dashboard.includes('role="dialog"')&&dashboard.includes('aria-modal="true"')&&dashboard.includes('aria-labelledby="dashboardReminderTitle"'),'Hatırlatma penceresi erişilebilir dialog semantiğini korumalı.');
assert(dashboard.includes("if(e.key==='Escape')close()")&&dashboard.includes('if(e.target===ov)close()'),'Hatırlatma penceresi Escape ve arka plan dokunuşuyla kapatılabilmeli.');
assert(dashboard.includes("KorukLocalFirst.meta(u,'reminderSnoozeUntil'"),'Erteleme IndexedDB meta üzerinden local-first kalmalı.');
assert(!dashboard.includes('db.collection(')&&!dashboard.includes('onSnapshot'),'Hatırlatma görünümü doğrudan Firestore kullanmamalı.');
for(const marker of ['/* TEACHER STARTUP REMINDERS — CANONICAL */','.ka-reminder-modal','.ka-reminder-item.is-overdue','.ka-reminder-footer','[data-theme="dark"] .ka-reminder-modal','@media(max-width:767px)']) assert(design.includes(marker),`Merkezi Design System reminder stili eksik: ${marker}`);
assert(assetVersion(index,'css/design-system.css')>=872&&assetVersion(index,'js/app-loader.js')>=872,'Yeni reminder tasarımı cache-busted shell üzerinden yüklenmeli.');
assert(assetVersion(loader,'js/modules/dashboard.js')>=872,'Dashboard yeni reminder sürümüyle lazy-load edilmeli.');
assert(cacheVersion(sw)>=872&&assetVersion(sw,'css/design-system.css')>=872&&assetVersion(sw,'js/app-loader.js')>=872&&assetVersion(sw,'js/modules/dashboard.js')>=872,'Service Worker reminder v872 varlıklarını önbelleğe almalı.');
console.log('Öğretmen açılış hatırlatma penceresi redesign sözleşmesi başarılı.');
