const fs=require('fs');
const assert=require('assert');
const {execFileSync}=require('child_process');
const js=fs.readFileSync('js/dashboard-mobile-state-v3.js','utf8');
const ui=fs.readFileSync('js/ui-stability-fixes.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
execFileSync(process.execPath,['--check','js/dashboard-mobile-state-v3.js']);
assert(js.includes("dashboardMobilBilgiKartlariV3"),'Bilgi kartları için yeni Firestore alanı bulunmalı.');
assert(js.includes("dashboardMobilHizliIslemlerV3"),'Hızlı işlemler için yeni Firestore alanı bulunmalı.');
assert(js.includes("oy_kullaniciTercihleri"),'Kullanıcı tercihleri Firestore koleksiyonuna yazılmalı.');
assert(js.includes("dashboardHizliIslemler:q"),'Yeni hızlı işlem seçimi eski alanla da uyumlu yazılmalı.');
assert(js.includes("dashboardBilgiKartlari:ids"),'Yeni bilgi kartı seçimi eski alanla da uyumlu yazılmalı.');
assert(js.includes("duplicate=$('#db41SocialCard'"),'Tekrarlanan Okul Bağlantıları kartı temizlenmeli.');
assert(js.includes("-webkit-text-fill-color:currentColor!important"),'Sosyal bağlantı etiket kontrastı inline stil karşısında zorlanmalı.');
assert(js.includes('db-state-sentinel'),'Seçili olmayan Servis kartının sayaç katmanı tarafından zorla eklenmesi engellenmeli.');
assert(js.includes("mod:'tasima',tab:'tasima'"),'Servis kartı gerçek taşıma yetkisi ve sekmesini kullanmalı.');
assert(js.includes('En fazla 4 kart seçebilirsiniz.'),'Hızlı işlem editörü dört kart sınırını açıkça uygulamalı.');
assert(!js.includes('setInterval('),'Yeni durum yöneticisi sürekli polling kullanmamalı.');
assert(ui.includes("dashboard-mobile-state-v3.js"),'Durum yöneticisi mobil yükleme zincirinde olmalı.');
assert(sw.includes("'./js/dashboard-mobile-state-v3.js'"),'Durum yöneticisi PWA precache içinde olmalı.');
console.log('dashboard-mobile-state-v3-smoke: OK');
