const fs=require('fs');
const assert=require('assert');
const v4=fs.readFileSync('js/dashboard-mobile-v4.js','utf8');
const polish=fs.readFileSync('js/dashboard-mobile-v4-polish.js','utf8');
const hotfix=fs.readFileSync('js/dashboard-mobile-v4-hotfix.js','utf8');
const counts=fs.readFileSync('js/dashboard-card-count-fix.js','utf8');
const loader=fs.readFileSync('js/ui-stability-fixes.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');

assert(v4.includes("p.classList.remove('dmv2','dmv3')"),'Eski dashboard sınıfları temizlenmeli');
assert(v4.includes("p.classList.add('db4')"),'Dashboard v4 sınıfı uygulanmalı');
assert(v4.includes('[data-theme="dark"] #tab-panel.db4'),'Koyu tema için ayrı tokenlar olmalı');
assert(v4.includes('db4-weather') && v4.includes('heroHavaSatir'),'Dinamik hava widgetı v4 içinde bulunmalı');
assert(v4.includes('db4-bell') && v4.includes('zilWidget'),'Canlı zil/ders widgetı v4 içinde bulunmalı');
assert(v4.includes('db4-social') && v4.includes('heroSosyalMedya'),'Sosyal medya kaynağı v4 içinde bulunmalı');
assert(v4.includes('Evrak Takibi') && v4.includes('Dökümanlar') && v4.includes('Öğrenciler') && v4.includes('Nöbetler') && v4.includes('Takvim'),'Beş ana hızlı işlem bulunmalı');
assert(v4.includes("Q('[data-kart-id=\"bekleyenEvrak\"]',p)?.remove()"),'Boş Bekleyen Evrak dashboard kartı kaldırılmalı');
assert(!v4.includes('<div class="l">Bekleyen Evrak</div>'),'Bugün özetinde Bekleyen Evrak bulunmamalı');
assert(polish.includes('oyDashboardV4KartDuzeni_v2'),'Kullanıcı kart düzeni yerel tercihle saklanmalı');
assert(polish.includes('dashboardV41Duzenle'),'Kart ekle/çıkar/sırala editörü bulunmalı');
assert(polish.includes('INFO_CARDS'),'Rol uyumlu ek bilgi kartı havuzu bulunmalı');
assert(polish.includes('Okul Bağlantıları') && polish.includes('heroSosyalMedya'),'Sosyal medya ve okul bağlantıları görünür karta taşınmalı');
assert(polish.includes('.db41 .db4-school{display:none!important}'),'Eski karmaşık okul özeti mobilde kaldırılmalı');
assert(polish.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'Mobil bilgi kartları iki kolonlu okunur düzende olmalı');
assert(polish.includes('--d-text:#0b1f33') && polish.includes('--d-text:#f6f9fc'),'Açık/koyu kontrast renkleri ayrı tanımlanmalı');
assert(hotfix.includes("PREF_COL='oy_kullaniciTercihleri'"),'Bilgi kartı düzeni Firestore kullanıcı tercihine bağlanmalı');
assert(hotfix.includes('dashboardBilgiKartlari:DEFAULT_INFO'),'İlk açılışta varsayılan kartlar Firestore’a yazılmalı');
assert(hotfix.includes('grid-template-columns:minmax(0,1.12fr) minmax(128px,.88fr)'),'Zil kartı iki dengeli sütunda düzenlenmeli');
assert(hotfix.includes('.db4-bell:after{content:none'),'Eski Program overlay rozeti kaldırılmalı');
assert(hotfix.includes('--d-track') && hotfix.includes('--d-fill'),'Zil ilerleme çubuğu açık/koyu temada ayrı kontrast tokenı kullanmalı');
assert(counts.includes("db.collection(col).onSnapshot"),'Servis sayısı doğrudan Firestore koleksiyonundan canlı izlenmeli');
assert(counts.includes('servisRemoteCount'),'Firestore servis sayısı merkezi sayaç motoruna aktarılmalı');
assert(counts.includes('dbx-female') && counts.includes('dbx-male'),'Kız/erkek göstergeleri ayrı renk sınıfları kullanmalı');
assert(loader.includes("dashboard-mobile-v4.js") && loader.includes("dashboard-mobile-v4-polish.js") && loader.includes('dashboard-mobile-v4-hotfix.js'),'Ana yükleyici v4 katmanlarını çağırmalı');
assert(!loader.includes("dashboard-mobile-v3.js") && !loader.includes("dashboard-mobile-v2.js") && !loader.includes("dashboard-daily-center.js"),'Eski dashboard motorları yüklenmemeli');
assert(sw.includes("'./js/dashboard-mobile-v4.js'") && sw.includes("'./js/dashboard-mobile-v4-polish.js'") && sw.includes("'./js/dashboard-card-count-fix.js'") && sw.includes("'./js/dashboard-mobile-v4-hotfix.js'"),'Dashboard dosyaları çevrimdışı önbelleğe alınmalı');
assert(sw.includes("oy-cache-v443"),'Service Worker cache sürümü v443 olmalı');
assert(v4.includes('@media(prefers-reduced-motion:reduce)'),'Hareket azaltma erişilebilirliği korunmalı');
console.log('dashboard-mobile-v4-smoke: OK');
