const fs=require('fs');
const assert=require('assert');

const documents=fs.readFileSync('js/modules/documents.js','utf8');
const viewer=fs.readFileSync('js/modules/document-viewer.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');

assert(documents.includes("s.src='js/modules/document-viewer.js'"),'Documents V2 belge görüntüleyiciyi doğrudan module path üzerinden yalnız kullanım anında lazy-load etmeli.');
assert(documents.includes("endsWith('js/modules/document-viewer.js')"),'Documents V2 mevcut module viewer scriptini yeniden kullanmalı.');
assert(documents.includes("s.dataset.korukCapability='document-viewer'"),'Belge görüntüleyici capability olarak işaretlenmeli.');
assert(documents.includes("PermissionService?.can?.('documents.view','preview')"),'Belge açma documents.view preview/read/edit yetki sözleşmesine uymalı.');
assert(documents.includes('viewer?.destekliMi?.'),'Dosya türü görüntüleyici capability kontrolünden geçmeli.');
assert(documents.includes('await viewer.ac('),'Desteklenen belgeler uygulama içi görüntüleyicide açılmalı.');
assert(documents.includes("window.open(d.dosyaUrl,'_blank','noopener')"),'Desteklenmeyen veya görüntüleyici hatalı belgelerde web fallback korunmalı.');
assert(!documents.includes('js/dokuman-okuyucu.js'),'Emekli root viewer yolu Documents V2 zincirine geri dönmemeli.');
for(const lib of ['pdf.js/3.11.174/pdf.min.js','docx-preview@0.3.6','exceljs/4.4.0/exceljs.min.js','xlsx/0.18.5/xlsx.full.min.js']) assert(viewer.includes(lib),`Belge görüntüleyici lazy bağımlılığı korunmalı: ${lib}`);
assert(viewer.includes('window.DokumanOkuyucu={'),'Görüntüleyici tek DokumanOkuyucu capability API sunmalı.');
assert(viewer.includes('function pullToRefreshAyarla(enabled)'),'Native pull-to-refresh capability fallback korunmalı.');
assert(!/createElement\(\s*['"]style['"]\s*\)/.test(viewer),'Belge görüntüleyici runtime <style> üretmemeli.');
assert(!viewer.includes('function style(){'),'Eski viewer style() katmanı geri dönmemeli.');
for(const selector of ['dv3','dv3h','dv3body','dv3pdfpage','dv3wordviewport','dv3sheet']) assert(new RegExp(`\\.${selector}\\s*\\{`).test(design),`Belge görüntüleyici stili design-system.css içinde olmalı: .${selector}`);
assert(documents.includes("PermissionService?.can?.('documents.tracking','read')"),'Evrak Takibi görüntüleme merkezi documents.tracking iznini kullanmalı.');
assert(documents.includes("PermissionService?.can?.('documents.tracking.edit','edit')"),'Evrak Takibi yazma merkezi documents.tracking.edit iznini kullanmalı.');
assert(documents.includes("device().add('evrak',COL.evrak")&&documents.includes("device().update('evrak',COL.evrak")&&documents.includes("device().remove('evrak',COL.evrak"),'Evrak CRUD DeviceData local-first kapısında kalmalı.');
assert(documents.includes('responsibleNames(x.sorumluOgretmenIdler)'),'Evrak kartı gerçek sorumlu öğretmenleri göstermeli.');
assert(loader.includes("['documents.tracking','Evrak Takibi','section']")&&loader.includes("['documents.tracking.edit','Evrak Takibi düzenleme','action']"),'Evrak izinleri merkezi katalogda olmalı.');
assert(loader.includes("'module.documents':['dokumanlar','evrak']"),'Eski evrak yetkisi Documents modül görünürlüğünü korumalı.');
assert(loader.includes("'documents.tracking':['evrak']")&&loader.includes("'documents.tracking.edit':['evrak']"),'Eski evrak rol yetkisi merkezi izinlere alias olmalı.');
console.log('Documents V2 Evrak Takibi merkezi yetki + local-first sözleşmesi başarılı.');
console.log('Documents V2 doğrudan module viewer + merkezi tasarım sözleşmesi başarılı.');
