const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('js/modules/management.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const report=fs.readFileSync('js/modules/report-engine.js','utf8');
assert(src.includes('const DUTY_REPORT_COLUMNS=['),'Nöbet raporu sabit referans sütunlarını kullanmalı.');
for(const header of ['BAHÇE','OKUL BİNASI','GİRİŞ - BAHÇE','NÖBETÇİ AMİR']) assert(src.includes(header),`Nöbet raporu sütunu eksik: ${header}`);
for(const marker of ['ka-duty-report-banner','ka-duty-report-weekend','ka-duty-report-holiday','ka-duty-report-phones','ka-duty-report-tasks','ka-duty-report-footer','ka-duty-report-signature']) assert(src.includes(marker)||css.includes(marker),`Tam nöbet raporu anatomisi eksik: ${marker}`);
assert(src.includes('for(let g=1;g<=gunSayisi;g++)'),'Rapor ayın tüm günlerini üretmeli.');
assert(!src.includes('if(haftasonu||tatil)continue;'),'Hafta sonu ve tatil günleri rapordan atılmamalı.');
assert(src.includes('colspan="4"'),'Hafta sonu/tatil satırları üç nöbet alanı + amir sütununu kaplamalı.');
assert(src.includes('Geçerlilik Tarihi')&&src.includes('dutyReportFirstWorkday'),'Rapor geçerlilik tarihi seçimini korumalı.');
assert(src.includes('dutyReportDocumentDate()'),'İmza tarihi raporun oluşturulduğu tarihi kullanmalı.');
const taskBlock=src.slice(src.indexOf('const DUTY_TASKS=['),src.indexOf('];',src.indexOf('const DUTY_TASKS=['))+2);
assert((taskBlock.match(/^\s*'/gm)||[]).length===14,'Tam nöbet talimatı 14 maddeden oluşmalı.');
for(const text of ['Ders başlamadan 30 dk önce okula gelinmesi','Taşıma çizelgesinin her gün servis şoförlerine imzalatılması','Törenlerin yapılması için gerekli düzenin sağlanması','Gün sonunda nöbet defterinin ilgili bölümünün doldurulması']) assert(taskBlock.includes(text),`Nöbet görevi eksik: ${text}`);
assert(src.includes('ka-duty-report--${orientation}'),'Dikey/yatay rapor ayrı orientation sınıfı üretmeli.');
assert(src.includes('function dutyReportDensity(days,assignments,chiefs)')&&src.includes('data-duty-density="${density}"'),'Rapor ay gün sayısı ve isim uzunluğuna göre otomatik punto yoğunluğu seçmeli.');
assert(css.includes('.ka-duty-report--portrait{height:287mm;min-height:287mm}')&&css.includes('.ka-duty-report--landscape{height:200mm;min-height:200mm;'),'Rapor her iki A4 yönünde kullanılabilir alanın tamamını doldurmalı.');
assert(css.includes('.ka-duty-report-table{flex:1 1 0')&&css.includes('height:auto!important'),'Çizelge sabit yükseklik yerine kalan A4 alanını otomatik doldurmalı.');
assert(!css.includes('.ka-duty-report--portrait .ka-duty-report-table{height:187mm}')&&!css.includes('.ka-duty-report--landscape .ka-duty-report-table{height:122mm}'),'Eski sabit tablo yüksekliği geri dönmemeli.');
assert(css.includes('.ka-duty-report-banner h1{width:100%')&&css.includes('font-size:9.4pt!important'),'Nöbet raporu başlığı daha büyük ve tam genişlik olmalı.');
assert(css.includes('font-size:var(--ka-duty-cell-font)!important')&&css.includes('[data-duty-density="dense"]')&&css.includes('[data-duty-density="roomy"]'),'Tablo ve alt veriler otomatik yoğunluk puntosunu kullanmalı.');
assert(css.includes('.ka-duty-report-table tbody tr.ka-duty-report-weekend td{background:#e6e6e6!important'),'Tüm hafta sonu hücreleri satır paritesinden bağımsız aynı dolgu renginde olmalı.');
assert(!css.includes('.ka-duty-report-footer{margin-top:auto')&&css.includes('.ka-duty-report-footer{flex:0 0 auto;margin-top:1mm'),'Alt onay alanı görevlerden sonra gelmeli; büyük yapay boşluk oluşturmamalı.');
assert(css.includes('columns:2'),'Yatay görevler iki sütuna sıkıştırılmalı.');
assert(report.includes("page=o.yon==='yatay'?'A4 landscape':'A4 portrait'")&&report.includes('@page{size:${page};margin:0}'),'Merkezi ReportEngine gerçek A4 portrait/landscape sayfa boyutunu korumalı.');
assert(src.includes('kenarBosluk:5'),'Nöbet raporu A4 yüzeyini küçük ve sabit kenar boşluğuyla kullanmalı.');
console.log('Adaptif tam A4 nöbet çizelgesi portrait/landscape sözleşmesi başarılı.');
