const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('js/modules/management.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const report=fs.readFileSync('js/modules/report-engine.js','utf8');
assert(src.includes('const DUTY_REPORT_COLUMNS=['),'Nöbet raporu sabit referans sütunlarını kullanmalı.');
for(const header of ['BAHÇE','OKUL BİNASI','GİRİŞ - BAHÇE','NÖBETÇİ AMİR']) assert(src.includes(header),`Nöbet raporu sütunu eksik: ${header}`);
for(const marker of ['ka-duty-report-banner','ka-duty-report-weekend','ka-duty-report-holiday','ka-duty-report-phones','ka-duty-report-tasks','ka-duty-report-footer','ka-duty-report-signature']) assert(src.includes(marker)||css.includes(marker),`Tam nöbet raporu anatomisi eksik: ${marker}`);
assert(src.includes('for(let g=1;g<=gunSayisi;g++)'),'Rapor ayın tüm günlerini üretmeli.');
assert(!src.includes('if(haftasonu||tatil)continue;'),'Hafta sonu ve tatil günleri rapordan atılmamalı.');
assert(src.includes('colspan="4"'),'Hafta sonu/tatil satırları üç nöbet alanı + amir sütununu kaplamalı.');
assert(src.includes('Geçerlilik Tarihi')&&src.includes('dutyReportFirstWorkday'),'Rapor geçerlilik tarihi seçimini korumalı.');
assert(src.includes('dutyReportDocumentDate()'),'İmza tarihi raporun oluşturulduğu tarihi kullanmalı.');
const taskBlock=src.slice(src.indexOf('const DUTY_TASKS=['),src.indexOf('];',src.indexOf('const DUTY_TASKS=['))+2);
assert((taskBlock.match(/^\s*'/gm)||[]).length===14,'Tam nöbet talimatı 14 maddeden oluşmalı.');
for(const text of ['Ders başlamadan 30 dk önce okula gelinmesi','Taşıma çizelgesinin her gün servis şoförlerine imzalatılması','Törenlerin yapılması için gerekli düzenin sağlanması','Gün sonunda nöbet defterinin ilgili bölümünün doldurulması']) assert(taskBlock.includes(text),`Nöbet görevi eksik: ${text}`);
assert(src.includes('ka-duty-report--${orientation}'),'Dikey/yatay rapor ayrı orientation sınıfı üretmeli.');
assert(css.includes('.ka-duty-report--portrait{min-height:287mm}')&&css.includes('.ka-duty-report--landscape{min-height:200mm}'),'Rapor her iki A4 yönünde kullanılabilir alanın tamamına yayılmalı.');
assert(css.includes('.ka-duty-report--portrait .ka-duty-report-table{height:187mm}')&&css.includes('.ka-duty-report--landscape .ka-duty-report-table{height:122mm}'),'Çizelge dikey ve yatay A4 alanını yönüne göre doldurmalı.');
assert(css.includes('margin-top:auto')&&css.includes('columns:2'),'Alt onay alanı sayfanın altına oturmalı; yatay görevler iki sütuna sıkıştırılmalı.');
assert(report.includes("page=o.yon==='yatay'?'A4 landscape':'A4 portrait'")&&report.includes('@page{size:${page};margin:0}'),'Merkezi ReportEngine gerçek A4 portrait/landscape sayfa boyutunu korumalı.');
assert(src.includes('kenarBosluk:5'),'Nöbet raporu A4 yüzeyini küçük ve sabit kenar boşluğuyla kullanmalı.');
console.log('Tam A4 nöbet çizelgesi portrait/landscape parity sözleşmesi başarılı.');
