const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('js/modules/management.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const report=fs.readFileSync('js/modules/report-engine.js','utf8');
assert(src.includes('const DUTY_REPORT_COLUMNS=['));
for(const header of ['BAHÇE','OKUL BİNASI','GİRİŞ - BAHÇE','NÖBETÇİ AMİR']) assert(src.includes(header));
assert(src.includes('function dutyReportChiefName(record)')&&src.includes('record.ogretmenAdSoyad')&&src.includes('record.amirAdSoyad')&&src.includes('teacherName(teacher)'));
assert(src.includes("dutyReportChiefName(amir).toLocaleUpperCase('tr')"));
assert(src.includes('for(let g=1;g<=gunSayisi;g++)'));
assert(!src.includes('if(haftasonu||tatil)continue;'));
const taskBlock=src.slice(src.indexOf('const DUTY_TASKS=['),src.indexOf('];',src.indexOf('const DUTY_TASKS=['))+2);
assert((taskBlock.match(/^\s*'/gm)||[]).length===14);
assert(src.includes('ka-duty-report-note')&&src.includes('Bu çizelge ${esc(validityText)} tarihinden itibaren geçerlidir.'));
assert(src.includes('first=dutyReportFirstWorkday(dutyYear,dutyMonth)'),'Nöbet raporu önizlemesi geçerlilik tarihini ilgili ayın ilk iş gününden başlatmalı.');
assert(src.includes('if(y&&m>=0)validity.value=dutyReportFirstWorkday(y,m)'),'Rapor ayı değiştiğinde geçerlilik tarihi yeni ayın ilk iş gününe güncellenmeli.');
assert(src.includes('documentDate=validityText'),'Müdür adı üzerindeki tarih rapor geçerlilik tarihi ile aynı olmalı.');
assert(css.includes('--ka-duty-table-height:188mm')&&css.includes('[data-duty-density="dense"]{--ka-duty-table-height:190mm'));
assert(css.includes('font-size:12.8pt!important')&&css.includes('width:calc(100% - 12mm)'));
assert(css.includes('--ka-duty-head-font:9.5pt;--ka-duty-cell-font:8.7pt;--ka-duty-task-font:7.2pt'));
assert(css.includes('font-size:var(--ka-duty-head-font)!important')&&css.includes('font-size:var(--ka-duty-cell-font)!important'));
assert(css.includes('.ka-duty-report-tasks ol{flex:0 0 auto')&&css.includes('font-size:var(--ka-duty-task-font)!important;line-height:1!important'));
assert(css.includes('.ka-duty-report-table tbody tr.ka-duty-report-weekend td{background:#e6e6e6!important'));
assert(report.includes("page=o.yon==='yatay'?'A4 landscape':'A4 portrait'")&&report.includes('@page{size:${page};margin:0}'));
console.log('Tablo öncelikli tam A4 nöbet raporu sözleşmesi başarılı.');
