const fs=require('fs');
const documents=fs.readFileSync('js/modules/documents.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
if(!documents.includes('ka-evrak-page'))throw new Error('Evrak Takibi kök konteyneri responsive sınıfını taşımalı.');
if(!documents.includes('ka-evrak-filter-row'))throw new Error('Evrak durum filtreleri taşmayı önleyen grid konteynerini kullanmalı.');
if(!css.includes('.ka-evrak-filter-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))'))throw new Error('Dar ekranda evrak filtreleri iki sütunlu responsive grid olmalı.');
if(!css.includes('@media (min-width:560px)'))throw new Error('Geniş ekranda evrak filtreleri beş sütuna dönebilmeli.');
if(!index.includes('css/design-system.css?v=988'))throw new Error('Evrak düzeni CSS cache sürümü yenilenmeli.');
console.log('Evrak Takibi mobil taşma regresyon testi başarılı.');
