const fs = require('fs');
const assert = require('assert');
const vm = require('vm');
const src = fs.readFileSync('js/ozellik-katalogu.js','utf8');
const app = fs.readFileSync('js/app.js','utf8');
const nav = fs.readFileSync('js/alt-navigasyon.js','utf8');
const editor = fs.readFileSync('js/nav-duzeni-editor.js','utf8');
const index = fs.readFileSync('index.html','utf8');
const sw = fs.readFileSync('service-worker.js','utf8');
const opened=[];const domNodes=[{getAttribute:k=>k==='data-tab'?'panel':null,textContent:'Ana Sayfa',querySelector:()=>null},{getAttribute:k=>k==='data-tab'?'ogrenciler':null,textContent:'Öğrenciler',querySelector:()=>null}];
const windowObj={sekmeAc:x=>opened.push(x)};const ctx={window:windowObj,document:{querySelectorAll:sel=>sel==='[data-tab]'?domNodes:[]},Map,Set,String,Object,Array,console};vm.createContext(ctx);vm.runInContext(src,ctx);let special=0;windowObj.OzellikKatalogu.kaydet({id:'yeniOzellik',ad:'Yeni Özellik',ac:()=>{special++}});const list=windowObj.OzellikKatalogu.liste();
assert(list.some(x=>x.deger==='panel'));assert(list.some(x=>x.deger==='@ozellik:yeniOzellik'));assert(windowObj.OzellikKatalogu.ac('panel'));assert.deepStrictEqual(opened,['panel']);assert(windowObj.OzellikKatalogu.ac('@ozellik:yeniOzellik'));assert.strictEqual(special,1);
assert(app.includes('window.OzellikKatalogu.liste().map'));assert(nav.includes('function _ozellikKatalogunuSenkronla()'));assert(nav.includes('window.OzellikKatalogu.ac(eo.sekmeAd)'));assert(editor.includes('window.OzellikKatalogu.liste().forEach'));
const featurePos=index.indexOf('<script src="js/ozellik-katalogu.js"></script>'),appPos=index.indexOf('<script src="js/app.js"></script>');assert(featurePos>=0&&appPos>=0&&featurePos<appPos);assert(sw.includes("'./js/ozellik-katalogu.js'"));assert(sw.includes('oy-cache-v448'));
console.log('Merkezi özellik kataloğu smoke testleri başarılı.');
