const fs=require('fs');
const assert=require('assert');
const rubric=fs.readFileSync('js/modules/rubric-settings.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
assert(rubric.includes('function maarifMatrix(rows)'),'Maarif görünümü öğretmen bazlı canonical matris renderer kullanmalı.');
assert(rubric.includes('aria-label="DERS / SINIF aylık rapor matrisi"')&&rubric.includes('CONTROLS.maarifRapor||[]'),'Maarif matrisi ders/sınıf ve 10 aylık kontrol yapısını korumalı.');
assert(rubric.includes('groups=new Map')&&rubric.includes('if(!r.ogretmenId)return'),'Maarif kayıtları mevcut davranıştaki gibi öğretmen bazında gruplanmalı.');
assert(rubric.includes("sorted.length*labels.length")&&rubric.includes("filter(Boolean).length"),'Öğretmen grup başlığı toplam ilerlemeyi göstermeli.');
assert(rubric.includes("String(a.ders||'').localeCompare")&&rubric.includes("String(a.sinif||'').localeCompare"),'Maarif kayıtları ders ve sınıfa göre sıralanmalı.');
assert(rubric.includes('data-cizelge-check data-type="${type}"')&&rubric.includes('data-index="${i}"'),'Aylık kontroller mevcut canonical toggle akışını kullanmalı.');
assert(rubric.includes("editButton('maarifRapor',r.id)"),'Maarif kayıtlarında mevcut düzenleme davranışı korunmalı.');
assert(rubric.includes("if(type==='maarifRapor')return maarifMatrix(rows);"),'Maarif sayfası canonical responsive matris görünümüne yönlenmeli.');
assert(rubric.includes('ka-maarif-record-grid')&&rubric.includes('ka-maarif-card'),'Maarif sabit geniş tablo yerine responsive kart matrisi kullanmalı.');
assert(!rubric.includes('style="min-width:980px"'),'Maarif görünümü sabit 980px yatay tabloya geri dönmemeli.');
assert(css.includes('.ka-maarif-record-grid')&&css.includes('@media(max-width:520px)'),'Maarif responsive kuralları merkezi design-system içinde olmalı.');
console.log('Maarif responsive teacher matrix visible parity OK');
