const fs = require('fs');
const assert = require('assert');
const { execFileSync } = require('child_process');
const navBootstrap = fs.readFileSync('js/alt-navigasyon.js','utf8');
const nav = fs.readFileSync('js/alt-navigasyon-core.js','utf8');
const editor = fs.readFileSync('js/nav-duzeni-editor.js','utf8');
const accordion = fs.readFileSync('js/nav-accordion.js','utf8');
const navScroll = fs.readFileSync('js/nav-scroll-fix.js','utf8');
const nativePreview = fs.readFileSync('js/native-report-preview.js','utf8');
const sw = fs.readFileSync('service-worker.js','utf8');
execFileSync(process.execPath,['--check','js/alt-navigasyon.js']);execFileSync(process.execPath,['--check','js/alt-navigasyon-core.js']);execFileSync(process.execPath,['--check','js/nav-accordion.js']);execFileSync(process.execPath,['--check','js/nav-scroll-fix.js']);
assert(navBootstrap.includes("yukle('js/alt-navigasyon-core.js'"),'Navigasyon bootstrap çekirdeği yüklemeli');
assert(nav.includes('oyNavDuzeniCacheV1'));assert(nav.includes('let _navDuzeniVerisi = _navDuzeniCacheOku();'));assert(nav.includes('window._navDuzeniYerelUygula = _navDuzeniYerelUygula;'));assert(nav.includes('_menuResmiVarsayilanGetir'));assert(editor.includes('window._navDuzeniYerelUygula(nd)'));assert(editor.includes('window._navDuzeniYerelUygula(onceki)'));assert(editor.includes('function _ndSekmeSeciciOlustur'));assert(editor.includes("document.querySelectorAll('[data-tab]')"));assert(editor.includes('const sekmeAd = _ndSekmeDegeriAl'));
for(const x of ["PDF_MENU,'g7','PDF İşlemleri'","'g7alt','g7','Raporlar'",'altMenuler','aria-expanded','ndAltMenuEkle','menuDuzenle','menuSil','nd-altmenu-sec','menuTasi',"sekmeAd:'@ozellik:pdf_resimden'","sekmeAd:'@ozellik:pdf_birlestir'"])assert(accordion.includes(x));
for(const x of ['height:100dvh !important','z-index:9800 !important','body.an-tam-ekran-nav-acik .bottom-nav','flex:1 1 0 !important','height:0 !important','overflow-y:scroll !important','touch-action:pan-y !important','scrollBy'])assert(navScroll.includes(x));assert(nativePreview.includes("s.src = 'js/nav-accordion.js'"));assert(/oy-cache-v\d+/.test(sw));
console.log('Navigasyon özelleştirme ve tam ekran akordeon smoke testleri başarılı.');
