const fs = require('fs');
const assert = require('assert');
const { execFileSync } = require('child_process');
const nav = fs.readFileSync('js/alt-navigasyon.js','utf8');
const editor = fs.readFileSync('js/nav-duzeni-editor.js','utf8');
const accordion = fs.readFileSync('js/nav-accordion.js','utf8');
const navScroll = fs.readFileSync('js/nav-scroll-fix.js','utf8');
const nativePreview = fs.readFileSync('js/native-report-preview.js','utf8');
const sw = fs.readFileSync('service-worker.js','utf8');
execFileSync(process.execPath, ['--check','js/nav-accordion.js']);
execFileSync(process.execPath, ['--check','js/nav-scroll-fix.js']);
assert(nav.includes("oyNavDuzeniCacheV1"));
assert(nav.includes('let _navDuzeniVerisi = _navDuzeniCacheOku();'));
assert(nav.includes('window._navDuzeniYerelUygula = _navDuzeniYerelUygula;'));
assert(nav.includes('_menuResmiVarsayilanGetir'));
assert(editor.includes("window._navDuzeniYerelUygula(nd)"));
assert(editor.includes("window._navDuzeniYerelUygula(onceki)"));
assert(editor.includes('function _ndSekmeSeciciOlustur'));
assert(editor.includes("document.querySelectorAll('[data-tab]')"));
assert(editor.includes('const sekmeAd = _ndSekmeDegeriAl'));
assert(accordion.includes("PDF_MENU,'g7','PDF İşlemleri'"));
assert(accordion.includes("'g7alt','g7','Raporlar'"));
assert(accordion.includes('altMenuler'));
assert(accordion.includes('aria-expanded'));
assert(accordion.includes('ndAltMenuEkle'));
assert(accordion.includes('menuDuzenle'));
assert(accordion.includes('menuSil'));
assert(accordion.includes('nd-altmenu-sec'));
assert(accordion.includes('menuTasi'));
assert(accordion.includes("sekmeAd:'@ozellik:pdf_resimden'"));
assert(accordion.includes("sekmeAd:'@ozellik:pdf_birlestir'"));
assert(navScroll.includes("height:100dvh !important"));
assert(navScroll.includes("z-index:9800 !important"));
assert(navScroll.includes("body.an-tam-ekran-nav-acik .bottom-nav"));
assert(navScroll.includes("flex:1 1 0 !important"));
assert(navScroll.includes("height:0 !important"));
assert(navScroll.includes("overflow-y:scroll !important"));
assert(navScroll.includes("touch-action:pan-y !important"));
assert(navScroll.includes('scrollBy'));
assert(nativePreview.includes("s.src = 'js/nav-accordion.js'"));
assert(sw.includes("oy-cache-v442"), 'Navigasyon ve özellik kataloğu güncel cache sürümünü kullanmalı.');
console.log('Navigasyon özelleştirme ve tam ekran akordeon smoke testleri başarılı.');
