const fs = require('fs');
const assert = require('assert');
const { execFileSync } = require('child_process');
const nav = fs.readFileSync('js/alt-navigasyon.js','utf8');
const editor = fs.readFileSync('js/nav-duzeni-editor.js','utf8');
const accordion = fs.readFileSync('js/nav-accordion.js','utf8');
const navScroll = fs.readFileSync('js/nav-scroll-fix.js','utf8');
const nativePreview = fs.readFileSync('js/native-report-preview.js','utf8');
const sw = fs.readFileSync('service-worker.js','utf8');
execFileSync(process.execPath, ['--check','js/nav-accordion.js']);
execFileSync(process.execPath, ['--check','js/nav-scroll-fix.js']);

assert(nav.includes("oyNavDuzeniCacheV1"), 'Navigasyon düzeni ilk çizim için local cache kullanmalı.');
assert(nav.includes('let _navDuzeniVerisi = _navDuzeniCacheOku();'), 'İlk GRUPLAR inşası cached resmi düzenle başlamalı.');
assert(nav.includes('window._navDuzeniYerelUygula = _navDuzeniYerelUygula;'), 'Editör optimistic düzeni gerçek menüye aktarabilmeli.');
assert(nav.includes('_menuResmiVarsayilanGetir'), 'Kart varsayılanı adminin güncel resmi rengini/adını kullanmalı.');
assert(editor.includes("window._navDuzeniYerelUygula(nd)"), 'Navigasyon editörü Firestore beklemeden optimistic UI uygulamalı.');
assert(editor.includes("window._navDuzeniYerelUygula(onceki)"), 'Firestore hatasında optimistic değişiklik geri alınmalı.');
assert(editor.includes('function _ndSekmeSeciciOlustur'), 'Yeni öğe ekleme ana app sekme seçicisi yokken fallback sağlamalı.');
assert(editor.includes("document.querySelectorAll('[data-tab]')"), 'Fallback sekme listesi mevcut uygulama sekmelerinden üretilmeli.');
assert(editor.includes('const sekmeAd = _ndSekmeDegeriAl'), 'Yeni öğe fallback seçicisinden değer okuyabilmeli.');
assert(accordion.includes("PDF_MENU,'g7','PDF İşlemleri'"), 'PDF İşlemleri gerçek alt menü olarak tanımlanmalı.');
assert(accordion.includes("'g7alt','g7','Raporlar'"), 'Raporlar akordeon alt menüsü korunmalı.');
assert(accordion.includes('altMenuler'), 'Navigasyon düzeni birden fazla alt menüyü saklayabilmeli.');
assert(accordion.includes('aria-expanded'), 'Alt menü başlığı erişilebilir akordeon durumu taşımalı.');
assert(accordion.includes('ndAltMenuEkle'), 'Navigasyon Düzeni ekranında Alt Menü Ekle kontrolü bulunmalı.');
assert(accordion.includes('menuDuzenle'), 'Alt menü adı düzenlenebilmeli.');
assert(accordion.includes('menuSil'), 'Alt menü silinebilmeli.');
assert(accordion.includes('nd-altmenu-sec'), 'Öğeler Navigasyon Düzeninden belirli bir alt menüye taşınabilmeli.');
assert(accordion.includes('menuTasi'), 'Alt menüler kendi aralarında sıralanabilmeli.');
assert(accordion.includes("sekmeAd:'@ozellik:pdf_resimden'"), 'Resimden PDF PDF İşlemleri alt menüsüne bağımsız hedef olarak eklenmeli.');
assert(accordion.includes("sekmeAd:'@ozellik:pdf_birlestir'"), 'PDF Birleştir PDF İşlemleri alt menüsüne bağımsız hedef olarak eklenmeli.');
assert(navScroll.includes("height:100dvh !important"), 'Mobil navigasyon katmanı tüm viewport yüksekliğini kaplamalı.');
assert(navScroll.includes("z-index:9800 !important"), 'Navigasyon katmanı bottom-nav üzerinde kalmalı.');
assert(navScroll.includes("body.an-tam-ekran-nav-acik .bottom-nav"), 'Alt katman açıkken bottom-nav gizlenmeli.');
assert(navScroll.includes("flex:1 1 0 !important"), 'Navigasyon gövdesi kalan yüksekliği doldurmalı.');
assert(navScroll.includes("height:0 !important"), 'Flex scroll viewport gerçek sınırlı yüksekliğe zorlanmalı.');
assert(navScroll.includes("overflow-y:scroll !important"), 'Akordeon açıldığında navigasyon gövdesi kesin dikey kaydırılabilir olmalı.');
assert(navScroll.includes("touch-action:pan-y !important"), 'Mobil navigasyon gövdesinde parmakla dikey kaydırma açık olmalı.');
assert(navScroll.includes('scrollBy'), 'Akordeon açılınca açılan içerik görünür konumda tutulmalı.');
assert(nativePreview.includes("s.src = 'js/nav-accordion.js'"), 'Akordeon motoru uygulama başlangıcında yüklenmeli.');
assert(sw.includes("oy-cache-v441"), 'Navigasyon ve özellik kataloğu için cache sürümü v441 olmalı.');
console.log('Navigasyon özelleştirme ve tam ekran akordeon smoke testleri başarılı.');
