const fs=require('fs');
const assert=require('assert');
const vm=require('vm');

const src=fs.readFileSync('js/modules/payroll-change.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const personnelDocs=fs.readFileSync('js/modules/personnel-documents.js','utf8');
const appLoader=fs.readFileSync('js/app-loader.js','utf8');
const index=fs.readFileSync('index.html','utf8');
new Function(src);
new Function(personnelDocs);

const shellUi=fs.readFileSync('js/core/shell-ui.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
assert(!index.includes('<script src="js/modules/payroll-change.js" defer></script>'),'V2 maaş formu ilk açılışta eager yüklenmemeli.');
assert(sw.includes("'./js/modules/payroll-change.js'"),'V2 maaş formu offline Service Worker cache içinde bulunmalı.');
assert(shellUi.includes("loadScript?.('js/modules/payroll-change.js')"),'V2 maaş formu özel route üzerinden ihtiyaç anında lazy yüklenmeli.');
assert(src.includes("rows('ogretmenler')"),'Maaş formu öğretmenleri AppStore/DeviceData kaynağından almalı.');
assert(src.includes("rows('personel')"),'Maaş formu diğer personeli gerçek Management personel kaynağından almalı.');
for(const section of ["B:[],C:[],D:[],E:[],F:[],G:[],H:[]","B:{title:","C:{title:","D:{title:","E:{title:","F:{title:","G:{title:","H:{title:"]) assert(src.includes(section),`A-H veri modeli korunmalı ve yalnız seçilen kişiler eklenmeli: ${section}`);
for(const token of ["<optgroup label=\"Öğretmenler\">","<optgroup label=\"Diğer Personel\">","data-payroll-picker","data-payroll-add-person","kaynakId:r.id","Bu kişi bölüme zaten eklendi.","Object.keys(SECTION_META).map(sectionCard)"]) assert(src.includes(token),`Tüm öğretmen/personel seçme ve ekleme sözleşmesi eksik: ${token}`);
assert(!src.includes('D:r.map')&&!src.includes('data-payroll-toggle'),'Tüm kadro gizli kart olarak önceden oluşturulmamalı.');
for(const selector of ['.ka-payroll-page','.ka-payroll-header','.ka-payroll-metrics','.ka-payroll-section','.ka-payroll-picker','.ka-payroll-person-card','.ka-payroll-actions','[data-theme="dark"] .ka-payroll-page','@media(max-width:760px)']) assert(css.includes(selector),`Maaş değişikliği tasarım sözleşmesi eksik: ${selector}`);
assert(src.includes("PermissionService?.can?.('documents.view','preview')"),'Form görüntüleme yetkisi merkezi PermissionService ile yönetilmeli.');
assert(src.includes("PermissionService?.can?.('documents.edit','edit')"),'Form düzenleme yetkisi merkezi PermissionService ile yönetilmeli.');
assert(src.includes('function open(){if(!canView())'),'Doğrudan Payroll API açılışı documents.view sınırını aşmamalı.');
assert(/function render\(root=document\.getElementById\('v2ModuleRoot'\)\)\s*\{\s*if\(!root\)return false;\s*if\(!canView\(\)\)/.test(src),'Render girişinde de görüntüleme sınırı korunmalı.');
assert(src.includes('function print(){if(!canView())'),'Rapor çıktısı görüntüleme yetkisini aşmamalı.');
assert(src.includes("ReportEngine.printReport('Maaş Değişikliği Bildirim Formu'"),'Çıktı merkezi ReportEngine kullanmalı.');
assert(src.includes("yon:'yatay'"),'Maaş formu A4 yatay çıktı üretmeli.');
for(const token of ['ka-payroll-report__identity','ka-payroll-report__summary','ka-payroll-report__promotion','MAAŞ DEĞİŞİKLİĞİ YAPILACAK PERSONELİN','7 Günü Geçen Kesinti Yapılacak Gün Sayısı','ka-payroll-report__approval','Olur/Kurum Yetkilisinin','principalName(school)']) assert(src.includes(token),`Referans resmî maaş raporu sözleşmesi eksik: ${token}`);
for(const option of ['baslikGoster:false','logoGoster:false','tarihGoster:false','compact:true','kenarBosluk:8','fontSize:7']) assert(src.includes(option),`Referans şablona özel baskı ayarı eksik: ${option}`);
for(const selector of ['.ka-report .ka-payroll-report__title','.ka-report .ka-payroll-report__section-title th','.ka-report .ka-payroll-report__approval','.ka-report .ka-payroll-report__approval dl div','.ka-report .ka-payroll-report__approval dt::after']) assert(css.includes(selector),`Maaş raporu hizalama stili eksik: ${selector}`);
assert(css.includes('.ka-report .ka-payroll-report__section tbody td{text-align:center!important;vertical-align:middle!important}'),'Maaş raporundaki personel bilgi hücreleri yatay ve dikey ortalanmalı.');
assert(src.includes("data-document-form='payroll'")||src.includes("dataset.documentForm='payroll'"),'Documents ekranına maaş formu girişi eklenmeli.');
for(const forbidden of ['db.collection','onSnapshot','localStorage','document.createElement(\'style\')','document.createElement("style")']) assert(!src.includes(forbidden),`V2 maaş formu ${forbidden} kullanmamalı.`);
assert(!src.includes('style="'),'V2 maaş formu inline CSS üretmemeli; design-system.css kullanılmalı.');

const runtimeAddButton={dataset:{payrollAddPerson:'D'},onclick:null},runtimePicker={value:'o_t1'};
const runtimeRoot={innerHTML:'',querySelector:selector=>selector==='[data-payroll-picker="D"]'?runtimePicker:null,querySelectorAll:selector=>selector==='[data-payroll-add-person]'?[runtimeAddButton]:[]};
const runtime={console,requestAnimationFrame:fn=>fn(),document:{getElementById:()=>runtimeRoot,querySelector:()=>null,createElement:()=>({})},AppStore:{data:type=>type==='ogretmenler'?[{id:'t1',ad:'Ayşe',soyad:'Yılmaz',brans:'Türkçe'},{id:'t2',ad:'Mehmet',soyad:'Kaya',brans:'Matematik'}]:type==='personel'?[{id:'p1',adSoyad:'Fatma Demir',gorev:'Hizmetli'}]:type==='okulBilgileri'?[{id:'ayarlar',okulAdi:'Koruk Ortaokulu',mudurId:'t2'}]:[]},PermissionService:{can:()=>true,applyModule:()=>{}},addEventListener:()=>{},toast:()=>{}};
runtime.window=runtime;
vm.runInNewContext(src,runtime);
assert(runtime.PayrollChangeModule.open(),'Maaş değişikliği modülü örnek AppStore verisiyle açılmalı.');
for(const name of ['Ayşe Yılmaz · Türkçe','Mehmet Kaya · Matematik','Fatma Demir · Hizmetli']) assert(runtimeRoot.innerHTML.includes(name),`Açılır listede gerçek kadro seçeneği eksik: ${name}`);
assert(!runtimeRoot.innerHTML.includes('ka-payroll-person-card'),'Seçim yapılmadan öğretmen/personel kartı oluşturulmamalı.');
assert.strictEqual(typeof runtimeAddButton.onclick,'function','Ekle düğmesi çalışma davranışına bağlanmalı.');
runtimeAddButton.onclick();
assert(runtimeRoot.innerHTML.includes('ka-payroll-person-card')&&runtimeRoot.innerHTML.includes('Ayşe Yılmaz'),'Seçilen öğretmen ilgili bölüme eklenip düzenleme kartı oluşturmalı.');
const report=runtime.PayrollChangeModule.reportBody();
assert(report.includes('KORUK ORTAOKULU')&&report.includes('Mehmet Kaya'),'Rapor okul adını ve okul müdürünü merkezi okul ayarlarından çözmeli.');
assert(report.includes('ka-payroll-report__promotion')&&report.includes('ka-payroll-report__approval'),'Rapor boş durumda da referanstaki ana tabloları ve hizalı onay bloğunu üretmeli.');

assert(!index.includes('<script src="js/modules/personnel-documents.js" defer></script>'),'Diploma belge adaptörü ilk açılışta eager yüklenmemeli.');
assert(sw.includes("'./js/modules/personnel-documents.js'"),'Diploma belge adaptörü offline Service Worker cache içinde bulunmalı.');
assert(appLoader.includes("window.ShellUI.registerPageRoute('diploma-request'"),'Diploma kayıt talep sayfası mevcut ShellUI route registry üzerinden açılmalı.');
assert(appLoader.includes("window.ShellUI.registerPageRoute('diploma-response'"),'Diploma okul cevabı sayfası mevcut ShellUI route registry üzerinden açılmalı.');
assert(appLoader.includes("loadScript('js/modules/personnel-documents.js')"),'Diploma belge adaptörü ihtiyaç anında lazy yüklenmeli.');
assert(appLoader.includes('Diploma Kayıt Talep Dilekçesi')&&appLoader.includes('Diploma Okul Dilekçesi'),'Eski Personel İşleri > Diploma İşlemleri menü hedefleri görünür olmalı.');
assert(personnelDocs.includes('SyncEngine.register(type,col)')&&personnelDocs.includes('SyncEngine.localHydrate(types)'),'Diploma belgesi okul/öğretmen verisini önce IndexedDB/AppStore üzerinden hydrate etmeli.');
assert(personnelDocs.includes('okul.mudurId?teacherName(okul.mudurId)'),'Okul müdürü mevcut mudurId alanından gerçek öğretmen kimliğiyle çözülmeli.');
for(const field of ['adSoyad','tc','babaAdi','anneAdi','dogumYeri','dogumTarihi','mezuniyetTarihi','mezunSinif','adres']) assert(personnelDocs.includes(`name="${field}"`),`Diploma talep alanı eksik: ${field}`);
for(const field of ['adSoyad','tc','babaAdi','kizOglu','dogumTarihi','ogrenimSuresi','diplomaTarihi','diplomaSayisi','adres','cepNo','mudurAdi']) assert(personnelDocs.includes(`name="${field}"`),`Diploma okul cevabı alanı eksik: ${field}`);
assert(personnelDocs.includes('Diplomamı kaybettiğimden tarafıma diploma kayıt örneği düzenlenmesi hususunda;'),'Eski diploma talep dilekçesi gövde metni korunmalı.');
assert(personnelDocs.includes('diplomayı almaya hak kazandığı resmi kayıtların incelenmesinden anlaşılmıştır.'),'Eski diploma okul cevabı gövde metni korunmalı.');
assert(personnelDocs.includes('ReportEngine.printReport(title,body'),'Diploma çıktıları merkezi ReportEngine kullanmalı.');
for(const forbidden of ['db.collection','onSnapshot','localStorage','document.createElement(\'style\')','document.createElement("style")']) assert(!personnelDocs.includes(forbidden),`Diploma belge adaptörü ${forbidden} kullanmamalı.`);
assert(!personnelDocs.includes('style="'),'Diploma belge adaptörü inline UI CSS üretmemeli.');

console.log('V2 maaş + diploma personel belge sözleşmesi başarılı.');
