const fs=require('fs');
const assert=require('assert');
const ui=fs.readFileSync('js/core/shell-ui.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const parity=fs.readFileSync('js/modules/classic-parity.js','utf8');
const feature=fs.readFileSync('js/core/login-security.js','utf8');
const firebaseInit=fs.readFileSync('js/firebase-init.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const start=ui.indexOf('function renderProfile({remember=true}={})');
const end=ui.indexOf('\nfunction profileDetailHead',start);
assert(start>=0&&end>start,'Profil renderer bulunmalı.');
const block=ui.slice(start,end);
assert(block.includes('ka-profile-stats')&&!block.includes('ka-home-stats'),'Profil özet kartları dashboard istatistik sınıflarından bağımsız olmalı.');
for(const token of ['ka-profile-contact','ka-profile-actions','ka-profile-action__copy','ka-profile-action__count','ka-profile-action__chevron'])assert(block.includes(token),`Profil yeni düzen bileşeni eksik: ${token}`);
assert(ui.includes("function profileContactHtml({handle='',phone='',email=''})")&&ui.includes('const seen=new Set()')&&block.includes('const contact=profileContactHtml({handle,phone,email});'),'Profil kullanıcı adı, telefon ve e-postayı tek canonical iletişim rendererı üzerinden, yinelenmeden üretmeli.');
assert(!block.includes('phone?`<span class="ka-profile-contact__item')&&!block.includes('email?`<span class="ka-profile-contact__item'),'Eski inline telefon/e-posta rendererı geri dönmemeli.');
assert(!parity.includes("insertAdjacentHTML('beforeend',`<small>☎")&&!parity.includes("insertAdjacentHTML('beforeend',`<small>✉"),'Classic parity profil kartına ikinci telefon/e-posta satırı eklememeli.');
assert(parity.includes("copy.querySelectorAll(':scope > small').forEach(x=>x.remove())"),'Classic parity eski raw iletişim satırlarını temizlemeli.');
assert(design.includes('.ka-profile-copy>small{display:none!important}'),'Merkezi CSS eski cache kaynaklı raw profil iletişim satırlarını da gizlemeli.');
assert(block.includes("action('schedule'")&&block.includes("action('duty'")&&block.includes("action('exams'")&&block.includes("action('tasks'"),'Dört kişisel çalışma alanı davranışı korunmalı.');
assert(block.includes('data-profile-logout')&&block.includes('global.cikisYap?.()'),'Oturum kapatma davranışı korunmalı.');
for(const token of ['data-profile-password-card','data-profile-password-open','data-password-current','data-password-new','data-password-repeat','global.kendiSifremiDegistir(current,next)','next.length<6','next!==repeat'])assert(feature.includes(token),`Profil şifre değiştirme sözleşmesi eksik: ${token}`);
assert(feature.includes('Mevcut şifreniz hatalı.')&&feature.includes('Şifreniz başarıyla değiştirildi.'),'Şifre değiştirme hata/başarı geri bildirimi bulunmalı.');
assert(!feature.includes('db.collection(')&&!feature.includes('firebase.firestore('),'Profil güvenliği eklentisi doğrudan Firestore kullanmamalı.');
assert(firebaseInit.includes("script.src='js/core/login-security.js?v=885'"),'Profil güvenliği çekirdek bootstrap üzerinden yüklenmeli.');
assert(sw.includes("const CACHE_ADI='oy-cache-v885'")&&sw.includes("'./js/core/login-security.js?v=885'"),'Profil güvenliği PWA cache içinde olmalı.');
console.log('Profil sayfası + güvenli şifre değiştirme sözleşmesi başarılı.');
