const fs=require('fs');
const assert=require('assert');
const ui=fs.readFileSync('js/core/shell-ui.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const start=ui.indexOf('const SEARCH_CATEGORIES=');
const end=ui.indexOf('\nfunction menuLayerOpen',start);
assert(start>=0&&end>start,'Arama sayfası bloğu bulunmalı.');
const block=ui.slice(start,end);
for(const key of ["['all','Tümü']","['teacher','👩‍🏫 Öğretmen']","['student','👨‍🎓 Öğrenci']","['staff','🧑‍💼 Personel']","['service','🚌 Servis']","['note','📝 Not']"])assert(block.includes(key),`Arama kategorisi eksik: ${key}`);
for(const forbidden of ["['document'","['chart'","arr('evrakTakibi')",'SEARCH_CHART_TYPES','Yıllık / BEP Planı','Zümre · Zümre'])assert(!block.includes(forbidden),`Evrak/doküman/çizelge arama kaynağı geri dönmemeli: ${forbidden}`);
assert(block.includes('Öğretmen, öğrenci, personel, servis ve notlarda hızlı arama yapın.'),'Arama açıklaması yalnız desteklenen kayıtları anlatmalı.');
assert(block.includes('placeholder="İsim, sınıf, telefon veya servis ara…"'),'Mobil arama placeholderı kısa ve taşmasız olmalı.');
assert(block.includes("state.category!=='all'")&&block.includes('ka-search-empty--idle'),'Boş açılışta tüm veriler dökülmemeli; arama niyeti beklenmeli.');
assert(block.includes('data-search-clear')&&block.includes('setSearchCategory(root,\'student\')'),'Temizleme kontrolü ve öğrenci filtrelerinin kategori senkronu korunmalı.');
for(const token of ['.ka-search-page{width:100%;max-width:760px','.ka-search-box{width:100%;min-height:54px','.ka-search-box>svg{position:static','.ka-search-filter-options{min-width:0;display:flex;flex-wrap:wrap','.ka-search-result{--ka-search-accent:','.ka-search-empty{min-height:150px'])assert(design.includes(token),`Yeni arama tasarım sözleşmesi eksik: ${token}`);
assert(!design.includes('.ka-search-box svg{position:absolute'),'Arama ikonu placeholder üstüne binen mutlak konuma dönmemeli.');
assert(index.includes('css/design-system.css?v=866'),'Arama tasarımı güncel merkezi CSS sürümüyle yüklenmeli.');
assert(sw.includes("const CACHE_ADI='oy-cache-v866'")&&sw.includes('./css/design-system.css?v=866'),'Yeni arama tasarımı PWA cache sürümüyle yayınlanmalı.');
console.log('Arama sayfası sade veri kapsamı + mobil düzen sözleşmesi başarılı.');
