const fs = require('fs');
const assert = require('assert');
const sw = fs.readFileSync('service-worker.js', 'utf8');
assert(sw.includes("const CACHE_ADI = 'oy-cache-v445'"), 'Service Worker cache sürümü v445 olmalı.');
for (const f of ['./index.html','./css/styles.css','./js/app.js','./js/ui-stability-fixes.js','./js/dashboard-mobile-v4.js','./js/dashboard-mobile-v4-polish.js','./js/dashboard-card-count-fix.js','./js/dashboard-mobile-v4-hotfix.js','./js/role-ui-hardening.js']) assert(sw.includes(`'${f}'`), `${f} precache içinde kalmalı.`);
const liste=sw.slice(sw.indexOf('const ONBELLEGE_ALINACAKLAR'),sw.indexOf("self.addEventListener('install'"));
for(const agir of ['./optik/index.html','./optik/js/app.js','xlsx.full.min.js','exceljs.min.js','pdf.min.js','mammoth.browser.min.js','leaflet.js'])assert(!liste.includes(agir),`${agir} ilk kurulum precache listesinden çıkarılmalı.`);
assert(sw.includes('fetch(event.request)'),'Ağ yüklemesi devam etmeli.');
assert(sw.includes('cache.put(event.request,copy)'),'Başarılı GET kaynakları runtime-cache edilmeli.');
assert(sw.includes('caches.match(event.request)'),'Çevrimdışı cache fallback kullanılmalı.');
console.log('Service Worker precache performans smoke testleri başarılı.');
