const fs=require('fs');
const assert=require('assert');
const settings=fs.readFileSync('js/modules/settings.js','utf8');
const runtime=fs.readFileSync('js/core/platform/mobile-runtime-fixes.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const index=fs.readFileSync('index.html','utf8');
new Function(settings);new Function(runtime);
assert(settings.includes("['app-update','Güncellemeleri Kontrol Et'"),'Güncelleme kontrolü canonical Settings menüsünde değil.');
assert(settings.includes('data-app-update-settings'),'Canonical güncelleme butonu eksik.');
assert(!runtime.includes('new MutationObserver(injectSettingsAction)'),'Güncelleme satırı MutationObserver ile enjekte edilmemeli.');
assert(runtime.includes('status.textContent!==next'),'Sürüm durum metni aynı değerle DOM mutasyonu üretmemeli.');
assert(settings.includes('schoolFormDirty')&&settings.includes('captureSchoolDraft'),'Okul bilgileri taslak koruması eksik.');
assert(settings.includes("active==='school'&&schoolFormDirty&&schoolFieldFocused()"),'Odaktaki okul formu arka plan renderından korunmuyor.');
assert(settings.includes('data-admin-note-add>+ Not Ekle'),'İdari Notlar ekleme butonu eksik.');
assert(css.includes('.ka-admin-savebar{position:static'),'İdari kaydet çubuğu Not Ekle butonunu örtebilir.');
const cacheMatch=sw.match(/const CACHE_ADI='oy-cache-v(\d+)'/);
assert(cacheMatch&&Number(cacheMatch[1])>=912,'Service worker cache sürümü güncellenmedi.');
assert(index.includes('css/design-system.css?v=912')&&sw.includes("'./css/design-system.css?v=912'"),'Index ve service worker design-system sürümü aynı değil.');
console.log('Android Ayarlar donma, okul adresi taslak ve idari not görünürlük sözleşmesi başarılı.');
