const fs=require('fs');
const assert=require('assert');
const service=fs.readFileSync('js/modules/teacher-list.js','utf8');
const firebase=fs.readFileSync('js/firebase-init.js','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');
const shell=fs.readFileSync('js/core/shell-ui.js','utf8');
const build=fs.readFileSync('scripts/build-client-bundles.mjs','utf8');
new Function(service);
for(const api of ['OgretmenListeRepository','OgretmenListeService','DeviceData','ogretmenListeSablon','ogretmenListeKayit','OgretmenListeUI']) assert(service.includes(api),`Öğretmen liste servisi ${api} sözleşmesini korumalı.`);
for(const forbidden of ['db.collection','onSnapshot','localStorage','<style']) assert(!service.includes(forbidden),`Öğretmen liste modülü doğrudan ${forbidden} kullanmamalı.`);
assert(service.includes("SyncEngine.register('ogretmenListeSablon'"),'Şablon koleksiyonu SyncEngine ile kaydedilmeli.');
assert(service.includes("SyncEngine.register('ogretmenListeKayit'"),'Çizelge koleksiyonu SyncEngine ile kaydedilmeli.');
assert(service.includes("q.where('ogretmenId','==',tid)"),'Firestore arka plan senkronu öğretmen sahiplik filtresi kullanmalı.');
assert(service.includes("SyncEngine.localHydrate(['ogretmenListeSablon','ogretmenListeKayit'])"),'İlk görünüm cihaz verisinden hydrate edilmeli.');
assert(service.includes("device().set('ogretmenListeSablon',COL.ogretmenListeSablon"),'Şablon yazması DeviceData üzerinden olmalı.');
assert(service.includes("device().add('ogretmenListeKayit',COL.ogretmenListeKayit"),'Yeni çizelge DeviceData üzerinden olmalı.');
assert(service.includes("device().update('ogretmenListeKayit',COL.ogretmenListeKayit"),'Çizelge güncellemesi DeviceData üzerinden olmalı.');
assert(service.includes("device().remove('ogretmenListeKayit',COL.ogretmenListeKayit"),'Çizelge silme DeviceData/tombstone üzerinden olmalı.');
assert(service.includes('sahip-degil'),'Yerel servis sahiplik kontrolünü korumalı.');
for(const key of ['siraNo','ogrenciAdi','ogrenciNo','cinsiyet','veliAdi','yakinlik','telefon1','telefon2','adres','servisAdi','kulupAdi','notlar']) assert(service.includes(`key:'${key}'`),`Legacy öğretmen liste sütunu korunmalı: ${key}`);
assert(service.includes("data('veliler').filter(v=>v.sinifId===sinifId||v.sinifId===sinifAdi)"),'Öğrenci roster kaynağı mevcut veliler/sinifId sözleşmesini korumalı.');
for(const hook of ['data-teacher-list-new','data-teacher-list-open','data-teacher-list-column','data-teacher-list-custom-add','data-teacher-list-cell','data-teacher-list-save','data-teacher-list-template-save','data-teacher-list-header','data-teacher-list-orientation','data-teacher-list-report','data-teacher-list-excel','data-teacher-list-move','data-teacher-list-align','data-teacher-list-width']) assert(service.includes(hook),`V2 öğretmen liste editörü ${hook} davranışını içermeli.`);
for(const fn of ['moveColumn','cycleAlign','setWidth','widthFor','alignmentFor']) assert(service.includes(`function ${fn}`),`Sütun yönetimi fonksiyonu korunmalı: ${fn}`);
for(const field of ['secilenKeyler','sutunSirasi','ozelSutunlar','satirlar','sutunGenislikleri','sutunHizalama','baslikBilgisi']) assert(service.includes(field),`Eski kayıt şeması korunmalı: ${field}`);
for(const header of ['okulAdiGoster','egitimYiliGoster','altBaslikGoster','ogretmenGoster','ogretmenBransGoster','mudurGoster','mudurUnvanGoster','yon']) assert(service.includes(header),`Başlık/imza çıktı ayarı korunmalı: ${header}`);
assert(service.includes("Math.max(72,Math.min(420"),'Sütun genişliği güvenli mobil/masaüstü aralığında sınırlandırılmalı.');
assert(service.includes("next={left:'center',center:'right',right:'left'}"),'Sütun hizalama döngüsü sol/orta/sağ olmalı.');
assert(service.includes('ReportEngine.printReport'),'A4/PDF çıktısı ortak ReportEngine üzerinden açılmalı.');
assert(service.includes("width:${widthFor(c.key)}px"),'A4 çıktısı kaydedilmiş sütun genişliğini kullanmalı.');
assert(service.includes("bs.yon==='landscape'?'yatay':'dikey'"),'Legacy portrait/landscape tercihi ReportEngine yönüne çevrilmeli.');
assert(service.includes('exceljs/4.4.0/exceljs.min.js'),'ExcelJS yalnız dışa aktarma sırasında lazy-load edilmeli.');
assert(service.includes('uygulamaDosyaKaydet'),'Android Excel dışa aktarma ortak native kaydetme yardımcısını kullanmalı.');
assert(service.includes('wb.xlsx.writeBuffer()'),'Excel çalışma kitabı istemci tarafında üretilmeli.');
assert(service.includes('Math.round(widthFor(c.key)/7)'),'Excel çıktısı kaydedilmiş sütun genişliğini kullanmalı.');
assert(firebase.includes("ogretmenListeSablon:'oy_ogretmenListeSablon'")&&firebase.includes("ogretmenListeKayit:'oy_ogretmenListeKayit'"),'Merkezi COL haritası öğretmen liste koleksiyonlarını korumalı.');
assert(!loader.match(/define\('tools',\[[^\]]*teacher-list\.js/)&&!loader.match(/define\('tools',\[[^\]]*map-ui\.js/),'Tools varsayılan bundle rota-özel öğretmen liste ve harita companionlarını eager yüklememeli.');
assert(shell.includes("if(['student-list','homework','grades'].includes(page))files.push('js/modules/teacher-list.js')")&&shell.includes("if(page==='map')files.push('js/modules/map-ui.js')"),'Shell öğretmen liste ve harita companionlarını ilgili rotalarda lazy-load etmeli.');
assert(!loader.includes("'js/harita.js'"),'Emekli root harita yolu Tools loader a geri dönmemeli.');
assert(/'tools\.js':\[[^\]]*'js\/modules\/teacher-list\.js'[^\]]*\]/.test(build),'Production tools bundle öğretmen liste servisini içermeli.');
console.log('Öğretmen liste local-first servis + V2 editör + sütun/çıktı sözleşmesi başarılı.');
