const fs=require('fs');
const assert=require('assert');
const transport=fs.readFileSync('js/modules/transport.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(transport);
for(const token of ['function busElementLayoutUsable','function elementAssignmentsToLegacy','busElementLayoutUsable(raw)','data-bus-classic-shell','ka-bus-classic-stats','ka-bus-template-grid','data-bus-row-add','data-bus-row-remove','data-bus-report'])assert(transport.includes(token),`Eski oturma paritesi eksik: ${token}`);
assert(transport.includes("if(sb==='ozel'&&raw.length)"),'Özel tasarım ham yerleşimi korunmalı.');
assert(transport.includes('assignments=Array.isArray(plan?.koltuklar)&&plan.koltuklar.length?plan.koltuklar:elementAssignmentsToLegacy(raw)'),'Bozuk element yerleşiminde öğrenci atamaları kaybolmamalı.');
assert(!transport.includes('<div class="ka-bus-cabin ka-bus-classic-shell">'),'Klasik araç şeması eski generic cabin sınıfıyla çakışmamalı.');
for(const token of ['Servis Oturma — eski ekran birebir düzeltme v3','.ka-bus-template-card.is-active','background:#e72b2f!important','.ka-bus-classic-stage{','overflow:visible!important','.ka-bus-classic-shell{','min-width:0!important'])assert(css.includes(token),`Klasik mobil stil eksik: ${token}`);
assert(css.includes('@media(max-width:390px)')&&css.includes('grid-template-columns:repeat(2,minmax(0,1fr))!important'),'Dar telefonda araç tipleri iki sütunda kalmalı.');
assert(css.includes('.ka-bus-classic-stats div:last-child')&&css.includes('grid-column:1!important'),'Doluluk eski ekrandaki gibi ikinci satır ilk hücrede olmalı.');
assert(loader.includes("define('transport',['js/modules/report-engine.js','js/modules/transport.js?v=892'])"),'Transport canonical lazy-loader sözleşmesini korumalı.');
assert(index.includes('css/design-system.css?v=892')&&index.includes('js/app-loader.js?v=892'),'Index yeni oturma düzenini zorunlu yüklemeli.');
assert(sw.includes("CACHE_ADI='oy-cache-v892'")&&sw.includes("./js/modules/transport.js?v=892"),'Service Worker yeni transport paketini önbelleğe almalı.');
for(const forbidden of ['db.collection','firebase.firestore','localStorage.setItem','localStorage.removeItem'])assert(!transport.includes(forbidden),`Local-first sınırı ihlal edildi: ${forbidden}`);
console.log('Servis oturma eski ekran mobil paritesi başarılı.');
