const fs=require('fs');
const assert=require('assert');
const {cacheVersion,assetVersion}=require('./helpers/version-contract');
const css=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const js=fs.readFileSync('js/modules/transport.js','utf8');
for(const token of ['sbe-backdrop','sbe-modal','sbe-layout','sbe-students','sbe-work','sbe-toolbar','sbe-stage','sbe-stage-inner','sbe-canvas-scale','sbe-canvas','sbe-object','sbe-seat','function renderBusEditor'])assert(js.includes(token)||css.includes('.'+token),`Yeni servis oturma editörü sözleşmesi eksik: ${token}`);
for(const token of ['SBE_W=900','SBE_H=1320','SBE_TYPES','sbeNormalize','sbeCollision','sbeUndo','sbeRedo','sbeAlign','sbePointer','sbeAdd'])assert(js.includes(token),`Nesne tabanlı servis editörü altyapısı eksik: ${token}`);
assert(assetVersion(index,'css/design-system.css')>=893,'Index servis oturma CSS paketini yüklemeli.');
assert(cacheVersion(sw)>=980&&assetVersion(sw,'css/design-system.css')>=893,'Service Worker servis oturma CSS paketini önbelleğe almalı.');
console.log('Servis oturma yeni object-based tasarım sözleşmesi başarılı.');
