const fs=require('fs');
const assert=require('assert');
const transport=fs.readFileSync('js/modules/transport.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
new Function(transport);
for(const token of ['ka-bus-classic-shell','data-bus-seat-index','function openBusSeatPicker','data-bus-student','function assignBusStudent','data-bus-template','data-bus-layout-edit','Düzenlemeyi Aç','data-bus-row-add','Sıra Ekle','data-bus-row-remove','Sıra Sil','data-bus-seat-lock','Kilitli','data-bus-clear-all','Atamaları Temizle','data-bus-report','Rapor Al','Vazgeç','💾 Kaydet','function busPrintReport','ReportEngine.printReport'])assert(transport.includes(token),`Klasik servis oturma editörü paritesi eksik: ${token}`);
for(const token of ['.ka-bus-classic-modal','.ka-bus-classic-hero','.ka-bus-template-grid','.ka-bus-template-card','.ka-bus-classic-shell','.ka-bus-classic-driver','.ka-bus-classic-row','.ka-bus-seat.is-filled','.ka-bus-seat.is-reserved','.ka-bus-seat.is-locked','.ka-bus-classic-footer','.ka-bus-seat-picker'])assert(design.includes(token),`Merkezi klasik servis oturma stili eksik: ${token}`);
assert(!transport.includes('data-seat-index'),'Servis oturma planı koltuk başına dropdown kartlara geri dönmemeli.');
assert(!transport.includes('id="busTemplateSelect"'),'Araç seçimi eski ekrandaki kartlı şablon seçicisi olmalı.');
assert(transport.includes('editor={servisId,sablon,elements,editable:canEditBusSeats()}'),'Canonical editör state/permission sözleşmesi korunmalı.');
assert(transport.includes('window.ServisOturmaService.planElementsKaydet(servisId,sablon,elements,false)'),'Kayıt local-first canonical servis üzerinden yapılmalı.');
assert(transport.includes("if(!editor?.editable)return"),'Öğretmen salt-okunur davranışı korunmalı.');
for(const forbidden of ['db.collection','firebase.firestore','localStorage.setItem','localStorage.removeItem'])assert(!transport.includes(forbidden),`Servis oturma editörü yasaklı kalıcı katmana inmemeli: ${forbidden}`);
console.log('Klasik görsel servis oturma editörü parite kilidi başarılı.');
