const fs=require('fs');
const assert=require('assert');
const {cacheVersion,assetVersion}=require('./helpers/version-contract');
const transport=fs.readFileSync('js/modules/transport.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(transport);
for(const token of ['ka-bus-tool-grid','data-bus-row-add','data-bus-row-remove','data-bus-report','data-bus-clear-all'])assert(transport.includes(token),`Editör aracı eksik: ${token}`);
assert(transport.includes("b.textContent='Kaydedildi ✓'"),'Kaydet butonu sonsuz Kaydediliyor durumunda kalmamalı.');
assert(transport.includes('const task=window.ServisOturmaService.planElementsKaydet'),'Local-first kayıt görevi başlatılmalı.');
assert(transport.includes('setTimeout(()=>{closeEditor();try{render()}'),'Kayıt arka planda sürse bile editör kullanıcıyı kilitlememeli.');
for(const token of ['.ka-bus-grid-shell','.ka-bus-grid-table','.ka-bus-grid-cell','.ka-bus-grid-driver','overflow:auto'])assert(transport.includes(token)||css.includes(token),`Yeni servis oturma tablo editörü stili eksik: ${token}`);
assert(assetVersion(index,'css/design-system.css')>=893&&assetVersion(index,'js/app-loader.js')>=892,'Index yeni servis oturma paketini yüklemeli.');
assert((loader.includes("'js/modules/report-engine.js'")&&assetVersion(loader,'js/modules/transport.js')>=892),'Transport cache-bust sürümü güncel olmalı.');
assert(cacheVersion(sw)>=893&&assetVersion(sw,'js/modules/transport.js')>=892&&assetVersion(sw,'css/design-system.css')>=893,'Service Worker yeni servis oturma paketini önbelleğe almalı.');
console.log('Servis oturma editör hızlı erişim/kayıt/isim sığdırma testi başarılı.');
