const fs=require('fs');
const assert=require('assert');
const academic=fs.readFileSync('js/modules/academic.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const loader=fs.readFileSync('js/app-loader.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const start=academic.indexOf('function renderTrialCounter(');
const end=academic.indexOf('\nfunction openTrialCounter(',start);
assert(start>=0&&end>start,'renderTrialCounter bulunamadı.');
const renderBlock=academic.slice(start,end);
assert(renderBlock.includes("data-trial-counter-scroll"),'Sayaç görünümü kalıcı scroll owner üretmeli.');
assert(renderBlock.includes('replaceTrialCounterNode'),'Saniyelik tikler tüm overlay yerine dinamik sayaç parçalarını güncellemeli.');
assert(renderBlock.includes('forceStructure||!hasStructure'),'Tam overlay yalnız ilk açılışta veya bozuk yapı kurtarmasında kurulmalı.');
assert.strictEqual((renderBlock.match(/ov\.innerHTML=/g)||[]).length,1,'Sayaç renderer yalnız tek yapısal innerHTML yolu içermeli.');
assert(!renderBlock.includes('scrollTop'),'Scroll sorunu scrollTop kaydet/geri yükle yamasıyla çözülmemeli.');
for(const token of ['data-trial-counter-main','data-trial-counter-schedule','data-trial-counter-overview'])assert(academic.includes(token),`Dinamik sayaç slotu eksik: ${token}`);
assert(academic.includes("if(trialCounterId){renderTrialCounter();return}if(needsTick)render()"),'Overlay açıkken alttaki Academic liste her saniye yeniden render edilmemeli.');
assert(academic.includes('renderTrialCounter(true)'),'Sayaç ilk açılışta yapısal render istemeli.');
assert(index.includes('css/design-system.css?v=863')&&index.includes('js/app-loader.js?v=859'),'Üretim shell güncel cache-bust sürümünü kullanmalı.');
assert(loader.includes('js/modules/academic.js?v=838'),'Academic loader v838 kullanmalı.');
assert(sw.includes("const CACHE_ADI='oy-cache-v863'"),'Service Worker güncel cache sürümünü kullanmalı.');
console.log('Deneme sayacı scroll konumu kalıcı DOM owner ile stabil.');
