const fs=require('fs');
const assert=require('assert');
const settings=fs.readFileSync('js/modules/settings.js','utf8');
const auth=fs.readFileSync('js/auth.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const rules=fs.readFileSync('firestore.rules','utf8');
const prep=settings.slice(settings.indexOf('async function prepareLocal()'),settings.indexOf('function settingsDescription'));
assert(!prep.includes('defs.kullaniciIstatistikleri'),'Genel settings hazırlığı tüm istatistikleri yetkisiz kaydetmemeli; dedicated service kullanmalı.');
for(const token of ['function statisticsRows()','arr(\'kullanicilar\')','arr(\'kullaniciIstatistikleri\')','__hasStats','Henüz giriş yapmadı','function prepareStatisticsData(force=false)','window.IstatistikService.prepare(admin())','data-stat-refresh'])assert(settings.includes(token),`Admin istatistik sözleşmesi eksik: ${token}`);
assert(settings.includes("if(admin())await window.IstatistikService.prepare(true)"),'Admin görünümü tüm kullanıcı istatistiklerini hazırlamalı.');
assert(settings.includes("if(page==='statistics')void prepareStatisticsData(false)"),'İstatistik sayfası açılırken local-first senkron başlatılmalı.');
assert(auth.includes("if(preparing){await preparing;if(mode===wanted)return true;return prepare(all);}"),'Self hazırlığı sürerken admin all isteği kaybolmamalı.');
assert(!settings.includes('db.collection(')&&!settings.includes('firebase.firestore('),'Settings UI doğrudan Firestore kullanmamalı.');
for(const token of ['.ka-statistics-page{--ka-stat-hero-start:','.ka-statistics-summary{display:grid;grid-template-columns:repeat(2','.ka-statistics-user{min-width:0','.ka-statistics-metrics{','.ka-statistics-storage__body{','@media(max-width:390px)'])assert(design.includes(token),`Yeni kullanıcı istatistik tasarımı eksik: ${token}`);
assert(index.includes('css/design-system.css?v=868'),'Yeni istatistik tasarımı merkezi CSS v867 ile yüklenmeli.');
assert(sw.includes("const CACHE_ADI='oy-cache-v868'")&&sw.includes('./css/design-system.css?v=868'),'PWA cache v867 olmalı.');
assert(rules.includes('match /oy_kullaniciIstatistikleri/{uid}')&&rules.includes('allow read: if adminMi() || (girisYapmis() && request.auth.uid == uid);'),'Firestore admin tüm istatistikleri okuyabilmeli.');
console.log('Admin tüm kullanıcı istatistikleri + mobil tasarım sözleşmesi başarılı.');
