const fs=require('fs');
const assert=require('assert');
const settings=fs.readFileSync('js/modules/settings.js','utf8');
const auth=fs.readFileSync('js/auth.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const feature=fs.readFileSync('js/core/login-security.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const rules=fs.readFileSync('firestore.rules','utf8');
const prep=settings.slice(settings.indexOf('async function prepareLocal()'),settings.indexOf('function settingsDescription'));
assert(!prep.includes('defs.kullaniciIstatistikleri'),'Genel settings hazırlığı tüm istatistikleri yetkisiz kaydetmemeli; dedicated service kullanmalı.');
for(const token of ['function statisticsRows()','arr(\'kullanicilar\')','arr(\'kullaniciIstatistikleri\')','__hasStats','Henüz giriş yapmadı','function prepareStatisticsData(force=false)','window.IstatistikService.prepare(admin())','data-stat-refresh'])assert(settings.includes(token),`Admin istatistik sözleşmesi eksik: ${token}`);
assert(settings.includes("if(admin())await window.IstatistikService.prepare(true)"),'Admin görünümü tüm kullanıcı istatistiklerini hazırlamalı.');
assert(settings.includes("if(page==='statistics')void prepareStatisticsData(false)"),'İstatistik sayfası açılırken local-first senkron başlatılmalı.');
assert(auth.includes("if(preparing){await preparing;if(mode===wanted)return true;return prepare(all);}"),'Self hazırlığı sürerken admin all isteği kaybolmamalı.');
assert(!settings.includes('db.collection(')&&!settings.includes('firebase.firestore('),'Settings UI doğrudan Firestore kullanmamalı.');
for(const token of ['.ka-statistics-page{--ka-stat-hero-start:','.ka-statistics-summary{display:grid;grid-template-columns:repeat(2','.ka-statistics-user{min-width:0','.ka-statistics-metrics{','.ka-statistics-storage__body{','@media(max-width:390px)'])assert(design.includes(token),`Kullanıcı istatistik tasarımı eksik: ${token}`);
for(const token of ["const STATS_TYPE='kullaniciIstatistikleri'",'girisKayitlari','sonGirisKonumu','navigator.geolocation.getCurrentPosition','platform()','data-login-location-section','data-login-location-map','Giriş Konumları ve Platformlar','https://{s}.tile.openstreetmap.org','global.IstatistikService?.prepare?.(true)'])assert(feature.includes(token),`Giriş konumu/platform sözleşmesi eksik: ${token}`);
assert(feature.includes('if(!isAdmin())return;'),'Giriş konumu haritası yalnız admin görünümünde oluşturulmalı.');
assert(feature.includes('global.DeviceData.set(STATS_TYPE,global.COL.kullaniciIstatistikleri')&&feature.includes('{merge:true}'),'Giriş konumu mevcut local-first kullanıcı istatistik belgesine merge edilerek yazılmalı.');
assert(!feature.includes('db.collection(')&&!feature.includes('firebase.firestore('),'Giriş konumu özelliği doğrudan Firestore kullanmamalı.');
assert(rules.includes('match /oy_kullaniciIstatistikleri/{uid}')&&rules.includes('allow read: if adminMi() || (girisYapmis() && request.auth.uid == uid);'),'Firestore admin tüm istatistikleri okuyabilmeli.');
assert(sw.includes("const CACHE_ADI='oy-cache-v885'")&&sw.includes("'./js/core/login-security.js'"),'Giriş konumu özelliği offline shell içinde olmalı.');
console.log('Admin kullanıcı istatistikleri + giriş konumu/platform haritası sözleşmesi başarılı.');
