const fs=require('fs');
const assert=require('assert');
const loader=fs.readFileSync('js/ui-stability-fixes.js','utf8');
const home=fs.readFileSync('js/dashboard-home.js','utf8');
const web=fs.readFileSync('js/dashboard-v2-init.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');

assert(loader.includes("matchMedia('(max-width:1023px)')"));
assert(loader.includes('if(mobil)'));
assert(loader.includes('dashboard-home.js'));
assert(loader.includes('dashboard-home.css'));
assert(home.includes("matchMedia('(max-width:1023px)')"));
assert(home.includes('claimDashboardRenderer'));
assert(web.includes("matchMedia('(min-width:1024px)')"));
assert(web.includes('__KORUK_WEB_SHELL_INIT__'));
assert(!web.includes('oyDashboardMobilBilgiKartlariV3'));
assert(sw.includes("'./js/dashboard-home.js'"));
assert(sw.includes("'./css/dashboard-home.css'"));
assert(!sw.includes("'./css/dashboard-v2.css'"));
assert(!sw.includes("'./css/mobil-dashboard.css'"));
console.log('Web/mobil motor ayrımı testi başarılı.');
