const fs = require('fs');
const assert = require('assert');
const src = fs.readFileSync('js/yillik-plan.js', 'utf8');
assert(src.includes('YPL_A4_DIKEY_PX = 794'), 'A4 dikey genişliği bulunmalı.');
assert(src.includes('id="yplRaporBaslik"'), 'Önizleme tuvalinde rapor başlığı görünmeli.');
assert(src.includes('_yplOnizlemeBaslikHtml(tanim)'), 'Dosya/rapor başlığı önizlemede üretilmeli.');
assert(src.includes('id="yplYonYatay"') && src.includes('id="yplYonDikey"'), 'Yatay ve dikey görünüm kontrolleri bulunmalı.');
assert(src.includes("tuval.style.transform = `scale(${olcek})`"), 'Zoom yalnız plan tuvaline transform ile uygulanmalı.');
assert(!src.includes('tuval.style.zoom = _yplTabanZoom * _yplManuelZoom'), 'Eski CSS zoom geri gelmemeli.');
assert(src.includes('mevcutGenislik / _yplSayfaGenisligi()'), 'Sığdır seçili yönün genişliğine göre hesaplanmalı.');
assert(src.includes('yillikPlaniYazdir(planId, genislik, _yplMevcutFontPx, _yplSayfaYonu)'), 'Yazdırma seçili sayfa yönünü kullanmalı.');
assert(src.includes('id="yplZoomYuzde"'), 'Zoom yüzdesi görünmeli.');
console.log('Yıllık plan önizleme smoke testleri başarılı.');
