from pathlib import Path
import re
D=Path('js/modules/dashboard.js');C=Path('css/design-system.css');T=Path('tests/dashboard-card-routes-smoke.test.js');S=Path('service-worker.js')
d=D.read_text(encoding='utf-8')
ps=d.find('function pollSection(){'); pe=d.find('\nfunction newsSection',ps)
if ps<0 or pe<0: raise SystemExit('poll boundaries missing')
poll=r'''function pollSection(){const list=arr('anketler').filter(x=>x.aktif!==false&&x.arsivlendi!==true&&!x.kapali).slice(0,2);if(!list.length)return'';const chart='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-7"/></svg>';return `<div class="kh-dynamic" data-home-section="polls">${list.map(x=>`<button type="button" class="kh-dyn-item" data-dash-route="communication" data-dash-page="polls" data-dash-title="Anketler"><span class="kh-dyn-icon">${chart}</span><span class="kh-row-main"><b>${esc(x.baslik||x.soru||'Aktif anket')}</b><small>${esc(x.aciklama||'Katılım bekleniyor')}</small></span><span class="kh-chip">ANKET</span></button>`).join('')}</div>`}'''
d=d[:ps]+poll+d[pe:]
ts=d.find('function trialCounterSection(){'); te=d.find('\nfunction refreshTrialTimers',ts)
if ts<0 or te<0: raise SystemExit('trial boundaries missing')
trial=r'''function trialCounterSection(){const list=arr('denemeSinavlari').filter(x=>x?.sayacDurumu?.aktif===true).sort((a,b)=>String(a.tarih||'').localeCompare(String(b.tarih||''))).slice(0,3);if(!list.length)return'';const exam='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 2h9l3 3v17H6z"/><path d="M14 2v4h4M9 11h6M9 15h6"/></svg>';return `<div class="kh-dynamic" data-home-section="trial-counter">${list.map(x=>{const st=trialTimerState(x);return `<button type="button" class="kh-dyn-item" data-dash-route="academic" data-dash-page="trial" data-dash-title="Deneme Sınavları"><span class="kh-dyn-icon">${exam}</span><span class="kh-row-main"><b>${esc(x.ad||x.baslik||'Deneme sınavı')}</b><small>${esc([x.sinflar||x.siniflar,x.oturumTuru,st.label].filter(Boolean).join(' · '))}</small></span><span class="kh-chip is-live" data-dash-trial-timer="${esc(x.id)}">${esc(trialFmt(st.remaining))}</span></button>`}).join('')}</div>`}'''
d=d[:ts]+trial+d[te:]
D.write_text(d,encoding='utf-8')
c=C.read_text(encoding='utf-8');mark='/* LEGACY DASHBOARD DYNAMIC ITEMS — REFERENCE PORT */'
if mark not in c:c+='''\n\n/* LEGACY DASHBOARD DYNAMIC ITEMS — REFERENCE PORT */\n.ka-home .kh-dynamic{display:flex;flex-direction:column;gap:8px}\n.ka-home .kh-dynamic:empty{display:none}\n.ka-home .kh-dyn-item{width:100%;display:grid;grid-template-columns:40px minmax(0,1fr) auto;gap:10px;align-items:center;padding:11px 12px;border-radius:18px;border:1px solid var(--ka-border);background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm);color:var(--ka-text);text-align:left;font:inherit;cursor:pointer}\n.ka-home .kh-dyn-icon{width:40px;height:40px;display:grid;place-items:center;border-radius:13px;background:var(--ka-primary-soft);color:var(--ka-primary)}\n.ka-home .kh-dyn-icon svg{width:20px;height:20px}\n.ka-home .kh-dyn-item .kh-chip.is-live{background:color-mix(in srgb,var(--ka-danger) 12%,var(--ka-card-bg));color:var(--ka-danger);font-variant-numeric:tabular-nums}\n'''
C.write_text(c,encoding='utf-8')
t=T.read_text(encoding='utf-8');chk='''\nassert(dash.includes('data-home-section="polls"')&&dash.includes('class="kh-dyn-item"')&&dash.includes('>ANKET</span>'),'Aktif Anketler referans kh-dynamic/kh-dyn-item yüzeyini kullanmalı.');\nassert(dash.includes('data-home-section="trial-counter"')&&dash.includes('data-dash-trial-timer')&&dash.includes('data-dash-page="trial"'),'Aktif deneme/sayaç referans dinamik kart geometrisini ve gerçek sayaç davranışını korumalı.');\nassert(!dash.includes("section('Aktif Anketler','📊','polls'")&&!dash.includes("section('Deneme / Sayaç','⏱️','trial-counter'"),'Geçici section tabanlı anket/deneme rendererları geri dönmemeli.');\nassert(css.includes('LEGACY DASHBOARD DYNAMIC ITEMS — REFERENCE PORT')&&css.includes('.ka-home .kh-dyn-item'),'Dinamik kart görünümü merkezi design-system içinde kalmalı.');\n'''
if 'LEGACY DASHBOARD DYNAMIC ITEMS — REFERENCE PORT' not in t:t+=chk
T.write_text(t,encoding='utf-8')
s=S.read_text(encoding='utf-8');m=re.search(r"const CACHE_ADI='oy-cache-v(\d+)'",s)
if not m: raise SystemExit('cache missing')
s=s[:m.start(1)]+str(int(m.group(1))+1)+s[m.end(1):];S.write_text(s,encoding='utf-8')
# execute after workflow registration
