from pathlib import Path
p=Path('js/modules/academic.js');s=p.read_text(encoding='utf-8')
tp=Path('tests/academic-separate-pages.test.js');test=tp.read_text(encoding='utf-8')

# Add Word action next to the existing real admin actions.
old='<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-plan-headings>🏷️ Ana Başlıklar</button><button class="ka-btn ka-btn--sm" type="button" data-plan-new>＋ Yeni Plan Tanımı</button>'
new='<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-plan-headings>🏷️ Ana Başlıklar</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-plan-word>📄 Word’den İçe Aktar</button><button class="ka-btn ka-btn--sm" type="button" data-plan-new>＋ Yeni Plan Tanımı</button>'
if old not in s: raise SystemExit('Annual plan action bar bulunamadı')
s=s.replace(old,new,1)

# Add print action to the weekly detail header.
old='<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-plan-current>Bu Hafta</button></div><div class="ka-plan-week__date">'
new='<div class="ka-row"><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-plan-print>🖨</button><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-plan-current>Bu Hafta</button></div></div><div class="ka-plan-week__date">'
if old not in s: raise SystemExit('Annual plan detail header bulunamadı')
s=s.replace(old,new,1)

anchor='function openPlanHeadings(){'
i=s.find(anchor)
if i<0: raise SystemExit('Admin functions anchor bulunamadı')
imp=r'''let planImportRows=null;
async function ensurePlanWordReader(){if(globalThis.mammoth)return globalThis.mammoth;await globalThis.AppLoader?.loadScript?.('https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.6.0/mammoth.browser.min.js');if(!globalThis.mammoth)throw new Error('Word okuma kütüphanesi yüklenemedi.');return globalThis.mammoth}
function renderPlanImportMapping(ov){const area=ov.querySelector('[data-plan-import-map]');if(!area||!planImportRows?.length)return;const heads=planImportRows[0],sample=planImportRows[1]||[],pool=arr('yillikPlanBasliklari').slice().sort((a,b)=>Number(a.sira||0)-Number(b.sira||0));area.innerHTML=`<p class="ka-muted">${heads.length} sütun, ${Math.max(0,planImportRows.length-1)} veri satırı bulundu. Her sütunun karşılığını seçin.</p><div class="ka-plan-import-map">${heads.map((h,idx)=>`<div class="ka-plan-import-column"><strong>${esc(h||'(başlıksız sütun)')}</strong><small>örn: ${esc(String(sample[idx]||'').slice(0,80))}</small><select data-plan-import-match="${idx}"><option value="">— Yoksay —</option><optgroup label="Sistem Alanları"><option value="sys:ay" ${idx===0?'selected':''}>Ay</option><option value="sys:hafta" ${idx===1?'selected':''}>Hafta</option><option value="sys:saat" ${idx===2?'selected':''}>Saat</option></optgroup><optgroup label="Ana Başlıklar">${pool.map(x=>`<option value="heading:${esc(x.id)}">${esc(x.ad||'Başlık')}</option>`).join('')}<option value="new">＋ Yeni Başlık Oluştur</option></optgroup></select><input data-plan-import-new="${idx}" hidden placeholder="Yeni başlık adı"></div>`).join('')}</div>`;area.querySelectorAll('[data-plan-import-match]').forEach(sel=>sel.addEventListener('change',()=>{const input=area.querySelector(`[data-plan-import-new="${sel.dataset.planImportMatch}"]`);if(input)input.hidden=sel.value!=='new'}));ov.querySelector('[data-save]').disabled=false}
async function readPlanWordFile(file,ov){if(!file)return;const area=ov.querySelector('[data-plan-import-map]');area.innerHTML='<div class="ka-muted">Dosya okunuyor…</div>';try{const reader=await ensurePlanWordReader(),result=await reader.convertToHtml({arrayBuffer:await file.arrayBuffer()}),tmp=document.createElement('div');tmp.innerHTML=result.value;const tables=[...tmp.querySelectorAll('table')].sort((a,b)=>b.querySelectorAll('tr').length-a.querySelectorAll('tr').length);if(!tables.length)throw new Error('Bu Word dosyasında tablo bulunamadı.');planImportRows=[...tables[0].querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>String(td.textContent||'').replace(/\s+/g,' ').replace(/^[#=]+/,'').trim()));if(planImportRows.length<2)throw new Error('Yıllık plan tablosunda veri satırı bulunamadı.');renderPlanImportMapping(ov)}catch(e){planImportRows=null;area.innerHTML=`<div class="ka-empty">${esc(e?.message||'Dosya okunamadı.')}</div>`}}
async function savePlanWordImport(ov){const lesson=ov.querySelector('[data-plan-import-lesson]').value.trim(),level=Number(ov.querySelector('[data-plan-import-level]').value),year=ov.querySelector('[data-plan-import-year]').value.trim();if(!lesson)return toast?.('Ders adı zorunludur.');if(!planImportRows?.length)return toast?.('Önce Word dosyasını seçin.');const mapping={},newHeads=[];ov.querySelectorAll('[data-plan-import-match]').forEach(sel=>{const idx=Number(sel.dataset.planImportMatch),v=sel.value;if(!v)return;if(v==='new'){const ad=ov.querySelector(`[data-plan-import-new="${idx}"]`)?.value.trim();if(ad)newHeads.push({idx,ad})}else if(v.startsWith('sys:'))mapping[idx]={type:'sys',value:v.slice(4)};else if(v.startsWith('heading:'))mapping[idx]={type:'heading',value:v.slice(8)}});try{for(const h of newHeads){const ref=await YillikPlanService.baslikEkle({ad:h.ad,sira:arr('yillikPlanBasliklari').length});mapping[h.idx]={type:'heading',value:ref.id}}const columns=[];Object.values(mapping).forEach(x=>{if(x.type==='heading'&&!columns.includes(x.value))columns.push(x.value)});const rows=planImportRows.slice(1).filter(r=>r.some(Boolean)).map(r=>{const row={ay:'',hafta:'',saat:'',degerler:{}};Object.entries(mapping).forEach(([idx,m])=>{const text=String(r[Number(idx)]||'').trim();if(!text)return;if(m.type==='sys')row[m.value]=text;else row.degerler[m.value]=text});return row});await YillikPlanService.tanimEkle({dersAdi:lesson,seviye:level,egitimOgretimYili:year,sutunlar:columns,satirlar:rows});ov.remove();planImportRows=null;toast?.(`İçe aktarıldı — ${rows.length} hafta.`)}catch(e){toast?.(e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':e?.message||'İçe aktarma başarısız.')}}
function openPlanWordImport(){planImportRows=null;const year=`${new Date().getFullYear()}-${new Date().getFullYear()+1}`,ov=modal('📄 Word’den İçe Aktar',`<div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Ders Adı</span><input data-plan-import-lesson placeholder="Örn: Fen Bilimleri"></label><label class="ka-field"><span class="ka-field__label">Sınıf Seviyesi</span><select data-plan-import-level>${[1,2,3,4,5,6,7,8].map(x=>`<option value="${x}" ${x===6?'selected':''}>${x}. Sınıf</option>`).join('')}</select></label></div><label class="ka-field"><span class="ka-field__label">Eğitim-Öğretim Yılı</span><input data-plan-import-year value="${esc(year)}"></label><label class="ka-field"><span class="ka-field__label">Yıllık Plan Dosyası (.docx)</span><input data-plan-import-file type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></label><div data-plan-import-map></div>`);ov.querySelector('[data-save]').disabled=true;ov.querySelector('[data-save]').textContent='Sütunları Eşleştirdim, Kaydet';ov.querySelector('[data-plan-import-file]').addEventListener('change',e=>readPlanWordFile(e.target.files?.[0],ov));ov.querySelector('[data-save]').onclick=()=>savePlanWordImport(ov)}
function printAnnualPlan(){const p=arr('yillikPlanTanimlari').find(x=>x.id===planView.planId);if(!p||!globalThis.ReportEngine)return;const heads=p.sutunlar||[],rows=(p.satirlar||[]).map(r=>`<tr><td>${esc(r.ay||'')}</td><td>${esc(r.hafta||'')}</td><td>${esc(r.saat||'')}</td>${heads.map(id=>`<td>${esc(r.degerler?.[id]||'').replace(/\n/g,'<br>')}</td>`).join('')}</tr>`).join(''),body=`<h1>${esc(p.dersAdi||'Yıllık Plan')} — ${esc(p.seviye?`${p.seviye}. Sınıf`:'')}</h1><p>${esc(p.egitimOgretimYili||'')}</p><table><thead><tr><th>Ay</th><th>Hafta</th><th>Saat</th>${heads.map(id=>`<th>${esc(planHeadingName(id))}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>`;globalThis.ReportEngine.printReport(`${p.dersAdi||'Yıllık Plan'} — ${p.seviye||''}. Sınıf`,body,{fileName:`Yillik_Plan_${p.dersAdi||'plan'}_${p.seviye||''}`,yon:'landscape'})}
'''
s=s[:i]+imp+s[i:]

old="out.querySelector('[data-plan-headings]')?.addEventListener('click',openPlanHeadings);out.querySelector('[data-plan-new]')?.addEventListener('click',()=>openPlanDefinition(''));"
new="out.querySelector('[data-plan-headings]')?.addEventListener('click',openPlanHeadings);out.querySelector('[data-plan-word]')?.addEventListener('click',openPlanWordImport);out.querySelector('[data-plan-new]')?.addEventListener('click',()=>openPlanDefinition(''));out.querySelector('[data-plan-print]')?.addEventListener('click',printAnnualPlan);"
if old not in s: raise SystemExit('bindPlans admin actions bulunamadı')
s=s.replace(old,new,1)

needle="for(const token of ['data-plan-headings','data-plan-new','data-plan-edit','openPlanHeadings','openPlanDefinition','openPlanRows','openPlanRowEditor','baslikEkle','baslikSil','tanimEkle','tanimGuncelle','tanimSil']) assert(academic.includes(token),`Yıllık Plan yönetim sözleşmesi eksik: ${token}`);"
if needle not in test: raise SystemExit('Annual admin test anchor bulunamadı')
extra=needle+"\nfor(const token of ['data-plan-word','openPlanWordImport','ensurePlanWordReader','mammoth.browser.min.js','data-plan-import-match','printAnnualPlan','ReportEngine.printReport']) assert(academic.includes(token),`Yıllık Plan Word/çıktı sözleşmesi eksik: ${token}`);\nassert(academic.includes('AppLoader?.loadScript?.'),'Word parser uygulama açılışında değil merkezi lazy loader ile yüklenmeli.');"
test=test.replace(needle,extra,1)

p.write_text(s,encoding='utf-8');tp.write_text(test,encoding='utf-8');print('Yıllık Plan Word içe aktarma ve A4 çıktı akışı taşındı.')
