from pathlib import Path

DASH=Path('js/modules/dashboard.js')
CSS=Path('css/design-system.css')
TEST=Path('tests/dashboard-card-routes-smoke.test.js')
SW=Path('service-worker.js')

dash=DASH.read_text(encoding='utf-8')
start=dash.find('function lessonsSection(){')
end=dash.find('\nfunction weekDatesLegacy',start)
if start<0 or end<0: raise SystemExit('lessonsSection boundaries not found')
new=r'''function lessonsSection(){const teacherMode=!isAdmin(),tid=teacherId(),mine=teacherMode&&!!tid,all=teacherMode&&!tid?[]:todayLessons({mine}),live=window.SchoolLiveStatus?.status?.();let list=all,title=teacherMode?'Bugünkü Derslerim':'Şu Anki Dersler';if(isAdmin()){const period=live?.mode==='lesson'?live.period:live?.nextPeriod;if(period)list=all.filter(x=>Number(x.saat??x.dersSaati)===Number(period));else if(['after','weekend'].includes(live?.mode))list=[];title=live?.mode==='lesson'?'Şu Anki Dersler':live?.nextPeriod?`Sonraki Dersler · ${live.nextPeriod}. Ders`:'Şu Anki Dersler'}const bookIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V5H6.5A2.5 2.5 0 0 0 4 7.5v12Z"/><path d="M8 9h8M8 13h6"/></svg>';const rows=list.length?list.slice(0,10).map(x=>{const period=Number(x.saat??x.dersSaati),now=teacherMode&&live?.mode==='lesson'&&Number(live.period)===period,next=teacherMode&&!now&&Number(live?.nextPeriod)===period,action=mine?`data-dash-lesson-plan data-lesson="${esc(lessonLabel(x))}" data-class="${esc(classLabel(x))}"`:`data-dash-route="academic" data-dash-page="schedule" data-dash-title="Ders Programı"`;return `<button type="button" class="kh-row${now?' is-now':''}" ${action}><div class="kh-row-main"><b>${esc(String(x.saat??x.dersSaati??'•'))}. Ders · ${esc(classLabel(x))} · ${esc(lessonLabel(x))}</b><small>${mine?'Yıllık planı aç':esc(teacherLabel(x))}</small></div>${now?'<span class="kh-chip green">ŞİMDİ</span>':next?'<span class="kh-chip">SIRADAKİ</span>':'<span class="kh-side">Planı</span>'}</button>`}).join(''):`<div class="kh-empty">${esc(isAdmin()?'Bu ders saati için program kaydı yok.':tid?'Bugün için ders programı kaydı yok.':'Profilinize bağlı öğretmen kaydı bulunamadı.')}</div>`;return `<section class="kh-section" data-home-section="lessons"><div class="kh-section-head"><div class="kh-section-title">${bookIcon}<span>${esc(title)}</span></div>${teacherMode?'<button type="button" class="kh-more" data-dash-route="academic" data-dash-page="schedule" data-dash-title="Ders Programı">Haftalık ›</button>':''}</div><div class="kh-card">${rows}</div></section>`}'''
dash=dash[:start]+new+dash[end:]
DASH.write_text(dash,encoding='utf-8')

css=CSS.read_text(encoding='utf-8')
marker='/* LEGACY TODAY LESSONS — REFERENCE PORT */'
block='''\n\n/* LEGACY TODAY LESSONS — REFERENCE PORT */\n.ka-home .kh-section[data-home-section="lessons"]{display:flex;flex-direction:column;gap:8px}\n.ka-home .kh-section[data-home-section="lessons"] .kh-section-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 2px}\n.ka-home .kh-section[data-home-section="lessons"] .kh-section-title{display:flex;align-items:center;gap:8px;min-width:0;font-size:15.5px;font-weight:900;color:var(--ka-text)}\n.ka-home .kh-section[data-home-section="lessons"] .kh-section-title svg{width:19px;height:19px;flex:none;color:var(--ka-primary)}\n.ka-home .kh-section[data-home-section="lessons"] .kh-more{border:0;background:transparent;color:var(--ka-primary);font:inherit;font-size:10.5px;font-weight:850;padding:6px 2px;white-space:nowrap}\n.ka-home .kh-section[data-home-section="lessons"] .kh-card{overflow:hidden;border:1px solid var(--ka-border);border-radius:20px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm)}\n.ka-home .kh-section[data-home-section="lessons"] .kh-row{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:11px 12px;border:0;border-bottom:1px solid var(--ka-border);background:transparent;color:var(--ka-text);text-align:left;font:inherit;cursor:pointer}\n.ka-home .kh-section[data-home-section="lessons"] .kh-row:last-child{border-bottom:0}\n.ka-home .kh-section[data-home-section="lessons"] .kh-row.is-now{background:var(--ka-primary-soft)}\n.ka-home .kh-section[data-home-section="lessons"] .kh-row-main{min-width:0}\n.ka-home .kh-section[data-home-section="lessons"] .kh-row-main b{display:block;font-size:12.5px;line-height:1.28;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--ka-text)}\n.ka-home .kh-section[data-home-section="lessons"] .kh-row-main small{display:block;font-size:10.5px;line-height:1.35;color:var(--ka-text-muted);margin-top:3px}\n'''
if marker not in css: css+=block
CSS.write_text(css,encoding='utf-8')

test=TEST.read_text(encoding='utf-8')
test=test.replace("assert(dash.includes(\"title=teacherMode?'Ders Programım':'Şu Anki Dersler'\")&&dash.includes('data-dash-page=\\\"schedule\\\"'),'Öğretmenin günlük ders kartı Ders Programım başlığıyla haftalık programa bağlanmalı.');","assert(dash.includes(\"title=teacherMode?'Bugünkü Derslerim':'Şu Anki Dersler'\")&&dash.includes('data-home-section=\\\"lessons\\\"')&&dash.includes('data-dash-page=\\\"schedule\\\"'),'Öğretmenin günlük ders kartı referanstaki Bugünkü Derslerim başlığıyla haftalık programa bağlanmalı.');")
test=test.replace("assert(css.includes('TEACHER WORKFLOW DASHBOARD')&&css.includes('.ka-home-lessons--teacher'),'Öğretmen iş akışı görsel düzeni merkezi design-system içinde kalmalı.');","assert(css.includes('LEGACY TODAY LESSONS — REFERENCE PORT')&&css.includes('.kh-section[data-home-section=\"lessons\"] .kh-row.is-now'),'Öğretmen ders kartı referans legacy geometriyle merkezi design-system içinde kalmalı.');")
test=test.replace("assert(dash.includes(\"live=window.SchoolLiveStatus?.status?.()\")&&dash.includes('ka-home-lesson-state active'),'Öğretmen ders programı mevcut zil/ders durumundan Şimdi-Sıradaki bağlamı üretmeli.');","assert(dash.includes(\"live=window.SchoolLiveStatus?.status?.()\")&&dash.includes('<span class=\\\"kh-chip green\\\">ŞİMDİ</span>')&&dash.includes('<span class=\\\"kh-chip\\\">SIRADAKİ</span>'),'Öğretmen ders programı mevcut zil/ders durumundan referans Şimdi-Sıradaki bağlamını üretmeli.');")
check='''\nassert(dash.includes('class="kh-row${now?')&&dash.includes('data-dash-lesson-plan'),'Bugünkü Derslerim satırları referans kh-row yapısını ve yıllık plan aksiyonunu korumalı.');\nassert(!dash.includes('ka-home-lessons--teacher'),'Eski yeni-taklit ders liste sınıfı aktif renderer içinde kalmamalı.');\n// Checkpoint: legacy today lessons port using canonical SchoolLiveStatus.\n'''
if 'legacy today lessons port using canonical SchoolLiveStatus' not in test: test+=check
TEST.write_text(test,encoding='utf-8')

sw=SW.read_text(encoding='utf-8')
if "const CACHE_ADI='oy-cache-v728';" not in sw: raise SystemExit('unexpected cache version')
sw=sw.replace("const CACHE_ADI='oy-cache-v728';","const CACHE_ADI='oy-cache-v729';",1)
SW.write_text(sw,encoding='utf-8')
