from pathlib import Path

rubric_path=Path('js/modules/rubric-settings.js')
src=rubric_path.read_text(encoding='utf-8')

old_head="function pageHead(type){const c=CFG[type];return `${routeMarker(type)}<div class=\"ka-row ka-row--between ka-wrap\"><div class=\"ka-grow\"><h2>${esc(c.title)}</h2><p class=\"ka-muted\">${esc(c.sub)}</p></div>${actions(type)}</div>`}"
new_head="function pageHead(type){if(type==='rehberlik')return guidancePageHead();const c=CFG[type];return `${routeMarker(type)}<div class=\"ka-row ka-row--between ka-wrap\"><div class=\"ka-grow\"><h2>${esc(c.title)}</h2><p class=\"ka-muted\">${esc(c.sub)}</p></div>${actions(type)}</div>`}"
if old_head not in src:
    raise RuntimeError('pageHead anchor not found')
src=src.replace(old_head,new_head,1)

marker="function maarifCard(r){"
if marker not in src:
    raise RuntimeError('maarifCard insertion anchor not found')

guidance=r'''function guidancePageHead(){const c=CFG.rehberlik,editable=canEdit('rehberlik');return `<h3 data-cizelge-route-label class="ka-guidance-route-marker">${esc(c.route)}</h3><header class="ka-guidance-page-head"><div class="ka-guidance-page-head__copy"><span class="ka-guidance-kicker">ÖĞRENCİ REHBERLİĞİ</span><h2>${esc(c.title)}</h2><p>${esc(c.sub)}</p></div><div class="ka-guidance-action-grid" aria-label="Rehberlik işlemleri">${c.report?'<button class="ka-guidance-action" type="button" data-cizelge-report><span class="ka-guidance-action__icon" aria-hidden="true">🖨️</span><span class="ka-guidance-action__copy"><strong>Rapor</strong><small>Rehberlik çizelgesi</small></span><span class="ka-guidance-action__chevron" aria-hidden="true">›</span></button>':''}<button class="ka-guidance-action" type="button" data-cizelge-excel ${editable?'':'disabled'}><span class="ka-guidance-action__icon" aria-hidden="true">⇧</span><span class="ka-guidance-action__copy"><strong>Excel'den İçe Aktar</strong><small>Toplu kayıt yükle</small></span><span class="ka-guidance-action__chevron" aria-hidden="true">›</span></button><button class="ka-guidance-action" type="button" data-cizelge-bulk ${editable?'':'disabled'}><span class="ka-guidance-action__icon" aria-hidden="true">📅</span><span class="ka-guidance-action__copy"><strong>Tarihleri Toplu Ayarla</strong><small>Plan tarihlerini güncelle</small></span><span class="ka-guidance-action__chevron" aria-hidden="true">›</span></button><button class="ka-guidance-action is-primary" type="button" data-cizelge-add ${editable?'':'disabled'}><span class="ka-guidance-action__icon" aria-hidden="true">＋</span><span class="ka-guidance-action__copy"><strong>Yeni Rehberlik</strong><small>Sınıf danışmanlığı ekle</small></span><span class="ka-guidance-action__chevron" aria-hidden="true">›</span></button></div></header>`}
function guidanceCheck(row,index,label,kind='month'){const values=checkArray('rehberlik',row),checked=!!values[index],disabled=!canEdit('rehberlik');return `<label class="ka-guidance-check ${checked?'is-checked':''} is-${kind}"><input type="checkbox" data-cizelge-check data-type="rehberlik" data-id="${esc(row.id)}" data-index="${index}" ${checked?'checked':''} ${disabled?'disabled':''}><span class="ka-guidance-check__state" aria-hidden="true">${checked?'✓':''}</span><span class="ka-guidance-check__label">${esc(label)}</span></label>`}
function guidanceEditButton(id){return canEdit('rehberlik')?`<button class="ka-guidance-edit" type="button" data-cizelge-edit="${esc(id)}"><span aria-hidden="true">✎</span><span>Düzenle</span></button>`:''}
function guidanceCard(r){const labels=CONTROLS.rehberlik||[],values=checkArray('rehberlik',r),done=values.filter(Boolean).length,dateText=r.yillikPlanTarihi?trDate(r.yillikPlanTarihi):'Tarih belirlenmedi',months=labels.slice(1,10),reports=labels.slice(10,12);return `<article class="ka-guidance-card" data-cizelge-guidance-card="${esc(r.id)}"><header class="ka-guidance-card__head"><div class="ka-guidance-card__identity"><strong>${esc(r.sinif||'Rehberlik')}</strong><span>${esc(dateText)}</span></div><div class="ka-guidance-card__head-actions"><span class="ka-guidance-card__progress">${done}/${values.length}</span>${guidanceEditButton(r.id)}</div></header><div class="ka-guidance-card__tracking"><section class="ka-guidance-plan-block"><div class="ka-guidance-section-label">PLAN</div>${guidanceCheck(r,0,labels[0]||'Yıllık Çalışma Planı','plan')}</section><section class="ka-guidance-period-block"><div class="ka-guidance-section-label">AYLIK TAKİP</div><div class="ka-guidance-month-grid">${months.map((label,i)=>guidanceCheck(r,i+1,label,'month')).join('')}</div>${reports.length?`<div class="ka-guidance-report-caption">DÖNEM RAPORLARI</div><div class="ka-guidance-report-grid">${reports.map((label,i)=>guidanceCheck(r,i+10,label,'report')).join('')}</div>`:''}</section></div>${r.aciklama?`<div class="ka-guidance-card__note"><span aria-hidden="true">📝</span><span>${esc(r.aciklama)}</span></div>`:''}</article>`}
function guidanceTeacherGroupedList(rows){const labels=CONTROLS.rehberlik||[],groups=new Map;rows.forEach(r=>{const key=r.ogretmenId?String(r.ogretmenId):'__yok__';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)});const name=key=>key==='__yok__'?'Öğretmen Atanmamış':teacherName(key)||'Öğretmen';return `<div class="ka-guidance-groups">${[...groups.entries()].sort((a,b)=>name(a[0]).localeCompare(name(b[0]),'tr')).map(([teacherId,records])=>{const sorted=records.slice().sort((a,b)=>genericTitle('rehberlik',a).localeCompare(genericTitle('rehberlik',b),'tr',{numeric:true})),done=sorted.reduce((sum,r)=>sum+checkArray('rehberlik',r).filter(Boolean).length,0),total=sorted.length*labels.length;return `<section class="ka-guidance-teacher" data-cizelge-teacher-group="${esc(teacherId)}"><header class="ka-guidance-teacher__head"><span class="ka-guidance-teacher__icon" aria-hidden="true">♙</span><div class="ka-guidance-teacher__copy"><strong>${esc(name(teacherId))}</strong><span>${sorted.length} kayıt</span></div><span class="ka-guidance-teacher__progress">${done}/${total}</span></header><div class="ka-guidance-teacher__records">${sorted.map(guidanceCard).join('')}</div></section>`}).join('')}</div>`}
'''
src=src.replace(marker,guidance+marker,1)

old_body="if(type==='maarifRapor')return maarifMatrix(rows);if(type==='digerEvrak')return `<div class=\"ka-stack\">${rows.map(otherCard).join('')}</div>`;if(TEACHER_GROUPED_TYPES.has(type))return teacherGroupedList(type,rows);"
new_body="if(type==='maarifRapor')return maarifMatrix(rows);if(type==='digerEvrak')return `<div class=\"ka-stack\">${rows.map(otherCard).join('')}</div>`;if(type==='rehberlik')return guidanceTeacherGroupedList(rows);if(TEACHER_GROUPED_TYPES.has(type))return teacherGroupedList(type,rows);"
if old_body not in src:
    raise RuntimeError('bodyHtml grouped renderer anchor not found')
src=src.replace(old_body,new_body,1)

old_section='`<section class="ka-stack" data-classic-cizelge-page="${currentType}" style="position:relative">${pageHead(currentType)}${bodyHtml(currentType)}</section>`'
new_section='`<section class="ka-stack ka-cizelge-page" data-classic-cizelge-page="${currentType}">${pageHead(currentType)}${bodyHtml(currentType)}</section>`'
if old_section not in src:
    raise RuntimeError('cizelge page wrapper anchor not found')
src=src.replace(old_section,new_section,1)
rubric_path.write_text(src,encoding='utf-8')

css_path=Path('css/design-system.css')
css=css_path.read_text(encoding='utf-8')
marker_css='/* Rehberlik page — responsive canonical Çizelgeler presentation. */'
if marker_css not in css:
    css += r'''

/* Rehberlik page — responsive canonical Çizelgeler presentation. */
.ka-cizelge-page{position:relative;min-width:0;max-width:100%}
[data-classic-cizelge-page="rehberlik"]{width:100%;min-width:0;max-width:100%;overflow-x:clip;gap:20px}
.ka-guidance-route-marker{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.ka-guidance-page-head{display:grid;gap:18px;min-width:0;padding:22px;border:1px solid var(--ka-hero-border);border-radius:24px;background:var(--ka-hero-bg);box-shadow:var(--ka-hero-shadow)}
.ka-guidance-page-head__copy{display:grid;gap:5px;min-width:0}.ka-guidance-kicker{color:var(--ka-hero-kicker);font-size:10px;font-weight:900;letter-spacing:.12em}.ka-guidance-page-head__copy h2{font-size:clamp(26px,5vw,34px);letter-spacing:-.03em}.ka-guidance-page-head__copy p{max-width:620px;color:var(--ka-hero-muted);font-size:14px}
.ka-guidance-action-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;min-width:0}.ka-guidance-action{min-width:0;min-height:78px;display:grid;grid-template-columns:42px minmax(0,1fr) 18px;align-items:center;gap:10px;padding:12px 13px;border:1px solid var(--ka-border);border-radius:17px;background:var(--ka-card-bg);color:var(--ka-text);text-align:left;cursor:pointer;box-shadow:var(--ka-shadow-sm);transition:border-color var(--ka-transition-fast),background var(--ka-transition-fast),transform var(--ka-transition-fast)}.ka-guidance-action:hover{border-color:var(--ka-border-strong);background:var(--ka-card-raised-bg)}.ka-guidance-action:active{transform:translateY(1px)}.ka-guidance-action:focus-visible{outline:3px solid var(--ka-focus);outline-offset:2px}.ka-guidance-action:disabled{opacity:.5;cursor:not-allowed;transform:none}.ka-guidance-action.is-primary{border-color:color-mix(in srgb,var(--ka-primary) 42%,var(--ka-border));background:var(--ka-primary-soft)}.ka-guidance-action__icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:var(--ka-muted-bg);color:var(--ka-primary);font-size:20px;font-weight:900}.ka-guidance-action.is-primary .ka-guidance-action__icon{background:color-mix(in srgb,var(--ka-primary) 16%,var(--ka-card-bg))}.ka-guidance-action__copy{display:grid;gap:2px;min-width:0}.ka-guidance-action__copy strong{font-size:13px;line-height:1.25}.ka-guidance-action__copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ka-text-muted);font-size:10px}.ka-guidance-action__chevron{color:var(--ka-text-muted);font-size:24px;line-height:1}
.ka-guidance-groups{display:grid;gap:22px;min-width:0}.ka-guidance-teacher{display:grid;gap:10px;min-width:0}.ka-guidance-teacher__head{display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:10px;min-width:0;padding:0 3px 10px;border-bottom:1px solid var(--ka-border)}.ka-guidance-teacher__icon{width:42px;height:42px;display:grid;place-items:center;border-radius:50%;background:var(--ka-primary-soft);color:var(--ka-primary);font-size:22px;font-weight:900}.ka-guidance-teacher__copy{display:grid;min-width:0}.ka-guidance-teacher__copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:17px;letter-spacing:.01em}.ka-guidance-teacher__copy span{color:var(--ka-text-muted);font-size:12px}.ka-guidance-teacher__progress{min-width:56px;min-height:34px;display:inline-flex;align-items:center;justify-content:center;padding:5px 10px;border-radius:999px;background:var(--ka-primary-soft);color:var(--ka-primary);font-size:13px;font-weight:850}.ka-guidance-teacher__records{display:grid;gap:10px;min-width:0}
.ka-guidance-card{display:grid;gap:15px;min-width:0;padding:18px;border:1px solid var(--ka-border);border-radius:22px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm)}.ka-guidance-card__head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;min-width:0}.ka-guidance-card__identity{display:grid;gap:2px;min-width:0}.ka-guidance-card__identity strong{font-size:21px;letter-spacing:-.02em}.ka-guidance-card__identity span{color:var(--ka-text-muted);font-size:13px}.ka-guidance-card__head-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.ka-guidance-card__progress{min-height:30px;display:inline-flex;align-items:center;padding:4px 9px;border-radius:999px;background:var(--ka-muted-bg);color:var(--ka-text-muted);font-size:11px;font-weight:800}.ka-guidance-edit{min-height:40px;display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:0 13px;border:1px solid color-mix(in srgb,var(--ka-primary) 48%,var(--ka-border));border-radius:12px;background:var(--ka-button-bg);color:var(--ka-button-text);font-weight:800;cursor:pointer}.ka-guidance-edit:focus-visible{outline:3px solid var(--ka-focus);outline-offset:2px}
.ka-guidance-card__tracking{display:grid;grid-template-columns:minmax(142px,170px) minmax(0,1fr);gap:14px;min-width:0}.ka-guidance-plan-block,.ka-guidance-period-block{min-width:0}.ka-guidance-plan-block{display:grid;align-content:start;gap:8px;padding:12px;border:1px solid var(--ka-border);border-radius:16px;background:var(--ka-muted-bg)}.ka-guidance-period-block{display:grid;gap:8px}.ka-guidance-section-label,.ka-guidance-report-caption{color:var(--ka-text-muted);font-size:9px;font-weight:900;letter-spacing:.1em}.ka-guidance-report-caption{margin-top:3px}
.ka-guidance-month-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(84px,1fr));gap:7px;min-width:0}.ka-guidance-report-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;min-width:0}.ka-guidance-check{min-width:0;min-height:42px;display:grid;grid-template-columns:24px minmax(0,1fr);align-items:center;gap:7px;padding:7px 9px;border:1px solid var(--ka-border);border-radius:12px;background:var(--ka-card-raised-bg);color:var(--ka-text);cursor:pointer;user-select:none}.ka-guidance-check.is-checked{border-color:color-mix(in srgb,var(--ka-primary) 45%,var(--ka-border));background:var(--ka-primary-soft)}.ka-guidance-check input{position:absolute;inline-size:1px!important;block-size:1px!important;opacity:0;pointer-events:none}.ka-guidance-check__state{width:24px;height:24px;display:grid;place-items:center;border:2px solid var(--ka-border-strong);border-radius:8px;color:var(--ka-text-inverse);font-size:14px;font-weight:900}.ka-guidance-check.is-checked .ka-guidance-check__state{border-color:var(--ka-primary);background:var(--ka-primary);color:var(--ka-text-inverse)}.ka-guidance-check__label{min-width:0;font-size:12px;line-height:1.25}.ka-guidance-check.is-plan{grid-template-columns:28px minmax(0,1fr);min-height:76px;align-content:center;background:transparent}.ka-guidance-check.is-plan .ka-guidance-check__state{width:28px;height:28px}.ka-guidance-check.is-plan .ka-guidance-check__label{font-size:13px;font-weight:750}.ka-guidance-check.is-report .ka-guidance-check__label{font-size:11px}.ka-guidance-check:focus-within{outline:3px solid var(--ka-focus);outline-offset:1px}.ka-guidance-card__note{display:flex;align-items:flex-start;gap:8px;padding-top:11px;border-top:1px solid var(--ka-border);color:var(--ka-text-muted);font-size:12px;line-height:1.5}
[data-theme="dark"] .ka-guidance-page-head{background:radial-gradient(circle at 90% 0,rgba(83,214,164,.10),transparent 34%),linear-gradient(145deg,#102019,#0c1612)}[data-theme="dark"] .ka-guidance-action{background:#102019}[data-theme="dark"] .ka-guidance-action.is-primary{background:#143126}[data-theme="dark"] .ka-guidance-card{background:#0f1b16}[data-theme="dark"] .ka-guidance-plan-block{background:#12221b}[data-theme="dark"] .ka-guidance-check{background:#101d18}[data-theme="dark"] .ka-guidance-check.is-checked{background:#123126}
@media(max-width:680px){[data-classic-cizelge-page="rehberlik"]{gap:16px}.ka-guidance-page-head{padding:17px;border-radius:20px}.ka-guidance-action-grid{gap:8px}.ka-guidance-action{min-height:72px;grid-template-columns:36px minmax(0,1fr) 14px;padding:10px}.ka-guidance-action__icon{width:36px;height:36px;border-radius:11px;font-size:17px}.ka-guidance-action__copy strong{font-size:12px}.ka-guidance-action__copy small{font-size:9px}.ka-guidance-card{padding:14px;border-radius:19px}.ka-guidance-card__tracking{grid-template-columns:minmax(128px,145px) minmax(0,1fr);gap:10px}.ka-guidance-month-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.ka-guidance-check{padding:6px;gap:5px}.ka-guidance-check__label{font-size:11px}.ka-guidance-report-grid{grid-template-columns:1fr 1fr}}
@media(max-width:480px){.ka-guidance-page-head__copy p{font-size:12px}.ka-guidance-action__copy small{display:none}.ka-guidance-card__head{align-items:center}.ka-guidance-card__head-actions{gap:6px}.ka-guidance-card__progress{display:none}.ka-guidance-edit{min-height:38px;padding-inline:11px}.ka-guidance-card__tracking{grid-template-columns:1fr}.ka-guidance-plan-block{padding:9px}.ka-guidance-check.is-plan{min-height:54px;grid-template-columns:28px minmax(0,1fr)}.ka-guidance-month-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.ka-guidance-report-grid{grid-template-columns:1fr 1fr}}
'''
css_path.write_text(css,encoding='utf-8')

sw_path=Path('service-worker.js')
sw=sw_path.read_text(encoding='utf-8')
if "const CACHE_ADI='oy-cache-v823';" not in sw:
    raise RuntimeError('service worker cache v823 anchor not found')
sw=sw.replace("const CACHE_ADI='oy-cache-v823';","const CACHE_ADI='oy-cache-v824';",1)
sw_path.write_text(sw,encoding='utf-8')

test=Path('tests/rehberlik-page-redesign.test.js')
test.write_text(r'''const fs=require('fs');
const assert=require('assert');
const rubric=fs.readFileSync('js/modules/rubric-settings.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
new Function(rubric);
const start=rubric.indexOf('function guidancePageHead(){');
const end=rubric.indexOf('function maarifCard(r){',start);
assert(start>=0&&end>start,'Rehberlik canonical özel renderer bloğu bulunmalı.');
const block=rubric.slice(start,end);
for(const token of ['ka-guidance-page-head','ka-guidance-action-grid','data-cizelge-report','data-cizelge-excel','data-cizelge-bulk','data-cizelge-add','function guidanceCard','function guidanceTeacherGroupedList','data-cizelge-teacher-group','data-cizelge-guidance-card','ka-guidance-month-grid','ka-guidance-report-grid','data-cizelge-check','data-cizelge-edit'])assert(block.includes(token),`Rehberlik görünür sözleşmesi eksik: ${token}`);
for(const label of ['Rapor',"Excel'den İçe Aktar",'Tarihleri Toplu Ayarla','Yeni Rehberlik','Yıllık Çalışma Planı','AYLIK TAKİP','DÖNEM RAPORLARI','Düzenle'])assert(block.includes(label),`Rehberlik metni eksik: ${label}`);
assert(!block.includes('style='),'Rehberlik özel renderer inline style üretmemeli.');
assert(rubric.includes("if(type==='rehberlik')return guidanceTeacherGroupedList(rows);"),'Rehberlik generic yatay kontrol rendererı yerine özel responsive rendererı kullanmalı.');
assert(rubric.includes("rehberlik:['Yıllık Çalışma Planı','Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz','1.Dönem Sonu Rap.','Sene Sonu Rap.']"),'12 gerçek Rehberlik kontrolü korunmalı.');
assert(rubric.includes("else if(type==='rehberlik')v={ogretmenId:"),'Rehberlik kayıt veri modeli ve mevcut save akışı korunmalı.');
assert(rubric.includes("if(type==='rehberlik')return{ogretmenId:teacherIdByName"),'Rehberlik Excel içe aktarma veri modeli korunmalı.');
for(const token of ['.ka-guidance-action-grid{','.ka-guidance-teacher{','.ka-guidance-card{','.ka-guidance-card__tracking{','.ka-guidance-month-grid{','.ka-guidance-report-grid{','[data-classic-cizelge-page="rehberlik"]'])assert(css.includes(token),`Design system Rehberlik stili eksik: ${token}`);
const monthCss=css.slice(css.indexOf('.ka-guidance-month-grid{'),css.indexOf('.ka-guidance-report-grid{'));
assert(monthCss.includes('display:grid')&&monthCss.includes('grid-template-columns'),'Aylık Rehberlik kontrolleri responsive grid olmalı.');
assert(!monthCss.includes('overflow-x:auto'),'Aylık Rehberlik kontrolleri yatay kaydırma üretmemeli.');
assert(sw.includes("const CACHE_ADI='oy-cache-v824';"),'PWA cache v824 olmalı.');
console.log('Rehberlik responsive page redesign contract OK');
''',encoding='utf-8')
