from pathlib import Path

rubric_path=Path('js/modules/rubric-settings.js')
src=rubric_path.read_text(encoding='utf-8')


def replace_function(text, name, next_name, replacement):
    start=f'function {name}'
    end=f'function {next_name}'
    i=text.find(start)
    if i<0:
        raise RuntimeError(f'{name} anchor not found')
    j=text.find(end,i)
    if j<0:
        raise RuntimeError(f'{next_name} anchor not found after {name}')
    return text[:i]+replacement.rstrip()+"\n"+text[j:]

# Shared page presentation metadata: UI-only, no persistent data model.
anchor="};\nlet currentType='';"
if anchor not in src:
    raise RuntimeError('CFG/currentType anchor not found')
page_ui=r''' };
const PAGE_UI={
 sosyalKulupler:{kicker:'KULÜP & TOPLUM HİZMETİ',icon:'♡',reportHint:'Kulüp teslim çizelgesi',excelHint:'Toplu kulüp kaydı yükle',bulkHint:'Plan tarihlerini güncelle',addHint:'Yeni sosyal kulüp oluştur'},
 belirliGunler:{kicker:'ETKİNLİK TAKVİMİ',icon:'✦',reportHint:'Görev dağılım raporu',excelHint:'Etkinlikleri toplu yükle',addHint:'Yeni etkinlik oluştur'},
 zumre:{kicker:'ZÜMRE YÖNETİMİ',icon:'◎',reportHint:'Zümre takip raporu',excelHint:'Zümre kayıtlarını yükle',bulkHint:'Dönem tarihlerini güncelle',addHint:'Yeni zümre kaydı oluştur'},
 sok:{kicker:'KURUL TAKİBİ',icon:'◇',reportHint:'ŞÖK takip raporu',excelHint:'ŞÖK kayıtlarını yükle',bulkHint:'Toplantı tarihlerini güncelle',addHint:'Yeni ŞÖK kaydı oluştur'},
 bepPlani:{kicker:'PLAN & BEP',icon:'▣',reportHint:'Plan ve BEP takip raporu',excelHint:'Plan kayıtlarını yükle',bulkHint:'Teslim tarihlerini güncelle',addHint:'Yeni plan kaydı oluştur'},
 maarifRapor:{kicker:'TÜRKİYE YÜZYILI MAARİF MODELİ',icon:'✺',reportHint:'Aylık rapor takip çizelgesi',excelHint:'Ders / sınıf kayıtlarını yükle',addHint:'Yeni aylık rapor kaydı oluştur'},
 digerEvrak:{kicker:'EVRAK TESLİM TAKİBİ',icon:'▤',excelHint:'Evrak kayıtlarını toplu yükle',addHint:'Yeni evrak kaydı oluştur'}
};
let currentType='';'''
src=src.replace(anchor,page_ui,1)

old_actions_start="function actions(type)"
old_page_head_start="function pageHead(type)"
i=src.find(old_actions_start)
j=src.find(old_page_head_start,i)
if i<0 or j<0:
    raise RuntimeError('actions/pageHead anchors not found')
new_actions=r'''function actions(type){const c=CFG[type],ui=PAGE_UI[type]||{},editable=canEdit(type),action=(cls,attrs,icon,label,hint)=>`<button class="ka-cizelge-action ${cls||''}" type="button" ${attrs}><span class="ka-cizelge-action__icon" aria-hidden="true">${icon}</span><span class="ka-cizelge-action__copy"><strong>${esc(label)}</strong><small>${esc(hint||'')}</small></span><span class="ka-cizelge-action__chevron" aria-hidden="true">›</span></button>`;return `<div class="ka-cizelge-action-grid" aria-label="${esc(c.title)} işlemleri">${c.report?action('', 'data-cizelge-report','🖨️','Rapor',ui.reportHint||'Çizelge raporu'):''}${action('',`data-cizelge-excel ${editable?'':'disabled'}`,'⇧',"Excel'den İçe Aktar",ui.excelHint||'Toplu kayıt yükle')}${c.bulk?action('',`data-cizelge-bulk ${editable?'':'disabled'}`,'📅','Tarihleri Toplu Ayarla',ui.bulkHint||'Tarihleri güncelle'):''}${action('is-primary',`data-cizelge-add ${editable?'':'disabled'}`,'＋',c.add.replace(/^\+\s*/,''),ui.addHint||'Yeni kayıt oluştur')}</div>`}
'''
src=src[:i]+new_actions+src[j:]

src=replace_function(src,'pageHead','checkArray',r'''function modernPageHead(type){const c=CFG[type],ui=PAGE_UI[type]||{};return `${routeMarker(type)}<header class="ka-cizelge-page-head"><div class="ka-cizelge-page-head__intro"><span class="ka-cizelge-page-head__icon" aria-hidden="true">${ui.icon||'▦'}</span><div class="ka-cizelge-page-head__copy"><span class="ka-cizelge-kicker">${esc(ui.kicker||'OKUL İŞLEMLERİ')}</span><h2>${esc(c.title)}</h2><p>${esc(c.sub)}</p></div></div>${actions(type)}</header>`}
function pageHead(type){if(type==='rehberlik')return guidancePageHead();return modernPageHead(type)}''')

src=replace_function(src,'controlGrid','teacherBadges',r'''function controlGrid(type,row){const labels=CONTROLS[type];if(!labels)return'';const a=checkArray(type,row),disabled=!canEdit(type),item=(label,i,kind='default')=>`<label class="ka-cizelge-check ${a[i]?'is-checked':''} is-${kind}"><input type="checkbox" data-cizelge-check data-type="${type}" data-id="${esc(row.id)}" data-index="${i}" ${a[i]?'checked':''} ${disabled?'disabled':''}><span class="ka-cizelge-check__state" aria-hidden="true">${a[i]?'✓':''}</span><span class="ka-cizelge-check__label">${esc(label)}</span></label>`;if(type==='sosyalKulupler'){const plan=labels.slice(0,2),months=labels.slice(2,11),report=labels.slice(11);return `<div class="ka-cizelge-control-sections"><section><span class="ka-cizelge-section-label">PLANLAR</span><div class="ka-cizelge-check-grid is-plan-grid">${plan.map((label,i)=>item(label,i,'plan')).join('')}</div></section><section><span class="ka-cizelge-section-label">AYLIK TAKİP</span><div class="ka-cizelge-check-grid is-month-grid">${months.map((label,i)=>item(label,i+2,'month')).join('')}</div></section>${report.length?`<section><span class="ka-cizelge-section-label">YIL SONU</span><div class="ka-cizelge-check-grid">${report.map((label,i)=>item(label,i+11,'report')).join('')}</div></section>`:''}</div>`}if(type==='belirliGunler')return `<div class="ka-cizelge-status-control">${item(labels[0],0,'status')}</div>`;return `<div class="ka-cizelge-check-grid ${type==='maarifRapor'?'is-month-grid':''}">${labels.map((label,i)=>item(label,i,type==='maarifRapor'?'month':'period')).join('')}</div>`}''')

src=replace_function(src,'teacherBadges','editButton',r'''function teacherBadges(ids){const a=Array.isArray(ids)?ids:[];return a.length?`<div class="ka-cizelge-chip-list">${a.map(id=>`<span class="ka-cizelge-chip"><span aria-hidden="true">♙</span>${esc(teacherName(id))}</span>`).join('')}</div>`:'<span class="ka-cizelge-empty-inline">Öğretmen atanmadı</span>'}''')

src=replace_function(src,'editButton','studentName',r'''function editButton(type,id){return canEdit(type)?`<button class="ka-cizelge-edit" type="button" data-cizelge-edit="${esc(id)}"><span aria-hidden="true">✎</span><span>Düzenle</span></button>`:''}''')

src=replace_function(src,'socialCard','belirliCard',r'''function socialCard(r){const a=checkArray('sosyalKulupler',r),done=a.filter(Boolean).length,classes=Array.isArray(r.sinifIdler)&&r.sinifIdler.length?r.sinifIdler.map(className).join(', '):'Tüm sınıflar',students=clubStudents(r.id),manage=canManageClubStudents(r);return `<article class="ka-cizelge-card ka-cizelge-club-card"><header class="ka-cizelge-card__head"><div class="ka-cizelge-card__identity"><span class="ka-cizelge-card__icon" aria-hidden="true">♡</span><div><div class="ka-cizelge-title-row"><strong>${esc(r.ad||'İsimsiz Kulüp')}</strong><span class="ka-cizelge-status ${r.aktif===false?'is-muted':'is-active'}">${r.aktif===false?'Pasif':'Aktif'}</span></div><small>${students.length} öğrenci · ${done}/${a.length} evrak tamamlandı</small></div></div><div class="ka-cizelge-card__head-actions"><span class="ka-cizelge-progress">${done}/${a.length}</span>${editButton('sosyalKulupler',r.id)}</div></header><div class="ka-cizelge-detail-grid"><section><span class="ka-cizelge-section-label">DANIŞMAN ÖĞRETMENLER</span>${teacherBadges(r.ogretmenIdler)}</section><section><span class="ka-cizelge-section-label">SINIF KAPSAMI</span><div class="ka-cizelge-detail-value">${esc(classes)}</div></section></div><div class="ka-cizelge-date-grid"><div><span>Yıllık Plan</span><strong>${esc(r.yillikPlanTarihi?trDate(r.yillikPlanTarihi):'Tarih yok')}</strong></div><div><span>Toplum Hizmeti</span><strong>${esc(r.toplumHizmetiTarihi?trDate(r.toplumHizmetiTarihi):'Tarih yok')}</strong></div></div><div class="ka-cizelge-inline-actions">${manage?`<button class="ka-btn ka-btn--sm" type="button" data-club-student-edit="${esc(r.id)}">＋ Öğrenci Ekle</button>`:''}<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-club-student-list="${esc(r.id)}">👥 Öğrenciler (${students.length})</button></div>${controlGrid('sosyalKulupler',r)}</article>`}''')

src=replace_function(src,'belirliCard','genericTitle',r'''function belirliCard(r){const done=checkArray('belirliGunler',r)[0],teachers=Array.isArray(r.ogretmenIdler)?r.ogretmenIdler:[];return `<article class="ka-cizelge-card ka-cizelge-event-card"><header class="ka-cizelge-card__head"><div class="ka-cizelge-card__identity"><span class="ka-cizelge-card__icon" aria-hidden="true">✦</span><div><div class="ka-cizelge-title-row"><strong>${esc(r.ad||'Etkinlik')}</strong><span class="ka-cizelge-status ${done?'is-active':'is-pending'}">${done?'✓ Yapıldı':'Bekliyor'}</span></div><small>Belirli gün / hafta etkinliği</small></div></div><div class="ka-cizelge-card__head-actions">${editButton('belirliGunler',r.id)}</div></header><div class="ka-cizelge-event-body"><div class="ka-cizelge-date-range"><span class="ka-cizelge-section-label">ETKİNLİK TARİHİ</span><strong>${esc(trDate(r.tarihBaslangic)||'Tarih yok')}</strong>${r.tarihBitis?`<span>→ ${esc(trDate(r.tarihBitis))}</span>`:''}</div><section><span class="ka-cizelge-section-label">SORUMLU ÖĞRETMENLER</span>${teacherBadges(teachers)}</section></div>${r.aciklama?`<div class="ka-cizelge-note"><span aria-hidden="true">📝</span><span>${esc(r.aciklama)}</span></div>`:''}${controlGrid('belirliGunler',r)}</article>`}''')

# Keep genericTitle and genericMeta contracts; modernize their card presentation.
src=replace_function(src,'genericCard','teacherGroupedList',r'''function recordDateTiles(type,r){const rows=type==='bepPlani'?[['Yıllık Ders Planı',r.yillikDersPlaniTarihi],['BEP Planı',r.bepPlaniTarihi]]:[['1. Dönem',r.tarih1],['2. Dönem',r.tarih2],['Yıl Sonu',r.tarih3]];return `<div class="ka-cizelge-date-grid ${rows.length===3?'is-three':''}">${rows.map(([label,value])=>`<div><span>${esc(label)}</span><strong>${esc(value?trDate(value):'Tarih yok')}</strong></div>`).join('')}</div>`}
function genericCard(type,r,includeTeacher=true){const a=checkArray(type,r),done=a.filter(Boolean).length,icon=type==='zumre'?'◎':type==='sok'?'◇':'▣';return `<article class="ka-cizelge-card ka-cizelge-period-card"><header class="ka-cizelge-card__head"><div class="ka-cizelge-card__identity"><span class="ka-cizelge-card__icon" aria-hidden="true">${icon}</span><div><strong>${esc(genericTitle(type,r))}</strong><small>${includeTeacher&&r.ogretmenId?esc(teacherName(r.ogretmenId)):`${done}/${a.length} dönem tamamlandı`}</small></div></div><div class="ka-cizelge-card__head-actions"><span class="ka-cizelge-progress">${done}/${a.length}</span>${editButton(type,r.id)}</div></header>${recordDateTiles(type,r)}${r.aciklama?`<div class="ka-cizelge-note"><span aria-hidden="true">📝</span><span>${esc(r.aciklama)}</span></div>`:''}${controlGrid(type,r)}</article>`}''')

src=replace_function(src,'teacherGroupedList','guidancePageHead',r'''function teacherGroupedList(type,rows){const labels=CONTROLS[type]||[],groups=new Map;rows.forEach(r=>{const key=r.ogretmenId?String(r.ogretmenId):'__yok__';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)});const name=key=>key==='__yok__'?'Öğretmen Atanmamış':teacherName(key)||'Öğretmen';return `<div class="ka-cizelge-groups">${[...groups.entries()].sort((a,b)=>name(a[0]).localeCompare(name(b[0]),'tr')).map(([teacherId,records])=>{const sorted=records.slice().sort((a,b)=>genericTitle(type,a).localeCompare(genericTitle(type,b),'tr',{numeric:true})),done=sorted.reduce((sum,r)=>sum+checkArray(type,r).filter(Boolean).length,0),total=sorted.length*labels.length;return `<section class="ka-cizelge-teacher" data-cizelge-teacher-group="${esc(teacherId)}"><header class="ka-cizelge-teacher__head"><span class="ka-cizelge-teacher__icon" aria-hidden="true">♙</span><div class="ka-cizelge-teacher__copy"><strong>${esc(name(teacherId))}</strong><span>${sorted.length} kayıt · ${done}/${total} tamamlandı</span></div><span class="ka-cizelge-teacher__progress">${done}/${total}</span></header><div class="ka-cizelge-record-grid">${sorted.map(r=>genericCard(type,r,false)).join('')}</div></section>`}).join('')}</div>`}''')

src=replace_function(src,'maarifCard','maarifMatrix',r'''function maarifCard(r){const a=checkArray('maarifRapor',r),done=a.filter(Boolean).length;return `<article class="ka-cizelge-card ka-maarif-card"><header class="ka-cizelge-card__head"><div class="ka-cizelge-card__identity"><span class="ka-cizelge-card__icon" aria-hidden="true">✺</span><div><strong>${esc(r.ders||'Ders')}</strong><small>${esc(r.sinif||'Sınıf')} · ${done}/${a.length} ay</small></div></div><div class="ka-cizelge-card__head-actions"><span class="ka-cizelge-progress">${done}/${a.length}</span>${editButton('maarifRapor',r.id)}</div></header>${r.aciklama?`<div class="ka-cizelge-note"><span aria-hidden="true">📝</span><span>${esc(r.aciklama)}</span></div>`:''}<div class="ka-cizelge-section-label">AYLIK RAPOR TAKİBİ</div>${controlGrid('maarifRapor',r)}</article>`}''')

src=replace_function(src,'maarifMatrix','otherCard',r'''function maarifMatrix(rows){const labels=CONTROLS.maarifRapor||[],groups=new Map;rows.forEach(r=>{if(!r.ogretmenId)return;const key=String(r.ogretmenId);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)});if(!groups.size)return'<div class="ka-empty">Öğretmen atanmış kayıt yok.</div>';return `<div class="ka-cizelge-groups ka-maarif-groups" aria-label="DERS / SINIF aylık rapor matrisi">${[...groups.entries()].sort((a,b)=>teacherName(a[0]).localeCompare(teacherName(b[0]),'tr')).map(([teacherId,records])=>{const sorted=records.slice().sort((a,b)=>String(a.ders||'').localeCompare(String(b.ders||''),'tr')||String(a.sinif||'').localeCompare(String(b.sinif||''),'tr',{numeric:true})),done=sorted.reduce((sum,r)=>sum+checkArray('maarifRapor',r).filter(Boolean).length,0),total=sorted.length*labels.length;return `<section class="ka-cizelge-teacher" data-cizelge-teacher-group="${esc(teacherId)}"><header class="ka-cizelge-teacher__head"><span class="ka-cizelge-teacher__icon" aria-hidden="true">♙</span><div class="ka-cizelge-teacher__copy"><strong>${esc(teacherName(teacherId)||'Öğretmen')}</strong><span>${sorted.length} ders / sınıf kaydı · ${done}/${total} aylık rapor</span></div><span class="ka-cizelge-teacher__progress">${done}/${total}</span></header><div class="ka-maarif-record-grid">${sorted.map(maarifCard).join('')}</div></section>`}).join('')}</div>`}''')

src=replace_function(src,'otherCard','bodyHtml',r'''function otherCard(r){const status=r.teslimEdildi?'Teslim Alındı':'Bekliyor';return `<article class="ka-cizelge-card ka-cizelge-document-card"><header class="ka-cizelge-card__head"><div class="ka-cizelge-card__identity"><span class="ka-cizelge-card__icon" aria-hidden="true">▤</span><div><div class="ka-cizelge-title-row"><strong>${esc(r.evrakAdi||'İsimsiz Evrak')}</strong><span class="ka-cizelge-status ${r.teslimEdildi?'is-active':'is-pending'}">${r.teslimEdildi?'✓ ':''}${esc(status)}</span></div><small>${esc(r.tur||'Diğer evrak')}</small></div></div><div class="ka-cizelge-card__head-actions">${editButton('digerEvrak',r.id)}</div></header><div class="ka-cizelge-document-meta">${r.sinif?`<span>🏫 ${esc(r.sinif)}</span>`:''}${r.tarih?`<span>📅 ${esc(trDate(r.tarih))}</span>`:''}<span>📁 ${esc(r.tur||'Diğer')}</span></div>${r.aciklama?`<div class="ka-cizelge-note"><span aria-hidden="true">📝</span><span>${esc(r.aciklama)}</span></div>`:''}</article>`}''')

old_body_start="function bodyHtml(type)"
old_render_start="function render(force=false)"
i=src.find(old_body_start)
j=src.find(old_render_start,i)
if i<0 or j<0:
    raise RuntimeError('bodyHtml/render anchors not found')
new_body=r'''function bodyHtml(type){let rows=arr(type).slice();if(type==='belirliGunler')rows.sort((a,b)=>String(a.tarihBaslangic||'').localeCompare(String(b.tarihBaslangic||'')));else if(type==='digerEvrak')rows.sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||'')));else rows.sort((a,b)=>genericTitle(type,a).localeCompare(genericTitle(type,b),'tr',{numeric:true}));if(!rows.length)return'<div class="ka-empty">Henüz kayıt eklenmedi.</div>';if(type==='sosyalKulupler')return `<div class="ka-cizelge-main-grid">${rows.map(socialCard).join('')}</div>`;if(type==='belirliGunler')return `<div class="ka-cizelge-event-list">${rows.map(belirliCard).join('')}</div>`;if(type==='maarifRapor')return maarifMatrix(rows);if(type==='digerEvrak')return `<div class="ka-cizelge-main-grid is-documents">${rows.map(otherCard).join('')}</div>`;if(type==='rehberlik')return guidanceTeacherGroupedList(rows);if(TEACHER_GROUPED_TYPES.has(type))return teacherGroupedList(type,rows);return `<div class="ka-stack">${rows.map(r=>genericCard(type,r)).join('')}</div>`}
'''
src=src[:i]+new_body+src[j:]

rubric_path.write_text(src,encoding='utf-8')

css_path=Path('css/design-system.css')
css=css_path.read_text(encoding='utf-8')
marker='/* Çizelge pages — shared responsive document tracking workspace. */'
if marker not in css:
    css += r'''

/* Çizelge pages — shared responsive document tracking workspace. */
[data-classic-cizelge-page="sosyalKulupler"],[data-classic-cizelge-page="belirliGunler"],[data-classic-cizelge-page="zumre"],[data-classic-cizelge-page="sok"],[data-classic-cizelge-page="bepPlani"],[data-classic-cizelge-page="maarifRapor"],[data-classic-cizelge-page="digerEvrak"]{width:100%;min-width:0;max-width:100%;overflow-x:clip;gap:20px}
.ka-cizelge-page-head{display:grid;gap:18px;min-width:0;padding:22px;border:1px solid var(--ka-hero-border);border-radius:24px;background:var(--ka-hero-bg);box-shadow:var(--ka-hero-shadow)}
.ka-cizelge-page-head__intro{display:grid;grid-template-columns:54px minmax(0,1fr);align-items:center;gap:14px;min-width:0}.ka-cizelge-page-head__icon{width:54px;height:54px;display:grid;place-items:center;border-radius:17px;background:var(--ka-hero-badge-bg);color:var(--ka-hero-badge-text);font-size:27px;font-weight:900}.ka-cizelge-page-head__copy{display:grid;gap:4px;min-width:0}.ka-cizelge-kicker{color:var(--ka-hero-kicker);font-size:10px;font-weight:900;letter-spacing:.12em}.ka-cizelge-page-head__copy h2{font-size:clamp(25px,4.8vw,34px);letter-spacing:-.03em}.ka-cizelge-page-head__copy p{max-width:680px;color:var(--ka-hero-muted);font-size:14px}
.ka-cizelge-action-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px;min-width:0}.ka-cizelge-action{min-width:0;min-height:74px;display:grid;grid-template-columns:40px minmax(0,1fr) 16px;align-items:center;gap:9px;padding:11px 12px;border:1px solid var(--ka-border);border-radius:16px;background:var(--ka-card-bg);color:var(--ka-text);text-align:left;cursor:pointer;box-shadow:var(--ka-shadow-sm);transition:border-color var(--ka-transition-fast),background var(--ka-transition-fast),transform var(--ka-transition-fast)}.ka-cizelge-action:hover{border-color:var(--ka-border-strong);background:var(--ka-card-raised-bg)}.ka-cizelge-action:active{transform:translateY(1px)}.ka-cizelge-action:focus-visible{outline:3px solid var(--ka-focus);outline-offset:2px}.ka-cizelge-action:disabled{opacity:.5;cursor:not-allowed;transform:none}.ka-cizelge-action.is-primary{border-color:color-mix(in srgb,var(--ka-primary) 42%,var(--ka-border));background:var(--ka-primary-soft)}.ka-cizelge-action__icon{width:40px;height:40px;display:grid;place-items:center;border-radius:12px;background:var(--ka-muted-bg);color:var(--ka-primary);font-size:18px;font-weight:900}.ka-cizelge-action__copy{display:grid;gap:2px;min-width:0}.ka-cizelge-action__copy strong{font-size:13px;line-height:1.2}.ka-cizelge-action__copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ka-text-muted);font-size:10px}.ka-cizelge-action__chevron{color:var(--ka-text-muted);font-size:22px}
.ka-cizelge-main-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;min-width:0}.ka-cizelge-main-grid.is-documents{grid-template-columns:repeat(auto-fit,minmax(290px,1fr))}.ka-cizelge-event-list,.ka-cizelge-groups{display:grid;gap:16px;min-width:0}.ka-cizelge-card{display:grid;gap:14px;min-width:0;padding:17px;border:1px solid var(--ka-border);border-radius:21px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm)}.ka-cizelge-card__head{display:flex;align-items:flex-start;justify-content:space-between;gap:11px;min-width:0}.ka-cizelge-card__identity{display:grid;grid-template-columns:42px minmax(0,1fr);align-items:center;gap:10px;min-width:0}.ka-cizelge-card__identity>div{display:grid;gap:2px;min-width:0}.ka-cizelge-card__identity strong{font-size:17px;line-height:1.25}.ka-cizelge-card__identity small{color:var(--ka-text-muted);font-size:11px}.ka-cizelge-card__icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:var(--ka-primary-soft);color:var(--ka-primary);font-size:21px;font-weight:900}.ka-cizelge-card__head-actions{display:flex;align-items:center;justify-content:flex-end;gap:7px;flex-wrap:wrap}.ka-cizelge-title-row{display:flex;align-items:center;gap:7px;flex-wrap:wrap;min-width:0}.ka-cizelge-status,.ka-cizelge-progress{min-height:27px;display:inline-flex;align-items:center;justify-content:center;padding:3px 8px;border-radius:999px;font-size:10px;font-weight:850;white-space:nowrap}.ka-cizelge-status{background:var(--ka-muted-bg);color:var(--ka-text-muted)}.ka-cizelge-status.is-active{background:color-mix(in srgb,var(--ka-success) 14%,transparent);color:var(--ka-success)}.ka-cizelge-status.is-pending{background:color-mix(in srgb,var(--ka-warning) 14%,transparent);color:var(--ka-warning)}.ka-cizelge-progress{background:var(--ka-primary-soft);color:var(--ka-primary)}.ka-cizelge-edit{min-height:38px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:0 11px;border:1px solid color-mix(in srgb,var(--ka-primary) 40%,var(--ka-border));border-radius:11px;background:var(--ka-button-bg);color:var(--ka-button-text);font-size:12px;font-weight:800;cursor:pointer}.ka-cizelge-edit:focus-visible{outline:3px solid var(--ka-focus);outline-offset:2px}
.ka-cizelge-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ka-cizelge-detail-grid>section{display:grid;align-content:start;gap:7px;min-width:0;padding:11px;border:1px solid var(--ka-border);border-radius:14px;background:var(--ka-muted-bg)}.ka-cizelge-section-label{display:block;color:var(--ka-text-muted);font-size:9px;font-weight:900;letter-spacing:.09em}.ka-cizelge-detail-value{color:var(--ka-text);font-size:12px;line-height:1.45}.ka-cizelge-chip-list{display:flex;flex-wrap:wrap;gap:6px;min-width:0}.ka-cizelge-chip{min-width:0;display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border:1px solid var(--ka-border);border-radius:999px;background:var(--ka-card-bg);color:var(--ka-text);font-size:11px;font-weight:700}.ka-cizelge-empty-inline{color:var(--ka-text-muted);font-size:11px}
.ka-cizelge-date-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ka-cizelge-date-grid.is-three{grid-template-columns:repeat(3,minmax(0,1fr))}.ka-cizelge-date-grid>div{display:grid;gap:2px;min-width:0;padding:10px 11px;border:1px solid var(--ka-border);border-radius:13px;background:var(--ka-muted-bg)}.ka-cizelge-date-grid span{color:var(--ka-text-muted);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.ka-cizelge-date-grid strong{font-size:12px}.ka-cizelge-inline-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.ka-cizelge-note{display:flex;align-items:flex-start;gap:8px;padding:10px 11px;border:1px solid var(--ka-border);border-radius:13px;background:var(--ka-muted-bg);color:var(--ka-text-muted);font-size:12px;line-height:1.45}
.ka-cizelge-control-sections{display:grid;gap:10px;padding-top:2px}.ka-cizelge-control-sections>section{display:grid;gap:6px}.ka-cizelge-check-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:7px;min-width:0}.ka-cizelge-check-grid.is-month-grid{grid-template-columns:repeat(auto-fit,minmax(72px,1fr))}.ka-cizelge-check{min-width:0;min-height:42px;display:grid;grid-template-columns:23px minmax(0,1fr);align-items:center;gap:7px;padding:7px 8px;border:1px solid var(--ka-border);border-radius:12px;background:var(--ka-card-raised-bg);color:var(--ka-text);cursor:pointer;user-select:none}.ka-cizelge-check.is-checked{border-color:color-mix(in srgb,var(--ka-primary) 45%,var(--ka-border));background:var(--ka-primary-soft)}.ka-cizelge-check input{position:absolute;inline-size:1px!important;block-size:1px!important;opacity:0;pointer-events:none}.ka-cizelge-check__state{width:23px;height:23px;display:grid;place-items:center;border:2px solid var(--ka-border-strong);border-radius:7px;color:var(--ka-text-inverse);font-size:13px;font-weight:900}.ka-cizelge-check.is-checked .ka-cizelge-check__state{border-color:var(--ka-primary);background:var(--ka-primary);color:var(--ka-text-inverse)}.ka-cizelge-check__label{min-width:0;font-size:11px;line-height:1.2}.ka-cizelge-check.is-period .ka-cizelge-check__label,.ka-cizelge-check.is-plan .ka-cizelge-check__label{font-weight:750}.ka-cizelge-check:focus-within{outline:3px solid var(--ka-focus);outline-offset:1px}.ka-cizelge-status-control{display:grid;max-width:220px}
.ka-cizelge-event-body{display:grid;grid-template-columns:minmax(150px,220px) minmax(0,1fr);gap:10px;min-width:0}.ka-cizelge-event-body>section,.ka-cizelge-date-range{display:grid;align-content:start;gap:6px;padding:11px;border:1px solid var(--ka-border);border-radius:14px;background:var(--ka-muted-bg)}.ka-cizelge-date-range strong{font-size:15px}.ka-cizelge-date-range>span:last-child:not(.ka-cizelge-section-label){color:var(--ka-text-muted);font-size:11px}
.ka-cizelge-teacher{display:grid;gap:10px;min-width:0}.ka-cizelge-teacher__head{display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:10px;min-width:0;padding:0 3px 10px;border-bottom:1px solid var(--ka-border)}.ka-cizelge-teacher__icon{width:42px;height:42px;display:grid;place-items:center;border-radius:50%;background:var(--ka-primary-soft);color:var(--ka-primary);font-size:21px;font-weight:900}.ka-cizelge-teacher__copy{display:grid;min-width:0}.ka-cizelge-teacher__copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:17px}.ka-cizelge-teacher__copy span{color:var(--ka-text-muted);font-size:11px}.ka-cizelge-teacher__progress{min-width:56px;min-height:34px;display:inline-flex;align-items:center;justify-content:center;padding:5px 9px;border-radius:999px;background:var(--ka-primary-soft);color:var(--ka-primary);font-size:12px;font-weight:850}.ka-cizelge-record-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:10px;min-width:0}.ka-maarif-record-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:10px;min-width:0}
.ka-cizelge-document-meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.ka-cizelge-document-meta span{display:inline-flex;align-items:center;min-height:28px;padding:4px 8px;border-radius:999px;background:var(--ka-muted-bg);color:var(--ka-text-muted);font-size:10px;font-weight:750}
[data-theme="dark"] .ka-cizelge-page-head{background:radial-gradient(circle at 90% 0,rgba(83,214,164,.10),transparent 34%),linear-gradient(145deg,#102019,#0c1612)}[data-theme="dark"] .ka-cizelge-action,[data-theme="dark"] .ka-cizelge-card,[data-theme="dark"] .ka-cizelge-chip,[data-theme="dark"] .ka-cizelge-check{background:#101d18}[data-theme="dark"] .ka-cizelge-action.is-primary,[data-theme="dark"] .ka-cizelge-check.is-checked{background:#123126}[data-theme="dark"] .ka-cizelge-detail-grid>section,[data-theme="dark"] .ka-cizelge-date-grid>div,[data-theme="dark"] .ka-cizelge-note,[data-theme="dark"] .ka-cizelge-event-body>section,[data-theme="dark"] .ka-cizelge-date-range{background:#12221b}
@media(max-width:760px){.ka-cizelge-page-head{padding:17px;border-radius:20px}.ka-cizelge-action-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ka-cizelge-action{min-height:70px;grid-template-columns:36px minmax(0,1fr) 14px;padding:9px}.ka-cizelge-action__icon{width:36px;height:36px;border-radius:11px;font-size:16px}.ka-cizelge-action__copy strong{font-size:12px}.ka-cizelge-action__copy small{font-size:9px}.ka-cizelge-main-grid{grid-template-columns:1fr}.ka-cizelge-record-grid,.ka-maarif-record-grid{grid-template-columns:1fr}.ka-cizelge-card{padding:14px;border-radius:18px}.ka-cizelge-check-grid.is-month-grid{grid-template-columns:repeat(5,minmax(0,1fr))}.ka-cizelge-check{padding:6px;gap:5px}.ka-cizelge-check__label{font-size:10px}.ka-cizelge-date-grid.is-three{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:520px){.ka-cizelge-page-head__intro{grid-template-columns:46px minmax(0,1fr);gap:10px}.ka-cizelge-page-head__icon{width:46px;height:46px;border-radius:14px;font-size:22px}.ka-cizelge-page-head__copy p{font-size:12px}.ka-cizelge-action__copy small{display:none}.ka-cizelge-card__head{align-items:center}.ka-cizelge-card__head-actions{gap:5px}.ka-cizelge-progress{display:none}.ka-cizelge-edit{min-height:36px;padding-inline:9px}.ka-cizelge-detail-grid,.ka-cizelge-event-body{grid-template-columns:1fr}.ka-cizelge-date-grid.is-three{grid-template-columns:1fr 1fr}.ka-cizelge-check-grid.is-month-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.ka-cizelge-check-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ka-cizelge-status-control{max-width:none}.ka-cizelge-teacher__head{grid-template-columns:38px minmax(0,1fr) auto}.ka-cizelge-teacher__icon{width:38px;height:38px;font-size:19px}.ka-cizelge-teacher__progress{min-width:50px;padding-inline:7px}}
@media(max-width:390px){.ka-cizelge-action-grid{grid-template-columns:1fr}.ka-cizelge-action{min-height:62px}.ka-cizelge-date-grid,.ka-cizelge-date-grid.is-three{grid-template-columns:1fr}.ka-cizelge-check-grid.is-month-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.ka-cizelge-card__identity{grid-template-columns:36px minmax(0,1fr)}.ka-cizelge-card__icon{width:36px;height:36px;border-radius:11px;font-size:18px}.ka-cizelge-edit span:last-child{display:none}}
'''
css_path.write_text(css,encoding='utf-8')

# Update the Maarif visible contract to the new responsive card matrix while preserving real model/toggle semantics.
Path('tests/maarif-matrix-visible-parity.test.js').write_text(r'''const fs=require('fs');
const assert=require('assert');
const rubric=fs.readFileSync('js/modules/rubric-settings.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
assert(rubric.includes('function maarifMatrix(rows)'),'Maarif görünümü öğretmen bazlı canonical matris renderer kullanmalı.');
assert(rubric.includes('aria-label="DERS / SINIF aylık rapor matrisi"')&&rubric.includes('CONTROLS.maarifRapor||[]'),'Maarif matrisi ders/sınıf ve 10 aylık kontrol yapısını korumalı.');
assert(rubric.includes('groups=new Map')&&rubric.includes('if(!r.ogretmenId)return'),'Maarif kayıtları mevcut davranıştaki gibi öğretmen bazında gruplanmalı.');
assert(rubric.includes("sorted.length*labels.length")&&rubric.includes("filter(Boolean).length"),'Öğretmen grup başlığı toplam ilerlemeyi göstermeli.');
assert(rubric.includes("String(a.ders||'').localeCompare")&&rubric.includes("String(a.sinif||'').localeCompare"),'Maarif kayıtları ders ve sınıfa göre sıralanmalı.');
assert(rubric.includes('data-cizelge-check data-type="${type}"')&&rubric.includes('data-index="${i}"'),'Aylık kontroller mevcut canonical toggle akışını kullanmalı.');
assert(rubric.includes("editButton('maarifRapor',r.id)"),'Maarif kayıtlarında mevcut düzenleme davranışı korunmalı.');
assert(rubric.includes("if(type==='maarifRapor')return maarifMatrix(rows);"),'Maarif sayfası canonical responsive matris görünümüne yönlenmeli.');
assert(rubric.includes('ka-maarif-record-grid')&&rubric.includes('ka-maarif-card'),'Maarif sabit geniş tablo yerine responsive kart matrisi kullanmalı.');
assert(!rubric.includes('style="min-width:980px"'),'Maarif görünümü sabit 980px yatay tabloya geri dönmemeli.');
assert(css.includes('.ka-maarif-record-grid')&&css.includes('@media(max-width:520px)'),'Maarif responsive kuralları merkezi design-system içinde olmalı.');
console.log('Maarif responsive teacher matrix visible parity OK');
''',encoding='utf-8')

Path('tests/cizelge-modern-pages-redesign.test.js').write_text(r'''const fs=require('fs');
const assert=require('assert');
const rubric=fs.readFileSync('js/modules/rubric-settings.js','utf8');
const css=fs.readFileSync('css/design-system.css','utf8');
for(const type of ['sosyalKulupler','belirliGunler','zumre','sok','bepPlani','maarifRapor','digerEvrak'])assert(rubric.includes(`${type}:`),`Sayfa UI metası eksik: ${type}`);
assert(rubric.includes('function modernPageHead(type)')&&rubric.includes('ka-cizelge-page-head'),'Yedi çizelge sayfası ortak responsive başlık rendererını kullanmalı.');
for(const token of ['data-cizelge-report','data-cizelge-excel','data-cizelge-bulk','data-cizelge-add','data-cizelge-edit','data-cizelge-check'])assert(rubric.includes(token),`Mevcut davranış kancası korunmalı: ${token}`);
assert(rubric.includes('data-club-student-edit')&&rubric.includes('data-club-student-list'),'Sosyal kulüp öğrenci yönetimi korunmalı.');
assert(rubric.includes("controlGrid('sosyalKulupler',r)")&&rubric.includes("controlGrid('belirliGunler',r)")&&rubric.includes("controlGrid('maarifRapor',r)"),'Gerçek kontrol dizileri yeni kartlarda kullanılmalı.');
assert(rubric.includes('genericCard(type,r,false)')&&rubric.includes('data-cizelge-teacher-group='),'Zümre, ŞÖK ve BEP öğretmen gruplaması korunmalı.');
assert(rubric.includes("if(type==='rehberlik')return guidanceTeacherGroupedList(rows)"),'Mevcut Rehberlik özel rendererı korunmalı.');
assert(rubric.includes("if(TEACHER_GROUPED_TYPES.has(type))return teacherGroupedList(type,rows);"),'Dönem sayfaları canonical öğretmen gruplu rendererı kullanmalı.');
assert(rubric.includes('ka-cizelge-main-grid')&&rubric.includes('ka-cizelge-event-list')&&rubric.includes('ka-maarif-record-grid'),'Sayfa türlerine uygun responsive liste/grid yüzeyleri bulunmalı.');
for(const field of ['yillikPlanTarihi','toplumHizmetiTarihi','tarihBaslangic','tarihBitis','tarih1','tarih2','tarih3','yillikDersPlaniTarihi','bepPlaniTarihi','teslimEdildi','kontroller'])assert(rubric.includes(field),`Gerçek veri alanı korunmalı: ${field}`);
assert(css.includes('/* Çizelge pages — shared responsive document tracking workspace. */'),'Ortak sayfa tasarımı merkezi design-system içinde olmalı.');
assert(css.includes('[data-classic-cizelge-page="sosyalKulupler"]')&&css.includes('[data-classic-cizelge-page="digerEvrak"]'),'Tüm yeni sayfalar merkezi responsive kapsamda olmalı.');
assert(css.includes('@media(max-width:760px)')&&css.includes('@media(max-width:520px)')&&css.includes('@media(max-width:390px)'),'Telefon kırılımları tanımlı olmalı.');
console.log('Seven schedule/document pages responsive redesign OK');
''',encoding='utf-8')

sw=Path('service-worker.js')
sw_text=sw.read_text(encoding='utf-8')
if "const CACHE_ADI='oy-cache-v824';" not in sw_text:
    raise RuntimeError('service worker cache version anchor not found')
sw.write_text(sw_text.replace("const CACHE_ADI='oy-cache-v824';","const CACHE_ADI='oy-cache-v825';",1),encoding='utf-8')
