from pathlib import Path

repo=Path('.')
design_path=repo/'css/design-system.css'
design=design_path.read_text(encoding='utf-8')
marker='/* MEVZUAT WORKSPACE — LOCAL-FIRST REDESIGN */'
css=r'''

/* MEVZUAT WORKSPACE — LOCAL-FIRST REDESIGN */
.ka-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
.ka-legislation-page{width:100%;max-width:820px;margin:0 auto;padding:3px 5px 22px;display:flex;flex-direction:column;gap:10px}
.ka-legislation-hero{position:relative;overflow:hidden;min-height:118px;padding:16px;border:1px solid var(--ka-hero-border);border-radius:23px;background:var(--ka-hero-bg);box-shadow:var(--ka-shadow-sm);display:grid;grid-template-columns:50px minmax(0,1fr) auto;align-items:center;gap:13px}
.ka-legislation-hero::after{content:"";position:absolute;right:-42px;top:-62px;width:150px;height:150px;border-radius:50%;background:color-mix(in srgb,var(--ka-primary) 6%,transparent);pointer-events:none}
.ka-legislation-hero__icon{position:relative;z-index:1;width:50px;height:50px;border-radius:16px;background:var(--ka-primary);color:var(--ka-button-text);display:grid;place-items:center;font-size:25px;box-shadow:0 6px 16px color-mix(in srgb,var(--ka-primary) 22%,transparent)}
.ka-legislation-hero__copy{position:relative;z-index:1;min-width:0}.ka-legislation-kicker{display:block;color:var(--ka-primary);font-size:8px;font-weight:950;letter-spacing:.12em}.ka-legislation-hero h2{margin-top:3px;font-size:20px;letter-spacing:-.02em}.ka-legislation-hero p{max-width:540px;margin-top:5px;color:var(--ka-text-muted);font-size:10.5px;line-height:1.42}
.ka-legislation-local-badge{position:relative;z-index:1;min-height:30px;padding:5px 9px;border:1px solid color-mix(in srgb,var(--ka-primary) 22%,var(--ka-border));border-radius:999px;background:var(--ka-primary-soft);color:var(--ka-primary);display:inline-flex;align-items:center;gap:5px;font-size:8.5px;font-weight:900;white-space:nowrap}
.ka-legislation-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.ka-legislation-summary article{min-width:0;min-height:62px;padding:8px 9px;border:1px solid var(--ka-border);border-radius:15px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm);display:grid;grid-template-columns:31px minmax(0,1fr);align-items:center;gap:7px}.ka-legislation-summary article>span{width:31px;height:31px;border-radius:10px;background:var(--ka-primary-soft);color:var(--ka-primary);display:grid;place-items:center;font-size:14px}.ka-legislation-summary article>div{min-width:0;display:flex;flex-direction:column}.ka-legislation-summary small{color:var(--ka-text-muted);font-size:7.5px;font-weight:900;letter-spacing:.04em}.ka-legislation-summary b{margin-top:1px;color:var(--ka-text);font-size:17px;line-height:1.05;font-variant-numeric:tabular-nums}
.ka-legislation-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ka-legislation-action{appearance:none;min-width:0;min-height:62px;padding:8px 10px;border:1px solid var(--ka-border);border-radius:16px;background:var(--ka-card-bg);color:var(--ka-text);box-shadow:var(--ka-shadow-sm);display:grid;grid-template-columns:36px minmax(0,1fr);align-items:center;gap:8px;text-align:left;cursor:pointer;transition:transform var(--ka-transition-fast),border-color var(--ka-transition-fast),box-shadow var(--ka-transition-fast),background var(--ka-transition-fast)}.ka-legislation-action:hover{border-color:color-mix(in srgb,var(--ka-primary) 40%,var(--ka-border));box-shadow:var(--ka-shadow-md)}.ka-legislation-action:active{transform:scale(.985)}.ka-legislation-action:focus-visible{outline:3px solid var(--ka-focus);outline-offset:1px}.ka-legislation-action__icon{width:36px;height:36px;border-radius:12px;background:var(--ka-primary-soft);color:var(--ka-primary);display:grid;place-items:center;font-size:17px;font-weight:950}.ka-legislation-action>span:last-child{min-width:0;display:flex;flex-direction:column;gap:2px}.ka-legislation-action strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ka-text);font-size:10.5px;font-weight:900}.ka-legislation-action small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ka-text-muted);font-size:8px}.ka-legislation-action--primary{border-color:var(--ka-primary);background:var(--ka-primary);color:var(--ka-button-text)}.ka-legislation-action--primary .ka-legislation-action__icon{background:color-mix(in srgb,var(--ka-button-text) 14%,transparent);color:var(--ka-button-text)}.ka-legislation-action--primary strong,.ka-legislation-action--primary small{color:var(--ka-button-text)}.ka-legislation-action--primary small{opacity:.78}
.ka-legislation-switch{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px;padding:4px;border:1px solid var(--ka-border);border-radius:15px;background:var(--ka-muted-bg)}.ka-legislation-switch>button{appearance:none;min-width:0;min-height:39px;padding:5px 8px;border:0;border-radius:11px;background:transparent;color:var(--ka-text-muted);display:flex;align-items:center;justify-content:center;gap:6px;font-size:10.5px;font-weight:850;cursor:pointer}.ka-legislation-switch>button.active,.ka-legislation-switch>button[aria-selected="true"]{background:var(--ka-card-bg);color:var(--ka-primary);box-shadow:var(--ka-shadow-sm)}.ka-legislation-switch em{min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:var(--ka-muted-bg);color:var(--ka-text-muted);display:grid;place-items:center;font-size:7.5px;font-style:normal;font-weight:900}.ka-legislation-switch>button.active em{background:var(--ka-primary-soft);color:var(--ka-primary)}
.ka-legislation-surface{display:grid;gap:8px}.ka-legislation-surface__head{min-height:48px;padding:3px 3px 0;display:flex;align-items:flex-end;justify-content:space-between;gap:10px}.ka-legislation-surface__head>div{min-width:0}.ka-legislation-surface__head small{display:block;color:var(--ka-primary);font-size:7.5px;font-weight:950;letter-spacing:.11em}.ka-legislation-surface__head h3{margin-top:2px;font-size:15px}.ka-legislation-surface__head p{margin-top:2px;color:var(--ka-text-muted);font-size:9px;line-height:1.35}.ka-legislation-surface__head>span{flex:0 0 auto;padding:5px 7px;border-radius:9px;background:var(--ka-primary-soft);color:var(--ka-primary);font-size:8px;font-weight:900}
.ka-legislation-search{min-height:48px;padding:0 7px 0 12px;border:1px solid var(--ka-input-border);border-radius:15px;background:var(--ka-input-bg);box-shadow:var(--ka-shadow-sm);display:grid;grid-template-columns:21px minmax(0,1fr) 31px;align-items:center;gap:6px}.ka-legislation-search:focus-within{border-color:var(--ka-input-focus);box-shadow:0 0 0 3px var(--ka-focus),var(--ka-shadow-sm)}.ka-legislation-search>span{color:var(--ka-primary);font-size:20px;line-height:1}.ka-legislation-search input{min-width:0;min-height:44px!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;font-size:12px}.ka-legislation-search button{width:31px;height:31px;border:0;border-radius:10px;background:var(--ka-muted-bg);color:var(--ka-text-muted);display:grid;place-items:center;font-size:17px;cursor:pointer}
.ka-legislation-list{display:grid;gap:7px}.ka-legislation-source{min-width:0;min-height:72px;padding:9px 9px 9px 10px;border:1px solid var(--ka-border);border-radius:17px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm);display:grid;grid-template-columns:39px minmax(0,1fr) auto;align-items:center;gap:9px;transition:border-color var(--ka-transition-fast),box-shadow var(--ka-transition-fast)}.ka-legislation-source:hover{border-color:color-mix(in srgb,var(--ka-primary) 34%,var(--ka-border));box-shadow:var(--ka-shadow-md)}.ka-legislation-source__icon{width:39px;height:39px;border-radius:12px;background:var(--ka-primary-soft);color:var(--ka-primary);display:grid;place-items:center;font-size:20px;font-family:Georgia,serif;font-weight:800}.ka-legislation-source__copy{min-width:0}.ka-legislation-source__title{min-width:0;display:flex;align-items:center;gap:6px}.ka-legislation-source__title strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ka-text);font-size:11.5px}.ka-legislation-source__title span{flex:0 0 auto;max-width:95px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:3px 6px;border-radius:999px;background:var(--ka-muted-bg);color:var(--ka-text-muted);font-size:7px;font-weight:850}.ka-legislation-source__meta{margin-top:5px;display:flex;align-items:center;gap:7px;flex-wrap:wrap;color:var(--ka-text-muted);font-size:8px;line-height:1.25}.ka-legislation-source__meta span{min-width:0;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ka-legislation-delete{appearance:none;min-width:34px;height:34px;padding:0 7px;border:1px solid color-mix(in srgb,var(--ka-danger) 22%,var(--ka-border));border-radius:11px;background:color-mix(in srgb,var(--ka-danger) 7%,var(--ka-card-bg));color:var(--ka-danger);display:inline-flex;align-items:center;justify-content:center;gap:4px;font-size:10px;font-weight:850;cursor:pointer}.ka-legislation-delete span{font-size:8px}
.ka-legislation-empty{min-height:178px;padding:22px 18px;border:1px dashed var(--ka-border-strong);border-radius:19px;background:color-mix(in srgb,var(--ka-muted-bg) 55%,transparent);color:var(--ka-text-muted);display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.ka-legislation-empty>span{width:48px;height:48px;border-radius:15px;background:var(--ka-primary-soft);color:var(--ka-primary);display:grid;place-items:center;font-size:23px}.ka-legislation-empty>strong{margin-top:9px;color:var(--ka-text);font-size:13px}.ka-legislation-empty>p{max-width:320px;margin-top:4px;font-size:9.5px;line-height:1.42}.ka-legislation-empty>.ka-btn{min-height:38px;margin-top:12px;font-size:9.5px}.ka-legislation-empty--search{min-height:150px}
.ka-legislation-chat{height:min(60vh,640px);min-height:430px;overflow:hidden;border:1px solid var(--ka-border);border-radius:20px;background:var(--ka-card-bg);box-shadow:var(--ka-shadow-sm);display:flex;flex-direction:column}.ka-legislation-chat__head{flex:0 0 auto;min-height:72px;padding:10px 12px;border-bottom:1px solid var(--ka-border);background:linear-gradient(135deg,var(--ka-primary-soft),var(--ka-card-bg));display:grid;grid-template-columns:36px minmax(0,1fr);align-items:center;gap:9px}.ka-legislation-chat__head>span{width:36px;height:36px;border-radius:12px;background:var(--ka-primary);color:var(--ka-button-text);display:grid;place-items:center;font-size:17px}.ka-legislation-chat__head>div{min-width:0}.ka-legislation-chat__head small{display:block;color:var(--ka-primary);font-size:7px;font-weight:950;letter-spacing:.1em}.ka-legislation-chat__head h3{margin-top:1px;font-size:13px}.ka-legislation-chat__head p{margin-top:2px;color:var(--ka-text-muted);font-size:8.5px;line-height:1.35}
.ka-legislation-messages{flex:1 1 auto;min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:11px;display:flex;flex-direction:column;gap:9px;scrollbar-width:thin}.ka-legislation-chat-welcome{margin:auto;max-width:420px;padding:22px 15px;color:var(--ka-text-muted);display:flex;flex-direction:column;align-items:center;text-align:center}.ka-legislation-chat-welcome>span{width:46px;height:46px;border-radius:15px;background:var(--ka-primary-soft);color:var(--ka-primary);display:grid;place-items:center;font-size:21px}.ka-legislation-chat-welcome>strong{margin-top:9px;color:var(--ka-text);font-size:13px}.ka-legislation-chat-welcome>p{margin-top:4px;max-width:360px;font-size:9.5px;line-height:1.45}.ka-legislation-prompts{margin-top:12px;display:flex;justify-content:center;gap:5px;flex-wrap:wrap}.ka-legislation-prompts button{min-height:31px;padding:5px 8px;border:1px solid var(--ka-border);border-radius:999px;background:var(--ka-card-bg);color:var(--ka-primary);font-size:8px;font-weight:800;cursor:pointer}
.ka-legislation-message{display:flex;align-items:flex-end;gap:6px}.ka-legislation-message--user{flex-direction:row-reverse}.ka-legislation-message__avatar{width:28px;height:28px;flex:0 0 28px;border-radius:9px;background:var(--ka-muted-bg);color:var(--ka-text-muted);display:grid;place-items:center;font-size:10px;font-weight:900}.ka-legislation-message--assistant .ka-legislation-message__avatar{background:var(--ka-primary-soft);color:var(--ka-primary)}.ka-legislation-message__bubble{max-width:min(84%,620px);padding:9px 11px;border:1px solid var(--ka-border);border-radius:14px 14px 14px 5px;background:var(--ka-muted-bg);color:var(--ka-text);font-size:10.5px;line-height:1.5;overflow-wrap:anywhere}.ka-legislation-message--user .ka-legislation-message__bubble{border-color:color-mix(in srgb,var(--ka-primary) 30%,var(--ka-border));border-radius:14px 14px 5px 14px;background:var(--ka-primary-soft)}.ka-legislation-thinking{display:flex;align-items:center;gap:4px}.ka-legislation-thinking>span{width:5px;height:5px;border-radius:50%;background:var(--ka-primary);opacity:.45;animation:ka-legislation-pulse 1.1s infinite ease-in-out}.ka-legislation-thinking>span:nth-child(2){animation-delay:.14s}.ka-legislation-thinking>span:nth-child(3){animation-delay:.28s}.ka-legislation-thinking em{margin-left:3px;color:var(--ka-text-muted);font-size:8px;font-style:normal}@keyframes ka-legislation-pulse{0%,60%,100%{transform:translateY(0);opacity:.38}30%{transform:translateY(-3px);opacity:1}}
.ka-legislation-composer{flex:0 0 auto;padding:9px;border-top:1px solid var(--ka-border);background:var(--ka-card-raised-bg);display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:7px}.ka-legislation-composer .ka-field{gap:4px}.ka-legislation-composer .ka-field__label{font-size:8.5px}.ka-legislation-composer textarea{min-height:48px;max-height:108px;padding:9px 10px;resize:none;font-size:11px;line-height:1.35}.ka-legislation-send{min-width:58px;height:48px;padding:0 10px;border:0;border-radius:13px;background:var(--ka-primary);color:var(--ka-button-text);display:flex;align-items:center;justify-content:center;gap:5px;font-size:10px;font-weight:900;cursor:pointer}.ka-legislation-send:focus-visible{outline:3px solid var(--ka-focus);outline-offset:1px}
.ka-legislation-modal{width:min(720px,100%)}.ka-legislation-modal__kicker{display:block;margin-bottom:3px;color:var(--ka-primary);font-size:8px;font-weight:950;letter-spacing:.11em}.ka-legislation-modal .ka-modal__header{align-items:flex-start}.ka-legislation-modal .ka-modal__header h2{font-size:18px}.ka-legislation-modal .ka-modal__header p{margin-top:4px;font-size:9.5px;line-height:1.4}.ka-legislation-modal__note{min-height:52px;padding:9px 10px;border:1px solid color-mix(in srgb,var(--ka-primary) 22%,var(--ka-border));border-radius:14px;background:var(--ka-primary-soft);display:grid;grid-template-columns:30px minmax(0,1fr);align-items:center;gap:8px}.ka-legislation-modal__note>span{width:30px;height:30px;border-radius:10px;background:var(--ka-card-bg);display:grid;place-items:center}.ka-legislation-modal__note strong,.ka-legislation-modal__note small{display:block}.ka-legislation-modal__note strong{font-size:10px}.ka-legislation-modal__note small{margin-top:2px;color:var(--ka-text-muted);font-size:8.5px}.ka-legislation-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ka-legislation-help{padding:9px 10px;border-radius:12px;background:var(--ka-muted-bg);color:var(--ka-text-muted);font-size:9px;line-height:1.45}
[data-theme="dark"] .ka-legislation-action--primary{box-shadow:0 8px 18px color-mix(in srgb,var(--ka-primary) 22%,transparent)}
@media(min-width:640px){.ka-legislation-summary{gap:8px}.ka-legislation-summary article{min-height:70px;padding:10px 12px}.ka-legislation-source{min-height:78px;padding:11px 12px}.ka-legislation-delete span{display:inline}}
@media(max-width:560px){.ka-legislation-page{gap:9px;padding-inline:3px}.ka-legislation-hero{min-height:108px;padding:13px;border-radius:20px;grid-template-columns:44px minmax(0,1fr);gap:10px}.ka-legislation-hero__icon{width:44px;height:44px;border-radius:14px;font-size:21px}.ka-legislation-hero h2{font-size:18px}.ka-legislation-hero p{font-size:9.5px}.ka-legislation-local-badge{grid-column:2/-1;justify-self:start;min-height:25px;padding:3px 7px;font-size:7.5px;margin-top:-4px}.ka-legislation-summary article{min-height:58px;padding:7px;grid-template-columns:28px minmax(0,1fr);gap:6px}.ka-legislation-summary article>span{width:28px;height:28px;font-size:13px}.ka-legislation-summary small{font-size:6.8px}.ka-legislation-summary b{font-size:15px}.ka-legislation-action{min-height:58px;padding:7px 8px;grid-template-columns:33px minmax(0,1fr);gap:7px}.ka-legislation-action__icon{width:33px;height:33px;border-radius:10px;font-size:15px}.ka-legislation-action strong{font-size:9.5px}.ka-legislation-action small{font-size:7.3px}.ka-legislation-switch>button{min-height:37px;font-size:9.5px}.ka-legislation-source{grid-template-columns:37px minmax(0,1fr) 34px;gap:7px;padding:8px}.ka-legislation-source__icon{width:37px;height:37px}.ka-legislation-source__title strong{font-size:10.5px}.ka-legislation-source__meta{gap:5px;font-size:7.5px}.ka-legislation-delete{width:34px;padding:0}.ka-legislation-delete span{display:none}.ka-legislation-chat{height:calc(100dvh - var(--ka-header-height) - var(--ka-bottom-nav-height) - 122px);min-height:410px;max-height:640px}.ka-legislation-chat__head{min-height:66px;padding:9px 10px}.ka-legislation-chat__head p{font-size:8px}.ka-legislation-messages{padding:9px}.ka-legislation-composer{padding:8px}.ka-legislation-composer textarea{font-size:10.5px}.ka-legislation-send{min-width:52px;padding-inline:8px}.ka-legislation-form-grid{grid-template-columns:1fr}.ka-legislation-modal-backdrop{align-items:end;padding:0}.ka-legislation-modal{width:100%;max-height:94dvh;border-radius:20px 20px 0 0}.ka-legislation-modal .ka-modal__body{padding:12px}.ka-legislation-modal .ka-modal__header,.ka-legislation-modal .ka-modal__footer{padding:12px}}
@media(max-width:360px){.ka-legislation-hero{grid-template-columns:40px minmax(0,1fr)}.ka-legislation-hero__icon{width:40px;height:40px}.ka-legislation-hero p{font-size:9px}.ka-legislation-summary article{grid-template-columns:1fr;justify-items:center;text-align:center;gap:3px}.ka-legislation-summary article>span{display:none}.ka-legislation-action strong{font-size:9px}.ka-legislation-action small{display:none}.ka-legislation-source__title span{max-width:72px}.ka-legislation-message__bubble{max-width:88%}}
'''
if marker not in design:
    design_path.write_text(design.rstrip()+css+'\n',encoding='utf-8')

# Dedicated visual contract test; engine/local-first test remains the behavioral owner.
test_path=repo/'tests/legislation-page-redesign.test.js'
test_path.write_text(r'''const fs=require('fs');
const assert=require('assert');
const ui=fs.readFileSync('js/modules/legislation-ui.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');

for(const token of [
  'ka-legislation-page','ka-legislation-hero','ka-legislation-local-badge','ka-legislation-summary',
  'ka-legislation-actions','ka-legislation-switch','ka-legislation-surface','ka-legislation-search',
  'ka-legislation-source','ka-legislation-empty','ka-legislation-chat','ka-legislation-messages',
  'ka-legislation-composer','ka-legislation-modal'
]) assert(ui.includes(token),`Yeni Mevzuat görünür çalışma alanı eksik: ${token}`);

for(const token of [
  '.ka-legislation-page{width:100%;max-width:820px',
  '.ka-legislation-hero{position:relative;overflow:hidden',
  '.ka-legislation-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))',
  '.ka-legislation-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))',
  '.ka-legislation-switch{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))',
  '.ka-legislation-chat{height:min(60vh,640px)',
  '.ka-legislation-source{min-width:0;min-height:72px',
  '@media(max-width:560px){.ka-legislation-page'
]) assert(design.includes(token),`Merkezi Mevzuat tasarım sözleşmesi eksik: ${token}`);

assert(ui.includes('data-legislation-stat="records"')&&ui.includes('data-legislation-stat="sections"')&&ui.includes('data-legislation-stat="categories"'),'Mevzuat özet sayaçları bulunmalı.');
assert(ui.includes('function visibleRows()')&&ui.includes('legislationSourceSearch'),'Yerel arşiv filtresi korunmalı.');
assert(ui.includes('data-legislation-prompt')&&ui.includes('ka-legislation-chat-welcome'),'Soru ekranında başlangıç yönlendirmesi bulunmalı.');
assert(ui.includes('Cihazda saklanır')&&ui.includes("hiçbir veri Firestore'a gitmez"),'Yerel saklama güvencesi görünür olmalı.');
assert(!ui.includes('style="'),'Mevzuat sayfası görünür stil sahipliğini JS içinde inline olarak taşımamalı.');
assert(!ui.includes('db.collection(')&&!ui.includes('firebase.firestore'),'Mevzuat presentation Firestore kullanmamalı.');
for(const call of ['engine().list()','engine().add({baslik,kaynak,kategori,metin})','engine().importJson(parsed)','engine().remove(b.dataset.legislationDelete)','engine().ask(q)']) assert(ui.includes(call),`Canonical LegislationEngine çağrısı korunmalı: ${call}`);
console.log('Mevzuat mobil çalışma alanı + merkezi tasarım sözleşmesi başarılı.');
''',encoding='utf-8')
print('Legislation redesign CSS and test installed.')
