/* Koruk Asistan — Mesajlaşma Service
 * İş kuralları/yetki. Veri erişimi yalnız MesajlasmaRepository üzerinden.
 */
const MesajlasmaService = {
  _yetkiKontrol(){if(!duzenleyebilir('mesajlasma')){toast('Bu işlem için yetkiniz yok.');return false;}return true;},
  _kendiKimlik(){const k=typeof _hesapKimligi==='function'?_hesapKimligi():{ad:'',fotoUrl:''};return{uid:(typeof AKTIF_KULLANICI!=='undefined'&&AKTIF_KULLANICI)?AKTIF_KULLANICI.uid:null,ad:k.ad||'Kullanıcı',foto:k.fotoUrl||''};},
  async _ogretmenUidBul(ogretmenId){const snap=await MesajlasmaRepository.kullaniciUidBulOgretmenId(ogretmenId);return snap.empty?null:snap.docs[0].id;},
  async konusmaBaslatOgretmenIle(ogretmenId,ogretmenAdi,mevcutKonusmalar,ogretmenFotoUrl){if(!this._yetkiKontrol())throw new Error('yetkisiz');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');const digerUid=await this._ogretmenUidBul(ogretmenId);if(!digerUid)throw new Error('hesap-yok');if(digerUid===ben.uid)throw new Error('kendine-mesaj');const varOlan=(mevcutKonusmalar||[]).find(k=>!k.grupMu&&k.katilimciUidler?.length===2&&k.katilimciUidler.includes(ben.uid)&&k.katilimciUidler.includes(digerUid));if(varOlan)return varOlan.id;const ref=await MesajlasmaRepository.konusmaOlustur({katilimciUidler:[ben.uid,digerUid],katilimciAdlari:{[ben.uid]:ben.ad,[digerUid]:ogretmenAdi},katilimciFotolari:{[ben.uid]:ben.foto||'',[digerUid]:ogretmenFotoUrl||''},grupMu:false,sonMesaj:null,okunmayanlar:{[ben.uid]:0,[digerUid]:0}});return ref.id;},
  async grupOlustur(grupAdi,katilimcilar){if(!this._yetkiKontrol())throw new Error('yetkisiz');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');if(!grupAdi?.trim())throw new Error('grup-adi-gerekli');if(!katilimcilar?.length)throw new Error('katilimci-gerekli');const ids=[ben.uid,...katilimcilar.map(k=>k.uid)],adlar={[ben.uid]:ben.ad},fotolar={[ben.uid]:ben.foto||''},ok={[ben.uid]:0};katilimcilar.forEach(k=>{adlar[k.uid]=k.ad;fotolar[k.uid]=k.foto||'';ok[k.uid]=0;});const ref=await MesajlasmaRepository.konusmaOlustur({katilimciUidler:ids,katilimciAdlari:adlar,katilimciFotolari:fotolar,grupMu:true,grupAdi:grupAdi.trim(),sonMesaj:null,okunmayanlar:ok});return ref.id;},
  async mesajGonder(konusmaId,metin,mevcutKonusma){if(!this._yetkiKontrol())throw new Error('yetkisiz');const temiz=(metin||'').trim();if(!temiz)throw new Error('mesaj-bos');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');await MesajlasmaRepository.mesajEkle({konusmaId,gonderenUid:ben.uid,gonderenAdi:ben.ad,metin:temiz});const ok={...(mevcutKonusma?.okunmayanlar||{})};(mevcutKonusma?.katilimciUidler||[]).forEach(u=>ok[u]=u===ben.uid?0:(ok[u]||0)+1);return MesajlasmaRepository.konusmaGuncelle(konusmaId,{sonMesaj:{metin:temiz,gonderenUid:ben.uid,tarih:new Date().toISOString()},guncellenmeTarihi:new Date().toISOString(),okunmayanlar:ok});},
  okunduIsaretle(konusmaId,mevcutKonusma){const ben=this._kendiKimlik();if(!ben.uid||!mevcutKonusma?.okunmayanlar?.[ben.uid])return Promise.resolve();return MesajlasmaRepository.konusmaGuncelle(konusmaId,{okunmayanlar:{...mevcutKonusma.okunmayanlar,[ben.uid]:0}});},
  _IZIN_VERILEN_TURLER:{'application/pdf':{etiket:'PDF',ikon:'📕'},'application/msword':{etiket:'Word',ikon:'📘'},'application/vnd.openxmlformats-officedocument.wordprocessingml.document':{etiket:'Word',ikon:'📘'},'application/vnd.ms-excel':{etiket:'Excel',ikon:'📗'},'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':{etiket:'Excel',ikon:'📗'},'image/jpeg':{etiket:'Resim',ikon:'🖼️',gorselMi:true},'image/png':{etiket:'Resim',ikon:'🖼️',gorselMi:true},'image/gif':{etiket:'Resim',ikon:'🖼️',gorselMi:true},'image/webp':{etiket:'Resim',ikon:'🖼️',gorselMi:true}},
  _MAKS_DOSYA_BOYUTU:10*1024*1024,
  dosyaTuruBilgisi(t){return this._IZIN_VERILEN_TURLER[t]||null;},
  async mesajGonderDosyaIle(konusmaId,dosya,mevcutKonusma,ilerlemeCb){if(!this._yetkiKontrol())throw new Error('yetkisiz');const tur=this.dosyaTuruBilgisi(dosya.type);if(!tur)throw new Error('desteklenmeyen-tur');if(dosya.size>this._MAKS_DOSYA_BOYUTU)throw new Error('dosya-cok-buyuk');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');if(typeof DepolamaSinirService!=='undefined'){const izin=await DepolamaSinirService.yuklemeIzniVarMi('mesaj',dosya.size);if(!izin.izinVar)throw new Error('depolama-siniri:'+izin.mesaj);}const{url,storagePath}=await MesajlasmaRepository.dosyaYukle(konusmaId,dosya,ilerlemeCb);if(typeof IstatistikService!=='undefined')IstatistikService.depolamaKullanimEkle('mesaj',dosya.size);await MesajlasmaRepository.mesajEkle({konusmaId,gonderenUid:ben.uid,gonderenAdi:ben.ad,metin:'',dosya:{ad:dosya.name,url,storagePath,tur:dosya.type,boyut:dosya.size,etiket:tur.etiket,gorselMi:!!tur.gorselMi}});const ok={...(mevcutKonusma?.okunmayanlar||{})};(mevcutKonusma?.katilimciUidler||[]).forEach(u=>ok[u]=u===ben.uid?0:(ok[u]||0)+1);return MesajlasmaRepository.konusmaGuncelle(konusmaId,{sonMesaj:{metin:`${tur.ikon} ${dosya.name}`,gonderenUid:ben.uid,tarih:new Date().toISOString()},guncellenmeTarihi:new Date().toISOString(),okunmayanlar:ok});},
  toplamOkunmayan(konusmalar){const ben=this._kendiKimlik();return ben.uid?(konusmalar||[]).reduce((t,k)=>t+((k.okunmayanlar&&k.okunmayanlar[ben.uid])||0),0):0;},
  mesajSilinebilirMi(m){if(typeof AKTIF_KULLANICI!=='undefined'&&AKTIF_KULLANICI?.admin)return true;const ben=this._kendiKimlik();return!!(ben.uid&&m&&m.gonderenUid===ben.uid);},
  async mesajSil(mesaj){if(!this.mesajSilinebilirMi(mesaj))throw new Error('sahip-degil');if(mesaj.dosya?.storagePath){await MesajlasmaRepository.dosyaSil(mesaj.dosya.storagePath).catch(()=>{});if(mesaj.dosya.boyut&&typeof IstatistikService!=='undefined')IstatistikService.depolamaKullanimCikarUid(mesaj.gonderenUid,'mesaj',mesaj.dosya.boyut);}return MesajlasmaRepository.mesajSil(mesaj.id,mesaj.konusmaId);},
  async konusmaSil(konusmaId,mevcutKonusma){if(!this._yetkiKontrol())throw new Error('yetkisiz');const ben=this._kendiKimlik(),katilimciMi=mevcutKonusma&&(mevcutKonusma.katilimciUidler||[]).includes(ben.uid),adminMi=typeof AKTIF_KULLANICI!=='undefined'&&AKTIF_KULLANICI?.admin;if(!katilimciMi&&!adminMi)throw new Error('sahip-degil');const{kullaniciBazliBayt}=await MesajlasmaRepository.mesajlariTopluSil(konusmaId);if(kullaniciBazliBayt&&typeof IstatistikService!=='undefined')Object.entries(kullaniciBazliBayt).forEach(([u,b])=>IstatistikService.depolamaKullanimCikarUid(u,'mesaj',b));return MesajlasmaRepository.konusmaSil(konusmaId);}
};
