/* Koruk Asistan v2 — Academic UI
   Tek UI sahibi: yazılılar + denemeler + yıllık planlar + akademik takvim.
   UI yalnız AppStore/IndexedDB okur; Firestore erişimi SyncEngine arka planındadır. */
(function(){
'use strict';
if(window.AcademicModule)return;
let active='written',query='',mounted=false,unsubs=[],timer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const match=vals=>{const q=norm(query.trim());return !q||norm(vals.filter(Boolean).join(' ')).includes(q)};
function date(v){if(!v)return'—';const d=new Date(String(v).length===10?v+'T00:00:00':v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR')}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function totalMin(d){if(!d)return 0;if(d.oturumTuru==='İki Oturum')return (Number(d.sozelSuresiDk)||0)+(Number(d.araSureDk)||0)+(Number(d.sayisalSuresiDk)||0);return Number(d.sinavSuresiDk)||0}
function fmtSec(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor((sec%3600)/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function timerState(d){const mins=totalMin(d),run=d?.sayacDurumu?.aktif===true,start=d?.sayacDurumu?.baslatmaTarihi?new Date(d.sayacDurumu.baslatmaTarihi).getTime():0;if(!run)return{run:false,valid:mins>0&&d?.tarih===today(),remaining:mins*60,label:mins>0?'Hazır':'Süre eksik'};if(!start||mins<=0)return{run:true,valid:false,remaining:0,label:'Sayaç bilgisi geçersiz'};const elapsed=(Date.now()-start)/1000,total=mins*60,remaining=Math.max(0,total-elapsed);if(d.oturumTuru==='İki Oturum'){const verbal=(Number(d.sozelSuresiDk)||0)*60,br=(Number(d.araSureDk)||0)*60;if(elapsed<verbal)return{run:true,remaining,label:'Sözel oturum'};if(elapsed<verbal+br)return{run:true,remaining,label:'Ara'};return{run:true,remaining,label:remaining>0?'Sayısal oturum':'Tamamlandı'}}return{run:true,remaining,label:remaining>0?'Sınav sürüyor':'Tamamlandı'}}
const syncDefs=()=>({yillikPlanBasliklari:window.COL?.yillikPlanBasliklari,yillikPlanTanimlari:window.COL?.yillikPlanTanimlari,ogretmenYillikPlanSecimleri:window.COL?.ogretmenYillikPlanSecimleri,yillikPlanNotlari:window.COL?.yillikPlanNotlari,dersSaatleri:window.COL?.dersSaatleri,akademikTakvim:window.COL?.akademikTakvim,denemeSonuclari:window.COL?.denemeSonuclari,testSonuclari:window.COL?.testSonuclari});
async function prepareLocal(){if(!window.SyncEngine)return;const defs=syncDefs(),types=[];Object.entries(defs).forEach(([type,col])=>{if(col){SyncEngine.register(type,col);types.push(type)}});if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(80)}}
function shell(){return `<section class="ka-stack" data-academic-module><div class="ka-row ka-row--between"><div><h2>Akademik</h2><p class="ka-muted">Sınavlar ve planlar önce cihaz verisinden gösterilir.</p></div><span id="academicCount" class="ka-badge"></span></div><div class="ka-tabs" role="tablist"><button class="ka-tab" data-academic-tab="written" type="button">Yazılılar</button><button class="ka-tab" data-academic-tab="trial" type="button">Denemeler</button><button class="ka-tab" data-academic-tab="plans" type="button">Yıllık Planlar</button><button class="ka-tab" data-academic-tab="calendar" type="button">Takvim</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="academicSearch" type="search" placeholder="Sınav, ders, sınıf veya plan ara…"></label><div id="academicContent" class="ka-stack"></div></section>`}
function written(){const list=arr('sinavlar').filter(s=>match([s.ders,s.sinif,s.siniflar,s.donem,s.tur,s.tarih])).sort((a,b)=>(b.tarih||'').localeCompare(a.tarih||''));return{count:list.length,html:list.length?list.map(s=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(s.ders||'Yazılı sınav')}</strong><div class="ka-muted">${esc(s.siniflar||s.sinif||'Sınıf belirtilmemiş')} · ${esc([s.donem,s.yaziliSirasi].filter(Boolean).join(' · ')||'Yazılı')}</div></div><span class="ka-badge">${esc(date(s.tarih))}</span></div></article>`).join(''):'<div class="ka-empty">Yazılı sınav kaydı bulunamadı.</div>'}}
function canControl(d){const u=window.AKTIF_KULLANICI||window.AppStore?.get?.('session.user')||{};return !!(u.admin||d?.sahipUid===u.uid)}
async function toggleTrial(id){const d=arr('denemeSinavlari').find(x=>x.id===id);if(!d)return;const st=timerState(d);try{if(d.sayacDurumu?.aktif)await window.SinavlarService?.denemeSayacDurdur?.(id,d);else{if(!st.valid){window.toast?.(totalMin(d)<=0?'Sınav süresi 0 olamaz.':'Sayaç yalnızca sınav tarihinde başlatılabilir.');return;}await window.SinavlarService?.denemeSayacBaslat?.(id,d);}}catch(e){if(e?.message!=='yetkisiz')window.toast?.('Sayaç işlemi başarısız: '+(e?.message||e));}}
function trials(){const list=arr('denemeSinavlari').filter(s=>match([s.ad,s.sinflar,s.siniflar,s.tarih])).sort((a,b)=>(b.tarih||'').localeCompare(a.tarih||''));return{count:list.length,html:list.length?list.map(s=>{const st=timerState(s),ctrl=canControl(s),running=s.sayacDurumu?.aktif===true;return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row"><div class="ka-grow"><strong>${esc(s.ad||'Deneme sınavı')}</strong><div class="ka-muted">${esc(s.sinflar||s.siniflar||'')} · ${esc(date(s.tarih))} · ${totalMin(s)} dk</div></div><span class="ka-badge">${esc(st.label)}</span></div>${running?`<div class="ka-row ka-row--between"><strong>${esc(fmtSec(st.remaining))}</strong><span class="ka-muted">kalan süre</span></div>`:''}${ctrl?`<button class="ka-btn ${running?'ka-btn--ghost':''}" type="button" data-trial-toggle="${esc(s.id)}" ${!running&&!st.valid?'disabled':''}>${running?'Durdur':'Başlat'}</button>`:''}</div></article>`}).join(''):'<div class="ka-empty">Deneme sınavı kaydı bulunamadı.</div>'}}
function plans(){const list=arr('yillikPlanTanimlari').filter(p=>match([p.dersAdi,p.seviye,p.egitimOgretimYili])).sort((a,b)=>(a.dersAdi||'').localeCompare(b.dersAdi||'','tr'));return{count:list.length,html:list.length?list.map(p=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(p.dersAdi||'Yıllık plan')}</strong><div class="ka-muted">${esc(p.seviye?`${p.seviye}. sınıf`:'')} ${p.egitimOgretimYili?'· '+esc(p.egitimOgretimYili):''}</div></div><span class="ka-badge">${Array.isArray(p.satirlar)?p.satirlar.length:0} hafta</span></div></article>`).join(''):'<div class="ka-empty">Yıllık plan bulunamadı.</div>'}}
function calendar(){const docs=arr('akademikTakvim'),d=docs.find(x=>x.id==='aktif')||docs[0];return{count:d?1:0,html:d?`<article class="ka-card"><div class="ka-card__body ka-stack"><strong>Akademik Takvim</strong><div class="ka-muted">${esc(d.dosyaAdi||d.baslik||'Aktif okul çalışma takvimi')}</div>${d.gorselUrl?`<img class="ka-media" src="${esc(d.gorselUrl)}" alt="Akademik Takvim" loading="lazy">`:''}</div></article>`:'<div class="ka-empty">Akademik takvim yüklenmemiş.</div>'}}
function render(){if(!mounted)return;document.querySelectorAll('[data-academic-tab]').forEach(b=>b.classList.toggle('active',b.dataset.academicTab===active));const r=active==='trial'?trials():active==='plans'?plans():active==='calendar'?calendar():written();const out=document.getElementById('academicContent'),c=document.getElementById('academicCount');if(out)out.innerHTML=r.html;if(c)c.textContent=`${r.count} kayıt`;if(active==='trial'&&out)out.querySelectorAll('[data-trial-toggle]').forEach(b=>b.onclick=()=>toggleTrial(b.dataset.trialToggle))}
function bind(){document.querySelectorAll('[data-academic-tab]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.academicTab;render()}));const s=document.getElementById('academicSearch');if(s)s.addEventListener('input',()=>{query=s.value;render()})}
function subscribe(){unsubs.forEach(fn=>{try{fn()}catch(_){}});unsubs=[];['data.sinavlar','data.denemeSinavlari','data.yillikPlanTanimlari','data.akademikTakvim'].forEach(p=>{const u=window.AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();clearInterval(timer);timer=setInterval(()=>{if(mounted&&active==='trial'&&arr('denemeSinavlari').some(x=>x.sayacDurumu?.aktif))render()},1000);return true}
function unmount(){mounted=false;unsubs.forEach(fn=>{try{fn()}catch(_){}});unsubs=[];clearInterval(timer);timer=null}
window.AcademicModule={mount,unmount,render,prepareLocal,timerState};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='academic')mount()});
})();