/* Koruk Asistan — AI Asistan V2
 * UI: Communication altında. Veri: AppStore snapshot. Kayıt: mevcut NotlarService/TakvimService.
 * AI hiçbir zaman doğrudan Firestore'a yazmaz; taslak kullanıcı onayıyla kaydedilir.
 */
(function(global){
'use strict';
if(global.AssistantModule)return;
const API='https://okul-ai-asistan.sedonet23.workers.dev';
let history=[],loading=false,lastTool=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const today=()=>new Date().toISOString().slice(0,10);
const toolPermission=name=>(name==='taslak_not'||name==='taslak_metin')?'notlar':'takvim';
const canSaveTool=name=>global.duzenleyebilir?.(toolPermission(name))!==false;
function context(){
 const classes=arr('siniflar'),students=arr('veliler'),teachers=arr('ogretmenler');
 const classLabel=s=>s?.ad||[s?.seviye,s?.sube].filter(Boolean).join('-')||'?';
 const className=id=>classLabel(classes.find(x=>x.id===id));
 const teacherName=id=>{const o=teachers.find(x=>x.id===id);return o?`${o.ad||''} ${o.soyad||''}`.trim():'?'};
 const data={bugun:today(),ogretmenler:teachers.map(o=>({ad:`${o.ad||''} ${o.soyad||''}`.trim(),brans:o.brans||'',unvan:o.unvan||''})),siniflar:classes.map(s=>({sinif:classLabel(s),ogrenciSayisi:students.filter(v=>v.sinifId===s.id).length,sinifOgretmeni:teacherName(s.sinifOgretmeniId)})),ogrenciler:students.map(v=>({ad:v.ogrenciAdi||'',sinif:className(v.sinifId)})),gorevler:arr('gorevler').map(g=>({baslik:g.baslik||'',tarih:g.tarih||'',tamamlandi:!!(g.tamamlandi||g.durum==='tamamlandi')})),hatirlaticilar:arr('hatirlaticilar').map(h=>({baslik:h.baslik||'',tarih:h.tarih||'',tamamlandi:!!h.tamamlandi})),notlar:arr('notlar').map(n=>({baslik:n.baslik||'',tip:n.tip||''})),sinavlar:arr('sinavlar').map(s=>({sinif:s.sinif||'',ders:s.ders||'',ogretmen:teacherName(s.ogretmenId),tarih:s.tarih||'',tur:s.tur||''})),servisler:arr('servisler').map(s=>({servisAdi:s.servisAdi||'',plaka:s.plaka||'',guzergah:s.guzergah||'',ogrenciSayisi:s.ogrenciSayisi||0})),nobetAtamalari:arr('nobetAtamalari').map(n=>({tarih:n.tarih||'',yerId:n.yerId||'',ogretmen:n.ogretmenAdSoyad||n.ogretmenAdi||''})),personel:arr('personel').map(p=>({ad:p.adSoyad||`${p.ad||''} ${p.soyad||''}`.trim(),gorev:p.gorev||p.unvan||''}))};
 let json=JSON.stringify(data);if(json.length>120000)json=json.slice(0,120000)+'…';return json;
}
function toolLabel(n){return{taslak_not:'Not',taslak_gorev:'Görev',taslak_hatirlatici:'Hatırlatıcı',taslak_metin:'Belge / Metin'}[n]||n}
function shell(){return `<section class="ka-stack" data-ai-assistant-v2><div class="ka-row ka-row--between"><div><h2>AI Asistan</h2><p class="ka-muted">Taslak üretir; hiçbir kaydı onayınız olmadan değiştirmez.</p></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-assistant-back>Geri</button></div><div id="assistantMessages" class="ka-stack"></div><label class="ka-field"><span class="ka-field__label">İsteğiniz</span><textarea id="assistantInput" rows="4" placeholder="Örn. Yarınki toplantı için hatırlatıcı taslağı hazırla"></textarea></label><div class="ka-row"><button class="ka-btn" type="button" data-assistant-send>Gönder</button><button class="ka-btn ka-btn--secondary" type="button" data-assistant-clear>Geçmişi Temizle</button></div><div id="assistantDraft"></div></section>`}
function renderMessages(){const box=document.getElementById('assistantMessages');if(!box)return;box.innerHTML=history.length?history.map(m=>`<article class="ka-card"><div class="ka-card__body"><strong>${m.role==='user'?'Siz':'Asistan'}</strong><div>${esc(m.text).replace(/\n/g,'<br>')}</div></div></article>`).join(''):'<div class="ka-empty">Henüz mesaj yok.</div>';if(loading)box.insertAdjacentHTML('beforeend','<div class="ka-muted">Asistan yanıt hazırlıyor…</div>')}
function renderDraft(){const host=document.getElementById('assistantDraft');if(!host)return;if(!lastTool){host.innerHTML='';return}const{name,args={}}=lastTool,title=args.baslik||'',text=args.icerik||args.aciklama||'',permission=toolPermission(name),editable=canSaveTool(name);host.innerHTML=`<article class="ka-card"><div class="ka-card__header"><h3>Taslak Onayı — ${esc(toolLabel(name))}</h3></div><div class="ka-card__body ka-stack"><label class="ka-field"><span class="ka-field__label">Başlık</span><input id="assistantDraftTitle" value="${esc(title)}"></label><label class="ka-field"><span class="ka-field__label">İçerik</span><textarea id="assistantDraftText" rows="8">${esc(text)}</textarea></label>${editable?'':`<div class="ka-empty">Bu taslağı kaydetmek için ${permission==='notlar'?'Notlar':'Takvim'} düzenleme yetkisi gerekir.</div>`}<div class="ka-row"><button class="ka-btn" type="button" data-assistant-save data-ka-permission="${permission}" data-ka-min-level="edit" data-ka-write="${permission}">Taslağı Kaydet</button><button class="ka-btn ka-btn--secondary" type="button" data-assistant-dismiss>Vazgeç</button></div></div></article>`;host.querySelector('[data-assistant-save]').onclick=saveDraft;host.querySelector('[data-assistant-dismiss]').onclick=()=>{lastTool=null;renderDraft()};global.PermissionService?.apply?.(host)}
async function saveDraft(){if(!lastTool)return;const{name,args={}}=lastTool;if(!canSaveTool(name)){global.toast?.('Bu taslağı kaydetme yetkiniz yok.');return;}const title=document.getElementById('assistantDraftTitle')?.value||'',text=document.getElementById('assistantDraftText')?.value||'';try{if(name==='taslak_not'||name==='taslak_metin'){if(!global.NotlarService)throw new Error('Notlar servisi hazır değil.');await global.NotlarService.notKaydet(null,{baslik:title,tip:'metin',icerik:text,renk:name==='taslak_metin'?'mavi':'sari'});}else if(name==='taslak_gorev'){if(!global.TakvimService)throw new Error('Takvim servisi hazır değil.');await global.TakvimService.gorevKaydet(null,{baslik:title,aciklama:text,tarih:args.tarih||today(),tamamlandi:false,durum:'yapilacak'});}else if(name==='taslak_hatirlatici'){if(!global.TakvimService)throw new Error('Takvim servisi hazır değil.');await global.TakvimService.hatirlaticiKaydet(null,{baslik:title,aciklama:text,tarih:args.tarih||today(),tamamlandi:false});}else throw new Error('Desteklenmeyen taslak.');global.toast?.('Taslak kaydedildi.');lastTool=null;renderDraft();}catch(e){global.toast?.('Taslak kaydedilemedi: '+(e?.message||e))}}
async function send(){const input=document.getElementById('assistantInput'),text=(input?.value||'').trim();if(!text||loading)return;history.push({role:'user',text});input.value='';loading=true;renderMessages();try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history,context:context()})}),data=await res.json();if(!res.ok||data.error)throw new Error(data.error||`AI isteği başarısız (${res.status})`);if(data.toolCall){lastTool=data.toolCall;history.push({role:'model',text:`Taslak hazırlandı: ${toolLabel(data.toolCall.name)}`});}else history.push({role:'model',text:data.text||'(boş yanıt)'});}catch(e){history.push({role:'model',text:'Hata: '+(e?.message||e)});}finally{loading=false;renderMessages();renderDraft()}}
function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return;root.innerHTML=shell();renderMessages();renderDraft();root.querySelector('[data-assistant-back]').onclick=()=>global.CommunicationModule?.mount?.(root);root.querySelector('[data-assistant-send]').onclick=send;root.querySelector('[data-assistant-clear]').onclick=()=>{history=[];lastTool=null;renderMessages();renderDraft()};root.querySelector('#assistantInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};global.PermissionService?.applyModule?.('communication')}
function inject(){const root=document.querySelector('[data-communication-module]');if(!root||root.querySelector('[data-ai-assistant-open]'))return;const tabs=root.querySelector('.ka-tabs');if(!tabs)return;const b=document.createElement('button');b.type='button';b.className='ka-tab';b.dataset.aiAssistantOpen='true';b.textContent='AI Asistan';b.onclick=()=>mount(document.getElementById('v2ModuleRoot'));tabs.appendChild(b)}
global.AssistantModule={mount,context,send,saveDraft};
global.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='communication')requestAnimationFrame(inject)});
})(window);