/* Koruk Asistan — Kurul ve Komisyonlar */
(function(g){
'use strict';
const T='kurulKomisyonlar';let root=null,mounted=false,detail='',q='',year='',unsub=null;
const A=t=>Array.isArray(g.AppStore?.data?.(t))?g.AppStore.data(t):[];
const D=()=>g.DeviceData||(()=>{throw Error('Cihaz veri katmanı hazır değil.')})();
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const edit=()=>g.AKTIF_KULLANICI?.admin===true||g.PermissionService?.can?.('management.committees.edit','edit')===true||g.PermissionService?.can?.('management.committees','edit')===true;
const tn=x=>String(x?.adSoyad||[x?.ad,x?.soyad].filter(Boolean).join(' ')||'Öğretmen').trim(),sn=x=>String(x?.ogrenciAdi||x?.adSoyad||x?.ad||'Öğrenci').trim();
const teachers=()=>A('ogretmenler').filter(x=>x?.id).sort((a,b)=>tn(a).localeCompare(tn(b),'tr'));
const students=()=>A('veliler').filter(x=>x?.id).sort((a,b)=>sn(a).localeCompare(sn(b),'tr'));
const cn=id=>A('siniflar').find(x=>String(x.id)===String(id))?.ad||'';
const cy=()=>{const d=new Date(),y=d.getFullYear();return d.getMonth()+1>=9?y+'-'+(y+1):(y-1)+'-'+y};
const ms=a=>Array.isArray(a)?a.map((x,i)=>({tur:x?.tur==='ogrenci'?'ogrenci':'ogretmen',id:String(x?.id||''),sira:i+1})).filter(x=>x.id):[];
const ml=x=>x.tur==='ogrenci'?sn(students().find(s=>String(s.id)===x.id))+' · '+cn(students().find(s=>String(s.id)===x.id)?.sinifId):tn(teachers().find(t=>String(t.id)===x.id));
const rows=()=>A(T).slice().sort((a,b)=>String(a.ad||'').localeCompare(String(b.ad||''),'tr'));
const filtered=()=>rows().filter(x=>(!year||x.egitimOgretimYili===year)&&(!q||String(x.ad||'').toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))));
const save=async(id,v)=>{if(!edit())throw Error('Bu işlem için yetkiniz yok.');const x={...v,guncellenmeTarihi:new Date().toISOString()};return id?D().update(T,COL.kurulKomisyonlar,id,x):D().add(T,COL.kurulKomisyonlar,{...x,olusturmaTarihi:new Date().toISOString()})};
const section=(h,b,a='')=>'<section class="ka-card ka-committee-section"><div class="ka-card__header ka-row ka-row--between"><h3>'+h+'</h3>'+a+'</div><div class="ka-card__body">'+b+'</div></section>';
function memberRows(a,type,canRemove=false){const r=ms(a).filter(x=>x.tur===type);return r.length?r.map((x,i)=>'<div class="ka-committee-member-row"><span class="ka-badge">'+(i+1)+'</span><div class="ka-grow"><strong>'+esc(ml(x))+'</strong><small>'+(type==='ogrenci'?'Öğrenci':'Öğretmen')+'</small></div>'+(canRemove?'<button type="button" class="ka-icon-button" data-rm-member="'+type+':'+x.id+'">×</button>':'')+'</div>').join(''):'<div class="ka-empty">Üye yok.</div>'}
function list(){const rs=filtered();return '<section class="ka-stack ka-committees-page"><div class="ka-row ka-row--between"><div><h2>Kurul ve Komisyonlar</h2><p class="ka-muted">Okul kurul ve komisyonlarını yönetin.</p></div>'+(edit()?'<button class="ka-btn" data-add>+ Yeni Kurul / Komisyon</button>':'')+'</div><div class="ka-grid"><input class="ka-input" data-q value="'+esc(q)+'" placeholder="Kurul veya komisyon ara..."><select class="ka-input" data-year><option value="">Tüm yıllar</option>'+[...new Set([cy(),...rows().map(x=>x.egitimOgretimYili).filter(Boolean)])].sort((a,b)=>String(b).localeCompare(String(a))).map(y=>'<option '+(year===y?'selected':'')+'>'+esc(y)+'</option>').join('')+'</select></div><div class="ka-committee-list">'+(rs.length?rs.map(r=>'<button class="ka-committee-list-row" data-open="'+esc(r.id)+'"><span class="ka-committee-list-icon">🏛️</span><span class="ka-grow"><strong>'+esc(r.ad)+'</strong><small>'+esc(r.tur||'Kurul')+' · '+esc(r.egitimOgretimYili||'')+' · Başkan: '+esc(tn(teachers().find(t=>String(t.id)===String(r.baskanId))))+'</small></span><span class="ka-badge">'+ms(r.asilUyeler).length+' asil · '+ms(r.yedekUyeler).length+' yedek</span><span>›</span></button>').join(''):'<div class="ka-empty">Kayıt bulunamadı.</div>')+'</div></section>'}
function detailView(r){const a=ms(r.asilUyeler),y=ms(r.yedekUyeler),gorev=r.gorevler||[],notes=r.notlar||[],works=r.isler||[],b=teachers().find(t=>String(t.id)===String(r.baskanId));return '<section class="ka-stack ka-committee-detail"><div class="ka-row"><button class="ka-icon-button" data-back>‹</button><div class="ka-grow"><small class="ka-muted">'+esc(r.egitimOgretimYili||'')+'</small><h2>'+esc(r.ad)+'</h2><p class="ka-muted">'+esc(r.tur||'Kurul')+'</p></div>'+(edit()?'<button class="ka-btn ka-btn--secondary" data-edit="'+r.id+'">Düzenle</button>':'')+'<button class="ka-btn ka-btn--secondary" data-print="'+r.id+'">🖨️ Rapor</button>'+(edit()?'<button class="ka-icon-button" data-del="'+r.id+'">🗑️</button>':'')+'</div>'+
section('Başkan',b?'<strong>'+esc(tn(b))+'</strong><div class="ka-muted">'+esc(b.brans||b.unvan||'Öğretmen')+'</div>':'<div class="ka-empty">Başkan atanmadı.</div>')+
section('Asil Üyeler','<div class="ka-committee-member-groups"><div><strong>Öğretmenler</strong>'+memberRows(a,'ogretmen')+'</div><div><strong>Öğrenciler</strong>'+memberRows(a,'ogrenci')+'</div></div>')+
section('Yedek Üyeler','<div class="ka-committee-member-groups"><div><strong>Öğretmenler</strong>'+memberRows(y,'ogretmen')+'</div><div><strong>Öğrenciler</strong>'+memberRows(y,'ogrenci')+'</div></div>')+
section('Görev ve Sorumluluklar',gorev.length?'<ol class="ka-committee-task-list">'+gorev.map((x,i)=>'<li><span class="ka-grow">'+esc(x.metin||x)+'</span>'+(edit()?'<button class="ka-icon-button" data-dtask="'+i+'">×</button>':'')+'</li>').join('')+'</ol>':'<div class="ka-empty">Görev eklenmemiş.</div>',edit()?'<button class="ka-btn ka-btn--secondary ka-btn--sm" data-add-task>+ Görev</button>':'')+
section('📝 Notlar',notes.length?notes.slice().reverse().map((x,i)=>'<article class="ka-committee-note"><strong>'+esc(x.baslik||'Not')+'</strong><small>'+esc(x.tarih||'')+'</small><p>'+esc(x.icerik||'')+'</p>'+(edit()?'<button class="ka-btn ka-btn--ghost ka-btn--sm" data-dnote="'+i+'">Sil</button>':'')+'</article>').join(''):'<div class="ka-empty">Not eklenmemiş.</div>',edit()?'<button class="ka-btn ka-btn--secondary ka-btn--sm" data-add-note>+ Not</button>':'')+
section('✅ İşler',works.length?works.map((x,i)=>'<div class="ka-committee-work '+(x.tamamlandi?'is-done':'')+'"><label><input type="checkbox" data-work="'+i+'" '+(x.tamamlandi?'checked':'')+'><span><strong>'+esc(x.baslik||'İş')+'</strong><small>'+esc([x.sorumluAdi,x.sonTarih].filter(Boolean).join(' · '))+'</small></span></label>'+(edit()?'<button class="ka-icon-button" data-dwork="'+i+'">×</button>':'')+'</div>').join(''):'<div class="ka-empty">İş eklenmemiş.</div>',edit()?'<button class="ka-btn ka-btn--secondary ka-btn--sm" data-add-work>+ İş</button>':'')+'</section></section>'}
function memberEditor(r,group,type){const list=ms(r[group+'Uyeler']),used=new Set(list.map(x=>x.tur+':'+x.id)),src=type==='ogrenci'?students():teachers();return src.map(x=>{const k=type+':'+x.id;if(used.has(k))return '';return '<option value="'+esc(x.id)+'">'+esc(type==='ogrenci'?sn(x)+' · '+cn(x.sinifId):tn(x))+'</option>'}).join('')}
function form(r){return '<div class="ka-modal-backdrop" data-modal><form class="ka-modal" id="cf"><div class="ka-modal__header"><h2>'+(r.id?'Kurul / Komisyonu Düzenle':'Yeni Kurul / Komisyon')+'</h2><button type="button" class="ka-icon-button" data-close>×</button></div><div class="ka-modal__body ka-stack"><input type="hidden" name="id" value="'+esc(r.id||'')+'"><label class="ka-field"><span class="ka-field__label">Ad *</span><input name="ad" required value="'+esc(r.ad||'')+'"></label><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Tür</span><select name="tur"><option>Kurul</option><option selected>Komisyon</option><option>Ekip</option><option>Diğer</option></select></label><label class="ka-field"><span class="ka-field__label">Eğitim öğretim yılı</span><input name="yil" value="'+esc(r.egitimOgretimYili||cy())+'"></label></div><label class="ka-field"><span class="ka-field__label">Başkan</span><select name="baskan"><option value="">Seçiniz</option>'+teachers().map(t=>'<option value="'+t.id+'" '+(String(t.id)===String(r.baskanId)?'selected':'')+'>'+esc(tn(t))+'</option>').join('')+'</select></label>'+['asil','yedek'].map(group=>'<div class="ka-committee-form-group"><h3>'+(group==='asil'?'Asil':'Yedek')+' Üyeler</h3><div class="ka-grid"><select data-s="'+group+'-ogretmen"><option value="">Öğretmen seç...</option>'+memberEditor(r,group,'ogretmen')+'</select><button type="button" class="ka-btn ka-btn--secondary" data-a="'+group+'-ogretmen">+ Öğretmen</button><select data-s="'+group+'-ogrenci"><option value="">Öğrenci seç...</option>'+memberEditor(r,group,'ogrenci')+'</select><button type="button" class="ka-btn ka-btn--secondary" data-a="'+group+'-ogrenci">+ Öğrenci</button></div><div data-m="'+group+'">'+memberRows(r[group+'Uyeler'],'ogretmen',true)+memberRows(r[group+'Uyeler'],'ogrenci',true)+'</div></div>').join('')+'<div class="ka-committee-form-group"><div class="ka-row ka-row--between"><h3>Görev ve Sorumluluklar</h3><button type="button" class="ka-btn ka-btn--secondary ka-btn--sm" data-ft>+ Ekle</button></div><div data-fg class="ka-stack">'+(r.gorevler||[]).map(x=>'<div class="ka-row"><input class="ka-grow" data-g value="'+esc(x.metin||x)+'"><button type="button" class="ka-icon-button" data-fr>×</button></div>').join('')+'</div></div></div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-close>Vazgeç</button><button class="ka-btn">Kaydet</button></div></form></div>'}
function openForm(r){document.querySelector('[data-modal]')?.remove();document.body.insertAdjacentHTML('beforeend',form(r));const ov=document.querySelector('[data-modal]'),f=ov.querySelector('#cf'),state={asil:ms(r.asilUyeler),yedek:ms(r.yedekUyeler)};const rebuild=g=>ov.querySelector('[data-m="'+g+'"]').innerHTML=memberRows(state[g],'ogretmen',true)+memberRows(state[g],'ogrenci',true);ov.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const k=b.dataset.a,s=ov.querySelector('[data-s="'+k+'"]'),id=s.value,type=k.endsWith('ogrenci')?'ogrenci':'ogretmen',group=k.startsWith('asil')?'asil':'yedek';if(!id)return;if(state.asil.concat(state.yedek).some(x=>x.tur===type&&String(x.id)===id)||(type==='ogretmen'&&String(f.baskan.value)===id))return g.toast?.('Bu kişi zaten kullanılıyor.');state[group].push({tur:type,id});s.value='';rebuild(group)});ov.onclick=e=>{if(e.target===ov||e.target.closest('[data-close]'))ov.remove();const rm=e.target.closest('[data-rm-member]');if(rm){const [type,id]=rm.dataset.rmMember.split(':');const group=state.asil.some(x=>x.tur===type&&String(x.id)===id)?'asil':'yedek';state[group]=state[group].filter(x=>!(x.tur===type&&String(x.id)===id));rebuild(group)}};ov.querySelector('[data-ft]')?.addEventListener('click',()=>{const w=ov.querySelector('[data-fg]'),d=document.createElement('div');d.className='ka-row';d.innerHTML='<input class="ka-grow" data-g placeholder="Görev / sorumluluk"><button type="button" class="ka-icon-button" data-fr>×</button>';w.appendChild(d)});ov.onclick=e=>{if(e.target.closest('[data-fr]'))e.target.closest('.ka-row')?.remove();if(e.target===ov||e.target.closest('[data-close]'))ov.remove();};f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),bid=String(fd.get('baskan')||''),used=new Set(),clean=g=>state[g].filter(x=>{const k=x.tur+':'+x.id;if(used.has(k)||(x.tur==='ogretmen'&&String(x.id)===bid))return false;used.add(k);return true}).map((x,i)=>({...x,sira:i+1})),v={ad:String(fd.get('ad')||'').trim(),tur:String(fd.get('tur')||'Komisyon'),egitimOgretimYili:String(fd.get('yil')||cy()).trim(),baskanId:bid,asilUyeler:clean('asil'),yedekUyeler:clean('yedek'),gorevler:[...ov.querySelectorAll('[data-g]')].map((x,i)=>({id:String(i+1),metin:x.value.trim(),sira:i+1})).filter(x=>x.metin),notlar:r.notlar||[],isler:r.isler||[]};if(!v.ad)return;try{await save(String(fd.get('id')||'')||null,v);ov.remove();detail=v.id||detail;render();g.toast?.('Kaydedildi.')}catch(e){g.toast?.(e.message||'Kaydedilemedi.')}}}
function addEntry(kind){const r=rows().find(x=>String(x.id)===String(detail));if(!r||!edit())return;const ov=document.createElement('div');ov.className='ka-modal-backdrop';ov.innerHTML='<form class="ka-modal"><div class="ka-modal__header"><h2>'+(kind==='note'?'Not Ekle':'İş Ekle')+'</h2></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Başlık</span><input name="b" required></label><label class="ka-field"><span class="ka-field__label">'+(kind==='note'?'Not':'Açıklama')+'</span><textarea name="c" rows="5"></textarea></label>'+(kind==='work'?'<label class="ka-field"><span class="ka-field__label">Son tarih</span><input name="d" type="date"></label>':'')+'</div><div class="ka-modal__footer"><button type="button" class="ka-btn ka-btn--secondary" data-x>Vazgeç</button><button class="ka-btn">Kaydet</button></div></form>';document.body.appendChild(ov);ov.querySelector('[data-x]').onclick=()=>ov.remove();ov.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),n=new Date().toISOString(),v={...r};if(kind==='note')v.notlar=[...(r.notlar||[]),{id:D().newId(),baslik:fd.get('b'),icerik:fd.get('c'),tarih:n.slice(0,10)}];else v.isler=[...(r.isler||[]),{id:D().newId(),baslik:fd.get('b'),icerik:fd.get('c'),sonTarih:fd.get('d'),tamamlandi:false};try{await save(r.id,v);ov.remove();render()}catch(e){g.toast?.(e.message||'Kaydedilemedi.')}}}
async function mutate(fn){const r=rows().find(x=>String(x.id)===String(detail));if(!r||!edit())return;const v=JSON.parse(JSON.stringify(r));fn(v);try{await save(r.id,v);render()}catch(e){g.toast?.(e.message||'Güncellenemedi.')}}
async function print(r){if(!g.ReportEngine?.printReport)await g.AppLoader?.loadScript?.('js/modules/report-engine.js');const t=new Map(teachers().map(x=>[String(x.id),x])),s=new Map(students().map(x=>[String(x.id),x])),p=x=>x.tur==='ogrenci'?sn(s.get(String(x.id)))+' · '+cn(s.get(String(x.id))?.sinifId):tn(t.get(String(x.id))),tab=a=>ms(a).map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(p(x))+'</td><td>'+esc(x.tur==='ogrenci'?'Öğrenci':'Öğretmen')+'</td></tr>').join('');const body='<h2 class="bolum-baslik">KURUL / KOMİSYON</h2><table><tbody><tr><td>Adı</td><td>'+esc(r.ad)+'</td></tr><tr><td>Tür</td><td>'+esc(r.tur)+'</td></tr><tr><td>Eğitim Öğretim Yılı</td><td>'+esc(r.egitimOgretimYili)+'</td></tr><tr><td>Başkan</td><td>'+esc(tn(t.get(String(r.baskanId))))+'</td></tr></tbody></table><h2 class="bolum-baslik">ASIL ÜYELER</h2><table><tbody>'+tab(r.asilUyeler)+'</tbody></table><h2 class="bolum-baslik">YEDEK ÜYELER</h2><table><tbody>'+tab(r.yedekUyeler)+'</tbody></table><h2 class="bolum-baslik">GÖREV VE SORUMLULUKLAR</h2>'+(r.gorevler?.length?'<ol>'+r.gorevler.map(x=>'<li>'+esc(x.metin||x)+'</li>').join('')+'</ol>':'<p>Yok.</p>')+'<h2 class="bolum-baslik">NOTLAR</h2>'+(r.notlar?.length?r.notlar.map(x=>'<p><b>'+esc(x.baslik)+'</b> — '+esc(x.icerik)+'</p>').join(''):'<p>Yok.</p>')+'<h2 class="bolum-baslik">İŞLER</h2>'+(r.isler?.length?r.isler.map(x=>'<p>['+(x.tamamlandi?'✓':' ')+'] '+esc(x.baslik)+'</p>').join(''):'<p>Yok.</p>');return g.ReportEngine.printReport(r.ad+' — Rapor',body,{fileName:r.ad+'_Rapor',ustBaslik:'KORUK İLK - ORTAOKULU'})}
function render(){if(!mounted||!root)return;const r=detail?rows().find(x=>String(x.id)===String(detail)):null;root.innerHTML=r?detailView(r):list();bind();g.PermissionService?.apply?.(root)}
function bind(){root.querySelector('[data-add]')?.addEventListener('click',()=>openForm(emptyRecord()));root.querySelector('[data-q]')?.addEventListener('input',e=>{q=e.target.value;render()});root.querySelector('[data-year]')?.addEventListener('change',e=>{year=e.target.value;render()});root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{detail=b.dataset.open;render()});root.querySelector('[data-back]')?.addEventListener('click',()=>{detail='';render()});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=rows().find(x=>String(x.id)===String(b.dataset.edit));if(r)openForm(r)});root.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const r=rows().find(x=>String(x.id)===String(b.dataset.del));if(r&&confirm('“'+r.ad+'” silinsin mi?')){await D().remove(T,COL.kurulKomisyonlar,r.id);detail='';render()}});root.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>{const r=rows().find(x=>String(x.id)===String(b.dataset.print));if(r)print(r).catch(e=>g.toast?.(e.message||'Rapor oluşturulamadı.'))});root.querySelector('[data-add-task]')?.addEventListener('click',()=>addEntry('work'));root.querySelector('[data-add-note]')?.addEventListener('click',()=>addEntry('note'));root.querySelectorAll('[data-dtask]').forEach(b=>b.onclick=()=>mutate(r=>r.gorevler.splice(+b.dataset.dtask,1)));root.querySelectorAll('[data-dnote]').forEach(b=>b.onclick=()=>mutate(r=>r.notlar.splice(+b.dataset.dnote,1)));root.querySelectorAll('[data-dwork]').forEach(b=>b.onclick=()=>mutate(r=>r.isler.splice(+b.dataset.dwork,1)));root.querySelectorAll('[data-work]').forEach(b=>b.onchange=()=>mutate(r=>r.isler[+b.dataset.work].tamamlandi=b.checked))}
function mount(target=document.getElementById('v2ModuleRoot')){if(!target)return false;mounted=true;root=target;unsub?.();unsub=g.AppStore?.subscribe?.('data.'+T,()=>mounted&&requestAnimationFrame(render));render();return true}
function unmount(){mounted=false;unsub?.();unsub=null;root=null;detail='';document.querySelector('[data-modal]')?.remove()}
function back(){if(document.querySelector('[data-modal]')){document.querySelector('[data-modal]').remove();return true}if(detail){detail='';render();return true}return false}
g.CommitteesModule={mount,unmount,openPage:()=>true,back,render,print};g.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='committees')mount()});
})(window);