/* Koruk Asistan — Communication tek modül
 * Mesajlaşma + takvim + notlar + duyurular + anket + haberler + push + UI.
 * Veri cihaz-first; Firestore yalnız DeviceData/SyncEngine arka planındadır.
 */

/* ========================= MESSAGING DATA ========================= */
(function(global){
'use strict';
function device(){if(!global.DeviceData)throw new Error('DeviceData hazır değil');return global.DeviceData;}
function uid(){return global.AKTIF_KULLANICI?.uid||global.AppStore?.get?.('session.user')?.uid||'';}
function arr(type){const v=global.AppStore?.data?.(type);return Array.isArray(v)?v:[];}
function safeUrl(url){if(typeof url!=='string')return'';const d=url.trim();if(!d||!/^https?:\/\//i.test(d)||/[\s"'<>]/.test(d))return'';try{const p=new URL(d);return(p.protocol==='https:'||p.protocol==='http:')?p.href:'';}catch(_){return'';}}
function safeConversation(v){if(!v||typeof v!=='object'||!v.katilimciFotolari)return v;const f={};Object.entries(v.katilimciFotolari).forEach(([u,url])=>f[u]=safeUrl(url));return{...v,katilimciFotolari:f};}
async function prepare(type,collection,query){if(!global.SyncEngine||!collection)return;SyncEngine.register(type,collection,query?{query}:{});await SyncEngine.localHydrate([type]);SyncEngine.schedule(80);}
const uidCache=new Map(),uidPending=new Map(),conversationPending=new Map();
const MesajlasmaRepository={
  konusmalariDinle(kullaniciUid,callback){const u=kullaniciUid||uid();prepare('konusmalar',COL.konusmalar,q=>q.where('katilimciUidler','array-contains',u)).catch(()=>{});return device().listen('konusmalar',rows=>callback(rows.filter(k=>(k.katilimciUidler||[]).includes(u)).map(safeConversation)));},
  konusmaOlustur(v){return device().add('konusmalar',COL.konusmalar,{...safeConversation(v),guncellenmeTarihi:new Date().toISOString()});},
  konusmaGuncelle(id,v){return device().update('konusmalar',COL.konusmalar,id,safeConversation(v));},
  konusmaSil(id){return device().remove('konusmalar',COL.konusmalar,id);},
  mesajlariDinle(konusmaId,callback){const type=`mesajlar:${konusmaId}`;prepare(type,COL.mesajlar,q=>q.where('konusmaId','==',konusmaId)).catch(()=>{});return device().listen(type,rows=>callback([...rows].sort((a,b)=>String(a.tarih||'').localeCompare(String(b.tarih||'')))));},
  mesajEkle(v){return device().add(`mesajlar:${v.konusmaId}`,COL.mesajlar,{...v,tarih:new Date().toISOString()});},
  mesajSil(id,konusmaId){return device().remove(konusmaId?`mesajlar:${konusmaId}`:'mesajlar',COL.mesajlar,id);},
  async mesajlariTopluSil(konusmaId){const type=`mesajlar:${konusmaId}`;await prepare(type,COL.mesajlar,q=>q.where('konusmaId','==',konusmaId)).catch(()=>{});const rows=arr(type),kullaniciBazliBayt={};for(const m of rows){if(m.dosya?.boyut&&m.gonderenUid)kullaniciBazliBayt[m.gonderenUid]=(kullaniciBazliBayt[m.gonderenUid]||0)+m.dosya.boyut;if(m.dosya?.storagePath)await this.dosyaSil(m.dosya.storagePath).catch(()=>{});await device().remove(type,COL.mesajlar,m.id);}return{kullaniciBazliBayt};},
  dosyaYukle(konusmaId,dosya,cb){return new Promise((resolve,reject)=>{const yol=`mesajDosyalari/${konusmaId}/${Date.now()}_${dosya.name}`,ref=storage.ref().child(yol),g=ref.put(dosya);g.on('state_changed',s=>cb?.(Math.round(s.bytesTransferred/s.totalBytes*100)),reject,async()=>resolve({url:await g.snapshot.ref.getDownloadURL(),storagePath:yol}));});},
  dosyaSil(path){return storage.ref().child(path).delete();},
  async kullaniciUidBulOgretmenId(ogretmenId){const type=`kullaniciDizin:${ogretmenId}`;if(!COL.kullanicilar)return{empty:true,docs:[]};SyncEngine.register(type,COL.kullanicilar,{query:q=>q.where('bagliOgretmenId','==',ogretmenId)});await SyncEngine.localHydrate([type]);let rows=arr(type);if(!rows.length&&navigator.onLine){await SyncEngine.pull([type]).catch(()=>{});rows=arr(type);}return{empty:!rows.length,docs:rows.slice(0,1).map(r=>({id:r.id,data:()=>r}))};}
};
global.MesajlasmaRepository=MesajlasmaRepository;
const MesajlasmaService={
  _yetkiKontrol(){if(!duzenleyebilir('mesajlasma')){toast?.('Bu işlem için yetkiniz yok.');return false;}return true;},
  _kendiKimlik(){const k=typeof _hesapKimligi==='function'?_hesapKimligi():{ad:'',fotoUrl:''};return{uid:global.AKTIF_KULLANICI?.uid||null,ad:k.ad||'Kullanıcı',foto:k.fotoUrl||''};},
  _ogretmenUidBul(id){if(uidCache.has(id))return Promise.resolve(uidCache.get(id));if(uidPending.has(id))return uidPending.get(id);const p=MesajlasmaRepository.kullaniciUidBulOgretmenId(id).then(s=>{const x=s.empty?null:s.docs[0].id;uidCache.set(id,x);uidPending.delete(id);return x;}).catch(e=>{uidPending.delete(id);throw e;});uidPending.set(id,p);return p;},
  konusmaBaslatOgretmenIle(id,ad,mevcut,foto){if(conversationPending.has(id))return conversationPending.get(id);const p=(async()=>{if(!this._yetkiKontrol())throw new Error('yetkisiz');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');const diger=await this._ogretmenUidBul(id);if(!diger)throw new Error('hesap-yok');if(diger===ben.uid)throw new Error('kendine-mesaj');const varOlan=[...(mevcut||[]),...arr('konusmalar')].find(k=>!k.grupMu&&k.katilimciUidler?.length===2&&k.katilimciUidler.includes(ben.uid)&&k.katilimciUidler.includes(diger));if(varOlan)return varOlan.id;const ref=await MesajlasmaRepository.konusmaOlustur({katilimciUidler:[ben.uid,diger],katilimciAdlari:{[ben.uid]:ben.ad,[diger]:ad},katilimciFotolari:{[ben.uid]:ben.foto||'',[diger]:foto||''},grupMu:false,sonMesaj:null,okunmayanlar:{[ben.uid]:0,[diger]:0}});return ref.id;})();conversationPending.set(id,p);return p.finally(()=>conversationPending.delete(id));},
  async grupOlustur(grupAdi,katilimcilar){if(!this._yetkiKontrol())throw new Error('yetkisiz');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');if(!grupAdi?.trim())throw new Error('grup-adi-gerekli');if(!katilimcilar?.length)throw new Error('katilimci-gerekli');const ids=[ben.uid,...katilimcilar.map(k=>k.uid)],adlar={[ben.uid]:ben.ad},fotolar={[ben.uid]:ben.foto||''},ok={[ben.uid]:0};katilimcilar.forEach(k=>{adlar[k.uid]=k.ad;fotolar[k.uid]=k.foto||'';ok[k.uid]=0;});const ref=await MesajlasmaRepository.konusmaOlustur({katilimciUidler:ids,katilimciAdlari:adlar,katilimciFotolari:fotolar,grupMu:true,grupAdi:grupAdi.trim(),sonMesaj:null,okunmayanlar:ok});return ref.id;},
  async mesajGonder(konusmaId,metin,mevcut){if(!this._yetkiKontrol())throw new Error('yetkisiz');const temiz=(metin||'').trim();if(!temiz)throw new Error('mesaj-bos');const ben=this._kendiKimlik();if(!ben.uid)throw new Error('kimlik-yok');await MesajlasmaRepository.mesajEkle({konusmaId,gonderenUid:ben.uid,gonderenAdi:ben.ad,metin:temiz});const ok={...(mevcut?.okunmayanlar||{})};(mevcut?.katilimciUidler||[]).forEach(u=>ok[u]=u===ben.uid?0:(ok[u]||0)+1);return MesajlasmaRepository.konusmaGuncelle(konusmaId,{sonMesaj:{metin:temiz,gonderenUid:ben.uid,tarih:new Date().toISOString()},guncellenmeTarihi:new Date().toISOString(),okunmayanlar:ok});},
  okunduIsaretle(konusmaId,mevcut){const ben=this._kendiKimlik();if(!ben.uid||!mevcut?.okunmayanlar?.[ben.uid])return Promise.resolve();return MesajlasmaRepository.konusmaGuncelle(konusmaId,{okunmayanlar:{...mevcut.okunmayanlar,[ben.uid]:0}});},
  _IZIN_VERILEN_TURLER:{'application/pdf':{etiket:'PDF',ikon:'📕'},'application/msword':{etiket:'Word',ikon:'📘'},'application/vnd.openxmlformats-officedocument.wordprocessingml.document':{etiket:'Word',ikon:'📘'},'application/vnd.ms-excel':{etiket:'Excel',ikon:'📗'},'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':{etiket:'Excel',ikon:'📗'},'image/jpeg':{etiket:'Resim',ikon:'🖼️',gorselMi:true},'image/png':{etiket:'Resim',ikon:'🖼️',gorselMi:true},'image/gif':{etiket:'Resim',ikon:'🖼️',gorselMi:true},'image/webp':{etiket:'Resim',ikon:'🖼️',gorselMi:true}},
  _MAKS_DOSYA_BOYUTU:10*1024*1024,
  dosyaTuruBilgisi(t){return this._IZIN_VERILEN_TURLER[t]||null;},
  async mesajGonderDosyaIle(konusmaId,dosya,mevcut,cb){if(!this._yetkiKontrol())throw new Error('yetkisiz');const tur=this.dosyaTuruBilgisi(dosya.type);if(!tur)throw new Error('desteklenmeyen-tur');if(dosya.size>this._MAKS_DOSYA_BOYUTU)throw new Error('dosya-cok-buyuk');const ben=this._kendiKimlik();if(global.DepolamaSinirService){const izin=await DepolamaSinirService.yuklemeIzniVarMi('mesaj',dosya.size);if(!izin.izinVar)throw new Error('depolama-siniri:'+izin.mesaj);}const{url,storagePath}=await MesajlasmaRepository.dosyaYukle(konusmaId,dosya,cb);await MesajlasmaRepository.mesajEkle({konusmaId,gonderenUid:ben.uid,gonderenAdi:ben.ad,metin:'',dosya:{ad:dosya.name,url,storagePath,tur:dosya.type,boyut:dosya.size,etiket:tur.etiket,gorselMi:!!tur.gorselMi}});const ok={...(mevcut?.okunmayanlar||{})};(mevcut?.katilimciUidler||[]).forEach(u=>ok[u]=u===ben.uid?0:(ok[u]||0)+1);return MesajlasmaRepository.konusmaGuncelle(konusmaId,{sonMesaj:{metin:`${tur.ikon} ${dosya.name}`,gonderenUid:ben.uid,tarih:new Date().toISOString()},guncellenmeTarihi:new Date().toISOString(),okunmayanlar:ok});},
  toplamOkunmayan(k){const ben=this._kendiKimlik();return ben.uid?(k||[]).reduce((t,x)=>t+((x.okunmayanlar&&x.okunmayanlar[ben.uid])||0),0):0;},
  mesajSilinebilirMi(m){return global.AKTIF_KULLANICI?.admin||this._kendiKimlik().uid===m?.gonderenUid;},
  async mesajSil(m){if(!this._yetkiKontrol())throw new Error('yetkisiz');if(!this.mesajSilinebilirMi(m))throw new Error('sahip-degil');if(m.dosya?.storagePath)await MesajlasmaRepository.dosyaSil(m.dosya.storagePath).catch(()=>{});return MesajlasmaRepository.mesajSil(m.id,m.konusmaId);},
  async konusmaSil(id,k){if(!this._yetkiKontrol())throw new Error('yetkisiz');const ben=this._kendiKimlik();if(!global.AKTIF_KULLANICI?.admin&&!(k?.katilimciUidler||[]).includes(ben.uid))throw new Error('sahip-degil');await MesajlasmaRepository.mesajlariTopluSil(id);return MesajlasmaRepository.konusmaSil(id);}
};
global.MesajlasmaService=MesajlasmaService;
})(window);

/* ========================= COMMUNICATION DATA ========================= */
(function(global){
'use strict';
function device(){if(!global.DeviceData)throw new Error('DeviceData hazır değil');return global.DeviceData;}
function user(){return global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};}
function uid(){return user().uid||'';}function isAdmin(){return user().admin===true;}function arr(type){const v=global.AppStore?.data?.(type);return Array.isArray(v)?v:[];}function safeToast(m){global.toast?.(m);}
function requireEdit(key){if(duzenleyebilir(key))return true;safeToast('Bu işlem için yetkiniz yok.');throw new Error('yetkisiz');}
const TakvimRepository={hatirlaticilariDinle:cb=>device().listen('hatirlaticilar',r=>cb(isAdmin()?r:r.filter(x=>x.sahipUid===uid()))),hatirlaticiEkle:v=>device().add('hatirlaticilar',COL.hatirlaticilar,{...v,eklenmeTarihi:new Date().toISOString()}),hatirlaticiGuncelle:(id,v)=>device().update('hatirlaticilar',COL.hatirlaticilar,id,v),hatirlaticiSil:id=>device().remove('hatirlaticilar',COL.hatirlaticilar,id),gorevleriDinle:cb=>device().listen('gorevler',r=>cb(isAdmin()?r:r.filter(x=>x.sahipUid===uid()))),gorevEkle:v=>device().add('gorevler',COL.gorevler,{...v,eklenmeTarihi:new Date().toISOString()}),gorevGuncelle:(id,v)=>device().update('gorevler',COL.gorevler,id,v),gorevSil:id=>device().remove('gorevler',COL.gorevler,id)};global.TakvimRepository=TakvimRepository;
global.TakvimService={_yetkiKontrol(){if(!duzenleyebilir('takvim')){safeToast('Bu işlem için yetkiniz yok.');return false;}return true;},gorunurListele:l=>isAdmin()?(l||[]):(l||[]).filter(x=>x.sahipUid===uid()),hatirlaticiKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));if(!id)v={...v,sahipUid:uid()};return id?TakvimRepository.hatirlaticiGuncelle(id,v):TakvimRepository.hatirlaticiEkle(v);},hatirlaticiSil(id){try{requireEdit('takvim')}catch(e){return Promise.reject(e)}return TakvimRepository.hatirlaticiSil(id)},hatirlaticiTamamlandiGuncelle(id,d){try{requireEdit('takvim')}catch(e){return Promise.reject(e)}return TakvimRepository.hatirlaticiGuncelle(id,{tamamlandi:d})},gorevKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));if(!id)v={...v,sahipUid:uid()};return id?TakvimRepository.gorevGuncelle(id,v):TakvimRepository.gorevEkle(v);},gorevSil(id){try{requireEdit('takvim')}catch(e){return Promise.reject(e)}return TakvimRepository.gorevSil(id)},gorevDurumGuncelle(id,d){try{requireEdit('takvim')}catch(e){return Promise.reject(e)}return TakvimRepository.gorevGuncelle(id,{durum:d})},gorevTamamlandiGuncelle(id,d){try{requireEdit('takvim')}catch(e){return Promise.reject(e)}return TakvimRepository.gorevGuncelle(id,{tamamlandi:d,durum:d?'tamamlandi':'yapilacak'})}};
function cleanHtml(html){if(typeof html!=='string'||!html)return'';if(typeof document==='undefined')return html.replace(/<[^>]*>/g,'');const tpl=document.createElement('template');tpl.innerHTML=html;tpl.content.querySelectorAll('script,style,iframe,object,embed,link,meta,base,form,input,button,textarea,select,option,svg,math,video,audio').forEach(e=>e.remove());tpl.content.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(a=>{const n=a.name.toLowerCase(),v=String(a.value||'').trim();if(n.startsWith('on')||n==='srcdoc'||((n==='href'||n==='src'||n==='xlink:href')&&/^(?:javascript|vbscript|data):/i.test(v)))el.removeAttribute(a.name);}));return tpl.innerHTML;}
const NotlarRepository={notlariDinle:cb=>device().listen('notlar',r=>cb((isAdmin()?r:r.filter(x=>x.sahipUid===uid())).map(x=>({...x,icerik:cleanHtml(x.icerik||'')})))),notEkle:v=>device().add('notlar',COL.notlar,{...v,eklenmeTarihi:new Date().toISOString(),guncellenmeTarihi:new Date().toISOString()}),notGuncelle:(id,v)=>device().update('notlar',COL.notlar,id,{...v,guncellenmeTarihi:new Date().toISOString()}),notSil:id=>device().remove('notlar',COL.notlar,id),notMaddeleriGuncelle:(id,m)=>device().update('notlar',COL.notlar,id,{maddeler:m,guncellenmeTarihi:new Date().toISOString()})};global.NotlarRepository=NotlarRepository;global.NotlarService={_yetkiKontrol(){return duzenleyebilir('notlar');},notKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));v={...v,icerik:cleanHtml(v?.icerik||'')};if(!id)v.sahipUid=uid();return id?NotlarRepository.notGuncelle(id,v):NotlarRepository.notEkle(v);},notSil(id){try{requireEdit('notlar')}catch(e){return Promise.reject(e)}return NotlarRepository.notSil(id)},notMaddeleriGuncelle(id,m){try{requireEdit('notlar')}catch(e){return Promise.reject(e)}return NotlarRepository.notMaddeleriGuncelle(id,m)}};
const DuyurularRepository={duyurulariDinle:cb=>device().listen('duyurular',cb),duyuruEkle:v=>device().add('duyurular',COL.duyurular,v),duyuruGuncelle:(id,v)=>device().update('duyurular',COL.duyurular,id,v),duyuruSil:id=>device().remove('duyurular',COL.duyurular,id),okunduIsaretle(id,u,v){const d=arr('duyurular').find(x=>x.id===id),okuyanlar={...(d?.okuyanlar||{}),[u]:v};return device().update('duyurular',COL.duyurular,id,{okuyanlar});}};global.DuyurularRepository=DuyurularRepository;global.DuyurularService={_yetkiKontrol:()=>duzenleyebilir('duyurular'),duyuruKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?DuyurularRepository.duyuruGuncelle(id,v):DuyurularRepository.duyuruEkle({...v,tarih:new Date().toISOString(),olusturanUid:uid(),okuyanlar:{}});},duyuruSil(id){try{requireEdit('duyurular')}catch(e){return Promise.reject(e)}return DuyurularRepository.duyuruSil(id)},okunduIsaretle(id){return DuyurularRepository.okunduIsaretle(id,uid(),{tarih:new Date().toISOString()});},benOkudumMu:d=>!!d?.okuyanlar?.[uid()]};
const AnketRepository={anketleriDinle:cb=>device().listen('anketler',cb),anketEkle:v=>device().add('anketler',COL.anketler,v),anketGuncelle:(id,v)=>device().update('anketler',COL.anketler,id,v),anketSil:id=>device().remove('anketler',COL.anketler,id)};global.AnketRepository=AnketRepository;global.AnketService={async anketOlustur(s,sec,c){if(!isAdmin())throw new Error('yetkisiz');const g=(sec||[]).map(x=>x.trim()).filter(Boolean);if(!s?.trim()||g.length<2)throw new Error('gecersiz');return AnketRepository.anketEkle({soru:s.trim(),secenekler:g.map((m,i)=>({id:'sk'+i+'_'+Date.now(),metin:m})),coklu:!!c,aktif:true,olusturanUid:uid(),olusturmaTarihi:new Date().toISOString(),oylar:{}});},oyVer(a,ids){const oylar={...(a.oylar||{}),[uid()]:{secenekIdler:ids,tarih:new Date().toISOString()}};return AnketRepository.anketGuncelle(a.id,{oylar});},anketKapat(id,k){if(!isAdmin())return Promise.reject(new Error('yetkisiz'));return AnketRepository.anketGuncelle(id,{aktif:!k})},anketSil(id){if(!isAdmin())return Promise.reject(new Error('yetkisiz'));return AnketRepository.anketSil(id)},kendiOyunuGetir:a=>a.oylar?.[uid()]||null};
const HaberlerRepository={haberleriDinle:cb=>device().listen('haberler',cb),haberEkle:v=>device().add('haberler',COL.haberler,{...v,eklenmeTarihi:new Date().toISOString()}),haberGuncelle:(id,v)=>device().update('haberler',COL.haberler,id,v),haberSil:id=>device().remove('haberler',COL.haberler,id),kaynaklariDinle:cb=>device().listen('haberKaynaklari',cb),kaynakEkle:v=>device().add('haberKaynaklari',COL.haberKaynaklari,v),kaynakGuncelle:(id,v)=>device().update('haberKaynaklari',COL.haberKaynaklari,id,v),kaynakSil:id=>device().remove('haberKaynaklari',COL.haberKaynaklari,id)};global.HaberlerRepository=HaberlerRepository;global.HaberlerService={_yetkiKontrol(){return duzenleyebilir('haberler')},haberKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?HaberlerRepository.haberGuncelle(id,v):HaberlerRepository.haberEkle(v)},haberSil(id){try{requireEdit('haberler')}catch(e){return Promise.reject(e)}return HaberlerRepository.haberSil(id)},kaynakKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?HaberlerRepository.kaynakGuncelle(id,v):HaberlerRepository.kaynakEkle(v)},kaynakSil(id){try{requireEdit('haberler')}catch(e){return Promise.reject(e)}return HaberlerRepository.kaynakSil(id)}};
})(window);

/* ========================= UI ========================= */
(function(){
'use strict';if(window.CommunicationModule)return;
let active='announcements',query='',mounted=false,unsubs=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=AppStore?.data?.(t);return Array.isArray(v)?v:[]};const match=v=>{const q=norm(query.trim());return!q||norm(v.filter(Boolean).join(' ')).includes(q)};const uid=()=>window.AKTIF_KULLANICI?.uid||AppStore?.get?.('session.user')?.uid||'';
function date(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('tr-TR')}
async function prepareLocal(){if(!SyncEngine||!COL)return;const defs={anketler:COL.anketler,haberKaynaklari:COL.haberKaynaklari,cihazlar:COL.cihazlar},types=[];Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});const u=uid();if(u&&COL.konusmalar){SyncEngine.register('konusmalar',COL.konusmalar,{query:q=>q.where('katilimciUidler','array-contains',u)});types.push('konusmalar')}if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(120)}}
function shell(){return `<section class="ka-stack" data-communication-module><div class="ka-row ka-row--between"><div><h2>İletişim</h2><p class="ka-muted">Okul içi içerikler cihazdan açılır.</p></div><span id="communicationCount" class="ka-badge"></span></div><div class="ka-tabs"><button class="ka-tab" data-communication-tab="announcements">Duyurular</button><button class="ka-tab" data-communication-tab="messages">Mesajlar</button><button class="ka-tab" data-communication-tab="polls">Anketler</button><button class="ka-tab" data-communication-tab="news">Haberler</button><button class="ka-tab" data-communication-tab="notes">Notlar</button><button class="ka-tab" data-communication-tab="calendar">Takvim</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="communicationSearch" type="search" placeholder="Başlık, kişi veya içerik ara…"></label><div id="communicationContent" class="ka-stack"></div></section>`}
function listResult(list,renderer,empty){return{count:list.length,html:list.length?list.map(renderer).join(''):`<div class="ka-empty">${esc(empty)}</div>`}}
function announcements(){const l=arr('duyurular').filter(x=>!x.arsivlendi&&match([x.baslik,x.icerik,x.aciklama,x.olusturanAdi])).sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||'')));return listResult(l,x=>`<article class="ka-card ka-list-card"><div class="ka-card__body"><strong>${esc(x.baslik||'Duyuru')}</strong><div class="ka-muted">${esc(String(x.icerik||x.aciklama||'').replace(/<[^>]*>/g,'').slice(0,180))}</div></div></article>`,'Duyuru bulunamadı.')}
function messages(){const me=uid(),l=arr('konusmalar').filter(k=>match([k.grupAdi,k.sonMesaj?.metin,...Object.values(k.katilimciAdlari||{})]));return listResult(l,k=>{const n=k.grupMu?k.grupAdi:Object.entries(k.katilimciAdlari||{}).filter(([id])=>id!==me).map(([,x])=>x).join(', '),u=Number(k.okunmayanlar?.[me]||0);return`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(n||'Sohbet')}</strong><div class="ka-muted">${esc(k.sonMesaj?.metin||'Henüz mesaj yok')}</div></div>${u?`<span class="ka-badge">${u}</span>`:''}</div></article>`},'Sohbet bulunamadı.')}
function polls(){return listResult(arr('anketler').filter(x=>match([x.soru])),x=>`<article class="ka-card ka-list-card"><div class="ka-card__body"><strong>${esc(x.soru||'Anket')}</strong><div class="ka-muted">${(x.secenekler||[]).length} seçenek · ${x.aktif===false?'Kapalı':'Aktif'}</div></div></article>`,'Anket bulunamadı.')}
function news(){return listResult(arr('haberler').filter(x=>match([x.baslik,x.ozet,x.kaynak])),x=>`<article class="ka-card ka-list-card"><div class="ka-card__body"><strong>${esc(x.baslik||'Haber')}</strong><div class="ka-muted">${esc([x.kaynak,date(x.tarih)].filter(Boolean).join(' · '))}</div></div></article>`,'Haber bulunamadı.')}
function notes(){return listResult(arr('notlar').filter(x=>match([x.baslik,x.icerik,x.not])),x=>`<article class="ka-card ka-list-card"><div class="ka-card__body"><strong>${esc(x.baslik||'Not')}</strong><div class="ka-muted">${esc(String(x.icerik||x.not||'').replace(/<[^>]*>/g,'').slice(0,160))}</div></div></article>`,'Not bulunamadı.')}
/* ================================================================
   TAKVİM — Hatırlatıcılar + Görevler
================================================================ */
const HAT_ONCELIK=['Düşük','Orta','Yüksek'];
const GOREV_DURUM=['yapilacak','devam ediyor','tamamlandi'];
const GOREV_DURUM_LABEL={yapilacak:'Yapılacak','devam ediyor':'Devam Ediyor',tamamlandi:'Tamamlandı'};
function calDate(v){if(!v)return'—';try{const d=new Date(String(v).slice(0,10)+'T00:00:00');return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR')}catch(_){return String(v)}}
function calDiff(v){if(!v)return null;const a=new Date(new Date().toISOString().slice(0,10)+'T00:00:00'),b=new Date(String(v).slice(0,10)+'T00:00:00');const d=Math.round((b-a)/86400000);if(d<0)return{text:`${Math.abs(d)} gün geçti`,cls:'ka-badge--danger'};if(d===0)return{text:'Bugün',cls:'ka-badge--warning'};if(d<=3)return{text:`${d} gün kaldı`,cls:'ka-badge--warning'};return{text:`${d} gün`,cls:''}}
function calModal(type,item={}){const isHat=type==='hat';const id=item.id||'';return`<div class="ka-modal-backdrop" data-cal-modal style="z-index:1300"><form class="ka-modal" id="calForm"><div class="ka-modal__header"><h2>${id?(isHat?'Hatırlatıcı Düzenle':'Görev Düzenle'):(isHat?'Yeni Hatırlatıcı':'Yeni Görev')}</h2></div><div class="ka-modal__body ka-stack"><input type="hidden" name="id" value="${esc(id)}"><input type="hidden" name="type" value="${esc(type)}"><label class="ka-field"><span class="ka-field__label">Başlık *</span><input name="baslik" value="${esc(item.baslik||item.ad||'')}" required></label>${isHat?`<div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Tarih</span><input name="tarih" type="date" value="${esc(item.tarih||'')}"></label><label class="ka-field"><span class="ka-field__label">Öncelik</span><select name="oncelik">${HAT_ONCELIK.map(o=>`<option ${o===item.oncelik?'selected':''}>${esc(o)}</option>`).join('')}</select></label></div>`:''}<label class="ka-field"><span class="ka-field__label">Açıklama</span><textarea name="aciklama">${esc(item.aciklama||item.not||'')}</textarea></label>${!isHat?`<div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Son Tarih</span><input name="sonTarih" type="date" value="${esc(item.sonTarih||'')}"></label><label class="ka-field"><span class="ka-field__label">Durum</span><select name="durum">${GOREV_DURUM.map(d=>`<option value="${esc(d)}" ${d===(item.durum||'yapilacak')?'selected':''}>${esc(GOREV_DURUM_LABEL[d]||d)}</option>`).join('')}</select></label></div>`:''}</div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-cal-modal-kapat>Vazgeç</button><button class="ka-btn" type="submit">Kaydet</button></div></form></div>`}
function calendar(){
  const hats=arr('hatirlaticilar').filter(x=>!x.tamamlandi||(calDiff(x.tarih)?.text)).sort((a,b)=>String(a.tarih||'').localeCompare(String(b.tarih||'')));
  const gorevs=arr('gorevler').filter(x=>x.durum!=='tamamlandi').sort((a,b)=>String(a.sonTarih||'').localeCompare(String(b.sonTarih||'')));
  const hatRows=hats.map(h=>{const diff=calDiff(h.tarih);return`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><div class="ka-row"><strong>${esc(h.baslik||'Hatırlatıcı')}</strong>${h.oncelik?`<span class="ka-badge">${esc(h.oncelik)}</span>`:''}</div>${h.tarih?`<div class="ka-muted">${calDate(h.tarih)}${diff?` · <span class="ka-badge ${diff.cls}">${diff.text}</span>`:''}</div>`:''}</div><div class="ka-row" style="gap:6px"><button class="ka-btn ka-btn--sm ka-btn--secondary" data-cal-check="${esc(h.id)}" data-cal-type="hat" title="Tamamlandı">${h.tamamlandi?'✓':'○'}</button><button class="ka-btn ka-btn--sm ka-btn--secondary" data-cal-edit="${esc(h.id)}" data-cal-type="hat">Düzenle</button><button class="ka-btn ka-btn--sm ka-btn--danger" data-cal-del="${esc(h.id)}" data-cal-type="hat">Sil</button></div></div></article>`});
  const gorevRows=gorevs.map(g=>{const diff=calDiff(g.sonTarih);return`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(g.baslik||'Görev')}</strong><div class="ka-muted">${esc(GOREV_DURUM_LABEL[g.durum]||g.durum||'Yapılacak')}${g.sonTarih?` · ${calDate(g.sonTarih)}`:''} ${diff?`<span class="ka-badge ${diff.cls}">${diff.text}</span>`:''}</div>${g.aciklama?`<small class="ka-muted">${esc(String(g.aciklama).slice(0,80))}</small>`:''}</div><div class="ka-row" style="gap:6px"><button class="ka-btn ka-btn--sm ka-btn--secondary" data-cal-edit="${esc(g.id)}" data-cal-type="gorev">Düzenle</button><button class="ka-btn ka-btn--sm ka-btn--danger" data-cal-del="${esc(g.id)}" data-cal-type="gorev">Sil</button></div></div></article>`});
  return{count:hats.length+gorevs.length,html:`<div class="ka-row" style="margin-bottom:10px;flex-wrap:wrap;gap:8px"><h3 style="font-size:16px">Takvim & Görevler</h3><div class="ka-row" style="gap:6px;margin-left:auto"><button class="ka-btn ka-btn--secondary ka-btn--sm" data-cal-add="hat">+ Hatırlatıcı</button><button class="ka-btn ka-btn--sm" data-cal-add="gorev">+ Görev</button></div></div><div style="margin-bottom:16px"><h3 class="ka-muted" style="font-size:12px;font-weight:800;letter-spacing:.06em;margin-bottom:8px">HATIRLATICILAR (${hats.length})</h3>${hatRows.length?hatRows.join(''):'<div class="ka-empty">Hatırlatıcı yok.</div>'}</div><div><h3 class="ka-muted" style="font-size:12px;font-weight:800;letter-spacing:.06em;margin-bottom:8px">GÖREVLER (${gorevs.length})</h3>${gorevRows.length?gorevRows.join(''):'<div class="ka-empty">Aktif görev yok.</div>'}</div>`}
}
function bindCalendar(out){if(!out)return;out.querySelectorAll('[data-cal-add]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('[data-cal-modal]')?.remove();document.body.insertAdjacentHTML('beforeend',calModal(b.dataset.calAdd));_calBindModal()}));out.querySelectorAll('[data-cal-edit]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.calType,id=b.dataset.calEdit,item=arr(type==='hat'?'hatirlaticilar':'gorevler').find(x=>x.id===id)||{};document.querySelector('[data-cal-modal]')?.remove();document.body.insertAdjacentHTML('beforeend',calModal(type,item));_calBindModal()}));out.querySelectorAll('[data-cal-del]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Silinsin mi?'))return;const type=b.dataset.calType,id=b.dataset.calDel;try{if(type==='hat')await global.TakvimService?.hatirlaticiSil?.(id);else await global.TakvimService?.gorevSil?.(id);render()}catch(e){safeToast(e?.message||'Silinemedi')}}));out.querySelectorAll('[data-cal-check]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.calCheck,item=arr('hatirlaticilar').find(x=>x.id===id);if(!item)return;try{await global.TakvimService?.hatirlaticiTamamlandiGuncelle?.(id,!item.tamamlandi);render()}catch(e){safeToast(e?.message||'Güncellenemedi')}}));}
function _calBindModal(){const modal=document.querySelector('[data-cal-modal]');if(!modal)return;modal.querySelector('[data-cal-modal-kapat]')?.addEventListener('click',()=>modal.remove());modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});modal.querySelector('#calForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=fd.get('id')||'',type=fd.get('type');const v={baslik:String(fd.get('baslik')||'').trim()};if(!v.baslik){safeToast('Başlık zorunlu');return}if(type==='hat'){v.tarih=fd.get('tarih')||'';v.oncelik=fd.get('oncelik')||'Orta';v.aciklama=String(fd.get('aciklama')||'').trim();v.tamamlandi=false;try{await global.TakvimService?.hatirlaticiKaydet?.(id||null,v);safeToast('Hatırlatıcı kaydedildi.');modal.remove();render()}catch(err){safeToast(err?.message||'Kaydedilemedi')}}else{v.sonTarih=fd.get('sonTarih')||'';v.durum=fd.get('durum')||'yapilacak';v.aciklama=String(fd.get('aciklama')||'').trim();try{await global.TakvimService?.gorevKaydet?.(id||null,v);safeToast('Görev kaydedildi.');modal.remove();render()}catch(err){safeToast(err?.message||'Kaydedilemedi')}}})}

function render(){if(!mounted)return;document.querySelectorAll('[data-communication-tab]').forEach(b=>b.classList.toggle('active',b.dataset.communicationTab===active));if(active==='calendar'){const out=document.getElementById('communicationContent'),c=document.getElementById('communicationCount');const r=calendar();if(out){out.innerHTML=r.html;bindCalendar(out)}if(c)c.textContent=`${r.count} kayıt`;PermissionService?.applyModule?.('communication');return}const r=active==='messages'?messages():active==='polls'?polls():active==='news'?news():active==='notes'?notes():announcements();document.getElementById('communicationContent').innerHTML=r.html;document.getElementById('communicationCount').textContent=`${r.count} kayıt`;PermissionService?.applyModule?.('communication')}
function bind(){document.querySelectorAll('[data-communication-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.communicationTab;render()});const s=document.getElementById('communicationSearch');if(s)s.oninput=()=>{query=s.value;render()}}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.duyurular','data.konusmalar','data.anketler','data.haberler','data.notlar','data.hatirlaticilar','data.gorevler'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.CommunicationModule={mount,unmount,render,prepareLocal};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='communication')mount()});
})();
