/* Koruk Asistan v2 — Communication UI
   Duyuru + haber + not + anket + konuşma listesi.
   UI yalnız AppStore/IndexedDB okur; Firestore yalnız SyncEngine arka planındadır. */
(function(){
'use strict';if(window.CommunicationModule)return;
let active='announcements',query='',mounted=false,unsubs=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const match=vals=>{const q=norm(query.trim());return!q||norm(vals.filter(Boolean).join(' ')).includes(q)};
function date(v){if(!v)return'';try{if(typeof v.toDate==='function')return v.toDate().toLocaleDateString('tr-TR');const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('tr-TR')}catch(_){return''}}
function uid(){return window.AKTIF_KULLANICI?.uid||window.AppStore?.get?.('session.user')?.uid||''}
async function prepareLocal(){
  if(!window.SyncEngine||!window.COL)return;
  const defs={anketler:COL.anketler,haberKaynaklari:COL.haberKaynaklari,cihazlar:COL.cihazlar};const types=[];
  Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});
  const u=uid();
  if(u&&COL.konusmalar){SyncEngine.register('konusmalar',COL.konusmalar,{query:q=>q.where('katilimciUidler','array-contains',u)});types.push('konusmalar')}
  if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(120)}
}
function shell(){return `<section class="ka-stack" data-communication-module><div class="ka-row ka-row--between"><div><h2>İletişim</h2><p class="ka-muted">Okul içi içerikler cihazdan açılır; güncellemeler arka planda gelir.</p></div><span id="communicationCount" class="ka-badge"></span></div><div class="ka-tabs"><button class="ka-tab" data-communication-tab="announcements">Duyurular</button><button class="ka-tab" data-communication-tab="messages">Mesajlar</button><button class="ka-tab" data-communication-tab="polls">Anketler</button><button class="ka-tab" data-communication-tab="news">Haberler</button><button class="ka-tab" data-communication-tab="notes">Notlar</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="communicationSearch" type="search" placeholder="Başlık, kişi veya içerik ara…"></label><div id="communicationContent" class="ka-stack"></div></section>`}
function announcements(){const list=arr('duyurular').filter(x=>!x.arsivlendi&&match([x.baslik,x.icerik,x.aciklama,x.olusturanAdi])).sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||'')));return listResult(list,x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>${esc(x.baslik||'Duyuru')}</strong><span class="ka-badge">${esc(date(x.tarih))}</span></div><div class="ka-muted">${esc(String(x.icerik||x.aciklama||'').replace(/<[^>]*>/g,'').slice(0,180))}</div></div></article>`,'Duyuru bulunamadı.')}
function messages(){const me=uid(),list=arr('konusmalar').filter(k=>match([k.grupAdi,k.sonMesaj?.metin,...Object.values(k.katilimciAdlari||{})])).sort((a,b)=>String(b.guncellenmeTarihi||'').localeCompare(String(a.guncellenmeTarihi||'')));return listResult(list,k=>{const names=k.grupMu?k.grupAdi:Object.entries(k.katilimciAdlari||{}).filter(([id])=>id!==me).map(([,n])=>n).join(', ');const unread=(k.okunmayanlar&&me)?Number(k.okunmayanlar[me]||0):0;return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(names||'Sohbet')}</strong><div class="ka-muted">${esc(k.sonMesaj?.metin||'Henüz mesaj yok')}</div></div>${unread?`<span class="ka-badge">${unread}</span>`:''}</div></article>`},'Sohbet bulunamadı.')}
function polls(){const list=arr('anketler').filter(x=>match([x.soru,...(x.secenekler||[]).map(s=>s.metin)])).sort((a,b)=>String(b.olusturmaTarihi?.seconds||b.olusturmaTarihi||'').localeCompare(String(a.olusturmaTarihi?.seconds||a.olusturmaTarihi||'')));return listResult(list,x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(x.soru||'Anket')}</strong><div class="ka-muted">${(x.secenekler||[]).length} seçenek · ${x.aktif===false?'Kapalı':'Aktif'}</div></div></div></article>`,'Anket bulunamadı.')}
function news(){const list=arr('haberler').filter(x=>match([x.baslik,x.ozet,x.kaynak])).sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||'')));return listResult(list,x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><strong>${esc(x.baslik||'Haber')}</strong><div class="ka-muted">${esc([x.kaynak,date(x.tarih)].filter(Boolean).join(' · '))}</div></div></article>`,'Haber bulunamadı.')}
function notes(){const me=uid();const list=arr('notlar').filter(x=>(!x.sahipUid||x.sahipUid===me||window.AKTIF_KULLANICI?.admin)&&match([x.baslik,x.icerik,x.not])).sort((a,b)=>String(b.guncellenmeTarihi||b.eklenmeTarihi||'').localeCompare(String(a.guncellenmeTarihi||a.eklenmeTarihi||'')));return listResult(list,x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><strong>${esc(x.baslik||'Not')}</strong><div class="ka-muted">${esc(String(x.icerik||x.not||'').replace(/<[^>]*>/g,'').slice(0,160))}</div></div></article>`,'Not bulunamadı.')}
function listResult(list,renderer,empty){return{count:list.length,html:list.length?list.map(renderer).join(''):`<div class="ka-empty">${esc(empty)}</div>`}}
function render(){if(!mounted)return;document.querySelectorAll('[data-communication-tab]').forEach(b=>b.classList.toggle('active',b.dataset.communicationTab===active));const r=active==='messages'?messages():active==='polls'?polls():active==='news'?news():active==='notes'?notes():announcements();const out=document.getElementById('communicationContent'),c=document.getElementById('communicationCount');if(out)out.innerHTML=r.html;if(c)c.textContent=`${r.count} kayıt`}
function bind(){document.querySelectorAll('[data-communication-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.communicationTab;render()});const s=document.getElementById('communicationSearch');if(s)s.oninput=()=>{query=s.value;render()}}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.duyurular','data.konusmalar','data.anketler','data.haberler','data.notlar'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}
function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.CommunicationModule={mount,unmount,render,prepareLocal};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='communication')mount()});
})();
