/* Koruk Asistan V2 — Ana Sayfa
 * Eski admin/öğretmen ana sayfa hiyerarşisi local-first mimaride yeniden kurulur.
 * Kalıcı veri kaynağı AppStore/DeviceData; Firestore yalnız SyncEngine arka planıdır.
 */
(function(){
'use strict';if(window.DashboardModule)return;
let mounted=false,unsubs=[],reminderShown=false,trialTimer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
function isoToday(){const d=new Date(),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function date(v){if(!v)return'—';try{if(typeof v.toDate==='function')return v.toDate().toLocaleDateString('tr-TR');const d=new Date(String(v).length===10?v+'T00:00:00':v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR')}catch(_){return String(v)}}
function user(){return window.AppStore?.get?.('session.user')||window.AKTIF_KULLANICI||{}}
function isAdmin(){return user().admin===true}
function firstName(){const u=user(),ad=u.ad||u.adSoyad||u.displayName||u.kullaniciAdi||'';return String(ad).trim().split(/\s+/)[0]||'Kullanıcı'}
function teacherId(){const u=user();return u.bagliOgretmenId||u.ogretmenId||''}
function greeting(){const h=new Date().getHours();return h<6?'İyi geceler':h<12?'Günaydın':h<18?'İyi günler':'İyi akşamlar'}
function upcoming(list,field,days=14){const now=new Date(isoToday()+'T00:00:00'),max=new Date(now.getTime()+days*86400000);return list.filter(x=>{if(!x?.[field])return false;const d=new Date(String(x[field]).slice(0,10)+'T00:00:00');return !Number.isNaN(d.getTime())&&d>=now&&d<=max}).sort((a,b)=>String(a[field]).localeCompare(String(b[field])))}
function cards(){return(window.AppConfig?.dashboardCards?.()||[{key:'welcome',visible:true,order:10},{key:'stats',visible:true,order:20},{key:'upcoming',visible:true,order:30},{key:'announcements',visible:true,order:40},{key:'duty',visible:true,order:50}]).filter(x=>x.visible!==false).sort((a,b)=>Number(a.order||0)-Number(b.order||0))}
function cardVisible(key){return cards().map(x=>x.key).includes(key)}
const DAY_NAMES=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];
function dayName(d=new Date()){return DAY_NAMES[d.getDay()]}
function dayLong(d=new Date()){return d.toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'})}
function normalizeDay(v){return String(v||'').toLocaleLowerCase('tr').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c')}
function sameDay(a,b){return normalizeDay(a)===normalizeDay(b)}
function sortHour(a,b){return String(a?.saat??a?.dersSaati??'').localeCompare(String(b?.saat??b?.dersSaati??''),'tr',{numeric:true})}
function lessonLabel(x){return x.ders||x.dersAdi||x.brans||'Ders'}
function classLabel(x){return x.sinif||x.sinifAdi||x.sube||'Sınıf'}
function teacherLabel(x){if(x.ogretmenAdSoyad||x.ogretmenAdi)return x.ogretmenAdSoyad||x.ogretmenAdi;const t=arr('ogretmenler').find(o=>o.id===x.ogretmenId);return t?.adSoyad||[t?.ad,t?.soyad].filter(Boolean).join(' ')||'Öğretmen'}
function todayLessons({mine=false}={}){const tid=teacherId(),name=dayName();return arr('dersProgrami').filter(x=>sameDay(x.gun,name)&&(!mine||!tid||x.ogretmenId===tid)).sort(sortHour)}
function isDone(x){return x?.tamamlandi===true||['Tamamlandı','Tamamlandi','tamamlandi'].includes(x?.durum)}
function section(title,icon,id,body,extra=''){return `<section class="ka-home-section ${extra}" data-home-section="${id}"><div class="ka-home-section__head"><div><span class="ka-home-section__icon">${icon}</span><h3>${esc(title)}</h3></div></div><div class="ka-home-section__body">${body}</div></section>`}
function empty(text){return `<div class="ka-home-empty">${esc(text)}</div>`}
function routeButton(label,module,page='',title='',icon='→'){return `<button class="ka-home-link" type="button" data-dash-route="${module}"${page?` data-dash-page="${esc(page)}"`:''}${title?` data-dash-title="${esc(title)}"`:''}><span>${esc(label)}</span><b>${icon}</b></button>`}
function hero(){const mine=todayLessons({mine:true}),live=window.SchoolLiveStatus?.status?.(),teacherMode=!isAdmin();let focus=mine[0]||null,focusLabel='Bugünkü ilk dersiniz';if(teacherMode&&mine.length){const current=live?.mode==='lesson'?mine.find(x=>Number(x.saat??x.dersSaati)===Number(live?.period)):null,next=mine.find(x=>Number(x.saat??x.dersSaati)===Number(live?.nextPeriod));if(current){focus=current;focusLabel='Şu anki dersiniz'}else if(next){focus=next;focusLabel='Sıradaki dersiniz'}else if(['after','weekend'].includes(live?.mode))focus=null}const reminders=teacherId()?collectReminders().filter(x=>x.gunFarki<=3).length:0,quiet=isAdmin()?'Yönetim özeti cihaz verilerinden hazırlandı.':live?.mode==='weekend'?'Bugün ders günü değil.':live?.mode==='after'?'Bugünkü dersler tamamlandı.':'Bugün için kişisel ders kaydı görünmüyor.';return `<section class="ka-home-hero" data-dashboard-card="welcome"><div class="ka-home-hero__top"><div><span>${esc(greeting())},</span><h1>${esc(firstName())} 👋</h1><small>${esc(dayLong())}</small></div><span class="ka-home-hero__badge">${isAdmin()?'Yönetici':'Öğretmen'}${reminders?` · 🔔 ${reminders}`:''}</span></div>${focus?`<div class="ka-home-lesson-focus"><div><small>${esc(focusLabel)}</small><strong>${esc(lessonLabel(focus))}</strong><span>${esc(classLabel(focus))}${focus.saat?` · ${esc(focus.saat)}. ders`:''}</span></div>${routeButton('Programım','academic','schedule','Ders Programı','›')}</div>`:`<div class="ka-home-hero__quiet">${esc(quiet)}</div>`}</section>`}
function announcementDateTime(v){if(!v)return'';try{const d=new Date(v);if(Number.isNaN(d.getTime()))return date(v);return d.toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}catch(_){return date(v)}}
function announcementSection(){if(!cardVisible('announcements'))return'';const d=arr('duyurular').filter(x=>x&&!x.arsivlendi&&x.aktif!==false&&!x.pasif).sort((a,b)=>String(b.tarih||b.eklenmeTarihi||'').localeCompare(String(a.tarih||a.eklenmeTarihi||'')))[0];if(!d)return'';const ok=!!window.DuyurularService?.benOkudumMu?.(d),readers=Object.keys(d.okuyanlar||{}).length,raw=String(d.icerik||d.aciklama||'').replace(/<[^>]*>/g,'').trim(),short=raw.length>180?raw.slice(0,180).trim()+'…':raw;return `<div class="kh-dynamic" data-home-section="announcements"><article class="kh-announcement ${ok?'is-read':'is-unread'}" data-duyuru-id="${esc(d.id||'')}"><div class="kh-announcement-accent"></div><div class="kh-announcement-head"><div class="kh-announcement-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m3 11 18-5v12L3 14v-3Z"/><path d="M11.6 16.5 13 21H7l-1.2-6"/></svg></div><div class="kh-announcement-title-wrap"><div class="kh-announcement-kicker">DUYURU</div><h3>${esc(d.baslik||d.ad||'Duyuru')}</h3><div class="kh-announcement-meta">${esc(d.olusturanAdi||'Yönetim')}${d.tarih?' · '+esc(announcementDateTime(d.tarih)):''}</div></div><span class="kh-announcement-status ${ok?'read':'new'}">${ok?'✓ OKUNDU':'YENİ'}</span></div>${short?`<button type="button" class="kh-announcement-body" data-dash-route="communication" data-dash-page="announcements" data-dash-title="Duyurular">${esc(short)}</button>`:''}<div class="kh-announcement-footer"><label class="kh-read-check ${ok?'checked':''}"><input type="checkbox" data-dash-announcement-read="${esc(d.id||'')}" ${ok?'checked disabled':''}><span class="kh-read-box" aria-hidden="true">✓</span><span>${ok?'Okundu olarak işaretlendi':'Okudum'}</span></label>${isAdmin()?`<button type="button" class="kh-read-count" data-dash-route="communication" data-dash-page="announcements" data-dash-title="Duyurular"><span>👁</span><b>${readers}</b> kişi okudu <span class="arrow">›</span></button>`:''}</div></article></div>`}
function pollSection(){const list=arr('anketler').filter(x=>x.aktif!==false&&x.arsivlendi!==true).slice(0,2);if(!list.length)return'';return section('Aktif Anketler','📊','polls',list.map(x=>`<article class="ka-home-row"><span class="ka-home-rowicon">📊</span><div class="ka-grow"><strong>${esc(x.baslik||x.soru||'Anket')}</strong><small>${esc(x.aciklama||'Katılım bekleniyor')}</small></div></article>`).join(''))}
function newsSection(){
  const items=arr('haberler').filter(x=>x&&x.aktif!==false).slice(0,10);if(!items.length)return'';
  const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V5H6.5A2.5 2.5 0 0 0 4 7.5v12Z"/><path d="M8 9h8M8 13h6"/></svg>';
  const text=items.map(x=>{const url=x?.url||x?.link,action=url?`data-dash-external="${esc(url)}"`:'data-dash-route="communication" data-dash-page="news" data-dash-title="Haberler"';return `<button type="button" class="kh-news-item" ${action}>${esc(x.baslik||x.ad||'Haber')}</button><span class="kh-news-dot">•</span>`}).join('');
  return `<div class="kh-news" data-home-section="news" style="--kh-ticker-time:${Math.max(22,items.length*8)}s"><button type="button" class="kh-news-label" aria-label="Haberler" data-dash-route="communication" data-dash-page="news" data-dash-title="Haberler">${icon} HABERLER</button><div class="kh-news-viewport"><div class="kh-news-track">${text}${text}</div></div></div>`
}
function trialTotalMin(d){return d?.oturumTuru==='İki Oturum'?(Number(d.sozelSuresiDk)||0)+(Number(d.araSureDk)||0)+(Number(d.sayisalSuresiDk)||0):Number(d?.sinavSuresiDk)||0}
function trialTimerState(d){const mins=trialTotalMin(d),run=d?.sayacDurumu?.aktif===true,start=d?.sayacDurumu?.baslatmaTarihi?new Date(d.sayacDurumu.baslatmaTarihi).getTime():0;if(!run)return{run:false,remaining:mins*60,label:mins>0?'Hazır':'Süre eksik'};if(!start||mins<=0)return{run:true,remaining:0,label:'Sayaç bilgisi geçersiz'};const elapsed=(Date.now()-start)/1000,total=mins*60,remaining=Math.max(0,total-elapsed);if(d.oturumTuru==='İki Oturum'){const verbal=(Number(d.sozelSuresiDk)||0)*60,br=(Number(d.araSureDk)||0)*60;if(elapsed<verbal)return{run:true,remaining,label:'Sözel oturum'};if(elapsed<verbal+br)return{run:true,remaining,label:'Ara'};return{run:true,remaining,label:remaining>0?'Sayısal oturum':'Tamamlandı'}}return{run:true,remaining,label:remaining>0?'Sınav sürüyor':'Tamamlandı'}}
function trialFmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return`${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor((sec%3600)/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function trialCounterSection(){const list=arr('denemeSinavlari').filter(x=>x?.sayacDurumu?.aktif===true).sort((a,b)=>Number(b?.sayacDurumu?.aktif===true)-Number(a?.sayacDurumu?.aktif===true)||String(a.tarih||'').localeCompare(String(b.tarih||''))).slice(0,3);if(!list.length)return'';const body=list.map(x=>{const st=trialTimerState(x),running=x?.sayacDurumu?.aktif===true;return`<article class="ka-home-row"><span class="ka-home-rowicon">⏱️</span><div class="ka-grow"><strong>${esc(x.ad||'Deneme sınavı')}</strong><small>${esc([x.sinflar||x.siniflar,x.oturumTuru,st.label].filter(Boolean).join(' · '))}</small></div>${running?`<strong data-dash-trial-timer="${esc(x.id)}">${esc(trialFmt(st.remaining))}</strong>`:`<span class="ka-badge">${esc(date(x.tarih))}</span>`}</article>`}).join('');return section('Deneme / Sayaç','⏱️','trial-counter',`${body}<button class="ka-home-link" type="button" data-dash-route="academic" data-dash-page="trial" data-dash-title="Deneme Sınavları"><span>Deneme Sınavlarını aç</span><b>›</b></button>`)}
function refreshTrialTimers(root=document){root.querySelectorAll?.('[data-dash-trial-timer]').forEach(el=>{const d=arr('denemeSinavlari').find(x=>x.id===el.dataset.dashTrialTimer);if(d)el.textContent=trialFmt(trialTimerState(d).remaining)})}
function schoolClassLevel(row){const raw=String(row?.seviye||row?.ad||'').match(/\d+/)?.[0]||'';return Number(raw)||0}
function schoolStageForStudent(student,classMap){const cls=classMap.get(student?.sinifId),level=schoolClassLevel(cls);return level>=1&&level<=4?'primary':level>=5&&level<=8?'secondary':'other'}
function summaryMetric(icon,label,value,meta='',cls=''){return `<article class="ka-school-summary-card ${cls}"><span class="ka-school-summary-icon">${icon}</span><small>${esc(label)}</small><b>${esc(String(value))}</b>${meta?`<div class="ka-school-summary-meta">${meta}</div>`:''}</article>`}
function statsSection(){
  if(!cardVisible('stats'))return'';
  const teachers=arr('ogretmenler'),students=arr('veliler'),classes=arr('siniflar'),services=arr('servisler'),classMap=new Map(classes.map(x=>[x.id,x]));
  const femaleTeachers=teachers.filter(x=>x.cinsiyet==='Kadın').length,maleTeachers=teachers.filter(x=>x.cinsiyet==='Erkek').length,unknownTeachers=Math.max(0,teachers.length-femaleTeachers-maleTeachers);
  const primary=students.filter(x=>schoolStageForStudent(x,classMap)==='primary'),secondary=students.filter(x=>schoolStageForStudent(x,classMap)==='secondary'),otherStudents=students.filter(x=>schoolStageForStudent(x,classMap)==='other').length;
  const genderLine=(list)=>{const girls=list.filter(x=>x.cinsiyet==='Kız').length,boys=list.filter(x=>x.cinsiyet==='Erkek').length,unknown=Math.max(0,list.length-girls-boys);return `<span class="is-girl">♀ ${girls}</span><span class="is-boy">♂ ${boys}</span>${unknown?`<span>• ${unknown}</span>`:''}`};
  const teacherMeta=`<span class="is-girl">♀ ${femaleTeachers} Kadın</span><span class="is-boy">♂ ${maleTeachers} Erkek</span>${unknownTeachers?`<span>• ${unknownTeachers}</span>`:''}`;
  const studentMeta=`<div class="ka-school-stage"><span class="ka-school-stage-icon">🏫</span><small>İLKOKUL</small><strong>${primary.length}</strong><div>${genderLine(primary)}</div></div><div class="ka-school-stage"><span class="ka-school-stage-icon">▣</span><small>ORTAOKUL</small><strong>${secondary.length}</strong><div>${genderLine(secondary)}</div></div>${otherStudents?`<small class="ka-school-unassigned">Sınıf seviyesi belirlenmeyen: ${otherStudents}</small>`:''}`;
  const body=`<div class="ka-school-summary-grid">${summaryMetric('👥','ÖĞRETMEN',teachers.length,teacherMeta,'is-teacher')}${summaryMetric('🎓','ÖĞRENCİ',students.length,studentMeta,'is-student')}${summaryMetric('🏫','SINIF',classes.length,'<span>Aktif sınıf / şube</span>','is-class')}${summaryMetric('🚌','SERVİS',services.length,'<span>Aktif servis</span>','is-service')}</div>`;
  return section('Okul Özeti','▥','stats',body,'ka-school-summary-section')
}
function dutyRows(list){const places=arr('nobetYerleri'),tid=teacherId(),teacherMode=!isAdmin()&&!!tid;return list.map(x=>{const p=places.find(y=>y.id===x.yerId),mine=teacherMode&&x.ogretmenId===tid;return `<article class="ka-home-row"><span class="ka-home-avatar">${esc((teacherLabel(x).split(/\s+/).slice(0,2).map(s=>s[0]).join('')||'N').toLocaleUpperCase('tr'))}</span><div class="ka-grow"><strong>${esc(teacherLabel(x))}</strong><small>${esc(x.yerAdi||p?.ad||'Nöbet yeri')}</small></div>${mine?`<label class="ka-check"><input type="checkbox" data-dash-duty-book="${esc(x.id)}" ${x.defterDolduruldu?'checked':''}> 📔 Nöbet defterini doldurdum</label>`:x.defterDolduruldu?'<span class="ka-badge ka-badge--success">Tamam</span>':''}</article>`}).join('')}
function dutySection(){if(!cardVisible('duty'))return'';const list=arr('nobetAtamalari').filter(x=>String(x.tarih||'').slice(0,10)===isoToday());if(isAdmin())return section("Bugünün Nöbetçileri",'🛡️','duty',list.length?dutyRows(list):empty('Bugün için nöbet kaydı yok.'));const tid=teacherId(),mine=list.filter(x=>tid&&x.ogretmenId===tid);if(!mine.length)return'';return section('Bugünkü Nöbetim','🛡️','duty',`<div class="ka-home-duty-focus">${dutyRows(mine)}</div>`,'ka-home-section--duty')}
function absencesSection(){if(!isAdmin())return'';const today=isoToday(),active=[...arr('personelIzinler'),...arr('ogretmenIzinleri')].filter(x=>{const a=String(x.baslangicTarihi||x.baslangic||x.tarih||'').slice(0,10),b=String(x.bitisTarihi||x.bitis||x.tarih||a).slice(0,10);return a&&a<=today&&(!b||b>=today)});if(!active.length)return'';return section('Bugün İzinli Olanlar','🏠','absences',active.map(x=>`<article class="ka-home-row"><span class="ka-home-rowicon">🏠</span><div class="ka-grow"><strong>${esc(x.adSoyad||x.personelAdi||x.ogretmenAdi||teacherLabel(x))}</strong><small>${esc(x.izinTuru||x.tur||x.aciklama||'İzinli')}</small></div></article>`).join(''))}
function upcomingRows(){const exams=upcoming([...arr('sinavlar'),...arr('denemeSinavlari')],'tarih',14).map(x=>({icon:'📝',title:x.ad||x.ders||x.sinavAdi||'Sınav',meta:`${date(x.tarih)} · Sınav`}));const reminders=upcoming(arr('hatirlaticilar'),'tarih',14).filter(x=>!x.tamamlandi).map(x=>({icon:'🔔',title:x.baslik||'Hatırlatıcı',meta:`${date(x.tarih)} · Hatırlatıcı`}));const tasks=upcoming(arr('gorevler'),'sonTarih',14).filter(x=>!isDone(x)).map(x=>({icon:'✓',title:x.baslik||'Görev',meta:`${date(x.sonTarih)} · Görev`}));return[...exams,...reminders,...tasks].sort((a,b)=>a.meta.localeCompare(b.meta)).slice(0,8)}
function reminderIcon(source){return({evrak:'📄',gorev:'✓',nobet:'🛡️',sosyalKulupler:'♡',rehberlik:'🧭',maarifRapor:'🏅',zumre:'👥',sok:'🛡️',bepPlani:'📋',belirliGunler:'📅',sinav:'📝',kontrolListesi:'☑️'})[source]||'🔔'}
function teacherUpcomingRows(){return collectReminders(30).filter(x=>x.kaynak!=='sinav').slice(0,8)}
function upcomingSection(){if(!cardVisible('upcoming'))return'';if(isAdmin()){const rows=upcomingRows();return section('Yaklaşan Görevler','📅','upcoming',rows.length?rows.map(r=>`<article class="ka-home-row"><span class="ka-home-rowicon">${r.icon}</span><div class="ka-grow"><strong>${esc(r.title)}</strong><small>${esc(r.meta)}</small></div></article>`).join(''):empty('Yaklaşan kayıt yok.'))}const rows=teacherUpcomingRows();return section('Teslim & Görev Takvimi','📅','upcoming',rows.length?rows.map((r,i)=>{const s=reminderStatus(r);return`<button class="ka-home-row ka-home-reminder-row" type="button" data-dash-reminder-index="${i}"><span class="ka-home-rowicon">${reminderIcon(r.kaynak)}</span><div class="ka-grow"><strong>${esc(r.baslik)}</strong><small>${esc(r.altBaslik||'')}</small></div><span class="ka-badge ${s.cls}">${esc(s.label)}</span></button>`}).join(''):empty('Bekleyen teslim veya görev yok.'))}
function lessonsSection(){const teacherMode=!isAdmin(),tid=teacherId(),mine=teacherMode&&!!tid,all=teacherMode&&!tid?[]:todayLessons({mine}),live=window.SchoolLiveStatus?.status?.();let list=all,title=teacherMode?'Ders Programım':'Şu Anki Dersler';if(isAdmin()){const period=live?.mode==='lesson'?live.period:live?.nextPeriod;if(period)list=all.filter(x=>Number(x.saat??x.dersSaati)===Number(period));else if(['after','weekend'].includes(live?.mode))list=[];title=live?.mode==='lesson'?'Şu Anki Dersler':live?.nextPeriod?`Sonraki Dersler · ${live.nextPeriod}. Ders`:'Şu Anki Dersler'}const rows=list.length?`<div class="ka-home-lessons ${teacherMode?'ka-home-lessons--teacher':''}">${list.slice(0,10).map(x=>{const period=Number(x.saat??x.dersSaati),now=teacherMode&&live?.mode==='lesson'&&Number(live.period)===period,next=teacherMode&&!now&&Number(live?.nextPeriod)===period;return`<article ${mine?`data-dash-lesson-plan data-lesson="${esc(lessonLabel(x))}" data-class="${esc(classLabel(x))}"`:`data-dash-route="academic" data-dash-page="schedule" data-dash-title="Ders Programı"`}><span>${esc(String(x.saat??x.dersSaati??'•'))}</span><div><strong>${esc(lessonLabel(x))}</strong><small>${esc(classLabel(x))}${mine?' · Haftalık kazanımlar':` · ${esc(teacherLabel(x))}`}</small></div>${now?'<em class="ka-home-lesson-state active">Şimdi</em>':next?'<em class="ka-home-lesson-state">Sıradaki</em>':''}</article>`}).join('')}</div>${teacherMode?'<button class="ka-home-link ka-home-link--footer" type="button" data-dash-route="academic" data-dash-page="schedule" data-dash-title="Ders Programı"><span>Haftalık programı aç</span><b>›</b></button>':''}`:empty(isAdmin()?'Bu ders saati için program kaydı yok.':tid?'Bugün için ders programı kaydı yok.':'Profilinize bağlı öğretmen kaydı bulunamadı.');return section(title,'📚','lessons',rows)}
function weekDatesLegacy(){const d=new Date(),diff=(d.getDay()+6)%7,mon=new Date(d);mon.setDate(d.getDate()-diff);mon.setHours(0,0,0,0);return Array.from({length:5},(_,i)=>{const x=new Date(mon);x.setDate(mon.getDate()+i);return x})}
function dutyPlace(x){return x?.yerAdi||arr('nobetYerleri').find(y=>y.id===x?.yerId)?.ad||''}
function isDutyChief(x){const y=normalizeDay(dutyPlace(x)),r=normalizeDay(x?.rol||x?.gorev||x?.tur||'');if(r.includes('mudur')||r.includes('idareci')||r.includes('sorumlu'))return true;return y.includes('mudur yardimci')||y.includes('mudur yrd')||y.includes('idare')||y==='mudur'||y==='mudurluk'}
function dutyPlaceKind(v){const n=normalizeDay(v);if(n.includes('bahce'))return{type:'yard',ico:'🌳'};if(n.includes('bina')||n.includes('kat')||n.includes('koridor'))return{type:'building',ico:'🏫'};if(n.includes('mudur')||n.includes('idare'))return{type:'admin',ico:'🧑‍💼'};return{type:'other',ico:'📍'}}
function dutyPlaceRank(v){return({yard:0,building:1,other:2,admin:3})[dutyPlaceKind(v).type]??4}
function sortDuties(list){return[...list].sort((a,b)=>dutyPlaceRank(dutyPlace(a))-dutyPlaceRank(dutyPlace(b))||teacherLabel(a).localeCompare(teacherLabel(b),'tr'))}
function dutyPlaceHtml(v){const p=dutyPlaceKind(v);return `<span class="kh-place ${p.type}"><span class="kh-place-ico">${p.ico}</span><b>${esc(v||'—')}</b></span>`}
function weekDutySection(){
  const dates=weekDatesLegacy(),all=arr('nobetAtamalari'),today=isoToday(),tid=teacherId(),teacherMode=!isAdmin()&&!!tid,calendarIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/></svg>';
  const rows=dates.map(d=>{const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,entries=sortDuties(all.filter(x=>String(x.tarih||'').slice(0,10)===key&&!isDutyChief(x)));return `<div class="kh-weekday ${key===today?'today':''}"><div class="kh-weekday-head"><span>${esc(dayName(d).toLocaleUpperCase('tr'))}</span>${key===today?'<span class="kh-chip">BUGÜN</span>':''}</div>${entries.length?entries.map(x=>{const mine=teacherMode&&x.ogretmenId===tid;return`<div class="kh-mini${mine?' is-me':''}"><span>${esc(teacherLabel(x))}</span>${dutyPlaceHtml(dutyPlace(x)||'—')}</div>`}).join(''):'<div class="kh-mini"><span class="kh-duty-empty">Nöbet kaydı yok</span><span></span></div>'}</div>`}).join('');
  if(!all.some(x=>{const k=String(x.tarih||'').slice(0,10);return dates.some(d=>k===`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)}))return'';
  return `<section class="kh-section" data-home-section="week-duty"><div class="kh-section-head"><div class="kh-section-title">${calendarIcon}<span>Haftanın Nöbet Programı</span></div><button type="button" class="kh-more" data-dash-route="management" data-dash-page="duty" data-dash-title="Nöbet Programı">Tümü ›</button></div><div class="kh-card">${rows}</div></section>`
}
function examsSection(){const teacherMode=!isAdmin(),tid=teacherId();if(teacherMode&&!tid)return'';const list=upcoming(arr('sinavlar'),'tarih',30).filter(x=>!teacherMode||x.ogretmenId===tid).slice(0,6);if(!list.length)return'';const body=list.map(x=>{const d=dayDiff(x.tarih),status=d===0?'Bugün':d===1?'Yarın':`${d} gün`;return`<button class="ka-home-row ka-home-exam-row" type="button" data-dash-route="academic" data-dash-page="written" data-dash-title="Yazılı Sınavlar"><span class="ka-home-datebox"><b>${esc(String(new Date(x.tarih+'T00:00:00').getDate()))}</b><small>${esc(new Date(x.tarih+'T00:00:00').toLocaleDateString('tr-TR',{month:'short'}))}</small></span><div class="ka-grow"><strong>${esc(x.ders||x.ad||x.sinavAdi||'Sınav')}</strong><small>${esc(x.siniflar||x.sinif||x.sinifAdi||'')}${x.saat?` · ${esc(x.saat)}`:''}</small></div><span class="ka-badge ${d<=1?'ka-badge--warning':''}">${esc(status)}</span></button>`}).join('');return section(teacherMode?'Yaklaşan Yazılı Sınavlar':'Yaklaşan Sınavlar','📝','exams',`${body}${teacherMode?'<button class="ka-home-link ka-home-link--footer" type="button" data-dash-route="academic" data-dash-page="written" data-dash-title="Yazılı Sınavlar"><span>Tüm yazılıları aç</span><b>›</b></button>':''}`)}
function personalScheduleSection(){const tid=!isAdmin()?teacherId():'';if(!tid)return'';const list=arr('dersProgrami').filter(x=>x.ogretmenId===tid).sort((a,b)=>{const ai=DAY_NAMES.indexOf(a.gun),bi=DAY_NAMES.indexOf(b.gun);return(ai-bi)||sortHour(a,b)});if(!list.length)return'';return section('Ders Programım','⏱️','schedule',`<div class="ka-home-schedule">${DAY_NAMES.slice(1,6).map(g=>{const rows=list.filter(x=>sameDay(x.gun,g));return rows.length?`<div><strong>${g}</strong><span>${rows.map(x=>`${esc(String(x.saat??'•'))}. ${esc(classLabel(x))}`).join(' · ')}</span></div>`:''}).join('')}</div>${routeButton('Tüm programı aç','academic','schedule','Ders Programı','›')}`)}
function notesSection(){const u=user(),list=arr('notlar').filter(x=>u.admin||!x.sahipUid||x.sahipUid===u.uid).sort((a,b)=>String(b.tarih||b.olusturmaTarihi||'').localeCompare(String(a.tarih||a.olusturmaTarihi||''))).slice(0,4);return section('Notlarım','📒','notes',list.length?list.map(x=>`<article class="ka-home-note"><strong>${esc(x.baslik||'Not')}</strong><p>${esc(String(x.icerik||x.not||x.metin||'').slice(0,130))}</p></article>`).join(''):empty('Henüz notunuz yok.'))}
function quickSection(){return section('Hızlı İşlemler','⚡','quick',`<div class="ka-home-quick"><button type="button" data-dash-route="academic" data-dash-page="written" data-dash-title="Yazılı Sınavlar"><span>📝</span><b>Sınav Ekle</b></button><button type="button" data-dash-quick-note><span>📒</span><b>Not Ekle</b></button><button type="button" data-dash-route="communication" data-dash-page="messages" data-dash-title="Mesajlaşma"><span>💬</span><b>Mesaj Gönder</b></button><button type="button" data-dash-route="communication" data-dash-page="announcements" data-dash-title="Duyurular"><span>📣</span><b>Duyurular</b></button></div>`) }
function calendarSection(){if(isAdmin())return'';const now=new Date(),days=[],personal=collectReminders(6).filter(x=>x.gunFarki>=0&&x.gunFarki<=6);for(let i=0;i<7;i++){const d=new Date(now);d.setDate(now.getDate()+i);days.push({d,count:personal.filter(x=>x.gunFarki===i).length})}return section('Takvim','📆','calendar',`<div class="ka-home-calendar">${days.map((x,i)=>`<article class="${i===0?'today':''}"><small>${esc(x.d.toLocaleDateString('tr-TR',{weekday:'short'}))}</small><b>${x.d.getDate()}</b>${x.count?`<span>${x.count}</span>`:'<i></i>'}</article>`).join('')}</div>${routeButton('Takvimi aç','communication','calendar','Takvim','›')}`)}
function socialSection(){const school=arr('okulBilgileri').find(x=>x.id==='ayarlar')||arr('okulBilgileri')[0]||{},links=Array.isArray(school.sosyalLinkler)?school.sosyalLinkler.filter(x=>x?.url):[];if(!links.length)return'';return section('Sosyal Medya ve Okul Siteleri','🌐','social',`<div class="ka-home-social">${links.slice(0,6).map(x=>`<button type="button" data-dash-external="${esc(x.url)}"><span>${esc(x.ikon||'🌐')}</span><b>${esc(x.etiket||'Bağlantı')}</b></button>`).join('')}</div>`)}
function allTodayDutySection(){if(isAdmin())return'';const list=arr('nobetAtamalari').filter(x=>String(x.tarih||'').slice(0,10)===isoToday());if(!list.length)return'';const places=arr('nobetYerleri'),tid=teacherId();return section("Bugünün Nöbetçileri",'🛡️','today-duty',list.map(x=>{const mine=!!tid&&x.ogretmenId===tid;return`<article class="ka-home-row${mine?' is-me':''}"><span class="ka-home-rowicon">🛡️</span><div class="ka-grow"><strong>${esc(teacherLabel(x))}</strong><small>${esc(x.yerAdi||places.find(p=>p.id===x.yerId)?.ad||'Nöbet yeri')}</small></div><span class="ka-badge ${mine?'ka-badge--success':''}">${mine?'Siz':'Bugün'}</span></article>`}).join(''))}
function adminShell(){return`${cardVisible('welcome')?hero():''}${announcementSection()}${pollSection()}${trialCounterSection()}${newsSection()}${statsSection()}${dutySection()}${absencesSection()}${upcomingSection()}${lessonsSection()}${weekDutySection()}${examsSection()}${notesSection()}`}
function teacherShell(){return`${cardVisible('welcome')?hero():''}${statsSection()}${announcementSection()}${pollSection()}${trialCounterSection()}${newsSection()}${lessonsSection()}${dutySection()}${examsSection()}${upcomingSection()}${quickSection()}${calendarSection()}${notesSection()}${allTodayDutySection()}${weekDutySection()}${socialSection()}`}
function shell(){const configured=cards().map(x=>x.key).join('|');return`<section class="ka-home" data-dashboard-module data-dashboard-role="${isAdmin()?'admin':'teacher'}" data-card-signature="${esc(configured)}">${isAdmin()?adminShell():teacherShell()}</section>`}
function bindPresentation(root){
  root.querySelectorAll('[data-dash-external]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const url=btn.dataset.dashExternal;if(url)window.open(url,'_blank','noopener,noreferrer')}));
  root.querySelectorAll('[data-dash-route]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();return window.ShellUI?.routeModule?.(btn.dataset.dashRoute,{bottom:'menu',page:btn.dataset.dashPage||'',title:btn.dataset.dashTitle||''})}));
  root.querySelectorAll('[data-dash-lesson-plan]').forEach(btn=>btn.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();const ok=await window.ShellUI?.routeModule?.('academic',{bottom:'menu',title:'Yıllık Plan'});if(ok===false)return;const opened=await window.AcademicModule?.openPlanForLesson?.(btn.dataset.lesson||'',btn.dataset.class||'');if(opened===false)window.toast?.('Bu ders ve sınıf için eşleşen yıllık plan bulunamadı.')}));
  root.querySelectorAll('[data-dash-duty-book]').forEach(box=>box.addEventListener('change',async()=>{const atama=arr('nobetAtamalari').find(x=>x.id===box.dataset.dashDutyBook);if(!atama)return;box.disabled=true;try{await window.DutyBookService?.toggle?.(atama,box.checked);window.toast?.(box.checked?'✅ Nöbet defteri işaretlendi.':'Nöbet defteri işareti kaldırıldı.')}catch(e){box.checked=!box.checked;window.toast?.(e?.message==='sahip-degil'?'Bu nöbet size ait değil.':'Nöbet defteri durumu güncellenemedi.')}finally{box.disabled=false}}));
  root.querySelectorAll('[data-dash-reminder-index]').forEach(btn=>btn.addEventListener('click',()=>teacherUpcomingRows()[Number(btn.dataset.dashReminderIndex)]?.git?.()));
  root.querySelectorAll('[data-dash-announcement-read]').forEach(box=>{box.addEventListener('click',e=>e.stopPropagation());box.addEventListener('change',async e=>{e.preventDefault();e.stopPropagation();if(!box.checked)return;box.disabled=true;try{await window.DuyurularService?.okunduIsaretle?.(box.dataset.dashAnnouncementRead);window.toast?.('Duyuru okundu olarak işaretlendi.');requestAnimationFrame(render)}catch(err){box.checked=false;window.toast?.(err?.message||'Duyuru güncellenemedi.')}finally{box.disabled=false}})});
  root.querySelector('[data-dash-quick-note]')?.addEventListener('click',()=>window.ShellUI?.openQuickNote?.())
}

/* ========================= LOCAL-FIRST HATIRLATMA MOTORU ========================= */
const REMINDER_DEFS={evrakTakibi:'evrak',sosyalKulupler:'sosyalKulupler',rehberlik:'rehberlik',maarifRapor:'maarifRapor',zumre:'zumre',sok:'sok',bepPlani:'bepPlani',belirliGunler:'belirliGunler',kontrolListeleri:'kontrolListeleri',kontrolListeTamamlama:'kontrolListeTamamlama',hatirlatmaAyarlari:'hatirlatmaAyarlari',dersSaatleri:'dersSaatleri',personelIzinler:'personelIzinler',ogretmenIzinleri:'ogretmenIzinleri',anketler:'anketler'};
const MONTH_NAMES=['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
const MONTHLY={sosyalKulupler:{aylar:['Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz'],start:2,label:'Sosyal Kulüp Aylık Rapor',teacherField:'ogretmenIdler'},rehberlik:{aylar:['Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz'],start:1,label:'Rehberlik Aylık Rapor',teacherField:'ogretmenId'},maarifRapor:{aylar:['Eyl','Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz'],start:0,label:'Maarif Model Aylık Rapor',teacherField:'ogretmenId'}};
const ONE_OFF=[{type:'sosyalKulupler',field:'yillikPlanTarihi',index:0,label:'Sosyal Kulüp — Yıllık Plan',teacherField:'ogretmenIdler'},{type:'sosyalKulupler',field:'toplumHizmetiTarihi',index:1,label:'Sosyal Kulüp — Toplum Hizmeti Planı',teacherField:'ogretmenIdler'},{type:'rehberlik',field:'yillikPlanTarihi',index:0,label:'Rehberlik — Yıllık Çalışma Planı',teacherField:'ogretmenId'},{type:'bepPlani',field:'yillikDersPlaniTarihi',index:0,label:'Yıllık Ders Planı',teacherField:'ogretmenId'},{type:'bepPlani',field:'bepPlaniTarihi',index:1,label:'BEP Planı',teacherField:'ogretmenId'}];
function reminderSettings(){return{gunSayisi:3,erteleSaat:4,...(arr('hatirlatmaAyarlari').find(x=>x.id==='ayarlar')||arr('hatirlatmaAyarlari')[0]||{})}}
function dayDiff(iso){if(!iso)return 99999;const a=new Date(isoToday()+'T00:00:00'),b=new Date(String(iso).slice(0,10)+'T00:00:00');return Number.isNaN(b.getTime())?99999:Math.round((b-a)/86400000)}
function nextMonthFirstWeek(year,month0){let m=month0+1,y=year;if(m>11){m=0;y++}return`${y}-${String(m+1).padStart(2,'0')}-07`}
function academicMonthDeadline(shortName){const idx=MONTH_NAMES.indexOf(shortName);if(idx<0)return null;const now=new Date();let iso=nextMonthFirstWeek(now.getFullYear(),idx);if(new Date(iso+'T00:00:00')>now)iso=nextMonthFirstWeek(now.getFullYear()-1,idx);return iso}
function belongs(row,id,field){return field==='ogretmenIdler'?(row?.[field]||[]).includes(id):row?.[field]===id}
function route(module,page='',title=''){return()=>{if(window.ShellUI?.routeModule)return window.ShellUI.routeModule(module,{bottom:'menu',page,title});document.querySelector(`[data-ka-module="${module}"]`)?.click()}}
function reminder(type,title,subtitle,diff,module,page='',pageTitle=''){return{kaynak:type,baslik:title,altBaslik:subtitle||'',gunFarki:diff,module,page,git:route(module,page,pageTitle)}}
const REMINDER_ROUTE_MAP=Object.freeze({sosyalKulupler:['tools','form-kulup','Sosyal Kulüpler'],rehberlik:['tools','form-rehberlik','Rehberlik'],maarifRapor:['tools','form-maarif','Maarif Model'],zumre:['tools','form-zumre','Zümre'],sok:['tools','form-sok','ŞÖK'],bepPlani:['tools','form-bep','BEP Planları'],belirliGunler:['tools','form-belirli','Belirli Günler ve Haftalar'],kontrolListesi:['tools','checklists','Kontrol Listeleri'],nobet:['management','duty','Nöbet Programı'],sinav:['academic','written','Yazılı Sınavlar']});
function exactReminder(type,title,subtitle,diff){const target=REMINDER_ROUTE_MAP[type];if(!target)throw new Error('Hatırlatma hedefi tanımsız: '+type);return reminder(type,title,subtitle,diff,target[0],target[1],target[2])}
function scanTasks(id,days){return arr('gorevler').filter(x=>(x.sorumluOgretmenIdler||[]).includes(id)&&!['tamamlandi','Tamamlandı','Tamamlandi'].includes(x.durum)&&x.sonTarih).map(x=>reminder('gorev',`Görev: ${x.baslik||'Görev'}`,x.aciklama,dayDiff(x.sonTarih),'dashboard')).filter(x=>x.gunFarki<=days)}
function scanDocuments(id,days){return arr('evrakTakibi').filter(x=>(x.sorumluOgretmenIdler||[]).includes(id)&&!['Tamamlandı','Tamamlandi','Arşivlendi','Arsivlendi'].includes(x.durum)&&x.tarih).map(x=>reminder('evrak',`Evrak: ${x.evrakAdi||x.baslik||'Evrak'}`,x.aciklama,dayDiff(x.tarih),'documents','evrak','Evrak Takibi')).filter(x=>x.gunFarki<=days)}
function scanDuty(id){const today=isoToday(),places=arr('nobetYerleri');return arr('nobetAtamalari').filter(x=>x.tarih===today&&x.ogretmenId===id&&!x.defterDolduruldu).map(x=>exactReminder('nobet',`Bugün nöbetçisiniz: ${places.find(p=>p.id===x.yerId)?.ad||x.yerAdi||'Nöbet'}`,'Nöbet defterini doldurmayı unutmayın',0))}
function scanMonthly(id,days){const out=[];Object.entries(MONTHLY).forEach(([type,cfg])=>arr(type).forEach(row=>{if(!belongs(row,id,cfg.teacherField))return;cfg.aylar.forEach((shortName,i)=>{if((row.kontroller||[])[cfg.start+i])return;const target=academicMonthDeadline(shortName),diff=dayDiff(target);if(diff>=-400&&diff<=days)out.push(exactReminder(type,`${cfg.label} — ${shortName}`,row.ders||row.sinif||row.rapor||'',diff))})}));return out}
function scanPeriods(id,days){const out=[];for(const type of ['zumre','sok'])arr(type).forEach(row=>{if(row.ogretmenId!==id)return;['tarih1','tarih2','tarih3'].forEach((field,i)=>{const target=row[field];if(!target||(row.kontroller||[])[i])return;const diff=dayDiff(target);if(diff<=days)out.push(exactReminder(type,`${type==='zumre'?'Zümre Toplantısı':'ŞÖK'} — ${['1. Dönem','2. Dönem','Yıl Sonu'][i]}: ${row.brans||row.konu||row.sinif||''}`.trim(),row.sinif&&row.brans?row.sinif:'',diff))})});return out}
function scanOneOff(id,days){const out=[];ONE_OFF.forEach(cfg=>arr(cfg.type).forEach(row=>{if(!belongs(row,id,cfg.teacherField))return;const target=row[cfg.field];if(!target||(row.kontroller||[])[cfg.index])return;const diff=dayDiff(target);if(diff<=days)out.push(exactReminder(cfg.type,cfg.label,row.ad||row.brans||row.sinif||'',diff))}));return out}
function scanSpecialDays(id,days){return arr('belirliGunler').filter(x=>(x.ogretmenIdler||[]).includes(id)&&!(x.kontroller||[])[0]&&x.tarihBaslangic).map(x=>exactReminder('belirliGunler',`Belirli Gün/Hafta: ${x.ad||''}`,'',dayDiff(x.tarihBaslangic))).filter(x=>x.gunFarki<=days)}
function scanExams(id,days){return arr('sinavlar').filter(x=>x.ogretmenId===id&&x.tarih).map(x=>exactReminder('sinav',`Yazılı Sınav: ${x.ders||''} ${x.sinif||''}`.trim(),x.saat?`Saat: ${x.saat}`:'',dayDiff(x.tarih))).filter(x=>x.gunFarki>=0&&x.gunFarki<=days)}
function linkedTeacherIds(row){if(Array.isArray(row?.ogretmenIdler))return row.ogretmenIdler;if(row?.ogretmenId)return[row.ogretmenId];return[]}
function linkedDate(type,row,index){if(!row)return null;if(type==='zumre'||type==='sok')return row[`tarih${index+1}`]||null;if(type==='sosyalKulupler'){if(index===0)return row.yillikPlanTarihi||null;if(index===1)return row.toplumHizmetiTarihi||null;const short=MONTHLY.sosyalKulupler.aylar[index-2];return short?academicMonthDeadline(short):null}if(type==='rehberlik'){if(index===0)return row.yillikPlanTarihi||null;const short=MONTHLY.rehberlik.aylar[index-1];return short?academicMonthDeadline(short):null}if(type==='bepPlani')return index===0?(row.yillikDersPlaniTarihi||null):(row.bepPlaniTarihi||null);if(type==='maarifRapor'){const short=MONTHLY.maarifRapor.aylar[index];return short?academicMonthDeadline(short):null}if(type==='belirliGunler')return row.tarihBaslangic||null;return row.tarih||row.sonTarih||null}
function itemTargetsTeacher(item,id){if(item.baglıEvrak){const ids=item.baglıEvrak.kayitIdler||(item.baglıEvrak.kayitId?[item.baglıEvrak.kayitId]:[]);return ids.some(rid=>linkedTeacherIds(arr(item.baglıEvrak.tip).find(x=>x.id===rid)).includes(id))}if(!item.hedefTip||item.hedefTip==='herkes')return true;if(item.hedefTip==='ozel')return(item.hedefOgretmenIdler||[]).includes(id);const teacher=arr('ogretmenler').find(x=>x.id===id);if(!teacher||typeof window.kademeFiiliListesi!=='function')return true;return window.kademeFiiliListesi(teacher).includes(item.hedefTip)}
function scanChecklists(id,days){const out=[];for(const list of arr('kontrolListeleri').filter(x=>x.yayinda!==false)){const complete=new Set((arr('kontrolListeTamamlama').find(x=>x.id===`${id}_${list.id}`||x.ogretmenId===id&&x.listeId===list.id)?.tamamlananMaddeIdler)||[]);for(const item of list.maddeler||[]){if(!itemTargetsTeacher(item,id))continue;let target=item.tarih,done=complete.has(item.id);if(item.baglıEvrak){const ids=item.baglıEvrak.kayitIdler||(item.baglıEvrak.kayitId?[item.baglıEvrak.kayitId]:[]),indices=item.baglıEvrak.kontrolIndexler||(item.baglıEvrak.kontrolIndex!==undefined?[item.baglıEvrak.kontrolIndex]:[]),row=ids.map(rid=>arr(item.baglıEvrak.tip).find(x=>x.id===rid)).find(x=>x&&linkedTeacherIds(x).includes(id));if(!row)continue;const relevant=indices.length?indices:[0];done=relevant.every(i=>(row.kontroller||[])[i]);target=relevant.map(i=>linkedDate(item.baglıEvrak.tip,row,i)).filter(Boolean).sort()[0]||null}if(!target||done)continue;const diff=dayDiff(target);if(diff<=days)out.push(exactReminder('kontrolListesi',`Kontrol Listesi: ${list.ad||'Liste'}`,item.metin||'',diff))}}return out}
function collectReminders(daysOverride=null){const id=teacherId();if(!id)return[];const days=Number.isFinite(Number(daysOverride))?Math.max(0,Number(daysOverride)):(Number(reminderSettings().gunSayisi)||3);return[...scanTasks(id,days),...scanDocuments(id,days),...scanDuty(id),...scanMonthly(id,days),...scanPeriods(id,days),...scanOneOff(id,days),...scanSpecialDays(id,days),...scanExams(id,days),...scanChecklists(id,days)].filter(x=>Number.isFinite(x.gunFarki)).sort((a,b)=>a.gunFarki-b.gunFarki)}
function holidayMode(){return !!(arr('dersSaatleri').find(x=>x.id==='ayarlar')||arr('dersSaatleri')[0]||{}).tatilModu}
async function reminderSnoozed(){const u=user().uid;if(!u||!window.KorukLocalFirst)return false;const until=await KorukLocalFirst.meta(u,'reminderSnoozeUntil');return Number(until||0)>Date.now()}
async function snoozeReminders(){const hours=Number(reminderSettings().erteleSaat)||4,u=user().uid;if(u&&window.KorukLocalFirst)await KorukLocalFirst.meta(u,'reminderSnoozeUntil',Date.now()+hours*3600000);closeReminderPopup()}
function closeReminderPopup(){document.getElementById('dashboardReminderModal')?.remove()}
function reminderStatus(r){if(r.gunFarki<0)return{label:`${Math.abs(r.gunFarki)} gün gecikti`,cls:'ka-badge--danger'};if(r.gunFarki===0)return{label:'Bugün son gün',cls:'ka-badge--warning'};return{label:`${r.gunFarki} gün kaldı`,cls:''}}
function openReminderPopup(items){closeReminderPopup();const settings=reminderSettings(),ov=document.createElement('div');ov.id='dashboardReminderModal';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><strong>🔔 Hatırlatmalarınız</strong><div class="ka-muted">${items.length} bekleyen madde</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-reminder-close>Kapat</button></div><div class="ka-modal__body ka-stack">${items.map((r,i)=>{const s=reminderStatus(r);return`<button class="ka-btn ka-btn--secondary" type="button" data-reminder-index="${i}"><span class="ka-grow"><strong>${esc(r.baslik)}</strong>${r.altBaslik?`<small>${esc(r.altBaslik)}</small>`:''}</span><span class="ka-badge ${s.cls}">${esc(s.label)}</span></button>`}).join('')}</div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-reminder-snooze>⏰ ${Number(settings.erteleSaat)||4} saat ertele</button><button class="ka-btn" type="button" data-reminder-ok>Tamam</button></div></section>`;document.body.appendChild(ov);ov.querySelector('[data-reminder-close]').onclick=closeReminderPopup;ov.querySelector('[data-reminder-ok]').onclick=closeReminderPopup;ov.querySelector('[data-reminder-snooze]').onclick=snoozeReminders;ov.querySelectorAll('[data-reminder-index]').forEach(btn=>btn.onclick=()=>{const r=items[Number(btn.dataset.reminderIndex)];closeReminderPopup();r?.git?.()})}
async function maybeShowReminders(){if(reminderShown||holidayMode()||await reminderSnoozed())return;const items=collectReminders();if(!items.length)return;reminderShown=true;openReminderPopup(items)}
async function prepareReminderData(){if(!window.SyncEngine||!window.COL)return;const types=[];for(const[type,colKey]of Object.entries(REMINDER_DEFS)){const col=COL[colKey];if(!col)continue;SyncEngine.register(type,col);types.push(type)}if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(120)}}
function render(){if(!mounted)return;const root=document.querySelector('[data-dashboard-module]');if(!root)return;const parent=root.parentElement||document.getElementById('v2ModuleRoot'),signature=cards().map(x=>x.key).join('|'),role=isAdmin()?'admin':'teacher';if(root.dataset.cardSignature!==signature||root.dataset.dashboardRole!==role){parent.innerHTML=shell();bindPresentation(parent);return}const scrollY=window.scrollY;parent.innerHTML=shell();bindPresentation(parent);if(scrollY>0)requestAnimationFrame(()=>window.scrollTo(0,scrollY))}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];const base=['data.ogretmenler','data.dersProgrami','data.siniflar','data.veliler','data.servisler','data.hatirlaticilar','data.gorevler','data.sinavlar','data.denemeSinavlari','data.duyurular','data.haberler','data.anketler','data.nobetAtamalari','data.nobetYerleri','data.personelIzinler','data.ogretmenIzinleri','data.notlar','data.appConfig','session.user'],paths=[...new Set([...base,...Object.keys(REMINDER_DEFS).map(t=>'data.'+t)])];paths.forEach(p=>{const u=window.AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bindPresentation(root);subscribe();await prepareReminderData();render();clearInterval(trialTimer);trialTimer=setInterval(()=>refreshTrialTimers(),1000);requestAnimationFrame(()=>maybeShowReminders());return true}
function unmount(){mounted=false;clearInterval(trialTimer);trialTimer=null;closeReminderPopup();unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.DashboardModule={mount,unmount,render,collectReminders,maybeShowReminders,prepareReminderData};
window.uygulamaBaslat=function(){window.AppLoader?.load?.('dashboard').then(()=>mount()).catch(e=>console.warn('[Dashboard]',e?.message||e))};
window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='dashboard')mount()});
window.addEventListener('koruk:app-config-changed',()=>requestAnimationFrame(render));
})();