/* Koruk Asistan v2 — Dashboard
   Kart görünürlüğü ve sırası AppConfig üzerinden yönetilir.
   Veri kaynağı yalnız AppStore/IndexedDB'dir.
   Eski çok-kaynaklı öğretmen hatırlatma motoru local-first olarak burada yaşar. */
(function(){
'use strict';if(window.DashboardModule)return;
let mounted=false,unsubs=[],reminderShown=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
function isoToday(){const d=new Date(),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function date(v){if(!v)return'—';try{if(typeof v.toDate==='function')return v.toDate().toLocaleDateString('tr-TR');const d=new Date(String(v).length===10?v+'T00:00:00':v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR')}catch(_){return String(v)}}
function user(){return window.AppStore?.get?.('session.user')||window.AKTIF_KULLANICI||{}}
function firstName(){const u=user(),ad=u.ad||u.adSoyad||u.displayName||u.kullaniciAdi||'';return String(ad).trim().split(/\s+/)[0]||'Kullanıcı'}
function teacherId(){const u=user();return u.bagliOgretmenId||u.ogretmenId||''}
function greeting(){const h=new Date().getHours();return h<6?'İyi geceler':h<12?'Günaydın':h<18?'İyi günler':'İyi akşamlar'}
function upcoming(list,field,days=14){const now=new Date(isoToday()+'T00:00:00'),max=new Date(now.getTime()+days*86400000);return list.filter(x=>{if(!x?.[field])return false;const d=new Date(x[field]+'T00:00:00');return d>=now&&d<=max}).sort((a,b)=>String(a[field]).localeCompare(String(b[field])))}
function cards(){return (window.AppConfig?.dashboardCards?.()||[{key:'welcome',visible:true,order:10},{key:'stats',visible:true,order:20},{key:'upcoming',visible:true,order:30},{key:'announcements',visible:true,order:40},{key:'duty',visible:true,order:50}]).filter(x=>x.visible!==false).sort((a,b)=>Number(a.order||0)-Number(b.order||0))}
function cardShell(key){if(key==='welcome')return'<section class="ka-card" data-dashboard-card="welcome"><div class="ka-card__body ka-stack" id="dashWelcome"></div></section>';if(key==='stats')return'<section data-dashboard-card="stats"><div class="ka-grid" id="dashStats"></div></section>';if(key==='upcoming')return'<section class="ka-card" data-dashboard-card="upcoming"><div class="ka-card__header"><h3>Yaklaşanlar</h3></div><div class="ka-card__body ka-stack" id="dashUpcoming"></div></section>';if(key==='announcements')return'<section class="ka-card" data-dashboard-card="announcements"><div class="ka-card__header"><h3>Duyurular</h3></div><div class="ka-card__body ka-stack" id="dashAnnouncements"></div></section>';if(key==='duty')return'<section class="ka-card" data-dashboard-card="duty"><div class="ka-card__header"><h3>Bugünün Nöbeti</h3></div><div class="ka-card__body ka-stack" id="dashDuty"></div></section>';return''}
function shell(){return `<section class="ka-stack" data-dashboard-module>${cards().map(c=>cardShell(c.key)).join('')}</section>`}
function stat(label,value,sub){return `<article class="ka-card"><div class="ka-card__body ka-stack"><span class="ka-muted">${esc(label)}</span><h2>${value}</h2>${sub?`<small class="ka-muted">${esc(sub)}</small>`:''}</div></article>`}
function renderWelcome(){const el=document.getElementById('dashWelcome');if(!el)return;el.innerHTML=`<span class="ka-muted">${greeting()}</span><h2>${esc(firstName())}</h2><div class="ka-row"><span class="ka-badge" id="dashLocalStatus">Cihaz verisi</span><span class="ka-badge" id="dashSyncStatus">Senkron hazır</span></div>`}
function renderStats(){const el=document.getElementById('dashStats');if(!el)return;const teachers=arr('ogretmenler'),classes=arr('siniflar'),students=arr('veliler'),pending=arr('hatirlaticilar').filter(x=>!x.tamamlandi),tasks=arr('gorevler').filter(x=>!['Tamamlandı','Tamamlandi','tamamlandi'].includes(x.durum));el.innerHTML=[stat('Öğretmen',teachers.length),stat('Sınıf',classes.length),stat('Öğrenci',students.length),stat('Bekleyen',pending.length+tasks.length,'görev ve hatırlatıcı')].join('')}
function renderUpcoming(){const el=document.getElementById('dashUpcoming');if(!el)return;const exams=upcoming([...arr('sinavlar'),...arr('denemeSinavlari')],'tarih',14).slice(0,5),reminders=upcoming(arr('hatirlaticilar'),'tarih',14).filter(x=>!x.tamamlandi).slice(0,5),tasks=upcoming(arr('gorevler'),'sonTarih',14).filter(x=>!['Tamamlandı','Tamamlandi','tamamlandi'].includes(x.durum)).slice(0,5);const rows=[...exams.map(x=>({title:x.ad||x.ders||'Sınav',meta:`${date(x.tarih)} · Sınav`})),...reminders.map(x=>({title:x.baslik||'Hatırlatıcı',meta:`${date(x.tarih)} · Hatırlatıcı`})),...tasks.map(x=>({title:x.baslik||'Görev',meta:`${date(x.sonTarih)} · Görev`}))].slice(0,8);el.innerHTML=rows.length?rows.map(r=>`<div class="ka-row ka-row--between"><div class="ka-grow"><strong>${esc(r.title)}</strong><div class="ka-muted">${esc(r.meta)}</div></div></div>`).join(''):'<div class="ka-empty">Yaklaşan kayıt yok.</div>'}
function renderAnnouncements(){const el=document.getElementById('dashAnnouncements');if(!el)return;const list=arr('duyurular').filter(x=>!x.arsivlendi).sort((a,b)=>String(b.tarih||'').localeCompare(String(a.tarih||''))).slice(0,5);el.innerHTML=list.length?list.map(x=>`<div class="ka-stack"><strong>${esc(x.baslik||'Duyuru')}</strong><div class="ka-muted">${esc(String(x.icerik||x.aciklama||'').replace(/<[^>]*>/g,'').slice(0,120))}</div></div>`).join(''):'<div class="ka-empty">Aktif duyuru yok.</div>'}
function renderDuty(){const el=document.getElementById('dashDuty');if(!el)return;const today=isoToday(),assign=arr('nobetAtamalari').filter(x=>x.tarih===today),places=arr('nobetYerleri');el.innerHTML=assign.length?assign.map(x=>{const place=places.find(p=>p.id===x.yerId);return `<div class="ka-row ka-row--between"><div class="ka-grow"><strong>${esc(x.ogretmenAdSoyad||x.ogretmenAdi||'Nöbetçi')}</strong><div class="ka-muted">${esc(x.yerAdi||place?.ad||'Nöbet yeri')}</div></div>${x.defterDolduruldu?'<span class="ka-badge ka-badge--success">Defter tamam</span>':''}</div>`}).join(''):'<div class="ka-empty">Bugün için nöbet kaydı yok.</div>'}
function renderStatus(){const local=document.getElementById('dashLocalStatus'),sync=document.getElementById('dashSyncStatus');if(local)local.textContent=AppStore?.state?.meta?.hydrated?'Cihaz verisi hazır':'Cihaz verisi hazırlanıyor';if(sync){const ui=AppStore?.state?.ui||{};sync.textContent=ui.syncing?'Senkronize ediliyor':(ui.pendingWrites?`${ui.pendingWrites} bekleyen işlem`:'Senkron hazır')}}

/* ========================= LOCAL-FIRST HATIRLATMA MOTORU ========================= */
const REMINDER_DEFS={evrakTakibi:'evrak',sosyalKulupler:'sosyalKulupler',rehberlik:'rehberlik',maarifRapor:'maarifRapor',zumre:'zumre',sok:'sok',bepPlani:'bepPlani',belirliGunler:'belirliGunler',kontrolListeleri:'kontrolListeleri',kontrolListeTamamlama:'kontrolListeTamamlama',hatirlatmaAyarlari:'hatirlatmaAyarlari',dersSaatleri:'dersSaatleri'};
const MONTH_NAMES=['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
const MONTHLY={sosyalKulupler:{aylar:['Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz'],start:2,label:'Sosyal Kulüp Aylık Rapor',teacherField:'ogretmenIdler'},rehberlik:{aylar:['Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz'],start:1,label:'Rehberlik Aylık Rapor',teacherField:'ogretmenId'},maarifRapor:{aylar:['Eyl','Eki','Kas','Ara','Oca','Şub','Mar','Nis','May','Haz'],start:0,label:'Maarif Model Aylık Rapor',teacherField:'ogretmenId'}};
const ONE_OFF=[{type:'sosyalKulupler',field:'yillikPlanTarihi',index:0,label:'Sosyal Kulüp — Yıllık Plan',teacherField:'ogretmenIdler'},{type:'sosyalKulupler',field:'toplumHizmetiTarihi',index:1,label:'Sosyal Kulüp — Toplum Hizmeti Planı',teacherField:'ogretmenIdler'},{type:'rehberlik',field:'yillikPlanTarihi',index:0,label:'Rehberlik — Yıllık Çalışma Planı',teacherField:'ogretmenId'},{type:'bepPlani',field:'yillikDersPlaniTarihi',index:0,label:'Yıllık Ders Planı',teacherField:'ogretmenId'},{type:'bepPlani',field:'bepPlaniTarihi',index:1,label:'BEP Planı',teacherField:'ogretmenId'}];
function reminderSettings(){return{gunSayisi:3,erteleSaat:4,...(arr('hatirlatmaAyarlari').find(x=>x.id==='ayarlar')||arr('hatirlatmaAyarlari')[0]||{})}}
function dayDiff(iso){if(!iso)return 99999;const a=new Date(isoToday()+'T00:00:00'),b=new Date(String(iso).slice(0,10)+'T00:00:00');return Number.isNaN(b.getTime())?99999:Math.round((b-a)/86400000)}
function nextMonthFirstWeek(year,month0){let m=month0+1,y=year;if(m>11){m=0;y++}return`${y}-${String(m+1).padStart(2,'0')}-07`}
function academicMonthDeadline(shortName){const idx=MONTH_NAMES.indexOf(shortName);if(idx<0)return null;const now=new Date();let iso=nextMonthFirstWeek(now.getFullYear(),idx);if(new Date(iso+'T00:00:00')>now)iso=nextMonthFirstWeek(now.getFullYear()-1,idx);return iso}
function belongs(row,id,field){return field==='ogretmenIdler'?(row?.[field]||[]).includes(id):row?.[field]===id}
function route(module){return()=>{document.querySelector(`[data-ka-module="${module}"]`)?.click()}}
function reminder(type,title,subtitle,diff,module){return{kaynak:type,baslik:title,altBaslik:subtitle||'',gunFarki:diff,module,git:route(module)}}
function scanTasks(id,days){return arr('gorevler').filter(x=>(x.sorumluOgretmenIdler||[]).includes(id)&&!['tamamlandi','Tamamlandı','Tamamlandi'].includes(x.durum)&&x.sonTarih).map(x=>reminder('gorev',`Görev: ${x.baslik||'Görev'}`,x.aciklama,dayDiff(x.sonTarih),'dashboard')).filter(x=>x.gunFarki<=days)}
function scanDocuments(id,days){return arr('evrakTakibi').filter(x=>(x.sorumluOgretmenIdler||[]).includes(id)&&!['Tamamlandı','Tamamlandi','Arşivlendi','Arsivlendi'].includes(x.durum)&&x.tarih).map(x=>reminder('evrak',`Evrak: ${x.evrakAdi||x.baslik||'Evrak'}`,x.aciklama,dayDiff(x.tarih),'documents')).filter(x=>x.gunFarki<=days)}
function scanDuty(id){const today=isoToday(),places=arr('nobetYerleri');return arr('nobetAtamalari').filter(x=>x.tarih===today&&x.ogretmenId===id&&!x.defterDolduruldu).map(x=>reminder('nobet',`Bugün nöbetçisiniz: ${places.find(p=>p.id===x.yerId)?.ad||x.yerAdi||'Nöbet'}`,'Nöbet defterini doldurmayı unutmayın',0,'management'))}
function scanMonthly(id,days){const out=[];Object.entries(MONTHLY).forEach(([type,cfg])=>arr(type).forEach(row=>{if(!belongs(row,id,cfg.teacherField))return;cfg.aylar.forEach((shortName,i)=>{if((row.kontroller||[])[cfg.start+i])return;const target=academicMonthDeadline(shortName),diff=dayDiff(target);if(diff>=-400&&diff<=days)out.push(reminder(type,`${cfg.label} — ${shortName}`,row.ders||row.sinif||row.rapor||'',diff,'tools'))})}));return out}
function scanPeriods(id,days){const out=[];for(const type of ['zumre','sok'])arr(type).forEach(row=>{if(row.ogretmenId!==id)return;['tarih1','tarih2','tarih3'].forEach((field,i)=>{const target=row[field];if(!target||(row.kontroller||[])[i])return;const diff=dayDiff(target);if(diff<=days)out.push(reminder(type,`${type==='zumre'?'Zümre Toplantısı':'ŞÖK'} — ${['1. Dönem','2. Dönem','Yıl Sonu'][i]}: ${row.brans||row.konu||row.sinif||''}`.trim(),row.sinif&&row.brans?row.sinif:'',diff,'tools'))})});return out}
function scanOneOff(id,days){const out=[];ONE_OFF.forEach(cfg=>arr(cfg.type).forEach(row=>{if(!belongs(row,id,cfg.teacherField))return;const target=row[cfg.field];if(!target||(row.kontroller||[])[cfg.index])return;const diff=dayDiff(target);if(diff<=days)out.push(reminder(cfg.type,cfg.label,row.ad||row.brans||row.sinif||'',diff,'tools'))}));return out}
function scanSpecialDays(id,days){return arr('belirliGunler').filter(x=>(x.ogretmenIdler||[]).includes(id)&&!(x.kontroller||[])[0]&&x.tarihBaslangic).map(x=>reminder('belirliGunler',`Belirli Gün/Hafta: ${x.ad||''}`,'',dayDiff(x.tarihBaslangic),'tools')).filter(x=>x.gunFarki<=days)}
function scanExams(id,days){return arr('sinavlar').filter(x=>x.ogretmenId===id&&x.tarih).map(x=>reminder('sinav',`Yazılı Sınav: ${x.ders||''} ${x.sinif||''}`.trim(),x.saat?`Saat: ${x.saat}`:'',dayDiff(x.tarih),'academic')).filter(x=>x.gunFarki>=0&&x.gunFarki<=days)}
function linkedTeacherIds(row){if(Array.isArray(row?.ogretmenIdler))return row.ogretmenIdler;if(row?.ogretmenId)return[row.ogretmenId];return[]}
function linkedDate(type,row,index){if(!row)return null;if(type==='zumre'||type==='sok')return row[`tarih${index+1}`]||null;if(type==='sosyalKulupler'){if(index===0)return row.yillikPlanTarihi||null;if(index===1)return row.toplumHizmetiTarihi||null;const short=MONTHLY.sosyalKulupler.aylar[index-2];return short?academicMonthDeadline(short):null}if(type==='rehberlik'){if(index===0)return row.yillikPlanTarihi||null;const short=MONTHLY.rehberlik.aylar[index-1];return short?academicMonthDeadline(short):null}if(type==='bepPlani')return index===0?(row.yillikDersPlaniTarihi||null):(row.bepPlaniTarihi||null);if(type==='maarifRapor'){const short=MONTHLY.maarifRapor.aylar[index];return short?academicMonthDeadline(short):null}if(type==='belirliGunler')return row.tarihBaslangic||null;return row.tarih||row.sonTarih||null}
function itemTargetsTeacher(item,id){if(item.baglıEvrak){const ids=item.baglıEvrak.kayitIdler||(item.baglıEvrak.kayitId?[item.baglıEvrak.kayitId]:[]);return ids.some(rid=>linkedTeacherIds(arr(item.baglıEvrak.tip).find(x=>x.id===rid)).includes(id))}if(!item.hedefTip||item.hedefTip==='herkes')return true;if(item.hedefTip==='ozel')return(item.hedefOgretmenIdler||[]).includes(id);const teacher=arr('ogretmenler').find(x=>x.id===id);if(!teacher||typeof window.kademeFiiliListesi!=='function')return true;return window.kademeFiiliListesi(teacher).includes(item.hedefTip)}
function scanChecklists(id,days){const out=[];for(const list of arr('kontrolListeleri').filter(x=>x.yayinda!==false)){const complete=new Set((arr('kontrolListeTamamlama').find(x=>x.id===`${id}_${list.id}`||x.ogretmenId===id&&x.listeId===list.id)?.tamamlananMaddeIdler)||[]);for(const item of list.maddeler||[]){if(!itemTargetsTeacher(item,id))continue;let target=item.tarih,done=complete.has(item.id);if(item.baglıEvrak){const ids=item.baglıEvrak.kayitIdler||(item.baglıEvrak.kayitId?[item.baglıEvrak.kayitId]:[]),indices=item.baglıEvrak.kontrolIndexler||(item.baglıEvrak.kontrolIndex!==undefined?[item.baglıEvrak.kontrolIndex]:[]),row=ids.map(rid=>arr(item.baglıEvrak.tip).find(x=>x.id===rid)).find(x=>x&&linkedTeacherIds(x).includes(id));if(!row)continue;const relevant=indices.length?indices:[0];done=relevant.every(i=>(row.kontroller||[])[i]);target=relevant.map(i=>linkedDate(item.baglıEvrak.tip,row,i)).filter(Boolean).sort()[0]||null}if(!target||done)continue;const diff=dayDiff(target);if(diff<=days)out.push(reminder('kontrolListesi',`Kontrol Listesi: ${list.ad||'Liste'}`,item.metin||'',diff,'tools'))}}return out}
function collectReminders(){const id=teacherId();if(!id)return[];const days=Number(reminderSettings().gunSayisi)||3;return[...scanTasks(id,days),...scanDocuments(id,days),...scanDuty(id),...scanMonthly(id,days),...scanPeriods(id,days),...scanOneOff(id,days),...scanSpecialDays(id,days),...scanExams(id,days),...scanChecklists(id,days)].filter(x=>Number.isFinite(x.gunFarki)).sort((a,b)=>a.gunFarki-b.gunFarki)}
function holidayMode(){return !!(arr('dersSaatleri').find(x=>x.id==='ayarlar')||arr('dersSaatleri')[0]||{}).tatilModu}
async function reminderSnoozed(){const u=user().uid;if(!u||!window.KorukLocalFirst)return false;const until=await KorukLocalFirst.meta(u,'reminderSnoozeUntil');return Number(until||0)>Date.now()}
async function snoozeReminders(){const hours=Number(reminderSettings().erteleSaat)||4,u=user().uid;if(u&&window.KorukLocalFirst)await KorukLocalFirst.meta(u,'reminderSnoozeUntil',Date.now()+hours*3600000);closeReminderPopup()}
function closeReminderPopup(){document.getElementById('dashboardReminderModal')?.remove()}
function reminderStatus(r){if(r.gunFarki<0)return{label:`${Math.abs(r.gunFarki)} gün gecikti`,cls:'ka-badge--danger'};if(r.gunFarki===0)return{label:'Bugün son gün',cls:'ka-badge--warning'};return{label:`${r.gunFarki} gün kaldı`,cls:''}}
function openReminderPopup(items){closeReminderPopup();const settings=reminderSettings(),ov=document.createElement('div');ov.id='dashboardReminderModal';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><strong>🔔 Hatırlatmalarınız</strong><div class="ka-muted">${items.length} bekleyen madde</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-reminder-close>Kapat</button></div><div class="ka-modal__body ka-stack">${items.map((r,i)=>{const s=reminderStatus(r);return`<button class="ka-btn ka-btn--secondary" type="button" data-reminder-index="${i}"><span class="ka-grow"><strong>${esc(r.baslik)}</strong>${r.altBaslik?`<small>${esc(r.altBaslik)}</small>`:''}</span><span class="ka-badge ${s.cls}">${esc(s.label)}</span></button>`}).join('')}</div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-reminder-snooze>⏰ ${Number(settings.erteleSaat)||4} saat ertele</button><button class="ka-btn" type="button" data-reminder-ok>Tamam</button></div></section>`;document.body.appendChild(ov);ov.querySelector('[data-reminder-close]').onclick=closeReminderPopup;ov.querySelector('[data-reminder-ok]').onclick=closeReminderPopup;ov.querySelector('[data-reminder-snooze]').onclick=snoozeReminders;ov.querySelectorAll('[data-reminder-index]').forEach(btn=>btn.onclick=()=>{const r=items[Number(btn.dataset.reminderIndex)];closeReminderPopup();r?.git?.()})}
async function maybeShowReminders(){if(reminderShown||holidayMode()||await reminderSnoozed())return;const items=collectReminders();if(!items.length)return;reminderShown=true;openReminderPopup(items)}
async function prepareReminderData(){if(!window.SyncEngine||!window.COL)return;const types=[];for(const[type,colKey]of Object.entries(REMINDER_DEFS)){const col=COL[colKey];if(!col)continue;SyncEngine.register(type,col);types.push(type)}if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(120)}}

function render(){if(!mounted)return;const root=document.querySelector('[data-dashboard-module]'),desired=cards().map(x=>x.key).join('|'),current=root?.dataset.cardSignature;if(root&&current!==desired){root.dataset.cardSignature=desired;root.innerHTML=cards().map(c=>cardShell(c.key)).join('')}renderWelcome();renderStats();renderUpcoming();renderAnnouncements();renderDuty();renderStatus()}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.ogretmenler','data.siniflar','data.veliler','data.hatirlaticilar','data.gorevler','data.sinavlar','data.denemeSinavlari','data.duyurular','data.nobetAtamalari','data.nobetYerleri','data.appConfig','ui.syncing','ui.pendingWrites','meta.hydrated','session.user'].forEach(p=>{const u=window.AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();const section=root.querySelector('[data-dashboard-module]');if(section)section.dataset.cardSignature=cards().map(x=>x.key).join('|');subscribe();render();await prepareReminderData();render();requestAnimationFrame(()=>maybeShowReminders());return true}
function unmount(){mounted=false;closeReminderPopup();unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.DashboardModule={mount,unmount,render,collectReminders,maybeShowReminders,prepareReminderData};
window.uygulamaBaslat=function(){window.AppLoader?.load?.('dashboard').then(()=>mount()).catch(e=>console.warn('[Dashboard]',e?.message||e))};
window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='dashboard')mount()});
window.addEventListener('koruk:app-config-changed',()=>requestAnimationFrame(render));
})();
