/* Koruk Asistan — Documents tek modül
 * Doküman metadata + Storage + görünürlük + UI + resmi form çıktıları tek dosyada.
 */
(function(global){
'use strict';
function device(){if(!global.DeviceData)throw new Error('DeviceData hazır değil.');return global.DeviceData;}
const active=()=>global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};
function tarih(d){const t=d?.yuklenmeTarihi;if(!t)return 0;if(typeof t.toMillis==='function')return t.toMillis();if(typeof t.seconds==='number')return t.seconds*1000;return new Date(t).getTime()||0;}
function safeName(ad){return(String(ad||'dosya').replace(/[\\/\u0000-\u001f\u007f]+/g,'_').replace(/\s+/g,' ').trim()||'dosya').slice(0,180);}
function allDocs(){const m=new Map();['dokumanlar','dokumanlarAcik','dokumanlarBenim'].forEach(t=>device().list(t).forEach(d=>d?.id&&m.set(d.id,d)));return[...m.values()];}
function primaryType(){return active().admin?'dokumanlar':'dokumanlarBenim';}
async function mirror(row){if(active().admin)return;const mine=device().list('dokumanlarBenim').filter(x=>x.id!==row.id);mine.push(row);await device().persist('dokumanlarBenim',mine);const open=device().list('dokumanlarAcik').filter(x=>x.id!==row.id);if(row.gorunurluk==='herkes')open.push(row);await device().persist('dokumanlarAcik',open);}
async function unmirror(id){if(active().admin)return;await device().persist('dokumanlarBenim',device().list('dokumanlarBenim').filter(x=>x.id!==id));await device().persist('dokumanlarAcik',device().list('dokumanlarAcik').filter(x=>x.id!==id));}
const fakeDoc=(row,id)=>({exists:!!row,id:id||row?.id||'',data:()=>row?{...row}:undefined});
const DokumanlarRepository={
 dokumanlariDinle(cb){const emit=()=>cb(allDocs().sort((a,b)=>tarih(b)-tarih(a)),{source:'device'});emit();const off=['data.dokumanlar','data.dokumanlarAcik','data.dokumanlarBenim'].map(p=>AppStore.subscribe(p,emit));return()=>off.forEach(f=>f());},
 dokumanGetir(id){return Promise.resolve(fakeDoc(allDocs().find(x=>x.id===id),id));},
 async dokumanEkle(meta){const row=await device().add(primaryType(),COL.dokumanlar,{...meta,yuklenmeTarihi:meta.yuklenmeTarihi||new Date().toISOString()});await mirror(row);return row;},
 async dokumanSil(id){await device().remove(primaryType(),COL.dokumanlar,id);await unmirror(id);return true;},
 async dokumanGuncelle(id,v){const mevcut=allDocs().find(x=>x.id===id)||{id},row=await device().update(primaryType(),COL.dokumanlar,id,v);await mirror({...mevcut,...row});return row;},
 dosyaYukle(dosya,sahipUid,gorunurluk,cb){return new Promise((resolve,reject)=>{if(!sahipUid)return reject(new Error('Dosya sahibi bulunamadı.'));const yol=`dokumanlar/${sahipUid}/${Date.now()}_${safeName(dosya?.name)}`,ref=storage.ref().child(yol),g=ref.put(dosya,{contentType:dosya?.type||'application/octet-stream',customMetadata:{olusturanUid:String(sahipUid),gorunurluk:gorunurluk==='herkes'?'herkes':'kisisel'}});g.on('state_changed',s=>cb?.(Math.round(s.bytesTransferred/s.totalBytes*100)),reject,async()=>resolve({url:await g.snapshot.ref.getDownloadURL(),storagePath:yol}));});},
 async dosyaGorunurlukGuncelle(path,g){if(!path||!/^dokumanlar\/[^/]+\/.+/.test(path))return false;const ref=storage.ref().child(path),m=await ref.getMetadata();await ref.updateMetadata({customMetadata:{...(m.customMetadata||{}),gorunurluk:g==='herkes'?'herkes':'kisisel'}});return true;},dosyaSil:path=>storage.ref().child(path).delete()
};global.DokumanlarRepository=DokumanlarRepository;
const DokumanlarService={
 _kendiKimlik(){const u=active(),k=typeof _hesapKimligi==='function'?_hesapKimligi():{ad:''};return{uid:u.uid||null,ad:k.ad||u.adSoyad||u.displayName||'Kullanıcı',adminMi:u.admin===true};},
 gorunurMu(d){if(!d)return false;if(d.gorunurluk==='herkes')return true;const b=this._kendiKimlik();return b.adminMi||!!(b.uid&&d.olusturanUid===b.uid);},gorunurListele:l=>(l||[]).filter(d=>DokumanlarService.gorunurMu(d)),gorunurlukDegistirilebilirMi(){return this._kendiKimlik().adminMi;},
 async dokumanGorunurlukGuncelle(id,yeni){if(!this.gorunurlukDegistirilebilirMi())throw new Error('yetkisiz');yeni=yeni==='herkes'?'herkes':'kisisel';const snap=await DokumanlarRepository.dokumanGetir(id);if(!snap.exists)throw new Error('Döküman bulunamadı.');const mevcut={id:snap.id,...snap.data()},eski=mevcut.gorunurluk==='herkes'?'herkes':'kisisel';let storageOk=false;if(mevcut.storagePath)storageOk=await DokumanlarRepository.dosyaGorunurlukGuncelle(mevcut.storagePath,yeni);try{return await DokumanlarRepository.dokumanGuncelle(id,{gorunurluk:yeni});}catch(e){if(storageOk)await DokumanlarRepository.dosyaGorunurlukGuncelle(mevcut.storagePath,eski).catch(()=>{});throw e;}},
 dokumanSilinebilirMi(d){const b=this._kendiKimlik();return b.adminMi||!!(b.uid&&d?.olusturanUid===b.uid);},
 async dokumanEkle(meta,dosya,cb){if(!gorebilir('dokumanlar'))throw new Error('yetkisiz');const b=this._kendiKimlik();if(!b.uid)throw new Error('Aktif kullanıcı bulunamadı.');const gorunurluk=b.adminMi&&meta.gorunurluk==='herkes'?'herkes':'kisisel';let next={...meta,gorunurluk,olusturanUid:b.uid,olusturanAdi:b.ad,yuklenmeTarihi:new Date().toISOString()};if(dosya){if(global.DepolamaSinirService){const izin=await DepolamaSinirService.yuklemeIzniVarMi('dokuman',dosya.size);if(!izin.izinVar)throw new Error('depolama-siniri:'+izin.mesaj);}const r=await DokumanlarRepository.dosyaYukle(dosya,b.uid,gorunurluk,cb);next={...next,dosyaUrl:r.url,storagePath:r.storagePath,dosyaAdi:dosya.name,dosyaBoyutu:dosya.size,dosyaTipi:dosya.type};}return DokumanlarRepository.dokumanEkle(next);},
 async dokumanSil(id,path,mevcut){if(!this.dokumanSilinebilirMi(mevcut))throw new Error('sahip-degil');if(path)await DokumanlarRepository.dosyaSil(path).catch(()=>{});return DokumanlarRepository.dokumanSil(id);}
};global.DokumanlarService=DokumanlarService;
})(window);

(function(){
'use strict';if(window.DocumentsModule)return;
let query='',mounted=false,unsubs=[],viewerPromise=null,mode='list',tebligState=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');const arr=t=>{const v=AppStore?.data?.(t);return Array.isArray(v)?v:[]};const uid=()=>window.AKTIF_KULLANICI?.uid||AppStore?.get?.('session.user')?.uid||'';const admin=()=>window.AKTIF_KULLANICI?.admin===true;
function time(d){const t=d?.yuklenmeTarihi;if(!t)return 0;if(typeof t.toMillis==='function')return t.toMillis();if(typeof t.seconds==='number')return t.seconds*1000;return new Date(t).getTime()||0}function docs(){const m=new Map(),source=admin()?arr('dokumanlar'):[...arr('dokumanlarAcik'),...arr('dokumanlarBenim')];source.forEach(d=>d?.id&&m.set(d.id,d));return[...m.values()].sort((a,b)=>time(b)-time(a))}
async function prepareLocal(){if(!SyncEngine||!COL?.dokumanlar)return;const types=[];if(admin()){SyncEngine.register('dokumanlar',COL.dokumanlar);types.push('dokumanlar')}else{SyncEngine.register('dokumanlarAcik',COL.dokumanlar,{query:q=>q.where('gorunurluk','==','herkes')});types.push('dokumanlarAcik');const u=uid();if(u){SyncEngine.register('dokumanlarBenim',COL.dokumanlar,{query:q=>q.where('olusturanUid','==',u)});types.push('dokumanlarBenim')}}if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(120)}}
function shell(){return `<section class="ka-stack" data-documents-module><div class="ka-row ka-row--between"><div><h2>Dokümanlar ve Raporlar</h2><p class="ka-muted">Erişebildiğiniz dokümanlar cihazdan açılır.</p></div><span id="documentsCount" class="ka-badge"></span></div><div class="ka-row"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-document-form="teblig" data-ka-permission="documents.view" data-ka-min-level="preview">Tebliğ‑Tebellüğ Formu</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="documentsSearch" type="search" placeholder="Doküman, kategori veya oluşturan kişi ara…"></label><div id="documentsContent" class="ka-stack"></div></section>`}
function ensureViewer(){if(window.DokumanOkuyucu)return Promise.resolve(window.DokumanOkuyucu);if(viewerPromise)return viewerPromise;viewerPromise=new Promise((resolve,reject)=>{const mevcut=[...document.scripts].find(s=>String(s.getAttribute('src')||'').split('?')[0].endsWith('js/modules/document-viewer.js'));if(mevcut){mevcut.addEventListener('load',()=>resolve(window.DokumanOkuyucu),{once:true});mevcut.addEventListener('error',()=>reject(new Error('Belge görüntüleyici yüklenemedi.')),{once:true});return;}const s=document.createElement('script');s.src='js/modules/document-viewer.js';s.async=true;s.dataset.korukCapability='document-viewer';s.onload=()=>window.DokumanOkuyucu?resolve(window.DokumanOkuyucu):reject(new Error('Belge görüntüleyici hazır değil.'));s.onerror=()=>reject(new Error('Belge görüntüleyici yüklenemedi.'));document.head.appendChild(s)}).catch(e=>{viewerPromise=null;throw e});return viewerPromise;}
async function openDocument(d){if(!d?.dosyaUrl)return;try{if(!PermissionService?.can?.('documents.view','preview'))throw new Error('yetkisiz');const viewer=await ensureViewer();if(viewer?.destekliMi?.(d.dosyaAdi||d.dosyaUrl)){await viewer.ac(d.dosyaUrl,d.dosyaAdi||d.baslik||'Belge');return;}window.open(d.dosyaUrl,'_blank','noopener');}catch(e){console.warn('[Documents/viewer]',e);if(e?.message==='yetkisiz')return;window.open(d.dosyaUrl,'_blank','noopener');}}
function school(){return arr('okulBilgileri').find(x=>x.id==='ayarlar')||arr('okulBilgileri')[0]||window.okulBilgileriAyari||{};}
function teachers(){return arr('ogretmenler').slice().sort((a,b)=>`${a.ad||''} ${a.soyad||''}`.localeCompare(`${b.ad||''} ${b.soyad||''}`,'tr'));}
function blankTeblig(){return{tarihIso:new Date().toISOString().slice(0,10),sayi:'',konu:'',satirlar:[]};}
function teacherName(o){return `${o?.ad||''} ${o?.soyad||''}`.trim();}
function teacherRole(o){return o?.unvan||o?.brans||'Öğretmen';}
function openTeblig(){if(!PermissionService?.can?.('documents.view','preview'))return;mode='teblig';tebligState=blankTeblig();render();}
function tebligReportBody(){const s=tebligState||blankTeblig(),okul=school(),tarih=s.tarihIso?new Date(s.tarihIso+'T00:00:00').toLocaleDateString('tr-TR'):'';return `<h1>${esc(okul.okulAdi||'KORUK İLK-ORTAOKULU')}</h1><h2>Tebliğ‑Tebellüğ Belgesi</h2><table class="ka-table"><tbody><tr><th>Tarih</th><td>${esc(tarih)}</td></tr><tr><th>Sayı</th><td>${esc(s.sayi)}</td></tr><tr><th>Konu</th><td>${esc(s.konu)}</td></tr></tbody></table><p>Yukarıda tarih, sayı ve konusu belirtilen yazı aşağıda adı bulunan personele tebliğ edilmiş ve tebellüğ edilmiştir.</p><table class="ka-table"><thead><tr><th>Sıra</th><th>Adı Soyadı</th><th>Görevi</th><th>İmza</th></tr></thead><tbody>${s.satirlar.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.ad)}</td><td>${esc(r.gorev)}</td><td>........................</td></tr>`).join('')}</tbody></table>`;}
function renderTeblig(out){const s=tebligState||(tebligState=blankTeblig()),edit=PermissionService?.can?.('documents.edit','edit')!==false,opts=teachers().filter(o=>!s.satirlar.some(r=>r.ogretmenId===o.id));out.innerHTML=`<article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><h3>Tebliğ‑Tebellüğ Formu</h3><p class="ka-muted">Resmi yazı bilgilerini ve tebellüğ edecek personeli seçin.</p></div><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-teblig-back>Geri</button></div><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Tarih</span><input type="date" data-teblig-field="tarihIso" value="${esc(s.tarihIso)}" ${edit?'':'readonly'}></label><label class="ka-field"><span class="ka-field__label">Sayı</span><input data-teblig-field="sayi" value="${esc(s.sayi)}" placeholder="E-..." ${edit?'':'readonly'}></label><label class="ka-field"><span class="ka-field__label">Konu</span><input data-teblig-field="konu" value="${esc(s.konu)}" ${edit?'':'readonly'}></label></div>${edit?`<div class="ka-row"><select data-teblig-teacher class="ka-grow"><option value="">— Öğretmen seçin —</option>${opts.map(o=>`<option value="${esc(o.id)}">${esc(teacherName(o))}</option>`).join('')}</select><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-teblig-add>Ekle</button></div>`:''}<div class="ka-stack">${s.satirlar.length?s.satirlar.map((r,i)=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><strong>${esc(r.ad)}</strong><input class="ka-input ka-grow" data-teblig-role="${i}" value="${esc(r.gorev)}" ${edit?'':'readonly'}>${edit?`<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-teblig-remove="${i}">Çıkar</button>`:''}</div></article>`).join(''):'<div class="ka-empty">Henüz personel eklenmedi.</div>'}</div><div class="ka-row"><button class="ka-btn" type="button" data-teblig-report>🖨 A4 Önizleme / PDF</button></div></div></article>`;bindTeblig(out);}
function bindTeblig(out){out.querySelector('[data-teblig-back]')?.addEventListener('click',()=>{mode='list';tebligState=null;render()});out.querySelectorAll('[data-teblig-field]').forEach(el=>el.oninput=()=>{tebligState[el.dataset.tebligField]=el.value});out.querySelector('[data-teblig-add]')?.addEventListener('click',()=>{const sel=out.querySelector('[data-teblig-teacher]'),o=teachers().find(x=>x.id===sel?.value);if(!o)return;tebligState.satirlar.push({ogretmenId:o.id,ad:teacherName(o),gorev:teacherRole(o)});render()});out.querySelectorAll('[data-teblig-role]').forEach(el=>el.oninput=()=>{const r=tebligState.satirlar[Number(el.dataset.tebligRole)];if(r)r.gorev=el.value});out.querySelectorAll('[data-teblig-remove]').forEach(b=>b.onclick=()=>{tebligState.satirlar.splice(Number(b.dataset.tebligRemove),1);render()});out.querySelector('[data-teblig-report]')?.addEventListener('click',()=>{if(!window.ReportEngine?.printReport){window.toast?.('Rapor motoru hazır değil.');return}window.ReportEngine.printReport('Tebliğ-Tebellüğ Belgesi',tebligReportBody(),{fileName:'Teblig_Tebellug_Belgesi',yon:'dikey'})});PermissionService?.apply?.(out);}
function render(){if(!mounted)return;const out=document.getElementById('documentsContent'),count=document.getElementById('documentsCount');if(mode==='teblig'){if(count)count.textContent='Resmi form';if(out)renderTeblig(out);return;}const q=norm(query.trim()),list=docs().filter(d=>!q||norm([d.baslik,d.aciklama,d.kategori,d.dosyaAdi,d.olusturanAdi].filter(Boolean).join(' ')).includes(q));if(count)count.textContent=`${list.length} kayıt`;if(out)out.innerHTML=list.length?list.map(d=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(d.baslik||d.dosyaAdi||'Doküman')}</strong><div class="ka-muted">${esc([d.kategori,d.olusturanAdi,d.gorunurluk==='herkes'?'Herkese açık':'Kişisel'].filter(Boolean).join(' · '))}</div></div>${d.dosyaUrl?`<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-document-open="${esc(d.id)}" data-ka-permission="documents.view" data-ka-min-level="preview">Aç</button>`:''}</div></article>`).join(''):'<div class="ka-empty">Doküman bulunamadı.</div>';bindDocumentButtons(list);PermissionService?.applyModule?.('documents')}
function bindDocumentButtons(list){document.querySelectorAll('[data-document-open]').forEach(b=>b.onclick=()=>{const d=list.find(x=>x.id===b.dataset.documentOpen);if(d)openDocument(d)});}
function bind(){const s=document.getElementById('documentsSearch');if(s)s.oninput=()=>{query=s.value;render()};document.querySelector('[data-document-form="teblig"]')?.addEventListener('click',openTeblig)}function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.dokumanlar','data.dokumanlarAcik','data.dokumanlarBenim','data.ogretmenler','data.okulBilgileri'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}function unmount(){mounted=false;mode='list';tebligState=null;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}window.DocumentsModule={mount,unmount,render,prepareLocal,openDocument,ensureViewer,openTeblig};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='documents')mount()});
})();