/* Koruk Asistan — Mevzuat Asistanı V2 motoru
 * Firestore kullanmaz. Tek merkezi local-first IndexedDB/AppStore sözleşmesini kullanır.
 * Eski okulMevzuatDB yalnız mevcutsa bir defa okunur, merkezi cache'e taşınır ve silinir.
 */
(function(global){
'use strict';
if(global.LegislationEngine)return;
const API='https://koruk-mevzuat-asistan.sedonet23.workers.dev/';
const RECORD_TYPE='mevzuatKayitlar',CHUNK_TYPE='mevzuatChunklar';
const LEGACY_DB='okulMevzuatDB',LEGACY_VERSION=1,LEGACY_META='legislationLegacyMigration';
let readyPromise=null;
const STOP=new Set(['ve','veya','ile','bir','bu','da','de','ki','için','olan','olarak','ise','gibi','çok','daha','en','ya','ancak','fakat','madde','fıkra','bent','göre','şu','o','her']);
const EKLER=['lerinden','larından','lerinin','larının','lerine','larına','lerini','larını','ndeki','ndaki','leri','ları','lere','lara','lerde','larda','lerden','lardan','lerin','ların','nden','ndan','sında','sinde','sunda','sünde','sına','sine','suna','süne','sinin','sının','sunun','sünün','ecek','acak','yordu','miş','mış','muş','müş','yor','dir','dır','dur','dür','siz','sız','suz','süz','nin','nın','nun','nün','nde','nda','den','dan','te','ta','de','da','li','lı','lu','lü','ci','cı','cu','cü','çi','çı','çu','çü','ler','lar','nı','ni','nu','nü','ın','in','un','ün','ı','i','u','ü','e','a'].sort((a,b)=>b.length-a.length);
const uid=()=>global.KorukLocalFirst?.uid?.()||global.AppStore?.get?.('session.user')?.uid||'';
const rows=type=>{const v=global.AppStore?.data?.(type);return Array.isArray(v)?v:[]};
function mergeById(a,b){const out=new Map();for(const [prefix,list] of [['a',a],['b',b]])(Array.isArray(list)?list:[]).forEach((x,i)=>out.set(x?.id||`${prefix}:${i}`,x));return [...out.values()];}
async function persist(type,list){if(!global.DeviceData?.persist)throw new Error('DeviceData hazır değil.');return global.DeviceData.persist(type,Array.isArray(list)?list:[]);}
function idbRequest(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB isteği başarısız.'));});}
async function legacyExists(){if(typeof indexedDB?.databases!=='function')return false;try{return (await indexedDB.databases()).some(x=>x?.name===LEGACY_DB)}catch(_){return false}}
async function openLegacy(){if(!(await legacyExists()))return null;return new Promise((resolve,reject)=>{const req=indexedDB.open(LEGACY_DB,LEGACY_VERSION);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Legacy mevzuat veritabanı açılamadı.'));req.onupgradeneeded=()=>{try{req.transaction?.abort?.()}catch(_){}};});}
async function legacyAll(db,store){if(!db?.objectStoreNames?.contains(store))return[];const t=db.transaction(store,'readonly'),s=t.objectStore(store);return idbRequest(s.getAll());}
async function deleteLegacy(){if(!(await legacyExists()))return true;return new Promise(resolve=>{const req=indexedDB.deleteDatabase(LEGACY_DB);req.onsuccess=()=>resolve(true);req.onerror=()=>resolve(false);req.onblocked=()=>resolve(false);});}
async function migrateLegacy(){const u=uid();if(!u)return false;const meta=await global.KorukLocalFirst?.meta?.(u,LEGACY_META);if(meta?.copied===true){if(meta.deleted!==true){const deleted=await deleteLegacy();if(deleted)await global.KorukLocalFirst.meta(u,LEGACY_META,{...meta,deleted:true,deletedAt:Date.now()});}return true;}if(!(await legacyExists())){await global.KorukLocalFirst?.meta?.(u,LEGACY_META,{copied:true,deleted:true,noLegacy:true,completedAt:Date.now()});return true;}let db=null;try{db=await openLegacy();if(!db)return false;const[oldRecords,oldChunks]=await Promise.all([legacyAll(db,'kayitlar'),legacyAll(db,'chunklar')]);await persist(RECORD_TYPE,mergeById(rows(RECORD_TYPE),oldRecords));await persist(CHUNK_TYPE,mergeById(rows(CHUNK_TYPE),oldChunks));const copied={copied:true,deleted:false,recordCount:oldRecords.length,chunkCount:oldChunks.length,copiedAt:Date.now()};await global.KorukLocalFirst?.meta?.(u,LEGACY_META,copied);db.close();db=null;const deleted=await deleteLegacy();await global.KorukLocalFirst?.meta?.(u,LEGACY_META,{...copied,deleted,deletedAt:deleted?Date.now():null});return true;}finally{try{db?.close?.()}catch(_){}}}
async function ensureReady(){if(readyPromise)return readyPromise;readyPromise=(async()=>{if(!global.AppStore||!global.DeviceData||!global.SyncEngine||!global.KorukLocalFirst)throw new Error('Local-first çekirdek hazır değil.');await global.SyncEngine.localHydrate([RECORD_TYPE,CHUNK_TYPE]);await migrateLegacy();return true;})().catch(e=>{readyPromise=null;throw e});return readyPromise;}
function keywords(text){return[...new Set(String(text||'').toLocaleLowerCase('tr').replace(/[^\wçğıöşü\s]/gi,' ').split(/\s+/).filter(k=>k.length>2&&!STOP.has(k)))].slice(0,60);}
function stem(word){let k=word;for(const suffix of EKLER){if(k.length-suffix.length>=3&&k.endsWith(suffix)){k=k.slice(0,k.length-suffix.length);break;}}return k.length>6?k.slice(0,6):k;}
function split(text){const clean=String(text||'').replace(/\r\n/g,'\n').trim();if(!clean)return[];let parts=clean.split(/(?=^\s*MADDE\s+\d+\s*[-–.]|^\s*Madde\s+\d+\s*[-–.])/gim).map(x=>x.trim()).filter(Boolean);if(parts.length<=1)parts=clean.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);if(parts.length<=1&&clean.length>1200){parts=[];for(let i=0;i<clean.length;i+=1000)parts.push(clean.slice(i,i+1000));}if(!parts.length)parts=[clean];return parts.map((text,index)=>{const first=text.split('\n')[0].trim();return{baslik:first.length<=80?first:`Bölüm ${index+1}`,metin:text,anahtarKelimeler:keywords(text)}});}
function makeId(){return'mv_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);}
async function all(type){await ensureReady();return rows(type).slice();}
async function chunksFor(id){return(await all(CHUNK_TYPE)).filter(x=>x.mevzuatId===id);}
async function list(){const items=await all(RECORD_TYPE);return items.sort((a,b)=>String(b.eklenmeTarihi||'').localeCompare(String(a.eklenmeTarihi||'')));}
async function add(input){await ensureReady();const baslik=String(input?.baslik||'').trim(),metin=String(input?.metin||'');if(!baslik||!metin.trim())throw new Error('Başlık ve metin zorunlu.');const parts=split(metin);if(!parts.length)throw new Error('Metinden bölüm çıkarılamadı.');const id=makeId(),row={id,baslik,kaynak:String(input?.kaynak||'').trim(),kategori:String(input?.kategori||'').trim()||'Genel',eklenmeTarihi:new Date().toISOString(),chunkSayisi:parts.length},chunks=parts.map((p,i)=>({id:id+'_c'+i,mevzuatId:id,indeks:i,baslik:p.baslik,metin:p.metin,anahtarKelimeler:p.anahtarKelimeler}));await persist(RECORD_TYPE,[...rows(RECORD_TYPE).filter(x=>x.id!==id),row]);await persist(CHUNK_TYPE,[...rows(CHUNK_TYPE).filter(x=>x.mevzuatId!==id),...chunks]);return row;}
async function remove(id){await ensureReady();await persist(CHUNK_TYPE,rows(CHUNK_TYPE).filter(x=>x.mevzuatId!==id));await persist(RECORD_TYPE,rows(RECORD_TYPE).filter(x=>x.id!==id));return true;}
async function importJson(items){if(!Array.isArray(items))throw new Error('İçe aktarma verisi dizi olmalı.');const current=await list(),sources=new Set(current.map(x=>x.kaynak).filter(Boolean));let eklenen=0,atlanan=0,hatali=0;for(const item of items){try{if(!item?.baslik||!String(item?.metin||'').trim()){hatali++;continue;}if(item.kaynak&&sources.has(item.kaynak)){atlanan++;continue;}await add(item);if(item.kaynak)sources.add(item.kaynak);eklenen++;}catch(_){hatali++;}}return{eklenen,atlanan,hatali};}
async function search(question,count=10){const q=keywords(question);if(!q.length)return[];const stems=[...new Set(q.map(stem))],chunks=await all(CHUNK_TYPE);let scores=chunks.map(chunk=>{const set=new Set((chunk.anahtarKelimeler||[]).map(stem));let score=0;stems.forEach(x=>{if(set.has(x))score++});if(chunk.baslik){const title=keywords(chunk.baslik).map(stem);stems.forEach(x=>{if(title.includes(x))score+=2});}return{chunk,score}}).filter(x=>x.score>0);if(!scores.length){const long=q.filter(x=>x.length>=4);scores=chunks.map(chunk=>{const text=String(chunk.metin||'').toLocaleLowerCase('tr'),title=String(chunk.baslik||'').toLocaleLowerCase('tr');let score=0;long.forEach(x=>{if(text.includes(x))score++;if(title.includes(x))score+=2});return{chunk,score}}).filter(x=>x.score>0);}return scores.sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.chunk);}
async function ask(question){const soru=String(question||'').trim();if(!soru)throw new Error('Soru boş.');const related=await search(soru,10);if(!related.length)return{text:'Eklediğiniz mevzuatlar arasında bu soruyla ilgili bir bölüm bulunamadı.',sources:[]};const items=await list(),byId=new Map(items.map(x=>[x.id,x]));const context=related.map(c=>`[Kaynak: ${byId.get(c.mevzuatId)?.baslik||'Bilinmeyen'} — ${c.baslik}]\n${c.metin}`).join('\n\n---\n\n');const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',text:soru}],context})});const data=await res.json();if(!res.ok||data.error)throw new Error(data.error||'Mevzuat asistanı yanıt vermedi.');return{text:data.text||'(boş yanıt)',sources:related.map(c=>({mevzuatId:c.mevzuatId,baslik:c.baslik}))};}
async function backup(){await ensureReady();return{kayitlar:rows(RECORD_TYPE).slice(),chunklar:rows(CHUNK_TYPE).slice()};}
async function restore(data){await ensureReady();const records=Array.isArray(data?.kayitlar)?data.kayitlar:[],chunks=Array.isArray(data?.chunklar)?data.chunklar:[];await persist(RECORD_TYPE,mergeById(rows(RECORD_TYPE),records));await persist(CHUNK_TYPE,mergeById(rows(CHUNK_TYPE),chunks));return list();}
global.LegislationEngine={list,add,remove,importJson,search,ask,backup,restore,split,keywords,stem,ensureReady,recordType:RECORD_TYPE,chunkType:CHUNK_TYPE,legacyDbName:LEGACY_DB};
global.addEventListener('koruk:app-ready',()=>{ensureReady().catch(e=>console.warn('[Legislation/migrate]',e?.message||e))});
})(window);