/* Koruk Asistan — Mevzuat Asistanı V2 motoru
 * Firestore kullanmaz. Mevcut okulMevzuatDB / kayitlar / chunklar veri modeli korunur.
 * UI bağımsızdır; Android, iOS Safari/PWA ve web aynı motoru kullanır.
 */
(function(global){
'use strict';
if(global.LegislationEngine)return;
const API='https://koruk-mevzuat-asistan.sedonet23.workers.dev/';
const DB_NAME='okulMevzuatDB',DB_VERSION=1;
let handle=null;
const STOP=new Set(['ve','veya','ile','bir','bu','da','de','ki','için','olan','olarak','ise','gibi','çok','daha','en','ya','ancak','fakat','madde','fıkra','bent','göre','şu','o','her']);
const EKLER=['lerinden','larından','lerinin','larının','lerine','larına','lerini','larını','ndeki','ndaki','leri','ları','lere','lara','lerde','larda','lerden','lardan','lerin','ların','nden','ndan','sında','sinde','sunda','sünde','sına','sine','suna','süne','sinin','sının','sunun','sünün','ecek','acak','yordu','miş','mış','muş','müş','yor','dir','dır','dur','dür','siz','sız','suz','süz','nin','nın','nun','nün','nde','nda','den','dan','te','ta','de','da','li','lı','lu','lü','ci','cı','cu','cü','çi','çı','çu','çü','ler','lar','nı','ni','nu','nü','ın','in','un','ün','ı','i','u','ü','e','a'].sort((a,b)=>b.length-a.length);
function db(){return new Promise((resolve,reject)=>{if(handle)return resolve(handle);const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('kayitlar'))d.createObjectStore('kayitlar',{keyPath:'id'});if(!d.objectStoreNames.contains('chunklar')){const s=d.createObjectStore('chunklar',{keyPath:'id'});s.createIndex('mevzuatId','mevzuatId',{unique:false});}};req.onsuccess=e=>{handle=e.target.result;resolve(handle)};req.onerror=e=>reject(e.target.error);});}
function tx(store,mode,fn){return db().then(d=>new Promise((resolve,reject)=>{const t=d.transaction(store,mode),s=t.objectStore(store),value=fn(s);t.oncomplete=()=>resolve(value);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('IndexedDB işlemi iptal edildi.'));}));}
function all(store){return db().then(d=>new Promise((resolve,reject)=>{const r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);}));}
function chunksFor(id){return db().then(d=>new Promise((resolve,reject)=>{const r=d.transaction('chunklar','readonly').objectStore('chunklar').index('mevzuatId').getAll(IDBKeyRange.only(id));r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);}));}
function keywords(text){return[...new Set(String(text||'').toLocaleLowerCase('tr').replace(/[^\wçğıöşü\s]/gi,' ').split(/\s+/).filter(k=>k.length>2&&!STOP.has(k)))].slice(0,60);}
function stem(word){let k=word;for(const suffix of EKLER){if(k.length-suffix.length>=3&&k.endsWith(suffix)){k=k.slice(0,k.length-suffix.length);break;}}return k.length>6?k.slice(0,6):k;}
function split(text){const clean=String(text||'').replace(/\r\n/g,'\n').trim();if(!clean)return[];let parts=clean.split(/(?=^\s*MADDE\s+\d+\s*[-–.]|^\s*Madde\s+\d+\s*[-–.])/gim).map(x=>x.trim()).filter(Boolean);if(parts.length<=1)parts=clean.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);if(parts.length<=1&&clean.length>1200){parts=[];for(let i=0;i<clean.length;i+=1000)parts.push(clean.slice(i,i+1000));}if(!parts.length)parts=[clean];return parts.map((text,index)=>{const first=text.split('\n')[0].trim();return{baslik:first.length<=80?first:`Bölüm ${index+1}`,metin:text,anahtarKelimeler:keywords(text)}});}
function makeId(){return'mv_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);}
async function list(){const rows=await all('kayitlar');return rows.sort((a,b)=>String(b.eklenmeTarihi||'').localeCompare(String(a.eklenmeTarihi||'')));}
async function add(input){const baslik=String(input?.baslik||'').trim(),metin=String(input?.metin||'');if(!baslik||!metin.trim())throw new Error('Başlık ve metin zorunlu.');const parts=split(metin);if(!parts.length)throw new Error('Metinden bölüm çıkarılamadı.');const id=makeId(),row={id,baslik,kaynak:String(input?.kaynak||'').trim(),kategori:String(input?.kategori||'').trim()||'Genel',eklenmeTarihi:new Date().toISOString(),chunkSayisi:parts.length},chunks=parts.map((p,i)=>({id:id+'_c'+i,mevzuatId:id,indeks:i,baslik:p.baslik,metin:p.metin,anahtarKelimeler:p.anahtarKelimeler}));await tx('kayitlar','readwrite',s=>s.put(row));await tx('chunklar','readwrite',s=>chunks.forEach(c=>s.put(c)));return row;}
async function remove(id){const chunks=await chunksFor(id);await tx('chunklar','readwrite',s=>chunks.forEach(c=>s.delete(c.id)));await tx('kayitlar','readwrite',s=>s.delete(id));return true;}
async function importJson(items){if(!Array.isArray(items))throw new Error('İçe aktarma verisi dizi olmalı.');const rows=await list(),sources=new Set(rows.map(x=>x.kaynak).filter(Boolean));let eklenen=0,atlanan=0,hatali=0;for(const item of items){try{if(!item?.baslik||!String(item?.metin||'').trim()){hatali++;continue;}if(item.kaynak&&sources.has(item.kaynak)){atlanan++;continue;}await add(item);if(item.kaynak)sources.add(item.kaynak);eklenen++;}catch(_){hatali++;}}return{eklenen,atlanan,hatali};}
async function search(question,count=10){const q=keywords(question);if(!q.length)return[];const stems=[...new Set(q.map(stem))],chunks=await all('chunklar');let scores=chunks.map(chunk=>{const set=new Set((chunk.anahtarKelimeler||[]).map(stem));let score=0;stems.forEach(x=>{if(set.has(x))score++});if(chunk.baslik){const title=keywords(chunk.baslik).map(stem);stems.forEach(x=>{if(title.includes(x))score+=2});}return{chunk,score}}).filter(x=>x.score>0);if(!scores.length){const long=q.filter(x=>x.length>=4);scores=chunks.map(chunk=>{const text=String(chunk.metin||'').toLocaleLowerCase('tr'),title=String(chunk.baslik||'').toLocaleLowerCase('tr');let score=0;long.forEach(x=>{if(text.includes(x))score++;if(title.includes(x))score+=2});return{chunk,score}}).filter(x=>x.score>0);}return scores.sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.chunk);}
async function ask(question){const soru=String(question||'').trim();if(!soru)throw new Error('Soru boş.');const related=await search(soru,10);if(!related.length)return{text:'Eklediğiniz mevzuatlar arasında bu soruyla ilgili bir bölüm bulunamadı.',sources:[]};const rows=await list(),byId=new Map(rows.map(x=>[x.id,x]));const context=related.map(c=>`[Kaynak: ${byId.get(c.mevzuatId)?.baslik||'Bilinmeyen'} — ${c.baslik}]\n${c.metin}`).join('\n\n---\n\n');const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',text:soru}],context})});const data=await res.json();if(!res.ok||data.error)throw new Error(data.error||'Mevzuat asistanı yanıt vermedi.');return{text:data.text||'(boş yanıt)',sources:related.map(c=>({mevzuatId:c.mevzuatId,baslik:c.baslik}))};}
async function backup(){const[kayitlar,chunklar]=await Promise.all([all('kayitlar'),all('chunklar')]);return{kayitlar,chunklar};}
async function restore(data){const kayitlar=Array.isArray(data?.kayitlar)?data.kayitlar:[],chunklar=Array.isArray(data?.chunklar)?data.chunklar:[];await tx('kayitlar','readwrite',s=>kayitlar.forEach(x=>s.put(x)));await tx('chunklar','readwrite',s=>chunklar.forEach(x=>s.put(x)));return list();}
global.LegislationEngine={list,add,remove,importJson,search,ask,backup,restore,split,keywords,stem,dbName:DB_NAME,dbVersion:DB_VERSION};
})(window);
