/* Koruk Asistan — Mevzuat Asistanı V3 motoru
 * Firestore kullanmaz. Tek merkezi local-first IndexedDB/AppStore sözleşmesini kullanır.
 * Eski okulMevzuatDB yalnız mevcutsa bir defa okunur, merkezi cache'e taşınır ve silinir.
 */
(function(global){
'use strict';
if(global.LegislationEngine)return;
const API='https://koruk-mevzuat-asistan.sedonet23.workers.dev/';
const RECORD_TYPE='mevzuatKayitlar',CHUNK_TYPE='mevzuatChunklar';
const LEGACY_DB='okulMevzuatDB',LEGACY_META='legislationLegacyMigration';
let readyPromise=null;
const STOP=new Set(['ve','veya','ile','bir','bu','da','de','ki','için','olan','olarak','ise','gibi','çok','daha','en','ya','ancak','fakat','madde','fıkra','bent','göre','şu','o','her']);
const EKLER=['lerinden','larından','lerinin','larının','lerine','larına','lerini','larını','ndeki','ndaki','leri','ları','lere','lara','lerde','larda','lerden','lardan','lerin','ların','nden','ndan','sında','sinde','sunda','sünde','sına','sine','suna','süne','sinin','sının','sunun','sünün','ecek','acak','yordu','miş','mış','muş','müş','yor','dir','dır','dur','dür','siz','sız','suz','süz','nin','nın','nun','nün','nde','nda','den','dan','te','ta','de','da','li','lı','lu','lü','ci','cı','cu','cü','çi','çı','çu','çü','ler','lar','nı','ni','nu','nü','ın','in','un','ün','ı','i','u','ü','e','a'].sort((a,b)=>b.length-a.length);
const EXPANSIONS={
  izin:['mazeret','rapor','yıllık','aylıksız','görevli','sağlık'],
  mazeret:['izin','eş','doğum','ölüm','evlilik'],
  rapor:['sağlık','istirahat','izin'],
  nöbet:['ek ders','görev','ücret','fiilen','öğretmen'],
  ücret:['ek ders','ödeme','görev','fiilen'],
  ek:['ders','ücret','ödeme'],
  disiplin:['ceza','soruşturma','uyarma','kınama','aylıktan','kademe'],
  devamsızlık:['özürlü','özürsüz','öğrenci','izin'],
  görevlendirme:['geçici','görev','öğretmen','yönetici'],
  müdür:['yönetici','okul','görev','yetki','sorumluluk'],
  öğretmen:['görev','sorumluluk','nöbet','izin','ders'],
  servis:['taşıma','araç','öğrenci','şoför','rehber'],
  taşıma:['servis','öğrenci','araç','ihale'],
  yazışma:['resmî','belge','imza','sayı','olur'],
  sınav:['ölçme','değerlendirme','yazılı','ortak'],
  veli:['öğrenci','okul aile','izin'],
  personel:['memur','öğretmen','izin','disiplin']
};
const OFFICIAL_HOSTS=['mevzuat.gov.tr','resmigazete.gov.tr','meb.gov.tr','www.meb.gov.tr','orgm.meb.gov.tr','iegm.meb.gov.tr','ms.hmb.gov.tr','csb.gov.tr','csgb.gov.tr','aile.gov.tr'];
const uid=()=>global.KorukLocalFirst?.uid?.()||global.AppStore?.get?.('session.user')?.uid||'';
const rows=type=>{const v=global.AppStore?.data?.(type);return Array.isArray(v)?v:[]};
function mergeById(a,b){const out=new Map();for(const [prefix,list] of [['a',a],['b',b]])(Array.isArray(list)?list:[]).forEach((x,i)=>out.set(x?.id||`${prefix}:${i}`,x));return [...out.values()];}
async function persist(type,list){if(!global.DeviceData?.persist)throw new Error('DeviceData hazır değil.');return global.DeviceData.persist(type,Array.isArray(list)?list:[]);}
function idbRequest(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB isteği başarısız.'));});}
async function legacyExists(){if(typeof indexedDB==='undefined')return false;if(typeof indexedDB.databases==='function'){try{return (await indexedDB.databases()).some(x=>x?.name===LEGACY_DB)}catch(_){}}return new Promise(resolve=>{let upgrade=false,settled=false;const done=v=>{if(settled)return;settled=true;resolve(v)};let req;try{req=indexedDB.open(LEGACY_DB)}catch(_){done(false);return}req.onupgradeneeded=()=>{upgrade=true;try{req.transaction?.abort?.()}catch(_){}};req.onsuccess=()=>{try{req.result?.close?.()}catch(_){}done(!upgrade)};req.onerror=()=>done(false);req.onblocked=()=>done(false);});}
async function openLegacy(){if(!(await legacyExists()))return null;return new Promise((resolve,reject)=>{const req=indexedDB.open(LEGACY_DB);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Legacy mevzuat veritabanı açılamadı.'));req.onupgradeneeded=()=>{try{req.transaction?.abort?.()}catch(_){}};});}
async function legacyAll(db,store){if(!db?.objectStoreNames?.contains(store))return[];const t=db.transaction(store,'readonly'),s=t.objectStore(store);return idbRequest(s.getAll());}
async function deleteLegacy(){if(!(await legacyExists()))return true;return new Promise(resolve=>{const req=indexedDB.deleteDatabase(LEGACY_DB);req.onsuccess=()=>resolve(true);req.onerror=()=>resolve(false);req.onblocked=()=>resolve(false);});}
async function migrateLegacy(){const u=uid();if(!u)return false;const meta=await global.KorukLocalFirst?.meta?.(u,LEGACY_META);if(meta?.copied===true){if(meta.deleted!==true){const deleted=await deleteLegacy();if(deleted)await global.KorukLocalFirst.meta(u,LEGACY_META,{...meta,deleted:true,deletedAt:Date.now()});}return true;}if(!(await legacyExists())){await global.KorukLocalFirst?.meta?.(u,LEGACY_META,{copied:true,deleted:true,noLegacy:true,completedAt:Date.now()});return true;}let db=null;try{db=await openLegacy();if(!db)return false;const[oldRecords,oldChunks]=await Promise.all([legacyAll(db,'kayitlar'),legacyAll(db,'chunklar')]);await persist(RECORD_TYPE,mergeById(rows(RECORD_TYPE),oldRecords));await persist(CHUNK_TYPE,mergeById(rows(CHUNK_TYPE),oldChunks));const copied={copied:true,deleted:false,recordCount:oldRecords.length,chunkCount:oldChunks.length,copiedAt:Date.now()};await global.KorukLocalFirst?.meta?.(u,LEGACY_META,copied);db.close();db=null;const deleted=await deleteLegacy();await global.KorukLocalFirst?.meta?.(u,LEGACY_META,{...copied,deleted,deletedAt:deleted?Date.now():null});return true;}finally{try{db?.close?.()}catch(_){}}}
async function ensureReady(){if(readyPromise)return readyPromise;readyPromise=(async()=>{if(!global.AppStore||!global.DeviceData||!global.SyncEngine||!global.KorukLocalFirst)throw new Error('Local-first çekirdek hazır değil.');await global.SyncEngine.localHydrate([RECORD_TYPE,CHUNK_TYPE]);await migrateLegacy();return true;})().catch(e=>{readyPromise=null;throw e});return readyPromise;}
function keywords(text){return[...new Set(String(text||'').toLocaleLowerCase('tr').replace(/[^\wçğıöşü\s]/gi,' ').split(/\s+/).filter(k=>k.length>2&&!STOP.has(k)))].slice(0,80);}
function stem(word){let k=String(word||'').toLocaleLowerCase('tr');for(const suffix of EKLER){if(k.length-suffix.length>=3&&k.endsWith(suffix)){k=k.slice(0,k.length-suffix.length);break;}}return k.length>7?k.slice(0,7):k;}
function expandTerms(question){const base=keywords(question),extra=[];for(const term of base){const s=stem(term);for(const [key,vals] of Object.entries(EXPANSIONS)){if(stem(key)===s||term.includes(key)||key.includes(term))extra.push(...vals);}}return[...new Set([...base,...extra.flatMap(keywords)])].slice(0,100);}
function split(text){const clean=String(text||'').replace(/\r\n/g,'\n').trim();if(!clean)return[];let parts=clean.split(/(?=^\s*(?:GEÇİCİ\s+MADDE|EK\s+MADDE|MADDE|Geçici\s+Madde|Ek\s+Madde|Madde)\s+\d+\s*[-–.]?)/gim).map(x=>x.trim()).filter(Boolean);if(parts.length<=1)parts=clean.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);if(parts.length<=1&&clean.length>1400){parts=[];for(let i=0;i<clean.length;i+=1100)parts.push(clean.slice(i,i+1250));}if(!parts.length)parts=[clean];return parts.map((text,index)=>{const first=text.split('\n')[0].trim();const maddeNo=(first.match(/(?:GEÇİCİ\s+MADDE|EK\s+MADDE|MADDE|Geçici\s+Madde|Ek\s+Madde|Madde)\s+(\d+)/i)||[])[1]||'';return{baslik:first.length<=120?first:`Bölüm ${index+1}`,maddeNo,metin:text,anahtarKelimeler:keywords(text)}});}
function makeId(){return'mv_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);}
async function all(type){await ensureReady();return rows(type).slice();}
async function chunksFor(id){return(await all(CHUNK_TYPE)).filter(x=>x.mevzuatId===id);}
async function list(){const items=await all(RECORD_TYPE);return items.sort((a,b)=>String(b.eklenmeTarihi||'').localeCompare(String(a.eklenmeTarihi||'')));}
async function add(input){await ensureReady();const baslik=String(input?.baslik||'').trim(),metin=String(input?.metin||'');if(!baslik||!metin.trim())throw new Error('Başlık ve metin zorunlu.');const parts=split(metin);if(!parts.length)throw new Error('Metinden bölüm çıkarılamadı.');const id=makeId(),row={id,baslik,kaynak:String(input?.kaynak||'').trim(),kategori:String(input?.kategori||'').trim()||'Genel',eklenmeTarihi:new Date().toISOString(),chunkSayisi:parts.length},chunks=parts.map((p,i)=>({id:id+'_c'+i,mevzuatId:id,indeks:i,baslik:p.baslik,maddeNo:p.maddeNo||'',metin:p.metin,anahtarKelimeler:p.anahtarKelimeler}));await persist(RECORD_TYPE,[...rows(RECORD_TYPE).filter(x=>x.id!==id),row]);await persist(CHUNK_TYPE,[...rows(CHUNK_TYPE).filter(x=>x.mevzuatId!==id),...chunks]);return row;}
async function remove(id){await ensureReady();await persist(CHUNK_TYPE,rows(CHUNK_TYPE).filter(x=>x.mevzuatId!==id));await persist(RECORD_TYPE,rows(RECORD_TYPE).filter(x=>x.id!==id));return true;}
async function importJson(items){if(!Array.isArray(items))throw new Error('İçe aktarma verisi dizi olmalı.');const current=await list(),seen=new Set(current.map(x=>canonicalKey(x)).filter(Boolean));let eklenen=0,atlanan=0,hatali=0;for(const item of items){try{if(!item?.baslik||!String(item?.metin||'').trim()){hatali++;continue;}const key=canonicalKey(item);if(key&&seen.has(key)){atlanan++;continue;}await add(item);if(key)seen.add(key);eklenen++;}catch(_){hatali++;}}return{eklenen,atlanan,hatali};}
function sourceHost(value){try{return new URL(String(value||'').trim()).hostname.toLocaleLowerCase('tr')}catch(_){return String(value||'').toLocaleLowerCase('tr')}}
function officialScore(value){const host=sourceHost(value);if(!host)return 0;if(host.includes('mevzuat.gov.tr'))return 8;if(host.includes('resmigazete.gov.tr'))return 8;if(host.endsWith('.meb.gov.tr')||host==='meb.gov.tr'||host==='www.meb.gov.tr')return 7;if(OFFICIAL_HOSTS.some(x=>host.includes(x)))return 5;if(host.endsWith('.gov.tr'))return 4;return 0;}
function canonicalKey(row){const title=String(row?.baslik||'').toLocaleLowerCase('tr').replace(/\b(\d+)\s*sayılı\b/g,'$1').replace(/[^a-z0-9çğıöşü]+/gi,' ').trim();if(!title)return'';return title.replace(/\s+/g,' ').slice(0,140);}
function phraseScore(text,question){const q=String(question||'').toLocaleLowerCase('tr').trim(),t=String(text||'').toLocaleLowerCase('tr');if(!q||q.length<5)return 0;if(t.includes(q))return 9;const phrase=keywords(question).slice(0,4).join(' ');return phrase&&phrase.length>7&&t.includes(phrase)?5:0;}
async function searchDetailed(question,count=12){const terms=expandTerms(question),stems=[...new Set(terms.map(stem).filter(Boolean))];if(!stems.length)return[];const [chunks,items]=await Promise.all([all(CHUNK_TYPE),list()]),byId=new Map(items.map(x=>[x.id,x]));const scored=chunks.map(chunk=>{const record=byId.get(chunk.mevzuatId)||{};const keySet=new Set((chunk.anahtarKelimeler||keywords(chunk.metin)).map(stem));const titleTerms=keywords(`${chunk.baslik||''} ${record.baslik||''}`).map(stem);let score=0,matched=0;for(const s of stems){if(keySet.has(s)){score+=2;matched++;}if(titleTerms.includes(s))score+=4;}score+=phraseScore(chunk.metin,question)+phraseScore(`${record.baslik||''} ${chunk.baslik||''}`,question);score+=officialScore(record.kaynak);if(chunk.maddeNo&&String(question).match(new RegExp(`(?:madde\\s*)?${chunk.maddeNo}\\b`,'i')))score+=8;const coverage=matched/Math.max(1,Math.min(stems.length,10));score+=coverage*6;return{chunk,record,score,matched,coverage};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.coverage-a.coverage);
  const picked=[],seenChunk=new Set(),perLaw=new Map();for(const item of scored){if(picked.length>=count)break;const lawCount=perLaw.get(item.chunk.mevzuatId)||0;if(lawCount>=4&&picked.length>=6)continue;picked.push(item);seenChunk.add(item.chunk.id);perLaw.set(item.chunk.mevzuatId,lawCount+1);}
  const chunkMap=new Map(chunks.map(x=>[`${x.mevzuatId}:${x.indeks}`,x]));for(const base of picked.slice(0,5)){for(const idx of [Number(base.chunk.indeks)-1,Number(base.chunk.indeks)+1]){if(picked.length>=count+4)break;const n=chunkMap.get(`${base.chunk.mevzuatId}:${idx}`);if(!n||seenChunk.has(n.id))continue;picked.push({chunk:n,record:base.record,score:Math.max(1,base.score-5),matched:0,coverage:0,neighbor:true});seenChunk.add(n.id);}}
  return picked.sort((a,b)=>b.score-a.score).slice(0,count).map(x=>({...x.chunk,_score:Number(x.score.toFixed(2)),_record:x.record,_neighbor:!!x.neighbor}));}
async function search(question,count=10){return(await searchDetailed(question,count)).map(({_record,_score,_neighbor,...chunk})=>chunk);}
function answerInstructions(){return[
  'ROL: Türkiye’de MEB okul yöneticilerine yardımcı olan kıdemli bir mevzuat danışmanısın.',
  'AMAÇ: Kullanıcıya kısa, yüzeysel cevap verme. Açık, ayrıntılı, uygulanabilir ve anlaşılır cevap üret.',
  'ÖNCELİK: Resmî ve güncel mevzuat. mevzuat.gov.tr, Resmî Gazete ve MEB kaynaklarını diğer kaynaklardan üstün tut.',
  'CEVAP YAPISI: 1) Sonuç 2) Mevzuat dayanağı 3) Ayrıntılı açıklama 4) Okul yönetiminde uygulama 5) İstisnalar/özel durumlar 6) Kaynaklar.',
  'DOĞRULUK: Kaynakta olmayan madde numarası, tarih veya hüküm uydurma. Emin değilsen bunu açıkça belirt.',
  'YETERSİZ BAĞLAM: Doğrudan hüküm yoksa hemen “bilmiyorum” deme; ilişkili hükümleri değerlendir ve hangi ek bilginin gerektiğini belirt.',
  'GÜNCELLİK: Worker internet araması destekliyorsa soruyu resmî web kaynaklarında güncellik açısından doğrula; güncel web sonucu yerel arşivle çelişirse bunu açıkça belirt.',
  'UZUNLUK: Varsayılan cevap ayrıntılı olsun; kullanıcı özellikle kısa istemedikçe birkaç cümleyle bitirme.'
].join('\n');}
function sanitizeHistory(history){return(Array.isArray(history)?history:[]).slice(-8).map(x=>({role:x.role==='model'?'assistant':'user',text:String(x.text||'').slice(0,2500)})).filter(x=>x.text.trim());}
async function ask(question,history=[]){const soru=String(question||'').trim();if(!soru)throw new Error('Soru boş.');let related=await searchDetailed(soru,14);if(!related.length){const fallback=keywords(soru).slice(0,6).join(' ');if(fallback&&fallback!==soru)related=await searchDetailed(fallback,14);}const items=await list(),byId=new Map(items.map(x=>[x.id,x]));const contextParts=related.map((c,i)=>{const r=c._record||byId.get(c.mevzuatId)||{};return`[Yerel Kaynak ${i+1}: ${r.baslik||'Bilinmeyen'}${c.maddeNo?` — Madde ${c.maddeNo}`:''}${c.baslik?` — ${c.baslik}`:''}]\nKaynak URL: ${r.kaynak||'belirtilmemiş'}\nKaynak güven puanı: ${officialScore(r.kaynak)}\n${c.metin}`;});const context=[answerInstructions(),'\nYEREL MEVZUAT BAĞLAMI:',contextParts.length?contextParts.join('\n\n---\n\n'):'Yerel arşivde doğrudan eşleşen bölüm bulunamadı. Varsa resmî internet kaynaklarında güncel doğrulama yap ve bunu açıkça belirt.'].join('\n\n');const messages=[...sanitizeHistory(history),{role:'user',text:soru}];const body={messages,context,mode:'hybrid',responseStyle:'detailed',webSearch:{enabled:true,officialOnly:true,domains:['mevzuat.gov.tr','resmigazete.gov.tr','meb.gov.tr'],freshness:'latest'},retrieval:{localMatches:related.length,requested:14}};const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok||data.error)throw new Error(data.error||'Mevzuat asistanı yanıt vermedi.');return{text:data.text||'(boş yanıt)',sources:related.map(c=>{const r=c._record||byId.get(c.mevzuatId)||{};return{mevzuatId:c.mevzuatId,baslik:r.baslik||c.baslik,maddeNo:c.maddeNo||'',bolum:c.baslik||'',kaynak:r.kaynak||'',resmi:officialScore(r.kaynak)>0,score:c._score||0}}),webSources:Array.isArray(data.sources)?data.sources:[],retrieval:{localMatches:related.length}};}
async function backup(){await ensureReady();return{kayitlar:rows(RECORD_TYPE).slice(),chunklar:rows(CHUNK_TYPE).slice()};}
async function restore(data){await ensureReady();const records=Array.isArray(data?.kayitlar)?data.kayitlar:[],chunks=Array.isArray(data?.chunklar)?data.chunklar:[];await persist(RECORD_TYPE,mergeById(rows(RECORD_TYPE),records));await persist(CHUNK_TYPE,mergeById(rows(CHUNK_TYPE),chunks));return list();}
global.LegislationEngine={list,add,remove,importJson,search,searchDetailed,ask,backup,restore,split,keywords,stem,expandTerms,officialScore,ensureReady,recordType:RECORD_TYPE,chunkType:CHUNK_TYPE,legacyDbName:LEGACY_DB};
global.addEventListener('koruk:app-ready',()=>{ensureReady().catch(e=>console.warn('[Legislation/migrate]',e?.message||e))});
})(window);