/* Koruk Asistan — Mevzuat Asistanı V2 presentation */
(function(global){
'use strict';
if(global.LegislationModule)return;
let rows=[],history=[],loading=false,view='sources';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('tr-TR')};
const canEdit=()=>global.PermissionService?.can?.('documents.edit','edit')!==false;
function requireEdit(){if(canEdit())return true;global.toast?.('Mevzuat düzenleme yetkiniz yok.');return false;}
function engine(){if(!global.LegislationEngine)throw new Error('Mevzuat motoru hazır değil.');return global.LegislationEngine;}
function shell(){return `<section class="ka-stack" data-legislation-v2><div class="ka-row ka-row--between"><div><h2>Mevzuat Asistanı</h2><p class="ka-muted">Kaynaklar cihazda tutulur; yalnız soruyla ilgili bölümler AI servisine gönderilir.</p></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-legislation-back>Geri</button></div><div class="ka-tabs"><button class="ka-tab" type="button" data-legislation-view="sources">Kaynaklar</button><button class="ka-tab" type="button" data-legislation-view="chat">Soru Sor</button></div><div id="legislationContent"></div></section>`}
function sourceView(){return `<section class="ka-stack"><div class="ka-row" data-ka-permission="documents.edit" data-ka-min-level="edit"><button class="ka-btn" type="button" data-legislation-add data-ka-write="documents.edit">Yeni Mevzuat</button><label class="ka-btn ka-btn--secondary" for="legislationImport">JSON İçe Aktar</label><input id="legislationImport" class="ka-hidden" type="file" accept="application/json,.json"></div><div id="legislationAddForm" class="ka-hidden"></div><div id="legislationList" class="ka-stack"></div></section>`}
function addForm(){return `<article class="ka-card"><div class="ka-card__header"><h3>Yeni Mevzuat</h3></div><div class="ka-card__body ka-stack"><label class="ka-field"><span class="ka-field__label">Başlık</span><input id="legislationTitle" placeholder="Örn. Personel İzin Yönergesi"></label><label class="ka-field"><span class="ka-field__label">Kaynak</span><input id="legislationSource" placeholder="mevzuat.gov.tr / Resmî Gazete"></label><label class="ka-field"><span class="ka-field__label">Kategori</span><input id="legislationCategory" value="Genel"></label><label class="ka-field"><span class="ka-field__label">Mevzuat Metni</span><textarea id="legislationText" rows="12" placeholder="Metni buraya yapıştırın"></textarea></label><div class="ka-row"><button class="ka-btn" type="button" data-legislation-save data-ka-write="documents.edit">Bölerek Kaydet</button><button class="ka-btn ka-btn--secondary" type="button" data-legislation-cancel>Vazgeç</button></div></div></article>`}
function chatView(){return `<section class="ka-stack"><div id="legislationMessages" class="ka-stack"></div><label class="ka-field"><span class="ka-field__label">Mevzuat sorunuz</span><textarea id="legislationQuestion" rows="4" placeholder="Örn. Mazeret izni hangi durumlarda verilir?"></textarea></label><div class="ka-row"><button class="ka-btn" type="button" data-legislation-send>Sor</button><button class="ka-btn ka-btn--secondary" type="button" data-legislation-clear>Sohbeti Temizle</button></div></section>`}
async function refresh(){rows=await engine().list();renderList();}
function renderList(){const host=document.getElementById('legislationList');if(!host)return;host.innerHTML=rows.length?rows.map(r=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(r.baslik)}</strong><div class="ka-muted">${esc(r.kategori||'Genel')} · ${Number(r.chunkSayisi||0)} bölüm${r.kaynak?` · ${esc(r.kaynak)}`:''}${r.eklenmeTarihi?` · ${date(r.eklenmeTarihi)}`:''}</div></div><button class="ka-btn ka-btn--danger ka-btn--sm" type="button" data-legislation-delete="${esc(r.id)}" data-ka-permission="documents.edit" data-ka-min-level="edit" data-ka-write="documents.edit">Sil</button></div></article>`).join(''):'<div class="ka-empty">Henüz mevzuat eklenmedi.</div>';host.querySelectorAll('[data-legislation-delete]').forEach(b=>b.onclick=async()=>{if(!requireEdit())return;if(!global.confirm?.('Bu mevzuatı ve tüm bölümlerini silmek istiyor musunuz?'))return;try{await engine().remove(b.dataset.legislationDelete);global.toast?.('Mevzuat silindi.');await refresh();}catch(e){global.toast?.('Silinemedi: '+(e?.message||e))}});global.PermissionService?.apply?.(host)}
function renderMessages(){const host=document.getElementById('legislationMessages');if(!host)return;host.innerHTML=history.length?history.map(m=>`<article class="ka-card"><div class="ka-card__body"><strong>${m.role==='user'?'Siz':'Mevzuat Asistanı'}</strong><div>${esc(m.text).replace(/\n/g,'<br>')}</div></div></article>`).join(''):'<div class="ka-empty">Henüz soru sorulmadı.</div>';if(loading)host.insertAdjacentHTML('beforeend','<div class="ka-muted">Mevzuat kaynakları cihazda taranıyor…</div>')}
function bindSources(){document.querySelector('[data-legislation-add]')?.addEventListener('click',()=>{if(!requireEdit())return;const box=document.getElementById('legislationAddForm');box.classList.remove('ka-hidden');box.innerHTML=addForm();box.querySelector('[data-legislation-cancel]').onclick=()=>{box.classList.add('ka-hidden');box.innerHTML=''};box.querySelector('[data-legislation-save]').onclick=save;global.PermissionService?.apply?.(box)});document.getElementById('legislationImport')?.addEventListener('change',importFile);renderList();global.PermissionService?.apply?.(document.querySelector('[data-legislation-v2]'))}
async function save(){if(!requireEdit())return;const baslik=document.getElementById('legislationTitle')?.value||'',kaynak=document.getElementById('legislationSource')?.value||'',kategori=document.getElementById('legislationCategory')?.value||'Genel',metin=document.getElementById('legislationText')?.value||'';try{const row=await engine().add({baslik,kaynak,kategori,metin});global.toast?.(`${row.baslik} cihazda kaydedildi.`);document.getElementById('legislationAddForm')?.classList.add('ka-hidden');await refresh();}catch(e){global.toast?.(e?.message||'Mevzuat kaydedilemedi.')}}
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error||new Error('Dosya okunamadı.'));r.readAsText(file,'utf-8')})}
async function importFile(e){const file=e.target.files?.[0];if(!file)return;if(!requireEdit()){e.target.value='';return;}try{const parsed=JSON.parse(await readFile(file)),result=await engine().importJson(parsed);global.toast?.(`İçe aktarma: ${result.eklenen} eklendi, ${result.atlanan} atlandı, ${result.hatali} hatalı.`);await refresh();}catch(err){global.toast?.('İçe aktarma başarısız: '+(err?.message||err));}finally{e.target.value=''}}
async function send(){const input=document.getElementById('legislationQuestion'),q=(input?.value||'').trim();if(!q||loading)return;history.push({role:'user',text:q});input.value='';loading=true;renderMessages();try{const result=await engine().ask(q);history.push({role:'model',text:result.text||'(boş yanıt)'});}catch(e){history.push({role:'model',text:'Hata: '+(e?.message||e)});}finally{loading=false;renderMessages()}}
function render(){const host=document.getElementById('legislationContent');if(!host)return;document.querySelectorAll('[data-legislation-view]').forEach(b=>b.classList.toggle('active',b.dataset.legislationView===view));host.innerHTML=view==='chat'?chatView():sourceView();if(view==='chat'){renderMessages();host.querySelector('[data-legislation-send]').onclick=send;host.querySelector('[data-legislation-clear]').onclick=()=>{history=[];renderMessages()};host.querySelector('#legislationQuestion').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};}else bindSources();}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;if(global.PermissionService?.can?.('documents.view','preview')===false){global.toast?.('Mevzuatı görüntüleme yetkiniz yok.');return false;}root.innerHTML=shell();root.querySelector('[data-legislation-back]').onclick=()=>global.ShellUI?.routeModule?.('documents',{bottom:'menu'});root.querySelectorAll('[data-legislation-view]').forEach(b=>b.onclick=()=>{view=b.dataset.legislationView;render()});await refresh();render();global.PermissionService?.applyModule?.('documents');return true}
global.LegislationModule={mount,refresh,send};
})(window);
