/* Koruk Asistan — Management tek modül (nöbet rotasyonu hariç)
 * Personel + periyodik işler + izin veri/servis/UI aynı dosyada.
 * Nöbet rotasyon/Excel motoru duty-data.js içinde ayrı tutulur.
 */
(function(global){
'use strict';
if(global.PersonelService&&global.PeriyodikService&&global.OgretmenIzinService)return;
function device(){if(!global.DeviceData)throw new Error('DeviceData hazır değil.');return global.DeviceData;}
const aktif=()=>global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};
const todayISO=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const formatTarih=v=>{if(!v)return'';const d=new Date(String(v).length===10?v+'T00:00:00':v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR')};
const PersonelRepository={personelDinle:cb=>device().listen('personel',cb),personelEkle:v=>device().add('personel',COL.personel,{...v,eklenmeTarihi:new Date().toISOString()}),personelGuncelle:(id,v)=>device().update('personel',COL.personel,id,v),personelSil:id=>device().remove('personel',COL.personel,id),izinleriDinle:cb=>device().listen('personelIzinler',cb),izinEkle:v=>device().add('personelIzinler',COL.personelIzinler,{...v,eklenmeTarihi:new Date().toISOString()}),izinGuncelle:(id,v)=>device().update('personelIzinler',COL.personelIzinler,id,v),izinSil:id=>device().remove('personelIzinler',COL.personelIzinler,id)};
global.PersonelRepository=PersonelRepository;
global.PersonelService={_yetkiKontrol(){if(!duzenleyebilir('personel')){toast?.('Bu işlem için yetkiniz yok.');return false}return true},tcGecerliMi:tc=>!tc||/^\d{11}$/.test(tc),tarihAraligiGecerliMi:(b,s)=>!!(b&&s)&&s>=b,personelKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?PersonelRepository.personelGuncelle(id,v):PersonelRepository.personelEkle(v)},personelSil(id){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return PersonelRepository.personelSil(id)},izinKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?PersonelRepository.izinGuncelle(id,v):PersonelRepository.izinEkle(v)},izinSil(id){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return PersonelRepository.izinSil(id)}};
const PeriyodikRepository={islerDinle:cb=>device().listen('periyodikIsler',cb),isEkle:v=>device().add('periyodikIsler',COL.periyodikIsler,v),isGuncelle:(id,v)=>device().update('periyodikIsler',COL.periyodikIsler,id,v),isSil:id=>device().remove('periyodikIsler',COL.periyodikIsler,id),sabloniDinle:cb=>device().listen('periyodikSablon',rows=>cb((rows.find(x=>x.id==='sablon')||{}).gorevler||[])),sabloniKaydet:g=>device().set('periyodikSablon',COL.periyodikSablon,'sablon',{gorevler:g},{merge:false})};
global.PeriyodikRepository=PeriyodikRepository;
global.PeriyodikService={_yetkiKontrol(){if(!duzenleyebilir('periyodikIsler')){toast?.('Bu işlem için yetkiniz yok.');return false}return true},isKaydet(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?PeriyodikRepository.isGuncelle(id,v):PeriyodikRepository.isEkle({...v,eklenmeTarihi:new Date().toISOString()})},isSil(id){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return PeriyodikRepository.isSil(id)},tamamlandiGuncelle(id,v){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return PeriyodikRepository.isGuncelle(id,{tamamlandi:v})},sabloniKaydet(g){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return PeriyodikRepository.sabloniKaydet(g)},_gunToISO(y,a,g){const son=new Date(y,a+1,0).getDate();return`${y}-${String(a+1).padStart(2,'0')}-${String(Math.min(Math.max(g,1),son)).padStart(2,'0')}`},_grupAnahtari:p=>(p.bitis||p.baslangic)?.slice(0,7)||'9999-99',async buAyinGorevleriniOlustur(sablon,mevcut){if(!this._yetkiKontrol())throw new Error('yetkisiz');const d=new Date(),y=d.getFullYear(),a=d.getMonth();let olusturulan=0,atlanan=0;for(const g of sablon||[]){if(!g.isAdi)continue;const baslangic=this._gunToISO(y,a,g.baslangicGun),bitis=this._gunToISO(y,a,g.bitisGun),ay=bitis.slice(0,7);if((mevcut||[]).some(p=>p.isAdi===g.isAdi&&this._grupAnahtari(p)===ay)){atlanan++;continue}await PeriyodikRepository.isEkle({isAdi:g.isAdi,baslangic,bitis,tamamlandi:false,not:'',bildirimGonderildi:false});olusturulan++}return{olusturulan,atlanan}}};
const OgretmenIzinRepository={izinleriDinle:cb=>device().listen('ogretmenIzinleri',cb),izinEkle:v=>device().add('ogretmenIzinleri',COL.ogretmenIzinleri,{...v,eklenmeTarihi:new Date().toISOString()}),izinGuncelle:(id,v)=>device().update('ogretmenIzinleri',COL.ogretmenIzinleri,id,v),izinSil:id=>device().remove('ogretmenIzinleri',COL.ogretmenIzinleri,id)};
global.OgretmenIzinRepository=OgretmenIzinRepository;
global.OgretmenIzinService={_yetkiKontrol(){if(!duzenleyebilir('ogretmenler')){toast?.('Bu işlem için yetkiniz yok.');return false}return true},gunSayisiHesapla:(b,s)=>Math.round((new Date(s+'T00:00:00')-new Date(b+'T00:00:00'))/86400000)+1,tarihAraligiGecerliMi:(b,s)=>!!(b&&s)&&s>=b,_isoTarihYaz:d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),async izinKaydet(id,eskiHat,adSoyad,v){if(!this._yetkiKontrol())throw new Error('yetkisiz');if(eskiHat)await device().remove('hatirlaticilar',COL.hatirlaticilar,eskiHat);let hatirlaticiId=null;const bitis=new Date(v.bitis+'T00:00:00'),hat=new Date(bitis.getTime()-86400000);if(hat>=new Date(todayISO()+'T00:00:00')){const h=await device().add('hatirlaticilar',COL.hatirlaticilar,{baslik:`🏥 ${adSoyad} — ${v.tur} bitiyor`,tarih:this._isoTarihYaz(hat),saat:'',oncelik:'Orta',aciklama:`${v.tur} kaydı ${formatTarih(v.bitis)} tarihinde sona eriyor.`,tamamlandi:false,bildirimGonderildi:false,sahipUid:aktif().uid||''});hatirlaticiId=h.id}const next={...v,hatirlaticiId};return id?OgretmenIzinRepository.izinGuncelle(id,next):OgretmenIzinRepository.izinEkle(next)},async izinSil(id,h){if(!this._yetkiKontrol())throw new Error('yetkisiz');if(h)await device().remove('hatirlaticilar',COL.hatirlaticilar,h);return OgretmenIzinRepository.izinSil(id)}};
})(window);

(function(){
'use strict';if(window.ManagementModule)return;
let active='staff',query='',mounted=false,unsubs=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const match=vals=>{const q=norm(query.trim());return!q||norm(vals.filter(Boolean).join(' ')).includes(q)};
function date(v){if(!v)return'—';const d=new Date(String(v).length===10?v+'T00:00:00':v);return isNaN(d)?String(v):d.toLocaleDateString('tr-TR')}
async function prepareLocal(){if(!SyncEngine||!COL)return;const defs={personel:COL.personel,personelIzinler:COL.personelIzinler,periyodikIsler:COL.periyodikIsler,periyodikSablon:COL.periyodikSablon,nobetciAmirleri:COL.nobetciAmirleri,resmiTatiller:COL.resmiTatiller,nobetRotasyon:COL.nobetRotasyon};const types=[];Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(100)}}
function shell(){return`<section class="ka-stack" data-management-module><div class="ka-row ka-row--between"><div><h2>Yönetim</h2><p class="ka-muted">Personel, görev, izin ve nöbet bilgileri cihaz verisinden açılır.</p></div><span id="managementCount" class="ka-badge"></span></div><div class="ka-tabs"><button class="ka-tab" data-management-tab="staff" data-ka-permission="management.personnel">Personel</button><button class="ka-tab" data-management-tab="tasks">Periyodik</button><button class="ka-tab" data-management-tab="leaves">İzinler</button><button class="ka-tab" data-management-tab="duty" data-ka-permission="management.duty">Nöbet</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="managementSearch" type="search" placeholder="Personel, görev veya tarih ara…"></label><div id="managementContent" class="ka-stack"></div></section>`}
function staff(){const list=arr('personel').filter(p=>match([p.ad,p.soyad,p.adSoyad,p.gorev,p.unvan,p.telefon])).sort((a,b)=>String(a.adSoyad||a.ad||'').localeCompare(String(b.adSoyad||b.ad||''),'tr'));return{count:list.length,html:list.length?list.map(p=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(p.adSoyad||`${p.ad||''} ${p.soyad||''}`.trim()||'Personel')}</strong><div class="ka-muted">${esc(p.gorev||p.unvan||'Personel')}</div></div>${p.telefon?`<a class="ka-btn ka-btn--ghost ka-btn--sm" href="tel:${esc(p.telefon)}">Ara</a>`:''}</div></article>`).join(''):'<div class="ka-empty">Personel kaydı bulunamadı.</div>'}}
function tasks(){const list=arr('periyodikIsler').filter(p=>match([p.isAdi,p.baslangic,p.bitis,p.not])).sort((a,b)=>(a.bitis||a.baslangic||'').localeCompare(b.bitis||b.baslangic||''));return{count:list.length,html:list.length?list.map(p=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(p.isAdi||'Periyodik görev')}</strong><div class="ka-muted">${esc(date(p.baslangic))} – ${esc(date(p.bitis))}${p.not?' · '+esc(p.not):''}</div></div><span class="ka-badge">${p.tamamlandi?'Tamamlandı':'Bekliyor'}</span></div></article>`).join(''):'<div class="ka-empty">Periyodik görev bulunamadı.</div>'}}
function leaves(){const all=[...arr('ogretmenIzinleri').map(x=>({...x,_type:'Öğretmen'})),...arr('personelIzinler').map(x=>({...x,_type:'Personel'}))].filter(x=>match([x.tur,x.aciklama,x.baslangic,x.bitis,x.ogretmenAdi,x.personelAdi])).sort((a,b)=>(b.baslangic||'').localeCompare(a.baslangic||''));return{count:all.length,html:all.length?all.map(x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(x.ogretmenAdi||x.personelAdi||x.tur||'İzin kaydı')}</strong><div class="ka-muted">${esc(x.tur||x._type)} · ${esc(date(x.baslangic))} – ${esc(date(x.bitis))}</div></div><span class="ka-badge">${esc(x._type)}</span></div></article>`).join(''):'<div class="ka-empty">İzin kaydı bulunamadı.</div>'}}
function duty(){const list=arr('nobetAtamalari').filter(x=>match([x.ogretmenAdSoyad,x.tarih,x.yerAdi])).sort((a,b)=>(a.tarih||'').localeCompare(b.tarih||''));return{count:list.length,html:list.length?list.slice(0,100).map(x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(x.ogretmenAdSoyad||'Nöbet')}</strong><div class="ka-muted">${esc(date(x.tarih))}${x.yerAdi?' · '+esc(x.yerAdi):''}</div></div></div></article>`).join(''):'<div class="ka-empty">Nöbet kaydı bulunamadı.</div>'}}
function render(){if(!mounted)return;document.querySelectorAll('[data-management-tab]').forEach(b=>b.classList.toggle('active',b.dataset.managementTab===active));const r=active==='tasks'?tasks():active==='leaves'?leaves():active==='duty'?duty():staff(),out=document.getElementById('managementContent'),c=document.getElementById('managementCount');if(out)out.innerHTML=r.html;if(c)c.textContent=`${r.count} kayıt`;PermissionService?.apply?.(document.getElementById('v2ModuleRoot')||document)}
function bind(){document.querySelectorAll('[data-management-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.managementTab;render()});const s=document.getElementById('managementSearch');if(s)s.oninput=()=>{query=s.value;render()}}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.personel','data.personelIzinler','data.periyodikIsler','data.ogretmenIzinleri','data.nobetAtamalari','data.nobetciAmirleri','data.resmiTatiller','data.nobetRotasyon'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}
function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.ManagementModule={mount,unmount,render,prepareLocal};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='management')mount()});
})();
