/* Koruk Asistan v2 — Management UI
   Personel + periyodik işler + izinler + nöbet özeti.
   Veri yalnız AppStore/IndexedDB'den okunur; SyncEngine arka planda günceller. */
(function(){
'use strict';if(window.ManagementModule)return;
let active='staff',query='',mounted=false,unsubs=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const match=vals=>{const q=norm(query.trim());return!q||norm(vals.filter(Boolean).join(' ')).includes(q)};
function date(v){if(!v)return'—';const d=new Date(String(v).length===10?v+'T00:00:00':v);return isNaN(d)?String(v):d.toLocaleDateString('tr-TR')}
async function prepareLocal(){if(!window.SyncEngine||!window.COL)return;const defs={personel:COL.personel,personelIzinler:COL.personelIzinler,periyodikIsler:COL.periyodikIsler,periyodikSablon:COL.periyodikSablon,nobetciAmirleri:COL.nobetciAmirleri,resmiTatiller:COL.resmiTatiller,nobetRotasyon:COL.nobetRotasyon};const types=[];Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(100)}}
function shell(){return `<section class="ka-stack" data-management-module><div class="ka-row ka-row--between"><div><h2>Yönetim</h2><p class="ka-muted">Personel, görev, izin ve nöbet bilgileri cihaz verisinden açılır.</p></div><span id="managementCount" class="ka-badge"></span></div><div class="ka-tabs"><button class="ka-tab" data-management-tab="staff">Personel</button><button class="ka-tab" data-management-tab="tasks">Periyodik</button><button class="ka-tab" data-management-tab="leaves">İzinler</button><button class="ka-tab" data-management-tab="duty">Nöbet</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="managementSearch" type="search" placeholder="Personel, görev veya tarih ara…"></label><div id="managementContent" class="ka-stack"></div></section>`}
function staff(){const list=arr('personel').filter(p=>match([p.ad,p.soyad,p.adSoyad,p.gorev,p.unvan,p.telefon])).sort((a,b)=>String(a.adSoyad||a.ad||'').localeCompare(String(b.adSoyad||b.ad||''),'tr'));return{count:list.length,html:list.length?list.map(p=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(p.adSoyad||`${p.ad||''} ${p.soyad||''}`.trim()||'Personel')}</strong><div class="ka-muted">${esc(p.gorev||p.unvan||'Personel')}</div></div>${p.telefon?`<a class="ka-btn ka-btn--ghost ka-btn--sm" href="tel:${esc(p.telefon)}">Ara</a>`:''}</div></article>`).join(''):'<div class="ka-empty">Personel kaydı bulunamadı.</div>'}}
function tasks(){const list=arr('periyodikIsler').filter(p=>match([p.isAdi,p.baslangic,p.bitis,p.not])).sort((a,b)=>(a.bitis||a.baslangic||'').localeCompare(b.bitis||b.baslangic||''));return{count:list.length,html:list.length?list.map(p=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(p.isAdi||'Periyodik görev')}</strong><div class="ka-muted">${esc(date(p.baslangic))} – ${esc(date(p.bitis))}${p.not?' · '+esc(p.not):''}</div></div><span class="ka-badge">${p.tamamlandi?'Tamamlandı':'Bekliyor'}</span></div></article>`).join(''):'<div class="ka-empty">Periyodik görev bulunamadı.</div>'}}
function leaves(){const teacher=arr('ogretmenIzinleri'),staffLeaves=arr('personelIzinler'),all=[...teacher.map(x=>({...x,_type:'Öğretmen'})),...staffLeaves.map(x=>({...x,_type:'Personel'}))].filter(x=>match([x.tur,x.aciklama,x.baslangic,x.bitis,x.ogretmenAdi,x.personelAdi])).sort((a,b)=>(b.baslangic||'').localeCompare(a.baslangic||''));return{count:all.length,html:all.length?all.map(x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(x.ogretmenAdi||x.personelAdi||x.tur||'İzin kaydı')}</strong><div class="ka-muted">${esc(x.tur||x._type)} · ${esc(date(x.baslangic))} – ${esc(date(x.bitis))}</div></div><span class="ka-badge">${esc(x._type)}</span></div></article>`).join(''):'<div class="ka-empty">İzin kaydı bulunamadı.</div>'}}
function duty(){const list=arr('nobetAtamalari').filter(x=>match([x.ogretmenAdSoyad,x.tarih,x.yerAdi])).sort((a,b)=>(a.tarih||'').localeCompare(b.tarih||''));return{count:list.length,html:list.length?list.slice(0,100).map(x=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(x.ogretmenAdSoyad||'Nöbet')}</strong><div class="ka-muted">${esc(date(x.tarih))}${x.yerAdi?' · '+esc(x.yerAdi):''}</div></div></div></article>`).join(''):'<div class="ka-empty">Nöbet kaydı bulunamadı.</div>'}}
function render(){if(!mounted)return;document.querySelectorAll('[data-management-tab]').forEach(b=>b.classList.toggle('active',b.dataset.managementTab===active));const r=active==='tasks'?tasks():active==='leaves'?leaves():active==='duty'?duty():staff();const out=document.getElementById('managementContent'),c=document.getElementById('managementCount');if(out)out.innerHTML=r.html;if(c)c.textContent=`${r.count} kayıt`}
function bind(){document.querySelectorAll('[data-management-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.managementTab;render()});const s=document.getElementById('managementSearch');if(s)s.oninput=()=>{query=s.value;render()}}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.personel','data.personelIzinler','data.periyodikIsler','data.ogretmenIzinleri','data.nobetAtamalari','data.nobetciAmirleri','data.resmiTatiller','data.nobetRotasyon'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}
function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.ManagementModule={mount,unmount,render,prepareLocal};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='management')mount()});
})();
