/* Koruk Asistan — V2 interaktif harita adaptörü
 * Leaflet/OpenStreetMap + Nominatim + OSRM.
 * Veri: AppStore/DeviceData. Uygulama görünümü: css/design-system.css.
 * Android / iOS Safari-PWA / web aynı davranış katmanını kullanır. */
(function(global){
'use strict';
if(global.HaritaUI)return;
const LEAFLET_JS='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';
const LEAFLET_CSS='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';
let leafletPromise=null;
let map=null,street=null,satellite=null,routeLine=null,locationCircle=null,markers=[],points=[],distanceM=0,mountedRoot=null,searchTimer=null,layer='street';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const rows=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const services=()=>rows('servisler').slice().sort((a,b)=>String(a.servisAdi||a.guzergah||'').localeCompare(String(b.servisAdi||b.guzergah||''),'tr'));
const favorites=()=>global.HaritaService?.gorunurFavoriler?.(rows('haritaFavoriler'))||[];
function requireEdit(){global.PermissionService?.require?.('tools.map','edit');return true}
function km(){return Number((distanceM/1000).toFixed(2))}
function serviceName(s){return s?.servisAdi||s?.guzergah||s?.plaka||'Servis'}
function shell(){return `<section class="ka-stack" data-harita-ui><article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Yer ara</span><input id="mapSearchInput" type="search" placeholder="Okul, köy, mahalle veya adres…" autocomplete="off"></label><label class="ka-field"><span class="ka-field__label">Servis</span><select id="mapServiceSelect"><option value="">— Servis seçin —</option>${services().map(s=>`<option value="${esc(s.id)}">${esc(serviceName(s))}${s.guzergahMesafe?` · ${esc(s.guzergahMesafe)} km`:''}</option>`).join('')}</select></label></div><div class="ka-row ka-wrap"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-map-location>📍 Konumum</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-map-layer>🛰 Uydu</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-map-load>Güzergâhı Yükle</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-map-clear>Temizle</button><button class="ka-btn ka-btn--sm" type="button" data-map-save data-ka-permission="tools.map" data-ka-write="tools.map">Servise Kaydet</button></div><div class="ka-row"><span class="ka-badge" id="mapPointCount">0 nokta</span><span class="ka-badge" id="mapDistance">—</span><span class="ka-muted">Haritaya dokunarak rota noktası ekleyin.</span></div><div id="mapSearchResults" class="ka-stack ka-hidden"></div></div></article><div id="toolsLeafletMap" class="ka-map-canvas" aria-label="Servis güzergâh haritası"></div><div class="ka-grid"><section class="ka-stack"><div class="ka-row ka-row--between"><h3>Favori Konumlar</h3><span class="ka-badge" id="mapFavoriteCount"></span></div><div id="mapFavorites" class="ka-stack"></div></section><section class="ka-stack"><div class="ka-row ka-row--between"><h3>Kayıtlı Güzergâhlar</h3><span class="ka-badge" id="mapRouteCount"></span></div><div id="mapRoutes" class="ka-stack"></div></section></div></section>`}
function leafletCssReady(){if([...document.styleSheets].some(s=>String(s.href||'').includes('leaflet@1.9.4/dist/leaflet.css')))return Promise.resolve();return new Promise((resolve,reject)=>{const existing=[...document.querySelectorAll('link[rel="stylesheet"]')].find(x=>x.href===LEAFLET_CSS||String(x.href||'').includes('leaflet@1.9.4/dist/leaflet.css'));if(existing){if(existing.sheet)return resolve();existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error('Harita stili yüklenemedi.')),{once:true});return;}const link=document.createElement('link');link.rel='stylesheet';link.href=LEAFLET_CSS;link.dataset.korukExternal='leaflet';link.onload=resolve;link.onerror=()=>reject(new Error('Harita stili yüklenemedi.'));document.head.appendChild(link);});}
function leafletJsReady(){if(typeof global.L!=='undefined')return Promise.resolve();return new Promise((resolve,reject)=>{const existing=[...document.scripts].find(s=>s.src===LEAFLET_JS||String(s.src||'').includes('leaflet@1.9.4/dist/leaflet.js'));if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error('Harita kütüphanesi yüklenemedi.')),{once:true});return;}const script=document.createElement('script');script.src=LEAFLET_JS;script.async=true;script.dataset.korukExternal='leaflet';script.onload=resolve;script.onerror=()=>reject(new Error('Harita kütüphanesi yüklenemedi.'));document.head.appendChild(script);});}
async function ensureLibs(){if(typeof global.L!=='undefined'){await leafletCssReady();return true}if(!leafletPromise)leafletPromise=Promise.all([leafletCssReady(),leafletJsReady()]).then(()=>true).catch(e=>{leafletPromise=null;throw e});await leafletPromise;if(!global.L)throw new Error('Leaflet yüklenemedi.');return true}
function initMap(){const el=document.getElementById('toolsLeafletMap');if(!el)return;if(map){try{map.remove()}catch(_){}map=null}street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19});satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'© Esri',maxZoom:19});map=L.map(el,{zoomControl:true,tap:true}).setView([39,35],6);street.addTo(map);layer='street';map.on('click',e=>addPoint(e.latlng.lat,e.latlng.lng));requestAnimationFrame(()=>map?.invalidateSize())}
function bind(){const q=document.getElementById('mapSearchInput');if(q)q.oninput=()=>{clearTimeout(searchTimer);const text=q.value.trim();if(text.length<3){renderSearch([]);return}searchTimer=setTimeout(()=>search(text),450)};document.querySelector('[data-map-location]')?.addEventListener('click',goLocation);document.querySelector('[data-map-layer]')?.addEventListener('click',toggleLayer);document.querySelector('[data-map-clear]')?.addEventListener('click',clearRoute);document.querySelector('[data-map-load]')?.addEventListener('click',loadSelectedService);document.querySelector('[data-map-save]')?.addEventListener('click',saveRoute);document.getElementById('mapServiceSelect')?.addEventListener('change',renderInfo);global.PermissionService?.apply?.(mountedRoot)}
function markerPopup(marker,index){const p=points[index];if(!p)return'';return `<div class="ka-stack"><strong>${esc(p.ad||`Nokta ${index+1}`)}</strong><small>${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}</small><div class="ka-row"><button class="ka-btn ka-btn--secondary ka-btn--sm" data-popup-favorite="${index}" type="button">⭐ Favori</button><button class="ka-btn ka-btn--danger ka-btn--sm" data-popup-remove="${index}" type="button">Sil</button></div></div>`}
function bindPopup(marker,index){marker.bindPopup(()=>markerPopup(marker,index));marker.on('popupopen',()=>{const popup=marker.getPopup()?.getElement();popup?.querySelector('[data-popup-remove]')?.addEventListener('click',()=>removePoint(markers.indexOf(marker)));popup?.querySelector('[data-popup-favorite]')?.addEventListener('click',()=>favoritePoint(markers.indexOf(marker)))})}
function addPoint(lat,lng,ad=''){if(!map)return;const marker=L.marker([lat,lng],{draggable:true}).addTo(map),point={lat:Number(lat),lng:Number(lng),ad:ad||`Nokta ${points.length+1}`};points.push(point);markers.push(marker);bindPopup(marker,markers.length-1);marker.bindTooltip(String(markers.length),{permanent:true,direction:'top',offset:[0,-12]});marker.on('dragend',()=>{const i=markers.indexOf(marker),p=marker.getLatLng();if(i<0)return;points[i]={...points[i],lat:p.lat,lng:p.lng};updateRoute()});updateRoute();renderInfo();return marker}
function removePoint(index){if(index<0||index>=markers.length)return;map?.removeLayer(markers[index]);markers.splice(index,1);points.splice(index,1);markers.forEach((m,i)=>{m.unbindTooltip();m.bindTooltip(String(i+1),{permanent:true,direction:'top',offset:[0,-12]});m.unbindPopup();bindPopup(m,i)});updateRoute();renderInfo()}
function clearRoute(){markers.forEach(m=>{try{map?.removeLayer(m)}catch(_){}});markers=[];points=[];distanceM=0;if(routeLine){map?.removeLayer(routeLine);routeLine=null}renderInfo()}
function straightDistance(){let total=0;for(let i=1;i<points.length;i++)total+=L.latLng(points[i-1].lat,points[i-1].lng).distanceTo(L.latLng(points[i].lat,points[i].lng));return total}
async function updateRoute(){if(routeLine){map?.removeLayer(routeLine);routeLine=null}if(points.length<2){distanceM=0;renderInfo();return}const badge=document.getElementById('mapDistance');if(badge)badge.textContent='Hesaplanıyor…';try{const coords=points.map(p=>`${p.lng},${p.lat}`).join(';'),res=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`),data=await res.json();if(data.code!=='Ok'||!data.routes?.length)throw new Error('rota-yok');distanceM=Number(data.routes[0].distance)||0;const line=data.routes[0].geometry.coordinates.map(c=>[c[1],c[0]]);routeLine=L.polyline(line,{weight:5,opacity:.85}).addTo(map)}catch(e){console.warn('[Harita/OSRM]',e?.message||e);distanceM=straightDistance();routeLine=L.polyline(points.map(p=>[p.lat,p.lng]),{weight:4,opacity:.8,dashArray:'8,4'}).addTo(map)}renderInfo()}
function renderInfo(){const n=document.getElementById('mapPointCount'),d=document.getElementById('mapDistance'),save=document.querySelector('[data-map-save]');if(n)n.textContent=`${points.length} nokta`;if(d)d.textContent=points.length>=2?`${km()} km`:'—';if(save)save.disabled=points.length<2||!document.getElementById('mapServiceSelect')?.value;renderDataLists()}
function renderDataLists(){const fav=favorites(),routes=services().filter(s=>Array.isArray(s.guzergahKoordinatlar)&&s.guzergahKoordinatlar.length);const fc=document.getElementById('mapFavoriteCount'),rc=document.getElementById('mapRouteCount'),fb=document.getElementById('mapFavorites'),rb=document.getElementById('mapRoutes');if(fc)fc.textContent=String(fav.length);if(rc)rc.textContent=String(routes.length);if(fb){fb.innerHTML=fav.length?fav.map(f=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(f.ad||'Favori')}</strong><div class="ka-muted">${Number(f.lat).toFixed(5)}, ${Number(f.lng).toFixed(5)}</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-fav-add="${esc(f.id)}">Rotaya Ekle</button>${global.HaritaService?.favoriSilinebilirMi?.(f)?`<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-fav-delete="${esc(f.id)}">Sil</button>`:''}</div></article>`).join(''):'<div class="ka-empty">Favori konum bulunamadı.</div>';fb.querySelectorAll('[data-fav-add]').forEach(b=>b.onclick=()=>{const f=fav.find(x=>x.id===b.dataset.favAdd);if(f){addPoint(f.lat,f.lng,f.ad);map?.setView([f.lat,f.lng],15)}});fb.querySelectorAll('[data-fav-delete]').forEach(b=>b.onclick=async()=>{const f=fav.find(x=>x.id===b.dataset.favDelete);if(!f)return;try{await global.HaritaService.favoriSil(f.id,f)}catch(e){global.toast?.(e?.message||'Favori silinemedi.')}})}if(rb){rb.innerHTML=routes.length?routes.map(s=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(serviceName(s))}</strong><div class="ka-muted">${esc(s.guzergahMesafe||'—')} km · ${s.guzergahKoordinatlar.length} nokta</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-route-load="${esc(s.id)}">Haritada Göster</button></div></article>`).join(''):'<div class="ka-empty">Kayıtlı servis güzergâhı bulunamadı.</div>';rb.querySelectorAll('[data-route-load]').forEach(b=>b.onclick=()=>loadService(b.dataset.routeLoad))}}
async function search(q){const box=document.getElementById('mapSearchResults');if(box){box.classList.remove('ka-hidden');box.innerHTML='<div class="ka-muted">Aranıyor…</div>'}try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(q)}&countrycodes=tr&limit=5&accept-language=tr`,{headers:{'Accept-Language':'tr'}}),data=await res.json();renderSearch(Array.isArray(data)?data:[])}catch(e){console.warn('[Harita/Nominatim]',e?.message||e);if(box)box.innerHTML='<div class="ka-empty">Arama bağlantısı kurulamadı.</div>'}}
function renderSearch(list){const box=document.getElementById('mapSearchResults');if(!box)return;if(!list.length){box.classList.add('ka-hidden');box.innerHTML='';return}box.classList.remove('ka-hidden');box.innerHTML=list.map((r,i)=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(String(r.display_name||'').split(',')[0])}</strong><div class="ka-muted">${esc(String(r.display_name||'').split(',').slice(1,4).join(','))}</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-search-add="${i}">Rotaya Ekle</button><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-search-fav="${i}">⭐</button></div></article>`).join('');box.querySelectorAll('[data-search-add]').forEach(b=>b.onclick=()=>{const r=list[Number(b.dataset.searchAdd)],lat=Number(r.lat),lng=Number(r.lon),ad=String(r.display_name||'').split(',')[0];addPoint(lat,lng,ad);map?.setView([lat,lng],15);box.classList.add('ka-hidden')});box.querySelectorAll('[data-search-fav]').forEach(b=>b.onclick=()=>{const r=list[Number(b.dataset.searchFav)];saveFavorite(Number(r.lat),Number(r.lon),String(r.display_name||'').split(',')[0])})}
function goLocation(){if(!navigator.geolocation){global.toast?.('Bu tarayıcı konum özelliğini desteklemiyor.');return}global.toast?.('Konum alınıyor…');navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;map?.setView([lat,lng],16);if(locationCircle)map?.removeLayer(locationCircle);locationCircle=L.circle([lat,lng],{radius:Math.max(10,pos.coords.accuracy/2),weight:2,fillOpacity:.12}).addTo(map);addPoint(lat,lng,'Mevcut Konum')},err=>global.toast?.({1:'Konum izni reddedildi.',2:'Konum alınamadı.',3:'Konum isteği zaman aşımına uğradı.'}[err.code]||'Konum hatası.'),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
function toggleLayer(){if(!map)return;const btn=document.querySelector('[data-map-layer]');if(layer==='street'){map.removeLayer(street);satellite.addTo(map);layer='satellite';if(btn)btn.textContent='🗺 Sokak'}else{map.removeLayer(satellite);street.addTo(map);layer='street';if(btn)btn.textContent='🛰 Uydu'}}
async function saveFavorite(lat,lng,name=''){try{requireEdit();const ad=name||global.prompt?.('Favori konum adı:','')?.trim();if(!ad)return;await global.HaritaService.favoriEkle({ad,aciklama:'',lat,lng});global.toast?.(`"${ad}" favorilere eklendi.`);refresh()}catch(e){global.toast?.(e?.code==='permission-denied'?'Bu işlem için yetkiniz yok.':e?.message||'Favori eklenemedi.')}}
function favoritePoint(index){const p=points[index];if(p)saveFavorite(p.lat,p.lng,p.ad)}
async function saveRoute(){const id=document.getElementById('mapServiceSelect')?.value;if(!id||points.length<2)return;try{requireEdit();if(!global.TasimaRepository)await global.AppLoader?.load?.('transport');await global.HaritaService.guzergahKaydet(id,km(),points.map(p=>({lat:p.lat,lng:p.lng,ad:p.ad})));global.toast?.(`Güzergâh cihazda kaydedildi: ${km()} km`);renderDataLists()}catch(e){global.toast?.(e?.code==='permission-denied'?'Bu işlem için yetkiniz yok.':e?.message==='tasima-hazir-degil'?'Taşıma veri katmanı hazır değil.':e?.message||'Güzergâh kaydedilemedi.')}}
function loadSelectedService(){const id=document.getElementById('mapServiceSelect')?.value;if(id)loadService(id)}
function loadService(id){const s=services().find(x=>x.id===id);if(!s?.guzergahKoordinatlar?.length){global.toast?.('Bu servis için kayıtlı güzergâh yok.');return}clearRoute();const sel=document.getElementById('mapServiceSelect');if(sel)sel.value=id;s.guzergahKoordinatlar.forEach(p=>addPoint(Number(p.lat),Number(p.lng),p.ad||''));if(points.length){const bounds=L.latLngBounds(points.map(p=>[p.lat,p.lng]));map?.fitBounds(bounds,{padding:[32,32]})}}
async function mount(root){if(!root)return false;unmount();mountedRoot=root;root.innerHTML=shell();try{await ensureLibs();if(mountedRoot!==root)return false;initMap();bind();renderInfo();return true}catch(e){root.innerHTML=`<div class="ka-empty">Harita yüklenemedi: ${esc(e?.message||e)}</div>`;return false}}
function refresh(){if(!mountedRoot)return;const select=document.getElementById('mapServiceSelect'),old=select?.value;if(select){select.innerHTML='<option value="">— Servis seçin —</option>'+services().map(s=>`<option value="${esc(s.id)}">${esc(serviceName(s))}${s.guzergahMesafe?` · ${esc(s.guzergahMesafe)} km`:''}</option>`).join('');if(services().some(s=>s.id===old))select.value=old}renderInfo();map?.invalidateSize()}
function unmount(){if(map){try{map.remove()}catch(_){}map=null}markers=[];points=[];routeLine=null;locationCircle=null;distanceM=0;mountedRoot=null;clearTimeout(searchTimer)}
global.HaritaUI={mount,unmount,refresh,addPoint,clear:clearRoute,loadService,saveRoute};

})(window);