/* Koruk Asistan — People yardımcı UI adaptörü
 * Eski Sınıflar UX'indeki Excel / e-Okul akışını yeni local-first SiniflarService'e bağlar.
 * Eski Öğretmenler UX'indeki Excel içe aktarmayı canonical OgretmenService'e bağlar.
 * Öğrenci sonuç trend grafiğini People sonuç sayfasına lazy Chart.js ile geri kazandırır.
 * Eski öğretmen detayındaki kulüp öğrenci işlemleri, sorumluluk ve haftalık norm bölümlerini canonical People görünümüne bağlar.
 * Ayrı veri katmanı oluşturmaz; yalnız UI + dosya ayrıştırma / görünüm adaptörüdür.
 */
(function(global){
'use strict';
if(global.PeopleImportUI)return;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const norm=v=>String(v??'').toLocaleUpperCase('tr').replace(/\./g,'').replace(/\s+/g,' ').trim();
let observer=null,busy=false;
function canImport(){return !global.PermissionService||global.PermissionService.can('people.students.edit','edit')}
function canImportTeachers(){return !global.PermissionService||global.PermissionService.can('people.teachers','edit')}
function loadScript(src,test){if(test())return Promise.resolve();return new Promise((ok,no)=>{const old=[...document.scripts].find(s=>s.src===src);if(old){old.addEventListener('load',ok,{once:true});old.addEventListener('error',no,{once:true});return}const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
const ensureXlsx=()=>loadScript('https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js',()=>!!global.XLSX);
async function rows(file){await ensureXlsx();const wb=global.XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];return global.XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:null})}
function headerIndex(data,test){return data.findIndex(r=>Array.isArray(r)&&test(r))}
function col(h,...names){for(const n of names){const i=h.indexOf(n);if(i>=0)return i}return-1}
function classByName(name){return arr('siniflar').find(s=>String(s.ad||'').localeCompare(String(name||''),'tr',{sensitivity:'base'})===0)||null}
function serviceByName(name){return arr('servisler').find(s=>String(s.servisAdi||s.guzergah||'').localeCompare(String(name||''),'tr',{sensitivity:'base'})===0)||null}
function teacherGender(v){const n=norm(v);if(['K','KADIN','BAYAN','FEMALE','KIZ'].includes(n)||n.includes('KADIN')||n.includes('KIZ'))return'Kadın';if(['E','ERKEK','BAY','MALE'].includes(n)||n.includes('ERKEK'))return'Erkek';return''}

/* Eski ogretmenExceliIceAktar sözleşmesi — yazma artık OgretmenService üzerinden. */
async function parseTeacherExcel(file){
 const data=await rows(file),hi=headerIndex(data,r=>r.some(c=>norm(c)==='AD'||norm(c)==='AD SOYAD'));
 if(hi<0)throw new Error('Başlık satırı bulunamadı (AD / AD SOYAD sütunu gerekli).');
 const h=data[hi].map(norm),cAS=col(h,'AD SOYAD'),cA=col(h,'AD'),cS=col(h,'SOYAD'),cB=col(h,'BRANŞ','BRANS'),cT=col(h,'TELEFON'),cE=col(h,'E-POSTA','EPOSTA','E POSTA'),cR=col(h,'SORUMLU SINIF','SORUMLU SINIFI'),cU=col(h,'ÜNVAN','UNVAN'),cD=col(h,'DERECE'),cK=col(h,'KADEME'),cC=col(h,'CİNSİYET','CINSIYET','CİNSİYETİ','CINSIYETI'),out=[];
 for(let i=hi+1;i<data.length;i++){
  const r=data[i]||[];let ad='',soyad='';
  if(cAS>=0&&r[cAS]){const p=String(r[cAS]).trim().split(/\s+/);soyad=p.pop()||'';ad=p.join(' ')}else{ad=cA>=0?String(r[cA]||'').trim():'';soyad=cS>=0?String(r[cS]||'').trim():''}
  if(!ad)continue;const derece=cD>=0?parseInt(r[cD]):NaN,kademe=cK>=0?parseInt(r[cK]):NaN;
  out.push({ad,soyad,unvan:cU>=0?String(r[cU]||'').trim():'',brans:cB>=0?String(r[cB]||'').trim():'',derece:Number.isNaN(derece)?null:derece,kademeNo:Number.isNaN(kademe)?null:kademe,telefon:cT>=0?String(r[cT]||'').trim():'',eposta:cE>=0?String(r[cE]||'').trim():'',sorumluSinif:cR>=0?String(r[cR]||'').trim():'',cinsiyet:cC>=0?teacherGender(r[cC]):''});
 }
 if(!out.length)throw new Error('Dosyada öğretmen satırı bulunamadı.');return out;
}
async function importTeachers(file){
 if(!canImportTeachers())throw new Error('Bu işlem için yetkiniz yok.');if(!global.OgretmenService?.kaydet)throw new Error('Öğretmen servisi hazır değil.');
 const parsed=await parseTeacherExcel(file),known=arr('ogretmenler'),seen=[...known];let eklenen=0,guncellenen=0;
 for(const v of parsed){const mevcut=seen.find(o=>String(o.ad||'').localeCompare(v.ad,'tr',{sensitivity:'base'})===0&&String(o.soyad||'').localeCompare(v.soyad,'tr',{sensitivity:'base'})===0);const saved=await global.OgretmenService.kaydet(mevcut?.id||'',v);if(mevcut){Object.assign(mevcut,v);guncellenen++}else{seen.push({id:saved?.id||'',...v});eklenen++}}
 global.toast?.(`Öğretmenler içe aktarıldı: ${eklenen} eklendi, ${guncellenen} güncellendi.`);return{eklenen,guncellenen};
}
function chooseTeacherExcel(){if(!canImportTeachers())return global.toast?.('Bu işlem için yetkiniz yok.');let input=document.querySelector('[data-teacher-excel-input]');if(!input){input=document.createElement('input');input.type='file';input.accept='.xlsx,.xls';input.hidden=true;input.dataset.teacherExcelInput='';input.addEventListener('change',async()=>{const f=input.files?.[0];input.value='';if(!f)return;try{await importTeachers(f)}catch(err){console.error('[PeopleImport/teachers]',err);global.toast?.('İçe aktarma hatası: '+(err?.message||err))}});document.body.appendChild(input)}input.click()}

async function parseStudentExcel(file,targetClassId=''){
 const data=await rows(file),hi=headerIndex(data,r=>r.some(c=>['ÖĞRENCİ ADI','OGRENCI ADI','AD SOYAD','AD'].includes(norm(c))));
 if(hi<0)throw new Error('Başlık satırı bulunamadı. Öğrenci Adı / Ad Soyad sütunu gerekli.');
 const h=data[hi].map(norm),cO=col(h,'ÖĞRENCİ ADI','OGRENCI ADI','AD SOYAD','AD'),cN=col(h,'ÖĞRENCİ NO','OGRENCI NO','NO','NUMARA'),cC=col(h,'CİNSİYET','CINSIYET'),cV=col(h,'VELİ ADI','VELI ADI','VELİ AD SOYAD','VELI AD SOYAD','VELİ','VELI'),cY=col(h,'YAKINLIK','YAKINLIK DERECESİ','YAKINLIK DERECESI'),cT1=col(h,'TELEFON 1','TELEFON1','TEL 1','TEL1','TELEFON'),cT2=col(h,'TELEFON 2','TELEFON2','TEL 2','TEL2'),cT3=col(h,'TELEFON 3','TELEFON3','TEL 3','TEL3'),cA=col(h,'ADRES'),cS=col(h,'SINIF','SINIF ADI'),cSV=col(h,'SERVİS','SERVIS','SERVİS ADI','SERVIS ADI'),cNO=col(h,'NOTLAR','NOT'),out=[];
 for(let i=hi+1;i<data.length;i++){
  const r=data[i]||[],ogrenciAdi=String(r[cO]||'').trim();if(!ogrenciAdi)continue;
  let sinifId=targetClassId;if(!sinifId&&cS>=0)sinifId=classByName(String(r[cS]||'').trim())?.id||'';
  let servisId='',servisAdi='';if(cSV>=0){const sv=serviceByName(String(r[cSV]||'').trim());if(sv){servisId=sv.id;servisAdi=sv.servisAdi||sv.guzergah||''}}
  const tel1=cT1>=0?String(r[cT1]||'').trim():'';
  out.push({sinifId,ogrenciAdi,ogrenciNo:cN>=0?String(r[cN]||'').trim():'',cinsiyet:cC>=0?String(r[cC]||'').trim():'',veliAdi:cV>=0?String(r[cV]||'').trim():'',yakinlik:cY>=0?String(r[cY]||'').trim():'',telefon1:tel1,telefon:tel1,telefon2:cT2>=0?String(r[cT2]||'').trim():'',telefon3:cT3>=0?String(r[cT3]||'').trim():'',adres:cA>=0?String(r[cA]||'').trim():'',servisId,servisAdi,notlar:cNO>=0?String(r[cNO]||'').trim():''});
 }
 if(!out.length)throw new Error('Dosyada öğrenci satırı bulunamadı.');
 return out;
}
async function importStudents(file,targetClassId=''){
 if(!canImport())throw new Error('Bu işlem için yetkiniz yok.');
 const parsed=await parseStudentExcel(file,targetClassId),result=await global.SiniflarService.ogrenciVeliListesiIceAktar(parsed,arr('veliler'));
 global.toast?.(`Öğrenci listesi içe aktarıldı: ${result.eklenen||0} eklendi, ${result.guncellenen||0} güncellendi.`);
 return result;
}
async function parseEOkul(file){
 const data=await rows(file),hi=headerIndex(data,r=>r.some(c=>norm(c)==='ADI')&&r.some(c=>norm(c)==='SOYADI'));
 if(hi<0)throw new Error('“Adı” / “Soyadı” başlıkları bulunamadı. e-Okul Sınıf Listesi raporu seçilmelidir.');
 const h=data[hi].map(norm),cA=col(h,'ADI'),cS=col(h,'SOYADI'),cN=col(h,'ÖĞRENCİ NO','OGRENCI NO','NUMARA'),cC=col(h,'CİNSİYETİ','CINSIYETI','CİNSİYET','CINSIYET'),blocks=[];let block=[];
 for(let i=hi+1;i<data.length;i++){
  const r=data[i];if(!r||r.every(c=>c==null||c===''))continue;
  const text=r.map(c=>String(c==null?'':c)).join(' ').toLocaleUpperCase('tr'),ad=cA>=0?String(r[cA]||'').trim():'',no=cN>=0?r[cN]:null,validNo=no!=null&&String(no).trim()!==''&&!Number.isNaN(parseInt(no));
  if(text.includes('SAYISI')||!ad||!validNo){if(block.length){blocks.push(block);block=[]}continue}
  const soyad=cS>=0?String(r[cS]||'').trim():'',raw=cC>=0?r[cC]:'',cinsiyet=global.SiniflarService.eOkulCinsiyetNormallestir(raw);
  block.push({ogrenciAdi:`${ad} ${soyad}`.trim(),ogrenciNo:String(no).trim(),cinsiyet});
 }
 if(block.length)blocks.push(block);if(!blocks.length)throw new Error('Dosyada öğrenci bloğu bulunamadı.');return blocks;
}
function closeModal(){document.querySelector('[data-people-import-modal]')?.remove()}
function eOkulModal(blocks,targetClassId=''){
 closeModal();const classes=arr('siniflar').slice().sort((a,b)=>String(a.ad||'').localeCompare(String(b.ad||''),'tr',{numeric:true})),ov=document.createElement('div');ov.className='ka-modal-backdrop';ov.dataset.peopleImportModal='';
 ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><h2>e-Okul Listesi</h2><p class="ka-muted">${blocks.length} sınıf bloğu bulundu. Her bloğun ait olduğu sınıfı seçin.</p></div><button class="ka-icon-button" type="button" data-close aria-label="Kapat">×</button></div><div class="ka-modal__body ka-stack">${blocks.map((b,i)=>`<label class="ka-field" data-eok-row><span class="ka-field__label">Blok ${i+1} · ${b.length} öğrenci</span><small class="ka-muted">${esc(b.slice(0,2).map(x=>x.ogrenciAdi).join(', '))}${b.length>2?'…':''}</small><select data-eok-class><option value="">Atla</option>${classes.map((s,si)=>`<option value="${esc(s.id)}" ${(targetClassId&&i===0?s.id===targetClassId:!targetClassId&&si===i)?'selected':''}>${esc(s.ad)}</option>`).join('')}</select></label>`).join('')}</div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-close>Vazgeç</button><button class="ka-btn" type="button" data-eok-apply>İçe Aktar</button></div></section>`;
 document.body.appendChild(ov);$$('[data-close]',ov).forEach(b=>b.onclick=closeModal);ov.addEventListener('click',e=>{if(e.target===ov)closeModal()});
 $('[data-eok-apply]',ov).onclick=async()=>{if(busy)return;const rs=$$('[data-eok-row]',ov),mapped=blocks.map((block,i)=>({block,sinifId:$('[data-eok-class]',rs[i])?.value||''})).filter(x=>x.sinifId);if(!mapped.length)return global.toast?.('En az bir blok için sınıf seçmelisiniz.');let add=0,update=0,remove=0;const plans=mapped.map(x=>{const existing=arr('veliler').filter(v=>v.sinifId===x.sinifId),matches=x.block.map(o=>({o,eslesen:global.SiniflarService.eOkulEslesenBul(existing,o.ogrenciNo,o.ogrenciAdi)}));add+=matches.filter(x=>!x.eslesen).length;update+=matches.filter(x=>x.eslesen).length;const ids=new Set(matches.filter(x=>x.eslesen).map(x=>x.eslesen.id)),deleted=existing.filter(v=>!ids.has(v.id));remove+=deleted.length;return{sinifId:x.sinifId,eslesmeler:matches,silinecekler:deleted}});if(!confirm(`${add} öğrenci eklenecek, ${update} güncellenecek, ${remove} öğrenci silinecek. Onaylıyor musunuz?`))return;busy=true;const apply=$('[data-eok-apply]',ov);apply.disabled=true;try{const r=await global.SiniflarService.eOkulPlanlariniUygula(plans);closeModal();global.toast?.(`İçe aktarıldı: ${r.eklenecek||0} eklendi, ${r.guncellenecek||0} güncellendi, ${r.silinecek||0} silindi.`)}catch(e){console.error('[PeopleImport/eOkul]',e);global.toast?.('İçe aktarma hatası: '+(e?.message||e))}finally{busy=false;if(apply.isConnected)apply.disabled=false}};
}
async function importEOkul(file,targetClassId=''){if(!canImport())throw new Error('Bu işlem için yetkiniz yok.');eOkulModal(await parseEOkul(file),targetClassId)}
function currentClassId(){const detail=$('.ka-class-detail');if(!detail)return'';const direct=$('[data-class-seating]',detail)?.dataset.classSeating||$('[data-class-student-add]',detail)?.dataset.classStudentAdd||$('[data-class-edit]',detail)?.dataset.classEdit||'';if(direct)return direct;const name=$('.ka-detail-topbar h2',detail)?.textContent?.trim()||'';return classByName(name)?.id||''}
function toolbar(target,targetClassId=''){
 if(!target||target.querySelector('[data-legacy-class-imports]')||!canImport())return;
 const box=document.createElement('div');box.className='ka-row ka-wrap';box.dataset.legacyClassImports='';box.innerHTML=`<label class="ka-btn ka-btn--secondary" type="button">📥 Excel'den Ekle<input type="file" accept=".xlsx,.xls" data-legacy-excel hidden></label><label class="ka-btn ka-btn--secondary" type="button">📋 e-Okul Aktar<input type="file" accept=".xlsx,.xls" data-legacy-eokul hidden></label>`;
 target.appendChild(box);$('[data-legacy-excel]',box).onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{await importStudents(f,targetClassId)}catch(err){console.error('[PeopleImport/excel]',err);global.toast?.('İçe aktarma hatası: '+(err?.message||err))}};$('[data-legacy-eokul]',box).onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{await importEOkul(f,targetClassId)}catch(err){console.error('[PeopleImport/eOkul-read]',err);global.toast?.('Dosya okunamadı: '+(err?.message||err))}};
}

/* Eski öğretmen detayındaki kulüp/sorumluluk davranışları — yalnız gerçek ID alanlarıyla. */
function sessionTeacherId(){const u=global.AppStore?.get?.('session.user')||global.AKTIF_KULLANICI||{};return u.bagliOgretmenId||u.ogretmenId||''}
function teacherProfileId(profile){return $('[data-teacher-message]',profile)?.dataset.teacherMessage||$('[data-teacher-edit]',profile)?.dataset.teacherEdit||$('[data-teacher-report]',profile)?.dataset.teacherReport||''}
function clubHasTeacher(k,id){return!!(id&&(Array.isArray(k?.ogretmenIdler)?k.ogretmenIdler.includes(id):k?.ogretmenId===id||k?.danismanOgretmenId===id))}
function teacherRows(type,id){return arr(type).filter(x=>x.ogretmenId===id||(Array.isArray(x.ogretmenIdler)&&x.ogretmenIdler.includes(id)))}
function classLabel(id){return arr('siniflar').find(s=>s.id===id)?.ad||'Sınıfsız'}
function clubStudents(kid){return arr('veliler').filter(v=>v.kulupId===kid).sort((a,b)=>{const c=classLabel(a.sinifId).localeCompare(classLabel(b.sinifId),'tr',{numeric:true});return c||String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr')})}
function canManageClub(k){const tid=sessionTeacherId();return canImport()||clubHasTeacher(k,tid)}
function closeClubModal(){document.querySelector('[data-people-club-modal]')?.remove()}
function clubStudentModal(kid){
 const k=arr('sosyalKulupler').find(x=>x.id===kid);if(!k)return global.toast?.('Kulüp bulunamadı.');if(!canManageClub(k))return global.toast?.('Bu kulübün öğrenci listesini değiştirme yetkiniz yok.');
 closeClubModal();const allowed=arr('veliler').filter(v=>!Array.isArray(k.sinifIdler)||!k.sinifIdler.length||k.sinifIdler.includes(v.sinifId)||v.kulupId===kid).sort((a,b)=>{const c=classLabel(a.sinifId).localeCompare(classLabel(b.sinifId),'tr',{numeric:true});return c||String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr')}),ov=document.createElement('div');ov.className='ka-modal-backdrop';ov.dataset.peopleClubModal='';
 ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><h2>${esc(k.ad||k.kulupAdi||'Sosyal Kulüp')}</h2><p class="ka-muted">Kulübe öğrenci ekle / çıkar</p></div><button class="ka-icon-button" type="button" data-club-close aria-label="Kapat">×</button></div><div class="ka-modal__body ka-stack">${allowed.length?allowed.map(v=>`<label class="ka-card"><span class="ka-card__body ka-row"><input type="checkbox" data-club-student="${esc(v.id)}" ${v.kulupId===kid?'checked':''}><span class="ka-grow"><strong>${esc(v.ogrenciAdi||'Öğrenci')}</strong><small class="ka-muted" style="display:block">${esc(classLabel(v.sinifId))}${v.kulupId&&v.kulupId!==kid?` · Başka kulüpte: ${esc(v.kulupAdi||'')}`:''}</small></span></span></label>`).join(''):'<div class="ka-empty">Bu kulüp için seçilebilir öğrenci bulunamadı.</div>'}</div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-club-close>Vazgeç</button><button class="ka-btn" type="button" data-club-save ${allowed.length?'':'disabled'}>Kaydet</button></div></section>`;
 document.body.appendChild(ov);$$('[data-club-close]',ov).forEach(b=>b.onclick=closeClubModal);ov.addEventListener('click',e=>{if(e.target===ov)closeClubModal()});$('[data-club-save]',ov)?.addEventListener('click',async e=>{if(busy)return;busy=true;e.currentTarget.disabled=true;try{const selected=new Set($$('[data-club-student]:checked',ov).map(x=>x.dataset.clubStudent));let changed=0;for(const v of allowed){const wanted=selected.has(v.id);if(wanted&&v.kulupId!==kid){await global.SiniflarService.ogrenciKulupGuncelle(v.id,kid,k.ad||k.kulupAdi||'');changed++}else if(!wanted&&v.kulupId===kid){await global.SiniflarService.ogrenciKulupGuncelle(v.id,'','');changed++}}closeClubModal();global.toast?.(changed?`${changed} öğrenci için kulüp bilgisi güncellendi.`:'Değişiklik yok.')}catch(err){console.error('[PeopleImport/club]',err);global.toast?.('Kulüp öğrenci listesi güncellenemedi: '+(err?.message||err))}finally{busy=false;if(e.currentTarget.isConnected)e.currentTarget.disabled=false}})
}
async function printClubStudents(kid){
 const k=arr('sosyalKulupler').find(x=>x.id===kid);if(!k)return;const rs=clubStudents(kid);try{if(!global.ReportEngine?.printReport)await global.AppLoader?.loadScript?.('js/modules/report-engine.js');if(!global.ReportEngine?.printReport)throw new Error('Rapor motoru hazır değil.');const body=rs.length?`<table><thead><tr><th>Sıra</th><th>Öğrenci</th><th>Sınıf</th><th>Öğrenci No</th></tr></thead><tbody>${rs.map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.ogrenciAdi||'')}</td><td>${esc(classLabel(v.sinifId))}</td><td>${esc(v.ogrenciNo||'')}</td></tr>`).join('')}</tbody></table>`:'<p>Kulübe atanmış öğrenci bulunmuyor.</p>';await global.ReportEngine.printReport(`${k.ad||k.kulupAdi||'Sosyal Kulüp'} Öğrenci Listesi`,body,{fileName:`${k.ad||'Kulup'}_Ogrenci_Listesi`,compact:true})}catch(err){console.error('[PeopleImport/club-print]',err);global.toast?.('Kulüp öğrenci listesi açılamadı.')}
}
function teacherSection(title,icon,rs,marker){if(!rs.length)return null;const s=document.createElement('section');s.className='ka-card ka-teacher-detail-section';s.dataset.legacyTeacherSection=marker;s.innerHTML=`<div class="ka-card__header"><div class="ka-row"><span class="ka-teacher-section-icon" aria-hidden="true">${icon}</span><h3>${esc(title)}</h3></div></div><div class="ka-card__body">${rs.join('')}</div>`;return s}

/* Eski Haftalık Norm Analizi — gerçek dersProgrami + dersListesi.haftalikSaatler modeli. */
let teacherNormPromise=null;
function prepareTeacherNormData(){
 if(teacherNormPromise)return teacherNormPromise;
 teacherNormPromise=(async()=>{if(!global.SyncEngine||!global.COL?.dersListesi)return false;global.SyncEngine.register('dersListesi',global.COL.dersListesi);await global.SyncEngine.localHydrate(['dersListesi']);requestAnimationFrame(enhanceTeacherProfile);Promise.resolve(global.SyncEngine.pull?.(['dersListesi'])).then(()=>requestAnimationFrame(enhanceTeacherProfile)).catch(e=>console.warn('[People/teacher-norm-sync]',e));return true})().catch(e=>{teacherNormPromise=null;console.warn('[People/teacher-norm]',e);return false});return teacherNormPromise;
}
function teacherNormData(id){const lessons=arr('dersProgrami').filter(d=>d.ogretmenId===id),groups={};lessons.forEach(d=>{const key=`${d.ders}__${d.sinif}`;if(!groups[key])groups[key]={ders:d.ders,sinif:d.sinif,saatSayisi:0};groups[key].saatSayisi++});let toplamNorm=0,toplamFiili=0;const rs=Object.values(groups).map(g=>{const m=String(g.sinif||'').match(/^(\d+)/),seviye=m?parseInt(m[1]):null,dersKayit=arr('dersListesi').find(d=>d.ad===g.ders),normSaat=dersKayit?.haftalikSaatler&&seviye?(dersKayit.haftalikSaatler[seviye]||dersKayit.haftalikSaatler[String(seviye)]||null):null;toplamFiili+=g.saatSayisi;if(normSaat!==null)toplamNorm+=normSaat;return{ders:g.ders,sinif:g.sinif,fiili:g.saatSayisi,norm:normSaat}});return{rows:rs,toplamNorm,toplamFiili,signature:JSON.stringify([id,rs,toplamNorm,toplamFiili])}}
function normFark(fiili,normSaat){if(normSaat===null)return'—';const fark=fiili-normSaat;return fark>0?`+${fark}`:`${fark}`}
function teacherNormSection(id){const n=teacherNormData(id),rs=n.rows.length?n.rows.map(r=>`<div class="ka-teacher-detail-row"><b>${esc(r.ders)} · ${esc(r.sinif)}</b><span>Norm (plan): ${r.norm!==null?r.norm:'—'} · Fiili (program): ${r.fiili} · Fark: ${normFark(r.fiili,r.norm)}</span></div>`):['<div class="ka-empty">Ders programı kaydı yok.</div>'];if(n.rows.length)rs.push(`<div class="ka-teacher-detail-row"><b>TOPLAM</b><span>Norm (plan): ${n.toplamNorm||'—'} · Fiili (program): ${n.toplamFiili} · Fark: ${n.toplamNorm?normFark(n.toplamFiili,n.toplamNorm):'—'}</span></div>`);const s=teacherSection('HAFTALIK NORM ANALİZİ','⏱',rs,'norm');if(s)s.dataset.normSignature=n.signature;return s}
function enhanceTeacherNorm(profile,id,before){prepareTeacherNormData();const current=profile.querySelector('[data-legacy-teacher-section="norm"]'),data=teacherNormData(id);if(current?.dataset.normSignature===data.signature)return;current?.remove();const s=teacherNormSection(id);if(s)(before||profile.lastElementChild)?.insertAdjacentElement(before?'beforebegin':'afterend',s)}
function enhanceTeacherProfile(){const profile=$('.ka-teacher-profile');if(!profile)return;const id=teacherProfileId(profile);if(!id)return;const clubs=arr('sosyalKulupler').filter(k=>clubHasTeacher(k,id)),clubSection=$$('.ka-teacher-detail-section',profile).find(s=>$('h3',s)?.textContent?.trim()==='KULÜP DANIŞMANLIĞI');if(clubSection){const body=$('.ka-card__body',clubSection),detailRows=$$('.ka-teacher-detail-row',body);detailRows.forEach((row,i)=>{const k=clubs[i];if(!k||body.querySelector(`[data-legacy-club-actions="${CSS.escape(String(k.id))}"]`))return;const actions=document.createElement('div');actions.className='ka-row ka-wrap';actions.dataset.legacyClubActions=k.id;actions.style.margin='0 0 10px';const count=clubStudents(k.id).length;actions.innerHTML=`${canManageClub(k)?`<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-legacy-club-add="${esc(k.id)}">➕ Öğrenci Ekle</button>`:''}<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-legacy-club-list="${esc(k.id)}">👥 Öğrenciler (${count})</button>`;row.insertAdjacentElement('afterend',actions);$('[data-legacy-club-add]',actions)?.addEventListener('click',()=>clubStudentModal(k.id));$('[data-legacy-club-list]',actions)?.addEventListener('click',()=>printClubStudents(k.id))})}const before=$('.ka-teacher-doc-status',profile);if(!profile.querySelector('[data-legacy-teacher-section="rehberlik"]')){const rs=teacherRows('rehberlik',id).map(x=>`<div class="ka-teacher-detail-row"><b>${esc(x.ad||x.baslik||x.sinif||'Rehberlik')}</b><span>${esc([x.sinif,x.danisman].filter(Boolean).join(' · '))}</span></div>`),s=teacherSection('REHBERLİK','R',rs,'rehberlik');if(s)(before||profile.lastElementChild)?.insertAdjacentElement(before?'beforebegin':'afterend',s)}if(!profile.querySelector('[data-legacy-teacher-section="bep"]')){const rs=teacherRows('bepPlani',id).map(x=>`<div class="ka-teacher-detail-row"><b>${esc(x.ad||x.baslik||[x.ders,x.sinif].filter(Boolean).join(' · ')||'Yıllık / BEP Planı')}</b><span>${esc([x.ders,x.sinif].filter(Boolean).join(' · '))}</span></div>`),s=teacherSection('YILLIK / BEP PLANLARI','P',rs,'bep');if(s)(before||profile.lastElementChild)?.insertAdjacentElement(before?'beforebegin':'afterend',s)}enhanceTeacherNorm(profile,id,before)}

let resultStudentId='',resultChart=null,resultChartLoadPromise=null,resultChartScheduled=false,resultChartSignature='';
function loadResultsChartLibrary(){if(typeof global.Chart!=='undefined')return Promise.resolve();if(resultChartLoadPromise)return resultChartLoadPromise;resultChartLoadPromise=new Promise((resolve,reject)=>{const existing=[...document.scripts].find(s=>/chart(?:\.umd)?(?:\.min)?\.js/i.test(s.src||''));if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.4/chart.umd.min.js';script.onload=resolve;script.onerror=()=>reject(new Error('Grafik kütüphanesi yüklenemedi.'));document.head.appendChild(script)}).catch(e=>{resultChartLoadPromise=null;throw e});return resultChartLoadPromise}
function resultNet(result){if(Number.isFinite(Number(result?.net)))return Number(result.net);if(Number.isFinite(Number(result?.toplamNet)))return Number(result.toplamNet);const nets=Object.values(result?.dersSonuclari||{}).map(x=>Number(x?.net)).filter(Number.isFinite);return nets.length?Math.round(nets.reduce((a,b)=>a+b,0)*100)/100:null}
function resultSeries(type,student){const out=[];for(const exam of arr(type))for(const result of Array.isArray(exam.sonuclar)?exam.sonuclar:[]){const sameId=result.ogrenciId&&result.ogrenciId===student.id,sameLegacy=!result.ogrenciId&&norm(result.ogrenciAdi)===norm(student.ogrenciAdi);if(!sameId&&!sameLegacy)continue;const net=resultNet(result);if(net===null)continue;out.push({x:exam.tarih||result.tarih||'',y:net})}return out.sort((a,b)=>String(a.x).localeCompare(String(b.x)))}
function destroyResultChart(){if(resultChart){try{resultChart.destroy()}catch(_){ }resultChart=null}resultChartSignature=''}
function chartColor(name,fallback){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback}
async function drawResultChart(){const page=$('.ka-student-results'),student=arr('veliler').find(v=>v.id===resultStudentId);if(!page||!student){destroyResultChart();return}let card=$('[data-student-results-chart]',page);if(!card){card=document.createElement('section');card.className='ka-card';card.dataset.studentResultsChart='';card.innerHTML='<div class="ka-card__header"><div><h3>Net Gelişimi</h3><small class="ka-muted">Deneme ve test sonuçlarının tarihsel görünümü</small></div></div><div class="ka-card__body"><canvas data-student-results-chart-canvas height="220"></canvas></div>';const overview=$('.ka-result-overview',page);overview?.insertAdjacentElement('afterend',card)}const canvas=$('[data-student-results-chart-canvas]',card);if(!canvas)return;const deneme=resultSeries('denemeSonuclari',student),test=resultSeries('testSonuclari',student),signature=JSON.stringify([resultStudentId,deneme,test]);if(!deneme.length&&!test.length){destroyResultChart();card.querySelector('.ka-card__body').innerHTML='<div class="ka-empty">Grafik için henüz sınav sonucu yok.</div>';resultChartSignature=signature;return}try{await loadResultsChartLibrary()}catch(e){console.warn('[People/results-chart] Chart.js yüklenemedi:',e);card.querySelector('.ka-card__body').innerHTML='<div class="ka-empty">Grafik çevrimdışıyken yüklenemedi. Sonuç listesi kullanılabilir.</div>';return}if(!canvas.isConnected||typeof global.Chart==='undefined')return;if(resultChart&&resultChart.canvas===canvas&&resultChartSignature===signature)return;destroyResultChart();const denemeColor=chartColor('--ka-accent','#1677d2'),testColor=chartColor('--ka-primary','#17684f');resultChart=new global.Chart(canvas.getContext('2d'),{type:'line',data:{datasets:[{label:'Deneme Net',data:deneme,borderColor:denemeColor,backgroundColor:denemeColor,tension:.25},{label:'Test Net',data:test,borderColor:testColor,backgroundColor:testColor,tension:.25}]},options:{responsive:true,scales:{x:{type:'category'},y:{beginAtZero:true}},plugins:{legend:{position:'bottom'}}}});resultChartSignature=signature}
function scheduleResultChart(){if(resultChartScheduled)return;resultChartScheduled=true;requestAnimationFrame(()=>{resultChartScheduled=false;drawResultChart().catch(e=>console.warn('[People/results-chart]',e))})}
function trackStudent(e){const exportBtn=e.target?.closest?.('[data-teacher-export]');if(exportBtn&&$('.ka-teacher-directory')){e.preventDefault();e.stopImmediatePropagation();chooseTeacherExcel();return}const detail=e.target?.closest?.('[data-student-detail]');if(detail?.dataset.studentDetail)resultStudentId=detail.dataset.studentDetail;if(e.target?.closest?.('[data-student-back]')){resultStudentId='';destroyResultChart()}if(e.target?.closest?.('[data-results-back]'))destroyResultChart()}
function enhance(){if(global.AppStore?.get?.('ui.route')!=='people'){destroyResultChart();closeClubModal();return}const list=$('.ka-class-directory .ka-people-page-head');if(list)toolbar(list,'');const detail=$('.ka-class-detail');if(detail){const tab=$('.ka-detail-tabs',detail),studentsActive=$('[data-class-tab="students"].active',detail);if(tab&&studentsActive){let holder=tab.nextElementSibling;if(!holder||!holder.classList.contains('ka-class-actions')){holder=document.createElement('div');holder.className='ka-class-actions';tab.insertAdjacentElement('afterend',holder)}toolbar(holder,currentClassId())}}const teacherExcel=$('.ka-teacher-directory [data-teacher-export]');if(teacherExcel)teacherExcel.textContent='Excel';enhanceTeacherProfile();if($('.ka-student-results'))scheduleResultChart();else destroyResultChart()}
function init(){if(observer)return;const root=document.getElementById('v2ModuleRoot')||document.body;root.addEventListener('click',trackStudent,true);observer=new MutationObserver(()=>requestAnimationFrame(enhance));observer.observe(root,{childList:true,subtree:true});window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='people')requestAnimationFrame(enhance)});requestAnimationFrame(enhance)}
global.PeopleImportUI={init,importStudents,importEOkul,importTeachers,parseStudentExcel,parseEOkul,parseTeacherExcel,clubStudentModal,printClubStudents};init();
})(window);