/* Koruk Asistan — Özelleştirilebilir Raporlar */
(function(global){
'use strict';
if(global.ReportsModule)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const STORE='koruk-report-designer-v1';
let active='home',root=null,editing=null;
function school(){const x=arr('okulBilgileri').find(x=>x.id==='ayarlar')||arr('okulBilgileri')[0]||{};return x.okulAdi||x.ad||'Koruk İlkokulu - Ortaokulu'}
function classLevel(s){const m=String(s?.ad||s?.sinif||'').match(/(^|\D)([1-8])(?:\D|$)/);return m?Number(m[2]):0}
function className(s){return String(s?.ad||s?.sinif||'Sınıf').trim()}
function genderCounts(s){const students=arr('veliler').filter(v=>String(v.sinifId||'')===String(s.id||''));if(students.length){let kiz=0,erkek=0;students.forEach(v=>{const c=String(v.cinsiyet||'').toLocaleLowerCase('tr-TR');if(c.includes('kız')||c.includes('kiz'))kiz++;else if(c.includes('erkek'))erkek++});return{kiz,erkek,toplam:students.length}}const kiz=Number(s.kizSayisi||0),erkek=Number(s.erkekSayisi||0),toplam=Number(s.ogrenciSayisi||kiz+erkek);return{kiz,erkek,toplam}}
function classesFor(stage){return arr('siniflar').filter(s=>{const l=classLevel(s);return stage==='primary'?l>=1&&l<=4:l>=5&&l<=8}).sort((a,b)=>classLevel(a)-classLevel(b)||className(a).localeCompare(className(b),'tr'))}
function lessonCfg(){const x=arr('dersSaatleri').find(x=>x.id==='ayarlar')||arr('dersSaatleri')[0]||{},rows=Array.isArray(x.donemler)&&x.donemler.length?x.donemler:(Array.isArray(x.dersler)?x.dersler:[]);return{...x,rows:rows.map((r,i)=>({saat:Number(r.saat||i+1),baslangic:String(r.baslangic||''),bitis:String(r.bitis||'')}))}}
function minutes(v){const m=/^(\d{1,2}):(\d{2})$/.exec(String(v||''));return m?Number(m[1])*60+Number(m[2]):NaN}
function duration(a,b){const n=minutes(b)-minutes(a);return Number.isFinite(n)&&n>=0?`${n} dk`:'—'}
function defs(){const p=classesFor('primary'),m=classesFor('middle');return[
{id:'lesson-times',icon:'🕘',title:'Ders Giriş - Çıkış Saatleri',desc:'Ders başlangıç, bitiş ve teneffüs süreleri',meta:`${lessonCfg().rows.length} ders saati`},
{id:'primary-students',icon:'🏫',title:'İlkokul Öğrenci Sayıları',desc:'Sınıf bazlı kız, erkek ve toplam öğrenci sayıları',meta:`${p.length} sınıf`},
{id:'middle-students',icon:'🎓',title:'Ortaokul Öğrenci Sayıları',desc:'Sınıf bazlı kız, erkek ve toplam öğrenci sayıları',meta:`${m.length} sınıf`},
{id:'all-students',icon:'👥',title:'Okul Geneli Öğrenci Sayıları',desc:'Tüm sınıfların toplu dağılımı',meta:`${p.length+m.length} sınıf`}];}
function baseSettings(id){const d=defs().find(x=>x.id===id)||defs()[0],lesson=id==='lesson-times';return{id,title:d.title,upperTitle:'OKUL YÖNETİM RAPORU',schoolName:school(),subtitle:'',showSchool:true,showUpper:true,showTitle:true,showDate:true,showTime:false,showLogo:true,showSummary:true,showTable:true,orientation:'portrait',titleAlign:'center',tableAlign:'center',dateAlign:'right',fontSize:10,columns:lesson?[{key:'name',label:'Ders / Ara',show:true,align:'left'},{key:'start',label:'Başlangıç',show:true,align:'center'},{key:'end',label:'Bitiş',show:true,align:'center'},{key:'duration',label:'Süre',show:true,align:'center'}]:[{key:'name',label:'Sınıf',show:true,align:'left'},{key:'girls',label:'Kız Öğrenci',show:true,align:'center'},{key:'boys',label:'Erkek Öğrenci',show:true,align:'center'},{key:'total',label:'Toplam',show:true,align:'center'}]};}
function saved(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(_){return{}}}
function settings(id){const b=baseSettings(id),s=saved()[id]||{};return{...b,...s,columns:Array.isArray(s.columns)?s.columns:b.columns}}
function saveSettings(s){const all=saved();all[s.id]=s;localStorage.setItem(STORE,JSON.stringify(all))}
function home(){return `<section class="ka-page ka-stack" data-reports-module><article class="ka-card"><div class="ka-card__body"><small>OKUL YÖNETİMİ</small><h2>Raporlar</h2><p class="ka-muted">Her raporun başlığını, alanlarını, sütunlarını, hizalamasını, tarih-saatini ve sayfa düzenini özelleştirebilirsiniz.</p></div></article><div class="ka-grid">${defs().map(r=>`<article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>${r.icon} ${esc(r.title)}</strong><span class="ka-badge">${esc(r.meta)}</span></div><p class="ka-muted">${esc(r.desc)}</p><div class="ka-row"><button class="ka-btn ka-btn--secondary ka-grow" data-report-design="${r.id}">⚙️ Düzenle</button><button class="ka-btn ka-btn--secondary ka-grow" data-report-open="${r.id}">👁 Önizle</button><button class="ka-btn ka-grow" data-report-print="${r.id}">🖨 Yazdır</button></div></div></article>`).join('')}</div></section>`}
function designer(id){const s=settings(id);return `<section class="ka-page ka-stack" data-reports-module><article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><small>RAPOR TASARIMI</small><h2>${esc(s.title)}</h2></div><button class="ka-btn ka-btn--secondary" data-report-back>← Raporlar</button></div><p class="ka-muted">Görünmesini istediğiniz alanları seçin; başlıkları ve hizalamaları istediğiniz gibi ayarlayın.</p></div></article>
<article class="ka-card"><div class="ka-card__body ka-stack"><h3>Başlık ve Sayfa</h3><label class="ka-field"><span class="ka-field__label">Üst Başlık</span><input class="ka-input" data-rs="upperTitle" value="${esc(s.upperTitle)}"></label><label class="ka-field"><span class="ka-field__label">Okul Adı</span><input class="ka-input" data-rs="schoolName" value="${esc(s.schoolName)}"></label><label class="ka-field"><span class="ka-field__label">Rapor Başlığı</span><input class="ka-input" data-rs="title" value="${esc(s.title)}"></label><label class="ka-field"><span class="ka-field__label">Alt Başlık / Açıklama</span><input class="ka-input" data-rs="subtitle" value="${esc(s.subtitle)}" placeholder="İsteğe bağlı"></label><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Başlık Hizası</span><select data-rs="titleAlign"><option value="left" ${s.titleAlign==='left'?'selected':''}>Sol</option><option value="center" ${s.titleAlign==='center'?'selected':''}>Orta</option><option value="right" ${s.titleAlign==='right'?'selected':''}>Sağ</option></select></label><label class="ka-field"><span class="ka-field__label">Sayfa</span><select data-rs="orientation"><option value="portrait" ${s.orientation==='portrait'?'selected':''}>Dikey A4</option><option value="landscape" ${s.orientation==='landscape'?'selected':''}>Yatay A4</option></select></label><label class="ka-field"><span class="ka-field__label">Yazı Boyutu</span><input class="ka-input" type="number" min="8" max="16" data-rs="fontSize" value="${s.fontSize}"></label></div></div></article>
<article class="ka-card"><div class="ka-card__body ka-stack"><h3>Raporda Görünecek Öğeler</h3><div class="ka-grid">${[['showLogo','Logo'],['showUpper','Üst başlık'],['showSchool','Okul adı'],['showTitle','Rapor başlığı'],['showDate','Tarih'],['showTime','Saat'],['showSummary','Özet kutuları'],['showTable','Veri tablosu']].map(([k,l])=>`<label><input type="checkbox" data-rflag="${k}" ${s[k]?'checked':''}> ${l}</label>`).join('')}</div><label class="ka-field"><span class="ka-field__label">Tarih / Saat Hizası</span><select data-rs="dateAlign"><option value="left" ${s.dateAlign==='left'?'selected':''}>Sol</option><option value="center" ${s.dateAlign==='center'?'selected':''}>Orta</option><option value="right" ${s.dateAlign==='right'?'selected':''}>Sağ</option></select></label></div></article>
<article class="ka-card"><div class="ka-card__body ka-stack"><h3>Sütunlar</h3><p class="ka-muted">Sütunları gizleyebilir, başlıklarını değiştirebilir ve her sütunun hizasını ayrı ayarlayabilirsiniz.</p>${s.columns.map((c,i)=>`<div class="ka-card"><div class="ka-card__body ka-grid"><label><input type="checkbox" data-col-show="${i}" ${c.show?'checked':''}> Göster</label><label class="ka-field"><span class="ka-field__label">Başlık</span><input class="ka-input" data-col-label="${i}" value="${esc(c.label)}"></label><label class="ka-field"><span class="ka-field__label">Hizalama</span><select data-col-align="${i}"><option value="left" ${c.align==='left'?'selected':''}>Sol</option><option value="center" ${c.align==='center'?'selected':''}>Orta</option><option value="right" ${c.align==='right'?'selected':''}>Sağ</option></select></label></div></div>`).join('')}</div></article>
<div class="ka-row"><button class="ka-btn ka-btn--secondary" data-report-reset>Varsayılana Dön</button><button class="ka-btn ka-btn--secondary ka-grow" data-report-preview-current>👁 Önizle</button><button class="ka-btn ka-grow" data-report-save>💾 Kaydet</button></div></section>`}
function studentRows(id){const stage=id==='primary-students'?'primary':id==='middle-students'?'middle':'all',classes=stage==='all'?[...classesFor('primary'),...classesFor('middle')]:classesFor(stage);return classes.map(s=>{const g=genderCounts(s);return{name:className(s),girls:g.kiz,boys:g.erkek,total:g.toplam}})}
function lessonRows(){const c=lessonCfg(),out=[];c.rows.forEach((r,i)=>{out.push({name:`${r.saat}. Ders`,start:r.baslangic||'—',end:r.bitis||'—',duration:duration(r.baslangic,r.bitis),kind:'lesson'});if(i<c.rows.length-1){const n=c.rows[i+1],l=c.ogleArasiVarMi!==false&&Number(c.ogleArasi?.sonrakiDers||0)===i+1,a=l?(c.ogleArasi?.baslangic||r.bitis):r.bitis,b=l?(c.ogleArasi?.bitis||n.baslangic):n.baslangic;if(a&&b)out.push({name:l?'Öğle Arası':'Teneffüs',start:a,end:b,duration:duration(a,b),kind:'break'})}});return out}
function reportData(id){return id==='lesson-times'?lessonRows():studentRows(id)}
function summary(id,rows){if(id==='lesson-times'){const lessons=rows.filter(x=>x.kind==='lesson'),first=lessons[0],last=lessons.at(-1);return[['İlk Ders',first?.start||'—'],['Son Ders Bitiş',last?.end||'—'],['Günlük Ders',lessons.length]]}return[['Kız Öğrenci',rows.reduce((a,x)=>a+Number(x.girls||0),0)],['Erkek Öğrenci',rows.reduce((a,x)=>a+Number(x.boys||0),0)],['Toplam Öğrenci',rows.reduce((a,x)=>a+Number(x.total||0),0)]]}
function build(id){const s=settings(id),rows=reportData(id),cols=s.columns.filter(c=>c.show),now=new Date(),date=now.toLocaleDateString('tr-TR'),time=now.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}),dt=[s.showDate?date:'',s.showTime?time:''].filter(Boolean).join(' · ');let body=`<div class="kr-custom-head" style="text-align:${s.titleAlign}">${s.showUpper?`<div class="kr-upper">${esc(s.upperTitle)}</div>`:''}${s.showSchool?`<div class="kr-school">${esc(s.schoolName)}</div>`:''}${s.showTitle?`<h2>${esc(s.title)}</h2>`:''}${s.subtitle?`<div class="kr-sub">${esc(s.subtitle)}</div>`:''}</div>${dt?`<div class="kr-datetime" style="text-align:${s.dateAlign}">${esc(dt)}</div>`:''}`;if(s.showSummary){body+=`<div class="kr-summary">${summary(id,rows).map(x=>`<div><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join('')}</div>`}if(s.showTable){body+=`<table><thead><tr>${cols.map(c=>`<th style="text-align:${c.align}">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td style="text-align:${c.align}">${esc(r[c.key]??'')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${Math.max(1,cols.length)}">Kayıtlı veri bulunamadı.</td></tr>`}</tbody></table>`}return{s,body}}
function style(s){return `<style>.ka-report-headcopy{display:${s.showLogo?'flex':'none'}!important}.kr-custom-head{margin:0 0 12px}.kr-upper{font-size:9pt;font-weight:700;letter-spacing:.08em}.kr-school{font-size:12pt;font-weight:800;margin-top:4px}.kr-custom-head h2{font-size:17pt;margin:5px 0}.kr-sub{font-size:10pt;color:#555}.kr-datetime{margin:8px 0 12px;font-size:9pt}.kr-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:0 0 14px}.kr-summary>div{border:1px solid #dbe8e2;background:#f4faf7;border-radius:8px;padding:9px;text-align:center}.kr-summary small{display:block}.kr-summary strong{display:block;font-size:15pt;margin-top:3px}table{font-size:${Number(s.fontSize)||10}pt}</style>`}
async function openReport(id,printNow=false){const {s,body}=build(id);if(!global.ReportEngine?.printReport)await global.AppLoader?.loadScript?.('js/modules/report-engine.js');if(!global.ReportEngine?.printReport)return global.toast?.('Rapor motoru yüklenemedi.');await global.ReportEngine.printReport('',body,{fileName:s.title||'Rapor',yon:s.orientation==='landscape'?'yatay':'dikey',logoGoster:!!s.showLogo,baslikGoster:false,tarihGoster:false,okulAdi:'',extraHead:style(s)});if(printNow)setTimeout(()=>document.querySelector('#kaReportPreview [data-report-print]')?.click(),120)}
function collectDesigner(){if(!editing||!root)return null;const s=settings(editing);root.querySelectorAll('[data-rs]').forEach(el=>s[el.dataset.rs]=el.type==='number'?Number(el.value):el.value);root.querySelectorAll('[data-rflag]').forEach(el=>s[el.dataset.rflag]=el.checked);root.querySelectorAll('[data-col-show]').forEach(el=>{if(s.columns[Number(el.dataset.colShow)])s.columns[Number(el.dataset.colShow)].show=el.checked});root.querySelectorAll('[data-col-label]').forEach(el=>{if(s.columns[Number(el.dataset.colLabel)])s.columns[Number(el.dataset.colLabel)].label=el.value});root.querySelectorAll('[data-col-align]').forEach(el=>{if(s.columns[Number(el.dataset.colAlign)])s.columns[Number(el.dataset.colAlign)].align=el.value});return s}
function bind(){root?.querySelectorAll('[data-report-design]').forEach(b=>b.onclick=()=>{editing=b.dataset.reportDesign;active='designer';render()});root?.querySelectorAll('[data-report-open]').forEach(b=>b.onclick=()=>openReport(b.dataset.reportOpen));root?.querySelectorAll('[data-report-print]').forEach(b=>b.onclick=()=>openReport(b.dataset.reportPrint,true));root?.querySelector('[data-report-back]')?.addEventListener('click',()=>{editing=null;active='home';render()});root?.querySelector('[data-report-save]')?.addEventListener('click',()=>{const s=collectDesigner();if(s){saveSettings(s);global.toast?.('Rapor ayarları kaydedildi.');editing=null;active='home';render()}});root?.querySelector('[data-report-preview-current]')?.addEventListener('click',()=>{const s=collectDesigner();if(s){saveSettings(s);openReport(s.id)}});root?.querySelector('[data-report-reset]')?.addEventListener('click',()=>{if(!editing)return;const all=saved();delete all[editing];localStorage.setItem(STORE,JSON.stringify(all));render()})}
function render(){root=document.getElementById('v2ModuleRoot');if(!root)return;root.innerHTML=active==='designer'&&editing?designer(editing):home();bind();global.PermissionService?.apply?.(root)}
function mount(page='home',target=document.getElementById('v2ModuleRoot')){active=page||'home';root=target;if(!root)return false;render();return true}
function unmount(){root=null;editing=null;active='home'}
function back(){if(active==='designer'){editing=null;active='home';render();return true}return false}
global.ReportsModule={mount,render,unmount,back,currentPage:()=>active,openReport};
global.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='reports')mount('home')});
})(window);
