/* Koruk Asistan — Raporlar
 * Uygulama verilerinden bağımsız rapor kartları, A4 önizleme ve yazdırma.
 */
(function(global){
'use strict';
if(global.ReportsModule)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
let active='home',root=null;
function school(){const x=arr('okulBilgileri').find(x=>x.id==='ayarlar')||arr('okulBilgileri')[0]||{};return x.okulAdi||x.ad||'Koruk İlkokulu - Ortaokulu'}
function classLevel(s){const m=String(s?.ad||s?.sinif||'').match(/(^|\D)([1-8])(?:\D|$)/);return m?Number(m[2]):0}
function className(s){return String(s?.ad||s?.sinif||'Sınıf').trim()}
function genderCounts(s){const students=arr('veliler').filter(v=>String(v.sinifId||'')===String(s.id||''));if(students.length){let kiz=0,erkek=0;students.forEach(v=>{const c=String(v.cinsiyet||'').toLocaleLowerCase('tr-TR');if(c.includes('kız')||c.includes('kiz'))kiz++;else if(c.includes('erkek'))erkek++});return{kiz,erkek,toplam:students.length}}const kiz=Number(s.kizSayisi||0),erkek=Number(s.erkekSayisi||0),toplam=Number(s.ogrenciSayisi||kiz+erkek);return{kiz,erkek,toplam}}
function classesFor(stage){return arr('siniflar').filter(s=>{const l=classLevel(s);return stage==='primary'?l>=1&&l<=4:l>=5&&l<=8}).sort((a,b)=>classLevel(a)-classLevel(b)||className(a).localeCompare(className(b),'tr'))}
function lessonCfg(){const x=arr('dersSaatleri').find(x=>x.id==='ayarlar')||arr('dersSaatleri')[0]||{},rows=Array.isArray(x.donemler)&&x.donemler.length?x.donemler:(Array.isArray(x.dersler)?x.dersler:[]);return{...x,rows:rows.map((r,i)=>({saat:Number(r.saat||i+1),baslangic:String(r.baslangic||''),bitis:String(r.bitis||'')}))}}
function minutes(v){const m=/^(\d{1,2}):(\d{2})$/.exec(String(v||''));return m?Number(m[1])*60+Number(m[2]):NaN}
function duration(a,b){const n=minutes(b)-minutes(a);return Number.isFinite(n)&&n>=0?`${n} dk`:'—'}
function reportDefs(){const p=classesFor('primary'),m=classesFor('middle');return[
 {id:'lesson-times',icon:'🕘',tone:'blue',title:'Ders Giriş - Çıkış Saatleri',desc:'Ders başlangıç, bitiş ve teneffüs süreleri',meta:`${lessonCfg().rows.length||0} ders saati`},
 {id:'primary-students',icon:'🏫',tone:'green',title:'İlkokul Öğrenci Sayıları',desc:'Sınıf bazlı kız, erkek ve toplam öğrenci sayıları',meta:`${p.length} sınıf`},
 {id:'middle-students',icon:'🎓',tone:'violet',title:'Ortaokul Öğrenci Sayıları',desc:'Sınıf bazlı kız, erkek ve toplam öğrenci sayıları',meta:`${m.length} sınıf`},
 {id:'all-students',icon:'👥',tone:'rose',title:'Okul Geneli Öğrenci Sayıları',desc:'İlkokul ve ortaokul sınıflarının toplu dağılımı',meta:`${p.length+m.length} sınıf`}
]}
function home(){const defs=reportDefs();return `<section class="ka-page ka-stack" data-reports-module><article class="ka-card"><div class="ka-card__body ka-stack"><small>OKUL YÖNETİMİ</small><h2>Raporlar</h2><p class="ka-muted">Uygulamadaki güncel verilerden oluşturulan raporları ayrı ayrı önizleyin ve yazdırın.</p></div></article><div class="ka-grid ka-report-hub-grid">${defs.map(r=>`<article class="ka-card ka-report-hub-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><span class="ka-report-hub-icon" data-tone="${r.tone}">${r.icon}</span><span class="ka-badge">${esc(r.meta)}</span></div><div><h3>${esc(r.title)}</h3><p class="ka-muted">${esc(r.desc)}</p></div><div class="ka-row"><button class="ka-btn ka-btn--secondary ka-grow" type="button" data-report-open="${r.id}">👁 Önizle</button><button class="ka-btn ka-grow" type="button" data-report-print="${r.id}">🖨 Yazdır</button></div></div></article>`).join('')}</div></section>`}
function summaryCards(rows){const t=rows.reduce((a,x)=>({kiz:a.kiz+x.kiz,erkek:a.erkek+x.erkek,toplam:a.toplam+x.toplam}),{kiz:0,erkek:0,toplam:0});return `<div class="ka-report-summary"><div><small>Kız Öğrenci</small><strong>${t.kiz}</strong></div><div><small>Erkek Öğrenci</small><strong>${t.erkek}</strong></div><div><small>Toplam Öğrenci</small><strong>${t.toplam}</strong></div></div>`}
function studentBody(stage){const classes=stage==='all'?[...classesFor('primary'),...classesFor('middle')]:classesFor(stage),rows=classes.map(s=>({ad:className(s),level:classLevel(s),...genderCounts(s)})),title=stage==='primary'?'İlkokul Sınıf Bazlı Öğrenci Sayıları':stage==='middle'?'Ortaokul Sınıf Bazlı Öğrenci Sayıları':'Okul Geneli Sınıf Bazlı Öğrenci Sayıları';return{title,body:`${summaryCards(rows)}<table><thead><tr><th>Sınıf</th><th>Kız Öğrenci</th><th>Erkek Öğrenci</th><th>Toplam</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td><strong>${esc(x.ad)}</strong></td><td>${x.kiz}</td><td>${x.erkek}</td><td><strong>${x.toplam}</strong></td></tr>`).join(''):'<tr><td colspan="4">Kayıtlı sınıf verisi bulunamadı.</td></tr>'}</tbody></table>`}}
function lessonBody(){const c=lessonCfg(),rows=c.rows,items=[];rows.forEach((r,i)=>{items.push(`<tr><td><strong>${r.saat}. Ders</strong></td><td>${esc(r.baslangic||'—')}</td><td>${esc(r.bitis||'—')}</td><td>${duration(r.baslangic,r.bitis)}</td></tr>`);if(i<rows.length-1){const next=rows[i+1],isLunch=c.ogleArasiVarMi!==false&&Number(c.ogleArasi?.sonrakiDers||0)===i+1,a=isLunch?(c.ogleArasi?.baslangic||r.bitis):r.bitis,b=isLunch?(c.ogleArasi?.bitis||next.baslangic):next.baslangic;if(a&&b)items.push(`<tr class="ka-report-break"><td>${isLunch?'Öğle Arası':'Teneffüs'}</td><td>${esc(a)}</td><td>${esc(b)}</td><td>${duration(a,b)}</td></tr>`)}});const first=rows[0],last=rows.at(-1);return{title:'Ders Giriş - Çıkış Saatleri',body:`<div class="ka-report-summary"><div><small>İlk Ders</small><strong>${esc(first?.baslangic||'—')}</strong></div><div><small>Son Ders Bitiş</small><strong>${esc(last?.bitis||'—')}</strong></div><div><small>Günlük Ders</small><strong>${rows.length}</strong></div></div><table><thead><tr><th>Ders / Ara</th><th>Başlangıç</th><th>Bitiş</th><th>Süre</th></tr></thead><tbody>${items.length?items.join(''):'<tr><td colspan="4">Ders saatleri henüz tanımlanmamış.</td></tr>'}</tbody></table>`}}
function payload(id){if(id==='lesson-times')return lessonBody();if(id==='primary-students')return studentBody('primary');if(id==='middle-students')return studentBody('middle');return studentBody('all')}
const reportStyle='<style>.ka-report-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:0 0 12px}.ka-report-summary>div{border:1px solid #dbe8e2;background:#f4faf7;border-radius:8px;padding:10px;text-align:center}.ka-report-summary small{display:block;color:#65766f;font-weight:700}.ka-report-summary strong{display:block;margin-top:3px;font-size:16pt;color:#17684f}.ka-report-break td{background:#fff7e6!important;color:#7a5200!important;font-weight:700}</style>';
async function openReport(id,printNow=false){const p=payload(id);if(!global.ReportEngine?.printReport)await global.AppLoader?.loadScript?.('js/modules/report-engine.js');if(!global.ReportEngine?.printReport)return global.toast?.('Rapor motoru yüklenemedi.');const opts={fileName:p.title,yon:'dikey',logoGoster:true,baslikGoster:true,tarihGoster:true,ustBaslik:'OKUL YÖNETİM RAPORU',okulAdi:school(),extraHead:reportStyle};await global.ReportEngine.printReport(p.title,p.body,opts);if(printNow)setTimeout(()=>document.querySelector('#kaReportPreview [data-report-print]')?.click(),120)}
function bind(){root?.querySelectorAll('[data-report-open]').forEach(b=>b.onclick=()=>openReport(b.dataset.reportOpen,false));root?.querySelectorAll('[data-report-print]').forEach(b=>b.onclick=()=>openReport(b.dataset.reportPrint,true))}
function render(){root=document.getElementById('v2ModuleRoot');if(!root)return;root.innerHTML=home();bind();global.PermissionService?.apply?.(root)}
function mount(page='home'){active=page||'home';render();return true}
function unmount(){root=null}
function back(){return false}
global.ReportsModule={mount,render,unmount,back,currentPage:()=>active,openReport};
})(window);
