/* Koruk Asistan — Merkezi Rapor + PDF Motoru
 * Tek sahip: A4 rapor önizleme/yazdırma + PDF birleştirme + resimlerden PDF.
 * Uygulama görünümü css/design-system.css üzerinden gelir; yeni stil/yama dosyası yoktur.
 */
(function(global){
'use strict';
if(global.ReportEngine)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PX_PER_MM=96/25.4;
const JSPDF_SRC='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
const PDFLIB_SRC='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';
let pdfObjectUrl=null,pdfToolsBlob=null,pdfToolsName='Koruk_Belge.pdf';
function fileName(v){return String(v||'Koruk_Rapor').replace(/[^\w\sÇĞİÖŞÜçğıöşü-]/g,'').trim().replace(/\s+/g,'_')||'Koruk_Rapor';}
function pdfFileName(v,def='Koruk_Belge'){let s=String(v||def).trim().replace(/[\u0000-\u001f<>:"/\\|?*]+/g,'-').replace(/\s+/g,' ').replace(/[. ]+$/g,'');if(!s)s=def;if(!/\.pdf$/i.test(s))s+='.pdf';return s;}
function styleUrl(){try{return new URL('css/design-system.css',global.location.href).href}catch(_){return'css/design-system.css'}}
function logoUrl(){try{return new URL('assets/logo.png',global.location.href).href}catch(_){return'assets/logo.png'}}
function schoolInfo(){const rows=global.AppStore?.data?.('okulBilgileri'),list=Array.isArray(rows)?rows:[],x=list.find(r=>r.id==='ayarlar')||list[0]||global.okulBilgileriAyari||{};return{okulAdi:x.okulAdi||x.ad||'Koruk İlkokulu - Ortaokulu',mudurluk:x.mudurluk||x.ilce||''};}
function normalizeOptions(opts={}){return{yon:opts.yon==='yatay'?'yatay':'dikey',logoGoster:opts.logoGoster!==false,tarihGoster:opts.tarihGoster!==false,baslikGoster:opts.baslikGoster!==false,ustBaslik:opts.ustBaslik||'',okulAdi:opts.okulAdi||schoolInfo().okulAdi,kenarBosluk:Number.isFinite(Number(opts.kenarBosluk))?Math.max(3,Math.min(20,Number(opts.kenarBosluk))):8,fontSize:Number.isFinite(Number(opts.fontSize))?Math.max(7,Math.min(14,Number(opts.fontSize))):9.5,compact:opts.compact===true,extraHead:opts.extraHead||''};}
function headerHtml(title,o){if(!o.baslikGoster&&!o.logoGoster&&!o.ustBaslik)return'';const tarih=new Date().toLocaleDateString('tr-TR',{day:'2-digit',month:'long',year:'numeric'});return `<header class="ka-report-head">${o.logoGoster?`<img class="ka-report-logo" src="${esc(logoUrl())}" alt="">`:''}<div class="ka-report-headcopy">${o.ustBaslik?`<small>${esc(o.ustBaslik)}</small>`:''}<strong>${esc(title||'Rapor')}</strong><span>${esc(o.okulAdi)}</span>${o.tarihGoster?`<time>${esc(tarih)}</time>`:''}</div></header>`;}
function documentHtml(title,body,opts={}){const o=normalizeOptions(opts),page=o.yon==='yatay'?'A4 landscape':'A4 portrait',w=o.yon==='yatay'?'297mm':'210mm',h=o.yon==='yatay'?'210mm':'297mm';return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title||'Rapor')}</title><link rel="stylesheet" href="${esc(styleUrl())}"><style>@page{size:${page};margin:0}html,body{margin:0;padding:0;background:#fff!important;color:#111;-webkit-print-color-adjust:exact;print-color-adjust:exact}body{width:${w};min-height:${h}}.ka-report{width:${w}!important;min-height:${h}!important;margin:0!important;padding:${o.kenarBosluk}mm!important;box-shadow:none!important;font-size:${o.fontSize}pt!important;overflow:visible!important}.ka-report-head{display:grid;grid-template-columns:${o.logoGoster?'48px 1fr':'1fr'};align-items:center;gap:10px;padding-bottom:7px;margin-bottom:8px;border-bottom:1.6px solid #17684f}.ka-report-logo{width:46px;height:46px;object-fit:contain}.ka-report-headcopy{display:flex;flex-direction:column;min-width:0}.ka-report-headcopy small{font-size:7.5pt;font-weight:700;color:#65766f;text-transform:uppercase;letter-spacing:.04em}.ka-report-headcopy strong{font-size:14pt;line-height:1.15;color:#17684f}.ka-report-headcopy span{margin-top:2px;font-size:8.5pt;font-weight:700;color:#384b43}.ka-report-headcopy time{margin-top:2px;font-size:7pt;color:#78857f}.ka-report table{width:100%!important;border-collapse:collapse!important;border-spacing:0!important;page-break-inside:auto}.ka-report thead{display:table-header-group}.ka-report tr{break-inside:avoid;page-break-inside:avoid}.ka-report th{padding:${o.compact?'3px 3px':'5px 4px'}!important;border:1px solid #397461!important;background:#17684f!important;color:#fff!important;font-size:${o.compact?'7pt':'8pt'}!important;font-weight:800!important;text-align:center!important;line-height:1.15}.ka-report td{padding:${o.compact?'3px 3px':'5px 4px'}!important;border:1px solid #d5ded9!important;background:#fff!important;color:#17221e!important;font-size:${o.compact?'7pt':'8.5pt'}!important;vertical-align:middle!important;line-height:1.18}.ka-report tbody tr:nth-child(even) td{background:#f7faf8!important}.ka-report .bolum-baslik{margin:9px 0 5px!important;padding:5px 7px!important;border-left:3px solid #17684f!important;background:#eaf4ef!important;color:#17684f!important;font-weight:800!important}.ka-report .sayfa-sonu{break-before:page;page-break-before:always}@media print{html,body{width:auto!important;height:auto!important}.ka-report{box-shadow:none!important}tr{break-inside:avoid;page-break-inside:avoid}}</style>${o.extraHead}</head><body><main class="ka-report">${headerHtml(title,o)}<section class="ka-report-content">${body}</section></main></body></html>`;}
function nativePlugin(){try{return global.Capacitor?.isNativePlatform?.()&&global.Capacitor?.Plugins?.PrintPlugin}catch(_){return null}}
async function printHtml(html,name='Koruk_Rapor',yon='dikey'){const plugin=nativePlugin();if(plugin?.yazdir)return plugin.yazdir({html,isAdi:fileName(name),yon:yon==='yatay'?'yatay':'dikey'});return new Promise((resolve,reject)=>{const f=document.createElement('iframe');f.setAttribute('aria-hidden','true');f.style.cssText='position:fixed;right:0;bottom:0;width:1px;height:1px;border:0;opacity:0;pointer-events:none';document.body.appendChild(f);let done=false;const clean=()=>{if(done)return;done=true;setTimeout(()=>f.remove(),600)};f.onload=()=>setTimeout(()=>{try{f.contentWindow?.focus();f.contentWindow?.print();resolve({web:true});}catch(e){reject(e)}finally{clean()}},160);f.srcdoc=html;setTimeout(()=>{if(!done){clean();reject(new Error('Yazdırma önizlemesi açılamadı.'));}},15000);});}
function pagePx(yon){return yon==='yatay'?{w:297*PX_PER_MM,h:210*PX_PER_MM}:{w:210*PX_PER_MM,h:297*PX_PER_MM};}
function closePreview(){document.getElementById('kaReportPreview')?.remove();global.KorukPlatformAdapter?.setPullToRefreshEnabled?.(true).catch?.(()=>{});}
function previewHtml(html,{title='Rapor Önizleme',fileName:name=title,yon='dikey'}={}){closePreview();global.KorukPlatformAdapter?.setPullToRefreshEnabled?.(false).catch?.(()=>{});const safeYon=yon==='yatay'?'yatay':'dikey',page=pagePx(safeYon),ov=document.createElement('div');ov.id='kaReportPreview';ov.className='dv3';ov.innerHTML=`<header class="dv3h"><button class="dv3btn" data-report-close type="button">✕ Kapat</button><div class="dv3title"><b>${esc(title)}</b><small>${safeYon==='yatay'?'Yatay':'Dikey'} A4 önizleme</small></div><button class="dv3btn" data-report-minus type="button">−</button><span class="dv3pdfpageinfo" data-report-zoom>100%</span><button class="dv3btn" data-report-plus type="button">+</button><button class="dv3btn dv3hide" data-report-fit type="button">Sığdır</button><button class="dv3btn dv3hide" data-report-100 type="button">%100</button><button class="dv3btn primary" data-report-print type="button">🖨 Yazdır / PDF</button></header><div class="dv3body dv3pdfbody"><div class="dv3pdfviewport" data-report-viewport><div class="dv3pdfscene" data-report-scene><iframe id="kaReportFrame" class="dv3frame dv3pdfstage" title="${esc(title)}"></iframe></div></div></div>`;document.body.appendChild(ov);const frame=ov.querySelector('#kaReportFrame'),viewport=ov.querySelector('[data-report-viewport]'),scene=ov.querySelector('[data-report-scene]'),label=ov.querySelector('[data-report-zoom]');let scale=1,contentH=page.h;
function apply(){scale=Math.max(.25,Math.min(2.5,scale));frame.style.width=page.w+'px';frame.style.height=contentH+'px';frame.style.transform=`scale(${scale})`;scene.style.width=Math.ceil(page.w*scale)+'px';scene.style.height=Math.ceil(contentH*scale)+'px';label.textContent=Math.round(scale*100)+'%';}
function fit(){const available=Math.max(240,viewport.clientWidth-12);scale=Math.min(1,available/page.w);apply();viewport.scrollTo({left:0,top:0});}
function zoom(d){scale+=d;apply();}
frame.onload=()=>{try{const doc=frame.contentDocument;contentH=Math.max(page.h,doc?.documentElement?.scrollHeight||0,doc?.body?.scrollHeight||0);}catch(_){}apply();requestAnimationFrame(fit);};frame.srcdoc=html;ov.querySelector('[data-report-close]').onclick=closePreview;ov.querySelector('[data-report-minus]').onclick=()=>zoom(-.1);ov.querySelector('[data-report-plus]').onclick=()=>zoom(.1);ov.querySelector('[data-report-fit]').onclick=fit;ov.querySelector('[data-report-100]').onclick=()=>{scale=1;apply();viewport.scrollTo({left:0,top:0})};ov.querySelector('[data-report-print]').onclick=async()=>{const b=ov.querySelector('[data-report-print]'),old=b.textContent;b.disabled=true;b.textContent='Hazırlanıyor…';try{await printHtml(html,name,safeYon);}catch(e){global.toast?.('Yazdırma açılamadı: '+(e?.message||e));}finally{b.disabled=false;b.textContent=old;}};return ov;}
async function printReport(title,body,opts={}){const o=normalizeOptions(opts),html=documentHtml(title,body,o);return previewHtml(html,{title,fileName:opts.fileName||title,yon:o.yon});}

/* ========================= PDF ARAÇLARI ========================= */
async function ensureExternal(src,test){if(test())return true;if(!global.AppLoader?.loadScript)throw new Error('Kütüphane yükleyicisi hazır değil.');await global.AppLoader.loadScript(src);if(!test())throw new Error('PDF kütüphanesi yüklenemedi.');return true;}
const ensureJsPdf=()=>ensureExternal(JSPDF_SRC,()=>!!global.jspdf?.jsPDF);
const ensurePdfLib=()=>ensureExternal(PDFLIB_SRC,()=>!!global.PDFLib?.PDFDocument);
function imageElement(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Görsel açılamadı.'));img.src=src;});}
function fileDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error||new Error('Dosya okunamadı.'));r.readAsDataURL(file);});}
async function normalizedImage(file,{maxLongSide=2400,quality=.88}={}){const src=await fileDataUrl(file),img=await imageElement(src),iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;if(!iw||!ih)throw new Error(`“${file?.name||'Görsel'}” boyutu okunamadı.`);const ratio=Math.min(1,Number(maxLongSide||2400)/Math.max(iw,ih)),w=Math.max(1,Math.round(iw*ratio)),h=Math.max(1,Math.round(ih*ratio)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);return{dataUrl:canvas.toDataURL('image/jpeg',Number(quality)||.88),w,h};}
async function imagesToPdf(files,opts={}){const list=Array.from(files||[]).filter(Boolean);if(!list.length)throw new Error('Önce resim seçin.');await ensureJsPdf();const {jsPDF}=global.jspdf,margin=Number.isFinite(Number(opts.margin))?Number(opts.margin):7,orientation=opts.orientation||'auto';let pdf=null;for(let i=0;i<list.length;i++){const im=await normalizedImage(list[i],opts),landscape=orientation==='landscape'||(orientation==='auto'&&im.w>im.h),pageW=landscape?297:210,pageH=landscape?210:297;if(!pdf)pdf=new jsPDF({unit:'mm',format:'a4',orientation:landscape?'l':'p',compress:true,putOnlyUsedFonts:true});else pdf.addPage('a4',landscape?'l':'p');const ratio=Math.min((pageW-margin*2)/im.w,(pageH-margin*2)/im.h),w=im.w*ratio,h=im.h*ratio;pdf.addImage(im.dataUrl,'JPEG',(pageW-w)/2,(pageH-h)/2,w,h,undefined,'FAST');await new Promise(r=>setTimeout(r,0));}return pdf.output('blob');}
async function mergePdfs(files){const list=Array.from(files||[]).filter(Boolean);if(!list.length)throw new Error('Önce PDF seçin.');await ensurePdfLib();const {PDFDocument}=global.PDFLib,target=await PDFDocument.create();let pages=0;for(const file of list){let source;try{source=await PDFDocument.load(new Uint8Array(await file.arrayBuffer()),{ignoreEncryption:false,updateMetadata:false});}catch(e){if(/encrypt|password/i.test(String(e?.message||'')))throw new Error(`“${file.name}” şifreli; şifreli PDF birleştirilemez.`);throw new Error(`“${file.name}” açılamadı: ${e?.message||e}`);}const copied=await target.copyPages(source,source.getPageIndices());copied.forEach(p=>target.addPage(p));pages+=copied.length;await new Promise(r=>setTimeout(r,0));}if(!pages)throw new Error('Birleştirilecek sayfa bulunamadı.');const bytes=await target.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:30});return new Blob([bytes],{type:'application/pdf'});}
function revokePdfUrl(){if(!pdfObjectUrl)return;try{URL.revokeObjectURL(pdfObjectUrl)}catch(_){}pdfObjectUrl=null;}
function closePdfPreview(){document.getElementById('kaPdfPreview')?.remove();revokePdfUrl();global.KorukPlatformAdapter?.setPullToRefreshEnabled?.(true).catch?.(()=>{});}
function previewPdfBlob(blob,{title='PDF Önizleme',fileName:name='Koruk_Belge.pdf'}={}){if(!(blob instanceof Blob))throw new Error('PDF verisi bulunamadı.');closePdfPreview();global.KorukPlatformAdapter?.setPullToRefreshEnabled?.(false).catch?.(()=>{});pdfObjectUrl=URL.createObjectURL(blob);const ov=document.createElement('div');ov.id='kaPdfPreview';ov.className='dv3';ov.innerHTML=`<header class="dv3h"><button class="dv3btn" data-pdf-close type="button">✕ Kapat</button><div class="dv3title"><b>${esc(title)}</b><small>${esc(pdfFileName(name))}</small></div><button class="dv3btn" data-pdf-save type="button">⬇ Kaydet</button><button class="dv3btn primary" data-pdf-share type="button">↗ Paylaş</button></header><div class="dv3body dv3pdfbody"><iframe class="dv3frame" data-pdf-frame title="${esc(title)}" src="${esc(pdfObjectUrl)}"></iframe></div>`;document.body.appendChild(ov);ov.querySelector('[data-pdf-close]').onclick=closePdfPreview;ov.querySelector('[data-pdf-save]').onclick=()=>savePdfBlob(blob,name,false);ov.querySelector('[data-pdf-share]').onclick=()=>savePdfBlob(blob,name,true);return ov;}
function blobBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||'').split(',')[1]||'');r.onerror=()=>reject(r.error||new Error('Dosya okunamadı.'));r.readAsDataURL(blob);});}
async function savePdfBlob(blob,name='Koruk_Belge.pdf',share=false){const safe=pdfFileName(name);if(typeof global.uygulamaDosyaKaydet==='function'){const b64=await blobBase64(blob);return global.uygulamaDosyaKaydet(b64,safe,'application/pdf',!!share);}if(share&&navigator.share&&typeof File==='function'){try{return await navigator.share({files:[new File([blob],safe,{type:'application/pdf'})],title:safe})}catch(e){if(e?.name!=='AbortError')console.warn('[ReportEngine/share]',e)}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safe;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);return{web:true};}
async function archivePdf(blob,{title='PDF Belgesi',category='Diğer',description='',visibility='kisisel'}={}){if(!global.DokumanlarService?.dokumanEkle)throw new Error('Döküman arşivi hazır değil.');const name=pdfFileName(title,'PDF Belgesi'),file=new File([blob],name,{type:'application/pdf',lastModified:Date.now()});return global.DokumanlarService.dokumanEkle({ad:String(title||'PDF Belgesi').replace(/\.pdf$/i,''),kategori:category,aciklama:description,gorunurluk:visibility},file);}
function closePdfTools(){document.getElementById('kaPdfTools')?.remove();}
function pdfToolResult(root,blob,name,message){pdfToolsBlob=blob;pdfToolsName=pdfFileName(name);const out=root.querySelector('[data-pdf-result]');if(out)out.innerHTML=`<article class="ka-card"><div class="ka-card__body ka-stack"><strong>✅ ${esc(message)}</strong><span class="ka-muted">${esc(pdfToolsName)} · ${Math.max(1,Math.round(blob.size/1024))} KB</span><div class="ka-row ka-wrap"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-result-preview>👁 Önizle</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-result-save>⬇ Kaydet</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-result-share>↗ Paylaş</button>${global.DokumanlarService?.dokumanEkle?'<button class="ka-btn ka-btn--sm" type="button" data-result-archive>☁ Dökümanlara Kaydet</button>':''}</div></div></article>`;out?.querySelector('[data-result-preview]')?.addEventListener('click',()=>previewPdfBlob(blob,{title:'PDF Önizleme',fileName:pdfToolsName}));out?.querySelector('[data-result-save]')?.addEventListener('click',()=>savePdfBlob(blob,pdfToolsName,false));out?.querySelector('[data-result-share]')?.addEventListener('click',()=>savePdfBlob(blob,pdfToolsName,true));out?.querySelector('[data-result-archive]')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{await archivePdf(blob,{title:pdfToolsName});b.textContent='✅ Kaydedildi';global.toast?.('PDF Dökümanlar arşivine kaydedildi.')}catch(err){b.disabled=false;global.toast?.('Dökümanlara kaydedilemedi: '+(err?.message||err))}});}
function pdfToolsBody(mode){return `<section class="ka-stack"><div class="ka-tabs"><button class="ka-btn ka-btn--sm ${mode==='images'?'':'ka-btn--secondary'}" type="button" data-pdf-mode="images">🖼 Resimden PDF</button><button class="ka-btn ka-btn--sm ${mode==='merge'?'':'ka-btn--secondary'}" type="button" data-pdf-mode="merge">🔗 PDF Birleştir</button></div>${mode==='merge'?`<label class="ka-field"><span class="ka-field__label">PDF Dosyaları</span><input type="file" accept="application/pdf,.pdf" multiple data-pdf-files></label><label class="ka-field"><span class="ka-field__label">Dosya Adı</span><input value="Birleştirilmiş PDF" data-pdf-name></label><p class="ka-muted">Sayfalar pdf-lib ile kopyalanır; metin ve vektör yapısı korunur. Şifreli PDF birleştirilmez.</p><button class="ka-btn" type="button" data-pdf-run>PDF'leri Birleştir</button>`:`<label class="ka-field"><span class="ka-field__label">Resimler</span><input type="file" accept="image/*" multiple data-pdf-files></label><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Sayfa Yönü</span><select data-pdf-orientation><option value="auto">Otomatik</option><option value="portrait">Dikey</option><option value="landscape">Yatay</option></select></label><label class="ka-field"><span class="ka-field__label">Dosya Adı</span><input value="Taranan Belge" data-pdf-name></label></div><p class="ka-muted">Her görsel A4 sayfaya orantılı yerleştirilir; görüntü yönüne göre sayfa otomatik dönebilir.</p><button class="ka-btn" type="button" data-pdf-run>PDF Oluştur</button>`}<div data-pdf-progress class="ka-muted"></div><div data-pdf-result></div></section>`;}
function renderPdfTools(root,mode){root.dataset.mode=mode;root.querySelector('[data-pdf-body]').innerHTML=pdfToolsBody(mode);root.querySelectorAll('[data-pdf-mode]').forEach(b=>b.onclick=()=>renderPdfTools(root,b.dataset.pdfMode));root.querySelector('[data-pdf-run]')?.addEventListener('click',async e=>{const b=e.currentTarget,files=Array.from(root.querySelector('[data-pdf-files]')?.files||[]),progress=root.querySelector('[data-pdf-progress]'),name=root.querySelector('[data-pdf-name]')?.value||'Koruk Belge';if(!files.length)return global.toast?.(mode==='merge'?'Önce PDF seçin.':'Önce resim seçin.');b.disabled=true;progress.textContent='Hazırlanıyor…';try{const blob=mode==='merge'?await mergePdfs(files):await imagesToPdf(files,{orientation:root.querySelector('[data-pdf-orientation]')?.value||'auto'});pdfToolResult(root,blob,name,mode==='merge'?`${files.length} PDF birleştirildi.`:`${files.length} görsel PDF'e dönüştürüldü.`);progress.textContent='';}catch(err){progress.textContent='❌ '+(err?.message||err);global.toast?.('PDF işlemi başarısız: '+(err?.message||err));}finally{b.disabled=false;}});}
function openPdfTools(mode='images'){closePdfTools();const ov=document.createElement('div');ov.id='kaPdfTools';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal" role="dialog" aria-modal="true" aria-label="PDF İşlemleri"><div class="ka-modal__header"><div><h2>PDF İşlemleri</h2><p class="ka-muted">Resimlerden PDF oluşturun veya PDF dosyalarını birleştirin.</p></div><button class="ka-icon-button" type="button" data-pdf-tools-close aria-label="Kapat">×</button></div><div class="ka-modal__body" data-pdf-body></div></section>`;document.body.appendChild(ov);ov.querySelector('[data-pdf-tools-close]').onclick=closePdfTools;ov.addEventListener('click',e=>{if(e.target===ov)closePdfTools()});renderPdfTools(ov,mode==='merge'?'merge':'images');return ov;}

global.ReportEngine={esc,fileName,pdfFileName,styleUrl,logoUrl,schoolInfo,normalizeOptions,documentHtml,printHtml,previewHtml,closePreview,printReport,imagesToPdf,mergePdfs,previewPdfBlob,closePdfPreview,savePdfBlob,archivePdf,openPdfTools,closePdfTools,get preparedPdf(){return pdfToolsBlob},get preparedPdfName(){return pdfToolsName}};
global.uygulamaHtmlYazdir=(html,dosyaAdi,yon)=>previewHtml(html,{title:dosyaAdi||'Rapor Önizleme',fileName:dosyaAdi||'Koruk_Rapor',yon:yon||'dikey'});
})(window);
