/* Koruk Asistan v2 — Settings UI
   Hesap + senkron durumu + admin kullanıcı/rol/depolama ayarları.
   Rol yetkileri PermissionService kataloğundan yönetilir.
   UI Firestore'a doğrudan erişmez. */
(function(){
'use strict';if(window.SettingsModule)return;
let active='account',mounted=false,unsubs=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const admin=()=>window.AKTIF_KULLANICI?.admin===true;
async function prepareLocal(){if(!admin()||!window.SyncEngine||!window.COL)return;const defs={roller:COL.roller,kullanicilar:COL.kullanicilar,depolamaAyarlari:COL.depolamaAyarlari},types=[];Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(120)}}
function shell(){const adminTabs=admin()?'<button class="ka-tab" data-settings-tab="users" data-ka-permission="settings.users" data-ka-min-level="preview">Kullanıcılar</button><button class="ka-tab" data-settings-tab="roles" data-ka-permission="settings.roles" data-ka-min-level="preview">Roller</button><button class="ka-tab" data-settings-tab="storage">Depolama</button>':'';return `<section class="ka-stack" data-settings-module><div><h2>Ayarlar</h2><p class="ka-muted">Uygulama, hesap, rol ve senkronizasyon ayarları tek noktada.</p></div><div class="ka-tabs"><button class="ka-tab" data-settings-tab="account">Hesabım</button><button class="ka-tab" data-settings-tab="sync">Senkronizasyon</button>${adminTabs}</div><div id="settingsContent" class="ka-stack"></div></section>`}
function account(){const u=window.AKTIF_KULLANICI||AppStore?.get?.('session.user')||{},role=window.AKTIF_ROL||AppStore?.get?.('session.role');return `<article class="ka-card"><div class="ka-card__body ka-stack"><strong>${esc(u.adSoyad||u.ad||u.displayName||u.email||'Kullanıcı')}</strong><div class="ka-muted">${esc(role?.ad||role?.rolAdi|| (u.admin?'Yönetici':'Kullanıcı'))}</div><div class="ka-row"><span class="ka-badge">${navigator.onLine?'Çevrimiçi':'Çevrimdışı'}</span><span class="ka-badge">${u.admin?'Yönetici':'Standart hesap'}</span></div></div></article>`}
function sync(){const s=AppStore?.state?.ui||{},hydrated=!!AppStore?.state?.meta?.hydrated;return `<article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>Cihaz verisi</strong><span class="ka-badge">${hydrated?'Hazır':'Hazırlanıyor'}</span></div><div class="ka-row ka-row--between"><span>Bekleyen işlemler</span><strong>${Number(s.pendingWrites||0)}</strong></div><div class="ka-row ka-row--between"><span>Arka plan senkronu</span><strong>${s.syncing?'Çalışıyor':'Hazır'}</strong></div><div class="ka-row ka-row--between"><span>Son senkron</span><strong>${s.lastSyncAt?new Date(s.lastSyncAt).toLocaleString('tr-TR'):'—'}</strong></div></div></article>`}
function users(){const list=arr('kullanicilar');return list.length?list.map(u=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(u.adSoyad||u.ad||u.displayName||u.email||u.id||'Kullanıcı')}</strong><div class="ka-muted">${esc(u.email||u.kullaniciAdi||'')} ${u.aktif===false?'· Pasif':'· Aktif'}</div></div><span class="ka-badge">${u.admin?'Admin':esc(u.rolAdi||'Kullanıcı')}</span></div></article>`).join(''):'<div class="ka-empty">Kullanıcı verisi bulunamadı.</div>'}
function explicitPermissionCount(role){const y=role?.yetkiler;return y&&typeof y==='object'?Object.keys(y).length:0}
function roles(){const list=arr('roller');return list.length?list.map(r=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(r.ad||r.rolAdi||'Rol')}</strong><div class="ka-muted">${esc(r.aciklama||'')} · ${explicitPermissionCount(r)} özel kural</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-role-permissions="${esc(r.id)}" data-ka-permission="settings.roles.edit" data-ka-min-level="edit" data-ka-write="settings.roles.edit">Yetkileri Düzenle</button></div></article>`).join(''):'<div class="ka-empty">Rol verisi bulunamadı.</div>'}
function storage(){const doc=arr('depolamaAyarlari').find(x=>x.id==='ayarlar')||arr('depolamaAyarlari')[0];if(!doc)return'<div class="ka-empty">Depolama ayarları bulunamadı.</div>';return `<article class="ka-card"><div class="ka-card__body ka-stack">${['mesaj','duyuru','dokuman','takvim'].map(k=>{const a=doc[k]||{};return `<div class="ka-row ka-row--between"><span>${esc(k)}</span><strong>${a.aktif===false?'Kapalı':esc((a.MB??100)+' MB')}</strong></div>`}).join('')}</div></article>`}
function rawPermission(role,key){const y=role?.yetkiler||{};if(Object.prototype.hasOwnProperty.call(y,key))return window.PermissionService?.normalize?.(y[key])||'';return''}
function permissionOptions(selected){const rows=[['','Varsayılan / Üst kural'],['hidden','Gizli'],['preview','Önizleme'],['read','Salt okunur'],['edit','Düzenleme']];return rows.map(([v,l])=>`<option value="${v}" ${selected===v?'selected':''}>${l}</option>`).join('')}
function catalogGroups(){const catalog=window.PermissionService?.catalog||[];const groups=new Map();catalog.forEach(item=>{const prefix=String(item.key||'').split('.')[0]||'other';if(!groups.has(prefix))groups.set(prefix,[]);groups.get(prefix).push(item)});return groups}
function openRoleEditor(roleId){
  if(!admin())return;const role=arr('roller').find(r=>r.id===roleId);if(!role)return;
  document.getElementById('rolePermissionEditor')?.remove();
  const groups=catalogGroups(),body=[...groups.entries()].map(([group,items])=>`<section class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>${esc(group.toLocaleUpperCase('tr'))}</strong><span class="ka-badge">${items.length} yetki</span></div>${items.map(item=>`<label class="ka-field"><span class="ka-field__label">${esc(item.label)} <span class="ka-muted">· ${esc(item.type)}</span></span><select data-permission-key="${esc(item.key)}">${permissionOptions(rawPermission(role,item.key))}</select><small class="ka-muted">${esc(item.key)}</small></label>`).join('')}</div></section>`).join('');
  const ov=document.createElement('div');ov.id='rolePermissionEditor';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><strong>${esc(role.ad||role.rolAdi||'Rol')} — Yetkiler</strong><div class="ka-muted">Sayfa, bölüm ve buton görünürlüğünü tek yerden yönetin.</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-role-close>Kapat</button></div><div class="ka-modal__body ka-stack"><article class="ka-card"><div class="ka-card__body"><strong>Yetki seviyeleri</strong><div class="ka-muted">Gizli: hiç görünmez · Önizleme: sınırlı görünür · Salt okunur: tam görüntüleme · Düzenleme: yazma işlemleri açık.</div></div></article>${body}</div><div class="ka-modal__footer"><button class="ka-btn" type="button" data-role-save data-ka-permission="settings.roles.edit" data-ka-write="settings.roles.edit">Yetkileri Kaydet</button></div></section>`;document.body.appendChild(ov);window.PermissionService?.apply?.(ov);ov.querySelector('[data-role-close]').onclick=()=>ov.remove();ov.querySelector('[data-role-save]').onclick=()=>saveRolePermissions(role,ov)}
async function saveRolePermissions(role,ov){
  try{window.PermissionService?.require?.('settings.roles.edit','edit')}catch(_){toast?.('Rol düzenleme yetkiniz yok.');return}
  const next={...(role.yetkiler||{})};
  ov.querySelectorAll('[data-permission-key]').forEach(sel=>{const key=sel.dataset.permissionKey;delete next[key];if(sel.value)next[key]=sel.value});
  const btn=ov.querySelector('[data-role-save]');if(btn){btn.disabled=true;btn.textContent='Kaydediliyor…'}
  try{
    await window.KullaniciYonetimiService.rolKaydet(role.id,{yetkiler:next});
    const updated={...role,yetkiler:next};
    if((window.AKTIF_ROL||AppStore?.get?.('session.role'))?.id===role.id){window.AKTIF_ROL=updated;AppStore?.set?.('session.role',updated);window.PermissionService?.refresh?.()}
    toast?.('Rol yetkileri cihazda kaydedildi.');ov.remove();render();
  }catch(e){toast?.('Rol yetkileri kaydedilemedi: '+(e?.message||e));if(btn){btn.disabled=false;btn.textContent='Yetkileri Kaydet'}}
}
function render(){if(!mounted)return;if(!admin()&&['users','roles','storage'].includes(active))active='account';document.querySelectorAll('[data-settings-tab]').forEach(b=>b.classList.toggle('active',b.dataset.settingsTab===active));const out=document.getElementById('settingsContent');if(!out)return;out.innerHTML=active==='sync'?sync():active==='users'?users():active==='roles'?roles():active==='storage'?storage():account();out.querySelectorAll('[data-role-permissions]').forEach(b=>b.onclick=()=>openRoleEditor(b.dataset.rolePermissions));window.PermissionService?.apply?.(document.getElementById('v2ModuleRoot')||document)}
function bind(){document.querySelectorAll('[data-settings-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.settingsTab;render()})}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['session.user','session.role','ui.syncing','ui.pendingWrites','ui.lastSyncAt','meta.hydrated','data.kullanicilar','data.roller','data.depolamaAyarlari'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}
function unmount(){mounted=false;document.getElementById('rolePermissionEditor')?.remove();unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.SettingsModule={mount,unmount,render,prepareLocal,openRoleEditor};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='settings')mount()});
})();
