/* Koruk Asistan — Öğrenci işlemleri ayrı sayfaları
 * Yoklama + öğrenci listesi + ödev takip + not çizelgesi.
 * Mevcut People/Tools servislerini kullanır; yeni veri modeli oluşturmaz.
 * Tasarım yalnız css/design-system.css bileşenlerini kullanır.
 */
(function(global){
'use strict';
if(global.StudentPages)return;

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const user=()=>global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};
const fullStudent=v=>String(v?.ogrenciAdi||v?.adSoyad||[v?.ad,v?.soyad].filter(Boolean).join(' ')||'Öğrenci').trim();
const className=s=>s?.ad||s?.sinifAdi||s?.sinif||'Sınıf';
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};

let currentPage='',currentTitle='',selectedClass='',selectedDate=today(),query='',openBook='',unsubs=[];

function root(){return $('#v2ModuleRoot')}
function setTitle(v){const h=$('#v2ModuleTitle');if(h)h.textContent=v||''}
function cleanup(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
function subscribe(paths){cleanup();for(const p of paths){const u=global.AppStore?.subscribe?.(p,()=>requestAnimationFrame(()=>render().catch(console.error)));if(u)unsubs.push(u)}}
function allClasses(){return arr('siniflar').slice().sort((a,b)=>className(a).localeCompare(className(b),'tr',{numeric:true}))}
function studentsOf(classId){return arr('veliler').filter(v=>v.sinifId===classId).slice().sort((a,b)=>{const an=Number(a.ogrenciNo||a.no||0),bn=Number(b.ogrenciNo||b.no||0);return(an&&bn?an-bn:0)||fullStudent(a).localeCompare(fullStudent(b),'tr')})}
function ensureClass(classes=allClasses()){if(selectedClass&&classes.some(x=>x.id===selectedClass))return selectedClass;selectedClass=classes[0]?.id||'';return selectedClass}
function classOptions(classes=allClasses()){ensureClass(classes);return `<option value="">Sınıf seçiniz</option>${classes.map(s=>`<option value="${esc(s.id)}" ${s.id===selectedClass?'selected':''}>${esc(className(s))}</option>`).join('')}`}
function pageHead(title,desc,tools=''){return `<div class="ka-row ka-row--between"><div class="ka-grow"><h2>${esc(title)}</h2><p class="ka-muted">${esc(desc)}</p></div>${tools}</div>`}
function empty(text){return `<div class="ka-empty">${esc(text)}</div>`}
function toast(msg){global.toast?.(msg)}

async function accessibleAttendanceClasses(){try{const list=global.YoklamaService?.erisilebilirSiniflar?.();if(Array.isArray(list)&&list.length)return list}catch(_){}return allClasses()}
async function attendanceRecord(){if(!selectedClass)return null;try{return await global.YoklamaService?.belgeGetir?.(selectedClass,selectedDate)||null}catch(e){console.warn('[StudentPages/yoklama]',e);return null}}
function attendanceStatusOptions(value){const names=global.YoklamaService?.DURUM_ADLARI||{var:'Var',yok:'Yok',gec:'Geç',izinli:'İzinli'};return Object.entries(names).map(([k,l])=>`<option value="${esc(k)}" ${value===k?'selected':''}>${esc(l)}</option>`).join('')}
async function renderAttendance(){
  const r=root();if(!r)return;const classes=await accessibleAttendanceClasses();ensureClass(classes);const students=studentsOf(selectedClass),doc=await attendanceRecord(),states=doc?.kayitlar||{};
  r.innerHTML=`<section class="ka-stack" data-student-page="attendance">${pageHead('Öğrenci Yoklama','Yoklama cihazdaki veriden anında açılır; değişiklikler arka planda senkronize edilir.',`<span class="ka-badge">${students.length} öğrenci</span>`)}<div class="ka-card"><div class="ka-card__body ka-grid"><label class="ka-field"><span class="ka-field__label">Sınıf</span><select id="studentAttendanceClass">${classOptions(classes)}</select></label><label class="ka-field"><span class="ka-field__label">Tarih</span><input id="studentAttendanceDate" type="date" value="${esc(selectedDate)}"></label></div></div>${selectedClass?`<div class="ka-row ka-row--between"><strong>${esc(className(classes.find(x=>x.id===selectedClass)))}</strong><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-att-all-present ${students.length?'':'disabled'}>Tümünü Var İşaretle</button></div>`:''}<div class="ka-stack">${students.length?students.map((s,i)=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><span class="ka-badge">${esc(s.ogrenciNo||s.no||i+1)}</span><div class="ka-grow"><strong>${esc(fullStudent(s))}</strong><div class="ka-muted">${esc(s.cinsiyet||'')}</div></div><label class="ka-field" style="min-width:120px"><select data-att-student="${esc(s.id)}">${attendanceStatusOptions(states[s.id]||'var')}</select></label></div></article>`).join(''):empty(selectedClass?'Bu sınıfta öğrenci bulunamadı.':'Sınıf seçiniz.')}</div></section>`;
  $('#studentAttendanceClass')?.addEventListener('change',e=>{selectedClass=e.target.value;renderAttendance()});
  $('#studentAttendanceDate')?.addEventListener('change',e=>{selectedDate=e.target.value||today();renderAttendance()});
  $$('[data-att-student]',r).forEach(sel=>sel.addEventListener('change',async()=>{sel.disabled=true;try{await global.YoklamaService.ogrenciDurumKaydet(selectedClass,selectedDate,sel.dataset.attStudent,sel.value);toast('Yoklama güncellendi.')}catch(e){toast(e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Yoklama kaydedilemedi.');await renderAttendance()}finally{sel.disabled=false}}));
  $('[data-att-all-present]',r)?.addEventListener('click',async e=>{const b=e.currentTarget,before=b.textContent;b.disabled=true;b.textContent='Kaydediliyor…';try{const kayitlar=Object.fromEntries(students.map(s=>[s.id,'var']));await global.YoklamaService.yoklamaKaydet(selectedClass,selectedDate,kayitlar);toast('Tüm öğrenciler var işaretlendi.')}catch(err){toast(err?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Yoklama kaydedilemedi.')}finally{b.disabled=false;b.textContent=before}});
}

function filteredStudents(){const q=query.trim().toLocaleLowerCase('tr');const rows=studentsOf(selectedClass);if(!q)return rows;return rows.filter(v=>[fullStudent(v),v.ogrenciNo,v.no,v.veliAdi,v.telefon1,v.telefon,v.cinsiyet].some(x=>String(x||'').toLocaleLowerCase('tr').includes(q)))}
function listReport(rows,cls){const body=`<table><thead><tr><th style="width:34px">Sıra</th><th style="width:60px">No</th><th>Öğrenci</th><th style="width:80px">Cinsiyet</th><th>Veli</th><th style="width:110px">Telefon</th></tr></thead><tbody>${rows.map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.ogrenciNo||v.no||'')}</td><td>${esc(fullStudent(v))}</td><td>${esc(v.cinsiyet||'')}</td><td>${esc(v.veliAdi||'')}</td><td>${esc(v.telefon1||v.telefon||v.telefon2||'')}</td></tr>`).join('')}</tbody></table>`;return global.ReportEngine?.printReport?.(`${className(cls)} Öğrenci Listesi`,body,{fileName:`${className(cls)}_Ogrenci_Listesi`,yon:'dikey',compact:true,ustBaslik:'ÖĞRENCİ LİSTESİ'});}
function renderStudentList(){
  const r=root();if(!r)return;const classes=allClasses();ensureClass(classes);const rows=filteredStudents(),cls=classes.find(x=>x.id===selectedClass);
  r.innerHTML=`<section class="ka-stack" data-student-page="student-list">${pageHead('Öğrenci Listesi Oluşturucu','Sınıf listesini gerçek öğrenci verilerinden oluşturun ve merkezi A4 rapor motoruyla yazdırın.',`<span class="ka-badge">${rows.length} öğrenci</span>`)}<div class="ka-card"><div class="ka-card__body ka-grid"><label class="ka-field"><span class="ka-field__label">Sınıf</span><select id="studentListClass">${classOptions(classes)}</select></label><label class="ka-field"><span class="ka-field__label">Ara</span><input id="studentListSearch" type="search" value="${esc(query)}" placeholder="Öğrenci, veli veya numara"></label></div></div><div class="ka-row ka-row--between"><strong>${esc(cls?className(cls):'Öğrenci Listesi')}</strong><button class="ka-btn" type="button" data-student-list-print ${rows.length?'':'disabled'}>Yazdır / PDF</button></div>${rows.length?`<div class="ka-table-wrap"><table class="ka-table"><thead><tr><th>#</th><th>No</th><th>Öğrenci</th><th>Cinsiyet</th><th>Veli</th><th>Telefon</th></tr></thead><tbody>${rows.map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.ogrenciNo||v.no||'')}</td><td><strong>${esc(fullStudent(v))}</strong></td><td>${esc(v.cinsiyet||'')}</td><td>${esc(v.veliAdi||'')}</td><td>${esc(v.telefon1||v.telefon||v.telefon2||'')}</td></tr>`).join('')}</tbody></table></div>`:empty(selectedClass?'Bu sınıfta öğrenci bulunamadı.':'Sınıf seçiniz.')}</section>`;
  $('#studentListClass')?.addEventListener('change',e=>{selectedClass=e.target.value;query='';renderStudentList()});
  $('#studentListSearch')?.addEventListener('input',e=>{query=e.target.value;renderStudentList()});
  $('[data-student-list-print]',r)?.addEventListener('click',()=>{if(!global.ReportEngine){toast('Rapor motoru hazır değil.');return}listReport(rows,cls)});
}

function bookType(page){return page==='homework'?'odevTakip':'notCizelgesi'}
function bookLabel(type){return type==='odevTakip'?'Ödev Takip Çizelgesi':'Not Çizelgesi'}
function visibleBooks(type){const u=user();return arr(type).filter(x=>u.admin===true||x.sahipUid===u.uid).slice().sort((a,b)=>String(b.olusturmaTarihi||'').localeCompare(String(a.olusturmaTarihi||'')))}
function bookStudents(k){return Array.isArray(k.ogrenciler)?k.ogrenciler:[]}
function bookCols(k){return Array.isArray(k.sutunlar)?k.sutunlar:[]}
function bookTable(type,k){const students=bookStudents(k),cols=bookCols(k),cells=k.hucreler||{};if(!students.length)return empty('Bu çizelgede öğrenci bulunmuyor.');if(!cols.length)return empty('Henüz sütun eklenmedi.');return `<div class="ka-table-wrap"><table class="ka-table"><thead><tr><th>Öğrenci</th>${cols.map(c=>`<th>${esc(c.baslik||'Sütun')}</th>`).join('')}</tr></thead><tbody>${students.map(s=>`<tr><td><strong>${esc(s.ad||fullStudent(s))}</strong></td>${cols.map(c=>{const key=`${s.id}_${c.id}`,v=cells[key]??'';return `<td><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-student-book-cell data-book-type="${type}" data-book-id="${esc(k.id)}" data-student-id="${esc(s.id)}" data-col-id="${esc(c.id)}">${esc(v||'–')}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function bookCard(type,k){const open=openBook===k.id,cls=allClasses().find(x=>x.id===k.sinifId);return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div class="ka-grow"><strong>${esc(k.ad||bookLabel(type))}</strong><div class="ka-muted">${esc(k.sinifAdi||className(cls)||'Sınıf')} · ${bookStudents(k).length} öğrenci · ${bookCols(k).length} sütun</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-book-open="${esc(k.id)}">${open?'Kapat':'Aç'}</button></div>${open?`<div class="ka-row ka-row--between"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-book-add-col="${esc(k.id)}">+ Sütun</button><button class="ka-btn ka-btn--danger ka-btn--sm" type="button" data-book-delete="${esc(k.id)}">Sil</button></div>${bookTable(type,k)}`:''}</div></article>`}
function createBookModal(type){const classes=allClasses();ensureClass(classes);document.querySelector('[data-student-book-modal]')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="ka-modal-backdrop" data-student-book-modal><form class="ka-modal" id="studentBookForm"><div class="ka-modal__header"><h2>Yeni ${esc(bookLabel(type))}</h2></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Çizelge Adı</span><input name="ad" required placeholder="Örn: 1. Dönem Ödev Takibi"></label><label class="ka-field"><span class="ka-field__label">Sınıf</span><select name="sinifId" required>${classOptions(classes)}</select></label><label class="ka-field"><span class="ka-field__label">İlk Sütun</span><input name="sutun" required placeholder="${type==='odevTakip'?'Ödev 1':'Yazılı 1'}"></label></div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-student-book-cancel>Vazgeç</button><button class="ka-btn" type="submit">Oluştur</button></div></form></div>`);const modal=$('[data-student-book-modal]'),form=$('#studentBookForm');const close=()=>modal?.remove();$('[data-student-book-cancel]',modal)?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});form?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),classId=String(fd.get('sinifId')||''),cls=classes.find(x=>x.id===classId),students=studentsOf(classId).map(v=>({id:v.id,ad:fullStudent(v),no:v.ogrenciNo||v.no||''})),col={id:`s_${Date.now()}`,baslik:String(fd.get('sutun')||'').trim()};if(!classId||!students.length){toast('Seçilen sınıfta öğrenci bulunamadı.');return}const data={ad:String(fd.get('ad')||'').trim(),sinifId:classId,sinifAdi:className(cls),ogrenciler:students,sutunlar:[col],hucreler:{},hucreModu:type==='notCizelgesi'?'puan':'durum'};try{await global.OdevNotCizelgeleriService.cizelgeOlustur(type,data);close();toast('Çizelge oluşturuldu.')}catch(err){toast(err?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Çizelge oluşturulamadı.')}})}
async function renderBookPage(){
  const r=root();if(!r)return;const type=bookType(currentPage),rows=visibleBooks(type),title=bookLabel(type);
  r.innerHTML=`<section class="ka-stack" data-student-page="${esc(currentPage)}">${pageHead(title,type==='odevTakip'?'Ödev durumlarını öğrenci bazında hızlıca işaretleyin.':'Öğrenci puanlarını sınıf ve değerlendirme sütunlarıyla yönetin.',`<button class="ka-btn" type="button" data-book-new>+ Yeni</button>`)}<div class="ka-row ka-row--between"><strong>Kayıtlı Çizelgeler</strong><span class="ka-badge">${rows.length}</span></div>${rows.length?rows.map(k=>bookCard(type,k)).join(''):empty('Henüz çizelge oluşturulmadı.')}</section>`;
  $('[data-book-new]',r)?.addEventListener('click',()=>createBookModal(type));
  $$('[data-book-open]',r).forEach(b=>b.addEventListener('click',()=>{openBook=openBook===b.dataset.bookOpen?'':b.dataset.bookOpen;renderBookPage()}));
  $$('[data-book-add-col]',r).forEach(b=>b.addEventListener('click',async()=>{const k=rows.find(x=>x.id===b.dataset.bookAddCol);if(!k)return;const title=global.prompt?.('Yeni sütun başlığı:',type==='odevTakip'?`Ödev ${bookCols(k).length+1}`:`Değerlendirme ${bookCols(k).length+1}`);if(!title?.trim())return;const next={...k,sutunlar:[...bookCols(k),{id:`s_${Date.now()}`,baslik:title.trim()}]};try{await global.OdevNotCizelgeleriService.taslagiKaydet(type,next)}catch(e){toast('Sütun eklenemedi.')}}));
  $$('[data-book-delete]',r).forEach(b=>b.addEventListener('click',async()=>{const k=rows.find(x=>x.id===b.dataset.bookDelete);if(!k||!confirm('Bu çizelge silinsin mi?'))return;try{await global.OdevNotCizelgeleriService.cizelgeSil(type,k);openBook='';toast('Çizelge silindi.')}catch(e){toast(e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Çizelge silinemedi.')}}));
  $$('[data-student-book-cell]',r).forEach(b=>b.addEventListener('click',async()=>{const k=rows.find(x=>x.id===b.dataset.bookId);if(!k)return;const key=`${b.dataset.studentId}_${b.dataset.colId}`,old=k.hucreler?.[key]??'';let next='';if(type==='odevTakip')next=old==='✓'?'✗':old==='✗'?'':'✓';else{const val=global.prompt?.('Puan:',String(old));if(val===null)return;next=val.trim();if(next!==''&&(isNaN(Number(next))||Number(next)<0)){toast('Geçerli bir puan girin.');return}}try{await global.OdevNotCizelgeleriService.hucreGuncelle(type,k,b.dataset.studentId,b.dataset.colId,next)}catch(e){toast(e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Değer kaydedilemedi.')}}));
}

async function render(){if(currentPage==='attendance')return renderAttendance();if(currentPage==='student-list')return renderStudentList();if(currentPage==='homework'||currentPage==='grades')return renderBookPage();}
async function open(page,title=''){
  currentPage=page||'';currentTitle=title||'';query='';openBook='';setTitle(currentTitle||({attendance:'Öğrenci Yoklama','student-list':'Öğrenci Listesi Oluşturucu',homework:'Ödev Takip Çizelgesi',grades:'Not Çizelgesi'}[currentPage]||'Öğrenci İşlemleri'));
  if(currentPage==='homework'||currentPage==='grades')await global.ToolsData?.prepareGradebooks?.();
  const paths=currentPage==='attendance'?['data.siniflar','data.veliler','data.yoklama']:currentPage==='student-list'?['data.siniflar','data.veliler']:['data.siniflar','data.veliler','data.odevTakip','data.notCizelgesi'];subscribe(paths);await render();return true;
}
function close(){currentPage='';cleanup();document.querySelector('[data-student-book-modal]')?.remove()}

global.StudentPages={open,close,render,get page(){return currentPage}};
})(window);
