/* Koruk Asistan — Öğretmen özel çizelgeleri: local-first servis + V2 Tools editörü. */
(function(global){
'use strict';
if(global.OgretmenListeService)return;
function device(){if(!global.DeviceData)throw new Error('DeviceData hazır değil.');return global.DeviceData;}
const user=()=>global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};
const teacherId=()=>user().bagliOgretmenId||user().ogretmenId||'';
const own=(row,id)=>!!row&&!!id&&row.ogretmenId===id;
const safeClass=v=>String(v||'').trim();
const templateId=(ogretmenId,sinif)=>`${ogretmenId}__${safeClass(sinif)}`.replace(/[^\w\-]/g,'_');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[];};
const clone=v=>{try{return structuredClone(v)}catch(_){return JSON.parse(JSON.stringify(v))}};
let preparedFor='',selectedClass='',unsubscribe=null,editingId='',draft=null;
const BUILTIN_COLUMNS=[
 {key:'siraNo',label:'Sıra No'},{key:'ogrenciAdi',label:'Ad Soyad'},{key:'ogrenciNo',label:'Öğrenci No'},
 {key:'cinsiyet',label:'Cinsiyet'},{key:'veliAdi',label:'Veli Adı'},{key:'yakinlik',label:'Yakınlık'},
 {key:'telefon1',label:'Telefon 1'},{key:'telefon2',label:'Telefon 2'},{key:'adres',label:'Adres'},
 {key:'servisAdi',label:'Servis'},{key:'kulupAdi',label:'Sosyal Kulüp'},{key:'notlar',label:'Notlar'}
];
const COLUMN_BY_KEY=Object.fromEntries(BUILTIN_COLUMNS.map(x=>[x.key,x]));
async function prepare(){
 const tid=teacherId();if(!tid||!global.SyncEngine||!global.COL?.ogretmenListeSablon||!global.COL?.ogretmenListeKayit)return false;if(preparedFor===tid)return true;preparedFor=tid;
 SyncEngine.register('ogretmenListeSablon',COL.ogretmenListeSablon,{query:q=>q.where('ogretmenId','==',tid)});
 SyncEngine.register('ogretmenListeKayit',COL.ogretmenListeKayit,{query:q=>q.where('ogretmenId','==',tid)});
 await SyncEngine.localHydrate(['ogretmenListeSablon','ogretmenListeKayit']);SyncEngine.schedule(100);return true;
}
const OgretmenListeRepository={
 sablonId:templateId,
 sablonGetir(ogretmenId,sinif){const id=templateId(ogretmenId,sinif);return Promise.resolve(device().list('ogretmenListeSablon').find(x=>x.id===id)||null);},
 sablonKaydet(ogretmenId,sinif,veri){const id=templateId(ogretmenId,sinif);return device().set('ogretmenListeSablon',COL.ogretmenListeSablon,id,{...veri,ogretmenId,sinif:safeClass(sinif),guncellenme:new Date().toISOString()},{merge:false});},
 kayitlariDinle(ogretmenId,sinif,cb){return device().listen('ogretmenListeKayit',rows=>cb((rows||[]).filter(x=>own(x,ogretmenId)&&x.sinif===safeClass(sinif)).sort((a,b)=>String(b.guncellenme||'').localeCompare(String(a.guncellenme||'')))));},
 kayitlariGetir(ogretmenId,sinif){return Promise.resolve(device().list('ogretmenListeKayit').filter(x=>own(x,ogretmenId)&&x.sinif===safeClass(sinif)).sort((a,b)=>String(b.guncellenme||'').localeCompare(String(a.guncellenme||''))));},
 kayitEkle(ogretmenId,sinif,veri){const now=new Date().toISOString();return device().add('ogretmenListeKayit',COL.ogretmenListeKayit,{...veri,ogretmenId,sinif:safeClass(sinif),olusturulma:veri.olusturulma||now,guncellenme:now});},
 kayitGuncelle(id,ogretmenId,veri){const mevcut=device().list('ogretmenListeKayit').find(x=>x.id===id);if(mevcut&&!own(mevcut,ogretmenId))return Promise.reject(new Error('sahip-degil'));return device().update('ogretmenListeKayit',COL.ogretmenListeKayit,id,{...veri,ogretmenId,guncellenme:new Date().toISOString()});},
 kayitSil(id,ogretmenId){const mevcut=device().list('ogretmenListeKayit').find(x=>x.id===id);if(mevcut&&!own(mevcut,ogretmenId))return Promise.reject(new Error('sahip-degil'));return device().remove('ogretmenListeKayit',COL.ogretmenListeKayit,id);}
};
global.OgretmenListeRepository=OgretmenListeRepository;
global.OgretmenListeService={prepare,ogretmenId:teacherId,sablonId:templateId,
 async sablonGetir(sinif){await prepare();const id=teacherId();return id?OgretmenListeRepository.sablonGetir(id,sinif):null;},
 async sablonKaydet(sinif,veri){await prepare();const id=teacherId();if(!id)throw new Error('ogretmen-bagli-degil');return OgretmenListeRepository.sablonKaydet(id,sinif,veri);},
 kayitlariDinle(sinif,cb){const id=teacherId();if(!id){cb([]);return()=>{};}prepare().catch(e=>console.warn('[OgretmenListe]',e?.message||e));return OgretmenListeRepository.kayitlariDinle(id,sinif,cb);},
 async kayitlariGetir(sinif){await prepare();const id=teacherId();return id?OgretmenListeRepository.kayitlariGetir(id,sinif):[];},
 async kayitKaydet(sinif,mevcutId,veri){await prepare();const id=teacherId();if(!id)throw new Error('ogretmen-bagli-degil');return mevcutId?OgretmenListeRepository.kayitGuncelle(mevcutId,id,{...veri,sinif:safeClass(sinif)}):OgretmenListeRepository.kayitEkle(id,sinif,veri);},
 async kayitSil(id){await prepare();const tid=teacherId();if(!tid)throw new Error('ogretmen-bagli-degil');return OgretmenListeRepository.kayitSil(id,tid);}
};
function ownClasses(){const tid=teacherId(),set=new Set();if(!tid)return[];data('dersProgrami').filter(x=>x.ogretmenId===tid).forEach(x=>{if(x.sinif)set.add(String(x.sinif));if(x.sinifAdi)set.add(String(x.sinifAdi));});data('siniflar').filter(x=>x.sinifOgretmeniId===tid||x.ogretmenId===tid).forEach(x=>{if(x.ad)set.add(String(x.ad));if(x.sinifAdi)set.add(String(x.sinifAdi));});data('ogretmenListeKayit').filter(x=>x.ogretmenId===tid&&x.sinif).forEach(x=>set.add(String(x.sinif)));return[...set].filter(Boolean).sort((a,b)=>a.localeCompare(b,'tr'));}
function rosterForClass(sinifAdi){const s=data('siniflar').find(x=>x.ad===sinifAdi),sinifId=s?s.id:sinifAdi;return data('veliler').filter(v=>v.sinifId===sinifId||v.sinifId===sinifAdi).sort((a,b)=>String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr'));}
function rosterSnapshot(){return rosterForClass(selectedClass).map(v=>({ogrenciAdi:v.ogrenciAdi||'',ogrenciNo:v.ogrenciNo||'',cinsiyet:v.cinsiyet||'',veliAdi:v.veliAdi||'',yakinlik1:v.yakinlik1||v.yakinlik||'',telefon1:v.telefon1||v.telefon||'',telefon2:v.telefon2||'',adres:v.adres||'',servisAdi:v.servisAdi||'',kulupAdi:v.kulupAdi||'',notlar:v.notlar||''}));}
function teacherRecord(){return data('ogretmenler').find(x=>x.id===teacherId())||null;}
function schoolSettings(){const local=data('okulBilgileri');return global.okulBilgileriAyari||(local.length?local[0]:{})||{};}
function academicYear(){const y=new Date().getFullYear();return`${y}-${y+1}`;}
function headerDefaults(){const og=teacherRecord(),okul=schoolSettings(),mudur=okul.mudurId?data('ogretmenler').find(x=>x.id===okul.mudurId):null;return{okulAdi:okul.okulAdi||'',okulAdiGoster:true,egitimYili:academicYear(),egitimYiliGoster:true,altBaslik:'',altBaslikGoster:false,ogretmenAdSoyad:og?`${og.ad||''} ${og.soyad||''}`.trim():'',ogretmenGoster:true,ogretmenBrans:og?.brans||'',ogretmenBransGoster:true,mudurAdSoyad:mudur?`${mudur.ad||''} ${mudur.soyad||''}`.trim():'',mudurGoster:true,mudurUnvan:'Okul Müdürü',mudurUnvanGoster:true,yon:'portrait'};}
function valueFor(row,key,index){if(key==='siraNo')return String(index+1);if(key==='yakinlik')return row.yakinlik1||row.yakinlik||'';return row[key]??'';}
function setValue(row,key,value){if(key==='yakinlik'){row.yakinlik1=value;delete row.yakinlik;}else row[key]=value;}
function normalizeCustom(cols){return(Array.isArray(cols)?cols:[]).map((c,i)=>typeof c==='string'?{id:`ozel_${i}_${Date.now().toString(36)}`,label:c}:{id:c.id||`ozel_${i}_${Date.now().toString(36)}`,label:c.label||''}).filter(c=>c.label);}
function normalizeDraft(source={}){const order=(Array.isArray(source.sutunSirasi)?source.sutunSirasi:BUILTIN_COLUMNS.map(c=>c.key)).filter(k=>COLUMN_BY_KEY[k]);BUILTIN_COLUMNS.forEach(c=>{if(!order.includes(c.key))order.push(c.key)});return{ad:source.ad||'',secilenKeyler:Array.isArray(source.secilenKeyler)?source.secilenKeyler.slice():BUILTIN_COLUMNS.map(c=>c.key),sutunSirasi:order,ozelSutunlar:normalizeCustom(source.ozelSutunlar),satirlar:Array.isArray(source.satirlar)?clone(source.satirlar):rosterSnapshot(),sutunGenislikleri:clone(source.sutunGenislikleri||{}),sutunHizalama:clone(source.sutunHizalama||{}),baslikBilgisi:{...headerDefaults(),...clone(source.baslikBilgisi||{})}};}
async function newDraft(){if(!selectedClass){global.toast?.('Önce bir sınıf seçin.');return;}editingId='';const tpl=await global.OgretmenListeService.sablonGetir(selectedClass);draft=normalizeDraft(tpl||{});draft.ad='';draft.satirlar=rosterSnapshot();renderUI();}
function openRecord(id){const r=data('ogretmenListeKayit').find(x=>x.id===id&&x.ogretmenId===teacherId());if(r){editingId=id;draft=normalizeDraft(r);renderUI();}}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR');}
function canEdit(){return global.PermissionService?.can?.('tools.schedules','edit')!==false;}
function alignmentFor(key){return draft?.sutunHizalama?.[key]||(key==='siraNo'||key==='ogrenciNo'?'center':'left');}
function widthFor(key){return Math.max(72,Math.min(420,Number(draft?.sutunGenislikleri?.[key])||126));}
function selectedColumns(){if(!draft)return[];const built=draft.sutunSirasi.filter(k=>draft.secilenKeyler.includes(k)).map(k=>({key:k,label:COLUMN_BY_KEY[k]?.label||k}));return[...built,...draft.ozelSutunlar.map(c=>({key:c.id,label:c.label}))];}
function moveColumn(key,dir){if(!draft)return;const i=draft.sutunSirasi.indexOf(key),j=i+dir;if(i<0||j<0||j>=draft.sutunSirasi.length)return;[draft.sutunSirasi[i],draft.sutunSirasi[j]]=[draft.sutunSirasi[j],draft.sutunSirasi[i]];renderUI();}
function cycleAlign(key){if(!draft)return;const now=alignmentFor(key),next={left:'center',center:'right',right:'left'}[now]||'left';draft.sutunHizalama[key]=next;renderUI();}
function setWidth(key,value){if(!draft)return;draft.sutunGenislikleri[key]=Math.max(72,Math.min(420,Number(value)||126));}
function recordCard(r){const rc=Array.isArray(r.satirlar)?r.satirlar.length:0,cc=(r.secilenKeyler?.length||0)+(r.ozelSutunlar?.length||0);return`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row ka-row--between"><div class="ka-grow"><strong>${esc(r.ad||'İsimsiz Çizelge')}</strong><div class="ka-muted">${esc(r.sinif||'')} · ${rc} satır · ${cc} sütun · ${esc(date(r.guncellenme||r.olusturulma))}</div></div><div class="ka-row"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-teacher-list-open="${esc(r.id)}">Aç</button>${canEdit()?`<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-teacher-list-delete="${esc(r.id)}" data-ka-permission="tools.schedules" data-ka-write="tools.schedules">Sil</button>`:''}</div></div></article>`;}
function toggleField(id,label,value,checked,editable=true){return`<label class="ka-field"><span class="ka-field__label">${esc(label)}</span><div class="ka-row"><input class="ka-input ka-grow" data-teacher-list-header="${esc(id)}" value="${esc(value||'')}" ${editable?'':'readonly'}><label class="ka-row"><input type="checkbox" data-teacher-list-header-toggle="${esc(id+'Goster')}" ${checked?'checked':''} ${editable?'':'disabled'}><span>Göster</span></label></div></label>`;}
function columnManager(editable){return`<section class="ka-stack"><div class="ka-row ka-row--between"><div><h4>Sütunlar</h4><div class="ka-muted">Sıra, hizalama ve genişlik burada yönetilir.</div></div></div>${draft.sutunSirasi.map(k=>`<article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><label class="ka-row ka-grow"><input type="checkbox" data-teacher-list-column="${esc(k)}" ${draft.secilenKeyler.includes(k)?'checked':''} ${editable?'':'disabled'}><strong>${esc(COLUMN_BY_KEY[k]?.label||k)}</strong></label>${editable?`<div class="ka-row"><button class="ka-btn ka-btn--ghost ka-btn--sm" data-teacher-list-move="-1" data-key="${esc(k)}" type="button">▲</button><button class="ka-btn ka-btn--ghost ka-btn--sm" data-teacher-list-move="1" data-key="${esc(k)}" type="button">▼</button></div>`:''}</div><div class="ka-row ka-wrap"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-teacher-list-align="${esc(k)}" ${editable?'':'disabled'}>Hiza: ${alignmentFor(k)==='left'?'Sol':alignmentFor(k)==='center'?'Orta':'Sağ'}</button><label class="ka-row ka-grow"><span class="ka-muted">Genişlik</span><input class="ka-input" style="max-width:110px" type="number" min="72" max="420" step="10" value="${widthFor(k)}" data-teacher-list-width="${esc(k)}" ${editable?'':'disabled'}></label></div></div></article>`).join('')}</section>`;}
function editorHtml(){
 if(!draft)return'';const cols=selectedColumns(),editable=canEdit(),bs=draft.baslikBilgisi;
 const custom=draft.ozelSutunlar.map(c=>`<div class="ka-row ka-row--between"><span>${esc(c.label)}</span>${editable?`<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-teacher-list-custom-remove="${esc(c.id)}">Sil</button>`:''}</div>`).join('');
 const table=cols.length?`<div class="ka-table-wrap"><table class="ka-table"><thead><tr>${cols.map(c=>`<th style="min-width:${widthFor(c.key)}px;text-align:${alignmentFor(c.key)}">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${draft.satirlar.map((row,ri)=>`<tr>${cols.map(c=>`<td style="min-width:${widthFor(c.key)}px;text-align:${alignmentFor(c.key)}">${c.key==='siraNo'?esc(ri+1):`<input class="ka-input" style="min-width:${Math.max(68,widthFor(c.key)-24)}px;text-align:${alignmentFor(c.key)}" data-teacher-list-cell data-row="${ri}" data-key="${esc(c.key)}" value="${esc(valueFor(row,c.key,ri))}" ${editable?'':'readonly'}>`}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="ka-empty">En az bir sütun seçin.</div>';
 const header=`<details class="ka-card"><summary class="ka-card__body"><strong>Başlık, İmza ve Sayfa Düzeni</strong></summary><div class="ka-card__body ka-stack"><div class="ka-grid">${toggleField('okulAdi','Okul Adı',bs.okulAdi,bs.okulAdiGoster,editable)}${toggleField('egitimYili','Eğitim-Öğretim Yılı',bs.egitimYili,bs.egitimYiliGoster,editable)}${toggleField('altBaslik','Alt Başlık',bs.altBaslik,bs.altBaslikGoster,editable)}${toggleField('ogretmenAdSoyad','Öğretmen Ad Soyad',bs.ogretmenAdSoyad,bs.ogretmenGoster,editable)}${toggleField('ogretmenBrans','Branş',bs.ogretmenBrans,bs.ogretmenBransGoster,editable)}${toggleField('mudurAdSoyad','Okul Müdürü Ad Soyad',bs.mudurAdSoyad,bs.mudurGoster,editable)}${toggleField('mudurUnvan','Müdür Ünvanı',bs.mudurUnvan,bs.mudurUnvanGoster,editable)}</div><div class="ka-row ka-wrap"><strong>Sayfa yönü:</strong><label class="ka-row"><input type="radio" name="teacherListOrientation" data-teacher-list-orientation value="portrait" ${bs.yon!=='landscape'?'checked':''} ${editable?'':'disabled'}> Dikey A4</label><label class="ka-row"><input type="radio" name="teacherListOrientation" data-teacher-list-orientation value="landscape" ${bs.yon==='landscape'?'checked':''} ${editable?'':'disabled'}> Yatay A4</label></div></div></details>`;
 return`<article class="ka-card" data-teacher-list-editor><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><h3>${editingId?'Çizelgeyi Düzenle':'Yeni Çizelge'}</h3><p class="ka-muted">${esc(selectedClass)} · ${draft.satirlar.length} öğrenci</p></div><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-teacher-list-close>Kapat</button></div><label class="ka-field"><span class="ka-field__label">Çizelge Adı</span><input class="ka-input" data-teacher-list-name value="${esc(draft.ad)}" placeholder="Örn: 1. Dönem Not Çizelgesi" ${editable?'':'readonly'}></label>${header}<div class="ka-grid">${columnManager(editable)}<section class="ka-stack"><h4>Özel Sütunlar</h4>${custom||'<div class="ka-muted">Özel sütun yok.</div>'}${editable?`<div class="ka-row"><input class="ka-input ka-grow" data-teacher-list-custom-name placeholder="Örn: İmza, Konuşma, Puan"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-teacher-list-custom-add>Ekle</button></div>`:''}</section></div>${table}<div class="ka-row ka-wrap"><button class="ka-btn ka-btn--secondary" type="button" data-teacher-list-report>🖨 A4 Önizleme / PDF</button><button class="ka-btn ka-btn--secondary" type="button" data-teacher-list-excel>📊 Excel'e Aktar</button>${editable?`<button class="ka-btn" type="button" data-teacher-list-save data-ka-permission="tools.schedules" data-ka-write="tools.schedules">💾 Çizelgeyi Kaydet</button><button class="ka-btn ka-btn--secondary" type="button" data-teacher-list-template-save data-ka-permission="tools.schedules" data-ka-write="tools.schedules">Sütun Düzenini Şablon Yap</button>`:''}</div></div></article>`;
}
function ensureTab(){const tabs=document.querySelector('[data-tools-module] .ka-tabs');if(!tabs)return;let b=tabs.querySelector('[data-teacher-list-tab]');if(!b){b=document.createElement('button');b.className='ka-tab';b.type='button';b.dataset.teacherListTab='';b.textContent='Öğretmen Çizelgelerim';tabs.appendChild(b);}b.onclick=()=>openUI();if(!b.dataset.teacherListBound){b.dataset.teacherListBound='1';tabs.addEventListener('click',e=>{if(e.target.closest?.('[data-tools-tab]'))b.classList.remove('active');});}}
async function openUI(){await prepare();ensureTab();document.querySelectorAll('[data-tools-tab]').forEach(b=>b.classList.remove('active'));document.querySelector('[data-teacher-list-tab]')?.classList.add('active');if(!selectedClass)selectedClass=ownClasses()[0]||'';renderUI();subscribeSelection();}
function subscribeSelection(){try{unsubscribe?.();}catch(_){}unsubscribe=null;if(selectedClass)unsubscribe=global.OgretmenListeService.kayitlariDinle(selectedClass,()=>requestAnimationFrame(renderUI));}
function renderUI(){const content=document.getElementById('toolsContent'),count=document.getElementById('toolsCount');if(!content)return;const classes=ownClasses(),tid=teacherId(),rows=data('ogretmenListeKayit').filter(x=>x.ogretmenId===tid&&(!selectedClass||x.sinif===selectedClass)).sort((a,b)=>String(b.guncellenme||'').localeCompare(String(a.guncellenme||'')));if(count)count.textContent=`${rows.length} çizelge`;if(!tid){content.innerHTML='<div class="ka-empty">Hesabınıza bağlı öğretmen kaydı bulunamadı.</div>';return;}content.innerHTML=`<section class="ka-stack" data-teacher-list-ui><article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><h3>Öğretmen Çizelgelerim</h3><p class="ka-muted">Cihaz verisi anında açılır; Firestore senkronu arka plandadır.</p></div>${selectedClass&&canEdit()?`<button class="ka-btn" type="button" data-teacher-list-new data-ka-permission="tools.schedules" data-ka-write="tools.schedules">+ Yeni Çizelge</button>`:''}</div><label class="ka-field"><span class="ka-field__label">Sınıf</span><select data-teacher-list-class><option value="">— Sınıf seçin —</option>${classes.map(c=>`<option value="${esc(c)}" ${c===selectedClass?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div></article>${draft?editorHtml():(selectedClass?(rows.length?rows.map(recordCard).join(''):'<div class="ka-empty">Bu sınıf için kayıtlı çizelge bulunamadı.</div>'):'<div class="ka-empty">Bir sınıf seçin.</div>')}</section>`;bindUI(rows);global.PermissionService?.apply?.(content);}
function bindUI(rows){const root=document.querySelector('[data-teacher-list-ui]');if(!root)return;
 root.querySelector('[data-teacher-list-class]')?.addEventListener('change',e=>{selectedClass=e.target.value;editingId='';draft=null;subscribeSelection();renderUI();});
 root.querySelector('[data-teacher-list-new]')?.addEventListener('click',()=>newDraft().catch(e=>global.toast?.(e?.message||'Yeni çizelge açılamadı.')));root.querySelectorAll('[data-teacher-list-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.teacherListOpen));
 root.querySelectorAll('[data-teacher-list-delete]').forEach(b=>b.onclick=async()=>{const r=rows.find(x=>x.id===b.dataset.teacherListDelete);if(!r||!global.confirm?.(`"${r.ad||'Bu çizelge'}" silinsin mi?`))return;try{await global.OgretmenListeService.kayitSil(r.id);if(editingId===r.id){editingId='';draft=null;}global.toast?.('Çizelge cihazdan silindi; senkron kuyruğuna alındı.');}catch(e){global.toast?.(e?.message||'Çizelge silinemedi.');}});
 root.querySelector('[data-teacher-list-close]')?.addEventListener('click',()=>{editingId='';draft=null;renderUI();});root.querySelector('[data-teacher-list-name]')?.addEventListener('input',e=>{if(draft)draft.ad=e.target.value;});
 root.querySelectorAll('[data-teacher-list-column]').forEach(el=>el.onchange=()=>{if(!draft)return;draft.secilenKeyler=el.checked?[...new Set([...draft.secilenKeyler,el.dataset.teacherListColumn])]:draft.secilenKeyler.filter(k=>k!==el.dataset.teacherListColumn);renderUI();});
 root.querySelectorAll('[data-teacher-list-move]').forEach(b=>b.onclick=()=>moveColumn(b.dataset.key,Number(b.dataset.teacherListMove)||0));root.querySelectorAll('[data-teacher-list-align]').forEach(b=>b.onclick=()=>cycleAlign(b.dataset.teacherListAlign));root.querySelectorAll('[data-teacher-list-width]').forEach(el=>el.onchange=()=>{setWidth(el.dataset.teacherListWidth,el.value);renderUI();});
 root.querySelector('[data-teacher-list-custom-add]')?.addEventListener('click',()=>{const input=root.querySelector('[data-teacher-list-custom-name]'),label=input?.value?.trim();if(!label||!draft)return;draft.ozelSutunlar.push({id:'ozel_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),label});renderUI();});
 root.querySelectorAll('[data-teacher-list-custom-remove]').forEach(b=>b.onclick=()=>{if(!draft)return;const id=b.dataset.teacherListCustomRemove;draft.ozelSutunlar=draft.ozelSutunlar.filter(c=>c.id!==id);draft.satirlar.forEach(r=>delete r[id]);renderUI();});root.querySelectorAll('[data-teacher-list-cell]').forEach(el=>el.oninput=()=>{if(!draft)return;const row=draft.satirlar[Number(el.dataset.row)];if(row)setValue(row,el.dataset.key,el.value);});
 root.querySelectorAll('[data-teacher-list-header]').forEach(el=>el.oninput=()=>{if(draft)draft.baslikBilgisi[el.dataset.teacherListHeader]=el.value;});root.querySelectorAll('[data-teacher-list-header-toggle]').forEach(el=>el.onchange=()=>{if(draft)draft.baslikBilgisi[el.dataset.teacherListHeaderToggle]=el.checked;});root.querySelectorAll('[data-teacher-list-orientation]').forEach(el=>el.onchange=()=>{if(draft&&el.checked)draft.baslikBilgisi.yon=el.value;});
 root.querySelector('[data-teacher-list-report]')?.addEventListener('click',openReport);root.querySelector('[data-teacher-list-excel]')?.addEventListener('click',()=>exportExcel().catch(e=>{console.error('[OgretmenListe/Excel]',e);global.toast?.('Excel oluşturulamadı: '+(e?.message||e));}));root.querySelector('[data-teacher-list-save]')?.addEventListener('click',saveDraft);root.querySelector('[data-teacher-list-template-save]')?.addEventListener('click',saveTemplate);
}
function reportTitle(){return String(draft?.ad||'').trim()||`${selectedClass} Sınıfı Öğrenci Listesi`;}
function reportBody(){if(!draft)return'';const cols=selectedColumns(),bs=draft.baslikBilgisi||headerDefaults();if(!cols.length)throw new Error('En az bir sütun seçin.');let logo='';try{logo=new URL('assets/icon-192.png',global.location.href).href}catch(_){}const meta=bs.egitimYiliGoster&&bs.egitimYili?`${esc(bs.egitimYili)} Eğitim-Öğretim Yılı`:'';const left=bs.ogretmenGoster?`<div><div>Öğretmen: <strong>${esc(bs.ogretmenAdSoyad||'...............................')}</strong></div>${bs.ogretmenBransGoster&&bs.ogretmenBrans?`<div>${esc(bs.ogretmenBrans)}</div>`:''}<div style="margin-top:24px">İmza: .......................</div></div>`:'';const right=bs.mudurGoster?`<div style="text-align:right"><div>${bs.mudurUnvanGoster&&bs.mudurUnvan?esc(bs.mudurUnvan):'Okul Müdürü'}: <strong>${esc(bs.mudurAdSoyad||'...............................')}</strong></div><div style="margin-top:24px">İmza: .......................</div></div>`:'';const heads=cols.map(c=>`<th style="width:${widthFor(c.key)}px;text-align:${alignmentFor(c.key)};background:#1B3A5C;color:#fff;padding:6px;border:1px solid #1B3A5C;white-space:nowrap">${esc(c.label)}</th>`).join('');const rows=draft.satirlar.map((r,i)=>`<tr>${cols.map(c=>`<td style="width:${widthFor(c.key)}px;text-align:${alignmentFor(c.key)};padding:5px 6px;border:1px solid #d8dde3;vertical-align:top">${esc(valueFor(r,c.key,i))}</td>`).join('')}</tr>`).join('');return`<header style="display:grid;grid-template-columns:64px 1fr 64px;align-items:center;gap:10px;border-bottom:2px solid #263746;padding-bottom:10px;margin-bottom:14px">${logo?`<img src="${esc(logo)}" alt="Okul logosu" style="width:58px;height:58px;object-fit:contain">`:'<span></span>'}<div style="text-align:center">${bs.okulAdiGoster&&bs.okulAdi?`<div style="font-size:15px;font-weight:800;text-transform:uppercase">${esc(bs.okulAdi)}</div>`:''}<div style="font-size:13px;font-weight:700;margin-top:4px">${esc(reportTitle())}</div>${bs.altBaslikGoster&&bs.altBaslik?`<div style="font-size:11px;margin-top:3px">${esc(bs.altBaslik)}</div>`:''}${meta?`<div style="font-size:10px;margin-top:4px;color:#5b6470">${meta}</div>`:''}</div><span></span></header><table style="width:100%;border-collapse:collapse;font-size:10px"><thead><tr>${heads}</tr></thead><tbody>${rows}</tbody></table><div style="text-align:right;margin-top:8px;font-size:10px">Toplam öğrenci sayısı: <strong>${draft.satirlar.length}</strong></div>${left||right?`<footer style="display:flex;justify-content:space-between;gap:24px;margin-top:18px;font-size:10px;line-height:1.6">${left||'<span></span>'}${right||'<span></span>'}</footer>`:''}`;}
function openReport(){try{if(!global.ReportEngine?.printReport)throw new Error('Rapor motoru hazır değil.');const bs=draft?.baslikBilgisi||{};global.ReportEngine.printReport(reportTitle(),reportBody(),{fileName:reportTitle(),yon:bs.yon==='landscape'?'yatay':'dikey'});}catch(e){global.toast?.(e?.message||'Rapor açılamadı.');}}
function loadScript(src,test){if(test())return Promise.resolve();return new Promise((resolve,reject)=>{const old=[...document.scripts].find(x=>x.src===src);if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
async function excelReady(){if(global.ExcelJS)return true;await loadScript('https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.4.0/exceljs.min.js',()=>!!global.ExcelJS);return!!global.ExcelJS;}
function bufferToBase64(buffer){const bytes=new Uint8Array(buffer);let out='';for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode.apply(null,bytes.subarray(i,i+0x8000));return btoa(out);}
async function exportExcel(){if(!draft)return;const cols=selectedColumns();if(!cols.length)throw new Error('En az bir sütun seçin.');if(!await excelReady())throw new Error('Excel kütüphanesi yüklenemedi.');const bs=draft.baslikBilgisi||headerDefaults(),wb=new global.ExcelJS.Workbook(),ws=wb.addWorksheet((selectedClass||'Liste').slice(0,31)),n=cols.length;let rn=1;const merged=(text,size=11,color='FF1B3A5C')=>{ws.mergeCells(rn,1,rn,n);const c=ws.getCell(rn,1);c.value=text;c.font={bold:true,size,color:{argb:color}};c.alignment={horizontal:'center',vertical:'middle'};rn++;};ws.columns=cols.map(c=>({width:Math.max(10,Math.min(60,Math.round(widthFor(c.key)/7)))}));if(bs.okulAdiGoster&&bs.okulAdi)merged(bs.okulAdi,13);merged(reportTitle(),12);if(bs.altBaslikGoster&&bs.altBaslik)merged(bs.altBaslik,10,'FF444444');if(bs.egitimYiliGoster&&bs.egitimYili)merged(`${bs.egitimYili} Eğitim-Öğretim Yılı`,9,'FF666666');rn++;const headNo=rn,head=ws.getRow(rn++),border={style:'thin',color:{argb:'FFB8C2CC'}};cols.forEach((c,i)=>{const cell=head.getCell(i+1);cell.value=c.label;cell.font={bold:true,size:10,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1B3A5C'}};cell.alignment={horizontal:alignmentFor(c.key),vertical:'middle'};cell.border={top:border,left:border,bottom:border,right:border};});draft.satirlar.forEach((r,ri)=>{const row=ws.getRow(rn++);cols.forEach((c,ci)=>{const cell=row.getCell(ci+1);cell.value=valueFor(r,c.key,ri);cell.font={size:10};cell.alignment={horizontal:alignmentFor(c.key),vertical:'middle'};cell.border={top:border,left:border,bottom:border,right:border};if(ri%2===1)cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF7F7F7'}};});});ws.mergeCells(rn,1,rn,n);const total=ws.getCell(rn,1);total.value=`Toplam öğrenci sayısı: ${draft.satirlar.length}`;total.font={italic:true,size:9,color:{argb:'FF444444'}};total.alignment={horizontal:'right'};ws.views=[{state:'frozen',ySplit:headNo}];const buffer=await wb.xlsx.writeBuffer(),name=(global.ReportEngine?.fileName?.(reportTitle())||'Ogrenci_Listesi')+'.xlsx',mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';if(typeof global.uygulamaDosyaKaydet==='function')await global.uygulamaDosyaKaydet(bufferToBase64(buffer),name,mime,false);else{const blob=new Blob([buffer],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}global.toast?.('Excel dosyası hazırlandı.');}
async function saveDraft(){if(!draft||!selectedClass)return;const ad=String(draft.ad||'').trim();if(!ad){global.toast?.('Çizelge adı girin.');return;}const payload={ad,secilenKeyler:draft.secilenKeyler.slice(),sutunSirasi:draft.sutunSirasi.slice(),ozelSutunlar:clone(draft.ozelSutunlar),satirlar:clone(draft.satirlar),sutunGenislikleri:clone(draft.sutunGenislikleri||{}),sutunHizalama:clone(draft.sutunHizalama||{}),baslikBilgisi:clone(draft.baslikBilgisi||{})};try{await global.OgretmenListeService.kayitKaydet(selectedClass,editingId||null,payload);global.toast?.(`"${ad}" cihazda kaydedildi.`);editingId='';draft=null;renderUI();}catch(e){global.toast?.(e?.message||'Çizelge kaydedilemedi.');}}
async function saveTemplate(){if(!draft||!selectedClass)return;try{await global.OgretmenListeService.sablonKaydet(selectedClass,{secilenKeyler:draft.secilenKeyler.slice(),sutunSirasi:draft.sutunSirasi.slice(),ozelSutunlar:clone(draft.ozelSutunlar),sutunGenislikleri:clone(draft.sutunGenislikleri||{}),sutunHizalama:clone(draft.sutunHizalama||{}),baslikBilgisi:clone(draft.baslikBilgisi||{})});global.toast?.('Sütun düzeni cihazda şablon olarak kaydedildi.');}catch(e){global.toast?.(e?.message||'Şablon kaydedilemedi.');}}
function closeUI(){try{unsubscribe?.()}catch(_){}unsubscribe=null;editingId='';draft=null;selectedClass='';return true}
global.OgretmenListeUI={open:openUI,close:closeUI,render:renderUI,newDraft,openRecord,openReport,exportExcel};
global.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='tools'){prepare().catch(err=>console.warn('[OgretmenListe/prepare]',err?.message||err));queueMicrotask(ensureTab);}});
})(window);

/* Ödev / Not çizelgeleri — eski taslak editör davranışının local-first karşılığı. */
(function(global){
'use strict';
if(global.OdevNotUI)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const data=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>{try{return structuredClone(v)}catch(_){return JSON.parse(JSON.stringify(v))}};
const user=()=>global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};
let page='',type='',openId='',draft=null,dirty=false,unsubs=[];
function root(){return document.getElementById('v2ModuleRoot')}
function label(){return type==='odevTakip'?'Ödev Takip Çizelgesi':'Not Çizelgesi'}
function classes(){return data('siniflar').slice().sort((a,b)=>String(a.ad||a.sinifAdi||'').localeCompare(String(b.ad||b.sinifAdi||''),'tr',{numeric:true}))}
function className(c){return c?.ad||c?.sinifAdi||c?.sinif||'Sınıf'}
function studentName(v){return String(v?.ogrenciAdi||v?.adSoyad||[v?.ad,v?.soyad].filter(Boolean).join(' ')||'Öğrenci').trim()}
function studentsOf(id){return data('veliler').filter(v=>v.sinifId===id).slice().sort((a,b)=>Number(a.ogrenciNo||a.no||0)-Number(b.ogrenciNo||b.no||0)||studentName(a).localeCompare(studentName(b),'tr'))}
function books(){const u=user();return data(type).filter(x=>u.admin===true||x.sahipUid===u.uid).slice().sort((a,b)=>String(b.olusturmaTarihi||'').localeCompare(String(a.olusturmaTarihi||'')))}
function canEdit(k){return !!global.OdevNotCizelgeleriService?.sahibiMiyimYaAdminMiyim?.(k)}
function markDirty(){dirty=true}
function closeEditor(){if(dirty&&!global.confirm?.('Kaydedilmemiş değişiklikler var. Kapatılsın mı?'))return false;openId='';draft=null;dirty=false;render();return true}
function normalize(k){return{...clone(k),ogrenciler:Array.isArray(k.ogrenciler)?clone(k.ogrenciler):[],sutunlar:Array.isArray(k.sutunlar)?clone(k.sutunlar):[],hucreler:clone(k.hucreler||{}),hucreModu:k.hucreModu||(type==='notCizelgesi'?'artiEksi':'durum')}}
function openBook(id){if(dirty&&!global.confirm?.('Kaydedilmemiş değişiklikler var. Diğer çizelge açılsın mı?'))return;const k=books().find(x=>x.id===id);if(!k)return;openId=id;draft=normalize(k);dirty=false;render()}
function colId(){return`s_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`}
function newModal(){const cs=classes();document.querySelector('[data-on-new]')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="ka-modal-backdrop" data-on-new><form class="ka-modal" data-on-form><div class="ka-modal__header"><h2>Yeni ${esc(label())}</h2></div><div class="ka-modal__body ka-stack"><label class="ka-field"><span class="ka-field__label">Çizelge Adı</span><input name="ad" required></label><label class="ka-field"><span class="ka-field__label">Sınıf</span><select name="sinifId" required><option value="">Seçiniz</option>${cs.map(c=>`<option value="${esc(c.id)}">${esc(className(c))}</option>`).join('')}</select></label>${type==='notCizelgesi'?`<label class="ka-field"><span class="ka-field__label">Not Giriş Biçimi</span><select name="hucreModu"><option value="artiEksi">Artı / Eksi</option><option value="puan">Sayısal Puan</option></select></label>`:''}<div class="ka-grid"><label class="ka-field"><span class="ka-field__label">İlk Sütun Başlığı</span><input name="sutun" required placeholder="${type==='odevTakip'?'Ödev 1':'Değerlendirme 1'}"></label><label class="ka-field"><span class="ka-field__label">Sütun Tarihi</span><input name="tarih" type="date"></label></div></div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-close>Vazgeç</button><button class="ka-btn" type="submit">Oluştur</button></div></form></div>`);const ov=$('[data-on-new]'),close=()=>ov?.remove();ov.querySelector('[data-close]').onclick=close;ov.addEventListener('click',e=>{if(e.target===ov)close()});ov.querySelector('[data-on-form]').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),cid=String(fd.get('sinifId')||''),cls=cs.find(x=>x.id===cid),students=studentsOf(cid).map(v=>({id:v.id,ad:studentName(v),no:v.ogrenciNo||v.no||''}));if(!cid||!students.length)return global.toast?.('Seçilen sınıfta öğrenci bulunamadı.');const k={ad:String(fd.get('ad')||'').trim(),sinifId:cid,sinifAdi:className(cls),ogrenciler:students,sutunlar:[{id:colId(),baslik:String(fd.get('sutun')||'').trim(),tarih:String(fd.get('tarih')||'')}],hucreler:{},hucreModu:type==='odevTakip'?'durum':String(fd.get('hucreModu')||'artiEksi')};try{const ref=await global.OdevNotCizelgeleriService.cizelgeOlustur(type,k);close();global.toast?.('Çizelge oluşturuldu.');setTimeout(()=>openBook(ref?.id||''),0)}catch(err){global.toast?.(err?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Çizelge oluşturulamadı.')}}}
function addColumn(){if(!draft)return;const baslik=global.prompt?.('Sütun başlığı:',type==='odevTakip'?`Ödev ${draft.sutunlar.length+1}`:`Değerlendirme ${draft.sutunlar.length+1}`);if(!baslik?.trim())return;const tarih=global.prompt?.('Sütun tarihi (YYYY-AA-GG, boş bırakılabilir):','')??'';draft.sutunlar.push({id:colId(),baslik:baslik.trim(),tarih:String(tarih).trim()});markDirty();render()}
function editColumn(id){const c=draft?.sutunlar.find(x=>x.id===id);if(!c)return;const baslik=global.prompt?.('Sütun başlığı:',c.baslik||'');if(baslik===null)return;const tarih=global.prompt?.('Sütun tarihi (YYYY-AA-GG):',c.tarih||'');if(tarih===null)return;c.baslik=baslik.trim()||c.baslik;c.tarih=tarih.trim();markDirty();render()}
function removeColumn(id){if(!draft||!global.confirm?.('Bu sütun ve sütundaki tüm değerler kaldırılsın mı?'))return;draft.sutunlar=draft.sutunlar.filter(x=>x.id!==id);for(const key of Object.keys(draft.hucreler))if(key.endsWith('_'+id))delete draft.hucreler[key];markDirty();render()}
function addStudent(){if(!draft)return;const all=studentsOf(draft.sinifId),used=new Set(draft.ogrenciler.map(x=>x.id)),available=all.filter(x=>!used.has(x.id));if(!available.length)return global.toast?.('Sınıftaki tüm öğrenciler çizelgede.');const text=available.map((s,i)=>`${i+1}. ${studentName(s)}`).join('\n'),n=Number(global.prompt?.(`Eklenecek öğrencinin sıra numarası:\n${text}`,'1'));const s=available[n-1];if(!s)return;draft.ogrenciler.push({id:s.id,ad:studentName(s),no:s.ogrenciNo||s.no||''});markDirty();render()}
function removeStudent(id){if(!draft||!global.confirm?.('Öğrenci çizelgeden çıkarılsın mı?'))return;draft.ogrenciler=draft.ogrenciler.filter(x=>x.id!==id);for(const key of Object.keys(draft.hucreler))if(key.startsWith(id+'_'))delete draft.hucreler[key];markDirty();render()}
function cycleCell(studentId,columnId){if(!draft)return;const key=`${studentId}_${columnId}`,old=draft.hucreler[key]??'';let next='';if(type==='odevTakip')next=old==='✓'?'✗':old==='✗'?'':'✓';else if(draft.hucreModu==='puan'){const v=global.prompt?.('Puan:',String(old));if(v===null)return;next=v.trim();if(next!==''&&(isNaN(Number(next))||Number(next)<0))return global.toast?.('Geçerli bir puan girin.')}else next=old==='+'?'-':old==='-'?'':'+';draft.hucreler[key]=next;markDirty();render()}
async function save(){if(!draft)return;try{await global.OdevNotCizelgeleriService.taslagiKaydet(type,draft);dirty=false;global.toast?.('Çizelge kaydedildi.');const fresh=books().find(x=>x.id===draft.id);if(fresh)draft=normalize(fresh);render()}catch(e){global.toast?.(e?.message==='yetkisiz'?'Bu işlem için yetkiniz yok.':'Çizelge kaydedilemedi.')}}
function report(){if(!draft||!global.ReportEngine?.printReport)return global.toast?.('Rapor motoru hazır değil.');const cols=draft.sutunlar||[],cells=draft.hucreler||{},body=`<table><thead><tr><th>No</th><th>Öğrenci</th>${cols.map(c=>`<th>${esc(c.baslik||'Sütun')}${c.tarih?`<br><small>${esc(c.tarih)}</small>`:''}</th>`).join('')}</tr></thead><tbody>${draft.ogrenciler.map(s=>`<tr><td>${esc(s.no||'')}</td><td>${esc(s.ad||'Öğrenci')}</td>${cols.map(c=>`<td style="text-align:center">${esc(cells[`${s.id}_${c.id}`]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;global.ReportEngine.printReport(draft.ad||label(),body,{fileName:draft.ad||label(),yon:cols.length>5?'yatay':'dikey',ustBaslik:`${draft.sinifAdi||''} — ${label()}`})}
function editor(){if(!draft)return'';const editable=canEdit(draft),cols=draft.sutunlar||[],cells=draft.hucreler||{};return`<article class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><h3>${esc(draft.ad||label())}</h3><div class="ka-muted">${esc(draft.sinifAdi||'')} · ${draft.ogrenciler.length} öğrenci · ${cols.length} sütun${type==='notCizelgesi'?` · ${draft.hucreModu==='puan'?'Sayısal Puan':'Artı / Eksi'}`:''}</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-on-close>Kapat</button></div>${editable?`<div class="ka-row ka-wrap"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-on-add-col>+ Sütun</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-on-add-student>+ Öğrenci</button><button class="ka-btn" type="button" data-on-save>💾 Kaydet${dirty?' *':''}</button><button class="ka-btn ka-btn--secondary" type="button" data-on-report>🖨 A4 / PDF</button></div>`:`<button class="ka-btn ka-btn--secondary" type="button" data-on-report>🖨 A4 / PDF</button>`}<div class="ka-table-wrap"><table class="ka-table"><thead><tr><th>No</th><th>Öğrenci</th>${cols.map(c=>`<th><button type="button" class="ka-btn ka-btn--ghost ka-btn--sm" data-on-edit-col="${esc(c.id)}">${esc(c.baslik||'Sütun')}${c.tarih?`<br><small>${esc(c.tarih)}</small>`:''}</button>${editable?`<button class="ka-icon-button" type="button" data-on-remove-col="${esc(c.id)}">×</button>`:''}</th>`).join('')}</tr></thead><tbody>${draft.ogrenciler.map(s=>`<tr><td>${esc(s.no||'')}</td><td><div class="ka-row"><strong class="ka-grow">${esc(s.ad||'Öğrenci')}</strong>${editable?`<button class="ka-icon-button" type="button" data-on-remove-student="${esc(s.id)}">×</button>`:''}</div></td>${cols.map(c=>{const v=cells[`${s.id}_${c.id}`]??'';return`<td><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-on-cell data-student="${esc(s.id)}" data-col="${esc(c.id)}" ${editable?'':'disabled'}>${esc(v||'–')}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div></div></article>`}
function cards(){const rows=books();return rows.length?rows.map(k=>`<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(k.ad||label())}</strong><div class="ka-muted">${esc(k.sinifAdi||'')} · ${(k.ogrenciler||[]).length} öğrenci · ${(k.sutunlar||[]).length} sütun${type==='notCizelgesi'?` · ${k.hucreModu==='puan'?'Puan':'Artı/Eksi'}`:''}</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-on-open="${esc(k.id)}">Aç</button>${canEdit(k)?`<button class="ka-btn ka-btn--danger ka-btn--sm" type="button" data-on-delete="${esc(k.id)}">Sil</button>`:''}</div></article>`).join(''):'<div class="ka-empty">Henüz çizelge oluşturulmadı.</div>'}
function bind(){const r=root();if(!r)return;$('[data-on-new]',r)?.addEventListener('click',newModal);$('[data-on-close]',r)?.addEventListener('click',closeEditor);$('[data-on-add-col]',r)?.addEventListener('click',addColumn);$('[data-on-add-student]',r)?.addEventListener('click',addStudent);$('[data-on-save]',r)?.addEventListener('click',save);$('[data-on-report]',r)?.addEventListener('click',report);$$('[data-on-open]',r).forEach(b=>b.onclick=()=>openBook(b.dataset.onOpen));$$('[data-on-delete]',r).forEach(b=>b.onclick=async()=>{const k=books().find(x=>x.id===b.dataset.onDelete);if(!k||!global.confirm?.('Bu çizelge silinsin mi?'))return;try{await global.OdevNotCizelgeleriService.cizelgeSil(type,k);if(openId===k.id){openId='';draft=null;dirty=false;}global.toast?.('Çizelge silindi.')}catch(e){global.toast?.('Çizelge silinemedi.')}});$$('[data-on-cell]',r).forEach(b=>b.onclick=()=>cycleCell(b.dataset.student,b.dataset.col));$$('[data-on-edit-col]',r).forEach(b=>b.onclick=()=>editColumn(b.dataset.onEditCol));$$('[data-on-remove-col]',r).forEach(b=>b.onclick=()=>removeColumn(b.dataset.onRemoveCol));$$('[data-on-remove-student]',r).forEach(b=>b.onclick=()=>removeStudent(b.dataset.onRemoveStudent))}
function render(){const r=root();if(!r)return;const title=label(),rows=books();r.innerHTML=`<section class="ka-stack" data-on-ui><div class="ka-row ka-row--between"><div><h2>${esc(title)}</h2><p class="ka-muted">Değişiklikler taslakta tutulur; yalnız Kaydet düğmesiyle cihaz verisine yazılır.</p></div><div class="ka-row"><span class="ka-badge">${rows.length} çizelge</span><button class="ka-btn" type="button" data-on-new>+ Yeni</button></div></div>${draft?editor():cards()}</section>`;bind();global.PermissionService?.apply?.(r)}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.odevTakip','data.notCizelgesi','data.siniflar','data.veliler'].forEach(p=>{const u=global.AppStore?.subscribe?.(p,()=>{if(!dirty)requestAnimationFrame(render)});if(u)unsubs.push(u)})}
async function open(which){page=which;type=which==='homework'?'odevTakip':'notCizelgesi';openId='';draft=null;dirty=false;await global.ToolsData?.prepareGradebooks?.();subscribe();render();return true}
function close(){if(dirty&&!global.confirm?.('Kaydedilmemiş değişiklikler var. Sayfadan çıkılsın mı?'))return false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];draft=null;openId='';dirty=false;return true}
global.OdevNotUI={open,close,render,get page(){return page}};
})(window);
