/* Koruk Asistan v2 — Araçlar
 * Kontrol Listeleri + Harita + Çizelgeler + Devamsızlık + Ödev/Not.
 * Ayrı görünüm/CSS motorları oluşturulmaz; design-system bileşenleri kullanılır. */
(function(global){
'use strict';if(global.ToolsModule)return;
let mounted=false,active='checklists',unsubs=[],attendanceDate=new Date(),openGradebook='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const currentTeacherId=()=>global.ToolsData?.teacherId?.()||'';
const user=()=>global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{};
const FORM_LABELS={sosyalKulupler:'Sosyal Kulüpler',sok:'ŞÖK',zumre:'Zümre',bepPlani:'BEP Planı',rehberlik:'Rehberlik',maarifRapor:'Maarif Raporu',belirliGunler:'Belirli Günler',digerEvrak:'Diğer Evrak'};
function shell(){return `<section class="ka-stack" data-tools-module><div class="ka-row ka-row--between"><div><h2>Araçlar</h2><p class="ka-muted">Okul yönetimi yardımcı araçları cihaz verisinden çalışır.</p></div><span id="toolsCount" class="ka-badge"></span></div><div class="ka-tabs"><button class="ka-tab" data-tools-tab="checklists">Kontrol Listeleri</button><button class="ka-tab" data-tools-tab="map">Harita</button><button class="ka-tab" data-tools-tab="forms">Çizelgeler</button><button class="ka-tab" data-tools-tab="attendance">Devamsızlık</button><button class="ka-tab" data-tools-tab="gradebooks">Ödev / Not</button></div><div id="toolsContent" class="ka-stack"></div></section>`}
function completedFor(listId){const tid=currentTeacherId();return arr('kontrolListeTamamlama').find(x=>x.listeId===listId&&(!tid||x.ogretmenId===tid))||null}
function checklistCard(list){const items=Array.isArray(list.maddeler)?list.maddeler:[],done=completedFor(list.id),ids=new Set(done?.tamamlananMaddeIdler||[]),count=items.filter(x=>ids.has(x.id)).length,pct=items.length?Math.round(count/items.length*100):0;return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div class="ka-grow"><strong>${esc(list.ad||'Kontrol Listesi')}</strong><div class="ka-muted">${esc(list.aciklama||`${items.length} madde`)}</div></div><span class="ka-badge">${count}/${items.length}</span></div>${items.length?`<div class="ka-stack">${items.map(item=>`<label class="ka-row"><input type="checkbox" data-tools-check="${esc(list.id)}" data-item-id="${esc(item.id)}" ${ids.has(item.id)?'checked':''}><span>${esc(item.ikon||'')} ${esc(item.metin||item.ad||'Madde')}</span></label>`).join('')}</div>`:'<div class="ka-empty">Bu listede madde bulunmuyor.</div>'}<div class="ka-muted">Tamamlanma: %${pct}</div></div></article>`}
function renderChecklists(){const lists=arr('kontrolListeleri').slice().sort((a,b)=>(Number(a.sira)||0)-(Number(b.sira)||0)),content=document.getElementById('toolsContent'),count=document.getElementById('toolsCount');if(count)count.textContent=`${lists.length} liste`;if(content)content.innerHTML=lists.length?lists.map(checklistCard).join(''):'<div class="ka-empty">Kontrol listesi bulunamadı.</div>';bindChecks()}
function mapFavoriteCard(f){const coords=(f.lat!=null&&f.lng!=null)?`${Number(f.lat).toFixed(5)}, ${Number(f.lng).toFixed(5)}`:(f.koordinat||f.adres||'Konum bilgisi yok');return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(f.ad||f.baslik||'Favori Konum')}</strong><div class="ka-muted">${esc(coords)}</div>${f.olusturanAdi?`<div class="ka-muted">${esc(f.olusturanAdi)}</div>`:''}</div>${global.HaritaService?.favoriSilinebilirMi?.(f)?`<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-map-remove="${esc(f.id)}">Sil</button>`:''}</div></article>`}
function routeCard(s){const km=Number(s.guzergahMesafe);return `<article class="ka-card ka-list-card"><div class="ka-card__body"><strong>${esc(s.ad||s.servisAdi||s.guzergah||'Servis')}</strong><div class="ka-muted">${Number.isFinite(km)?`${km.toFixed(1)} km`:'Mesafe kaydı yok'} · ${Array.isArray(s.guzergahKoordinatlar)?s.guzergahKoordinatlar.length:0} rota noktası</div></div></article>`}
function renderMap(){const favorites=global.HaritaService?.gorunurFavoriler?.(arr('haritaFavoriler'))||[],routes=arr('servisler').filter(s=>s.guzergahMesafe!=null||Array.isArray(s.guzergahKoordinatlar)),content=document.getElementById('toolsContent'),count=document.getElementById('toolsCount');if(count)count.textContent=`${favorites.length} favori`;if(content)content.innerHTML=`<div class="ka-grid"><section class="ka-stack"><div class="ka-row ka-row--between"><h3>Favori Konumlar</h3><span class="ka-badge">${favorites.length}</span></div>${favorites.length?favorites.map(mapFavoriteCard).join(''):'<div class="ka-empty">Favori konum bulunamadı.</div>'}</section><section class="ka-stack"><div class="ka-row ka-row--between"><h3>Servis Güzergâhları</h3><span class="ka-badge">${routes.length}</span></div>${routes.length?routes.map(routeCard).join(''):'<div class="ka-empty">Kayıtlı servis güzergâhı bulunamadı.</div>'}</section></div>`;bindMap()}
function recordTitle(r){return r.ad||r.baslik||r.konu||r.sinif||r.ogretmenAdi||r.aciklama||'Kayıt'}
function renderForms(){const types=global.ToolsData?.FORM_TYPES||[],sections=types.map(t=>{const rows=arr(t),preview=rows.slice(0,5);return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>${esc(FORM_LABELS[t]||t)}</strong><span class="ka-badge">${rows.length} kayıt</span></div>${preview.length?preview.map(r=>`<div class="ka-row ka-row--between"><span>${esc(recordTitle(r))}</span><span class="ka-muted">${esc(r.tarih||r.donem||r.yil||'')}</span></div>`).join(''):'<div class="ka-empty">Kayıt bulunamadı.</div>'}${rows.length>5?'<div class="ka-muted">İlk 5 kayıt gösteriliyor.</div>':''}</div></article>`}),total=types.reduce((n,t)=>n+arr(t).length,0),content=document.getElementById('toolsContent'),count=document.getElementById('toolsCount');if(count)count.textContent=`${total} kayıt`;if(content)content.innerHTML=sections.join('')}
function monthDoc(){const y=attendanceDate.getFullYear(),m=attendanceDate.getMonth()+1;return arr('devamsizlikCizelgesi').find(x=>x.id===`${y}-${m}`)||null}
function attCounts(gunler){const vals=Object.values(gunler||{});return {izin:vals.filter(x=>x==='İ').length,rapor:vals.filter(x=>x==='R').length,tatil:vals.filter(x=>x==='T').length,gorev:vals.filter(x=>x==='+').length};}
function attTeacherCard(o,y,m){const gunler=o.gunler||{},c=attCounts(gunler),days=Array.from({length:new Date(y,m,0).getDate()},(_,i)=>i+1);return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><strong>${esc(o.adSoyad||o.ad||o.ogretmenId)}</strong><div class="ka-muted">${esc(o.gorev||'')}</div></div><span class="ka-badge">İ:${c.izin} R:${c.rapor} T:${c.tatil} +:${c.gorev}</span></div><div class="ka-row ka-wrap">${days.map(g=>{const v=gunler[g];return `<button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-att-day="${g}" data-att-teacher="${esc(o.ogretmenId||'')}"><span>${g}</span>&nbsp;<strong>${esc(v??'–')}</strong></button>`}).join('')}</div></div></article>`}
function renderAttendance(){const y=attendanceDate.getFullYear(),m=attendanceDate.getMonth()+1,doc=monthDoc(),teachers=Object.values(doc?.ogretmenler||{}),content=document.getElementById('toolsContent'),count=document.getElementById('toolsCount');if(count)count.textContent=`${teachers.length} personel`;if(content)content.innerHTML=`<div class="ka-row ka-row--between"><button class="ka-btn ka-btn--secondary" type="button" data-att-nav="-1">‹ Önceki</button><div><strong>${attendanceDate.toLocaleDateString('tr-TR',{month:'long',year:'numeric'})}</strong><div class="ka-muted">Belge: ${y}-${m}</div></div><button class="ka-btn ka-btn--secondary" type="button" data-att-nav="1">Sonraki ›</button></div>${teachers.length?teachers.map(o=>attTeacherCard(o,y,m)).join(''):'<div class="ka-empty">Bu ay için devamsızlık çizelgesi bulunamadı.</div>'}`;bindAttendance()}
function gradeTitle(t){return t==='odevTakip'?'Ödev Takip':'Not Çizelgesi'}
function gradeTable(t,k){const students=k.ogrenciler||[],cols=k.sutunlar||[],cells=k.hucreler||{};if(!students.length||!cols.length)return '<div class="ka-empty">Öğrenci veya sütun bulunmuyor.</div>';return `<div class="ka-table-wrap"><table class="ka-table"><thead><tr><th>Öğrenci</th>${cols.map(c=>`<th>${esc(c.baslik||'Sütun')}</th>`).join('')}</tr></thead><tbody>${students.map(s=>`<tr><td>${esc(s.ad||'Öğrenci')}</td>${cols.map(c=>{const key=s.id+'_'+c.id,v=cells[key]??'';return `<td><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-grade-cell="${esc(key)}" data-grade-type="${t}" data-grade-id="${esc(k.id)}">${esc(v||'–')}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
function gradeCard(t,k){const open=openGradebook===`${t}:${k.id}`;return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><div><strong>${esc(k.ad||gradeTitle(t))}</strong><div class="ka-muted">${esc(k.sinifId||'Sınıf yok')} · ${(k.ogrenciler||[]).length} öğrenci · ${(k.sutunlar||[]).length} sütun</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-grade-open="${t}:${esc(k.id)}">${open?'Kapat':'Aç'}</button></div>${open?gradeTable(t,k):''}</div></article>`}
function renderGradebooks(){const u=user(),types=['odevTakip','notCizelgesi'],sections=types.map(t=>{const rows=arr(t).filter(x=>u.admin===true||x.sahipUid===u.uid);return `<section class="ka-stack"><div class="ka-row ka-row--between"><h3>${gradeTitle(t)}</h3><span class="ka-badge">${rows.length}</span></div>${rows.length?rows.map(k=>gradeCard(t,k)).join(''):'<div class="ka-empty">Kayıt bulunamadı.</div>'}</section>`}),total=types.reduce((n,t)=>n+arr(t).filter(x=>u.admin===true||x.sahipUid===u.uid).length,0),content=document.getElementById('toolsContent'),count=document.getElementById('toolsCount');if(count)count.textContent=`${total} çizelge`;if(content)content.innerHTML=sections.join('');bindGradebooks()}
function render(){if(!mounted)return;document.querySelectorAll('[data-tools-tab]').forEach(b=>b.classList.toggle('active',b.dataset.toolsTab===active));if(active==='map')renderMap();else if(active==='forms')renderForms();else if(active==='attendance')renderAttendance();else if(active==='gradebooks')renderGradebooks();else renderChecklists()}
function bindChecks(){document.querySelectorAll('[data-tools-check]').forEach(input=>{input.onchange=async()=>{const tid=currentTeacherId(),listId=input.dataset.toolsCheck,itemId=input.dataset.itemId;if(!tid){input.checked=!input.checked;if(typeof toast==='function')toast('Bağlı öğretmen kaydı bulunamadı.');return}const existing=completedFor(listId),ids=new Set(existing?.tamamlananMaddeIdler||[]);input.checked?ids.add(itemId):ids.delete(itemId);try{await global.KontrolListeleriService.tamamlamaKaydet(tid,listId,[...ids]);}catch(e){input.checked=!input.checked;console.warn('[Tools]',e?.message||e)}}})}
function bindMap(){document.querySelectorAll('[data-map-remove]').forEach(btn=>{btn.onclick=async()=>{const f=arr('haritaFavoriler').find(x=>x.id===btn.dataset.mapRemove);if(!f)return;try{await global.HaritaService.favoriSil(f.id,f)}catch(e){console.warn('[Tools/Harita]',e?.message||e)}}})}
function bindAttendance(){document.querySelectorAll('[data-att-nav]').forEach(b=>b.onclick=async()=>{attendanceDate=new Date(attendanceDate.getFullYear(),attendanceDate.getMonth()+Number(b.dataset.attNav),1);renderAttendance()});document.querySelectorAll('[data-att-day]').forEach(b=>b.onclick=async()=>{const y=attendanceDate.getFullYear(),m=attendanceDate.getMonth()+1,doc=monthDoc(),o=doc?.ogretmenler?.[b.dataset.attTeacher];if(!o)return;const old=o.gunler?.[b.dataset.attDay]??'',next=global.prompt?.(`Kod girin (D, İ, Y, R, T, + veya saat):`,String(old));if(next===null)return;try{await global.DevamsizlikCizelgesiService.gunGuncelle(y,m,b.dataset.attTeacher,b.dataset.attDay,next.trim())}catch(e){if(typeof toast==='function')toast(e.message||'Güncellenemedi.')}})}
function bindGradebooks(){document.querySelectorAll('[data-grade-open]').forEach(b=>b.onclick=()=>{openGradebook=openGradebook===b.dataset.gradeOpen?'':b.dataset.gradeOpen;renderGradebooks()});document.querySelectorAll('[data-grade-cell]').forEach(b=>b.onclick=async()=>{const t=b.dataset.gradeType,k=arr(t).find(x=>x.id===b.dataset.gradeId);if(!k)return;const [studentId,colId]=b.dataset.gradeCell.split(/_(?=s_)/);const old=k.hucreler?.[b.dataset.gradeCell]??'';let next;if(t==='odevTakip')next=old==='✓'?'✗':old==='✗'?'':'✓';else if(k.hucreModu==='puan'){const val=global.prompt?.('Puan:',String(old));if(val===null)return;next=val.trim();if(next!==''&&(isNaN(Number(next))||Number(next)<0)){if(typeof toast==='function')toast('Geçerli bir puan girin.');return}}else next=old==='+'?'-':old==='-'?'':'+';try{await global.OdevNotCizelgeleriService.hucreGuncelle(t,k,studentId,colId,next)}catch(e){console.warn('[Tools/ÖdevNot]',e?.message||e)}})}
function bind(){document.querySelectorAll('[data-tools-tab]').forEach(b=>b.onclick=async()=>{active=b.dataset.toolsTab;if(active==='map')await global.ToolsData?.prepareMap?.();if(active==='forms')await global.ToolsData?.prepareForms?.();if(active==='attendance')await global.ToolsData?.prepareAttendance?.();if(active==='gradebooks')await global.ToolsData?.prepareGradebooks?.();render()})}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];const paths=['data.kontrolListeleri','data.kontrolListeTamamlama','data.haritaFavoriler','data.servisler','data.devamsizlikCizelgesi','data.odevTakip','data.notCizelgesi',...(global.ToolsData?.FORM_TYPES||[]).map(t=>'data.'+t)];paths.forEach(p=>{const u=global.AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await global.ToolsData?.prepareControlLists?.();render();return true}
function unmount(){mounted=false;unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
global.ToolsModule={mount,unmount,render};global.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='tools')mount()});
})(window);
