/* Koruk Asistan — Transport tek modül
 * Veri/repository/service + araç yerleşim şeması + rapor + UI aynı dosyada.
 * Veri akışı: DeviceData/IndexedDB -> AppStore -> UI; Firestore yalnız arka plan senkronizasyonudur.
 */
(function(global){
'use strict';
function device(){if(!global.DeviceData)throw new Error('DeviceData hazır değil.');return global.DeviceData;}
function localDoc(type,id){return device().get(type,id)}
function activeUser(){return global.AKTIF_KULLANICI||global.AppStore?.get?.('session.user')||{}}
function activeTeacherId(){const u=activeUser();return u.bagliOgretmenId||u.ogretmenId||''}
function isTeacherUser(){const u=activeUser();return u.admin!==true&&!!activeTeacherId()}
function ownsClass(id){const tid=activeTeacherId();if(!tid)return false;const s=localDoc('siniflar',id)||device().list('siniflar').find(x=>x.id===id);return s?.sinifOgretmeniId===tid}
function fakeDoc(row,id){return{exists:!!row,id:id||row?.id||'',data:()=>row?{...row}:undefined}}
function fakeQuery(rows){const docs=(rows||[]).map(r=>({id:r.id,data:()=>({...r})}));return{empty:docs.length===0,size:docs.length,docs}}
const SO_SEMA_VERSIYON=2;
function duzenA(siraMax=7){const y=[];y.push({sira:0,konum:'sag-ic',aktif:true},{sira:0,konum:'sag-dis',aktif:true},{sira:1,konum:'sol-dis',kapiSag:true,aktif:true},{sira:1,konum:'sol-ic',kapiSag:true,aktif:true});for(let s=2;s<=siraMax;s++)y.push({sira:s,konum:'sol-dis',aktif:true},{sira:s,konum:'sol-ic',aktif:true},{sira:s,konum:'sag-dis',aktif:true});for(let k=0;k<4;k++)y.push({sira:siraMax+1,konum:'arka',aktif:true});return y;}
function duzenB(siraMax=5){const y=[{sira:0,konum:'sol-dis',soforYani:true,kapiSag:true,aktif:true}];for(let s=1;s<=siraMax;s++)y.push({sira:s,konum:'sol-dis',aktif:true},{sira:s,konum:'sol-ic',aktif:true},{sira:s,konum:'sag-ic',aktif:true},{sira:s,konum:'sag-dis',aktif:true});y.push({sira:siraMax+1,konum:'sol-dis',kapiSag:true,aktif:true},{sira:siraMax+1,konum:'sol-ic',kapiSag:true,aktif:true});for(let k=0;k<4;k++)y.push({sira:siraMax+2,konum:'arka',aktif:true});return y;}
const SO_SABLONLAR={ducato:{ad:'Fiat Ducato',ikon:'🚐',aciklama:'2+1 düzen, orta boy',yerlesimUret:(n=7)=>duzenA(n)},'ford-transit':{ad:'Ford Transit',ikon:'🚐',aciklama:'2+1 düzen, kompakt',yerlesimUret:(n=6)=>duzenA(n)},'mercedes-sprinter':{ad:'Mercedes Sprinter',ikon:'🚐',aciklama:'2+1 düzen, uzun şasi',yerlesimUret:(n=8)=>duzenA(n)},'vw-crafter':{ad:'Volkswagen Crafter',ikon:'🚐',aciklama:'2+1 düzen',yerlesimUret:(n=7)=>duzenA(n)},buyuk:{ad:'Büyük Servis',ikon:'🚍',aciklama:'2+2 düzen + arka sıra',yerlesimUret:(n=5)=>duzenB(n)},midibus:{ad:'Midibüs',ikon:'🚌',aciklama:'2+2 düzen, orta boy',yerlesimUret:(n=7)=>duzenB(n)},ozel:{ad:'Özel Tasarım',ikon:'🛠️',aciklama:'Manuel yerleşim',yerlesimUret:()=>[]}};
function legacyToElements(yerlesim,koltuklar){koltuklar=Array.isArray(koltuklar)?koltuklar:[];return(yerlesim||[]).map((yuva,idx)=>{const no=idx+1,k=koltuklar.find(x=>Number(x.no)===no),p={konum:yuva.konum||'',kapiSag:!!yuva.kapiSag,soforYani:!!yuva.soforYani,studentName:k?.ogrenciAdi||'',stop:k?.durak||'',note:k?.not||'',reserved:!!k?.rezerve};return{id:'el_'+no,type:yuva.soforYani?'sofor':yuva.konum==='arka'?'arka-koltuk':'koltuk',seatNumber:yuva.soforYani?null:no,studentId:k?.ogrenciId||null,row:yuva.sira,column:idx,x:null,y:null,rotation:0,locked:!!k?.kilit,visible:yuva.aktif!==false,color:k?.renk||null,properties:p};});}
function elementsToLegacy(elements){const yerlesim=[],koltuklar=[];(elements||[]).forEach((el,idx)=>{const no=idx+1,p=el.properties||{},yuva={sira:el.row,konum:p.konum||'',aktif:el.visible!==false};if(p.soforYani)yuva.soforYani=true;if(p.kapiSag)yuva.kapiSag=true;yerlesim.push(yuva);if(el.type!=='sofor'&&(el.studentId||p.studentName||p.reserved||p.stop||p.note||el.color||el.locked))koltuklar.push({no,ogrenciId:el.studentId||null,ogrenciAdi:p.studentName||'',rezerve:!!p.reserved,durak:p.stop||'',not:p.note||'',renk:el.color||null,kilit:!!el.locked});});return{yerlesim,koltuklar};}
function planElements(plan,sablon){const sb=sablon||plan?.sablon||'ducato';if(Array.isArray(plan?.elements)&&plan.elements.length)return structuredClone(plan.elements);const yerlesim=Array.isArray(plan?.yerlesim)&&plan.yerlesim.length?plan.yerlesim:(SO_SABLONLAR[sb]?.yerlesimUret()||[]);return legacyToElements(yerlesim,plan?.koltuklar||[]);}
function elementStats(elements){const seats=(elements||[]).filter(e=>e.type!=='sofor'&&e.visible!==false),dolu=seats.filter(e=>e.studentId||e.properties?.studentName).length,rezerve=seats.filter(e=>e.properties?.reserved&&!(e.studentId||e.properties?.studentName)).length,toplam=seats.length;return{toplam,dolu,bos:Math.max(0,toplam-dolu-rezerve),rezerve,doluluk:toplam?Math.round(dolu/toplam*100):0};}
global.SO_SABLONLAR=SO_SABLONLAR;global.soPlanElementleriGetir=planElements;global.soElementIstatistik=elementStats;
const TasimaRepository={servisleriDinle(callback){return device().listen('servisler',callback);},servisEkle(veri){return device().add('servisler',COL.servisler,{...veri,eklenmeTarihi:new Date().toISOString()});},servisGuncelle(id,veri){return device().update('servisler',COL.servisler,id,veri);},servisSil(id){return device().remove('servisler',COL.servisler,id);}};global.TasimaRepository=TasimaRepository;
const TasimaService={_yetkiKontrol(){const ok=global.PermissionService?PermissionService.can('transport.services.edit','edit'):duzenleyebilir('tasima');if(!ok){toast?.('Bu işlem için yetkiniz yok.');return false;}return true;},servisKaydet(id,veri){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return id?TasimaRepository.servisGuncelle(id,veri):TasimaRepository.servisEkle(veri);},servisSil(id){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return TasimaRepository.servisSil(id);},ogrencileriServiseAta(ids,servisId,servisAdi){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return Promise.all((ids||[]).map(id=>device().update('veliler',COL.veliler,id,{servisId,servisAdi})));}};global.TasimaService=TasimaService;
const ServisOturmaRepository={planlariDinle(callback){return device().listen('servisOturma',callback);},planKaydet(servisId,veri,merge){return device().set('servisOturma',COL.servisOturma,servisId,{servisId,...veri},{merge:!!merge});},planGuncelle(servisId,veri){return device().update('servisOturma',COL.servisOturma,servisId,veri);},planServisIdIleGetir(servisId){return Promise.resolve(fakeQuery(device().list('servisOturma').filter(x=>x?.servisId===servisId||x?.id===servisId)));}};global.ServisOturmaRepository=ServisOturmaRepository;
const ServisOturmaService={_yetkiKontrol(){if(isTeacherUser()){toast?.('Öğretmen kullanıcıları servis oturma planını yalnız görüntüleyebilir.');return false;}const ok=global.PermissionService?PermissionService.can('transport.seating.edit','edit'):duzenleyebilir('tasima');if(!ok){toast?.('Bu işlem için yetkiniz yok.');return false;}return true;},planKaydet(servisId,veri,merge){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return ServisOturmaRepository.planKaydet(servisId,veri,merge);},planGuncelle(servisId,veri){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));return ServisOturmaRepository.planGuncelle(servisId,veri);},planElementsGetir(servisId,sablon='ducato'){return planElements(localDoc('servisOturma',servisId)||{},sablon);},planElementsKaydet(servisId,sablon,elements,merge=false){if(!this._yetkiKontrol())return Promise.reject(new Error('yetkisiz'));const legacy=elementsToLegacy(elements);return ServisOturmaRepository.planKaydet(servisId,{sablon,elements,...legacy,semaVersiyon:SO_SEMA_VERSIYON,guncellendi:new Date().toISOString()},merge);},sablonUygula(servisId,sablon){const elements=legacyToElements(SO_SABLONLAR[sablon]?.yerlesimUret?.()||[],[]);return this.planElementsKaydet(servisId,sablon,elements,false);}};global.ServisOturmaService=ServisOturmaService;
const SinifOturmaRepository={planGetir(id){return Promise.resolve(fakeDoc(localDoc('sinifOturma',id),id));},planDinle(id,cb){const run=()=>{const r=localDoc('sinifOturma',id);cb(r?{id,...r}:null,{source:'device'});};run();return AppStore.subscribe('data.sinifOturma',run);},planKaydet(id,veri){return device().set('sinifOturma',COL.sinifOturma,id,{sinifId:id,...veri},{merge:false});}};global.SinifOturmaRepository=SinifOturmaRepository;
const SinifOturmaService={_yetkiKontrol(id){const u=activeUser(),ok=isTeacherUser()?ownsClass(id):(u.admin===true||(global.PermissionService?PermissionService.can('transport.classSeating.edit','edit'):duzenleyebilir('siniflar')));if(!ok){toast?.('Bu sınıf oturma planını düzenleme yetkiniz yok.');return false;}return true;},planGetir:id=>SinifOturmaRepository.planGetir(id),planDinle(id,cb,hata){try{return SinifOturmaRepository.planDinle(id,cb);}catch(e){hata?.(e);return()=>{};}},planKaydet(id,veri){if(!this._yetkiKontrol(id))return Promise.reject(new Error('yetkisiz'));return SinifOturmaRepository.planKaydet(id,veri);}};global.SinifOturmaService=SinifOturmaService;
})(window);

(function(global){
'use strict';
if(global.TransportReports)return;
const arr=t=>{const v=global.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const escReport=v=>global.ReportEngine?.esc?.(v)??String(v??'');
const AYLAR=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
const GUNLER=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];
const DENETIM=[['Aracın yaşı "Okul Servis Araçları Yönetmeliği"nde yer alan yaş şartına uygun mu?','Okul Servis Araçları Yönetmeliği 4/1-f'],['Okul servis aracı temiz, bakımlı, güvenli ve her fırsatta havalandırılmış vaziyette bulunduruluyor mu?','Okul Servis Araçları Yönetmeliği 4/1-e'],['Taşıma işinin gerçekleştirildiği okul servis aracı, yüklenici tarafından idareye bildirilen araç mı?','Teknik Şartname'],['Taşımayı gerçekleştiren şoför idareye bildirilen kişi mi?','Teknik Şartname'],['"Sürücü Belgesi" taşıma hizmeti veren aracın kullanımı için yeterli ve uygun mu?','Okul Servis Araçları Yönetmeliği 9/1-c'],['Aracın camları, renkli film tabakaları yapıştırılması yasağına uygun mu?','Okul Servis Araçları Yönetmeliği 4/1-n'],['Aracın arkasında "OKUL TAŞITI" yazısını kapsayan numunesine uygun reflektif kuşak var mı?','Okul Servis Araçları Yönetmeliği 4/1-a'],['En az 30 cm çapında kırmızı ışık veren, üzerinde "DUR" yazısı okunan lamba tesis edilmiş mi?','Okul Servis Araçları Yönetmeliği 4/1-b'],['Öğrencilerin emniyet kemeri takmaları sağlanıyor mu?','MEB Taşıma Yoluyla Eğitime Erişim Yönetmeliği 15/2-ğ'],['Araca taşıma kapasitesi üzerinde öğrenci/kursiyer/veli alınıyor mu?','Teknik Şartname'],['Taşıma merkezi okul/kurum müdürlüğünce düzenlenen puantaj cetvelleri günlük düzenli olarak imzalanıyor mu?','MEB TYEE 15/2-e / Teknik Şartname'],['Şoför, temiz ve işe uygun kıyafetlerle çalışıyor mu?','Teknik Şartname'],['Şoför, öğrencilerin güvenli ve rahat yolculuk yapmasını sağlayarak azami sürelere uyuyor mu?','Okul Servis Araçları Yönetmeliği 9/1-ğ'],['Rehber personel (varsa), TS EN ISO 20471 standardına uygun "REHBER" yazılı ikaz yeleğini kullanıyor mu?','Okul Servis Araçları Yönetmeliği 9/2-f'],['Servis aracında "İlkyardım Çantası" bulunuyor mu?','Teknik Şartname'],['Servis aracında "Trafik Seti" bulunuyor mu?','Teknik Şartname'],['Servis aracında bakımlı ve süresi geçmemiş yangın söndürme tüpü bulunuyor mu?','Teknik Şartname'],['Araçta öğrencilerin kolayca yetişebileceği camlar ve pencereler sabit mi?','Okul Servis Araçları Yönetmeliği 4/1-c'],['Aracın iç düzenlemesinde açıkta olan demir aksam yumuşak bir madde ile kaplanmış mı?','Okul Servis Araçları Yönetmeliği 4/1-c']];
function school(){const rows=arr('okulBilgileri');return rows.find(x=>x.id==='ayarlar')||rows[0]||{}}
function teachers(){return arr('ogretmenler')}
function adminNames(){const o=school(),ts=teachers(),mudur=ts.find(t=>t.id===o.mudurId)||ts.find(t=>(t.unvan||'').trim()==='Müdür'),yrd=ts.find(t=>(t.unvan||'').trim()==='Müdür Yardımcısı'),name=t=>t?`${t.ad||''} ${t.soyad||''}`.trim():'';return{mudur:name(mudur),yardimci:name(yrd)}}
function reportService(id){return arr('servisler').find(s=>s.id===id)||null}
function reportStudents(id){const classes=arr('siniflar');return arr('veliler').filter(v=>v.servisId===id).map(v=>({id:v.id,ad:v.ogrenciAdi||'',sinif:classes.find(s=>s.id===v.sinifId)?.ad||v.sinifAdi||''})).sort((a,b)=>a.ad.localeCompare(b.ad,'tr'))}
function schoolTitle(){const o=school(),parts=[];if(o.il)parts.push(`${String(o.il).toLocaleUpperCase('tr')} İLİ`);if(o.ilce)parts.push(`${String(o.ilce).toLocaleUpperCase('tr')} İLÇESİ`);parts.push(String(o.okulAdi||'KORUK İLK-ORTAOKULU').toLocaleUpperCase('tr'));return parts.join(' ')}
async function prepareReports(){if(!global.SyncEngine||!global.COL)return;const defs={okulBilgileri:COL.okulBilgileri,resmiTatiller:COL.resmiTatiller},types=[];for(const[t,c]of Object.entries(defs)){if(c){SyncEngine.register(t,c);types.push(t)}}if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(60)}}
function signatures(){const a=adminNames();return `<table><tbody><tr><td><strong>${escReport(a.yardimci)}</strong><br>Müdür Yardımcısı</td><td><strong>${escReport(a.mudur)}</strong><br>Okul Müdürü</td></tr></tbody></table>`}
async function denetim(servisId){await prepareReports();const s=reportService(servisId);if(!s)throw new Error('servis-bulunamadi');const count=reportStudents(servisId).length,rows=DENETIM.map(([m,r],i)=>`<tr><td>${i+1}. ${escReport(m)}<br><small>(${escReport(r)})</small></td><td></td><td></td><td></td></tr>`).join(''),body=`<h1>${escReport(schoolTitle())}</h1><h2>OKUL SERVİS ARACI DENETİM FORMU</h2><table><tbody><tr><th>Servis</th><td>${escReport(s.servisAdi||s.guzergah||'')}</td><th>Plaka</th><td>${escReport(s.plaka||'')}</td></tr><tr><th>Sürücü</th><td>${escReport(s.soforAdi||'')}</td><th>Telefon</th><td>${escReport(s.soforTelefon||'')}</td></tr><tr><th>Öğrenci Sayısı</th><td>${count}</td><th>Tarih</th><td>${new Date().toLocaleDateString('tr-TR')}</td></tr></tbody></table><table><thead><tr><th>DENETLEME KONULARI</th><th>EVET</th><th>HAYIR</th><th>AÇIKLAMALAR</th></tr></thead><tbody>${rows}</tbody></table>${signatures()}`;return ReportEngine.printReport('Okul Servis Aracı Denetim Formu',body,{fileName:`${s.plaka||'Servis'}_Denetim`,yon:'dikey'})}
function holiday(iso){const t=arr('resmiTatiller').find(x=>x.tarih===iso);return t?(t.aciklama||t.ad||'Resmî Tatil'):null}
function dateIso(y,m,d){return`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function studentTable(list){const rows=[...list];while(rows.length<30)rows.push({ad:'',sinif:''});return `<table><thead><tr><th>Sıra</th><th>Öğrenci Adı Soyadı</th><th>Sınıf</th></tr></thead><tbody>${rows.map((o,i)=>`<tr><td>${i+1}</td><td>${escReport(o.ad)}</td><td>${escReport(o.sinif)}</td></tr>`).join('')}</tbody></table>`}
function dailyRows(y,m){const last=new Date(y,m+1,0).getDate();let out='';for(let d=1;d<=last;d++){const dt=new Date(y,m,d),weekend=dt.getDay()===0||dt.getDay()===6,iso=dateIso(y,m,d),h=!weekend&&holiday(iso),label=`${d} ${AYLAR[m]} ${y} ${GUNLER[dt.getDay()]}`,mark=weekend?'Hafta Sonu':h?'Resmî Tatil':'';out+=`<tr><td>${escReport(label)}</td>${mark?`<td colspan="8">${escReport(mark)}</td>`:'<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>'}</tr>`}return out}
async function takip(servisId,yil=new Date().getFullYear(),ay=new Date().getMonth()){await prepareReports();const s=reportService(servisId);if(!s)throw new Error('servis-bulunamadi');const ayAdi=`${AYLAR[ay].toLocaleUpperCase('tr')} - ${yil}`,body=`<h1>${escReport(schoolTitle())}</h1><h2>${escReport(ayAdi)} TAŞIMA TAKİP ÇİZELGESİ</h2><table><tbody><tr><th>Servis</th><td>${escReport(s.servisAdi||s.guzergah||'')}</td><th>Sürücü</th><td>${escReport(s.soforAdi||'')}</td></tr><tr><th>Plaka</th><td>${escReport(s.plaka||'')}</td><th>Telefon</th><td>${escReport(s.soforTelefon||'')}</td></tr></tbody></table>${studentTable(reportStudents(servisId))}<table><thead><tr><th rowspan="2">Tarih</th><th colspan="4">Öğle</th><th colspan="4">Akşam</th></tr><tr><th>Geliş Saati</th><th>Gelen Sayı</th><th>Şoför İmza</th><th>N. Öğrt. İmza</th><th>Çıkış Saati</th><th>Giden Sayı</th><th>Şoför İmza</th><th>N. Öğrt. İmza</th></tr></thead><tbody>${dailyRows(yil,ay)}</tbody></table>${signatures()}`;return ReportEngine.printReport(`${ayAdi} Taşıma Takip Çizelgesi`,body,{fileName:`${s.plaka||'Servis'}_${AYLAR[ay]}_${yil}_Takip`,yon:'dikey'})}
function takipSec(servisId){const now=new Date(),ov=document.createElement('div');ov.id='transportReportPicker';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><strong>Aylık Taşıma Takip Çizelgesi</strong><button class="ka-btn ka-btn--secondary ka-btn--sm" data-close type="button">Kapat</button></div><div class="ka-modal__body ka-grid"><label class="ka-field"><span class="ka-field__label">Yıl</span><input id="trYear" type="number" min="2020" max="2100" value="${now.getFullYear()}"></label><label class="ka-field"><span class="ka-field__label">Ay</span><select id="trMonth">${AYLAR.map((a,i)=>`<option value="${i}" ${i===now.getMonth()?'selected':''}>${a}</option>`).join('')}</select></label></div><div class="ka-modal__footer"><button class="ka-btn" data-print type="button">Yazdır / PDF</button></div></section>`;document.body.appendChild(ov);ov.querySelector('[data-close]').onclick=()=>ov.remove();ov.querySelector('[data-print]').onclick=async()=>{const b=ov.querySelector('[data-print]');b.disabled=true;try{await takip(servisId,Number(ov.querySelector('#trYear').value),Number(ov.querySelector('#trMonth').value));ov.remove()}catch(e){toast?.('Rapor hazırlanamadı: '+(e?.message||e));b.disabled=false}}}
global.TransportReports={prepare:prepareReports,denetim,takip,takipSec};
})(window);

(function(){
'use strict';if(window.TransportModule)return;
let active='services',query='',mounted=false,unsubs=[],editor=null;
const uiUser=()=>window.AKTIF_KULLANICI||window.AppStore?.get?.('session.user')||{};
const uiTeacherId=()=>{const u=uiUser();return u.bagliOgretmenId||u.ogretmenId||''};
const uiTeacher=()=>uiUser().admin!==true&&!!uiTeacherId();
const classOwn=id=>{const t=uiTeacherId(),s=arr('siniflar').find(x=>x.id===id);return !!t&&s?.sinifOgretmeniId===t};
const canEditBusSeats=()=>!uiTeacher()&&(uiUser().admin===true||!window.PermissionService||window.PermissionService.can('transport.seating.edit','edit'));
const canEditClassSeat=id=>uiTeacher()?classOwn(id):(uiUser().admin===true||!window.PermissionService||window.PermissionService.can('transport.classSeating.edit','edit')||window.PermissionService.can('people.classes','edit'));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const match=vals=>{const q=norm(query.trim());return!q||norm(vals.filter(Boolean).join(' ')).includes(q)};
const canEditServices=()=>!window.PermissionService||PermissionService.can('transport.services.edit','edit');
function requirePermission(key,min='edit'){if(window.PermissionService){PermissionService.require('module.transport',min==='edit'?'edit':'preview');PermissionService.require(key,min)}return true}
async function prepareLocal(){if(!window.SyncEngine||!window.COL)return;const defs={servisOturma:COL.servisOturma,sinifOturma:COL.sinifOturma},types=[];Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(100)}}
function shell(){return `<section class="ka-stack" data-transport-module><div class="ka-row ka-row--between"><div><h2>Taşıma</h2><p class="ka-muted">Servis, oturma planı ve resmî çıktılar cihaz verisiyle çalışır.</p></div><span id="transportCount" class="ka-badge"></span></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="transportSearch" type="search" placeholder="Servis, plaka, güzergâh veya sınıf ara…"></label><div id="transportContent" class="ka-stack"></div></section>`}
function serviceName(s){return s?.servisAdi||s?.guzergah||s?.plaka||'Servis'}
function services(){const students=arr('veliler'),list=arr('servisler').filter(s=>match([s.servisAdi,s.guzergah,s.plaka,s.soforAdi,s.soforTelefon])).sort((a,b)=>serviceName(a).localeCompare(serviceName(b),'tr')),cards=list.map(s=>{const n=students.filter(v=>v.servisId===s.id).length;return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row"><div class="ka-grow"><strong>${esc(serviceName(s))}</strong><div class="ka-muted">${esc([s.plaka,s.guzergah,s.soforAdi].filter(Boolean).join(' · '))}</div></div><span class="ka-badge">${n} öğrenci</span></div>${s.soforTelefon?`<div class="ka-muted">Sürücü telefonu: <a href="tel:${esc(s.soforTelefon)}">${esc(s.soforTelefon)}</a></div>`:''}<div class="ka-row ka-wrap">${canEditServices()?`<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-service-edit="${esc(s.id)}" data-ka-write="transport.services.edit">Düzenle</button><button class="ka-btn ka-btn--ghost ka-btn--sm" type="button" data-service-delete="${esc(s.id)}" data-ka-write="transport.services.edit">Sil</button>`:''}<button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-transport-denetim="${esc(s.id)}" data-ka-permission="transport.report.inspection" data-ka-min-level="preview">Denetim Formu</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-transport-takip="${esc(s.id)}" data-ka-permission="transport.report.monthly" data-ka-min-level="preview">Aylık Takip</button></div></div></article>`});return{count:list.length,html:`<div class="ka-row ka-row--between"><div><h3>Servisler</h3><div class="ka-muted">Güzergâh, plaka, sürücü ve öğrenci dağılımını yönetin.</div></div>${canEditServices()?'<button class="ka-btn" type="button" data-service-add data-ka-write="transport.services.edit">+ Yeni Servis</button>':''}</div>${cards.length?cards.join(''):'<div class="ka-empty">Servis kaydı bulunamadı.</div>'}`}}
function serviceModal(s={}){return `<div class="ka-modal-backdrop" data-service-modal><form class="ka-modal" id="serviceForm"><div class="ka-modal__header"><h2>${s.id?'Servisi Düzenle':'Yeni Servis'}</h2></div><div class="ka-modal__body ka-stack"><input type="hidden" name="id" value="${esc(s.id||'')}"><label class="ka-field"><span class="ka-field__label">Servis Adı</span><input name="servisAdi" value="${esc(s.servisAdi||'')}" placeholder="Örn. Balıbey Servisi"></label><label class="ka-field"><span class="ka-field__label">Güzergâh *</span><input name="guzergah" required value="${esc(s.guzergah||'')}" placeholder="Örn. Aydınlar - Balıbey"></label><label class="ka-field"><span class="ka-field__label">Plaka *</span><input name="plaka" required value="${esc(s.plaka||'')}" placeholder="23 ABC 123"></label><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Sürücü Adı Soyadı</span><input name="soforAdi" value="${esc(s.soforAdi||'')}"></label><label class="ka-field"><span class="ka-field__label">Sürücü Telefonu</span><input name="soforTelefon" inputmode="tel" value="${esc(s.soforTelefon||'')}"></label></div></div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" type="button" data-service-close>Vazgeç</button><button class="ka-btn" type="submit">Kaydet</button></div></form></div>`}
function openServiceModal(item={}){if(!canEditServices())return;document.querySelector('[data-service-modal]')?.remove();document.body.insertAdjacentHTML('beforeend',serviceModal(item));const modal=document.querySelector('[data-service-modal]');modal.querySelector('[data-service-close]')?.addEventListener('click',()=>modal.remove());modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});modal.querySelector('#serviceForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=String(fd.get('id')||''),veri={servisAdi:String(fd.get('servisAdi')||'').trim(),guzergah:String(fd.get('guzergah')||'').trim(),plaka:String(fd.get('plaka')||'').trim().toLocaleUpperCase('tr'),soforAdi:String(fd.get('soforAdi')||'').trim(),soforTelefon:String(fd.get('soforTelefon')||'').trim()};if(!veri.guzergah||!veri.plaka)return toast?.('Güzergâh ve plaka zorunludur.');try{await window.TasimaService.servisKaydet(id||null,veri);toast?.('Servis kaydedildi.');modal.remove();render()}catch(err){toast?.('Servis kaydedilemedi: '+(err?.message||err))}})}
async function deleteService(id){if(!canEditServices())return;const s=arr('servisler').find(x=>x.id===id);if(!s)return;const n=arr('veliler').filter(v=>v.servisId===id).length;if(n){toast?.(`Bu servise bağlı ${n} öğrenci var. Önce öğrencileri başka servise taşıyın.`);return}if(!confirm(`“${serviceName(s)}” silinsin mi?`))return;try{await window.TasimaService.servisSil(id);toast?.('Servis silindi.');render()}catch(err){toast?.('Servis silinemedi: '+(err?.message||err))}}
function currentPlan(servisId){return arr('servisOturma').find(p=>p.servisId===servisId||p.id===servisId)||null}
function busSeats(){const editable=canEditBusSeats(),list=arr('servisler').filter(s=>match([s.servisAdi,s.guzergah,s.plaka,currentPlan(s.id)?.sablon])).sort((a,b)=>serviceName(a).localeCompare(serviceName(b),'tr'));return listResult(list,s=>{const p=currentPlan(s.id),els=window.soPlanElementleriGetir?.(p||{},p?.sablon||'ducato')||[],st=window.soElementIstatistik?.(els)||{toplam:0,dolu:0};return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(serviceName(s))}</strong><div class="ka-muted">${esc(window.SO_SABLONLAR?.[p?.sablon]?.ad||p?.sablon||'Henüz plan yok')}</div></div><span class="ka-badge">${st.dolu}/${st.toplam||'—'}</span><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-bus-edit="${esc(s.id)}">${editable?'Düzenle':'Görüntüle'}</button></div></article>`},'Servis kaydı bulunamadı.')}
function classSeats(){const plans=arr('sinifOturma'),classes=arr('siniflar').filter(s=>match([s.ad,s.derslik,plans.find(p=>p.sinifId===s.id||p.id===s.id)?.sinifAdi])).sort((a,b)=>String(a.ad||'').localeCompare(String(b.ad||''),'tr',{numeric:true}));return listResult(classes,s=>{const p=plans.find(x=>x.sinifId===s.id||x.id===s.id),items=Array.isArray(p?.koltuklar)?p.koltuklar:Array.isArray(p?.yerlesim)?p.yerlesim:[],editable=canEditClassSeat(s.id);return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(s.ad||p?.sinifAdi||'Sınıf oturma planı')}</strong><div class="ka-muted">${esc(s.derslik||'')}${p?'':' · Henüz plan yok'}</div></div><span class="ka-badge">${items.length} yer</span><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-class-seat-open="${esc(s.id)}">${editable?'Düzenle':'Görüntüle'}</button></div></article>`},'Sınıf bulunamadı.')}
function listResult(list,renderer,empty){return{count:list.length,html:list.length?list.map(renderer).join(''):`<div class="ka-empty">${esc(empty)}</div>`}}
function studentOptions(servisId,selected){const list=arr('veliler').filter(v=>v.servisId===servisId).sort((a,b)=>String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr'));return `<option value="">Boş</option>`+list.map(v=>`<option value="${esc(v.id)}" ${v.id===selected?'selected':''}>${esc(v.ogrenciAdi||'Öğrenci')}</option>`).join('')}
function seatStudentName(e){return arr('veliler').find(v=>v.id===e.studentId)?.ogrenciAdi||e.properties?.studentName||''}
function openBusEditor(servisId){const s=arr('servisler').find(x=>x.id===servisId);if(!s)return;const p=currentPlan(servisId)||{},sablon=p.sablon||'ducato',elements=window.soPlanElementleriGetir?.(p,sablon)||[];editor={servisId,sablon,elements,editable:canEditBusSeats()};renderBusEditor(s)}
function renderBusEditor(s){if(!editor)return;const st=window.soElementIstatistik?.(editor.elements)||{toplam:0,dolu:0,bos:0,rezerve:0,doluluk:0},seats=editor.elements.filter(e=>e.type!=='sofor'&&e.visible!==false),editable=editor.editable;const templates=editable?Object.entries(window.SO_SABLONLAR||{}).map(([k,v])=>`<option value="${esc(k)}" ${k===editor.sablon?'selected':''}>${esc(v.ikon+' '+v.ad)}</option>`).join(''):'';const rows=seats.map((e,i)=>editable?`<div class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>Koltuk ${e.seatNumber||i+1}</strong><span class="ka-badge">${esc(e.properties?.konum||'')}</span></div><label class="ka-field"><span class="ka-field__label">Öğrenci</span><select data-seat-index="${editor.elements.indexOf(e)}">${studentOptions(editor.servisId,e.studentId)}</select></label><label class="ka-check"><input type="checkbox" data-seat-reserve="${editor.elements.indexOf(e)}" ${e.properties?.reserved?'checked':''}> Rezerve</label></div></div>`:`<div class="ka-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>Koltuk ${e.seatNumber||i+1}</strong><div class="ka-muted">${esc(seatStudentName(e)||'Boş')}</div></div><span class="ka-badge">${e.properties?.reserved&&!seatStudentName(e)?'Rezerve':esc(e.properties?.konum||'')}</span></div></div>`).join('');const ov=document.createElement('div');ov.id='transportBusEditor';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><strong>${esc(serviceName(s))}</strong><div class="ka-muted">Servis oturma planı · ${editable?'Düzenleme':'Salt okunur'}</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" data-bus-close type="button">Kapat</button></div><div class="ka-modal__body ka-stack">${editable?`<div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Araç şablonu</span><select id="busTemplateSelect">${templates}</select></label><div class="ka-card"><div class="ka-card__body"><strong>${st.dolu}/${st.toplam}</strong><div class="ka-muted">Dolu koltuk · %${st.doluluk}</div></div></div></div>`:`<div class="ka-card"><div class="ka-card__body ka-row ka-row--between"><div><strong>${esc(window.SO_SABLONLAR?.[editor.sablon]?.ad||editor.sablon||'Araç')}</strong><div class="ka-muted">Araç şablonu</div></div><span class="ka-badge">${st.dolu}/${st.toplam} dolu</span></div></div>`}<div class="ka-grid">${rows||'<div class="ka-empty">Bu şablonda koltuk yok.</div>'}</div></div>${editable?'<div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" data-bus-reset type="button">Şablonu Sıfırla</button><button class="ka-btn" data-bus-save type="button">Kaydet</button></div>':''}</section>`;document.body.appendChild(ov);bindEditor(ov,s)}
function closeEditor(){document.getElementById('transportBusEditor')?.remove();editor=null}
function newElements(sablon){const layout=window.SO_SABLONLAR?.[sablon]?.yerlesimUret?.()||[];return layout.map((yuva,idx)=>({id:'el_'+(idx+1),type:yuva.soforYani?'sofor':yuva.konum==='arka'?'arka-koltuk':'koltuk',seatNumber:yuva.soforYani?null:idx+1,studentId:null,row:yuva.sira,column:idx,locked:false,visible:yuva.aktif!==false,color:null,properties:{konum:yuva.konum||'',kapiSag:!!yuva.kapiSag,soforYani:!!yuva.soforYani,studentName:'',stop:'',note:'',reserved:false}}))}
function bindEditor(ov,s){ov.querySelector('[data-bus-close]').onclick=closeEditor;if(!editor?.editable)return;ov.querySelector('#busTemplateSelect').onchange=e=>{editor.sablon=e.target.value;editor.elements=newElements(editor.sablon);ov.remove();renderBusEditor(s)};ov.querySelectorAll('[data-seat-index]').forEach(sel=>sel.onchange=()=>{const i=Number(sel.dataset.seatIndex),el=editor.elements[i],student=arr('veliler').find(v=>v.id===sel.value);el.studentId=student?.id||null;el.properties={...(el.properties||{}),studentName:student?.ogrenciAdi||'',reserved:student?false:!!el.properties?.reserved}});ov.querySelectorAll('[data-seat-reserve]').forEach(ch=>ch.onchange=()=>{const i=Number(ch.dataset.seatReserve),el=editor.elements[i];el.properties={...(el.properties||{}),reserved:ch.checked}});ov.querySelector('[data-bus-reset]').onclick=()=>{editor.elements=newElements(editor.sablon);ov.remove();renderBusEditor(s)};ov.querySelector('[data-bus-save]').onclick=async()=>{if(!canEditBusSeats()){toast?.('Öğretmen kullanıcıları servis oturma planını yalnız görüntüleyebilir.');return}const b=ov.querySelector('[data-bus-save]');b.disabled=true;b.textContent='Kaydediliyor…';try{await window.ServisOturmaService.planElementsKaydet(editor.servisId,editor.sablon,editor.elements,false);toast?.('Oturma planı cihazda kaydedildi.');closeEditor();render()}catch(e){toast?.('Plan kaydedilemedi: '+(e?.message||e));b.disabled=false;b.textContent='Kaydet'}}}
async function openClassSeating(id){try{if(!window.SinifOturma?.ac)await window.AppLoader?.loadScript?.('js/modules/class-seating.js');if(!window.SinifOturma?.ac)throw new Error('Sınıf oturma motoru yüklenemedi.');return await window.SinifOturma.ac(id)}catch(e){console.error('[Transport/class-seating]',e);toast?.('Sınıf oturma planı açılamadı.');return false}}
function back(){if(document.getElementById('transportBusEditor')){closeEditor();return true}if(document.querySelector('[data-class-seating-overlay]')){window.SinifOturma?.kapat?.();return true}return false}
async function denetimAc(id){try{requirePermission('transport.report.inspection','preview');await window.TransportReports?.denetim?.(id)}catch(e){if(e?.code==='permission-denied')toast?.('Denetim Formu rolünüz için gizli.');else toast?.('Denetim formu hazırlanamadı: '+(e?.message||e))}}
function takipAc(id){try{requirePermission('transport.report.monthly','preview');window.TransportReports?.takipSec?.(id)}catch(e){if(e?.code==='permission-denied')toast?.('Aylık Takip rolünüz için gizli.');else toast?.('Takip çizelgesi açılamadı: '+(e?.message||e))}}
function render(){if(!mounted)return;const r=active==='busSeats'?busSeats():active==='classSeats'?classSeats():services();const out=document.getElementById('transportContent'),c=document.getElementById('transportCount');if(out)out.innerHTML=r.html;if(c)c.textContent=`${r.count} kayıt`;document.querySelector('[data-service-add]')?.addEventListener('click',()=>openServiceModal({}));document.querySelectorAll('[data-service-edit]').forEach(b=>b.onclick=()=>{const s=arr('servisler').find(x=>x.id===b.dataset.serviceEdit);if(s)openServiceModal(s)});document.querySelectorAll('[data-service-delete]').forEach(b=>b.onclick=()=>deleteService(b.dataset.serviceDelete));document.querySelectorAll('[data-bus-edit]').forEach(b=>b.onclick=()=>openBusEditor(b.dataset.busEdit));document.querySelectorAll('[data-class-seat-open]').forEach(b=>b.onclick=()=>openClassSeating(b.dataset.classSeatOpen));document.querySelectorAll('[data-transport-denetim]').forEach(b=>b.onclick=()=>denetimAc(b.dataset.transportDenetim));document.querySelectorAll('[data-transport-takip]').forEach(b=>b.onclick=()=>takipAc(b.dataset.transportTakip));window.PermissionService?.apply?.(document.getElementById('v2ModuleRoot')||document)}
function bind(){const s=document.getElementById('transportSearch');if(s)s.oninput=()=>{query=s.value;render()}}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.servisler','data.veliler','data.siniflar','data.servisOturma','data.sinifOturma'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}
function openPage(page,title=''){const allowed=['services','busSeats','classSeats'];if(!allowed.includes(page))return false;active=page;query='';const h=document.querySelector('[data-transport-module] > .ka-row h2');if(h&&title)h.textContent=title;render();return true}
function unmount(){mounted=false;closeEditor();document.querySelector('[data-service-modal]')?.remove();document.getElementById('transportReportPicker')?.remove();unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.TransportModule={mount,unmount,render,prepareLocal,openBusEditor,openClassSeating,openPage,back};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='transport')mount()});
})();
