/* Koruk Asistan v2 — Transport UI
   Servisler + resmî raporlar + servis oturma editörü + sınıf oturma özetleri.
   UI yalnız AppStore/IndexedDB okur; Firestore SyncEngine arka planındadır. */
(function(){
'use strict';if(window.TransportModule)return;
let active='services',query='',mounted=false,unsubs=[],editor=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c');
const arr=t=>{const v=window.AppStore?.data?.(t);return Array.isArray(v)?v:[]};
const match=vals=>{const q=norm(query.trim());return!q||norm(vals.filter(Boolean).join(' ')).includes(q)};
async function prepareLocal(){if(!window.SyncEngine||!window.COL)return;const defs={servisOturma:COL.servisOturma,sinifOturma:COL.sinifOturma},types=[];Object.entries(defs).forEach(([t,c])=>{if(c){SyncEngine.register(t,c);types.push(t)}});if(types.length){await SyncEngine.localHydrate(types);SyncEngine.schedule(100)}}
function shell(){return `<section class="ka-stack" data-transport-module><div class="ka-row ka-row--between"><div><h2>Taşıma</h2><p class="ka-muted">Servis, oturma planı ve resmî çıktılar cihaz verisiyle çalışır.</p></div><span id="transportCount" class="ka-badge"></span></div><div class="ka-tabs"><button class="ka-tab" data-transport-tab="services">Servisler</button><button class="ka-tab" data-transport-tab="busSeats">Servis Oturma</button><button class="ka-tab" data-transport-tab="classSeats">Sınıf Oturma</button></div><label class="ka-field"><span class="ka-field__label">Ara</span><input id="transportSearch" type="search" placeholder="Servis, plaka, güzergâh veya sınıf ara…"></label><div id="transportContent" class="ka-stack"></div></section>`}
function serviceName(s){return s?.servisAdi||s?.guzergah||s?.plaka||'Servis'}
function services(){const students=arr('veliler'),list=arr('servisler').filter(s=>match([s.servisAdi,s.guzergah,s.plaka,s.soforAdi,s.soforTelefon])).sort((a,b)=>serviceName(a).localeCompare(serviceName(b),'tr'));return listResult(list,s=>{const n=students.filter(v=>v.servisId===s.id).length;return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-stack"><div class="ka-row"><div class="ka-grow"><strong>${esc(serviceName(s))}</strong><div class="ka-muted">${esc([s.plaka,s.guzergah,s.soforAdi].filter(Boolean).join(' · '))}</div></div><span class="ka-badge">${n} öğrenci</span></div><div class="ka-row"><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-transport-denetim="${esc(s.id)}">Denetim Formu</button><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-transport-takip="${esc(s.id)}">Aylık Takip</button></div></div></article>`},'Servis kaydı bulunamadı.')}
function currentPlan(servisId){return arr('servisOturma').find(p=>p.servisId===servisId||p.id===servisId)||null}
function busSeats(){const list=arr('servisler').filter(s=>match([s.servisAdi,s.guzergah,s.plaka,currentPlan(s.id)?.sablon])).sort((a,b)=>serviceName(a).localeCompare(serviceName(b),'tr'));return listResult(list,s=>{const p=currentPlan(s.id),els=window.soPlanElementleriGetir?.(p||{},p?.sablon||'ducato')||[],st=window.soElementIstatistik?.(els)||{toplam:0,dolu:0};return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(serviceName(s))}</strong><div class="ka-muted">${esc(window.SO_SABLONLAR?.[p?.sablon]?.ad||p?.sablon||'Henüz plan yok')}</div></div><span class="ka-badge">${st.dolu}/${st.toplam||'—'}</span><button class="ka-btn ka-btn--secondary ka-btn--sm" type="button" data-bus-edit="${esc(s.id)}">Düzenle</button></div></article>`},'Servis kaydı bulunamadı.')}
function classSeats(){const classes=arr('siniflar'),plans=arr('sinifOturma').filter(p=>{const s=classes.find(x=>x.id===p.sinifId||x.id===p.id);return match([s?.ad,s?.derslik,p.sinifAdi])});return listResult(plans,p=>{const s=classes.find(x=>x.id===p.sinifId||x.id===p.id),items=Array.isArray(p.koltuklar)?p.koltuklar:Array.isArray(p.yerlesim)?p.yerlesim:[];return `<article class="ka-card ka-list-card"><div class="ka-card__body ka-row"><div class="ka-grow"><strong>${esc(s?.ad||p.sinifAdi||'Sınıf oturma planı')}</strong><div class="ka-muted">${esc(s?.derslik||'')}</div></div><span class="ka-badge">${items.length} yer</span></div></article>`},'Sınıf oturma planı bulunamadı.')}
function listResult(list,renderer,empty){return{count:list.length,html:list.length?list.map(renderer).join(''):`<div class="ka-empty">${esc(empty)}</div>`}}
function studentOptions(servisId,selected){const list=arr('veliler').filter(v=>v.servisId===servisId).sort((a,b)=>String(a.ogrenciAdi||'').localeCompare(String(b.ogrenciAdi||''),'tr'));return `<option value="">Boş</option>`+list.map(v=>`<option value="${esc(v.id)}" ${v.id===selected?'selected':''}>${esc(v.ogrenciAdi||'Öğrenci')}</option>`).join('')}
function openBusEditor(servisId){const s=arr('servisler').find(x=>x.id===servisId);if(!s)return;const p=currentPlan(servisId)||{},sablon=p.sablon||'ducato',elements=window.soPlanElementleriGetir?.(p,sablon)||[];editor={servisId,sablon,elements};renderBusEditor(s)}
function renderBusEditor(s){if(!editor)return;const st=window.soElementIstatistik?.(editor.elements)||{toplam:0,dolu:0,bos:0,rezerve:0,doluluk:0},templates=Object.entries(window.SO_SABLONLAR||{}).map(([k,v])=>`<option value="${esc(k)}" ${k===editor.sablon?'selected':''}>${esc(v.ikon+' '+v.ad)}</option>`).join(''),seats=editor.elements.filter(e=>e.type!=='sofor'&&e.visible!==false);const rows=seats.map((e,i)=>`<div class="ka-card"><div class="ka-card__body ka-stack"><div class="ka-row ka-row--between"><strong>Koltuk ${e.seatNumber||i+1}</strong><span class="ka-badge">${esc(e.properties?.konum||'')}</span></div><label class="ka-field"><span class="ka-field__label">Öğrenci</span><select data-seat-index="${editor.elements.indexOf(e)}">${studentOptions(editor.servisId,e.studentId)}</select></label><label class="ka-check"><input type="checkbox" data-seat-reserve="${editor.elements.indexOf(e)}" ${e.properties?.reserved?'checked':''}> Rezerve</label></div></div>`).join('');const ov=document.createElement('div');ov.id='transportBusEditor';ov.className='ka-modal-backdrop';ov.innerHTML=`<section class="ka-modal"><div class="ka-modal__header"><div><strong>${esc(serviceName(s))}</strong><div class="ka-muted">Servis oturma planı</div></div><button class="ka-btn ka-btn--secondary ka-btn--sm" data-bus-close type="button">Kapat</button></div><div class="ka-modal__body ka-stack"><div class="ka-grid"><label class="ka-field"><span class="ka-field__label">Araç şablonu</span><select id="busTemplateSelect">${templates}</select></label><div class="ka-card"><div class="ka-card__body"><strong>${st.dolu}/${st.toplam}</strong><div class="ka-muted">Dolu koltuk · %${st.doluluk}</div></div></div></div><div class="ka-grid">${rows||'<div class="ka-empty">Bu şablonda koltuk yok.</div>'}</div></div><div class="ka-modal__footer"><button class="ka-btn ka-btn--secondary" data-bus-reset type="button">Şablonu Sıfırla</button><button class="ka-btn" data-bus-save type="button">Kaydet</button></div></section>`;document.body.appendChild(ov);bindEditor(ov,s)}
function closeEditor(){document.getElementById('transportBusEditor')?.remove();editor=null}
function newElements(sablon){const layout=window.SO_SABLONLAR?.[sablon]?.yerlesimUret?.()||[];return layout.map((yuva,idx)=>({id:'el_'+(idx+1),type:yuva.soforYani?'sofor':yuva.konum==='arka'?'arka-koltuk':'koltuk',seatNumber:yuva.soforYani?null:idx+1,studentId:null,row:yuva.sira,column:idx,locked:false,visible:yuva.aktif!==false,color:null,properties:{konum:yuva.konum||'',kapiSag:!!yuva.kapiSag,soforYani:!!yuva.soforYani,studentName:'',stop:'',note:'',reserved:false}}))}
function bindEditor(ov,s){ov.querySelector('[data-bus-close]').onclick=closeEditor;ov.querySelector('#busTemplateSelect').onchange=e=>{editor.sablon=e.target.value;editor.elements=newElements(editor.sablon);ov.remove();renderBusEditor(s)};ov.querySelectorAll('[data-seat-index]').forEach(sel=>sel.onchange=()=>{const i=Number(sel.dataset.seatIndex),el=editor.elements[i],student=arr('veliler').find(v=>v.id===sel.value);el.studentId=student?.id||null;el.properties={...(el.properties||{}),studentName:student?.ogrenciAdi||'',reserved:student?false:!!el.properties?.reserved};});ov.querySelectorAll('[data-seat-reserve]').forEach(ch=>ch.onchange=()=>{const i=Number(ch.dataset.seatReserve),el=editor.elements[i];el.properties={...(el.properties||{}),reserved:ch.checked};});ov.querySelector('[data-bus-reset]').onclick=()=>{editor.elements=newElements(editor.sablon);ov.remove();renderBusEditor(s)};ov.querySelector('[data-bus-save]').onclick=async()=>{const b=ov.querySelector('[data-bus-save]');b.disabled=true;b.textContent='Kaydediliyor…';try{await window.ServisOturmaService.planElementsKaydet(editor.servisId,editor.sablon,editor.elements,false);toast?.('Oturma planı cihazda kaydedildi.');closeEditor();render();}catch(e){toast?.('Plan kaydedilemedi: '+(e?.message||e));b.disabled=false;b.textContent='Kaydet';}}}
async function denetimAc(id){try{await window.TransportReports?.denetim?.(id)}catch(e){toast?.('Denetim formu hazırlanamadı: '+(e?.message||e))}}
function takipAc(id){try{window.TransportReports?.takipSec?.(id)}catch(e){toast?.('Takip çizelgesi açılamadı: '+(e?.message||e))}}
function render(){if(!mounted)return;document.querySelectorAll('[data-transport-tab]').forEach(b=>b.classList.toggle('active',b.dataset.transportTab===active));const r=active==='busSeats'?busSeats():active==='classSeats'?classSeats():services();const out=document.getElementById('transportContent'),c=document.getElementById('transportCount');if(out)out.innerHTML=r.html;if(c)c.textContent=`${r.count} kayıt`;document.querySelectorAll('[data-bus-edit]').forEach(b=>b.onclick=()=>openBusEditor(b.dataset.busEdit));document.querySelectorAll('[data-transport-denetim]').forEach(b=>b.onclick=()=>denetimAc(b.dataset.transportDenetim));document.querySelectorAll('[data-transport-takip]').forEach(b=>b.onclick=()=>takipAc(b.dataset.transportTakip))}
function bind(){document.querySelectorAll('[data-transport-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.transportTab;render()});const s=document.getElementById('transportSearch');if(s)s.oninput=()=>{query=s.value;render()}}
function subscribe(){unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[];['data.servisler','data.veliler','data.siniflar','data.servisOturma','data.sinifOturma'].forEach(p=>{const u=AppStore?.subscribe?.(p,()=>requestAnimationFrame(render));if(u)unsubs.push(u)})}
async function mount(root=document.getElementById('v2ModuleRoot')){if(!root)return false;mounted=true;root.innerHTML=shell();bind();subscribe();await prepareLocal();render();return true}
function unmount(){mounted=false;closeEditor();document.getElementById('transportReportPicker')?.remove();unsubs.forEach(f=>{try{f()}catch(_){}});unsubs=[]}
window.TransportModule={mount,unmount,render,prepareLocal,openBusEditor};window.addEventListener('koruk:module-ready',e=>{if(e.detail?.name==='transport')mount()});
})();